[database]
CBSDBName=crz_cust_scorecard
EZDBName=ez_dev1
RCRRDBName=prod_rcrr_dev1
TSZDBName=tsz
TSZRMADBName=tsz_rma
TSZRRAPDBName=tsz_b9xf_rrap

[connection]
Server=sddsvrwm369.scglobaluat.aduat.scotiacapital.com
KeyTab=/app/dev_bbcx_cbs_appid/.keytab/dev_bbcx_cbs_appid.keytab
KeyTabPrincipal=dev_bbcx_cbs_appid
KeyTabPrincipalDomain=dev_bbcx_cbs_appid@SCGLOBALUAT.ADUAT.SCOTIACAPITAL.COM
JDBCConn=jdbc:hive2://sddsvrwm369.scglobaluat.aduat.scotiacapital.com:2181,sddsvrwm367.scglobaluat.aduat.scotiacapital.com:2181,sddsvrwm368.scglobaluat.aduat.scotiacapital.com:2181/default;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2


[table]
TblJobInfo=cbs_job_info
TblJobDepInfo=cbs_job_dependent_info
TblAuditLog=risk_cbs_audit_job_log
TblDataQuality=cbs_data_quality_check_info
TblDataQualityLog=cbs_data_quality_check_log

[system]
LoggingLevel=DEBUG

