[database]
CBSDBName=crz_cust_scorecard
EZDBName=ez1
RCRRDBName=prod_rcrr1
TSZDBName=tsz
TSZRMADBName=tsz_rma
TSZRRAPDBName=tsz_b9xf_rrap

[connection]
Server=sdpsvrwm0124.scglobal.ad.scotiacapital.com
KeyTab=/app/bbcx_cbs_appid/.keytab/bbcx_cbs_appid.keytab
KeyTabPrincipal=bbcx_cbs_appid
KeyTabPrincipalDomain=bbcx_cbs_appid@SCGLOBAL.AD.SCOTIACAPITAL.COM
JDBCConn=jdbc:hive2://sdpsvrwm0124.scglobal.ad.scotiacapital.com:2181,sdpsvrwm0128.scglobal.ad.scotiacapital.com:2181,sdpsvrwm0162.scglobal.ad.scotiacapital.com:2181,sdpsvrwm0123.scglobal.ad.scotiacapital.com:2181,sdpsvrwm0127.scglobal.ad.scotiacapital.com:2181/default;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2


[table]
TblJobInfo=cbs_job_info
TblJobDepInfo=cbs_job_dependent_info
TblAuditLog=risk_cbs_audit_job_log
TblDataQuality=cbs_data_quality_check_info
TblDataQualityLog=cbs_data_quality_check_log

[system]
LoggingLevel=DEBUG



