[database]
CBSDBName=crz_cust_scorecard
EZDBName=ez1
RCRRDBName=prod_rcrr1
TSZDBName=tsz
TSZRMADBName=tsz_rma
TSZRRAPDBName=tsz_b9xf_rrap

[connection]
Server=sdusvrwm0125.scglobaluat.aduat.scotiacapital.com
KeyTab=/app/bbcx_cbs_appid/.keytab/bbcx_cbs_appid.keytab
KeyTabPrincipal=bbcx_cbs_appid
KeyTabPrincipalDomain=bbcx_cbs_appid@SCGLOBALUAT.ADUAT.SCOTIACAPITAL.COM
JDBCConn=jdbc:hive2://sdusvrwm0125.scglobaluat.aduat.scotiacapital.com:2181,sdusvrwm0126.scglobaluat.aduat.scotiacapital.com:2181,sdusvrwm0127.scglobaluat.aduat.scotiacapital.com:2181/default;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2;principal=hive/_HOST@SCGLOBALUAT.ADUAT.SCOTIACAPITAL.COM



[table]
TblJobInfo=cbs_job_info
TblJobDepInfo=cbs_job_dependent_info
TblAuditLog=risk_cbs_audit_job_log
TblDataQuality=cbs_data_quality_check_info
TblDataQualityLog=cbs_data_quality_check_log

[system]
LoggingLevel=DEBUG



