use crz_cust_scorecard;
drop table if exists CBS_ACCT_BASE;
CREATE EXTERNAL TABLE CBS_ACCT_BASE(
    CUST_CID                    VARCHAR(40),
    INSRT_PROCESS_TMSTMP        TIMESTAMP,
    OP_FIELD                    VARCHAR(1000),
    PRODUCT_TYPE                VARCHAR(30),
    ACCOUNT_NUM                 VARCHAR(30),
    PRIMARY_CUST_FLAG           VARCHAR(1),
    RELATION_CODE               VARCHAR(10),
    EMPLOYEE_IND                VARCHAR(1),
    MORT_NUM                    VARCHAR(30),
    LOAN_NUM                    VARCHAR(30),
    FILE_DATE                   DATE,
    PROCESS_DATE                DATE,
    BASEL_ACCT_ID               VARCHAR(30),
    PRD_ID_SPL                  VARCHAR(30),
    COMM_FLAG_SPL               VARCHAR(1),
    OS_BAL_AMT_SPL              DECIMAL(18, 2),
    RECD_STAT_CD_SPL            VARCHAR(20),
    PAID_OFF_DATE_MORT          DATE,
    CURRENT_BAL_MORT            DECIMAL(18, 2),
    COMM_TP_CD_MORT             VARCHAR(25),
    TOTAL_SUSPENSE_MORT         DECIMAL(18, 2),
    OS_BAL_AMT_MORT             DECIMAL(18, 2),
    PD_OFF_F_MORT               VARCHAR(1),
    MTH_IN_ARRS_CNT_MORT        INT,
    LIFE_INSUR_CD_MORT          VARCHAR(20),
    SOURCE_CD                   VARCHAR(20),
    ACCT_STAT_CD                VARCHAR(20),
    CR_LMT_AMT                  DECIMAL(18, 2),
    TOT_NEW_BAL_AMT             DECIMAL(18, 2),
    NON_ACCRL_DT                DATE,
    WRITE_OFF_DT                DATE,
    ACCT_CLS_RSN_CD             VARCHAR(20),
    BLOCKED_IND                 VARCHAR(1),
    DECEASED_IND                VARCHAR(1),
    STOLEN_IND                  VARCHAR(1),
    NUM_OF_LEND_PRODS           INT,
    CID_NUM                     VARCHAR(30),
    MORT_IND                    VARCHAR(1),
    SPL_IND                     VARCHAR(1),
    REV_IND                     VARCHAR(1),
    SSL_IND                     VARCHAR(1),
    LEND_PRODS_CUR              INT,
    LEND_PRODS_CLSD             INT,
    LEND_PRODS_BNKRPT           INT,
    LEND_PRODS_DEF              INT,
    LEND_PRODS_CHRG_OFF         INT,
    LEND_PRODS_WRT_OFF          INT,
    LEND_PRODS_COMM             INT,
    LEND_PRODS_COMM_CUR         INT,
    LEND_PRODS_COMM_CLSD        INT,
    LEND_PRODS_COMM_DEF         INT,
    LEND_PRODS_COMM_CHRG_OFF    INT,
    LEND_PRODS_COMM_WRT_OFF     INT,
    PRIVATE_BANK_IND            VARCHAR(1),
    CORP_COMM_EXCL              VARCHAR(1),
    STAFF_EXCL                  VARCHAR(1),
    DEFAULT_DATE                DATE,
    DEFAULT_BAL                 DECIMAL(18, 2),
    DEFAULT_IND                 VARCHAR(1),
    MODEL_EXCL                  VARCHAR(1),
    PIT_STATUS                  VARCHAR(10),
    DAYS_DLQNT                  INT,
    NON_LEND_PRODS_ACT          INT,
    NON_LEND_PRODS_PEND_CLSD    INT,
    NON_LEND_PRODS_DOR          INT,
    NON_LEND_PRODS_INACT        INT,
    NON_LEND_PRODS_PND          INT,
    NON_LEND_PRODS_STOLN        INT,
    NON_LEND_PRODS_CLSD         INT,
    NON_LEND_PRODS_WRT_OFF      INT,
    CUST_TYPE                   VARCHAR(20),
    CUST_STATUS                 VARCHAR(20),
    CUST_DEP_ONLY_FLG           VARCHAR(1),
    CUST_DECEASED_IND           VARCHAR(1),
    CUST_PRIME_IND              VARCHAR(1),
    CUST_SECONDARY_IND          VARCHAR(1),
    CUST_NOACCT_EXCL            VARCHAR(1),
    CUST_BANKRUPTCY_EXCL        VARCHAR(1),
    CUST_UNDER_AGE_EXCL         VARCHAR(1)
)
PARTITIONED BY( EFF_DT DATE, DATE_TYPE VARCHAR(20))
CLUSTERED BY (CUST_CID, ACCOUNT_NUM) SORTED BY (CUST_CID ASC, ACCOUNT_NUM ASC) INTO 60 BUCKETS
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/CBS_ACCT_BASE'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

