use crz_cust_scorecard;
drop table if exists RISK_CUST_ACCT_RLTNP;
CREATE EXTERNAL TABLE RISK_CUST_ACCT_RLTNP(
    CUST_CID                   VARCHAR(40),
    ACCT_NUM                   VARCHAR(80),
    INSRT_PROCESS_TMSTMP       TIMESTAMP,
    OP_FIELD                   VARCHAR(1000),
    CUST_ACCT_RLTNP_TYPE_CD    VARCHAR(10),
    PRIMARY_ACCT_HOLDER_F      VARCHAR(1)
)
PARTITIONED BY( EFF_DT DATE, DATE_TYPE VARCHAR(30), SRC_SYS_CD VARCHAR(20))
CLUSTERED BY (CUST_CID, ACCT_NUM) SORTED BY (CUST_CID ASC, ACCT_NUM ASC) INTO 60 BUCKETS
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_CUST_ACCT_RLTNP'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

