DROP VIEW FRG_USER_DATA.TNG_LGDD_SEGMENTATION_IFRS_V;
CREATE VIEW FRG_USER_DATA.TNG_LGDD_SEGMENTATION_IFRS_V AS
SELECT
    ACCOUNT_ID,
    MONTH_END_DT,
    "RECOVERY",
    INDIRECT_COST,
    FINAL_COST,
    LGD,
    LGD_COSTS,
    LGD_COSTS_CAP_100,
    LGD_COSTS_CAP_150,
    ACCRUED_INTEREST_AMT,
    END_PRINCIPAL_BALANCE,
    MONTHS_IN_DEFAULT,
    CLOSE_DT,
    LTV_TERANET,
    INS_ID_GROUP,
    BALANCE_INTEREST,
    EXCL,
    LGDD_SEGMENT,
    LGD_BKUP,
    LGD_COSTS_BKUP,
    LGD_COSTS_CAP_100_BKUP,
    LGD_COSTS_CAP_150_BKUP
FROM
    FRG_USER_DATA.TNG_LGDD_SEGMENTATION;


DROP VIEW FRG_USER_DATA.TNG_LGD_ND_SEGMENTATION_IFRS_V;
CREATE VIEW FRG_USER_DATA.TNG_LGD_ND_SEGMENTATION_IFRS_V AS
SELECT
    ACCOUNT_ID,
    MONTH_END_DT,
    END_PRINCIPAL_BALANCE,
    DEFAULT_IND,
    CLOSE_DT,
    NEW_DEF_IND,
    NEW_DEFAULT_IND,
    WRITE_OFF_MONTH,
    WRITE_OFF_IND,
    WRITE_OFF_AMT,
    FINAL_DEFAULT_IND,
    TRADES_STSFCT_CNTSLP6M,
    TRADES_ACTIVE_UTIL_PCTMAX12M,
    DEROGATORY_PUBLIC_REC_CNT,
    COLLECTIONS_CNT,
    BANKRUPTCIES_CNT,
    CREDIT_TRBLE_BNKRPTCY_COLL_DER,
    INS_ID_GROUP,
    DAYS_ARREARS_CNT,
    NSF_YTD_CNT,
    EVER_30_CNT,
    REMAIN_AMORT2,
    PROP_VAL_NEW,
    LTV_TERANET,
    PROVIDER,
    MODEL_EXCL,
    SEGMENT
FROM
    FRG_USER_DATA.TNG_LGD_ND_SEGMENTATION;


DROP VIEW FRG_USER_DATA.TNG_PD_SEGM_FINAL_IFRS_V;
CREATE VIEW FRG_USER_DATA.TNG_PD_SEGM_FINAL_IFRS_V AS
SELECT
    ACCOUNT_ID,
    MONTH_END_DT,
    END_PRINCIPAL_BALANCE,
    DEFAULT_IND,
    CLOSE_DT,
    NEW_DEF_IND,
    NEW_DEFAULT_IND,
    WRITE_OFF_MONTH,
    WRITE_OFF_IND,
    WRITE_OFF_AMT,
    FINAL_DEFAULT_IND,
    TRADES_STSFCT_CNTSLP6M,
    TRADES_ACTIVE_UTIL_PCTMAX12M,
    DEROGATORY_PUBLIC_REC_CNT,
    COLLECTIONS_CNT,
    BANKRUPTCIES_CNT,
    CREDIT_TRBLE_BNKRPTCY_COLL_DER,
    INS_ID_GROUP,
    DAYS_ARREARS_CNT,
    NSF_YTD_CNT,
    EVER_30_CNT,
    REMAIN_AMORT2,
    PROP_VAL_NEW,
    LTV_TERANET,
    MODEL_EXCL,
    SCORECARD_POINTS,
    SCR_DAYS_ARREARS_CNT,
    SCR_EVER_30_CNT,
    SCR_LTV_TERANET,
    SCR_NSF_YTD_CNT,
    SCR_TRADES_ACTIVE_UTIL_PCTMAX12M,
    SCR_TRADES_STSFCT_CNTSLP6M,
    SCR_REMAIN_AMORT2,
    SCR_CREDIT_TRBLE_BNKRPTCY_COLL_D,
    SCR_INS_ID_GROUP,
    PD_SEGMENT,
    SEGMENT
FROM
    FRG_USER_DATA.TNG_PD_SEGMENTATION_FINAL;


DROP VIEW EDRTLRP1D.BASEL_SEG_IFRS_V;
CREATE VIEW EDRTLRP1D.BASEL_SEG_IFRS_V AS
SELECT
    BASEL_SEG_ID,
    BASEL_MODEL_ID,
    BASEL_SEG_NM,
    BASEL_SEG_DESC,
    SEG_CRTRIA_DESC,
    SEG_NUM,
    SEG_VER,
    SEG_ST_DT,
    SEG_END_DT,
    BIN_CRTRIA_SQL_CD_STRG,
    SRC_SYS_CD,
    INSRT_PROCESS_TMSTMP,
    UPDT_PROCESS_TMSTMP
FROM
    EDRTLRP1D.BASEL_SEG;


DROP VIEW EDRTLRP1D.BASEL_MODEL_REL_IFRS_V;
CREATE VIEW EDRTLRP1D.BASEL_MODEL_REL_IFRS_V AS
SELECT
    BASEL_MODEL_REL.BASEL_MODEL_REL_ID,
    BASEL_MODEL_REL.BASEL_SEG_ID,
    BASEL_MODEL_REL.BASEL_MODEL_SCORECRD_HDR_ID,
    BASEL_MODEL_REL.RPTG_USAGE_F,
    BASEL_MODEL_REL.SCORECRD_VER,
    BASEL_MODEL_REL.SEG_VER,
    BASEL_MODEL_REL.INSRT_PROCESS_TMSTMP,
    BASEL_MODEL_REL.UPDT_PROCESS_TMSTMP
FROM
    EDRTLRP1D.BASEL_MODEL_REL AS BASEL_MODEL_REL;