DROP TABLE EDRTLRP1D.RPTG_EXPSR_CL_DIM IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.RPTG_EXPSR_CL_DIM (
		EXPSR_CL_ID INTEGER NOT NULL,
		NCR_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		NCR_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		FRS_CD VARCHAR(10 OCTETS),
		BCAR_SCHED_NUM VARCHAR(10 OCTETS), 
		CCAR_EXPSR_CL_NM VARCHAR(20 OCTETS), 
		EFF_FROM_YR_MTH CHAR(6 OCTETS), 
		EFF_TO_YR_MTH CHAR(6 OCTETS), 
		CRNT_F CHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (NCR_EXPSR_CL_KEY_VAL, EFF_FROM_YR_MTH);  COMMIT;	
	
DROP TABLE EDRTLRP1D.RPTG_PRD_LKP_KS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.RPTG_PRD_LKP_KS (
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		PRD_CD VARCHAR(10 OCTETS), 
		SUB_PRD_CD VARCHAR(10 OCTETS), 
		REVISED_EXPSR_OV_125K_F VARCHAR(1 OCTETS), 
		HELOC_F VARCHAR(1 OCTETS), 
		BASEL_PRD_CD VARCHAR(10 OCTETS), 
		BASEL_PRD_TP_CD VARCHAR(10 OCTETS), 
		ASST_CL_NUM SMALLINT, 
		ASST_CL_DESC VARCHAR(255 OCTETS), 
		PRD_ID VARCHAR(10 OCTETS), 
		PORTFL_NM VARCHAR(50 OCTETS), 
		PRD_NM VARCHAR(50 OCTETS), 
		SUB_PRD_NM VARCHAR(255 OCTETS), 
		BASEL_SUB_PRD_NM VARCHAR(255 OCTETS), 
		BCAR_SCHED_NUM VARCHAR(3 OCTETS), 
		NCR_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		CCAR_BASEL_PRD_TP_NM VARCHAR(50 OCTETS), 
		CCAR_SHT_NM VARCHAR(4 OCTETS), 
		ACCT_CRNCY_CD VARCHAR(10 OCTETS), 
		RT_KEY_VAL VARCHAR(4 OCTETS), 
		BASEL_PRD_NM VARCHAR(50 OCTETS), 
		BASEL_PRD_ABR VARCHAR(50 OCTETS), 
		SCRTY_TP_CD VARCHAR(50 OCTETS), 
		PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		PD_BAND_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		NCR_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		DT4_RISK_RT_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (SRC_SYS_CD, PRD_CD, SUB_PRD_CD, REVISED_EXPSR_OV_125K_F, HELOC_F, BASEL_PRD_CD, EFF_FROM_YR_MTH); COMMIT; 
	
DROP TABLE EDRTLRP1D.RPTG_PRD_LKP_MOR IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.RPTG_PRD_LKP_MOR (
		SOURCE_SYSTEM_CODE VARCHAR(7 OCTETS), 
		BASEL_MORTGAGE_INSURER_GROUP_DES VARCHAR(39 OCTETS), 
		BULK_INDICATOR VARCHAR(1 OCTETS), 
		BASEL_PRODUCT_CODE VARCHAR(7 OCTETS), 
		BASEL_PRODUCT_TYPE_CODE VARCHAR(10 OCTETS), 
		ASSET_CLASS_NUMBER DOUBLE, 
		ASSET_CLASS_DESCRIPTION VARCHAR(19 OCTETS), 
		PRODUCT_ID VARCHAR(3 OCTETS), 
		PORTFOLIO_NAME VARCHAR(8 OCTETS), 
		PRODUCT_NAME VARCHAR(14 OCTETS), 
		SUB_PRODUCT_NAME VARCHAR(24 OCTETS), 
		BASEL_SUB_PRODUCT_NAME VARCHAR(46 OCTETS), 
		BCAR_SCHEDULE_NUMBER DOUBLE, 
		NCR_EXPOSURE_CLASS_KEY_VALUE VARCHAR(4 OCTETS), 
		CCAR_BASEL_PRODUCT_TYPE_NAME VARCHAR(18 OCTETS), 
		CCAR_SHORT_NAME VARCHAR(8 OCTETS), 
		CURRENCY_OF_ACCOUNT VARCHAR(3 OCTETS), 
		BASEL_PRODUCT VARCHAR(31 OCTETS), 
		BASEL_PROD_ABBR VARCHAR(23 OCTETS), 
		SECURITY_TYPE VARCHAR(9 OCTETS), 
		PD_BAND_EXPOSURE_CLASS_KEY_VALUE VARCHAR(4 OCTETS), 
		PD_BAND_EXPOSURE_CLASS_DESCRIPTI VARCHAR(9 OCTETS), 
		NCR_EXPOSURE_CLASS_DESCRIPTION VARCHAR(23 OCTETS),
		DT4_RISK_RT_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (SOURCE_SYSTEM_CODE, BASEL_MORTGAGE_INSURER_GROUP_DES, BULK_INDICATOR, EFF_FROM_YR_MTH); COMMIT;
	
DROP TABLE EDRTLRP1D.RPTG_PRD_LKP_SPL IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.RPTG_PRD_LKP_SPL (
		SRC_SYS_CD VARCHAR(10 OCTETS) NOT NULL, 
		PRD_ID VARCHAR(10 OCTETS) NOT NULL, 
		PRD_CD VARCHAR(60 OCTETS), 
		BASEL_PRD_CD VARCHAR(10 OCTETS), 
		BASEL_PRD_TP_CD VARCHAR(20 OCTETS), 
		ASST_CL_NUM SMALLINT, 
		ASST_CL_DESC VARCHAR(255 OCTETS), 
		PORTFL_NM VARCHAR(50 OCTETS), 
		PRD_NM VARCHAR(50 OCTETS), 
		SUB_PRD_NM VARCHAR(255 OCTETS), 
		BASEL_SUB_PRD_NM VARCHAR(255 OCTETS), 
		BCAR_SCHED_NUM VARCHAR(3 OCTETS), 
		NCR_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		CCAR_BASEL_PRD_TP_NM VARCHAR(50 OCTETS), 
		CCAR_SHT_NM VARCHAR(10 OCTETS), 
		CRNCY_OF_ACCT VARCHAR(10 OCTETS), 
		NCR_RT_KEY_VAL VARCHAR(4 OCTETS), 
		BASEL_PRD VARCHAR(50 OCTETS), 
		BASEL_PRD_ABR VARCHAR(50 OCTETS), 
		SCRTY_TP VARCHAR(50 OCTETS), 
		PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		PD_BAND_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		NCR_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		DT4_RISK_RT_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (SRC_SYS_CD, PRD_ID, EFF_FROM_YR_MTH); COMMIT;
	
/******************************************************************************************************************************************/

DROP TABLE EDRTLRP1D.CCAR_PROVISIONS_MAPPING IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.CCAR_PROVISIONS_MAPPING (
		PROVISIONS_PRODUCT VARCHAR(30 OCTETS), 
		BASEL_PRODUCT_TYPE VARCHAR(30 OCTETS), 
		SECURITY_TYPE_DESC VARCHAR(30 OCTETS), 
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROVISIONS_PRODUCT, BASEL_PRODUCT_TYPE, SECURITY_TYPE_DESC, EFF_FROM_YR_MTH); COMMIT;

DROP TABLE EDRTLRP1D.POST_ECL_PROVISIONS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.POST_ECL_PROVISIONS (
		MTH_TM_ID DOUBLE, 
		PRODUCTS VARCHAR(19 OCTETS), 
		SECURITY_TYPE_DESC VARCHAR(9 OCTETS), 
		ECL_DRAWN_1_ADJ DOUBLE, 
		ECL_DRAWN_2_ADJ DOUBLE, 
		ECL_DRAWN_3_ADJ DOUBLE, 
		ECL_UNDRAWN_1_ADJ DOUBLE, 
		ECL_UNDRAWN_2_ADJ DOUBLE, 
		ECL_UNDRAWN_3_ADJ DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PRODUCTS, SECURITY_TYPE_DESC, MTH_TM_ID); COMMIT;

DROP TABLE EDRTLRP1D.DT4_RW_INSURER IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RW_INSURER (
		NAME VARCHAR(4 OCTETS), 
		RW_INSURER DOUBLE, 
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (NAME, EFF_FROM_YR_MTH); COMMIT;
	
/******************************************************************************************************************************************/

DROP TABLE EDRTLRP1D.DT4_RPTG_DRVD_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RPTG_DRVD_VARS (
		MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NUM VARCHAR(50 OCTETS), 
		PIT_STAT_CD VARCHAR(5 OCTETS), 
		PD_BAND CHAR(10 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		PD_BASEL_SEG_NUM INTEGER, 
		DT4_PD_SEG_KEY_VAL CHAR(4 OCTETS), 
		DT4_PD_SEG_DESC VARCHAR(255 OCTETS), 
		LGD_BASEL_SEG_NUM INTEGER, 
		DT4_LGD_SEG_KEY_VAL CHAR(4 OCTETS), 
		DT4_LGD_SEG_DESC VARCHAR(255 OCTETS), 
		EAD_BASEL_SEG_NUM INTEGER, 
		DT4_EAD_SEG_KEY_VAL CHAR(4 OCTETS), 
		DT4_EAD_SEG_DESC VARCHAR(255 OCTETS),
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MTH_TM_ID); COMMIT;
	
/******************************************************************************************************************************************/

DROP TABLE EDRTLRP1D.DT4_RT18_EST_CCAR_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT18_EST_CCAR_VARS (
		BASEL_ACCT_ID BIGINT, 
		MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		CCAR_BASEL_PRD_TP_NM VARCHAR(50 OCTETS), 
		BASEL_PRODUCT_TYPE VARCHAR(50 OCTETS), 
		PERIOD_IND VARCHAR(4 OCTETS), 
		PD_BAND VARCHAR(10 OCTETS), 
		EAD_INCL INTEGER, 
		BASEL_GRP VARCHAR(50 OCTETS), 
		PD_VALUE DECIMAL(29 , 8), 
		RW_INSURER DOUBLE, 
		ADJUSTED_OS_BAL_AMT DOUBLE, 
		UNADJUSTED_ADD_ON_BAL_AMT DOUBLE, 
		BEFORE_ZERO_NET_UNDRAWN_AMT DOUBLE, 
		AF_ZERO_NET_UNDRAWN_AMT DOUBLE, 
		PD_FINAL_RPTG_RTO DOUBLE, 
		LGD_FINAL_RPTG_RTO DECIMAL(29 , 8), 
		EAD_FINAL_RPTG_RTO DOUBLE, 
		DLGD_RPTG_RTO DECIMAL(29 , 8), 
		EXPOSURE_DRAWN DOUBLE, 
		UNDRAWN DOUBLE, 
		EXPSR_DRAWN_PRIOR_SECUR DOUBLE, 
		ECL_DRAWN_3 DECIMAL(23 , 2), 
		ECL_UNDRAWN_3 DECIMAL(23 , 2), 
		ECL_DRAWN_POSTSEC_3 DECIMAL(23 , 12), 
		ECL_POST_ADJ_DRAWN_3 DOUBLE, 
		ECL_POST_ADJ_UNDRAWN_3 DOUBLE, 
		ECL_POST_ADJ_DRAWN_POSTSEC_3 DOUBLE,
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MTH_TM_ID); COMMIT; 
	
DROP TABLE EDRTLRP1D.DT4_RT18_EST_ER_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT18_EST_ER_VARS (
		BASEL_ACCT_ID BIGINT, 
		MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		CCAR_BASEL_PRD_TP_NM VARCHAR(50 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		PD_BAND VARCHAR(10 OCTETS), 
		PD_VALUE DECIMAL(30 , 8), 
		EAD_INCL INTEGER, 
		EXPOSURE_DRAWN DOUBLE, 
		NETEAD_UNDRAWN DOUBLE, 
		EL_DRAWNPCT_FOR_DEFAULTED DOUBLE, 
		EAD_FINAL_RPTG_RTO DOUBLE, 
		DLGD_RPTG_RTO_VAL DOUBLE, 
		CORRELATION DOUBLE, 
		RETAIL_RW DOUBLE, 
		GUARANTEE_PARTICIPATION DOUBLE, 
		ADJ_FOR_CRM DOUBLE, 
		NETEAD_DRAWN DOUBLE, 
		RWA_UNDRAWN DOUBLE, 
		RWA_DRAWN DOUBLE,
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MTH_TM_ID); COMMIT; 
	
DROP TABLE EDRTLRP1D.DT4_RT18_EST_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT18_EST_VARS (
		MTH_TM_ID INTEGER, 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		EXPOSURE_CLASS VARCHAR(255 OCTETS), 
		OBLIGORS DOUBLE, 
		WEIGHTED_PD_AFTERCRM DOUBLE, 
		WEIGHTED_LGD_AFTERCRM DOUBLE, 
		WEIGHTED_EAD_AFTERCRM DOUBLE, 
		EAD_AFTERCRM_NODEF DOUBLE, 
		EAD_AFTERCRM_DEF DOUBLE, 
		RWA_NODEF DOUBLE, 
		RWA_DEF DOUBLE, 
		RWA DOUBLE, 
		RWA_WSCALAR DOUBLE,
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, DT4_EXPSR_CL_KEY_VAL); COMMIT;
	
/******************************************************************************************************************************************/

DROP TABLE EDRTLRP1D.DT4_RT18_RLZ_PDEAD_DRVD_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT18_RLZ_PDEAD_DRVD_VARS (
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NO VARCHAR(20 OCTETS), 
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		OBS_PIT_STAT_CD CHAR(10 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		DRAWN DECIMAL(17 , 3), 
		UNDRAWN DECIMAL(17 , 3), 
		MODEL_DFT_F INTEGER, 
		EAD_INCL INTEGER, 
		EAD_OBS_AUTHORIZED_AMT DECIMAL(17 , 3), 
		LAST_NEW_DEFAULT_DATE INTEGER, 
		LAST_NEW_DEFAULT_OS_BAL_AMT DECIMAL(17 , 3), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MORT_NO, PROCESS_MTH_TM_ID); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT18_RLZ_LGD_DRVD_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT18_RLZ_LGD_DRVD_VARS (
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NO VARCHAR(20 OCTETS), 
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		OBS_PIT_STAT_CD CHAR(10 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		MODEL_DFT_F INTEGER, 
		LAST_NEW_DEFAULT_DATE INTEGER, 
		LAST_NEW_DEFAULT_OS_BAL_AMT DECIMAL(17 , 3), 
		RLZ_LGD_RTO DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MORT_NO, PROCESS_MTH_TM_ID); COMMIT;

	
DROP TABLE EDRTLRP1D.DT4_RT18_RLZ_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT18_RLZ_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		PD_OBS_MTH_TM_ID INTEGER, 
		PREDICTED_EAD_DEFLTRS DOUBLE, 
		PREDICTED_EAD_PORT DOUBLE, 
		OBSERVED_PD DOUBLE, 
		LGD_OBS_MTH_TM_ID INTEGER, 
		SUM_RLZEAD_X_LGD_RTO DOUBLE, 
		SUM_LGD_PR_3M_LAST_DEFAULT_OS_BA DOUBLE, 
		OBSERVED_LGD DOUBLE, 
		EAD_OBS_MTH_TM_ID INTEGER, 
		RLZEAD_DIVBY_AUTH_X_RLZ DOUBLE, 
		RLZEAD DOUBLE, 
		OBSERVED_EAD DOUBLE,
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, DT4_EXPSR_CL_KEY_VAL); COMMIT;
	
/******************************************************************************************************************************************/


DROP TABLE EDRTLRP1D.DT4_RT18_FINAL_RPTG_VARS IF EXISTS; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT18_FINAL_RPTG_VARS (
		MTH_TM_ID INTEGER, 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		PRODUCTION_PD DOUBLE, 
		OBSERVED_PD DOUBLE, 
		PRODUCTION_LGD DOUBLE, 
		OBSERVED_LGD DOUBLE, 
		PRODUCTION_EAD DOUBLE, 
		OBSERVED_EAD DOUBLE, 
		EAD_MM_NON_DEFAULTED_ACCOUNTS DOUBLE, 
		EAD_MM_DEFAULTED_ACCOUNTS DOUBLE, 
		RWA_MM DOUBLE,
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, DT4_EXPSR_CL_KEY_VAL); COMMIT;
	
