CREATE TABLE
    IF NOT EXISTS MODELS.HELOC_LGDD_SCORE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        VAR_NAME VARCHAR,
        VAR_INPUT VARCHAR,
        VAR_SCORE INTEGER,
        VAR_BIN INTEGER,
        MODEL VARCHAR NOT NULL,
        STREAM VARCHAR
    )
;

ALTER TABLE MODELS.HELOC_LGDD_SCORE
SET
    PARTITIONED BY (OBSN_DT, MODEL)
;