CREATE TABLE
    IF NOT EXISTS MODELS.LOC_EAD_SCORE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        VAR_NAME VARCHAR,
        VAR_INPUT VARCHAR,
        VAR_SCORE INTEGER,        
        VAR_BIN INTEGER,
        STREAM VARCHAR,
        MODEL VARCHAR NOT NULL
    )
;

ALTER TABLE MODELS.LOC_EAD_SCORE
SET
    PARTITIONED BY (OBSN_DT, MODEL)
; 