CREATE TABLE
    IF NOT EXISTS MODELS.STEP_HELOC_PD_SCORE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        VAR_NAME VARCHAR,
        VAR_INPUT VARCHAR,
        VAR_SCORE INTEGER,
        VAR_BIN INTEGER,
        MODEL VARCHAR NOT NULL,
        STREAM VARCHAR
    )
;

ALTER TABLE MODELS.STEP_HELOC_PD_SCORE
SET
    PARTITIONED BY (OBSN_DT, MODEL)
;