
--STEP 1------

DELETE FROM EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT WHERE
MTH_TM_ID = 19516 AND BASEL_ACCT_ID = -1
AND NCR_LTV_KEY_VAL = 0401;



----STEP 2-----

DELETE FROM EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT WHERE
MTH_TM_ID = 19516 AND BASEL_ACCT_ID = -1
AND NCR_LTV_KEY_VAL = 0402
AND rowID <> (SELECT max(rowID) FROM EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT WHERE
MTH_TM_ID = 19516 AND BASEL_ACCT_ID = -1
AND NCR_LTV_KEY_VAL = 0402)