import os
import pyarrow as pa
from airflow.sdk import get_current_context, task


@task
def create_sq019_rundir():
    """Create sq019 run directory."""
    context = get_current_context()
    rundir = context["ti"].xcom_pull(task_ids="handle_month_context", key="RUNDIR")
    sq019_rundir = f"{rundir}/sq019"
    os.makedirs(sq019_rundir, exist_ok=True)


@task.beeline(
    task_id="get_tng_cpd3_trans_union_data_1",
    beeline_conn_id="edlr-conn",
    sql="""
        SELECT
            date_format(current_timestamp, 'yyyy-MM-dd HH:mm:ss.SSSSSS') AS INSRT_PROCESS_TMSTMP,
            '{{ task_instance.xcom_pull(task_ids="handle_month_context", key="MTH_END_DT") }}' as MONTH_END_DT,
            ACCOUNT_ID ,
            date_format(from_unixtime(unix_timestamp(eff_from_dt, 'yyyyMMdd')), 'yyyy-MM-dd') as eff_from_dt,
            CUSTOMER_ID ,
            ACCOUNT_KEY ,
            CUSTOMER_KEY ,
            MTG_PROVIDER_KEY ,
            date_format(from_unixtime(unix_timestamp(eff_to_dt, 'yyyyMMdd')), 'yyyy-MM-dd') as eff_to_dt,
            CURRENT_IND ,
            TRADES_CNT,
            TRADES_ACTIVE_CNT,
            TRADES_STSFCT_CNT,
            TRADES_OPENED_3M_CNT,
            TRADES_OPENED_6M_CNT,
            TRADES_OPENED_12M_CNT,
            TRADES_OPENED_18M_CNT,
            TRADES_OPENED_24M_CNT,
            TRADES_REVISED_3M_CNT,
            TRADES_REVISED_6M_CNT,
            TRADES_REVISED_12M_CNT,
            TRADES_REVISED_18M_CNT,
            TRADES_REVISED_24M_CNT,
            HIT_NOHIT_EDIT_REJECT_IND ,
            TRADES_WORSE_DPD30_CNT,
            TRADES_WORSE_DPD60_CNT,
            TRADES_WORSE_DPD90_CNT,
            TRADES_ACTIVE_PAST_DUE_CNT,
            OCCUR_DPD60_12M_CNT,
            OLDEST_TRADE_MONTHS_CNT,
            MOST_RECENT_TRADE_MONTHS_CNT,
            TRADES_OPENED_12M_BAL_CNT,
            TRADES_STSFCT_3M_CNT,
            TRADES_STSFCT_6M_CNT,
            TRADES_STSFCT_12M_CNT,
            TRADES_STSFCT_18M_CNT,
            TRADES_STSFCT_24M_CNT,
            TOTAL_HC_CL,
            TRADES_BAL_CNT,
            TRADES_NO_BAL_CNT,
            REPOSSESSIONS_CNT,
            CREDIT_COUNSELLING_CNT,
            TRADES_TOT_BALANCE_AMT,
            TRADES_TOT_BAL_HC_CL_RATIO,
            TRADES_AVG_BALANCE_AMT,
            LATEST_DELNQ_MON_CNT,
            TRADES_BAL_5000_CNT,
            TRADES_BAL_1000_CNT,
            TRADES_BAL_500_CNT,
            TRADES_BAL_0_CNT,
            DPD30_12M_CNT,
            DPD60_12M_CNT,
            DPD90_12M_CNT,
            DPD60_EVER_CNT,
            DPD90_EVER_CNT,
            CAST(TOT_MONTHLY_PYMTS AS INTEGER) TOT_MONTHLY_PYMTS,
            HIGHEST_OUTSTND_BAL,
            HIGHEST_HC_CL_AMT,
            TRADES_ACTIVE_30D_RATING_CNT,
            TRADES_ACTIVE_60D_RATING_CNT,
            TRADES_ACTIVE_90D_RATING_CNT,
            CAST(OUTSTND_BAL_30D_RATING AS INTEGER) OUTSTND_BAL_30D_RATING,
            CAST(OUTSTND_BAL_60D_RATING AS INTEGER) OUTSTND_BAL_60D_RATING,
            CAST(OUTSTND_BAL_90D_RATING AS INTEGER) OUTSTND_BAL_90D_RATING,
            CAST(HC_CL_30D_RATING AS INTEGER) HC_CL_30D_RATING,
            CAST(HC_CL_60D_RATING AS INTEGER) HC_CL_60D_RATING,
            CAST(HC_CL_90D_RATING AS INTEGER) HC_CL_90D_RATING,
            TRADES_DPD30_12M_CNT,
            TRADES_DPD60_12M_CNT,
            TRADES_DPD90_12M_CNT,
            TRADES_DPD30_6M_CNT,
            TRADES_DPD60_6M_CNT,
            TRADES_DPD90_6M_CNT,
            TRADES_DPD30_CNT,
            TRADES_DPD60_CNT,
            TRADES_DPD90_CNT,
            TRADES_DPD30_24M_CNT,
            TRADES_DPD60_24M_CNT,
            TRADES_DPD90_24M_CNT,
            TOT_PAST_DUE_AMT,
            LAST_30D_DELNQ_MONTHS_CNT,
            LAST_60D_DELNQ_MONTHS_CNT,
            LAST_90D_DELNQ_MONTHS_CNT,
            TRADES_IN_COLLECT_EVER_CNT,
            TRADES_IN_COLLECT_EVER_AMT,
            TRADES_120D_RATING_CNT,
            TRADES_OPEN_CNT,
            TRADES_OPEN_AVG_BAL_AMT,
            OLDEST_TRADE_LINE_AGE_MONTHS,
            AVAIL_CREDIT_NOT_UTLZD_AMT,
            TRADES_90D_DPD_36M_CNT,
            TRADES_NEGATIVE_CNT,
            LAST_ACTIVITY_MONTHS_CNT,
            TRADES_PAST_DUE_3M_BAL25_CNT,
            TRADES_PAST_DUE_3M_BAL_CNT,
            DPD60_36M_CNT,
            DPD90_36M_CNT,
            TRADES_DISPUTED_CNT,
            TRADES_R9_BAL500_INST_REVL_CNT,
            TRADES_R8_BAL200_INST_REVL_CNT,
            TRADES_R7_BAL200_INST_REVL_CNT,
            TRADES_R5_BAL200_INST_REVL_CNT,
            TRADES_R4_BAL200_INST_REVL_CNT,
            TRADES_R3_BAL200_INST_REVL_CNT,
            TRADES_R2_BAL200_INST_REVL_CNT,
            TRADES_R3_6M_CNT,
            TRADES_R4_WITHIN_60M_CNT,
            TRADES_R4_GREATER_60M_CNT,
            TRADES_R3_WITHIN_60M_CNT,
            TRADES_R3_GREATER_60M_CNT,
            TRADES_R7_WITHIN_60M_CNT,
            TRADES_R7_GREATER_60M_CNT,
            TRADES_OPEN_R9_BAL500_CNT,
            TRADES_OPEN_OPENED_12M_BAL_CNT,
            TRADES_STSFCT_2_DPD30_CNT,
            TRADES_PYMNT_NOT_MON_CNT,
            TRADES_CLOSED_6M_CNT,
            TRADES_OPEN_UTIL_0_5_CNT,
            TRADES_OPEN_UTIL_5_50_CNT,
            TRADES_OPEN_UTIL_50_70_CNT,
            TRADES_OPEN_UTIL_70_90_CNT,
            TRADES_OPEN_UTIL_90_CNT,
            TRADES_ACTIVE_TOT_BAL_AMT,
            TRADES_ACTIVE_TOT_HC_CL_AMT,
            TRADES_ACTIVE_UTIL_PCT,
            TRADES_R4_36M_BAL250_CNT,
            BANKRUPTCIES_CNT,
            JUDGEMENTS_CNT,
            JUDGEMENTS_AMT,
            COLLECTIONS_CNT,
            DEROGATORY_PUBLIC_REC_CNT,
            COLLECTIONS_60M_CNT,
            COLLECTIONS_OLDER_60M_CNT,
            CREDIT_BUREAU_WORST_RATING,
            TRADES_NEVER_DELNQ_PCT,
            TRADES_DPD90_24M_2_TIMES_CNT,
            TRADES_DPD60_BAL100_CNT,
            TOTAL_INCOME,
            HK_POTENTIAL_IND ,
            HK_CONFIRMED_IND ,
            HK_COMPROMISED_IND ,
            ACCT_NUM
        FROM {{ var.value.TSZ_SCHEMA }}.tng_cpd3_trans_union_data_1
        WHERE date_format(from_unixtime(unix_timestamp(month_end_dt, 'yyyyMMdd')), 'yyyy-MM-dd') = '{{ task_instance.xcom_pull(task_ids="handle_month_context", key="MTH_END_DT") }}';
    """,
    rundir="{{ task_instance.xcom_pull(task_ids='handle_month_context', key='RUNDIR') }}/sq019",
    to_parquet=True,
    tmpfileloc="/bns/rrap/data/tmp",
    target="tng_cust_tu_snapshot.parquet",
    schema=pa.schema([
        ('INSRT_PROCESS_TMSTMP', pa.string()),
        ('MONTH_END_DT', pa.string()),
        ('ACCOUNT_ID', pa.string()),
        ('EFF_FROM_DT', pa.string()),
        ('CUSTOMER_ID', pa.string()),
        ('ACCOUNT_KEY', pa.int64()),
        ('CUSTOMER_KEY', pa.int64()),
        ('MTG_PROVIDER_KEY', pa.int64()),
        ('EFF_TO_DT', pa.string()),
        ('CURRENT_IND', pa.string()),
        ('TRADES_CNT', pa.int64()),
        ('TRADES_ACTIVE_CNT', pa.int64()),
        ('TRADES_STSFCT_CNT', pa.int64()),
        ('TRADES_OPENED_3M_CNT', pa.int64()),
        ('TRADES_OPENED_6M_CNT', pa.int64()),
        ('TRADES_OPENED_12M_CNT', pa.int64()),
        ('TRADES_OPENED_18M_CNT', pa.int64()),
        ('TRADES_OPENED_24M_CNT', pa.int64()),
        ('TRADES_REVISED_3M_CNT', pa.int64()),
        ('TRADES_REVISED_6M_CNT', pa.int64()),
        ('TRADES_REVISED_12M_CNT', pa.int64()),
        ('TRADES_REVISED_18M_CNT', pa.int64()),
        ('TRADES_REVISED_24M_CNT', pa.int64()),
        ('HIT_NOHIT_EDIT_REJECT_IND', pa.string()),
        ('TRADES_WORSE_DPD30_CNT', pa.int64()),
        ('TRADES_WORSE_DPD60_CNT', pa.int64()),
        ('TRADES_WORSE_DPD90_CNT', pa.int64()),
        ('TRADES_ACTIVE_PAST_DUE_CNT', pa.int64()),
        ('OCCUR_DPD60_12M_CNT', pa.int64()),
        ('OLDEST_TRADE_MONTHS_CNT', pa.int64()),
        ('MOST_RECENT_TRADE_MONTHS_CNT', pa.int64()),
        ('TRADES_OPENED_12M_BAL_CNT', pa.int64()),
        ('TRADES_STSFCT_3M_CNT', pa.int64()),
        ('TRADES_STSFCT_6M_CNT', pa.int64()),
        ('TRADES_STSFCT_12M_CNT', pa.int64()),
        ('TRADES_STSFCT_18M_CNT', pa.int64()),
        ('TRADES_STSFCT_24M_CNT', pa.int64()),
        ('TOTAL_HC_CL', pa.int64()),
        ('TRADES_BAL_CNT', pa.int64()),
        ('TRADES_NO_BAL_CNT', pa.int64()),
        ('REPOSSESSIONS_CNT', pa.int64()),
        ('CREDIT_COUNSELLING_CNT', pa.int64()),
        ('TRADES_TOT_BALANCE_AMT', pa.float64()),
        ('TRADES_TOT_BAL_HC_CL_RATIO', pa.float64()),
        ('TRADES_AVG_BALANCE_AMT', pa.float64()),
        ('LATEST_DELNQ_MON_CNT', pa.int64()),
        ('TRADES_BAL_5000_CNT', pa.int64()),
        ('TRADES_BAL_1000_CNT', pa.int64()),
        ('TRADES_BAL_500_CNT', pa.int64()),
        ('TRADES_BAL_0_CNT', pa.int64()),
        ('DPD30_12M_CNT', pa.int64()),
        ('DPD60_12M_CNT', pa.int64()),
        ('DPD90_12M_CNT', pa.int64()),
        ('DPD60_EVER_CNT', pa.int64()),
        ('DPD90_EVER_CNT', pa.int64()),
        ('TOT_MONTHLY_PYMTS', pa.int64()),
        ('HIGHEST_OUTSTND_BAL', pa.float64()),
        ('HIGHEST_HC_CL_AMT', pa.float64()),
        ('TRADES_ACTIVE_30D_RATING_CNT', pa.int64()),
        ('TRADES_ACTIVE_60D_RATING_CNT', pa.int64()),
        ('TRADES_ACTIVE_90D_RATING_CNT', pa.int64()),
        ('OUTSTND_BAL_30D_RATING', pa.int64()),
        ('OUTSTND_BAL_60D_RATING', pa.int64()),
        ('OUTSTND_BAL_90D_RATING', pa.int64()),
        ('HC_CL_30D_RATING', pa.int64()),
        ('HC_CL_60D_RATING', pa.int64()),
        ('HC_CL_90D_RATING', pa.int64()),
        ('TRADES_DPD30_12M_CNT', pa.int64()),
        ('TRADES_DPD60_12M_CNT', pa.int64()),
        ('TRADES_DPD90_12M_CNT', pa.int64()),
        ('TRADES_DPD30_6M_CNT', pa.int64()),
        ('TRADES_DPD60_6M_CNT', pa.int64()),
        ('TRADES_DPD90_6M_CNT', pa.int64()),
        ('TRADES_DPD30_CNT', pa.int64()),
        ('TRADES_DPD60_CNT', pa.int64()),
        ('TRADES_DPD90_CNT', pa.int64()),
        ('TRADES_DPD30_24M_CNT', pa.int64()),
        ('TRADES_DPD60_24M_CNT', pa.int64()),
        ('TRADES_DPD90_24M_CNT', pa.int64()),
        ('TOT_PAST_DUE_AMT', pa.float64()),
        ('LAST_30D_DELNQ_MONTHS_CNT', pa.int64()),
        ('LAST_60D_DELNQ_MONTHS_CNT', pa.int64()),
        ('LAST_90D_DELNQ_MONTHS_CNT', pa.int64()),
        ('TRADES_IN_COLLECT_EVER_CNT', pa.int64()),
        ('TRADES_IN_COLLECT_EVER_AMT', pa.float64()),
        ('TRADES_120D_RATING_CNT', pa.int64()),
        ('TRADES_OPEN_CNT', pa.int64()),
        ('TRADES_OPEN_AVG_BAL_AMT', pa.float64()),
        ('OLDEST_TRADE_LINE_AGE_MONTHS', pa.int64()),
        ('AVAIL_CREDIT_NOT_UTLZD_AMT', pa.float64()),
        ('TRADES_90D_DPD_36M_CNT', pa.int64()),
        ('TRADES_NEGATIVE_CNT', pa.int64()),
        ('LAST_ACTIVITY_MONTHS_CNT', pa.int64()),
        ('TRADES_PAST_DUE_3M_BAL25_CNT', pa.int64()),
        ('TRADES_PAST_DUE_3M_BAL_CNT', pa.int64()),
        ('DPD60_36M_CNT', pa.int64()),
        ('DPD90_36M_CNT', pa.int64()),
        ('TRADES_DISPUTED_CNT', pa.int64()),
        ('TRADES_R9_BAL500_INST_REVL_CNT', pa.int64()),
        ('TRADES_R8_BAL200_INST_REVL_CNT', pa.int64()),
        ('TRADES_R7_BAL200_INST_REVL_CNT', pa.int64()),
        ('TRADES_R5_BAL200_INST_REVL_CNT', pa.int64()),
        ('TRADES_R4_BAL200_INST_REVL_CNT', pa.int64()),
        ('TRADES_R3_BAL200_INST_REVL_CNT', pa.int64()),
        ('TRADES_R2_BAL200_INST_REVL_CNT', pa.int64()),
        ('TRADES_R3_6M_CNT', pa.int64()),
        ('TRADES_R4_WITHIN_60M_CNT', pa.int64()),
        ('TRADES_R4_GREATER_60M_CNT', pa.int64()),
        ('TRADES_R3_WITHIN_60M_CNT', pa.int64()),
        ('TRADES_R3_GREATER_60M_CNT', pa.int64()),
        ('TRADES_R7_WITHIN_60M_CNT', pa.int64()),
        ('TRADES_R7_GREATER_60M_CNT', pa.int64()),
        ('TRADES_OPEN_R9_BAL500_CNT', pa.int64()),
        ('TRADES_OPEN_OPENED_12M_BAL_CNT', pa.int64()),
        ('TRADES_STSFCT_2_DPD30_CNT', pa.int64()),
        ('TRADES_PYMNT_NOT_MON_CNT', pa.int64()),
        ('TRADES_CLOSED_6M_CNT', pa.int64()),
        ('TRADES_OPEN_UTIL_0_5_CNT', pa.int64()),
        ('TRADES_OPEN_UTIL_5_50_CNT', pa.int64()),
        ('TRADES_OPEN_UTIL_50_70_CNT', pa.int64()),
        ('TRADES_OPEN_UTIL_70_90_CNT', pa.int64()),
        ('TRADES_OPEN_UTIL_90_CNT', pa.int64()),
        ('TRADES_ACTIVE_TOT_BAL_AMT', pa.float64()),
        ('TRADES_ACTIVE_TOT_HC_CL_AMT', pa.float64()),
        ('TRADES_ACTIVE_UTIL_PCT', pa.float64()),
        ('TRADES_R4_36M_BAL250_CNT', pa.int64()),
        ('BANKRUPTCIES_CNT', pa.int64()),
        ('JUDGEMENTS_CNT', pa.int64()),
        ('JUDGEMENTS_AMT', pa.float64()),
        ('COLLECTIONS_CNT', pa.int64()),
        ('DEROGATORY_PUBLIC_REC_CNT', pa.int64()),
        ('COLLECTIONS_60M_CNT', pa.int64()),
        ('COLLECTIONS_OLDER_60M_CNT', pa.int64()),
        ('CREDIT_BUREAU_WORST_RATING', pa.int64()),
        ('TRADES_NEVER_DELNQ_PCT', pa.float64()),
        ('TRADES_DPD90_24M_2_TIMES_CNT', pa.int64()),
        ('TRADES_DPD60_BAL100_CNT', pa.int64()),
        ('TOTAL_INCOME', pa.float64()),
        ('HK_POTENTIAL_IND', pa.string()),
        ('HK_CONFIRMED_IND', pa.string()),
        ('HK_COMPROMISED_IND', pa.string()),
        ('ACCT_NUM', pa.string())
    ]),
)
def get_tng_cpd3_trans_union_data_1():
    """
    Extract Tangerine credit union trade data.
    
    Extracts comprehensive credit union trade information including timestamp,
    account/customer/provider keys, trade counts (active, satisfied, opened/revised
    in various timeframes), delinquency metrics (DPD30/60/90 in various periods),
    balance information, credit ratings, income, and fraud indicators from
    TNG_CPD3_TRANS_UNION_DATA_1 for the current month-end.
    """
    pass


"""Source layer for sq019."""
rundir_task = create_sq019_rundir()
extract_task = get_tng_cpd3_trans_union_data_1()

rundir_task >> extract_task