-- Output of J_CBS_0030_CUSTUNIV_03 (custuniv_03 -> cbs.CUST_BASE_05).
--
-- Columns / order / types mirror the PRODUCTION CUST_BASE_05 (SYSCOLUMNS, 41 cols).
-- OBSN_DT / STREAM are prepended as the emulated pipeline's partition + delete/replace
-- keys (not present on-prem), matching cbs.CIS_DATA_POP_02. DB2 CHAR(n) -> VARCHAR
-- (DuckDB treats CHAR as VARCHAR); DECIMAL precision preserved, scale 0 for counts.
--
-- NOTE: the 6 NUM_LEND_PRODS_COMM* names (cols 12-17) and HIT_NOHIT_EDIT_REJCT_CD were
-- truncated in the source screenshot -- reconstructed from the CIS_DATA_POP_02 COMM set
-- (COMM, COMM_CUR, COMM_CLO, COMM_DEF, COMM_CHG, COMM_WO). Verify against SYSCOLUMNS.
CREATE TABLE IF NOT EXISTS cbs.CUST_BASE_05 (
    -- Emulated-pipeline partition keys
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,

    CID VARCHAR,
    CID_NUM DOUBLE,
    MTH_TM_ID DECIMAL(11, 0),
    PROCESS_DATE DATE,
    NUM_PRODS DECIMAL(31, 0),
    NUM_LEND_PRODS_CUR DOUBLE,
    NUM_LEND_PRODS_CLO DOUBLE,
    NUM_LEND_PRODS_BNK DOUBLE,
    NUM_LEND_PRODS_DEF DOUBLE,
    NUM_LEND_PRODS_CHG DOUBLE,
    NUM_LEND_PRODS_WO DOUBLE,
    NUM_LEND_PRODS_COMM DOUBLE,
    NUM_LEND_PRODS_COMM_CUR DOUBLE,
    NUM_LEND_PRODS_COMM_CLO DOUBLE,
    NUM_LEND_PRODS_COMM_DEF DOUBLE,
    NUM_LEND_PRODS_COMM_CHG DOUBLE,
    NUM_LEND_PRODS_COMM_WO DOUBLE,
    PRIVATE_BANK_IND DOUBLE,
    NUM_MOR DOUBLE,
    NUM_SPL DOUBLE,
    NUM_REV DOUBLE,
    NUM_SSL DOUBLE,
    NUM_LEND_PRODS DOUBLE,
    WORST_DLQ_DAYS DOUBLE,
    BASEL_CUST_ID BIGINT,
    CUST_CID VARCHAR,
    HIT_NOHIT_EDIT_REJCT_CD VARCHAR,
    FICO_08_SCORE VARCHAR,
    FICO_08_EXCLSN_CD VARCHAR,
    BUREAU_EXIST INTEGER,
    ROW_NUM BIGINT,
    CUST_TYPE VARCHAR,
    CUST_STATUS VARCHAR,
    DECEASED_IND VARCHAR,
    BNKRPTCY_FLAG VARCHAR,
    UNDER_18_FLAG VARCHAR,
    RETAIL_IND INTEGER,
    PRIME_IND INTEGER,
    SECONDARY_IND INTEGER,
    PRIME_IND_LEND INTEGER,
    SECONDARY_IND_LEND INTEGER
);

ALTER TABLE cbs.CUST_BASE_05
SET PARTITIONED BY (OBSN_DT, STREAM);
