CREATE TABLE IF NOT EXISTS instruments.CCAR_BASEL_PRD_TP_NM (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    CCAR_BASEL_PRD_TP_NM VARCHAR NOT NULL,
    STREAM VARCHAR
);
 
ALTER TABLE instruments.CCAR_BASEL_PRD_TP_NM
SET PARTITIONED BY (OBSN_DT,STREAM);