CREATE TABLE
    IF NOT EXISTS instruments.CCAR_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        CCAR_F INTEGER,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.CCAR_F
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;