CREATE TABLE
    IF NOT EXISTS instruments.CONS_DFT_MTH_CNT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CONS_DFT_MTH_CNT INTEGER,
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

-- Set partitions
ALTER TABLE instruments.CONS_DFT_MTH_CNT
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;