CREATE TABLE
    IF NOT EXISTS INSTRUMENTS.CRNT_PRPTY_VAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CRNT_PRPTY_VAL_AMT DECIMAL,
        STREAM VARCHAR
    )
;

ALTER TABLE INSTRUMENTS.CRNT_PRPTY_VAL_AMT
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;