CREATE TABLE
    IF NOT EXISTS INSTRUMENTS.CRNT_LTV_RTO (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CRNT_LTV_RTO DECIMAL(30, 20),
        STREAM VARCHAR
    )
;

ALTER TABLE INSTRUMENTS.CRNT_LTV_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;