CREATE TABLE
    IF NOT EXISTS instruments.DLGD_FLR (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        DLGD_FLR DECIMAL(9, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.DLGD_FLR
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;