CREATE TABLE
    IF NOT EXISTS instruments.EAD_FLRD_RPTG_RTO (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        EAD_FLRD_RPTG_RTO DECIMAL(18, 15),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.EAD_FLRD_RPTG_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;