CREATE TABLE IF NOT EXISTS instruments.EAD_ACCT_SCORE (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    EAD_ACCT_SCORE INTEGER,
    STREAM VARCHAR
);
 
ALTER TABLE instruments.EAD_ACCT_SCORE
SET PARTITIONED BY (OBSN_DT,STREAM);