CREATE TABLE IF NOT EXISTS instruments.EAD_FINAL_RPTG_RTO (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    EAD_FINAL_RPTG_RTO DECIMAL(28,8),
    STREAM VARCHAR
);
 
ALTER TABLE instruments.EAD_FINAL_RPTG_RTO
SET PARTITIONED BY (OBSN_DT, STREAM);