CREATE TABLE
    IF NOT EXISTS instruments.EAD_SEG_VER (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        SRC_SYS_CD VARCHAR,
        EAD_SEG_VER DECIMAL(28,8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.EAD_SEG_VER
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;