CREATE TABLE
    IF NOT EXISTS instruments.EAD_UNADJUSTED_RPTG_RTO (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        EAD_UNADJUSTED_RPTG_RTO DECIMAL(28, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.EAD_UNADJUSTED_RPTG_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;