CREATE TABLE
    IF NOT EXISTS instruments.EAD_BASEL_SEG_NUM (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        MODEL VARCHAR,
        EAD_BASEL_SEG_NUM INT,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.EAD_BASEL_SEG_NUM
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;