CREATE TABLE IF NOT EXISTS instruments.EAD_FLR (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    EAD_FLR DECIMAL(18,15),
    STREAM VARCHAR
);
 
ALTER TABLE instruments.EAD_FLR
SET PARTITIONED BY (OBSN_DT,STREAM);