CREATE TABLE IF NOT EXISTS instruments.EXPOSURE_SECURED (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    EXPOSURE_SECURED DECIMAL(38,8),
    STREAM VARCHAR
);
 
ALTER TABLE instruments.EXPOSURE_SECURED
SET PARTITIONED BY (OBSN_DT, STREAM);