CREATE TABLE
    IF NOT EXISTS instruments.EXPOSURE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        EXPOSURE DECIMAL(38,8),
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.EXPOSURE
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;