CREATE TABLE
    IF NOT EXISTS instruments.EXPSR_AT_DFT_RTO (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        EXPSR_AT_DFT_RTO DECIMAL(28, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.EXPSR_AT_DFT_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;