CREATE TABLE
    IF NOT EXISTS instruments.FINAL_RTO (
        OBSN_DT DATE NOT NULL,
        BASEL_MODEL_ID VARCHAR,
        SEG_NUM SMALLINT,
        FINAL_RTO DECIMAL(28, 8) NOT NULL,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.FINAL_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;