CREATE TABLE IF NOT EXISTS instruments.FULLY_SECURED_F (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    FULLY_SECURED_F VARCHAR,
    STREAM VARCHAR
);
 
ALTER TABLE instruments.FULLY_SECURED_F
SET PARTITIONED BY (OBSN_DT, STREAM);