CREATE TABLE
    IF NOT EXISTS instruments.INDEX_TERANETV_CMA (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        MORT_NUM BIGINT NOT NULL,
        INDEX_TERANETV DECIMAL(38, 11),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.INDEX_TERANETV_CMA
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;