CREATE TABLE
    IF NOT EXISTS INSTRUMENTS.INDEXED_PRPTY_VAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        INDEXED_PRPTY_VAL_AMT DOUBLE,
        STREAM VARCHAR
    )
;

ALTER TABLE INSTRUMENTS.INDEXED_PRPTY_VAL_AMT
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;