CREATE TABLE
    IF NOT EXISTS instruments.INDEXED_CCLTV_RTO (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        INDEXED_CCLTV_RTO DECIMAL(31, 21),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.INDEXED_CCLTV_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;