CREATE TABLE IF NOT EXISTS instruments.INSUR_F (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    INSUR_F VARCHAR,
    STREAM VARCHAR
);

ALTER TABLE instruments.INSUR_F SET PARTITIONED BY (OBSN_DT, STREAM);