CREATE TABLE IF NOT EXISTS instruments.INTR_ACCR_AMT(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    INTR_ACCR_AMT DECIMAL (17,5),
    STREAM VARCHAR
);

ALTER TABLE instruments.INTR_ACCR_AMT SET PARTITIONED BY (OBSN_DT, STREAM);
