CREATE TABLE IF NOT EXISTS instruments.LGD_FLRD_RPTG_RTO (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    LGD_FLRD_RPTG_RTO DECIMAL(18,10),
    STREAM VARCHAR
);

ALTER TABLE instruments.LGD_FLRD_RPTG_RTO SET PARTITIONED BY (OBSN_DT, STREAM)
;