CREATE TABLE IF NOT EXISTS instruments.LGD_ACCT_SCORE (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    LGD_ACCT_SCORE INTEGER,
    STREAM VARCHAR
);
 
ALTER TABLE instruments.LGD_ACCT_SCORE
SET PARTITIONED BY (OBSN_DT,STREAM);