CREATE TABLE
    IF NOT EXISTS instruments.LGD_LR_PV_AD_RPTG_RTO (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        LGD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.LGD_LR_PV_AD_RPTG_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;