CREATE TABLE
    IF NOT EXISTS instruments.LGD_MODEL_NM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        LGD_MODEL_ID VARCHAR,
        LGD_MODEL_NM VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.LGD_MODEL_NM
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;