CREATE TABLE IF NOT EXISTS instruments.LGD_FLR (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    LGD_FLR DECIMAL(18,3),
    STREAM VARCHAR
);

ALTER TABLE instruments.LGD_FLR SET PARTITIONED BY (OBSN_DT, STREAM);