CREATE TABLE
    IF NOT EXISTS instruments.LGD_MODEL_VER (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        LGD_MODEL_VER VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.LGD_MODEL_VER
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;