CREATE TABLE IF NOT EXISTS instruments.LNG_RUN_LGD_ADD_ON_RTO (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    LNG_RUN_LGD_ADD_ON_RTO DECIMAL(38,8),
    STREAM VARCHAR
);
 
ALTER TABLE instruments.LNG_RUN_LGD_ADD_ON_RTO
SET PARTITIONED BY (OBSN_DT, STREAM);