CREATE TABLE
    IF NOT EXISTS instruments.METRPL_AREA_NM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        METRPL_AREA_NM VARCHAR,
        CMA VARCHAR,
        SRC_SYS_CD VARCHAR,
        PROV VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.METRPL_AREA_NM
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;