CREATE TABLE
    IF NOT EXISTS instruments.PD_90_DAY_F (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        PD_90_DAY_F VARCHAR,
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PD_90_DAY_F
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;