CREATE TABLE
    IF NOT EXISTS instruments.PD_BAND (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        PD_BAND VARCHAR,
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PD_BAND
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;