CREATE TABLE IF NOT EXISTS instruments.PD_FINAL_RPTG_RTO (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    PD_FINAL_RPTG_RTO DECIMAL(28,8),
    STREAM VARCHAR
);
 
ALTER TABLE instruments.PD_FINAL_RPTG_RTO
SET PARTITIONED BY (OBSN_DT,STREAM);