CREATE TABLE
    IF NOT EXISTS instruments.PD_FLRD_RPTG_RTO (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        PD_FLRD_RPTG_RTO DECIMAL(9, 8),
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PD_FLRD_RPTG_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;