CREATE TABLE
    IF NOT EXISTS instruments.PD_FLR (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        PD_FLR DECIMAL(8, 4),
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PD_FLR
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;