CREATE TABLE
    IF NOT EXISTS instruments.PD_MODEL_NM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PD_MODEL_ID VARCHAR,
        PD_MODEL_NM VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PD_MODEL_NM
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;