CREATE TABLE
    IF NOT EXISTS instruments.PD_UNADJUSTED_RPTG_RTO (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        PD_UNADJUSTED_RPTG_RTO DECIMAL(28, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PD_UNADJUSTED_RPTG_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;