CREATE TABLE
    IF NOT EXISTS instruments.PIT_STAT_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PIT_STAT_CD VARCHAR,
        SRC_SYS_CD VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PIT_STAT_CD
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;