CREATE TABLE IF NOT EXISTS instruments.PMI_LGD_UNADJUSTED_RPTG_RTO (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(9,8),
    STREAM VARCHAR
);

ALTER TABLE instruments.PMI_LGD_UNADJUSTED_RPTG_RTO SET PARTITIONED BY (OBSN_DT, STREAM)
;