CREATE TABLE
    IF NOT EXISTS instruments.PRE_INSURANCE_LGD (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        PRE_INSURANCE_LGD DECIMAL(9, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.PRE_INSURANCE_LGD
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;