CREATE TABLE
    IF NOT EXISTS INSTRUMENTS.PREV_12_QTR_PRPTY_VAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PREV_12_QTR_PRPTY_VAL_AMT DECIMAL(20, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE INSTRUMENTS.PREV_12_QTR_PRPTY_VAL_AMT
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;