CREATE TABLE
    IF NOT EXISTS INSTRUMENTS.PRPTY_VAL_CORR_PCTG (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PRPTY_VAL_CORR_PCTG DECIMAL(11, 4),
        STREAM VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE INSTRUMENTS.PRPTY_VAL_CORR_PCTG
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;