-- AMORT feature definition
CREATE TABLE
    IF NOT EXISTS instruments.RESIDUAL_MAT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        RESIDUAL_MAT INTEGER,
        STREAM VARCHAR
    )
;

-- Set partitions 
ALTER TABLE instruments.RESIDUAL_MAT
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;