CREATE TABLE
    IF NOT EXISTS instruments.RNTL_PRPTY_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        RNTL_PRPTY_F VARCHAR,
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.RNTL_PRPTY_F
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;