CREATE TABLE
    IF NOT EXISTS instruments.UNDRAWN (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        UNDRAWN DECIMAL(19, 3),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.UNDRAWN
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;