CREATE TABLE IF NOT EXISTS instruments.UNINSURED_LGD_SEG_NUM (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    UNINSURED_LGD_SEG_NUM INT,
    STREAM VARCHAR
);
 
ALTER TABLE instruments.UNINSURED_LGD_SEG_NUM
SET PARTITIONED BY (OBSN_DT,STREAM);