CREATE TABLE IF NOT EXISTS instruments.UNINSURED_FLRD_LGD_RTO (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    UNINSURED_FLRD_LGD_RTO  DECIMAL(28,8),
    STREAM VARCHAR
);
 
ALTER TABLE instruments.UNINSURED_FLRD_LGD_RTO
SET PARTITIONED BY (OBSN_DT,STREAM);