CREATE TABLE
    IF NOT EXISTS instruments.UNINSURED_DLGD_RTO (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        UNINSURED_DLGD_RTO DECIMAL(28, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.UNINSURED_DLGD_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;