CREATE TABLE
    IF NOT EXISTS instruments.UNINSURED_LGD_RTO (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        UNINSURED_LGD_RTO DECIMAL(28, 8),
        STREAM VARCHAR
    )
;

ALTER TABLE instruments.UNINSURED_LGD_RTO
SET
    PARTITIONED BY (OBSN_DT, STREAM)
;