CREATE TABLE IF NOT EXISTS instruments.WEIGHT_UNSECURED (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    WEIGHT_UNSECURED BIGINT,
    STREAM VARCHAR
);
 
ALTER TABLE instruments.WEIGHT_UNSECURED
SET PARTITIONED BY (OBSN_DT,STREAM);