CREATE TABLE IF NOT EXISTS instruments.WEIGHT_SECURED (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    WEIGHT_SECURED BIGINT,
    STREAM VARCHAR
);
 
ALTER TABLE instruments.WEIGHT_SECURED
SET PARTITIONED BY (OBSN_DT,STREAM);