Use crz_cust_scorecard;
DROP TABLE IF EXISTS RISK_KQ_ACCT_SNAPSHOT;
CREATE EXTERNAL TABLE RISK_KQ_ACCT_SNAPSHOT(
    ACCT_NUM                        VARCHAR(30)       COMMENT 'Account Number',
    INSRT_PROCESS_TMSTMP            TIMESTAMP,
    OP_FIELD                        VARCHAR(1000),
    STEP_PLN_AGRMNT_NUM             VARCHAR(15),
    PRIM_CUST_CID                   VARCHAR(40),
    PROD_CD                         VARCHAR(3)        COMMENT 'Product Code',
    SUB_PROD_CD                     VARCHAR(5)        COMMENT 'Sub Product Code',
    CIS_PROD_CD                     VARCHAR(3)        COMMENT 'CIS Product Code',
    MAJR_PROD_GRP                   VARCHAR(3)        COMMENT 'Major Product Group',
    TRNST_NUM                       VARCHAR(5)        COMMENT 'Bank Transit Number',
    BLOCK_RECL_CD                   VARCHAR(2)        COMMENT 'Block Reclassification Code',
    ACCT_STAT_CD                    VARCHAR(2)        COMMENT 'Account Status Code',
    ACCT_OPEN_DT                    DATE              COMMENT 'Date the Account was opened',
    SRC_CD                          SMALLINT          COMMENT 'Source Code',
    FINAL_CR_SCORE                  SMALLINT          COMMENT 'Final Credit Score',
    LAST_PURCH_DT                   DATE              COMMENT 'Date Last Purchase was made',
    LAST_ACTY_DT                    DATE              COMMENT 'Date of Last Activity on the Account',
    CR_LMT_AMT                      DECIMAL(18, 2)    COMMENT 'Credit Limit Amount',
    MTH_DLQNT_CNT                   INT               COMMENT 'Number of times the account was Delinquent in the processing month',
    ORIG_CHRG_FF_AMT                DECIMAL(18, 2)    COMMENT 'Original Charge Off Amount',
    CHRG_OFF_DT                     DATE              COMMENT 'Charge Off Date',
    CHRG_OFF_CD                     VARCHAR(1)        COMMENT 'Charge Off Code',
    LAST_PYMNT_DT                   DATE              COMMENT 'Last Payment Date',
    TOT_NEW_BAL_AMT                 DECIMAL(18, 2)    COMMENT 'Total New Balance Amount',
    NON_ACCRL_DT                    DATE              COMMENT 'Non Accrual Date',
    WRITE_OFF_DT                    DATE              COMMENT 'Write Off Date',
    ACCT_CLS_RSN_CD                 VARCHAR(2)        COMMENT 'Account Closing Reason Code',
    BNS_DLQNT_DAY                   SMALLINT          COMMENT 'BNS Delinquent Day',
    LAST_BLOCKED_DT                 DATE              COMMENT 'Last Blocked Date',
    SCRD_TYPE_CD                    VARCHAR(1),
    SWITCH_CD                       VARCHAR(1),
    SWITCH_DT                       DATE,
    SWITCH_XREF                     BIGINT,
    NEXT_RNEWL_FEE_DT               DATE              COMMENT 'Next Renewal Date',
    INACT_CD                        VARCHAR(1)        COMMENT 'Inactivity Code',
    SCRTY_TP_CD                     VARCHAR(2),
    SCRTY_VAL_AMT                   DECIMAL(18, 2),
    CORP_RTL_FLAG                   VARCHAR(1),
    CRNT_BILL_CD                    VARCHAR(10)       COMMENT 'Current Bill Code',
    PRCH_CRNT_CYCL_BAL_AMT          DECIMAL(18, 2),
    PRCH_1_CYCL_AGO_BAL_AMT         DECIMAL(18, 2),
    PRCH_2_CYCL_AGO_BAL_AMT         DECIMAL(18, 2),
    CSH_ADVNC_CRNT_CYCL_BAL_AMT     DECIMAL(18, 2),
    CSH_ADVNC_1_CYCL_AGO_BAL_AMT    DECIMAL(18, 2),
    CSH_ADVNC_2_CYCL_AGO_BAL_AMT    DECIMAL(18, 2),
    TOT_UNPAID_FNCL_CHRG_AMT        DECIMAL(18, 2),
    YTD_PRCHS_CNT                   SMALLINT          COMMENT 'Year To Date Purchase Count',
    YTD_PRCHS_INTR_CHRGD_AMT        DECIMAL(18, 2),
    YTD_PRCHS_INTR_PD_AMT           DECIMAL(18, 2)    COMMENT 'Year To Date Interest Paid on Purchases Amount',
    YTD_CSH_ADVNC_INTR_CHRGD_AMT    DECIMAL(18, 2)    COMMENT 'Year To Date Interest Amount charged on Cash Advances',
    YTD_CSH_ADVNC_INTR_PD_AMT       DECIMAL(18, 2)    COMMENT 'Year To Date Interest Paid Amount on Cash Advances',
    TOT_RCVRY_INTR_AMT              DECIMAL(18, 2)    COMMENT 'Total Recovery Interest Amount',
    PRCH_RCVRY_INTR_AMT             DECIMAL(18, 2)    COMMENT 'Purchase Recovery Interest Amount',
    CSH_ADVNC_RCVRY_INTR_AMT        DECIMAL(18, 2)    COMMENT 'Cash Advance Recovery Interest Amount',
    LAST_YR_CR_INTR_PD_AMT          DECIMAL(18, 2)    COMMENT 'Last Year Credit Interest Paid Amount',
    TOT_YTD_CR_INTR_PD_AMT          DECIMAL(18, 2)    COMMENT 'Total Year To Date Credit Interest Paid Amount',
    BAL_HIST_PRCHS_AMT              DECIMAL(18, 2)    COMMENT 'Balance History Purchase Amount',
    BAL_HIST_CSH_ADV_AMT            DECIMAL(18, 2)    COMMENT 'Balance History Cash Advance Amount',
    BAL_HIST_PYMTS_AMT              DECIMAL(18, 2)    COMMENT 'Balance History Payments Amount',
    FULL_PYMT_CD                    VARCHAR(1)        COMMENT 'Full Payment Code',
    PREV_SUB_PROD_CD                VARCHAR(3),
    DLQNT_HIST_13_24                BIGINT,
    DLQNT_HIST_1_12                 BIGINT,
    LAST_PYMT_AMT                   DECIMAL(18, 2)    COMMENT 'Last Payment Amount',
    GL_ACCT_NUM                     VARCHAR(7)        COMMENT 'General Ledger Account Number',
    GL_TRNST_NUM                    VARCHAR(5)        COMMENT 'General Ledger Transit Number',
    CURRENCY_CD                     VARCHAR(3)        COMMENT 'Currency Code'
)
PARTITIONED BY( EFF_DT DATE COMMENT 'Effective Date', DATE_TYPE VARCHAR(20))
CLUSTERED BY (ACCT_NUM) SORTED BY (ACCT_NUM ASC) INTO 60 BUCKETS
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_KQ_ACCT_SNAPSHOT'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

