Use crz_cust_scorecard;
DROP TABLE IF EXISTS RISK_TRNST_EXCLSN_LKP;
CREATE EXTERNAL TABLE RISK_TRNST_EXCLSN_LKP(
    EXCLUDED_TRNST_NUM      VARCHAR(5),
    INSRT_PROCESS_TMSTMP    TIMESTAMP,
    OP_FIELD                VARCHAR(1000)
)
PARTITIONED BY( EFF_DT DATE)
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_TRNST_EXCLSN_LKP'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

