Use crz_cust_scorecard;
DROP TABLE IF EXISTS RISK_CHRG_OFF_LKP;
CREATE EXTERNAL TABLE RISK_CHRG_OFF_LKP(
    CHRG_OFF_CD             VARCHAR(10),
    INSRT_PROCESS_TMSTMP    TIMESTAMP,
    OP_FIELD                VARCHAR(1000),
    CHRG_OFF_STAT_FLAG      VARCHAR(1),
    CHRG_OFF_STAT_DESC      VARCHAR(50),
    ACCRL_STAT_FLAG         VARCHAR(1),
    ACCRL_STAT_DESC         VARCHAR(50)
)
PARTITIONED BY( EFF_DT DATE)
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_CHRG_OFF_LKP'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

