import os
from datetime import timedelta
import pendulum

from airflow.sdk import get_current_context
from airflow.sdk.bases.sensor import PokeReturnValue

from bns.rrap.helpers.asset_event import (
    _pull_asset_event_extras,
    _push_asset_event_extras,
)


UPSTREAM_ASSET = [
    "ingestion.BASEL_MORT_MTH_SNAPSHOT",
    "ingestion.AIRB_MORT_MTH_SNAPSHOT",
]
DOWNSTREAM_ASSET = "ingestion.MORT_MTH_SNAPSHOT"
DEPENDENCIES = {"duckdb_delete": ["duckdb_load"]}


def duckdb_delete(
    duckdb_conn_id="duckdb-conn",
    sql=f"""
    DELETE FROM {DOWNSTREAM_ASSET} 
    WHERE mth_tm_id = {{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="mth_tm_id") }}}}
    """,
):
    pass


def duckdb_load(
    duckdb_conn_id="duckdb-conn",
    sql=f"""
    INSERT INTO {DOWNSTREAM_ASSET} BY NAME
    FROM (
        select
            AIRB_MORT_MTH_SNAPSHOT.DLQNT_DAY::INTEGER as DLQNT_DAY,
            AIRB_MORT_MTH_SNAPSHOT.DLQNT_MTH::INTEGER as DLQNT_MTH,
            AIRB_MORT_MTH_SNAPSHOT.EFF_TMSTMP::TIMESTAMP as EFF_TMSTMP,
            BASEL_MORT_MTH_SNAPSHOT.MORT_NUM::BIGINT as MORT_NUM,
            AIRB_MORT_MTH_SNAPSHOT.MTH_END_DT::DATE as MTH_END_DT,
            TRIM(AIRB_MORT_MTH_SNAPSHOT.CRNCY_CD::VARCHAR) as CRNCY_CD,
            TRIM(AIRB_MORT_MTH_SNAPSHOT.GL_TRNST_NUM::VARCHAR) as GL_TRNST_NUM,
            TRIM(AIRB_MORT_MTH_SNAPSHOT.INSUR_GRP::VARCHAR) as INSUR_GRP,
            TRIM(AIRB_MORT_MTH_SNAPSHOT.LRA_STAT::VARCHAR) as LRA_STAT,
            TRIM(AIRB_MORT_MTH_SNAPSHOT.PROP_PROV::VARCHAR) as PROP_PROV,
            TRIM(AIRB_MORT_MTH_SNAPSHOT.PROPERTY_ADDR_3::VARCHAR) as PROPERTY_ADDR_3,
            TRIM(AIRB_MORT_MTH_SNAPSHOT.TNIF_RGN_CD::VARCHAR) as TNIF_RGN_CD,
            AIRB_MORT_MTH_SNAPSHOT.UNPAID_WKLY_PAY_DT::TIMESTAMP as UNPAID_WKLY_PAY_DT,
            BASEL_MORT_MTH_SNAPSHOT.BASEL_MORT_MTH_SNAPSHOT_ID::BIGINT as BASEL_MORT_MTH_SNAPSHOT_ID,
            BASEL_MORT_MTH_SNAPSHOT.MTH_TM_ID::INTEGER as MTH_TM_ID,
            BASEL_MORT_MTH_SNAPSHOT.STEP_PLN_SNAPSHOT_ID::BIGINT as STEP_PLN_SNAPSHOT_ID,
            BASEL_MORT_MTH_SNAPSHOT.PRIM_BASEL_CUST_ID::BIGINT as PRIM_BASEL_CUST_ID,
            BASEL_MORT_MTH_SNAPSHOT.BASEL_ACCT_ID::BIGINT as BASEL_ACCT_ID,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.FLOAT_CD::VARCHAR) as FLOAT_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.PD_OFF_F::VARCHAR) as PD_OFF_F,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.FRCLSR_F::VARCHAR) as FRCLSR_F,
            BASEL_MORT_MTH_SNAPSHOT.MTH_IN_ARRS_CNT::DECIMAL(5,0) as MTH_IN_ARRS_CNT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.INSUR_CL_CD::VARCHAR) as INSUR_CL_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.PRPTY_CD::VARCHAR) as PRPTY_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.FUND_CD::VARCHAR) as FUND_CD,
            BASEL_MORT_MTH_SNAPSHOT.INTR_ADJ_DT::DATE as INTR_ADJ_DT,
            BASEL_MORT_MTH_SNAPSHOT.CRNT_BAL_AMT::DECIMAL(17,3) as CRNT_BAL_AMT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.SERV_BR_TRNST_NUM::VARCHAR) as SERV_BR_TRNST_NUM,
            BASEL_MORT_MTH_SNAPSHOT.SERV_BR_OU_ID::BIGINT as SERV_BR_OU_ID,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.PROC_BR_TRNST_NUM::VARCHAR) as PROC_BR_TRNST_NUM,
            BASEL_MORT_MTH_SNAPSHOT.PROC_BR_OU_ID::BIGINT as PROC_BR_OU_ID,
            BASEL_MORT_MTH_SNAPSHOT.MORT_AUTH_DT::DATE as MORT_AUTH_DT,
            BASEL_MORT_MTH_SNAPSHOT.PD_OFF_DT::DATE as PD_OFF_DT,
            BASEL_MORT_MTH_SNAPSHOT.CRNT_TERM_MAT_DT::DATE as CRNT_TERM_MAT_DT,
            BASEL_MORT_MTH_SNAPSHOT.LAST_RNEW_DT::DATE as LAST_RNEW_DT,
            BASEL_MORT_MTH_SNAPSHOT.AUTH_AMT::DECIMAL(17,3) as AUTH_AMT,
            BASEL_MORT_MTH_SNAPSHOT.INTR_DUE_AMT::DECIMAL(17,3) as INTR_DUE_AMT,
            BASEL_MORT_MTH_SNAPSHOT.LND_VAL::INTEGER as LND_VAL,
            BASEL_MORT_MTH_SNAPSHOT.TAX_CRNT_BAL_AMT::DECIMAL(17,3) as TAX_CRNT_BAL_AMT,
            BASEL_MORT_MTH_SNAPSHOT.INTR_ACCR_AMT::DECIMAL(17,3) as INTR_ACCR_AMT,
            BASEL_MORT_MTH_SNAPSHOT.TOT_ADVNC_AMT::DECIMAL(17,3) as TOT_ADVNC_AMT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.BRWER_CD::VARCHAR) as BRWER_CD,
            BASEL_MORT_MTH_SNAPSHOT.APRSD_LAST_BUILDING_VAL::INTEGER as APRSD_LAST_BUILDING_VAL,
            BASEL_MORT_MTH_SNAPSHOT.APRSD_LAND_VAL::INTEGER as APRSD_LAND_VAL,
            BASEL_MORT_MTH_SNAPSHOT.APRSD_LAST_LAND_VAL::INTEGER as APRSD_LAST_LAND_VAL,
            BASEL_MORT_MTH_SNAPSHOT.APRSD_BUILDING_VAL::INTEGER as APRSD_BUILDING_VAL,
            BASEL_MORT_MTH_SNAPSHOT.APRSD_ORIG_LAND_VAL::INTEGER as APRSD_ORIG_LAND_VAL,
            BASEL_MORT_MTH_SNAPSHOT.APRSD_ORIG_BUILDING_VAL::INTEGER as APRSD_ORIG_BUILDING_VAL,
            BASEL_MORT_MTH_SNAPSHOT.FINAL_ADVNC_DT::DATE as FINAL_ADVNC_DT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.LIFE_INSUR_CD::VARCHAR) as LIFE_INSUR_CD,
            BASEL_MORT_MTH_SNAPSHOT.WK_FRST_UNPAID_DT::DATE as WK_FRST_UNPAID_DT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.BUS_SRC_CD::VARCHAR) as BUS_SRC_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.SCRTY_TP_2::VARCHAR) as SCRTY_TP_2,
            BASEL_MORT_MTH_SNAPSHOT.FRST_UNPAID_DT::DATE as FRST_UNPAID_DT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.MONTREAL_TRUST_DSBLTY_STAT_CD::VARCHAR) as MONTREAL_TRUST_DSBLTY_STAT_CD,
            BASEL_MORT_MTH_SNAPSHOT.SALE_DT_VAL::INTEGER as SALE_DT_VAL,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.MRKTING_1_CD::VARCHAR) as MRKTING_1_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.MRKTING_2_CD::VARCHAR) as MRKTING_2_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.MRKTING_3_CD::VARCHAR) as MRKTING_3_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.MRKTING_4_CD::VARCHAR) as MRKTING_4_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.MRKTING_5_CD::VARCHAR) as MRKTING_5_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.CRI_CD::VARCHAR) as CRI_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.ARI_CD::VARCHAR) as ARI_CD,
            BASEL_MORT_MTH_SNAPSHOT.PVSN_AMT::DECIMAL(17,3) as PVSN_AMT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.SCOTIA_TOT_EQTY_PLN_F::VARCHAR) as SCOTIA_TOT_EQTY_PLN_F,
            BASEL_MORT_MTH_SNAPSHOT.LOAN_AUTH_DT::DATE as LOAN_AUTH_DT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.HLTH_CRSIS_PRTCTN_INSUR_STAT_CD::VARCHAR) as HLTH_CRSIS_PRTCTN_INSUR_STAT_CD,
            BASEL_MORT_MTH_SNAPSHOT.TOT_SUSP_BAL_AMT::DECIMAL(17,3) as TOT_SUSP_BAL_AMT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.ACCT_TP_CD::VARCHAR) as ACCT_TP_CD,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.PRPTY_PROV_CD::VARCHAR) as PRPTY_PROV_CD,
            BASEL_MORT_MTH_SNAPSHOT.RENEWED_DT::DATE as RENEWED_DT,
            BASEL_MORT_MTH_SNAPSHOT.MORT_TERM_MTH::DECIMAL(4,0) as MORT_TERM_MTH,
            BASEL_MORT_MTH_SNAPSHOT.MAX_INTR_RT::DECIMAL(10,4) as MAX_INTR_RT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.YR_5_MTH_6_F::VARCHAR) as YR_5_MTH_6_F,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.PRIM_CUST_CID::VARCHAR) as PRIM_CUST_CID,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.STEP_PLN_AGRMNT_NUM::VARCHAR) as STEP_PLN_AGRMNT_NUM,
            BASEL_MORT_MTH_SNAPSHOT.INSRT_PROCESS_TMSTMP::TIMESTAMP as INSRT_PROCESS_TMSTMP,
            BASEL_MORT_MTH_SNAPSHOT.UPDT_PROCESS_TMSTMP::TIMESTAMP as UPDT_PROCESS_TMSTMP,
            BASEL_MORT_MTH_SNAPSHOT.YTD_PRPY_AMT::DECIMAL(17,3) as YTD_PRPY_AMT,
            BASEL_MORT_MTH_SNAPSHOT.AMORT_MTH::SMALLINT as AMORT_MTH,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.PRPTY_ADDR::VARCHAR) as PRPTY_ADDR,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.GL_ACCT_NUM::VARCHAR) as GL_ACCT_NUM,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.PRD_GRP_CD::VARCHAR) as PRD_GRP_CD,
            BASEL_MORT_MTH_SNAPSHOT.UNIT_CNT::SMALLINT as UNIT_CNT,
            TRIM(BASEL_MORT_MTH_SNAPSHOT.COMM_TP::VARCHAR) as COMM_TP,
        FROM
            ingestion.BASEL_MORT_MTH_SNAPSHOT as BASEL_MORT_MTH_SNAPSHOT
            LEFT JOIN ingestion.AIRB_MORT_MTH_SNAPSHOT as AIRB_MORT_MTH_SNAPSHOT ON BASEL_MORT_MTH_SNAPSHOT.mth_tm_id = AIRB_MORT_MTH_SNAPSHOT.tm_id
            AND TRIM(BASEL_MORT_MTH_SNAPSHOT.mort_num) = AIRB_MORT_MTH_SNAPSHOT.mort_num
        WHERE BASEL_MORT_MTH_SNAPSHOT.MTH_TM_ID = {{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="mth_tm_id") }}}}
    )
    """,
):
    pass
