/***************************************************************************
Deployment Date: AUG 02, 2024
CHANGE TICKET: CHG0894511
JIRA: RRMSS- 2845, 2846
CHANGE: CREATE NEW TABLE/VIEW IN IIAS PROD
NOTE: RUN THIS BEFORE STEP_Script_3_DataPatch.xlsx
/****************************************************************************/

/****************** New PIT STATUS Table ***********************/
/* PLEASE ADD HIDDEN COLUMNS FOR REPLICATION */
/* PLEASE ADD THIS TABLE TO IIAS DR */

CREATE TABLE EDRTLRP1D.PIT_STATUS_PRE_STEP (  
MTH_TM_ID INTEGER NOT NULL
,SRC_SYS_CD CHAR(10) NOT NULL
,BASEL_ACCT_ID BIGINT NOT NULL
,MORT_NUM INTEGER
,MORT_PROCESS_DATE TIMESTAMP
,PIT_STATUS_PRE_STEP CHAR(10)
,STEP_PLN_SNAPSHOT_ID BIGINT NOT NULL
,STEP_PLN_AGRMNT_NUM CHAR(23)
,STEP_DFLT_F CHAR(1)
,CROSS_DFLT_PIT_OVERRIDE_F CHAR(1)
,CROSS_DFLT_PIT_STATUS CHAR(10) 
,INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
,UPDT_PROCESS_TMSTMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) 
DISTRIBUTE BY HASH (BASEL_ACCT_ID, STEP_PLN_SNAPSHOT_ID, MTH_TM_ID); 
COMMIT;

/****************** New Step Default View ***********************/
/* PLEASE ADD THIS VIEW TO IIAS DR */

CREATE VIEW EDRTLRP1D.DFLTD_STEP_PLAN_V AS 
SELECT 
s.MTH_TM_ID
,s.SRC_SYS_CD
,s.BASEL_ACCT_ID
,a.ACCT_NUM
,s.STEP_PLN_SNAPSHOT_ID
,s.STEP_PLN_AGRMNT_NUM
,a.LNK_TO_STEP
,a.CLP_FLAG
,s.STEP_DFLT_F
,s.PIT_STATUS_PRE_STEP
,s.CROSS_DFLT_PIT_STATUS
,s.CROSS_DFLT_PIT_OVERRIDE_F
,r.RECD_STAT_CD 
,c.BLOCK_RECL_CD
,d.CCAR_BASEL_PRD_TP_NM 
,d.BCAR_SCHED_NUM_50 
,d.PD_BAND 
,d.BASEL_GRP 
,d.INSURER_GRP 
,d.RNTL_PRPTY_F 
,d.EXPOSURE_DRAWN 
,d.UNDRAWN 
,d.EXPSR_DRAWN_PRIOR_SECUR 
,d.ECL_POST_ADJ_DRAWN_POSTSEC_3 
,d.EL_DRAWNPCT_FOR_DEFAULTED 
,d.NETEAD_BEFORECRM_DRAWN AS EAD_BEFORECRM_DRAWN 
,d.NETEAD_DRAWN AS EAD_AFTER_CRM_DRAWN 
,d.NETEAD_UNDRAWN 
,d.RWA_DRAWN 
,d.RWA_UNDRAWN 
FROM 
EDRTLRP1D.PIT_STATUS_PRE_STEP s 
LEFT JOIN 
EDRTLRP1D.BASEL_ACCT_PRFM_FACT a
ON s.MTH_TM_ID=a.MTH_TM_ID 
AND s.SRC_SYS_CD=CASE a.SRC_SYS_CD WHEN 'KQ' THEN 'KS' WHEN 'GZ' THEN 'MOR' WHEN 'SL' THEN 'SPL' ELSE a.SRC_SYS_CD END 
AND s.BASEL_ACCT_ID=a.BASEL_ACCT_ID 
LEFT JOIN 
EDRTLRP1D.BASEL_PSNL_LOAN_MTH_SNAPSHOT r 
ON s.MTH_TM_ID=r.MTH_TM_ID 
AND s.SRC_SYS_CD='SPL' 
AND s.BASEL_ACCT_ID=r.BASEL_ACCT_ID 
LEFT JOIN 
EDRTLRP1D.BASEL_REVLVNG_CR_MTH_SNAPSHOT c
ON s.MTH_TM_ID=c.MTH_TM_ID 
AND s.SRC_SYS_CD='KS' 
AND s.BASEL_ACCT_ID=c.BASEL_ACCT_ID 
LEFT JOIN 
EDRTLRP1D.DT4_RT18_EST_ER_VARS d 
ON s.MTH_TM_ID=d.MTH_TM_ID 
AND s.SRC_SYS_CD=d.SRC_SYS_CD 
AND s.BASEL_ACCT_ID=d.BASEL_ACCT_ID 
WHERE s.MTH_TM_ID >= 20036 
AND s.STEP_DFLT_F = 'Y'
;

/******* ACCESS ***************/
-- Please provide full access to ID IIASSAS for table EDRTLRP1D.PIT_STATUS_PRE_STEP 