/***************************************************************************
Deployment Date: AUG 02, 2024
CHANGE TICKET: CHG0894511
JIRA: RRMSS- 3038
CHANGE: BACKUPS IN IIAS PROD
NOTE: RUN THIS BEFORE STEP_Script_3_DataPatch.xlsx
/****************************************************************************/


/************************** STEP 1 *****************************************
Change: Create table backups in IIAS PROD
****************************************************************************/

1. EDRTLRP1D.BASEL_REVLVNG_CR_BASE_DRVD_VARS
2. EDRTLRP1D.BASEL_REVLVNG_CR_ACCT_DRVD_VARS
3. EDRTLRP1D.REVLVNG_CR_OBSVTN_PT_DRVD_VAR
4. EDRTLRP1D.PD_SEG_ACCT_XREF
5. EDRTLRP1D.EAD_SEG_ACCT_XREF
6. EDRTLRP1D.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2
7. EDRTLRP1D.PSNL_LOAN_OBSVTN_PT_DRVD_VAR
8. EDRTLRP1D.BASEL_PNL_LN_PD_SEG_ACCT_XREF
9. FRG_USER_DATA.SCORED_SEGMENTED_ACCTS 
10. FRG_USER_DATA.SCORED_SEGMENTED_ACCTS_ANTQ
 


/************************* STEP 2 ***********************************************
Change: Delete data in IIAS PROD - DO NOT RUN BEFORE STEP 1 COMPLETION
*********************************************************************************/

DELETE FROM EDRTLRP1D.BASEL_REVLVNG_CR_BASE_DRVD_VARS WHERE MTH_TM_ID >= 20036 ;
DELETE FROM EDRTLRP1D.BASEL_REVLVNG_CR_ACCT_DRVD_VARS WHERE MTH_TM_ID >= 20036;
DELETE FROM EDRTLRP1D.REVLVNG_CR_OBSVTN_PT_DRVD_VAR WHERE PROCESS_MTH_TM_ID >= 20036;
DELETE FROM EDRTLRP1D.PD_SEG_ACCT_XREF WHERE MTH_TM_ID >= 20036 AND BASEL_MODEL_ID = 8003;
DELETE FROM EDRTLRP1D.EAD_SEG_ACCT_XREF WHERE MTH_TM_ID >= 20036 AND BASEL_MODEL_ID = 8004;
DELETE FROM EDRTLRP1D.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 WHERE MTH_TM_ID >= 20036 ;
DELETE FROM EDRTLRP1D.PSNL_LOAN_OBSVTN_PT_DRVD_VAR WHERE PROCESS_MTH_TM_ID >= 20036;
DELETE FROM EDRTLRP1D.BASEL_PNL_LN_PD_SEG_ACCT_XREF WHERE MTH_TM_ID >= 20036 AND BASEL_MODEL_ID = 8027;
DELETE FROM FRG_USER_DATA.SCORED_SEGMENTED_ACCTS WHERE PROCESS_DATE >= '2023-06-30';
DELETE FROM FRG_USER_DATA.SCORED_SEGMENTED_ACCTS_ANTQ WHERE PROCESS_DATE >= '2022-11-30';

