CREATE TABLE
    IF NOT EXISTS MODELS.CC_LGDD_SEGMENT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        VAR_NAME VARCHAR,
        VAR_INPUT VARCHAR,
        VAR_SEGMENT INTEGER,
        MODEL VARCHAR NOT NULL,
        STREAM VARCHAR
    )
;

ALTER TABLE MODELS.CC_LGDD_SEGMENT
SET
    PARTITIONED BY (OBSN_DT, MODEL)
;