CREATE TABLE
    IF NOT EXISTS MODELS.DTL_PD_SEGMENT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        VAR_NAME VARCHAR,
        VAR_SCORE INTEGER,
        VAR_INPUT VARCHAR,
        VAR_BIN INTEGER,
        VAR_SEGMENT INTEGER,
        STREAM VARCHAR,
        MODEL VARCHAR NOT NULL
    )
;

ALTER TABLE MODELS.DTL_PD_SEGMENT
SET
    PARTITIONED BY (OBSN_DT, MODEL)
;