CREATE TABLE
    IF NOT EXISTS MODELS.TNG_MOR_LGDND_SEGMENT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        VAR_NAME VARCHAR,
        VAR_INPUT VARCHAR,
        VAR_SEGMENT INTEGER,
        MODEL VARCHAR NOT NULL,
        STREAM VARCHAR
    )
;

ALTER TABLE MODELS.TNG_MOR_LGDND_SEGMENT
SET
    PARTITIONED BY (OBSN_DT, MODEL)
;