INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'AIRB_DR@scotiabank.com',N'AIRB_DR@scotiabank.com',N'AIRB_DR@scotiabank.com',N'AIRB_DR@scotiabank.com',N'SYS',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'SCGLOBAL\mkao',N's5664039',N'Michelle Kao',N'michelle.kao@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s6447685',N's6447685',N'Nelly Selitser',N'Nelly.Selitser@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'Carol.Gardner@scotiabank.com',N's6469560',N'Carol.Gardner@scotiabank.com',N'Carol.Gardner@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'frank.russo@scotiabank.com',N's1902237',N'frank.russo@scotiabank.com',N'frank.russo@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s1127820',N's1127820',N'Vita Kornieva',N'vita.kornieva@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s5197480',N's5197480',N'Ganesh',N'ganeshbhagwan.patro@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'edwsupport@scotiabank.com',N'edwsupport@scotiabank.com',N'edwsupport@scotiabank.com',N'edwsupport@scotiabank.com',N'SYS',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'ganeshbhagwan.patro@scotiabank.com',N's5197480',N'ganeshbhagwan.patro@scotiabank.com',N'ganeshbhagwan.patro@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'zulfiqar.hyder@scotiabank.com',N's5979021',N'zulfiqar.hyder@scotiabank.com',N'zulfiqar.hyder@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s7457980',N's7457980',N'Eric Wolfe',N'eric.wolfe@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s1078828',N's1078828',N'Wanda Kemp',N'wanda.kemp@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'wanda.kemp@scotiabank.com',N's1078828',N'wanda.kemp@scotiabank.com',N'wanda.kemp@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s2028040',N's2028040',N'Nikhil',N'nikhilarun.gaikwad@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'nikhilarun.gaikwad@scotiabank.com',N's2028040',N'nikhilarun.gaikwad@scotiabank.com',N'nikhilarun.gaikwad@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'michelle.kao@scotiabank.com',N's5664039',N'michelle.kao@scotiabank.com',N'michelle.kao@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s2993929',N's2993929',N'Nimrat',N'nimrat.grewal@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'nimrat.grewal@scotiabank.com',N's2993929',N'nimrat.grewal@scotiabank.com',N'nimrat.grewal@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\BrMathers',N's5867517',N'Brent Mathers',N'brent.mathers@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s2354847',N's2354847',N'Sujeetha Selvaraj',N'sujeetha.selvaraj@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s2462851',N's2462851',N'Haichuan luo',N'haichuan.luo@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s6293237',N's6293237',N'liliya kuznetsova',N'liliya.kuznetsova@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s6469560',N's6469560',N'Carol Gardner',N'Carol.Gardner@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\shyder',N's5979021',N'Zulfiqar Hyder',N'zulfiqar.hyder@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\FRusso',N's1902237',N'Frank Russo',N'frank.russo@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'EDL-applicationsupport@scotiabank.com',N'EDL-applicationsupport@scotiabank.com',N'EDL-applicationsupport@scotiabank.com',N'EDL-applicationsupport@scotiabank.com',N'SYS',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'eric.wolfe@scotiabank.com',N's7457980',N'eric.wolfe@scotiabank.com',N'eric.wolfe@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);
INSERT INTO AIRB_RECON.dbo.Online_Users_Info VALUES (N'BNS\s5750443',N's5750443',N'Michel Valentik',N'michel.valentik@scotiabank.com',N'IND',N'Y',NULL,NULL,NULL,NULL);