ALTER TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP
	ADD COLUMN CLP_FLAG VARCHAR(1); 

ALTER TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP
	ADD COLUMN CLP_FLAG VARCHAR(1); 

ALTER TABLE EDRTLRP1D.RRAP_CCAR_ACAP_FILES
	ADD COLUMN CLP_FLAG VARCHAR(1); 

ALTER TABLE EDRTLRP1D.BASEL_ACCT_PRFM_FACT
	ADD COLUMN LNK_TO_STEP VARCHAR(1); 