ALTER TABLE
      EDRTLRP1D.DT4_RT18_EST_ER_VARS
ADD
      COLUMN BCAR_SCHED_NUM CHAR(3);

ALTER TABLE
      EDRTLRP1D.DT4_RT18_EST_ER_VARS
ADD
      COLUMN BCAR_SCHED_NM VARCHAR(150);

ALTER TABLE
      EDRTLRP1D.DT4_RT18_EST_ER_VARS
ADD
      COLUMN BCAR_SCHED_NUM_50 VARCHAR(10);