CREATE TABLE
    IF NOT EXISTS FEATURES.ACCRL_STAT_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCRL_STAT_F VARCHAR
    )
;

ALTER TABLE FEATURES.ACCRL_STAT_F
SET
    PARTITIONED BY (OBSN_DT)
;