CREATE TABLE
    IF NOT EXISTS FEATURES.ACCT_NUM_RECVD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCT_NUM_RECVD BIGINT
    )
;

ALTER TABLE FEATURES.ACCT_NUM_RECVD
SET
    PARTITIONED BY (OBSN_DT)
;