CREATE TABLE
    IF NOT EXISTS FEATURES.ACCT_NUM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        ACCT_NUM VARCHAR
    )
;

ALTER TABLE FEATURES.ACCT_NUM
SET
    PARTITIONED BY (OBSN_DT)
;