CREATE TABLE
    IF NOT EXISTS FEATURES.ACCT_MATCHED_PCTG (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        ACCT_MATCHED_PCTG DECIMAL(18,12)
    )
;

ALTER TABLE FEATURES.ACCT_MATCHED_PCTG
SET
    PARTITIONED BY (OBSN_DT)
;