CREATE TABLE
    IF NOT EXISTS FEATURES.ACCT_NUM_RRAP (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCT_NUM_RRAP VARCHAR
    )
;

ALTER TABLE FEATURES.ACCT_NUM_RRAP
SET
    PARTITIONED BY (OBSN_DT)
;