CREATE TABLE
    IF NOT EXISTS FEATURES.ACCT_SENRTY_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCT_SENRTY_CD INT
    )
;

ALTER TABLE FEATURES.ACCT_SENRTY_CD
SET
    PARTITIONED BY (OBSN_DT)
;