CREATE TABLE
    IF NOT EXISTS FEATURES.ACCT_ODT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        ACCT_ODT VARCHAR
    );

ALTER TABLE FEATURES.ACCT_ODT
SET
    PARTITIONED BY (OBSN_DT)
;