CREATE TABLE
    IF NOT EXISTS FEATURES.ADJUSTED_OS_BAL_AMT_SECURITIZATION (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_NUMBER BIGINT,
        ADJUSTED_OS_BAL_AMT_SECURITIZATION DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.ADJUSTED_OS_BAL_AMT_SECURITIZATION
SET
    PARTITIONED BY (OBSN_DT)
;