CREATE TABLE
    IF NOT EXISTS features.ADJUSTED_OS_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        ADJUSTED_OS_BAL_AMT DECIMAL(38,8)
    )
;

ALTER TABLE features.ADJUSTED_OS_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;