CREATE TABLE
    IF NOT EXISTS features.ADVNC_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        ADVNC_AMT DECIMAL(18,8)
    )
;

ALTER TABLE features.ADVNC_AMT
SET
    PARTITIONED BY (OBSN_DT)
;