CREATE TABLE
    IF NOT EXISTS FEATURES.AF_ADJ_OS_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        AF_ADJ_OS_BAL_AMT DECIMAL(17,3),
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.AF_ADJ_OS_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;