CREATE TABLE
    IF NOT EXISTS FEATURES.AF_SECRTZTN_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        AF_SECRTZTN_BAL_AMT DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.AF_SECRTZTN_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;