CREATE TABLE
    IF NOT EXISTS FEATURES.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        AF_ZERO_NET_ADJUSTED_OS_BAL_AMT DECIMAL(20,8)
    )
;

ALTER TABLE FEATURES.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;