CREATE TABLE
    IF NOT EXISTS FEATURES.AF_ZERO_NET_DRAWN_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        AF_ZERO_NET_DRAWN_AMT DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.AF_ZERO_NET_DRAWN_AMT
SET
    PARTITIONED BY (OBSN_DT)
;