CREATE TABLE
    IF NOT EXISTS FEATURES.AMORT_LEFT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        AMORT_LEFT INTEGER
    )
;

ALTER TABLE FEATURES.AMORT_LEFT
SET
    PARTITIONED BY (OBSN_DT)
;