-- AMORT feature definition
CREATE TABLE IF NOT EXISTS features.AMORT (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    AMORT INTEGER
);
-- Set partitions 
ALTER TABLE features.AMORT SET PARTITIONED BY (OBSN_DT);
