CREATE TABLE IF NOT EXISTS features.ASST_CL_DESC(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    ASST_CL_DESC VARCHAR
);

ALTER TABLE features.ASST_CL_DESC 
SET PARTITIONED BY (OBSN_DT);