CREATE TABLE
    IF NOT EXISTS FEATURES.ASST_CL_NUM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ASST_CL_NUM SMALLINT
    )
;

ALTER TABLE FEATURES.ASST_CL_NUM
SET
    PARTITIONED BY (OBSN_DT)
;