CREATE TABLE
    IF NOT EXISTS FEATURES.AT02_AVG3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT02_AVG3M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.AT02_AVG3M
SET
    PARTITIONED BY (OBSN_DT)
;