CREATE TABLE
    IF NOT EXISTS FEATURES.AT147_MIN6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT147_MIN6M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.AT147_MIN6M
SET
    PARTITIONED BY (OBSN_DT)
;

