CREATE TABLE
    IF NOT EXISTS FEATURES.AT147 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT147 DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.AT147
SET
    PARTITIONED BY (OBSN_DT)
;

