CREATE TABLE
    IF NOT EXISTS features.AT22 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT22 INTEGER
    )
;

ALTER TABLE features.AT22
SET
    PARTITIONED BY (OBSN_DT)
;