CREATE TABLE
    IF NOT EXISTS FEATURES.AT29_MAX12M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT29_MAX12M INTEGER
    )
;

ALTER TABLE FEATURES.AT29_MAX12M
SET
    PARTITIONED BY (OBSN_DT)
;