CREATE TABLE
    IF NOT EXISTS FEATURES.AT29_AVG6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT29_AVG6M DECIMAL(18,3)
    )
;

ALTER TABLE FEATURES.AT29_AVG6M
SET
    PARTITIONED BY (OBSN_DT)
;