CREATE TABLE
    IF NOT EXISTS FEATURES.AT29 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT29 INT
    )
;

ALTER TABLE FEATURES.AT29
SET
    PARTITIONED BY (OBSN_DT)
;