CREATE TABLE
    IF NOT EXISTS FEATURES.AT34_MAX12M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT34_MAX12M INTEGER
    )
;

ALTER TABLE FEATURES.AT34_MAX12M
SET PARTITIONED BY (OBSN_DT);