CREATE TABLE IF NOT EXISTS features.AT34_AVG6M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    AT34_AVG6M DECIMAL(18,4)
);

ALTER TABLE features.AT34_AVG6M
SET PARTITIONED BY (OBSN_DT);