CREATE TABLE IF NOT EXISTS features.AT34_MAX6M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    AT34_MAX6M DECIMAL(18,3)
);

ALTER TABLE features.AT34_MAX6M
SET PARTITIONED BY (OBSN_DT);