CREATE TABLE
    IF NOT EXISTS FEATURES.AT41 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT41 INTEGER
    )
;

ALTER TABLE FEATURES.AT41
SET
    PARTITIONED BY (OBSN_DT)
;