CREATE TABLE
    IF NOT EXISTS FEATURES.AT43 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT43 INTEGER
    )
;

ALTER TABLE FEATURES.AT43
SET
    PARTITIONED BY (OBSN_DT)
;