CREATE TABLE
    IF NOT EXISTS FEATURES.AT74 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT74 INTEGER
    )
;

ALTER TABLE FEATURES.AT74
SET
    PARTITIONED BY (OBSN_DT)
;

