CREATE TABLE
    IF NOT EXISTS FEATURES.AT83 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT83 INTEGER
    )
;

ALTER TABLE FEATURES.AT83
SET
    PARTITIONED BY (OBSN_DT)
;

