CREATE TABLE IF NOT EXISTS features.AT84_SUM12M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    AT84_SUM12M DECIMAL(18,4)
);

ALTER TABLE features.AT84_SUM12M
SET PARTITIONED BY (OBSN_DT);