CREATE TABLE
    IF NOT EXISTS FEATURES.AT85 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT85 INTEGER
    )
;

ALTER TABLE FEATURES.AT85
SET
    PARTITIONED BY (OBSN_DT)
;