CREATE TABLE
    IF NOT EXISTS FEATURES.AT86_AVG6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT86_AVG6M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.AT86_AVG6M
SET
    PARTITIONED BY (OBSN_DT)
;

