CREATE TABLE
    IF NOT EXISTS FEATURES.AT91 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT91 INTEGER
    )
;

ALTER TABLE FEATURES.AT91
SET
    PARTITIONED BY (OBSN_DT)
;