CREATE TABLE
    IF NOT EXISTS FEATURES.AT93 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT93 INTEGER
    )
;

ALTER TABLE FEATURES.AT93
SET
    PARTITIONED BY (OBSN_DT)
;

