CREATE TABLE
    IF NOT EXISTS FEATURES.AT94_SUM3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT94_SUM3M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.AT94_SUM3M
SET
    PARTITIONED BY (OBSN_DT)
;

