CREATE TABLE
    IF NOT EXISTS FEATURES.AT94_MIN24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        AT94_MIN24M DECIMAL(38, 3)
    )
;

ALTER TABLE FEATURES.AT94_MIN24M
SET
    PARTITIONED BY (OBSN_DT)
;