CREATE TABLE IF NOT EXISTS features.AUTH_AMT(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    AUTH_AMT DECIMAL(28,8)
);

ALTER TABLE features.AUTH_AMT 
SET PARTITIONED BY (OBSN_DT);