CREATE TABLE IF NOT EXISTS features.BAD_PAYER_IND(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    BAD_PAYER_IND CHARACTER
);

ALTER TABLE features.BAD_PAYER_IND
SET PARTITIONED BY (OBSN_DT);