CREATE TABLE IF NOT EXISTS features.BAL_HIST_CSH_ADV_KSC(
 BASEL_CUST_ID BIGINT NOT NULL,
 OBSN_DT DATE NOT NULL,
 BAL_HIST_CSH_ADV_KSC DECIMAL(18,4)
);

ALTER TABLE features.BAL_HIST_CSH_ADV_KSC SET PARTITIONED BY (OBSN_DT);