CREATE TABLE IF NOT EXISTS features.BAL_HIST_CSH_ADV_KSC_AVG12M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    BAL_HIST_CSH_ADV_KSC_AVG12M DECIMAL(18,4)
);

ALTER TABLE features.BAL_HIST_CSH_ADV_KSC_AVG12M
SET PARTITIONED BY (OBSN_DT);