CREATE TABLE IF NOT EXISTS features.BAL_HIST_CSH_ADV_KSA_MIN3M(
 BASEL_ACCT_ID BIGINT NOT NULL,
 OBSN_DT DATE NOT NULL,
 BAL_HIST_CSH_ADV_KSA_MIN3M DECIMAL(18,4)
);

ALTER TABLE features.BAL_HIST_CSH_ADV_KSA_MIN3M SET PARTITIONED BY (OBSN_DT);