CREATE TABLE IF NOT EXISTS FEATURES.BALANCE_INTEREST (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    ACCOUNT_ID VARCHAR NOT NULL,
    BALANCE_INTEREST DECIMAL(12,2)
)
;

ALTER TABLE FEATURES.BALANCE_INTEREST
SET
    PARTITIONED BY (OBSN_DT)
;
