CREATE TABLE
    IF NOT EXISTS FEATURES.BASEL_ACCT_ID_CCAR_MATCHED (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        BASEL_ACCT_ID_CCAR_MATCHED BIGINT
    )
;

ALTER TABLE FEATURES.BASEL_ACCT_ID_CCAR_MATCHED
SET
    PARTITIONED BY (OBSN_DT)
;