CREATE TABLE IF NOT EXISTS features.BASEL_PRD_ABR(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    BASEL_PRD_ABR VARCHAR
);

ALTER TABLE features.BASEL_PRD_ABR 
SET PARTITIONED BY (OBSN_DT);