CREATE TABLE IF NOT EXISTS features.BASEL_ACCT_ID(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR
);

ALTER TABLE features.BASEL_ACCT_ID 
SET PARTITIONED BY (OBSN_DT);