CREATE TABLE IF NOT EXISTS features.BASEL_CIF_KEY(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    BASEL_CIF_KEY VARCHAR
);

ALTER TABLE features.BASEL_CIF_KEY 
SET PARTITIONED BY (OBSN_DT);