CREATE TABLE
    IF NOT EXISTS FEATURES.BASEL_PRD_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BASEL_PRD_CD VARCHAR,
        BASEL_PRD_DESC VARCHAR
    )
;

ALTER TABLE FEATURES.BASEL_PRD_CD
SET
    PARTITIONED BY (OBSN_DT)
;