CREATE TABLE
    IF NOT EXISTS FEATURES.BASEL_PRD_TP_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        BASEL_PRD_TP_CD VARCHAR
    )
;

ALTER TABLE FEATURES.BASEL_PRD_TP_CD
SET
    PARTITIONED BY (OBSN_DT)
;