CREATE TABLE IF NOT EXISTS features.BC33_MAX12M (
    BASEL_CUST_ID BIGINT NOT NULL,
    OBSN_DT DATE NOT NULL,
    BC33_MAX12M DECIMAL
);

-- Set partitions
ALTER TABLE features.BC33_MAX12M SET PARTITIONED BY (OBSN_DT);
