CREATE TABLE IF NOT EXISTS features.BC33_AVG6M (
    BASEL_CUST_ID BIGINT NOT NULL,
    OBSN_DT DATE NOT NULL,
    BC33_AVG6M DECIMAL(11,4)
);

-- Set partitions
ALTER TABLE features.BC33_AVG6M SET PARTITIONED BY (OBSN_DT);
