CREATE TABLE
    IF NOT EXISTS FEATURES.BC33 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BC33 DECIMAL
    )
;

ALTER TABLE FEATURES.BC33
SET
    PARTITIONED BY (OBSN_DT)
;

