CREATE TABLE IF NOT EXISTS features.BCAR_SCHED_NUM (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    BCAR_SCHED_NUM VARCHAR,
    SRC_SYS_CD VARCHAR
);
 
ALTER TABLE features.BCAR_SCHED_NUM
SET PARTITIONED BY (OBSN_DT);