CREATE TABLE IF NOT EXISTS features.BCAR_SCHED_NM (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    BCAR_SCHED_NM VARCHAR,
    SRC_SYS_CD VARCHAR
);
 
ALTER TABLE features.BCAR_SCHED_NM
SET PARTITIONED BY (OBSN_DT);