CREATE TABLE IF NOT EXISTS features.BI33_MAX24M (
    BASEL_CUST_ID BIGINT NOT NULL,
    OBSN_DT DATE NOT NULL,
    BI33_MAX24M DECIMAL(18,4)
);

-- Set partitions
ALTER TABLE features.BI33_MAX24M SET PARTITIONED BY (OBSN_DT);
