CREATE TABLE IF NOT EXISTS features.BI33_MAX3M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    BI33_MAX3M INTEGER
);

-- Set partitions
ALTER TABLE features.BI33_MAX3M SET PARTITIONED BY (OBSN_DT);
