CREATE TABLE
    IF NOT EXISTS FEATURES.BNKRPY_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BNKRPY_F VARCHAR
    )
;

ALTER TABLE FEATURES.BNKRPY_F
SET
    PARTITIONED BY (OBSN_DT)
;