CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DLQNT_DAY_GP_KSC_MAX6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BNS_DLQNT_DAY_GP_KSC_MAX6M INTEGER
    )
;

ALTER TABLE FEATURES.BNS_DLQNT_DAY_GP_KSC_MAX6M
SET
    PARTITIONED BY (OBSN_DT)
;