CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DLQNT_DAY_GP_KSC (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BNS_DLQNT_DAY_GP_KSC DECIMAL(18,3)
    )
;

ALTER TABLE FEATURES.BNS_DLQNT_DAY_GP_KSC
SET
    PARTITIONED BY (OBSN_DT)
;