CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DLQNT_DAY_GP_KSA_MAX24M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BNS_DLQNT_DAY_GP_KSA_MAX24M INTEGER
    )
;

ALTER TABLE FEATURES.BNS_DLQNT_DAY_GP_KSA_MAX24M
SET
    PARTITIONED BY (OBSN_DT)
;