CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DLQNT_DAY_GP_KSA (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BNS_DLQNT_DAY_GP_KSA INTEGER
    )
;

ALTER TABLE FEATURES.BNS_DLQNT_DAY_GP_KSA
SET
    PARTITIONED BY (OBSN_DT)
;