CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DAY_DLQNT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BNS_DAY_DLQNT INTEGER
    )
;

ALTER TABLE FEATURES.BNS_DAY_DLQNT
SET
    PARTITIONED BY (OBSN_DT)
;