CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DAY_DLQNT_KSC (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BNS_DAY_DLQNT_KSC INTEGER
    )
;

ALTER TABLE FEATURES.BNS_DAY_DLQNT_KSC
SET
    PARTITIONED BY (OBSN_DT)
;