CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DLQNT_DAY_GP_KSA_MAX3M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BNS_DLQNT_DAY_GP_KSA_MAX3M INTEGER
    )
;

ALTER TABLE FEATURES.BNS_DLQNT_DAY_GP_KSA_MAX3M
SET
    PARTITIONED BY (OBSN_DT)
;
