CREATE TABLE
    IF NOT EXISTS FEATURES.BNS_DLQNT_DAY_GP_KSC_AVG12M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BNS_DLQNT_DAY_GP_KSC_AVG12M DECIMAL(31,4)
    )
;

ALTER TABLE FEATURES.BNS_DLQNT_DAY_GP_KSC_AVG12M
SET
    PARTITIONED BY (OBSN_DT)
;