CREATE TABLE
    IF NOT EXISTS FEATURES.BR147_MAX3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BR147_MAX3M INTEGER
    )
;

ALTER TABLE FEATURES.BR147_MAX3M
SET
    PARTITIONED BY (OBSN_DT)
;