CREATE TABLE
    IF NOT EXISTS FEATURES.BR147_MIN3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BR147_MIN3M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.BR147_MIN3M
SET
    PARTITIONED BY (OBSN_DT)
;
