CREATE TABLE IF NOT EXISTS features.BR34_MAX6M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    BR34_MAX6M INTEGER
);
-- Set partitions 
ALTER TABLE features.BR34_MAX6M SET PARTITIONED BY (OBSN_DT);