CREATE TABLE
    IF NOT EXISTS FEATURES.BR34_AVG3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BR34_AVG3M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.BR34_AVG3M
SET
    PARTITIONED BY (OBSN_DT)
;

