CREATE TABLE IF NOT EXISTS features.BY34_MAX12M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    BY34_MAX12M DECIMAL(18,3)
);

ALTER TABLE features.BY34_MAX12M
SET PARTITIONED BY (OBSN_DT);