CREATE TABLE IF NOT EXISTS features.BY34_MAX3M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    BY34_MAX3M DECIMAL(18,3)
);

ALTER TABLE features.BY34_MAX3M 
SET PARTITIONED BY (OBSN_DT);