CREATE TABLE
    IF NOT EXISTS features.CAB_TRNST_NUM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        CAB_TRNST_NUM VARCHAR
    );

ALTER TABLE features.CAB_TRNST_NUM
SET
    PARTITIONED BY (OBSN_DT)
;