CREATE TABLE IF NOT EXISTS features.CC_TRANSACTOR_F(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    CC_TRANSACTOR_F VARCHAR NOT NULL
);

ALTER TABLE features.CC_TRANSACTOR_F
SET PARTITIONED BY (OBSN_DT);