CREATE TABLE IF NOT EXISTS features.CCAR_EXPSR_CL_NM(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    CCAR_EXPSR_CL_NM VARCHAR,
    SRC_SYS_CD VARCHAR NOT NULL
);

ALTER TABLE features.CCAR_EXPSR_CL_NM
SET PARTITIONED BY (OBSN_DT);