CREATE TABLE IF NOT EXISTS features.CLP_FLAG(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    CLP_FLAG VARCHAR
);

ALTER TABLE features.CLP_FLAG 
SET PARTITIONED BY (OBSN_DT);