CREATE TABLE IF NOT EXISTS features.CLP_F_B20(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    CLP_F_B20 VARCHAR
);

ALTER TABLE features.CLP_F_B20 
SET PARTITIONED BY (OBSN_DT);