CREATE TABLE IF NOT EXISTS features.CMHC_F(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    CMHC_F VARCHAR
);

ALTER TABLE features.CMHC_F 
SET PARTITIONED BY (OBSN_DT);