CREATE TABLE IF NOT EXISTS features.COLLATERAL_VALUE(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    COLLATERAL_VALUE DECIMAL(22,2)
);

ALTER TABLE features.COLLATERAL_VALUE 
SET PARTITIONED BY (OBSN_DT);