CREATE TABLE IF NOT EXISTS features.COLLATERAL_TYPE(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    COLLATERAL_TYPE VARCHAR
);

ALTER TABLE features.COLLATERAL_TYPE 
SET PARTITIONED BY (OBSN_DT);