CREATE TABLE
    IF NOT EXISTS FEATURES.COMM_F_V2 (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        COMM_F_V2 INTEGER,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.COMM_F_V2
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
