CREATE TABLE
    IF NOT EXISTS FEATURES.CONSM_PRD_TREATMNT_CD_IF (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CONSM_PRD_TREATMNT_CD_IF VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.CONSM_PRD_TREATMNT_CD_IF
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;