CREATE TABLE
    IF NOT EXISTS FEATURES.CONSM_PRD_TREATMNT_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BASEL_CUST_ID BIGINT,
        CONSM_PRD_TREATMNT_CD VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.CONSM_PRD_TREATMNT_CD
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;