CREATE TABLE
    IF NOT EXISTS FEATURES.CONSM_SCORECRD_EXCLSN_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CONSM_SCORECRD_EXCLSN_F VARCHAR
    )
;

ALTER TABLE FEATURES.CONSM_SCORECRD_EXCLSN_F
SET
    PARTITIONED BY (OBSN_DT)
;