CREATE TABLE
    IF NOT EXISTS FEATURES.CR_LMT_AMT_IF (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        CR_LMT_AMT_IF DECIMAL(17, 8)
    )
;

ALTER TABLE FEATURES.CR_LMT_AMT_IF
SET
    PARTITIONED BY (OBSN_DT)
;