CREATE TABLE
    IF NOT EXISTS FEATURES.CR_LMT_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CR_LMT_AMT DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.CR_LMT_AMT
SET
    PARTITIONED BY (OBSN_DT)
;