CREATE TABLE
    IF NOT EXISTS FEATURES.CREDIT_TRBLE_BNKRPTCY_COLL_DER (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        CREDIT_TRBLE_BNKRPTCY_COLL_DER DOUBLE
    )
;

ALTER TABLE FEATURES.CREDIT_TRBLE_BNKRPTCY_COLL_DER
SET
    PARTITIONED BY (OBSN_DT)
;