CREATE TABLE
    IF NOT EXISTS FEATURES.CSH_AD_CRNT_C_BAL_KSC_SUM3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CSH_AD_CRNT_C_BAL_KSC_SUM3M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.CSH_AD_CRNT_C_BAL_KSC_SUM3M
SET
    PARTITIONED BY (OBSN_DT)
;
