CREATE TABLE
    IF NOT EXISTS FEATURES.CSH_ADVNC_1_CYCL_BAL_SUM12M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CSH_ADVNC_1_CYCL_BAL_SUM12M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.CSH_ADVNC_1_CYCL_BAL_SUM12M
SET
    PARTITIONED BY (OBSN_DT)
;