CREATE TABLE IF NOT EXISTS features.CSH_AD_CRNT_C_BAL_KSA_SUM6M(
 BASEL_ACCT_ID BIGINT NOT NULL,
 OBSN_DT DATE NOT NULL,
 CSH_AD_CRNT_C_BAL_KSA_SUM6M DECIMAL(18,4)
);

ALTER TABLE features.CSH_AD_CRNT_C_BAL_KSA_SUM6M SET PARTITIONED BY (OBSN_DT);