CREATE TABLE
    IF NOT EXISTS FEATURES.CSH_AD_CRNT_C_BAL_KSC (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CSH_ADVNC_CRNT_CYCL_BAL_AMT DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.CSH_AD_CRNT_C_BAL_KSC
SET
    PARTITIONED BY (OBSN_DT)
;