CREATE TABLE
    IF NOT EXISTS FEATURES.CSH_ADVNC_1_CYCL_AGO_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CSH_ADVNC_1_CYCL_AGO_BAL_AMT DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.CSH_ADVNC_1_CYCL_AGO_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;