CREATE TABLE
    IF NOT EXISTS FEATURES.CU115 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CU115 INT
    )
;

ALTER TABLE FEATURES.CU115
SET
    PARTITIONED BY (OBSN_DT)
;