CREATE TABLE IF NOT EXISTS features.CURRENCY_MISMATCH_F(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    CURRENCY_MISMATCH_F VARCHAR
);

ALTER TABLE features.CURRENCY_MISMATCH_F 
SET PARTITIONED BY (OBSN_DT);
