CREATE TABLE
    IF NOT EXISTS FEATURES.CURRENT_BAL (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CURRENT_BAL DOUBLE,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.CURRENT_BAL
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
