CREATE TABLE
    IF NOT EXISTS FEATURES.CUST19 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST19 INTEGER
    )
;

ALTER TABLE FEATURES.CUST19
SET
    PARTITIONED BY (OBSN_DT)
;