CREATE TABLE IF NOT EXISTS FEATURES.CUST22_SLP3M_V2 (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    CUST22_SLP3M_V2 DECIMAL(31,7)
);

ALTER TABLE FEATURES.CUST22_SLP3M_V2
SET PARTITIONED BY (OBSN_DT);