CREATE TABLE IF NOT EXISTS features.CUST25_MIN3M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    CUST25_MIN3M DECIMAL (20,6)
);

ALTER TABLE features.CUST25_MIN3M
SET PARTITIONED BY (OBSN_DT);