CREATE TABLE IF NOT EXISTS FEATURES.CUST24_AVG3M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    CUST24_AVG3M DECIMAL(18,4)
);

ALTER TABLE FEATURES.CUST24_AVG3M
SET PARTITIONED BY (OBSN_DT);