CREATE TABLE
    IF NOT EXISTS FEATURES.CUST18 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST18 INTEGER
    )
;

ALTER TABLE FEATURES.CUST18
SET
    PARTITIONED BY (OBSN_DT)
;