CREATE TABLE IF NOT EXISTS features.CUST32_MIN6M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    CUST32_MIN6M DECIMAL (17,3)
);

ALTER TABLE features.CUST32_MIN6M
SET PARTITIONED BY (OBSN_DT);
