CREATE TABLE IF NOT EXISTS features.CUST_BEHV_SCORE(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    CUST_BEHV_SCORE INTEGER
);

ALTER TABLE features.CUST_BEHV_SCORE 
SET PARTITIONED BY (OBSN_DT);
