CREATE TABLE IF NOT EXISTS features.CUST_ACCT_CNT (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID INTEGER NOT NULL,
    CUST_ACCT_CNT INTEGER
);
-- Set partitions 
ALTER TABLE features.CUST_ACCT_CNT SET PARTITIONED BY (OBSN_DT);
