CREATE TABLE IF NOT EXISTS FEATURES.CUST22_SLP3M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    CUST22_SLP3M DECIMAL(31,7)
);

ALTER TABLE FEATURES.CUST22_SLP3M
SET PARTITIONED BY (OBSN_DT);