CREATE TABLE
    IF NOT EXISTS FEATURES.CUST16_MAX6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST16_MAX6M INTEGER
    )
;

ALTER TABLE FEATURES.CUST16_MAX6M
SET
    PARTITIONED BY (OBSN_DT)
;