CREATE TABLE
    IF NOT EXISTS FEATURES.CUST21_MIN3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST21_MIN3M DECIMAL(31, 3)
    )
;

ALTER TABLE FEATURES.CUST21_MIN3M
SET
    PARTITIONED BY (OBSN_DT)
;
