CREATE TABLE
    IF NOT EXISTS FEATURES.CUST18_MIN24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST18_MIN24M INTEGER
    )
;

ALTER TABLE FEATURES.CUST18_MIN24M
SET
    PARTITIONED BY (OBSN_DT)
;