CREATE TABLE
    IF NOT EXISTS FEATURES.CUST21 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST21 DECIMAL(31, 3)
    )
;

ALTER TABLE FEATURES.CUST21
SET
    PARTITIONED BY (OBSN_DT)
;
