CREATE TABLE IF NOT EXISTS features.CUST22_V2 (
      OBSN_DT DATE NOT NULL,
      BASEL_CUST_ID BIGINT NOT NULL,
      CUST22_V2 DECIMAL(31,7)
  );
ALTER TABLE features.CUST22_V2
SET PARTITIONED BY (OBSN_DT);
