CREATE TABLE IF NOT EXISTS features.CUST24_MAX6M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    CUST24_MAX6M DECIMAL(18,4)
);

ALTER TABLE features.CUST24_MAX6M
SET PARTITIONED BY (OBSN_DT);