CREATE TABLE
    IF NOT EXISTS FEATURES.CUST13_MAX6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST13_MAX6M DECIMAL(12,0)
    )
;

ALTER TABLE FEATURES.CUST13_MAX6M
SET
    PARTITIONED BY (OBSN_DT)
;