CREATE TABLE
    IF NOT EXISTS FEATURES.CUST13 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST13 DECIMAL(12,0)
    )
;

ALTER TABLE FEATURES.CUST13
SET
    PARTITIONED BY (OBSN_DT)
;