CREATE TABLE IF NOT EXISTS features.CUST22 (
      OBSN_DT DATE NOT NULL,
      BASEL_CUST_ID BIGINT NOT NULL,
      CUST22 DECIMAL(31,7)
  );
ALTER TABLE features.CUST22
SET PARTITIONED BY (OBSN_DT);
