CREATE TABLE
    IF NOT EXISTS FEATURES.CUST18_V2 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST18_V2 INTEGER
    )
;

ALTER TABLE FEATURES.CUST18_V2
SET
    PARTITIONED BY (OBSN_DT)
;