CREATE TABLE
    IF NOT EXISTS FEATURES.CUST16 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        CUST16 INTEGER
    )
;

ALTER TABLE FEATURES.CUST16
SET
    PARTITIONED BY (OBSN_DT)
;