CREATE TABLE IF NOT EXISTS features.D2D_BAL_AMT_MAX12M(
OBSN_DT DATE NOT NULL,
BASEL_CUST_ID BIGINT,               
D2D_BAL_AMT_MAX12M DECIMAL(18,4)
);

ALTER TABLE features.D2D_BAL_AMT_MAX12M SET PARTITIONED BY (OBSN_DT);