CREATE TABLE IF NOT EXISTS features.D2D_BAL_AMT_P_MIN6M(
OBSN_DT DATE NOT NULL,
BASEL_ACCT_ID BIGINT NOT NULL,   
D2D_BAL_AMT_P_MIN6M DECIMAL(18,4)
);

ALTER TABLE features.D2D_BAL_AMT_P_MIN6M SET PARTITIONED BY (OBSN_DT);