CREATE TABLE
    IF NOT EXISTS FEATURES.D2D_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        D2D_BAL_AMT DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.D2D_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;