CREATE TABLE
    IF NOT EXISTS FEATURES.D2D_BAL_AMT_MIN12M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        D2D_BAL_AMT_MIN12M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.D2D_BAL_AMT_MIN12M
SET
    PARTITIONED BY (OBSN_DT)
;
