CREATE TABLE IF NOT EXISTS features.D2D_BAL_AMT_P(
OBSN_DT DATE NOT NULL,
D2D_BAL_AMT_P DECIMAL(18,4),
BASEL_ACCT_ID BIGINT NOT NULL
);

ALTER TABLE features.D2D_BAL_AMT_P SET PARTITIONED BY (OBSN_DT);