CREATE TABLE
    IF NOT EXISTS FEATURES.D2D_BAL_AMT_MIN3M (
        BASEL_CUST_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        D2D_BAL_AMT_MIN3M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.D2D_BAL_AMT_MIN3M
SET
    PARTITIONED BY (OBSN_DT)
;