CREATE TABLE IF NOT EXISTS FEATURES.DAY_ODUE_MAX6M (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    DAY_ODUE_MAX6M DECIMAL(6)
);

ALTER TABLE FEATURES.DAY_ODUE_MAX6M
SET PARTITIONED BY (OBSN_DT);