CREATE TABLE IF NOT EXISTS FEATURES.DAYS_ARREARS_CNT (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    ACCOUNT_ID VARCHAR NOT NULL,
    DAYS_ARREARS_CNT DOUBLE
)
;

ALTER TABLE FEATURES.DAYS_ARREARS_CNT
SET
    PARTITIONED BY (OBSN_DT)
;
