CREATE TABLE
    IF NOT EXISTS FEATURES.DEFAULT_IND (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSVTN_MTH_TM_ID INTEGER NOT NULL,
        DEFAULT_IND INTEGER,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.DEFAULT_IND
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
