CREATE TABLE
    IF NOT EXISTS FEATURES.DEFAULT_BAL (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSVTN_MTH_TM_ID INTEGER NOT NULL,
        DEFAULT_BAL DOUBLE,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.DEFAULT_BAL
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
