CREATE TABLE
    IF NOT EXISTS FEATURES.DEFAULT_DATE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSVTN_MTH_TM_ID INTEGER NOT NULL,
        DEFAULT_DATE DATE,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.DEFAULT_DATE
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
