CREATE TABLE
    IF NOT EXISTS FEATURES.DELTA_FOR_DRAWN_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        DELTA_FOR_DRAWN_AMT DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.DELTA_FOR_DRAWN_AMT
SET
    PARTITIONED BY (OBSN_DT)
;