CREATE TABLE
    IF NOT EXISTS FEATURES.DEP_CNT_MIN6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        DEP_CNT_MIN6M INTEGER
    )
;

ALTER TABLE FEATURES.DEP_CNT_MIN6M
SET
    PARTITIONED BY (OBSN_DT)
;