CREATE TABLE
    IF NOT EXISTS FEATURES.DEP_CNT (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        DEP_CNT INTEGER
    )
;

ALTER TABLE FEATURES.DEP_CNT
SET
    PARTITIONED BY (OBSN_DT)
;