CREATE TABLE
    IF NOT EXISTS features.DLQNT_DAY_CNT_IF (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        DLQNT_DAY_CNT_IF INTEGER,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE features.DLQNT_DAY_CNT_IF
SET
    PARTITIONED BY (OBSN_DT)
;
