CREATE TABLE IF NOT EXISTS features.DLQNT_DAY (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    DLQNT_DAY INTEGER
);
-- Set partitions 
ALTER TABLE features.DLQNT_DAY SET PARTITIONED BY (OBSN_DT);
