CREATE TABLE IF NOT EXISTS features.DLQNT_STG (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    DLQNT_STG INTEGER
);
-- Set partitions 
ALTER TABLE features.DLQNT_STG SET PARTITIONED BY (OBSN_DT);