CREATE TABLE
    IF NOT EXISTS FEATURES.DLQNT_MTH_CNT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        DLQNT_MTH_CNT INTEGER,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.DLQNT_MTH_CNT
SET
    PARTITIONED BY (OBSN_DT)
;
