CREATE TABLE IF NOT EXISTS FEATURES.DLQNT_MTH_MAX24M (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    DLQNT_MTH_MAX24M INTEGER
);
-- SET PARTITIONS 
ALTER TABLE FEATURES.DLQNT_MTH_MAX24M SET PARTITIONED BY (OBSN_DT);