CREATE TABLE IF NOT EXISTS features.DLQNT_MTH (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    DLQNT_MTH INTEGER
);
-- Set partitions 
ALTER TABLE features.DLQNT_MTH SET PARTITIONED BY (OBSN_DT);