CREATE TABLE
    IF NOT EXISTS FEATURES.E_MAT_DT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        E_MAT_DT DATE
    )
;

ALTER TABLE FEATURES.E_MAT_DT
SET
    PARTITIONED BY (OBSN_DT)
;