CREATE TABLE IF NOT EXISTS features.EGL_DEPRTMNT(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    EGL_DEPRTMNT VARCHAR
);

ALTER TABLE features.EGL_DEPRTMNT 
SET PARTITIONED BY (OBSN_DT);