CREATE TABLE IF NOT EXISTS features.END_PRINCIPAL_BALANCE (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    END_PRINCIPAL_BALANCE DECIMAL(17,3)
);
-- Set partitions 
ALTER TABLE features.END_PRINCIPAL_BALANCE SET PARTITIONED BY (OBSN_DT);