CREATE TABLE IF NOT EXISTS FEATURES.EVER_30_CNT (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    ACCOUNT_ID VARCHAR NOT NULL,
    EVER_30_CNT BIGINT
)
;

ALTER TABLE FEATURES.EVER_30_CNT
SET
    PARTITIONED BY (OBSN_DT)
;
