CREATE TABLE IF NOT EXISTS features.FINAL_RTO (
    BASEL_ACCT_ID BIGINT NOT NULL,
    OBSN_DT DATE NOT NULL,
    FINAL_RTO DECIMAL(28,8),
    STREAM VARCHAR
);
 
ALTER TABLE features.FINAL_RTO
SET PARTITIONED BY (OBSN_DT);