CREATE TABLE IF NOT EXISTS features.GENL_LEDGER_BALCNG_ADJ_AMT(
    OBSN_DT DATE NOT NULL,
    SRC_SYS_CD VARCHAR,
    BASEL_ACCT_ID BIGINT NOT NULL,
    GENL_LEDGER_BALCNG_ADJ_AMT DECIMAL(38,3)
);

ALTER TABLE features.GENL_LEDGER_BALCNG_ADJ_AMT 
SET PARTITIONED BY (OBSN_DT);