CREATE TABLE
    IF NOT EXISTS FEATURES.GO04_MAX24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO04_MAX24M INTEGER
    )
;

ALTER TABLE FEATURES.GO04_MAX24M
SET
    PARTITIONED BY (OBSN_DT)
;

