CREATE TABLE
    IF NOT EXISTS FEATURES.GO04_AVG6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO04_AVG6M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.GO04_AVG6M
SET
    PARTITIONED BY (OBSN_DT)
;
