CREATE TABLE IF NOT EXISTS features.GO04 (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    GO04 INTEGER
);
-- Set partitions 
ALTER TABLE features.GO04 SET PARTITIONED BY (OBSN_DT);
