CREATE TABLE IF NOT EXISTS FEATURES.GO04_MAX6M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    GO04_MAX6M INTEGER
);
-- SET PARTITIONS 
ALTER TABLE FEATURES.GO04_MAX6M SET PARTITIONED BY (OBSN_DT);