CREATE TABLE IF NOT EXISTS features.GO05_MAX3M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    GO05_MAX3M DECIMAL(11,4)
);

ALTER TABLE features.GO05_MAX3M
SET
    PARTITIONED BY (OBSN_DT);