CREATE TABLE IF NOT EXISTS features.GO06MAX12M (
    BASEL_CUST_ID BIGINT NOT NULL,
    OBSN_DT DATE NOT NULL,
    GO06MAX12M DECIMAL(11,4)
);

-- Set partitions
ALTER TABLE features.GO06MAX12M SET PARTITIONED BY (OBSN_DT);
