CREATE TABLE IF NOT EXISTS features.GO06_MAX6M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    GO06_MAX6M INT
);

-- Set partitions
ALTER TABLE features.GO06_MAX6M SET PARTITIONED BY (OBSN_DT);
