CREATE TABLE
    IF NOT EXISTS FEATURES.GO06_AVG12M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO06_AVG12M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.GO06_AVG12M
SET
    PARTITIONED BY (OBSN_DT)
;
