CREATE TABLE IF NOT EXISTS features.GO06_MAX3M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    GO06_MAX3M DECIMAL(11,4)
);

-- Set partitions
ALTER TABLE features.GO06_MAX3M SET PARTITIONED BY (OBSN_DT);
