CREATE TABLE
    IF NOT EXISTS FEATURES.GO06 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO06 DECIMAL(2)
    )
;

ALTER TABLE FEATURES.GO06
SET
    PARTITIONED BY (OBSN_DT)
;