CREATE TABLE IF NOT EXISTS features.GO06_AVG24M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    GO06_AVG24M DECIMAL(11,4)
);

-- Set partitions
ALTER TABLE features.GO06_AVG24M SET PARTITIONED BY (OBSN_DT);
