CREATE TABLE
    IF NOT EXISTS FEATURES.GO11_MAX24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO11_MAX24M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.GO11_MAX24M
SET
    PARTITIONED BY (OBSN_DT)
;