CREATE TABLE
    IF NOT EXISTS FEATURES.GO11_MIN3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO11_MIN3M DECIMAL(5,2)
    )
;

ALTER TABLE FEATURES.GO11_MIN3M
SET
    PARTITIONED BY (OBSN_DT)
;
