CREATE TABLE
    IF NOT EXISTS FEATURES.GO11_MAX6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO11_MAX6M INTEGER
    )
;

ALTER TABLE FEATURES.GO11_MAX6M
SET
    PARTITIONED BY (OBSN_DT)
;

