CREATE TABLE
    IF NOT EXISTS FEATURES.GO11_AVG24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO11_AVG24M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.GO11_AVG24M
SET
    PARTITIONED BY (OBSN_DT)
;

