CREATE TABLE
    IF NOT EXISTS FEATURES.GO11_MIN12M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        GO11_MIN12M INTEGER
    )
;

ALTER TABLE FEATURES.GO11_MIN12M
SET
    PARTITIONED BY (OBSN_DT)
;

