-- -- HELOC_F feature definition
-- CREATE TABLE IF NOT EXISTS features.HELOC_F (
--     OBSN_DT BIGINT,
--     BASEL_ACCT_ID BIGINT,
--     STEP_PLN_SNAPSHOT_ID BIGINT,
--     SUB_PRD_CD VARCHAR,
--     HELOC_F VARCHAR
-- );
-- -- Set partitions 
-- ALTER TABLE features.HELOC_F SET PARTITIONED BY (MTH_TM_ID);
-- -- Changed columns (below) added to top CREATE but won't be applied
-- ALTER TABLE features.HELOC_F ADD COLUMN IF NOT EXISTS MTH_TM_ID BIGINT;
-- ALTER TABLE features.HELOC_F ADD COLUMN IF NOT EXISTS STEP_PLN_SNAPSHOT_ID BIGINT;
-- ALTER TABLE features.HELOC_F ADD COLUMN IF NOT EXISTS SUB_PRD_CD VARCHAR;
-- ALTER TABLE features.HELOC_F DROP COLUMN IF EXISTS OBSN_DT;
-- ALTER TABLE features.HELOC_F ALTER COLUMN BASEL_ACCT_ID SET TYPE BIGINT;
CREATE TABLE
    IF NOT EXISTS FEATURES.HELOC_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        HELOC_F VARCHAR
    )
;

ALTER TABLE FEATURES.HELOC_F
SET
    PARTITIONED BY (OBSN_DT)
;