CREATE TABLE
    IF NOT EXISTS FEATURES.HGST_DLQNT_DAY_MTG_MAX24M_ACCT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        HGST_DLQNT_DAY_MTG_MAX24M_ACCT INTEGER
    )
;

ALTER TABLE FEATURES.HGST_DLQNT_DAY_MTG_MAX24M_ACCT
SET
    PARTITIONED BY (OBSN_DT)
;
