CREATE TABLE
    IF NOT EXISTS FEATURES.HGST_DLQNT_DAY (
        OBSN_DT DATE NOT NULL,
        MORT_NUM BIGINT NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        HGST_DLQNT_DAY INTEGER
    )
;

ALTER TABLE FEATURES.HGST_DLQNT_DAY
SET
    PARTITIONED BY (OBSN_DT)
;