CREATE TABLE
    IF NOT EXISTS FEATURES.HGST_DLQNT_DAY_COMB_MAX24M (
        BASEL_CUST_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        HGST_DLQNT_DAY_COMB_MAX24M INTEGER
    )
;

ALTER TABLE FEATURES.HGST_DLQNT_DAY_COMB_MAX24M
SET
    PARTITIONED BY (OBSN_DT)
;

