CREATE TABLE
    IF NOT EXISTS features.HOUSE_TP_NM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        HOUSE_TP_NM VARCHAR
    )
;

ALTER TABLE features.HOUSE_TP_NM
SET
    PARTITIONED BY (OBSN_DT)
;