CREATE TABLE
    IF NOT EXISTS FEATURES.INACT_12M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        INACT_12M VARCHAR
    )
;

ALTER TABLE FEATURES.INACT_12M
SET
    PARTITIONED BY (OBSN_DT)
;