CREATE TABLE
    IF NOT EXISTS FEATURES.INACT_6M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        INACT_6M VARCHAR
    )
;

ALTER TABLE FEATURES.INACT_6M
SET
    PARTITIONED BY (OBSN_DT)
;
