CREATE TABLE IF NOT EXISTS FEATURES.IND_DELQ_SUM24M(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    IND_DELQ_SUM24M INTEGER
);

ALTER TABLE FEATURES.IND_DELQ_SUM24M
SET PARTITIONED BY(OBSN_DT);