CREATE TABLE IF NOT EXISTS features.IND_DELQ_MAX24M(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    IND_DELQ_MAX24M INTEGER
);

ALTER TABLE features.IND_DELQ_MAX24M
SET PARTITIONED BY(OBSN_DT);