CREATE TABLE
    IF NOT EXISTS features.INDEXED_LTV_ACCT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        INDEXED_LTV_ACCT DECIMAL(18,17)
    );

ALTER TABLE features.INDEXED_LTV_ACCT
SET
    PARTITIONED BY (OBSN_DT);