CREATE TABLE
    IF NOT EXISTS FEATURES.INS_ID_GROUP (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        INS_ID_GROUP DOUBLE
    )
;

ALTER TABLE FEATURES.INS_ID_GROUP
SET
    PARTITIONED BY (OBSN_DT)
;