CREATE TABLE
    IF NOT EXISTS FEATURES.INSURANCE_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        INSURANCE_F VARCHAR
    )
;

ALTER TABLE FEATURES.INSURANCE_F
SET
    PARTITIONED BY (OBSN_DT)
;