CREATE TABLE IF NOT EXISTS features.INVSTM_ACCT_AMT_INV(
 BASEL_CUST_ID BIGINT NOT NULL,
 OBSN_DT DATE NOT NULL,
 INVSTM_ACCT_AMT_INV DECIMAL(18, 3)
);

ALTER TABLE features.INVSTM_ACCT_AMT_INV SET PARTITIONED BY (OBSN_DT);