CREATE TABLE
    IF NOT EXISTS FEATURES.LAND_RGSTRN_ACT_STAT_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        LAND_RGSTRN_ACT_STAT_F VARCHAR
    )
;

ALTER TABLE FEATURES.LAND_RGSTRN_ACT_STAT_F
SET
    PARTITIONED BY (OBSN_DT)
;
