CREATE TABLE
    IF NOT EXISTS features.LAST_ACTY_DT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        LAST_ACTY_DT DATE
    )
;

ALTER TABLE features.LAST_ACTY_DT
SET
    PARTITIONED BY (OBSN_DT)
;