CREATE TABLE
    IF NOT EXISTS FEATURES.LAST_NEW_DFT_DT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSVTN_MTH_TM_ID INTEGER,
        LAST_NEW_DFT_DT DATE,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.LAST_NEW_DFT_DT
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
