CREATE TABLE
    IF NOT EXISTS features.LAST_PYMT_DT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        LAST_PYMT_DT DATE
    )
;

ALTER TABLE features.LAST_PYMT_DT
SET
    PARTITIONED BY (OBSN_DT)
;