CREATE TABLE
    IF NOT EXISTS features.LAST_RGL_PAY_DT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        LAST_RGL_PAY_DT DATE
    )
;

ALTER TABLE features.LAST_RGL_PAY_DT
SET
    PARTITIONED BY (OBSN_DT)
;