CREATE TABLE IF NOT EXISTS features.LEGAL_ENTITY(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    LEGAL_ENTITY VARCHAR
);

ALTER TABLE 
    features.LEGAL_ENTITY SET PARTITIONED BY (OBSN_DT);