CREATE TABLE IF NOT EXISTS features.LGD_S(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    LGD_S DECIMAL(18,3)
);

ALTER TABLE features.LGD_S 
SET PARTITIONED BY (OBSN_DT);