CREATE TABLE IF NOT EXISTS features.LGD_U(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    LGD_U DECIMAL(18,3)
);

ALTER TABLE features.LGD_U 
SET PARTITIONED BY (OBSN_DT);