CREATE TABLE IF NOT EXISTS features.LOAN_NUM(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    LOAN_NUM VARCHAR
);

ALTER TABLE features.LOAN_NUM 
SET PARTITIONED BY (OBSN_DT);