-- AMORT feature definition
CREATE TABLE IF NOT EXISTS features.LOAN_TERM (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    LOAN_TERM DECIMAL(6,0)
);
-- Set partitions 
ALTER TABLE features.LOAN_TERM SET PARTITIONED BY (OBSN_DT);
