CREATE TABLE
    IF NOT EXISTS FEATURES.LRA_STATUS (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        LRA_STATUS VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.LRA_STATUS
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
