CREATE TABLE
    IF NOT EXISTS FEATURES.LTV_METHOD2_FIX (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        LTV_METHOD2_FIX DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.LTV_METHOD2_FIX
SET
    PARTITIONED BY (OBSN_DT)
;

