CREATE TABLE IF NOT EXISTS features.LTV_PERCENTAGE(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    LTV_PERCENTAGE VARCHAR
);

ALTER TABLE features.LTV_PERCENTAGE 
SET PARTITIONED BY (OBSN_DT);