CREATE TABLE IF NOT EXISTS features.LTV_BUCKET(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    LTV_BUCKET VARCHAR
);

ALTER TABLE features.LTV_BUCKET 
SET PARTITIONED BY (OBSN_DT);