CREATE TABLE
    IF NOT EXISTS FEATURES.LTV_TERANET (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        LTV_TERANET DOUBLE
    )
;

ALTER TABLE FEATURES.LTV_TERANET
SET
    PARTITIONED BY (OBSN_DT)
;