CREATE TABLE
    IF NOT EXISTS FEATURES.LTV_TP_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        LTV_TP_CD VARCHAR
    )
;

ALTER TABLE FEATURES.LTV_TP_CD
SET
    PARTITIONED BY (OBSN_DT)
;