CREATE TABLE IF NOT EXISTS features.LTV_VEH10 (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    LTV_VEH10 DECIMAL(18,4)
);

ALTER TABLE features.LTV_VEH10
SET PARTITIONED BY (OBSN_DT);