CREATE TABLE
    IF NOT EXISTS FEATURES.LTV_TERANET_CMA (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        LTV_TERANET_CMA DOUBLE
    )
;

ALTER TABLE FEATURES.LTV_TERANET_CMA
SET
    PARTITIONED BY (OBSN_DT)
;