CREATE TABLE
    IF NOT EXISTS FEATURES.MAX_LEND_VALUE (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        MORT_AUTH_DT DATE,
        MORT_NUM BIGINT,
        MAX_LEND_VALUE INTEGER
    )
;

ALTER TABLE FEATURES.MAX_LEND_VALUE
SET
    PARTITIONED BY (OBSN_DT)
;