CREATE TABLE IF NOT EXISTS features.MAX_ACCT_BAL_AMT (
    BASEL_ACCT_ID BIGINT NOT NULL,
    OBSN_DT DATE NOT NULL,
    MAX_ACCT_BAL_AMT DECIMAL(17,3)
);

ALTER TABLE features.MAX_ACCT_BAL_AMT
SET PARTITIONED BY (OBSN_DT);