CREATE TABLE
    IF NOT EXISTS FEATURES.METRPL_SCRI_VAL (
        OBSN_DT DATE NOT NULL,
        METRPL_SCRI_VAL DOUBLE,
        YRMTH VARCHAR,
        METRPL_AREA_NM VARCHAR
    )
;

ALTER TABLE FEATURES.METRPL_SCRI_VAL
SET
    PARTITIONED BY (OBSN_DT)
;