CREATE TABLE
    IF NOT EXISTS FEATURES.METRPL_BREACH_F (
        OBSN_DT DATE NOT NULL,
        METRPL_BREACH_F VARCHAR,
        METRPL_AREA_NM VARCHAR
    )
;

ALTER TABLE FEATURES.METRPL_BREACH_F
SET
    PARTITIONED BY (OBSN_DT)
; 