CREATE TABLE IF NOT EXISTS features.MODEL_EXCL_F (
    OBSN_DT DATE NOT NULL,
    MODEL_EXCL_F VARCHAR,
    BASEL_ACCT_ID BIGINT NOT NULL
);

-- Set partitions
ALTER TABLE features.MODEL_EXCL_F SET PARTITIONED BY (OBSN_DT);