CREATE TABLE
    IF NOT EXISTS FEATURES.MODEL_DFT_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSVTN_MTH_TM_ID INTEGER,
        MODEL_DFT_F VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.MODEL_DFT_F
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
