CREATE TABLE IF NOT EXISTS features.MODEL_EXCL_F_V2 (
    OBSN_DT DATE NOT NULL,
    MODEL_EXCL_F_V2 VARCHAR,
    BASEL_ACCT_ID BIGINT NOT NULL
);

-- Set partitions
ALTER TABLE features.MODEL_EXCL_F_V2 SET PARTITIONED BY (OBSN_DT);