CREATE TABLE IF NOT EXISTS features.MONTH_DEF_24M (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    MONTH_DEF_24M INTEGER,
    SRC_SYS_CD VARCHAR NOT NULL
);

-- Set partitions
ALTER TABLE features.MONTH_DEF_24M SET PARTITIONED BY (OBSN_DT);