CREATE TABLE IF NOT EXISTS features.MONTH_DEF (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    MONTH_DEF INTEGER,
    SRC_SYS_CD VARCHAR
);

-- Set partitions
ALTER TABLE features.MONTH_DEF SET PARTITIONED BY (OBSN_DT);