CREATE TABLE IF NOT EXISTS features.MONTH_DEF_SINCE_LAST_DEF (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    MONTH_DEF_SINCE_LAST_DEF INTEGER,
    SRC_SYS_CD VARCHAR NOT NULL
);

-- Set partitions
ALTER TABLE features.MONTH_DEF_SINCE_LAST_DEF SET PARTITIONED BY (OBSN_DT, SRC_SYS_CD);
