CREATE TABLE IF NOT EXISTS features.MORT_NUM(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    MORT_NUM VARCHAR
);

ALTER TABLE features.MORT_NUM 
SET PARTITIONED BY (OBSN_DT);