CREATE TABLE IF NOT EXISTS features.MTH_TM_ID(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    MTH_TM_ID INTEGER
);

ALTER TABLE features.MTH_TM_ID 
SET PARTITIONED BY (OBSN_DT);