CREATE TABLE
    IF NOT EXISTS FEATURES.MTH_DLQNT_AVG12M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        MTH_DLQNT_AVG12M DECIMAL(11,4)
    )
;

ALTER TABLE FEATURES.MTH_DLQNT_AVG12M
SET
    PARTITIONED BY (OBSN_DT)
;
