CREATE TABLE
    IF NOT EXISTS FEATURES.MTH_DLQNT_CNT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        MTH_DLQNT_CNT INT
    )
;

ALTER TABLE FEATURES.MTH_DLQNT_CNT
SET
    PARTITIONED BY (OBSN_DT)
;
