CREATE TABLE
    IF NOT EXISTS FEATURES.NON_REG_INV_ACCT_CNT_MIN3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        NON_REG_INV_ACCT_CNT_MIN3M INTEGER
    )
;

ALTER TABLE FEATURES.NON_REG_INV_ACCT_CNT_MIN3M
SET
    PARTITIONED BY (OBSN_DT)
;

