CREATE TABLE IF NOT EXISTS features.NONREGINVBAL (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    NONREGINVBAL DECIMAL(17,3)
);

ALTER TABLE features.NONREGINVBAL SET PARTITIONED BY (OBSN_DT);
