CREATE TABLE
    IF NOT EXISTS FEATURES.NONREGINVCNT (
        OBSN_DT DATE NOT NULL,
        MTH_TM_ID INTEGER NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        NONREGINVCNT INTEGER
    )
;

ALTER TABLE FEATURES.NONREGINVCNT
SET
    PARTITIONED BY (OBSN_DT)
;

