CREATE TABLE
    IF NOT EXISTS features.NOTE_DT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        NOTE_DT DATE
    )
;

ALTER TABLE features.NOTE_DT
SET
    PARTITIONED BY (OBSN_DT)
;