CREATE TABLE
    IF NOT EXISTS FEATURES.NSF_AMT_SUM6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        NSF_AMT_SUM6M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.NSF_AMT_SUM6M
SET
    PARTITIONED BY (OBSN_DT)
;

