CREATE TABLE
    IF NOT EXISTS FEATURES.NSF_CNT (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        NSF_CNT INTEGER
    )
;

ALTER TABLE FEATURES.NSF_CNT
SET
    PARTITIONED BY (OBSN_DT)
;

