CREATE TABLE
    IF NOT EXISTS FEATURES.NSF_CNT_AVG24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        NSF_CNT_AVG24M DECIMAL(31,4)
    )
;

ALTER TABLE FEATURES.NSF_CNT_AVG24M
SET
    PARTITIONED BY (OBSN_DT)
;
