CREATE TABLE
    IF NOT EXISTS FEATURES.NSF_CNT_MAX24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        NSF_CNT_MAX24M INTEGER
    )
;

ALTER TABLE FEATURES.NSF_CNT_MAX24M
SET
    PARTITIONED BY (OBSN_DT)
;

