CREATE TABLE
    IF NOT EXISTS FEATURES.NSF_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        NSF_AMT DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.NSF_AMT
SET
    PARTITIONED BY (OBSN_DT)
;

