CREATE TABLE IF NOT EXISTS FEATURES.NSF_NUM_MAX6M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    NSF_NUM_MAX6M INTEGER
);
-- SET PARTITIONS 
ALTER TABLE FEATURES.NSF_NUM_MAX6M SET PARTITIONED BY (OBSN_DT);
