CREATE TABLE IF NOT EXISTS features.NSF_NUM (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    NSF_NUM INTEGER
);
-- Set partitions 
ALTER TABLE features.NSF_NUM SET PARTITIONED BY (OBSN_DT);
