CREATE TABLE IF NOT EXISTS FEATURES.NSF_YTD_CNT (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    ACCOUNT_ID VARCHAR NOT NULL,
    NSF_YTD_CNT BIGINT
)
;

ALTER TABLE FEATURES.NSF_YTD_CNT
SET
    PARTITIONED BY (OBSN_DT)
;
