CREATE TABLE IF NOT EXISTS features.ORIG_PRPTY_VAL_AMT(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    ORIG_PRPTY_VAL_AMT DECIMAL(22,2)
);

ALTER TABLE features.ORIG_PRPTY_VAL_AMT 
SET PARTITIONED BY (OBSN_DT);