CREATE TABLE IF NOT EXISTS features.ORIG_AMT_LOAN(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    ORIG_AMT_LOAN DECIMAL(22,2)
);

ALTER TABLE features.ORIG_AMT_LOAN 
SET PARTITIONED BY (OBSN_DT);