CREATE TABLE
    IF NOT EXISTS FEATURES.OS_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        OS_BAL_AMT DECIMAL(17, 3),
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.OS_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;