CREATE TABLE
    IF NOT EXISTS FEATURES.OS_BAL_AMT_V2 (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        OS_BAL_AMT_V2 DECIMAL(17,3),
    )
;

ALTER TABLE FEATURES.OS_BAL_AMT_V2
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;