CREATE TABLE
    IF NOT EXISTS FEATURES.OS_BAL_AMT_MATCHED_PCTG (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        OS_BAL_AMT_MATCHED_PCTG DECIMAL(18,12)
    )
;

ALTER TABLE FEATURES.OS_BAL_AMT_MATCHED_PCTG
SET
    PARTITIONED BY (OBSN_DT)
;