CREATE TABLE
    IF NOT EXISTS FEATURES.PAID_OFF_DATE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PAID_OFF_DATE TIMESTAMP,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.PAID_OFF_DATE
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
