CREATE TABLE IF NOT EXISTS features.PAYROLL_AMT (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    PAYROLL_AMT DECIMAL
);
-- Set partitions 
ALTER TABLE features.PAYROLL_AMT SET PARTITIONED BY (OBSN_DT);
