CREATE TABLE IF NOT EXISTS FEATURES.PAYROLL_AMT_MIN3M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    PAYROLL_AMT_MIN3M DECIMAL
);
-- SET PARTITIONS 
ALTER TABLE FEATURES.PAYROLL_AMT_MIN3M SET PARTITIONED BY (OBSN_DT);
