CREATE TABLE IF NOT EXISTS features.PD_BAND_EXPSR_CL_KEY_VAL(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    PD_BAND_EXPSR_CL_KEY_VAL VARCHAR
);

ALTER TABLE features.PD_BAND_EXPSR_CL_KEY_VAL 
SET PARTITIONED BY (OBSN_DT);