CREATE TABLE IF NOT EXISTS features.PD_OFF_DT(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT,
    SRC_SYS_CD VARCHAR,
    PD_OFF_DT DATE
);

ALTER TABLE features.PD_OFF_DT 
SET PARTITIONED BY (OBSN_DT);