CREATE TABLE
    IF NOT EXISTS features.PD_OFF_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        PD_OFF_F VARCHAR
    )
;

ALTER TABLE features.PD_OFF_F
SET
    PARTITIONED BY (OBSN_DT)
;