CREATE TABLE IF NOT EXISTS FEATURES.PE_NUM_OF_MONTHS_SINCE_LAST_PAYM (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    PE_NUM_OF_MONTHS_SINCE_LAST_PAYM INTEGER
);

ALTER TABLE FEATURES.PE_NUM_OF_MONTHS_SINCE_LAST_PAYM
SET PARTITIONED BY (OBSN_DT);
