CREATE TABLE
    IF NOT EXISTS FEATURES.PIT_STATUS_ACCOUNT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_DFLT_F VARCHAR,
        CRS_DFLT_INCL_F VARCHAR,
        PIT_STATUS_ACCOUNT VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.PIT_STATUS_ACCOUNT
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;