CREATE TABLE
    IF NOT EXISTS FEATURES.PIT_STATUS_STEP (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        PIT_STATUS_STEP VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.PIT_STATUS_STEP
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;