CREATE TABLE
    IF NOT EXISTS FEATURES.PIT_STAT_VER_1_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PIT_STAT_VER_1_CD VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.PIT_STAT_VER_1_CD
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
