CREATE TABLE
    IF NOT EXISTS FEATURES.PIT_STATUS_ACCOUNT_GCP (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_DFLT_F VARCHAR,
        PIT_STATUS_ACCOUNT_GCP VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.PIT_STATUS_ACCOUNT_GCP
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;