CREATE TABLE
    IF NOT EXISTS FEATURES.PIT_STAT_VER_2_CD180 (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        BASEL_CUST_ID BIGINT,
        PIT_STAT_VER_2_CD180 VARCHAR
    )
;

ALTER TABLE FEATURES.PIT_STAT_VER_2_CD180
SET
    PARTITIONED BY (OBSN_DT)
;