CREATE TABLE
    IF NOT EXISTS FEATURES.PIT_STATUS_CROSS_DEFAULT_ORIG (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        CROSS_DFLT_PIT_OVERRIDE_F VARCHAR,
        PIT_STATUS_CROSS_DEFAULT_ORIG VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.PIT_STATUS_CROSS_DEFAULT_ORIG
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;