CREATE TABLE
    IF NOT EXISTS FEATURES.PLANUTILIZATIONSTP (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_PLN_SNAPSHOT_ID BIGINT,
        PLANUTILIZATIONSTP DECIMAL(17, 4)
    )
;

ALTER TABLE FEATURES.PLANUTILIZATIONSTP
SET
    PARTITIONED BY (OBSN_DT)
;