CREATE TABLE
    IF NOT EXISTS FEATURES.PR01 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        PR01 INT,
    )
;

ALTER TABLE FEATURES.PR01
SET
    PARTITIONED BY (OBSN_DT)
;