CREATE TABLE
    IF NOT EXISTS FEATURES.PR01_MAX6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        PR01_MAX6M INT
    )
;

ALTER TABLE FEATURES.PR01_MAX6M
SET
    PARTITIONED BY (OBSN_DT)
;