CREATE TABLE IF NOT EXISTS features.PRCH_CRNT_C_BAL_KSC(
 PRIM_BASEL_CUST_ID BIGINT NOT NULL,
 OBSN_DT DATE NOT NULL,
 PRCH_CRNT_C_BAL_KSC DECIMAL(18,4)
);

ALTER TABLE features.PRCH_CRNT_C_BAL_KSC SET PARTITIONED BY (OBSN_DT);