CREATE TABLE IF NOT EXISTS features.PRCH_CRNT_C_BAL_KSC_MAX3M(
 BASEL_CUST_ID BIGINT NOT NULL,
 OBSN_DT DATE NOT NULL,
 PRCH_CRNT_C_BAL_KSC_MAX3M DECIMAL(18,4)
);

ALTER TABLE features.PRCH_CRNT_C_BAL_KSC_MAX3M SET PARTITIONED BY (OBSN_DT);