CREATE TABLE
    IF NOT EXISTS features.PRD_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        PRD_CD VARCHAR
    )
;

ALTER TABLE features.PRD_CD
SET
    PARTITIONED BY (OBSN_DT)
;