CREATE TABLE IF NOT EXISTS features.PRD_TYPE (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    PRD_TYPE VARCHAR NOT NULL
);

ALTER TABLE features.PRD_TYPE SET PARTITIONED BY (OBSN_DT);