CREATE TABLE
    IF NOT EXISTS FEATURES.PRD_ID (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PRD_ID VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.PRD_ID
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;