CREATE TABLE IF NOT EXISTS FEATURES.PREPAY_YTD_MAX24M (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    PREPAY_YTD_MAX24M DOUBLE
);
-- SET PARTITIONS 
ALTER TABLE FEATURES.PREPAY_YTD_MAX24M SET PARTITIONED BY (OBSN_DT);