CREATE TABLE IF NOT EXISTS features.PREPAY_YTD (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    PREPAY_YTD DOUBLE
);
-- Set partitions 
ALTER TABLE features.PREPAY_YTD SET PARTITIONED BY (OBSN_DT);