CREATE TABLE
    IF NOT EXISTS features.PRIM_CUST_CID (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        PRIM_CUST_CID VARCHAR
    )
;

ALTER TABLE features.PRIM_CUST_CID
SET
    PARTITIONED BY (OBSN_DT)
;