CREATE TABLE
    IF NOT EXISTS FEATURES.PROP_VAL_NEW_CMA (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        PROP_VAL_NEW DOUBLE
    )
;

ALTER TABLE FEATURES.PROP_VAL_NEW_CMA
SET
    PARTITIONED BY (OBSN_DT)
;