CREATE TABLE
    IF NOT EXISTS FEATURES.PURPOSE_CODE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PURPOSE_CODE VARCHAR
    )
;

ALTER TABLE FEATURES.PURPOSE_CODE
SET
    PARTITIONED BY (OBSN_DT)
;