CREATE TABLE
    IF NOT EXISTS FEATURES.RE33_MAX24M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        RE33_MAX24M DECIMAL (17,3)
    )
;
 
ALTER TABLE FEATURES.RE33_MAX24M
SET
    PARTITIONED BY (OBSN_DT)
;
