CREATE TABLE
    IF NOT EXISTS FEATURES.RE33 (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        RE33 INT
    )
;

ALTER TABLE FEATURES.RE33
SET
    PARTITIONED BY (OBSN_DT)
;