CREATE TABLE
    IF NOT EXISTS FEATURES.REG_INV_ACCT_CNT_AVG3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        REG_INV_ACCT_CNT_AVG3M DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.REG_INV_ACCT_CNT_AVG3M
SET
    PARTITIONED BY (OBSN_DT)
;