CREATE TABLE
    IF NOT EXISTS FEATURES.REGINVACCTCNT (
        OBSN_DT DATE NOT NULL,
        MTH_TM_ID INT NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        REGINVACCTCNT INT
    )
;

ALTER TABLE FEATURES.REGINVACCTCNT
SET
    PARTITIONED BY (OBSN_DT)
;