CREATE TABLE
    IF NOT EXISTS FEATURES.REMAIN_AMORT2 (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        REMAIN_AMORT2 DOUBLE
    )
;

ALTER TABLE FEATURES.REMAIN_AMORT2
SET
    PARTITIONED BY (OBSN_DT)
;