CREATE TABLE
    IF NOT EXISTS features.RESIDUAL_MAT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        RESIDUAL_MAT INTEGER
    )
;

ALTER TABLE features.RESIDUAL_MAT
SET
    PARTITIONED BY (OBSN_DT)
;