CREATE TABLE
    IF NOT EXISTS features.REVISED_EXPSR_OV_125K_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        REVISED_EXPSR_OV_125K_F VARCHAR
    )
;

ALTER TABLE features.REVISED_EXPSR_OV_125K_F
SET
    PARTITIONED BY (OBSN_DT)
;