CREATE TABLE
    IF NOT EXISTS FEATURES.REVISED_EXPSR_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        REVISED_EXPSR_AMT DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.REVISED_EXPSR_AMT
SET
    PARTITIONED BY (OBSN_DT)
;