CREATE TABLE IF NOT EXISTS features.RGNL_OFFC_CD(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    RGNL_OFFC_CD VARCHAR
);

ALTER TABLE features.RGNL_OFFC_CD 
SET PARTITIONED BY (OBSN_DT);