CREATE TABLE
    IF NOT EXISTS FEATURES.RGSTRD_INVSTMNT_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        MTH_TM_ID INT NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        RGSTRD_INVSTMNT_BAL_AMT DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.RGSTRD_INVSTMNT_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;