CREATE TABLE IF NOT EXISTS features.RNTL_PRPTY_F_IFRS9(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    RNTL_PRPTY_F_IFRS9 VARCHAR
);

ALTER TABLE features.RNTL_PRPTY_F_IFRS9 
SET PARTITIONED BY (OBSN_DT);