CREATE TABLE
    IF NOT EXISTS FEATURES.RRAP_PRD_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        RRAP_PRD_CD VARCHAR
    )
;

ALTER TABLE FEATURES.RRAP_PRD_CD
SET
    PARTITIONED BY (OBSN_DT)
;