CREATE TABLE
    IF NOT EXISTS FEATURES.RS_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        RS_F VARCHAR
    )
;

ALTER TABLE FEATURES.RS_F
SET
    PARTITIONED BY (OBSN_DT)
;