CREATE TABLE
    IF NOT EXISTS FEATURES.SCRTY_TP_DESC (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        SCRTY_TP_DESC VARCHAR
    )
;

ALTER TABLE FEATURES.SCRTY_TP_DESC
SET
    PARTITIONED BY (OBSN_DT)
;