CREATE TABLE
    IF NOT EXISTS features.SECRTZTN_TP_DESC (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SECRTZTN_TP_DESC VARCHAR
    )
;

ALTER TABLE features.SECRTZTN_TP_DESC
SET
    PARTITIONED BY (OBSN_DT)
;
