CREATE TABLE
    IF NOT EXISTS features.SECRTZTN_OS_ADJ_FACTR (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        SECRTZTN_OS_ADJ_FACTR DECIMAL(20,10)
    )
;

ALTER TABLE features.SECRTZTN_OS_ADJ_FACTR
SET
    PARTITIONED BY (OBSN_DT) 
;
