CREATE TABLE IF NOT EXISTS features.SECURITIZATION_DATE (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SECRTZTN_TP_CD VARCHAR,
    SECURITIZATION_DATE DATE
);
-- Set partitions 
ALTER TABLE features.SECURITIZATION_DATE SET PARTITIONED BY (OBSN_DT);
