CREATE TABLE IF NOT EXISTS features.SECURITIZEDAMOUNT (
    OBSN_DT DATE NOT NULL,
    SECRTZTN_TP_CD VARCHAR,
    SECURITIZEDAMOUNT DECIMAL(17,2)
);
-- Set partitions 
ALTER TABLE features.SECURITIZEDAMOUNT SET PARTITIONED BY (OBSN_DT);
