CREATE TABLE
    IF NOT EXISTS FEATURES.SML_BUS_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SML_BUS_F VARCHAR
    )
;

ALTER TABLE FEATURES.SML_BUS_F
SET
    PARTITIONED BY (OBSN_DT)
;