CREATE TABLE
    IF NOT EXISTS FEATURES.SRC_SYS_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.SRC_SYS_CD
SET
    PARTITIONED BY (OBSN_DT)
;