CREATE TABLE IF NOT EXISTS features.SRC_PRD_DESC(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    SRC_PRD_DESC VARCHAR
);

ALTER TABLE features.SRC_PRD_DESC 
SET PARTITIONED BY (OBSN_DT);