CREATE TABLE IF NOT EXISTS features.STEP_STANDALONE_MONTH_DEF_SINCE_LAST_DEF (
    OBSN_DT DATE NOT NULL,
     BASEL_ACCT_ID BIGINT NOT NULL,
    STEP_STANDALONE_MONTH_DEF_SINCE_LAST_DEF INTEGER
);

-- Set partitions
ALTER TABLE features.STEP_STANDALONE_MONTH_DEF_SINCE_LAST_DEF 
SET PARTITIONED BY (OBSN_DT);
