CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_LEND_VALUE (
        OBSN_DT DATE NOT NULL,
        MORT_NUM BIGINT NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_LEND_VALUE INTEGER
    )
;

ALTER TABLE FEATURES.STEP_LEND_VALUE
SET
    PARTITIONED BY (OBSN_DT)
;