CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_HGST_DLQNT_DAY_MTG_MAX12M_ACCT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_HGST_DLQNT_DAY_MTG_MAX12M_ACCT INTEGER
    )
;

ALTER TABLE FEATURES.STEP_HGST_DLQNT_DAY_MTG_MAX12M_ACCT
SET
    PARTITIONED BY (OBSN_DT)
;
