CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_BNS_DLQNT_DAY (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_BNS_DLQNT_DAY INTEGER
    )
;

ALTER TABLE FEATURES.STEP_BNS_DLQNT_DAY
SET
    PARTITIONED BY (OBSN_DT)
;