CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_ACCT_OP_DT_REVL (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_ACCT_OP_DT_REVL DATE
    )
;

ALTER TABLE FEATURES.STEP_ACCT_OP_DT_REVL
SET
    PARTITIONED BY (OBSN_DT)
;
