CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_LEND_VALUE_MTG_MAX12M_ACCT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_LEND_VALUE_MTG_MAX12M_ACCT DECIMAL(18,2)
    )
;

ALTER TABLE FEATURES.STEP_LEND_VALUE_MTG_MAX12M_ACCT
SET
    PARTITIONED BY (OBSN_DT)
;