CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_LTV_MIN6M_ACCT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_LTV_MIN6M_ACCT DECIMAL(18,6)
    )
;

ALTER TABLE FEATURES.STEP_LTV_MIN6M_ACCT
SET
    PARTITIONED BY (OBSN_DT)
;