CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_WORST_DLQDAYS_KS_AVG12M (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_PLN_SNAPSHOT_ID BIGINT,
        STEP_WORST_DLQDAYS_KS_AVG12M DECIMAL(17, 4)
    )
;

ALTER TABLE FEATURES.STEP_WORST_DLQDAYS_KS_AVG12M
SET
    PARTITIONED BY (OBSN_DT)
;