CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_BNS_DLQNT_DAY_KSA_MAX24M (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_BNS_DLQNT_DAY_KSA_MAX24M INTEGER
    )
;

ALTER TABLE FEATURES.STEP_BNS_DLQNT_DAY_KSA_MAX24M
SET
    PARTITIONED BY (OBSN_DT)
;