CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_DELQ_DAYS_AVG12M (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_DELQ_DAYS_AVG12M DECIMAL(17,5)
    )
;

ALTER TABLE FEATURES.STEP_DELQ_DAYS_AVG12M
SET PARTITIONED BY (OBSN_DT);

