CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_HGST_DLQNT_MTH_MTG_MAX12M (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_HGST_DLQNT_MTH_MTG_MAX12M INTEGER
    )
;

ALTER TABLE FEATURES.STEP_HGST_DLQNT_MTH_MTG_MAX12M
SET
    PARTITIONED BY (OBSN_DT)
;
