CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_INDEXED_APRSD_VAL_AVG3M_ACCT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_INDEXED_APRSD_VAL_AVG3M_ACCT DECIMAL(18,4)
    )
;

ALTER TABLE FEATURES.STEP_INDEXED_APRSD_VAL_AVG3M_ACCT
SET
    PARTITIONED BY (OBSN_DT)
;