CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        STEP_CD VARCHAR
    )
;

ALTER TABLE FEATURES.STEP_CD
SET
    PARTITIONED BY (OBSN_DT)
;