CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_BNS_DLQNT_DAY_GP_KSA (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_BNS_DLQNT_DAY_GP_KSA INTEGER
    )
;

ALTER TABLE FEATURES.STEP_BNS_DLQNT_DAY_GP_KSA
SET
    PARTITIONED BY (OBSN_DT)
;