CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_BNS_DLQNT_DAY_GP_KSA_AVG24M (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_BNS_DLQNT_DAY_GP_KSA_AVG24M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.STEP_BNS_DLQNT_DAY_GP_KSA_AVG24M
SET
    PARTITIONED BY (OBSN_DT)
;