CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_CR_LMT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_CR_LMT DECIMAL
    )
;

ALTER TABLE FEATURES.STEP_CR_LMT
SET
    PARTITIONED BY (OBSN_DT)
;
