CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_PRIM_CUST_ID (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_PRIM_CUST_ID BIGINT
    )
;

ALTER TABLE FEATURES.STEP_PRIM_CUST_ID
SET
    PARTITIONED BY (OBSN_DT)
;
