CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_AMORT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_AMORT INTEGER
    )
;

ALTER TABLE FEATURES.STEP_AMORT
SET
    PARTITIONED BY (OBSN_DT)
;