CREATE TABLE IF NOT EXISTS features.STEP_MONTH_DEF_SINCE_LAST_DEF (
    OBSN_DT DATE NOT NULL,
    STEP_PLN_AGRMNT_NUM BIGINT,
    STEP_MONTH_DEF_SINCE_LAST_DEF INTEGER
);

-- Set partitions
ALTER TABLE features.STEP_MONTH_DEF_SINCE_LAST_DEF 
SET PARTITIONED BY (OBSN_DT);
