CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_TOT_PREPAY_YTD_MTG_MAX12M (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM BIGINT NOT NULL,
        STEP_TOT_PREPAY_YTD_MTG_MAX12M DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.STEP_TOT_PREPAY_YTD_MTG_MAX12M
SET
    PARTITIONED BY (OBSN_DT)
;

