CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_UTIL_KSA (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_UTIL_KSA DECIMAL(11, 6)
    )
;

ALTER TABLE FEATURES.STEP_UTIL_KSA
SET
    PARTITIONED BY (OBSN_DT)
;

