CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_TOT_CR_BAL_DPD30_90_KSA (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_TOT_CR_BAL_DPD30_90_KSA DECIMAL(31,3)
    )
;

ALTER TABLE FEATURES.STEP_TOT_CR_BAL_DPD30_90_KSA
SET
    PARTITIONED BY (OBSN_DT)
;