CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_INDEXED_CLTV_METRO_METHOD2 (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_INDEXED_CLTV_METRO_METHOD2 DECIMAL(22,15)
    )
;

ALTER TABLE FEATURES.STEP_INDEXED_CLTV_METRO_METHOD2
SET
    PARTITIONED BY (OBSN_DT)
;