CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_TOTAL_BAL (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_TOTAL_BAL DECIMAL
    )
;

ALTER TABLE FEATURES.STEP_TOTAL_BAL
SET
    PARTITIONED BY (OBSN_DT)
;
