CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_LTV (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR NOT NULL,
        STEP_LTV DECIMAL(18,4)
    )
;

ALTER TABLE FEATURES.STEP_LTV
SET
    PARTITIONED BY (OBSN_DT)
;