CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_INSURANCE (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_INSURANCE VARCHAR
    )
;

ALTER TABLE FEATURES.STEP_INSURANCE
SET
    PARTITIONED BY (OBSN_DT)
;
