CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_FLAG (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        STEP_FLAG VARCHAR NOT NULL,
        SRC_SYS_CD VARCHAR NOT NULL
    )
;

ALTER TABLE FEATURES.STEP_FLAG
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
