CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_MONTHLY_MAX_DELQ (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_MONTHLY_MAX_DELQ INTEGER
    )
;

ALTER TABLE FEATURES.STEP_MONTHLY_MAX_DELQ
SET PARTITIONED BY (OBSN_DT);

