CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_SUB_PORT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        BASEL_ACCT_ID BIGINT NOT NULL,
        STEP_SUB_PORT VARCHAR
    )
;

ALTER TABLE FEATURES.STEP_SUB_PORT
SET
    PARTITIONED BY (OBSN_DT)
;