CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        STEP_F VARCHAR
    )
;

ALTER TABLE FEATURES.STEP_F
SET
    PARTITIONED BY (OBSN_DT)
;