CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_TOT_LEND_VALUE_ACCT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        STEP_TOT_LEND_VALUE_ACCT DECIMAL(18,2) 
    )
;

ALTER TABLE FEATURES.STEP_TOT_LEND_VALUE_ACCT
SET
    PARTITIONED BY (OBSN_DT)
;