CREATE TABLE
    IF NOT EXISTS FEATURES.STEP_MORT_ACCT_CNT (
        OBSN_DT DATE NOT NULL,
        STEP_PLN_SNAPSHOT_ID BIGINT NOT NULL,
        STEP_MORT_ACCT_CNT INTEGER
    )
;

ALTER TABLE FEATURES.STEP_MORT_ACCT_CNT
SET
    PARTITIONED BY (OBSN_DT)
;