CREATE TABLE IF NOT EXISTS features.SUB_PPLTN_FLAG (
    BASEL_ACCT_ID BIGINT NOT NULL,
    OBSN_DT DATE NOT NULL,
    SUB_PPLTN_FLAG VARCHAR
);
 
ALTER TABLE features.SUB_PPLTN_FLAG
SET PARTITIONED BY (OBSN_DT);