CREATE TABLE
    IF NOT EXISTS FEATURES.SUB_PORT_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SUB_PORT_F VARCHAR,
        SRC_SYS_CD VARCHAR,
    )
;

ALTER TABLE FEATURES.SUB_PORT_F
SET
    PARTITIONED BY (OBSN_DT)
;