CREATE TABLE
    IF NOT EXISTS FEATURES.SUB_PRD_CD (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        SUB_PRD_CD VARCHAR
    )
;

ALTER TABLE FEATURES.SUB_PRD_CD
SET
    PARTITIONED BY (OBSN_DT)
;