CREATE TABLE
    IF NOT EXISTS FEATURES.SUM_DLQNT_DAY_CNT (
        OBSN_DT DATE NOT NULL,
        MTH_TM_ID INT NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        SUM_DLQNT_DAY_CNT INT
    )
;

ALTER TABLE FEATURES.SUM_DLQNT_DAY_CNT
SET
    PARTITIONED BY (OBSN_DT)
;