CREATE TABLE
    IF NOT EXISTS FEATURES.TNG_FINAL_DEFAULT_IND (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        TNG_FINAL_DEFAULT_IND VARCHAR,
    )
;

ALTER TABLE FEATURES.TNG_FINAL_DEFAULT_IND
SET
    PARTITIONED BY (OBSN_DT)
;