CREATE TABLE IF NOT EXISTS FEATURES.TNG_PIT_STATUS_CD (
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    ACCOUNT_ID VARCHAR NOT NULL,
    TNG_PIT_STATUS_CD VARCHAR
)
;

ALTER TABLE FEATURES.TNG_PIT_STATUS_CD SET PARTITIONED BY (OBSN_DT)
;
