CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_BAL_HCCL (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        TOT_BAL_HCCL DECIMAL(17, 4)
    )
;

ALTER TABLE FEATURES.TOT_BAL_HCCL
SET
    PARTITIONED BY (OBSN_DT)
;