CREATE TABLE IF NOT EXISTS features.TOT_C_DT_FNC_CHRG_AMT(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    TOT_C_DT_FNC_CHRG_AMT DECIMAL(17,3)
);

ALTER TABLE features.TOT_C_DT_FNC_CHRG_AMT
SET
    PARTITIONED BY (OBSN_DT)
;