CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_PAYRL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        TOT_PAYRL_AMT DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.TOT_PAYRL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;