CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_OS_BAL_MATCHED (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        TOT_OS_BAL_MATCHED DECIMAL(38,6)
    )
;

ALTER TABLE FEATURES.TOT_OS_BAL_MATCHED
SET
    PARTITIONED BY (OBSN_DT)
;