CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_ACCT_CNT_RECVD (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR NOT NULL,
        TOT_ACCT_CNT_RECVD INTEGER
    )
;

ALTER TABLE FEATURES.TOT_ACCT_CNT_RECVD
SET
    PARTITIONED BY (OBSN_DT)
;