CREATE TABLE
    IF NOT EXISTS features.TOT_UNP_FNC_CHRG_KSC_MAX3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        TOT_UNP_FNC_CHRG_KSC_MAX3M DECIMAL(17, 3)
    )
;

ALTER TABLE features.TOT_UNP_FNC_CHRG_KSC_MAX3M
SET
    PARTITIONED BY (OBSN_DT)
;