CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_ACCT_CNT_MATCHED (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR NOT NULL,
        TOT_ACCT_CNT_MATCHED INTEGER
    )
;

ALTER TABLE FEATURES.TOT_ACCT_CNT_MATCHED
SET
    PARTITIONED BY (OBSN_DT)
;