CREATE TABLE
    IF NOT EXISTS features.TOT_UNP_FNC_CHRG_KSC (
        BASEL_CUST_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        TOT_UNP_FNC_CHRG_KSC DECIMAL(17, 3)
    )
;

ALTER TABLE features.TOT_UNP_FNC_CHRG_KSC
SET
    PARTITIONED BY (OBSN_DT)
;