CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_PAYRL_AMT_MIN3M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        TOT_PAYRL_AMT_MIN3M DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.TOT_PAYRL_AMT_MIN3M
SET
    PARTITIONED BY (OBSN_DT)
;