CREATE TABLE
    IF NOT EXISTS features.TOT_UNP_FNC_CHRG_KSA_AVG6M (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        TOT_UNP_FNC_CHRG_KSA_AVG6M DECIMAL(17, 3)
    )
;

ALTER TABLE features.TOT_UNP_FNC_CHRG_KSA_AVG6M
SET
    PARTITIONED BY (OBSN_DT)
;