CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_CUR_BAL_CUST_SUM6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        TOT_CUR_BAL_CUST_SUM6M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.TOT_CUR_BAL_CUST_SUM6M
SET
    PARTITIONED BY (OBSN_DT)
;