CREATE TABLE
    IF NOT EXISTS features.TOT_C_DT_FNC_CHRG_KSA (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TOT_C_DT_FNC_CHRG_KSA DECIMAL(11, 4)
    )
;

ALTER TABLE features.TOT_C_DT_FNC_CHRG_KSA
SET
    PARTITIONED BY (OBSN_DT)
;