CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_PREPAY_YTD_MTG_MAX24M_ACCT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TOT_PREPAY_YTD_MTG_MAX24M_ACCT DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.TOT_PREPAY_YTD_MTG_MAX24M_ACCT
SET
    PARTITIONED BY (OBSN_DT)
;