CREATE TABLE
    IF NOT EXISTS features.TOT_ADJUSTED_OS_BAL_IN_CCAR (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        TOT_ADJUSTED_OS_BAL_IN_CCAR DECIMAL(20,2)
    )
;

ALTER TABLE features.TOT_ADJUSTED_OS_BAL_IN_CCAR
SET
    PARTITIONED BY (OBSN_DT) 
;
