CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_NEW_BAL_AMT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TOT_NEW_BAL_AMT DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.TOT_NEW_BAL_AMT
SET
    PARTITIONED BY (OBSN_DT)
;