CREATE TABLE IF NOT EXISTS features.TOT_C_DT_FNC_CHRG_KSC_MAX3M(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    TOT_C_DT_FNC_CHRG_KSC_MAX3M DECIMAL(20,4)
);

ALTER TABLE features.TOT_C_DT_FNC_CHRG_KSC_MAX3M
SET
    PARTITIONED BY (OBSN_DT)
;
