CREATE TABLE IF NOT EXISTS features.TOT_C_DT_FNC_CHRG_KSC(
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    TOT_C_DT_FNC_CHRG_KSC DECIMAL(31,3)
);

ALTER TABLE features.TOT_C_DT_FNC_CHRG_KSC
SET
    PARTITIONED BY (OBSN_DT)
;
