CREATE TABLE IF NOT EXISTS features.TOT_C_DT_FNC_CHRG_KSA_AVG24M(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    TOT_C_DT_FNC_CHRG_KSA_AVG24M DECIMAL(17,3)
);

ALTER TABLE features.TOT_C_DT_FNC_CHRG_KSA_AVG24M
SET
    PARTITIONED BY (OBSN_DT)
;