CREATE TABLE
    IF NOT EXISTS features.TOT_UNP_FNC_CHRG_KSC_CHG12M (
        BASEL_CUST_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        TOT_UNP_FNC_CHRG_KSC_CHG12M DECIMAL(17, 3)
    )
;

ALTER TABLE features.TOT_UNP_FNC_CHRG_KSC_CHG12M
SET
    PARTITIONED BY (OBSN_DT)
;