CREATE TABLE IF NOT EXISTS features.TOT_DEP_AMT_MAX3M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    TOT_DEP_AMT_MAX3M DECIMAL(17,3)
);

-- Set partitions
ALTER TABLE features.TOT_DEP_AMT_MAX3M SET PARTITIONED BY (OBSN_DT);