CREATE TABLE IF NOT EXISTS features.TOT_EXPSR_ABOVE_1500K_LMT_F(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    TOT_EXPSR_ABOVE_1500K_LMT_F VARCHAR
);

ALTER TABLE features.TOT_EXPSR_ABOVE_1500K_LMT_F 
SET PARTITIONED BY (OBSN_DT);