CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_SECRTZTN_AMT_TO_ADJUST (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR,
        TOT_SECRTZTN_AMT_TO_ADJUST DECIMAL(38,2)
    )
;

ALTER TABLE FEATURES.TOT_SECRTZTN_AMT_TO_ADJUST
SET
    PARTITIONED BY (OBSN_DT)
;