CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_OS_BAL_RECVD (
        OBSN_DT DATE NOT NULL,
        SECRTZTN_TP_CD VARCHAR NOT NULL,
        TOT_OS_BAL_RECVD DECIMAL(17,2)
    )
;

ALTER TABLE FEATURES.TOT_OS_BAL_RECVD
SET
    PARTITIONED BY (OBSN_DT)
;