CREATE TABLE
    IF NOT EXISTS FEATURES.TOT_NEW_BAL_CHG3M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TOT_NEW_BAL_CHG3M DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.TOT_NEW_BAL_CHG3M
SET
    PARTITIONED BY (OBSN_DT)
;

