CREATE TABLE
    IF NOT EXISTS FEATURES.TOTAL_SUSPENSE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TOTAL_SUSPENSE DOUBLE,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.TOTAL_SUSPENSE
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
