CREATE TABLE
    IF NOT EXISTS FEATURES.TOTAL_BALANCE (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TOTAL_BALANCE DECIMAL(17, 3)
    )
;

ALTER TABLE FEATURES.TOTAL_BALANCE
SET
    PARTITIONED BY (OBSN_DT)
;