CREATE TABLE
    IF NOT EXISTS FEATURES.TOTAL_EXPSR_ABOVE_LMT_F (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TOTAL_EXPSR_ABOVE_LMT_F VARCHAR
    )
;

ALTER TABLE FEATURES.TOTAL_EXPSR_ABOVE_LMT_F
SET
    PARTITIONED BY (OBSN_DT)
;