CREATE TABLE
    IF NOT EXISTS FEATURES.TRADES_STSFCT_CNT_SLP6M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        TRADES_STSFCT_CNT_SLP6M DECIMAL(13,2)
    )
;

ALTER TABLE FEATURES.TRADES_STSFCT_CNT_SLP6M
SET
    PARTITIONED BY (OBSN_DT)
;