CREATE TABLE
    IF NOT EXISTS FEATURES.TRADES_ACTIVE_UTIL_PCT_MAX12M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        ACCOUNT_ID VARCHAR NOT NULL,
        TRADES_ACTIVE_UTIL_PCT_MAX12M DECIMAL(13,2)
    )
;

ALTER TABLE FEATURES.TRADES_ACTIVE_UTIL_PCT_MAX12M
SET
    PARTITIONED BY (OBSN_DT)
;