CREATE TABLE IF NOT EXISTS features.TRANSACTOR_FLAG_QRR(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    TRANSACTOR_FLAG_QRR VARCHAR
);

ALTER TABLE features.TRANSACTOR_FLAG_QRR 
SET PARTITIONED BY (OBSN_DT);