CREATE TABLE IF NOT EXISTS features.TRANSACTOR_F(
    OBSN_DT DATE NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    SRC_SYS_CD VARCHAR,
    TRANSACTOR_F VARCHAR
);

ALTER TABLE features.TRANSACTOR_F 
SET PARTITIONED BY (OBSN_DT);