CREATE TABLE IF NOT EXISTS features.TREATMENT_F (
    OBSN_DT DATE NOT NULL,
    TREATMENT_F VARCHAR,
    BASEL_ACCT_ID BIGINT NOT NULL
);

-- Set partitions
ALTER TABLE features.TREATMENT_F SET PARTITIONED BY (OBSN_DT);