CREATE TABLE
    IF NOT EXISTS FEATURES.TRNST_EXCLSN_F_MORT (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        TRNST_EXCLSN_F_MORT VARCHAR,
        SRC_SYS_CD VARCHAR
    )
;

ALTER TABLE FEATURES.TRNST_EXCLSN_F_MORT
SET
    PARTITIONED BY (OBSN_DT, SRC_SYS_CD)
;
