CREATE TABLE
    IF NOT EXISTS FEATURES.TRNST_NUM (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        TRNST_NUM VARCHAR
    )
;

ALTER TABLE FEATURES.TRNST_NUM
SET
    PARTITIONED BY (OBSN_DT)
;