CREATE TABLE
    IF NOT EXISTS FEATURES.UNDRAWN_EXPSR_PCT (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        SRC_SYS_CD VARCHAR,
        UNDRAWN_EXPSR_PCT DECIMAL(2,1)
    );

ALTER TABLE FEATURES.UNDRAWN_EXPSR_PCT
SET
    PARTITIONED BY (OBSN_DT)
;