CREATE TABLE
    IF NOT EXISTS FEATURES.UNQ_ACCT_ID (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        UNQ_ACCT_ID VARCHAR
    );

ALTER TABLE FEATURES.UNQ_ACCT_ID
SET
    PARTITIONED BY (OBSN_DT)
;