CREATE TABLE
    IF NOT EXISTS FEATURES.UTIL_KSA_MAX12M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        UTIL_KSA_MAX12M DECIMAL(10, 5)
    )
;

ALTER TABLE FEATURES.UTIL_KSA_MAX12M
SET
    PARTITIONED BY (OBSN_DT)
;