CREATE TABLE
    IF NOT EXISTS FEATURES.UTIL_KSA_AVG3M (
        BASEL_ACCT_ID BIGINT NOT NULL,
        OBSN_DT DATE NOT NULL,
        UTIL_KSA_AVG3M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.UTIL_KSA_AVG3M
SET
    PARTITIONED BY (OBSN_DT)
;

