CREATE TABLE
    IF NOT EXISTS FEATURES.UTILIZATION_AVG3M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        UTILIZATION_AVG3M DECIMAL(16, 9)
    )
;

ALTER TABLE FEATURES.UTILIZATION_AVG3M
SET
    PARTITIONED BY (OBSN_DT)
;

