CREATE TABLE
    IF NOT EXISTS FEATURES.UTIL_KSA (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        UTIL_KSA DECIMAL(16, 9)
    )
;

ALTER TABLE FEATURES.UTIL_KSA
SET
    PARTITIONED BY (OBSN_DT)
;

