CREATE TABLE
    IF NOT EXISTS FEATURES.UTIL_KSA_MAX3M (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        UTIL_KSA_MAX3M DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.UTIL_KSA_MAX3M
SET
    PARTITIONED BY (OBSN_DT)
;