CREATE TABLE
    IF NOT EXISTS features.UTLTN_RTO (
        OBSN_DT DATE NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        SRC_SYS_CD VARCHAR,
        UTLTN_RTO DECIMAL(17, 8)
    )
;

ALTER TABLE features.UTLTN_RTO
SET
    PARTITIONED BY (OBSN_DT)
;