CREATE TABLE
    IF NOT EXISTS FEATURES.WORST_DLQDAYS_MO_SLP6M (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        WORST_DLQDAYS_MO_SLP6M DECIMAL(17,3)
    )
;

ALTER TABLE FEATURES.WORST_DLQDAYS_MO_SLP6M
SET
    PARTITIONED BY (OBSN_DT)
;