CREATE TABLE IF NOT EXISTS features.WORST_DLQDAYS_KS_CUST (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    WORST_DLQDAYS_KS_CUST INTEGER
);

-- Set partitions
ALTER TABLE features.WORST_DLQDAYS_KS_CUST SET PARTITIONED BY (OBSN_DT);