CREATE TABLE IF NOT EXISTS features.WORST_DLQDAYS_KS_CUST_MAX6M (
    OBSN_DT DATE NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    WORST_DLQDAYS_KS_CUST_MAX6M INTEGER
);

-- Set partitions
ALTER TABLE features.WORST_DLQDAYS_KS_CUST_MAX6M SET PARTITIONED BY (OBSN_DT);