CREATE TABLE IF NOT EXISTS features.WRITTEN_OUT_F (
    OBSN_DT DATE NOT NULL,
    WRITTEN_OUT_F VARCHAR,
    BASEL_ACCT_ID BIGINT NOT NULL
);

-- Set partitions
ALTER TABLE features.WRITTEN_OUT_F SET PARTITIONED BY (OBSN_DT);