CREATE TABLE
    IF NOT EXISTS FEATURES.WTHDRWL_CNT (
        OBSN_DT DATE NOT NULL,
        BASEL_CUST_ID BIGINT NOT NULL,
        WTHDRWL_CNT DECIMAL(11, 4)
    )
;

ALTER TABLE FEATURES.WTHDRWL_CNT
SET
    PARTITIONED BY (OBSN_DT)
;