Use crz_cust_scorecard;
DROP TABLE IF EXISTS RISK_MORT_ACCT_SNAPSHOT;
CREATE EXTERNAL TABLE RISK_MORT_ACCT_SNAPSHOT(
    MORT_NUM                    BIGINT,
    INSRT_PROCESS_TMSTMP        TIMESTAMP,
    OP_FIELD                    VARCHAR(1000),
    LOAN_AUTH_DT                DATE              COMMENT 'Date the Loan is Authorized',
    PD_OFF_DT                   DATE              COMMENT 'The date the mortage is paid off',
    LAST_RNEW_DT                DATE              COMMENT 'The date mortgage was last renewed',
    CRNT_TERM_MAT_DT            DATE              COMMENT 'Maturity of the current mortgage term',
    RNEWL_DT                    DATE              COMMENT 'Renewal Date',
    INTR_ADJ_DT                 DATE              COMMENT 'The date the interest rate is adjusted. During account creation, this date defaults to the current processing date.',
    FLOAT_CD                    CHAR(1)           COMMENT 'Mortgage Payment Frequency Code',
    PD_OFF_FLAG                 CHAR(1)           COMMENT 'Indicates that the Mortrgage has been paid off',
    FRCLSR_FLAG                 CHAR(1)           COMMENT 'Indicates if the mortgage has been foreclosed',
    MTH_IN_ARRS_CNT             INT               COMMENT 'Number of Months the account has been in delinquency',
    INS_CLASS_CD                VARCHAR(5)        COMMENT 'Numeric code specifying insurance class of the property',
    PRPTY_TYPE_CD               VARCHAR(10)       COMMENT 'Property type code - E.g. CND NC MFD NC Commer Indust ',
    PRPTY_TYPE_DESC             VARCHAR(10)       COMMENT 'Describes the property type E.g. SEMI-D = Semi Detatched',
    FUND_CD                     VARCHAR(4)        COMMENT 'Numeric code for funding type',
    CRNT_BAL_AMT                DECIMAL(18, 2)    COMMENT 'Current Balance on the Mortgage account',
    SERV_BR_TRNST_NUM           VARCHAR(5)        COMMENT 'Transit number of the Servicing Branch',
    INTR_DUE_AMT                DECIMAL(18, 2)    COMMENT 'Ineterest Amount Due',
    PROC_BR_TRNST_NUM           VARCHAR(5)        COMMENT 'Transit number of the branch processing the mortgage',
    MORT_AUTH_DT                DATE              COMMENT 'Authorization date of the mortgage',
    AUTH_AMT                    DECIMAL(18, 2)    COMMENT 'Original Loan Amount',
    LEND_VAL                    DECIMAL(18, 2)    COMMENT 'Lending Value - Dollar value assigned to the property',
    TAX_CRNT_BAL_AMT            DECIMAL(18, 2)    COMMENT 'Amount of Tax in Escrow',
    INTR_ACCR_AMT               DECIMAL(18, 5)    COMMENT 'Interest Accrual Amount',
    TOT_ADVNC_AMT               DECIMAL(18, 2)    COMMENT 'Total Amount to be Repaid by the borrower including fees and principal (RCRR definition Total Disbursement Amount)',
    BRWR_CD                     VARCHAR(5)        COMMENT 'Describes the borrwer as personal (P), non-personal (NP)',
    WEEK_FRST_UNPAID_DT         DATE              COMMENT 'Date the next payment is due - based on the float code (Payment frequency) of ''weekly''',
    SCRTY_TYPE_2                VARCHAR(5)        COMMENT 'Defines the type of security',
    APRSD_LAST_BLDNG_VAL_AMT    DECIMAL(18, 2)    COMMENT 'Last Appraisal value of the building',
    APRSD_LAND_VAL_AMT          DECIMAL(18, 2)    COMMENT 'Apraised value of the land',
    APRSD_LAST_LAND_VAL_AMT     DECIMAL(18, 2),
    APRSD_BLDNG_VAL_AMT         DECIMAL(18, 2),
    APRSD_ORIG_LAND_VAL_AMT     DECIMAL(18, 2)    COMMENT 'Original Appraised Land Value',
    APRSD_ORIG_BLDNG_VAL_AMT    DECIMAL(18, 2)    COMMENT 'Original Appraised Building Value',
    FINAL_ADVNC_DT              DATE              COMMENT 'Date of the most recent advance on the mortgage ',
    BUS_SRC_CD                  SMALLINT          COMMENT 'Business Source Code',
    FRST_UNPD_DT                DATE              COMMENT 'The date payment is due based on float code (frequency type) ''Monthly''',
    SALE_DT_AMT                 DECIMAL(18, 2),
    CRI_CD                      VARCHAR(1)        COMMENT 'Customer Risk Indicator',
    ARI_CD                      VARCHAR(1)        COMMENT 'Account Risk Indicator',
    STEP_FLAG                   VARCHAR(1)        COMMENT 'Scotia Total Equity Plan',
    STEP_PLN_AGRMNT_NUM         VARCHAR(15)       COMMENT 'STEP Plan agreement number',
    TOT_SUSP_BAL_AMT            DECIMAL(22, 2)    COMMENT 'Total Suspense balance amount',
    ACCT_TYPE_CD                SMALLINT          COMMENT 'Account Type Code',
    PROD_TYPE_CD                SMALLINT,
    PROD_TYPE_DESC              VARCHAR(50)       COMMENT 'Product Type Description',
    PRPTY_PROV_CD               VARCHAR(2)        COMMENT '2 Character province code',
    MORT_TERM_MTH               INT               COMMENT 'Mortgage term in months',
    MAX_INTR_RT                 DECIMAL(14, 5)    COMMENT 'Maximum interest rate',
    PRIM_CUST_CID               VARCHAR(40)       COMMENT 'Primary Customer ID',
    YTD_PREPAY_AMT              DECIMAL(18, 2)    COMMENT 'Year to Date prepayment amount',
    AMORT_MTHS                  INT               COMMENT 'Remaining amortization months',
    GL_ACCT_NUM                 VARCHAR(7)        COMMENT 'General Ledger Account Number',
    GL_TRNST_NUM                VARCHAR(5)        COMMENT 'General Ledger Transit Number',
    PROD_GRP_CD                 VARCHAR(5)        COMMENT 'Product Group Code -  A subset of a product class that represents a common deposit or loan application E.g. MTG, LN',
    UNIT_CNT                    SMALLINT          COMMENT 'Number of units in the property',
    COMM_TYPE                   VARCHAR(20)       COMMENT 'Defines the property as commercial or residential'
)
PARTITIONED BY( EFF_DT DATE, DATE_TYPE VARCHAR(20) COMMENT 'Shows Date Type for the partition date columm - ''Daily'',''Monthly'' etc')
CLUSTERED BY (MORT_NUM) SORTED BY (MORT_NUM ASC) INTO 60 BUCKETS
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_MORT_ACCT_SNAPSHOT'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

