from airflow.sdk import get_current_context

from bns.rrap.helpers.asset_event import (
    _pull_asset_event_extras,
    _push_asset_event_extras,
)


UPSTREAM_ASSET = [
    "ingestion.BASEL_ACCT_DIM",
    "ingestion.TNG_ACCT_MO",
    "ingestion.TM_DIM",
    "ingestion.TERANET_HOUSE_PRC_INDEX",
    "ingestion.PROVNCL_HOUSE_INDEX_SUM",
    "reference.HOUSING_INDEX",
]
DOWNSTREAM_ASSET = "features.LTV_TERANET"
DEPENDENCIES = {
    "export_ltv": ["duckdb_delete"],
    "duckdb_delete": ["duckdb_load"],
}


def export_ltv(
    duckdb_conn_id="duckdb-conn",
    sql=f"""
WITH
params AS (
    SELECT
        tm_id AS mth_tm_id,
        tm_lvl_end_dt AS month_end_dt
    FROM { UPSTREAM_ASSET[2] }
    WHERE 
        tm_lvl = 'Month'
        AND tm_id <= {{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="mth_tm_id") }}}}
)
, housing_index0 AS (
    SELECT
        b.month_end_dt,
        CASE
            WHEN UPPER(TRIM(a.label_1)) = 'COMPOSITE' THEN TRIM(a.label_1) || '_' || TRIM(a.label_2)
            WHEN UPPER(TRIM(a.label_2)) = 'OTTAWA_GATINEAU' THEN 'Ottawa_t'
            ELSE REPLACE(COALESCE(TRIM(a.label_2), ''), '_', ' ') || '_t'
        END AS region,
        TRY_CAST(a."index" AS DECIMAL(8,4)) AS "INDEX"
    FROM { UPSTREAM_ASSET[3] } a
    INNER JOIN params b ON
        a.mth_tm_id = b.mth_tm_id
    WHERE
        NOT (label_1 = 'ON' AND label_2 = 'OTTAWA_GATINEAU')
    UNION
    SELECT
        b.month_end_dt,
        TRIM(a.prov_cd) AS region,
        a.house_index_rto
    FROM { UPSTREAM_ASSET[4] } a
    INNER JOIN params b ON
        a.mth_tm_id = b.mth_tm_id
)
, housing_index AS (
    SELECT
        a.month_end_dt
        , a.region
        , coalesce(b.INDEX, a.INDEX) AS "INDEX"
    FROM housing_index0 a
    LEFT OUTER JOIN { UPSTREAM_ASSET[5] } b ON
        a.month_end_dt = b.month_end_dt
        AND a.region = b.region
)
, province AS (
    SELECT 
        month_end_dt,
        trim(account_id) AS account_id,
        end_principal_balance,
        CASE 
            WHEN PROP_PURCHASE_DT IS NOT NULL AND PROP_PURCHASE_AMT IS NOT NULL THEN PROP_PURCHASE_AMT
            WHEN ORIG_PROP_APPRAISAL_DT IS NOT NULL AND ORIG_PROP_APPRAISAL_VAL IS NOT NULL THEN ORIG_PROP_APPRAISAL_VAL
            WHEN LST_PROP_APPRAISAL_DT IS NOT NULL AND LST_PROP_APPRAISAL_VAL IS NOT NULL THEN LST_PROP_APPRAISAL_VAL
            WHEN ORIG_PROP_APPRAISAL_VAL IS NOT NULL AND ORIG_PROP_APPRAISAL_DT IS NULL THEN ORIG_PROP_APPRAISAL_VAL
            WHEN PROP_PURCHASE_AMT IS NOT NULL AND PROP_PURCHASE_DT IS NULL THEN PROP_PURCHASE_AMT
            WHEN LST_PROP_APPRAISAL_VAL IS NOT NULL AND LST_PROP_APPRAISAL_DT IS NULL THEN LST_PROP_APPRAISAL_VAL
        END AS prop_val,
        CASE 
            WHEN PROP_PURCHASE_DT IS NOT NULL AND PROP_PURCHASE_AMT IS NOT NULL THEN LAST_DAY(PROP_PURCHASE_DT)
            WHEN ORIG_PROP_APPRAISAL_DT IS NOT NULL AND ORIG_PROP_APPRAISAL_VAL IS NOT NULL THEN LAST_DAY(ORIG_PROP_APPRAISAL_DT)
            WHEN LST_PROP_APPRAISAL_DT IS NOT NULL AND LST_PROP_APPRAISAL_VAL IS NOT NULL THEN LAST_DAY(LST_PROP_APPRAISAL_DT)
            WHEN ORIG_PROP_APPRAISAL_VAL IS NOT NULL AND ORIG_PROP_APPRAISAL_DT IS NULL THEN LAST_DAY(OPEN_DT)
            WHEN PROP_PURCHASE_AMT IS NOT NULL AND PROP_PURCHASE_DT IS NULL THEN LAST_DAY(OPEN_DT)
            WHEN LST_PROP_APPRAISAL_VAL IS NOT NULL AND LST_PROP_APPRAISAL_DT IS NULL THEN LAST_DAY(OPEN_DT)
        END AS prop_val_date,
        trim(FSA) AS FSA,
        CASE 
            WHEN prop_province_code IS NULL OR prop_province_code='' OR prop_province_code='?' THEN 
                CASE 
                    WHEN substr(FSA,1,1)='A' THEN 'NL'
                    WHEN substr(FSA,1,1)='B' THEN 'NS'
                    WHEN substr(FSA,1,1)='C' THEN 'PE'
                    WHEN substr(FSA,1,1)='E' THEN 'NB'
                    WHEN substr(FSA,1,1)='G' THEN 'QC'
                    WHEN substr(FSA,1,1)='H' THEN 'QC'
                    WHEN substr(FSA,1,1)='J' THEN 'QC'
                    WHEN substr(FSA,1,1)='R' THEN 'MB'
                    WHEN substr(FSA,1,1)='S' THEN 'SK'
                    WHEN substr(FSA,1,1)='T' THEN 'AB'
                    WHEN substr(FSA,1,1)='V' THEN 'BC'
                    WHEN substr(FSA,1,1)='X' THEN 'NT'
                    WHEN substr(FSA,1,1)='Y' THEN 'YT'
                    WHEN TRIM(account_id)='MBS~370528' THEN 'MB'
                    WHEN TRIM(account_id)='MBS~370579' THEN 'BC'
                    ELSE 'ON'
                END
            ELSE prop_province_code
        END AS province
    FROM { UPSTREAM_ASSET[1] }
    WHERE 
        month_end_dt = (SELECT max(month_end_dt) FROM params)
)
, prov_city AS (
    SELECT 
        *,
        CASE 
            WHEN province='AB' THEN
                CASE
                    WHEN FSA='Airdrie' THEN 'Calgary'
                    WHEN FSA='Beiseker' THEN 'Calgary'
                    WHEN FSA='Calgary' THEN 'Calgary'
                    WHEN FSA='Chestermere' THEN 'Calgary'
                    WHEN FSA='Cochrane' THEN 'Calgary'
                    WHEN FSA='Crossfield' THEN 'Calgary'
                    WHEN FSA='Irricana' THEN 'Calgary'
                    WHEN FSA='Rocky View' THEN 'Calgary'
                    WHEN FSA='Tsuu T''ina Nation' THEN 'Calgary'
                    WHEN FSA='Sarcee' THEN 'Calgary'
                    WHEN FSA='T1Y' THEN 'Calgary'
                    WHEN FSA='T2A' THEN 'Calgary'
                    WHEN FSA='T2B' THEN 'Calgary'
                    WHEN FSA='T2C' THEN 'Calgary'
                    WHEN FSA='T2E' THEN 'Calgary'
                    WHEN FSA='T2G' THEN 'Calgary'
                    WHEN FSA='T2H' THEN 'Calgary'
                    WHEN FSA='T2J' THEN 'Calgary'
                    WHEN FSA='T2K' THEN 'Calgary'
                    WHEN FSA='T2L' THEN 'Calgary'
                    WHEN FSA='T2M' THEN 'Calgary'
                    WHEN FSA='T2N' THEN 'Calgary'
                    WHEN FSA='T2P' THEN 'Calgary'
                    WHEN FSA='T2R' THEN 'Calgary'
                    WHEN FSA='T2S' THEN 'Calgary'
                    WHEN FSA='T2T' THEN 'Calgary'
                    WHEN FSA='T2V' THEN 'Calgary'
                    WHEN FSA='T2W' THEN 'Calgary'
                    WHEN FSA='T2X' THEN 'Calgary'
                    WHEN FSA='T2Y' THEN 'Calgary'
                    WHEN FSA='T2Z' THEN 'Calgary'
                    WHEN FSA='T3A' THEN 'Calgary'
                    WHEN FSA='T3B' THEN 'Calgary'
                    WHEN FSA='T3C' THEN 'Calgary'
                    WHEN FSA='T3E' THEN 'Calgary'
                    WHEN FSA='T3G' THEN 'Calgary'
                    WHEN FSA='T3H' THEN 'Calgary'
                    WHEN FSA='T3J' THEN 'Calgary'
                    WHEN FSA='T3K' THEN 'Calgary'
                    WHEN FSA='T3L' THEN 'Calgary'
                    WHEN FSA='T3M' THEN 'Calgary'
                    WHEN FSA='T3N' THEN 'Calgary'
                    WHEN FSA='T3P' THEN 'Calgary'
                    WHEN FSA='T3R' THEN 'Calgary'
                    WHEN FSA='T3S' THEN 'Calgary'
                    WHEN FSA='T4A' THEN 'Calgary'
                    WHEN FSA='T4B' THEN 'Calgary'
                    WHEN FSA='T4C' THEN 'Calgary'
                    WHEN FSA='T1X' THEN 'Calgary'
                    WHEN FSA='T0M 0G0' THEN 'Calgary'
                    WHEN FSA='T0M0G0' THEN 'Calgary'
                    WHEN FSA='T0M 0S0' THEN 'Calgary'
                    WHEN FSA='T0M0S0' THEN 'Calgary'
                    WHEN FSA='T0M 1B0' THEN 'Calgary'
                    WHEN FSA='T0M1B0' THEN 'Calgary'
                    WHEN FSA='Alexander' THEN 'Edmonton'
                    WHEN FSA='Beaumont' THEN 'Edmonton'
                    WHEN FSA='Betula Beach' THEN 'Edmonton'
                    WHEN FSA='Bon Accord' THEN 'Edmonton'
                    WHEN FSA='Bruderheim' THEN 'Edmonton'
                    WHEN FSA='Calmar' THEN 'Edmonton'
                    WHEN FSA='Devon' THEN 'Edmonton'
                    WHEN FSA='Edmonton' THEN 'Edmonton'
                    WHEN FSA='Fort Saskatchewan' THEN 'Edmonton'
                    WHEN FSA='Gibbons' THEN 'Edmonton'
                    WHEN FSA='Golden Days' THEN 'Edmonton'
                    WHEN FSA='Itaska Beach' THEN 'Edmonton'
                    WHEN FSA='Kapasiwin' THEN 'Edmonton'
                    WHEN FSA='Lakeview' THEN 'Edmonton'
                    WHEN FSA='Leduc' THEN 'Edmonton'
                    WHEN FSA='Leduc County' THEN 'Edmonton'
                    WHEN FSA='Legal' THEN 'Edmonton'
                    WHEN FSA='Morinviller' THEN 'Edmonton'
                    WHEN FSA='New Sarepta' THEN 'Edmonton'
                    WHEN FSA='Parkland County' THEN 'Edmonton'
                    WHEN FSA='Point Alison' THEN 'Edmonton'
                    WHEN FSA='Redwater' THEN 'Edmonton'
                    WHEN FSA='Seba Beach' THEN 'Edmonton'
                    WHEN FSA='Spring Lake' THEN 'Edmonton'
                    WHEN FSA='Spruce Grove' THEN 'Edmonton'
                    WHEN FSA='St. Albert' THEN 'Edmonton'
                    WHEN FSA='Stony Plain' THEN 'Edmonton'
                    WHEN FSA='Strathcona County' THEN 'Edmonton'
                    WHEN FSA='Sturgeon County' THEN 'Edmonton'
                    WHEN FSA='Sundance Beach' THEN 'Edmonton'
                    WHEN FSA='Thorsby' THEN 'Edmonton'
                    WHEN FSA='Wabamun' THEN 'Edmonton'
                    WHEN FSA='Warburg ' THEN 'Edmonton'
                    WHEN FSA='T4X' THEN 'Edmonton'
                    WHEN FSA='Alexander' THEN 'Edmonton'
                    WHEN FSA='T4X' THEN 'Edmonton'
                    WHEN FSA='T5A' THEN 'Edmonton'
                    WHEN FSA='T5B' THEN 'Edmonton'
                    WHEN FSA='T5C' THEN 'Edmonton'
                    WHEN FSA='T5E' THEN 'Edmonton'
                    WHEN FSA='T5G' THEN 'Edmonton'
                    WHEN FSA='T5H' THEN 'Edmonton'
                    WHEN FSA='T5J' THEN 'Edmonton'
                    WHEN FSA='T5K' THEN 'Edmonton'
                    WHEN FSA='T5L' THEN 'Edmonton'
                    WHEN FSA='T5M' THEN 'Edmonton'
                    WHEN FSA='T5N' THEN 'Edmonton'
                    WHEN FSA='T5P' THEN 'Edmonton'
                    WHEN FSA='T5R' THEN 'Edmonton'
                    WHEN FSA='T5S' THEN 'Edmonton'
                    WHEN FSA='T5T' THEN 'Edmonton'
                    WHEN FSA='T5V' THEN 'Edmonton'
                    WHEN FSA='T5W' THEN 'Edmonton'
                    WHEN FSA='T5X' THEN 'Edmonton'
                    WHEN FSA='T5Y' THEN 'Edmonton'
                    WHEN FSA='T5Z' THEN 'Edmonton'
                    WHEN FSA='T6A' THEN 'Edmonton'
                    WHEN FSA='T6B' THEN 'Edmonton'
                    WHEN FSA='T6C' THEN 'Edmonton'
                    WHEN FSA='T6E' THEN 'Edmonton'
                    WHEN FSA='T6G' THEN 'Edmonton'
                    WHEN FSA='T6H' THEN 'Edmonton'
                    WHEN FSA='T6J' THEN 'Edmonton'
                    WHEN FSA='T6K' THEN 'Edmonton'
                    WHEN FSA='T6L' THEN 'Edmonton'
                    WHEN FSA='T6M' THEN 'Edmonton'
                    WHEN FSA='T6N' THEN 'Edmonton'
                    WHEN FSA='T6P' THEN 'Edmonton'
                    WHEN FSA='T6R' THEN 'Edmonton'
                    WHEN FSA='T6S' THEN 'Edmonton'
                    WHEN FSA='T6T' THEN 'Edmonton'
                    WHEN FSA='T6V' THEN 'Edmonton'
                    WHEN FSA='T6W' THEN 'Edmonton'
                    WHEN FSA='T6X' THEN 'Edmonton'
                    WHEN FSA='T7X' THEN 'Edmonton'
                    WHEN FSA='T7Y' THEN 'Edmonton'
                    WHEN FSA='T7Z' THEN 'Edmonton'
                    WHEN FSA='T8L' THEN 'Edmonton'
                    WHEN FSA='T8N' THEN 'Edmonton'
                    WHEN FSA='T8R' THEN 'Edmonton'
                    WHEN FSA='T9E' THEN 'Edmonton'
                    WHEN FSA='T9G' THEN 'Edmonton'
                    WHEN FSA='T0A 0K0' THEN 'Edmonton'
                    WHEN FSA='T0A 2W0' THEN 'Edmonton'
                    WHEN FSA='T0A 1N0' THEN 'Edmonton'
                    WHEN FSA='T0B 0S0' THEN 'Edmonton'
                    WHEN FSA='T0B 3M0' THEN 'Edmonton'
                    WHEN FSA='T0C 0V0' THEN 'Edmonton'
                    WHEN FSA='T0C 2P0' THEN 'Edmonton'
                    WHEN FSA='T0C 2T0' THEN 'Edmonton'
                    WHEN FSA='T0E 2B0' THEN 'Edmonton'
                    WHEN FSA='T0E 2K0' THEN 'Edmonton'
                    WHEN FSA='T0L 1V0' THEN 'Edmonton'
                    WHEN FSA='T0G 1L0' THEN 'Edmonton'
                    WHEN FSA='T0A0K0' THEN 'Edmonton'
                    WHEN FSA='T0A2W0' THEN 'Edmonton'
                    WHEN FSA='T0A1N0' THEN 'Edmonton'
                    WHEN FSA='T0B0S0' THEN 'Edmonton'
                    WHEN FSA='T0B3M0' THEN 'Edmonton'
                    WHEN FSA='T0C0V0' THEN 'Edmonton'
                    WHEN FSA='T0C2P0' THEN 'Edmonton'
                    WHEN FSA='T0C2T0' THEN 'Edmonton'
                    WHEN FSA='T0E2B0' THEN 'Edmonton'
                    WHEN FSA='T0E2K0' THEN 'Edmonton'
                    WHEN FSA='T0L1V0' THEN 'Edmonton'
                    WHEN FSA='T0G1L0' THEN 'Edmonton'
                    ELSE 'AB - other'
                END
            WHEN province='BC' THEN
                CASE
                    WHEN FSA='Anmore' THEN 'Vancouver'
                    WHEN FSA='Barnston Island' THEN 'Vancouver'
                    WHEN FSA='Belcarra' THEN 'Vancouver'
                    WHEN FSA='Bowen Island' THEN 'Vancouver'
                    WHEN FSA='Burnaby' THEN 'Vancouver'
                    WHEN FSA='Burrard Inlet 3' THEN 'Vancouver'
                    WHEN FSA='Capilano' THEN 'Vancouver'
                    WHEN FSA='Coquitlam' THEN 'Vancouver'
                    WHEN FSA='Delta' THEN 'Vancouver'
                    WHEN FSA='Greater Vancouver' THEN 'Vancouver'
                    WHEN FSA='Katzie' THEN 'Vancouver'
                    WHEN FSA='Langley' THEN 'Vancouver'
                    WHEN FSA='Langl' THEN 'Vancouver'
                    WHEN FSA='Lions Bay' THEN 'Vancouver'
                    WHEN FSA='Maple Ridge' THEN 'Vancouver'
                    WHEN FSA='Matsqui' THEN 'Vancouver'
                    WHEN FSA='McMillan Island 6' THEN 'Vancouver'
                    WHEN FSA='Mission' THEN 'Vancouver'
                    WHEN FSA='Musqueam' THEN 'Vancouver'
                    WHEN FSA='New Westminster' THEN 'Vancouver'
                    WHEN FSA='New Westminister' THEN 'Vancouver'
                    WHEN FSA='NewWestmin' THEN 'Vancouver'
                    WHEN FSA='North Vancouver' THEN 'Vancouver'
                    WHEN FSA='North Vancouv' THEN 'Vancouver'
                    WHEN FSA='Pitt Meadows' THEN 'Vancouver'
                    WHEN FSA='Port Coquitlam' THEN 'Vancouver'
                    WHEN FSA='Port Moody' THEN 'Vancouver'
                    WHEN FSA='Richmond' THEN 'Vancouver'
                    WHEN FSA='Semiahmoo' THEN 'Vancouver'
                    WHEN FSA='Seymour Creek' THEN 'Vancouver'
                    WHEN FSA='Surrey' THEN 'Vancouver'
                    WHEN FSA='Tsawwassen' THEN 'Vancouver'
                    WHEN FSA='Vancouver' THEN 'Vancouver'
                    WHEN FSA='Vanvouver' THEN 'Vancouver'
                    WHEN FSA='West Vancouver' THEN 'Vancouver'
                    WHEN FSA='White Rock' THEN 'Vancouver'
                    WHEN FSA='Whonnock' THEN 'Vancouver'
                    WHEN FSA='V3A' THEN 'Vancouver'
                    WHEN FSA='V4A' THEN 'Vancouver'
                    WHEN FSA='V5A' THEN 'Vancouver'
                    WHEN FSA='V6A' THEN 'Vancouver'
                    WHEN FSA='V7A' THEN 'Vancouver'
                    WHEN FSA='V3B' THEN 'Vancouver'
                    WHEN FSA='V4B' THEN 'Vancouver'
                    WHEN FSA='V5B' THEN 'Vancouver'
                    WHEN FSA='V6B' THEN 'Vancouver'
                    WHEN FSA='V7B' THEN 'Vancouver'
                    WHEN FSA='V3C' THEN 'Vancouver'
                    WHEN FSA='V4C' THEN 'Vancouver'
                    WHEN FSA='V5C' THEN 'Vancouver'
                    WHEN FSA='V6C' THEN 'Vancouver'
                    WHEN FSA='V7C' THEN 'Vancouver'
                    WHEN FSA='V3E' THEN 'Vancouver'
                    WHEN FSA='V4E' THEN 'Vancouver'
                    WHEN FSA='V5E' THEN 'Vancouver'
                    WHEN FSA='V6E' THEN 'Vancouver'
                    WHEN FSA='V7E' THEN 'Vancouver'
                    WHEN FSA='V4G' THEN 'Vancouver'
                    WHEN FSA='V5G' THEN 'Vancouver'
                    WHEN FSA='V6G' THEN 'Vancouver'
                    WHEN FSA='V3H' THEN 'Vancouver'
                    WHEN FSA='V5H' THEN 'Vancouver'
                    WHEN FSA='V6H' THEN 'Vancouver'
                    WHEN FSA='V3J' THEN 'Vancouver'
                    WHEN FSA='V5J' THEN 'Vancouver'
                    WHEN FSA='V6J' THEN 'Vancouver'
                    WHEN FSA='V3K' THEN 'Vancouver'
                    WHEN FSA='V4K' THEN 'Vancouver'
                    WHEN FSA='V5K' THEN 'Vancouver'
                    WHEN FSA='V6K' THEN 'Vancouver'
                    WHEN FSA='V3L' THEN 'Vancouver'
                    WHEN FSA='V4L' THEN 'Vancouver'
                    WHEN FSA='V5L' THEN 'Vancouver'
                    WHEN FSA='V6L' THEN 'Vancouver'
                    WHEN FSA='V1M' THEN 'Vancouver'
                    WHEN FSA='V3M' THEN 'Vancouver'
                    WHEN FSA='V4M' THEN 'Vancouver'
                    WHEN FSA='V5M' THEN 'Vancouver'
                    WHEN FSA='V6M' THEN 'Vancouver'
                    WHEN FSA='V3N' THEN 'Vancouver'
                    WHEN FSA='V4N' THEN 'Vancouver'
                    WHEN FSA='V5N' THEN 'Vancouver'
                    WHEN FSA='V6N' THEN 'Vancouver'
                    WHEN FSA='V4P' THEN 'Vancouver'
                    WHEN FSA='V5P' THEN 'Vancouver'
                    WHEN FSA='V6P' THEN 'Vancouver'
                    WHEN FSA='V3R' THEN 'Vancouver'
                    WHEN FSA='V4R' THEN 'Vancouver'
                    WHEN FSA='V5R' THEN 'Vancouver'
                    WHEN FSA='V6R' THEN 'Vancouver'
                    WHEN FSA='V3S' THEN 'Vancouver'
                    WHEN FSA='V4S' THEN 'Vancouver'
                    WHEN FSA='V5S' THEN 'Vancouver'
                    WHEN FSA='V6S' THEN 'Vancouver'
                    WHEN FSA='V7S' THEN 'Vancouver'
                    WHEN FSA='V3T' THEN 'Vancouver'
                    WHEN FSA='V5T' THEN 'Vancouver'
                    WHEN FSA='V6T' THEN 'Vancouver'
                    WHEN FSA='V7T' THEN 'Vancouver'
                    WHEN FSA='V2V' THEN 'Vancouver'
                    WHEN FSA='V3V' THEN 'Vancouver'
                    WHEN FSA='V5V' THEN 'Vancouver'
                    WHEN FSA='V6V' THEN 'Vancouver'
                    WHEN FSA='V7V' THEN 'Vancouver'
                    WHEN FSA='V2W' THEN 'Vancouver'
                    WHEN FSA='V3W' THEN 'Vancouver'
                    WHEN FSA='V4W' THEN 'Vancouver'
                    WHEN FSA='V5W' THEN 'Vancouver'
                    WHEN FSA='V6W' THEN 'Vancouver'
                    WHEN FSA='V7W' THEN 'Vancouver'
                    WHEN FSA='V2X' THEN 'Vancouver'
                    WHEN FSA='V3X' THEN 'Vancouver'
                    WHEN FSA='V5X' THEN 'Vancouver'
                    WHEN FSA='V6X' THEN 'Vancouver'
                    WHEN FSA='V7X' THEN 'Vancouver'
                    WHEN FSA='V2Y' THEN 'Vancouver'
                    WHEN FSA='V3Y' THEN 'Vancouver'
                    WHEN FSA='V5Y' THEN 'Vancouver'
                    WHEN FSA='V6Y' THEN 'Vancouver'
                    WHEN FSA='V7Y' THEN 'Vancouver'
                    WHEN FSA='V2Z' THEN 'Vancouver'
                    WHEN FSA='V5Z' THEN 'Vancouver'
                    WHEN FSA='V6Z' THEN 'Vancouver'
                    WHEN FSA='Becher Bay' THEN 'Victoria'
                    WHEN FSA='Capital H' THEN 'Victoria'
                    WHEN FSA='Central Saanich' THEN 'Victoria'
                    WHEN FSA='Cole Bay' THEN 'Victoria'
                    WHEN FSA='Colwood' THEN 'Victoria'
                    WHEN FSA='East Saanich' THEN 'Victoria'
                    WHEN FSA='Esquimalt' THEN 'Victoria'
                    WHEN FSA='Highlands' THEN 'Victoria'
                    WHEN FSA='Langford' THEN 'Victoria'
                    WHEN FSA='Metchosin' THEN 'Victoria'
                    WHEN FSA='New Songhees' THEN 'Victoria'
                    WHEN FSA='North Saanich' THEN 'Victoria'
                    WHEN FSA='Oak Bay' THEN 'Victoria'
                    WHEN FSA='Saanich' THEN 'Victoria'
                    WHEN FSA='Sidney' THEN 'Victoria'
                    WHEN FSA='Sooke' THEN 'Victoria'
                    WHEN FSA='South Saanich' THEN 'Victoria'
                    WHEN FSA='T''Sou-ke' THEN 'Victoria'
                    WHEN FSA='sooke' THEN 'Victoria'
                    WHEN FSA='Union Bay' THEN 'Victoria'
                    WHEN FSA='Victoria' THEN 'Victoria'
                    WHEN FSA='View Royal' THEN 'Victoria'
                    WHEN FSA='V9A' THEN 'Victoria'
                    WHEN FSA='V9B' THEN 'Victoria'
                    WHEN FSA='V9C' THEN 'Victoria'
                    WHEN FSA='V9E' THEN 'Victoria'
                    WHEN FSA='V8L' THEN 'Victoria'
                    WHEN FSA='V8M' THEN 'Victoria'
                    WHEN FSA='V8N' THEN 'Victoria'
                    WHEN FSA='V8P' THEN 'Victoria'
                    WHEN FSA='V8R' THEN 'Victoria'
                    WHEN FSA='V8S' THEN 'Victoria'
                    WHEN FSA='V9T' THEN 'Victoria'
                    WHEN FSA='V8V' THEN 'Victoria'
                    WHEN FSA='V8W' THEN 'Victoria'
                    WHEN FSA='V8X' THEN 'Victoria'
                    WHEN FSA='V8Y' THEN 'Victoria'
                    WHEN FSA='V8Z' THEN 'Victoria'
                    ELSE 'BC - other'
                END
            WHEN province IN ('NS','NO') THEN
                CASE
                    WHEN FSA='Beaver Lake' THEN 'Halifax'
                    WHEN FSA='Cole Harbour' THEN 'Halifax'
                    WHEN FSA='Halifax' THEN 'Halifax'
                    WHEN FSA='Sheet Harbour' THEN 'Halifax'
                    WHEN FSA='Shubenacadie ' THEN 'Halifax'
                    WHEN FSA='B3H' THEN 'Halifax'
                    WHEN FSA='B3J' THEN 'Halifax'
                    WHEN FSA='B3K' THEN 'Halifax'
                    WHEN FSA='B3L' THEN 'Halifax'
                    WHEN FSA='B3M' THEN 'Halifax'
                    WHEN FSA='B3N' THEN 'Halifax'
                    WHEN FSA='B3P' THEN 'Halifax'
                    WHEN FSA='B3R' THEN 'Halifax'
                    WHEN FSA='B3S' THEN 'Halifax'
                    WHEN FSA='B3V' THEN 'Halifax'
                    ELSE 'NS - other'
                END
            WHEN province='MB' THEN
                CASE
                    WHEN FSA='Brokenhead' THEN 'Winnipeg'
                    WHEN FSA='East St. Paul' THEN 'Winnipeg'
                    WHEN FSA='Headingley' THEN 'Winnipeg'
                    WHEN FSA='Macdonald' THEN 'Winnipeg'
                    WHEN FSA='Ritchot' THEN 'Winnipeg'
                    WHEN FSA='Rosser' THEN 'Winnipeg'
                    WHEN FSA='Springfield' THEN 'Winnipeg'
                    WHEN FSA='St. Clements' THEN 'Winnipeg'
                    WHEN FSA='St. François Xavier' THEN 'Winnipeg'
                    WHEN FSA='Taché' THEN 'Winnipeg'
                    WHEN FSA='West St. Paul' THEN 'Winnipeg'
                    WHEN FSA='Winnipeg' THEN 'Winnipeg'
                    WHEN FSA='R2C' THEN 'Winnipeg'
                    WHEN FSA='R2E' THEN 'Winnipeg'
                    WHEN FSA='R2G' THEN 'Winnipeg'
                    WHEN FSA='R2H' THEN 'Winnipeg'
                    WHEN FSA='R2J' THEN 'Winnipeg'
                    WHEN FSA='R2K' THEN 'Winnipeg'
                    WHEN FSA='R2L' THEN 'Winnipeg'
                    WHEN FSA='R2M' THEN 'Winnipeg'
                    WHEN FSA='R2N' THEN 'Winnipeg'
                    WHEN FSA='R2P' THEN 'Winnipeg'
                    WHEN FSA='R2R' THEN 'Winnipeg'
                    WHEN FSA='R2V' THEN 'Winnipeg'
                    WHEN FSA='R2W' THEN 'Winnipeg'
                    WHEN FSA='R2X' THEN 'Winnipeg'
                    WHEN FSA='R2Y' THEN 'Winnipeg'
                    WHEN FSA='R3A' THEN 'Winnipeg'
                    WHEN FSA='R3B' THEN 'Winnipeg'
                    WHEN FSA='R3C' THEN 'Winnipeg'
                    WHEN FSA='R3E' THEN 'Winnipeg'
                    WHEN FSA='R3G' THEN 'Winnipeg'
                    WHEN FSA='R3H' THEN 'Winnipeg'
                    WHEN FSA='R3J' THEN 'Winnipeg'
                    WHEN FSA='R3K' THEN 'Winnipeg'
                    WHEN FSA='R3L' THEN 'Winnipeg'
                    WHEN FSA='R3M' THEN 'Winnipeg'
                    WHEN FSA='R3N' THEN 'Winnipeg'
                    WHEN FSA='R3P' THEN 'Winnipeg'
                    WHEN FSA='R3R' THEN 'Winnipeg'
                    WHEN FSA='R3S' THEN 'Winnipeg'
                    WHEN FSA='R3T' THEN 'Winnipeg'
                    WHEN FSA='R3V' THEN 'Winnipeg'
                    WHEN FSA='R3W' THEN 'Winnipeg'
                    WHEN FSA='R3X' THEN 'Winnipeg'
                    WHEN FSA='R3Y' THEN 'Winnipeg'
                    WHEN FSA='R4A' THEN 'Winnipeg'
                    WHEN FSA='R4L' THEN 'Winnipeg'
                    WHEN FSA='R4H' THEN 'Winnipeg'
                    WHEN FSA='R4J' THEN 'Winnipeg'
                    WHEN FSA='R0H 0S0' THEN 'Winnipeg'
                    WHEN FSA='R0H 1E0' THEN 'Winnipeg'
                    WHEN FSA='R0H0S0' THEN 'Winnipeg'
                    WHEN FSA='R0H1E0' THEN 'Winnipeg'
                    ELSE 'MB - other'
                END
            WHEN province='ON' THEN
                CASE
                    WHEN FSA='Burlington' THEN 'Hamilton'
                    WHEN FSA='Grimsby' THEN 'Hamilton'
                    WHEN FSA='Hamilton' THEN 'Hamilton'
                    WHEN FSA='L3M' THEN 'Hamilton'
                    WHEN FSA='L8E' THEN 'Hamilton'
                    WHEN FSA='L8G' THEN 'Hamilton'
                    WHEN FSA='L8H' THEN 'Hamilton'
                    WHEN FSA='L8J' THEN 'Hamilton'
                    WHEN FSA='L8K' THEN 'Hamilton'
                    WHEN FSA='L8L' THEN 'Hamilton'
                    WHEN FSA='L8M' THEN 'Hamilton'
                    WHEN FSA='L8N' THEN 'Hamilton'
                    WHEN FSA='L8P' THEN 'Hamilton'
                    WHEN FSA='L8R' THEN 'Hamilton'
                    WHEN FSA='L8S' THEN 'Hamilton'
                    WHEN FSA='L8T' THEN 'Hamilton'
                    WHEN FSA='L8V' THEN 'Hamilton'
                    WHEN FSA='L8W' THEN 'Hamilton'
                    WHEN FSA='L9A' THEN 'Hamilton'
                    WHEN FSA='L9B' THEN 'Hamilton'
                    WHEN FSA='L9C' THEN 'Hamilton'
                    WHEN FSA='L7L' THEN 'Hamilton'
                    WHEN FSA='L7M' THEN 'Hamilton'
                    WHEN FSA='L7N' THEN 'Hamilton'
                    WHEN FSA='L7P' THEN 'Hamilton'
                    WHEN FSA='L7R' THEN 'Hamilton'
                    WHEN FSA='L7S' THEN 'Hamilton'
                    WHEN FSA='L7T' THEN 'Hamilton'
                    WHEN FSA='Ajax' THEN 'Toronto'
                    WHEN FSA='L1S' THEN 'Toronto'
                    WHEN FSA='L1T' THEN 'Toronto'
                    WHEN FSA='L1Z' THEN 'Toronto'
                    WHEN FSA='Aurora' THEN 'Toronto'
                    WHEN FSA='L4G' THEN 'Toronto'
                    WHEN FSA='Bradford West Gwillimbury' THEN 'Toronto'
                    WHEN FSA='L3Z' THEN 'Toronto'
                    WHEN FSA='Brampton' THEN 'Toronto'
                    WHEN FSA='L6P' THEN 'Toronto'
                    WHEN FSA='L6R' THEN 'Toronto'
                    WHEN FSA='L6S' THEN 'Toronto'
                    WHEN FSA='L6T' THEN 'Toronto'
                    WHEN FSA='L6V' THEN 'Toronto'
                    WHEN FSA='L6W' THEN 'Toronto'
                    WHEN FSA='L6X' THEN 'Toronto'
                    WHEN FSA='L6Y' THEN 'Toronto'
                    WHEN FSA='L6Z' THEN 'Toronto'
                    WHEN FSA='L7A' THEN 'Toronto'
                    WHEN FSA='Caledon' THEN 'Toronto'
                    WHEN FSA='L7C' THEN 'Toronto'
                    WHEN FSA='L7K' THEN 'Toronto'
                    WHEN FSA='L0N 1E0' THEN 'Toronto'
                    WHEN FSA='L0N1E0' THEN 'Toronto'
                    WHEN FSA='Chippewas of Georgina Island First Nation' THEN 'Toronto'
                    WHEN FSA='East Gwillimbury' THEN 'Toronto'
                    WHEN FSA='L9N' THEN 'Toronto'
                    WHEN FSA='Georgina' THEN 'Toronto'
                    WHEN FSA='Halton Hills' THEN 'Toronto'
                    WHEN FSA='King' THEN 'Toronto'
                    WHEN FSA='L7B' THEN 'Toronto'
                    WHEN FSA='Markham' THEN 'Toronto'
                    WHEN FSA='L3P' THEN 'Toronto'
                    WHEN FSA='L3R' THEN 'Toronto'
                    WHEN FSA='L3S' THEN 'Toronto'
                    WHEN FSA='L3B' THEN 'Toronto'
                    WHEN FSA='L6B' THEN 'Toronto'
                    WHEN FSA='L6C' THEN 'Toronto'
                    WHEN FSA='L6E' THEN 'Toronto'
                    WHEN FSA='L6G' THEN 'Toronto'
                    WHEN FSA='Milton' THEN 'Toronto'
                    WHEN FSA='L9T' THEN 'Toronto'
                    WHEN FSA='Mississauga' THEN 'Toronto'
                    WHEN FSA='L4T' THEN 'Toronto'
                    WHEN FSA='L4V' THEN 'Toronto'
                    WHEN FSA='L4W' THEN 'Toronto'
                    WHEN FSA='L4X' THEN 'Toronto'
                    WHEN FSA='L4Y' THEN 'Toronto'
                    WHEN FSA='L4Z' THEN 'Toronto'
                    WHEN FSA='L5A' THEN 'Toronto'
                    WHEN FSA='L5B' THEN 'Toronto'
                    WHEN FSA='L5C' THEN 'Toronto'
                    WHEN FSA='L5E' THEN 'Toronto'
                    WHEN FSA='L5G' THEN 'Toronto'
                    WHEN FSA='L5H' THEN 'Toronto'
                    WHEN FSA='L5J' THEN 'Toronto'
                    WHEN FSA='L5K' THEN 'Toronto'
                    WHEN FSA='L5L' THEN 'Toronto'
                    WHEN FSA='L5M' THEN 'Toronto'
                    WHEN FSA='L5N' THEN 'Toronto'
                    WHEN FSA='L5P' THEN 'Toronto'
                    WHEN FSA='L5R' THEN 'Toronto'
                    WHEN FSA='L5S' THEN 'Toronto'
                    WHEN FSA='L5T' THEN 'Toronto'
                    WHEN FSA='L5V' THEN 'Toronto'
                    WHEN FSA='L5W' THEN 'Toronto'
                    WHEN FSA='Mono' THEN 'Toronto'
                    WHEN FSA='New Tecumseth' THEN 'Toronto'
                    WHEN FSA='Newmarket' THEN 'Toronto'
                    WHEN FSA='L3X' THEN 'Toronto'
                    WHEN FSA='L3Y' THEN 'Toronto'
                    WHEN FSA='Oakville' THEN 'Toronto'
                    WHEN FSA='L6H' THEN 'Toronto'
                    WHEN FSA='L6J' THEN 'Toronto'
                    WHEN FSA='L6K' THEN 'Toronto'
                    WHEN FSA='L6L' THEN 'Toronto'
                    WHEN FSA='L6M' THEN 'Toronto'
                    WHEN FSA='Orangeville' THEN 'Toronto'
                    WHEN FSA='L9V' THEN 'Toronto'
                    WHEN FSA='L9W' THEN 'Toronto'
                    WHEN FSA='Pickering' THEN 'Toronto'
                    WHEN FSA='L1V' THEN 'Toronto'
                    WHEN FSA='L1W' THEN 'Toronto'
                    WHEN FSA='L1X' THEN 'Toronto'
                    WHEN FSA='L1Y' THEN 'Toronto'
                    WHEN FSA='Richmond Hill' THEN 'Toronto'
                    WHEN FSA='L4B' THEN 'Toronto'
                    WHEN FSA='L4C' THEN 'Toronto'
                    WHEN FSA='L4E' THEN 'Toronto'
                    WHEN FSA='L4S' THEN 'Toronto'
                    WHEN FSA='Toronto' THEN 'Toronto'
                    WHEN FSA='M4E' THEN 'Toronto'
                    WHEN FSA='M4J' THEN 'Toronto'
                    WHEN FSA='M4K' THEN 'Toronto'
                    WHEN FSA='M4L' THEN 'Toronto'
                    WHEN FSA='M4M' THEN 'Toronto'
                    WHEN FSA='M4N' THEN 'Toronto'
                    WHEN FSA='M4P' THEN 'Toronto'
                    WHEN FSA='M4R' THEN 'Toronto'
                    WHEN FSA='M4S' THEN 'Toronto'
                    WHEN FSA='M4T' THEN 'Toronto'
                    WHEN FSA='M4V' THEN 'Toronto'
                    WHEN FSA='M4W' THEN 'Toronto'
                    WHEN FSA='M4X' THEN 'Toronto'
                    WHEN FSA='M4Y' THEN 'Toronto'
                    WHEN FSA='M5A' THEN 'Toronto'
                    WHEN FSA='M5B' THEN 'Toronto'
                    WHEN FSA='M5C' THEN 'Toronto'
                    WHEN FSA='M5E' THEN 'Toronto'
                    WHEN FSA='M5G' THEN 'Toronto'
                    WHEN FSA='M5H' THEN 'Toronto'
                    WHEN FSA='M5J' THEN 'Toronto'
                    WHEN FSA='M5K' THEN 'Toronto'
                    WHEN FSA='M5L' THEN 'Toronto'
                    WHEN FSA='M5N' THEN 'Toronto'
                    WHEN FSA='M5P' THEN 'Toronto'
                    WHEN FSA='M5R' THEN 'Toronto'
                    WHEN FSA='M5S' THEN 'Toronto'
                    WHEN FSA='M5T' THEN 'Toronto'
                    WHEN FSA='M5V' THEN 'Toronto'
                    WHEN FSA='M5W' THEN 'Toronto'
                    WHEN FSA='M5X' THEN 'Toronto'
                    WHEN FSA='M6G' THEN 'Toronto'
                    WHEN FSA='M6H' THEN 'Toronto'
                    WHEN FSA='M6J' THEN 'Toronto'
                    WHEN FSA='M6K' THEN 'Toronto'
                    WHEN FSA='M6P' THEN 'Toronto'
                    WHEN FSA='M6R' THEN 'Toronto'
                    WHEN FSA='M6S' THEN 'Toronto'
                    WHEN FSA='M7A' THEN 'Toronto'
                    WHEN FSA='M7Y' THEN 'Toronto'
                    WHEN FSA='Uxbridge' THEN 'Toronto'
                    WHEN FSA='L9P' THEN 'Toronto'
                    WHEN FSA='Vaughan' THEN 'Toronto'
                    WHEN FSA='Whitchurch-Stouffville' THEN 'Toronto'
                    WHEN FSA='L4A' THEN 'Toronto'
                    WHEN FSA='Clarence-Rockland' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K4K' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Ottawa' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1A' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1B' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1C' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1E' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1G' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1H' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1J' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1K' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1L' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1N' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1M' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1P' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1R' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1S' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1T' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1V' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1W' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1X' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1Y' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K1Z' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2A' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2B' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2C' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2E' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2G' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2H' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2J' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2K' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2L' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2M' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2P' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2R' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2S' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2T' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2V' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K2W' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K4A' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K4B' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K4C' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K4M' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K4P' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Russell' THEN 'Ottawa - Gatineau'
                    WHEN FSA='K4R' THEN 'Ottawa - Gatineau'
                    ELSE 'ON - other'
                END
            WHEN province='QC' THEN
                CASE
                    WHEN FSA='Cantley' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Chelsea' THEN 'Ottawa - Gatineau'
                    WHEN FSA='J9B' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Denholm' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Gatineau' THEN 'Ottawa - Gatineau'
                    WHEN FSA='J8P' THEN 'Ottawa - Gatineau'
                    WHEN FSA='J8R' THEN 'Ottawa - Gatineau'
                    WHEN FSA='J8T' THEN 'Ottawa - Gatineau'
                    WHEN FSA='J8V' THEN 'Ottawa - Gatineau'
                    WHEN FSA='La Pêche' THEN 'Ottawa - Gatineau'
                    WHEN FSA='L''Ange-Gardien' THEN 'Ottawa - Gatineau'
                    WHEN FSA='G0A 2K0' THEN 'Ottawa - Gatineau'
                    WHEN FSA='G0A2K0' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Pontiac ' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Val-des-Monts' THEN 'Ottawa - Gatineau'
                    WHEN FSA='J8N' THEN 'Ottawa - Gatineau'
                    WHEN FSA='Beaumont ' THEN 'Quebec'
                    WHEN FSA='G0R 1C0' THEN 'Quebec'
                    WHEN FSA='G0R1C0' THEN 'Quebec'
                    WHEN FSA='Boischatel' THEN 'Quebec'
                    WHEN FSA='G0A 1H0' THEN 'Quebec'
                    WHEN FSA='G0A1H0' THEN 'Quebec'
                    WHEN FSA='Château-Richer' THEN 'Quebec'
                    WHEN FSA='G0A 1N0' THEN 'Quebec'
                    WHEN FSA='G0A1N0' THEN 'Quebec'
                    WHEN FSA='Fossambault-sur-le-Lac' THEN 'Quebec'
                    WHEN FSA='Lac-Beauport' THEN 'Quebec'
                    WHEN FSA='G3B' THEN 'Quebec'
                    WHEN FSA='Lac-Delage' THEN 'Quebec'
                    WHEN FSA='Lac-Saint-Joseph' THEN 'Quebec'
                    WHEN FSA='L''Ancienne-Lorette' THEN 'Quebec'
                    WHEN FSA='G2E' THEN 'Quebec'
                    WHEN FSA='G2G' THEN 'Quebec'
                    WHEN FSA='L''Ange-Gardien' THEN 'Quebec'
                    WHEN FSA='G0A 2K0' THEN 'Quebec'
                    WHEN FSA='G0A2K0' THEN 'Quebec'
                    WHEN FSA='Lévis ' THEN 'Quebec'
                    WHEN FSA='G6V' THEN 'Quebec'
                    WHEN FSA='G6W' THEN 'Quebec'
                    WHEN FSA='Notre-Dame-des-Anges' THEN 'Quebec'
                    WHEN FSA='Québec' THEN 'Quebec'
                    WHEN FSA='G1A' THEN 'Quebec'
                    WHEN FSA='G1G' THEN 'Quebec'
                    WHEN FSA='G1J' THEN 'Quebec'
                    WHEN FSA='G1K' THEN 'Quebec'
                    WHEN FSA='G1L' THEN 'Quebec'
                    WHEN FSA='G1M' THEN 'Quebec'
                    WHEN FSA='G1N' THEN 'Quebec'
                    WHEN FSA='G1P' THEN 'Quebec'
                    WHEN FSA='G1R' THEN 'Quebec'
                    WHEN FSA='G1S' THEN 'Quebec'
                    WHEN FSA='G1T' THEN 'Quebec'
                    WHEN FSA='G2C' THEN 'Quebec'
                    WHEN FSA='G2J' THEN 'Quebec'
                    WHEN FSA='G2K' THEN 'Quebec'
                    WHEN FSA='G2M' THEN 'Quebec'
                    WHEN FSA='G2N' THEN 'Quebec'
                    WHEN FSA='Saint-Augustin-de-Desmaures' THEN 'Quebec'
                    WHEN FSA='G3A' THEN 'Quebec'
                    WHEN FSA='Sainte-Brigitte-de-Laval' THEN 'Quebec'
                    WHEN FSA='G0A 3K0' THEN 'Quebec'
                    WHEN FSA='G0A3K0' THEN 'Quebec'
                    WHEN FSA='Sainte-Catherine-de-la-Jacques-Cartier' THEN 'Quebec'
                    WHEN FSA='G3N' THEN 'Quebec'
                    WHEN FSA='Sainte-Famille' THEN 'Quebec'
                    WHEN FSA='G0A 3P0' THEN 'Quebec'
                    WHEN FSA='G0A3P0' THEN 'Quebec'
                    WHEN FSA='Sainte-Pétronille' THEN 'Quebec'
                    WHEN FSA='G0A 4C0' THEN 'Quebec'
                    WHEN FSA='G0A4C0' THEN 'Quebec'
                    WHEN FSA='Saint-François-de-l''Île-d''Orléans' THEN 'Quebec'
                    WHEN FSA='Saint-François-d''Orléans' THEN 'Quebec'
                    WHEN FSA='G0A 3S0' THEN 'Quebec'
                    WHEN FSA='Saint-Gabriel-de-Valcartier' THEN 'Quebec'
                    WHEN FSA='G0A 4S0' THEN 'Quebec'
                    WHEN FSA='Saint-Henri' THEN 'Quebec'
                    WHEN FSA='Saint-Jean-de-l''Île-d''Orléans' THEN 'Quebec'
                    WHEN FSA='Saint-Jean-d''Orléans' THEN 'Quebec'
                    WHEN FSA='G0A 3W0' THEN 'Quebec'
                    WHEN FSA='Saint-Lambert-de-Lauzon' THEN 'Quebec'
                    WHEN FSA='G0S 2W0' THEN 'Quebec'
                    WHEN FSA='Saint-Laurent-de-l''Île-d''Orléans' THEN 'Quebec'
                    WHEN FSA='Saint-Laurent-de-l''Île-d''Orléans' THEN 'Quebec'
                    WHEN FSA='G0A 3Z0' THEN 'Quebec'
                    WHEN FSA='Saint-Pierre-de-l''Île-d''Orléans' THEN 'Quebec'
                    WHEN FSA='G0A 4E0' THEN 'Quebec'
                    WHEN FSA='Shannon' THEN 'Quebec'
                    WHEN FSA='G0A 4N0' THEN 'Quebec'
                    WHEN FSA='Stoneham-et-Tewkesbury' THEN 'Quebec'
                    WHEN FSA='G3C' THEN 'Quebec'
                    WHEN FSA='Wendake' THEN 'Quebec'
                    WHEN FSA='G0A 4V0' THEN 'Quebec'
                    WHEN FSA='Baie-D''Urfé' THEN 'Montreal'
                    WHEN FSA='Beaconsfield' THEN 'Montreal'
                    WHEN FSA='H9W' THEN 'Quebec'
                    WHEN FSA='Beauharnois' THEN 'Montreal'
                    WHEN FSA='J6N' THEN 'Montreal'
                    WHEN FSA='Beloeil' THEN 'Montreal'
                    WHEN FSA='J3G' THEN 'Montreal'
                    WHEN FSA='J3H' THEN 'Montreal'
                    WHEN FSA='Blainville' THEN 'Montreal'
                    WHEN FSA='Boisbriand' THEN 'Montreal'
                    WHEN FSA='Bois-des-Filion' THEN 'Montreal'
                    WHEN FSA='Boucherville' THEN 'Montreal'
                    WHEN FSA='J4B' THEN 'Montreal'
                    WHEN FSA='Brossard' THEN 'Montreal'
                    WHEN FSA='J4W' THEN 'Montreal'
                    WHEN FSA='J4X' THEN 'Montreal'
                    WHEN FSA='J4Y' THEN 'Montreal'
                    WHEN FSA='J4Z' THEN 'Montreal'
                    WHEN FSA='Candiac' THEN 'Montreal'
                    WHEN FSA='Carignan' THEN 'Montreal'
                    WHEN FSA='Chambly' THEN 'Montreal'
                    WHEN FSA='J3L' THEN 'Montreal'
                    WHEN FSA='Charlemagne' THEN 'Montreal'
                    WHEN FSA='Châteauguay' THEN 'Montreal'
                    WHEN FSA='J6J' THEN 'Montreal'
                    WHEN FSA='J6K' THEN 'Montreal'
                    WHEN FSA='Coteau-du-Lac' THEN 'Montreal'
                    WHEN FSA='J0P 1B0' THEN 'Montreal'
                    WHEN FSA='Côte-Saint-Luc' THEN 'Montreal'
                    WHEN FSA='H3X' THEN 'Montreal'
                    WHEN FSA='H4V' THEN 'Montreal'
                    WHEN FSA='H4W' THEN 'Montreal'
                    WHEN FSA='Delson' THEN 'Montreal'
                    WHEN FSA='J5B' THEN 'Montreal'
                    WHEN FSA='Deux-Montagnes' THEN 'Montreal'
                    WHEN FSA='Dollard-Des Ormeaux' THEN 'Montreal'
                    WHEN FSA='H9A' THEN 'Montreal'
                    WHEN FSA='H9B' THEN 'Montreal'
                    WHEN FSA='H9G' THEN 'Montreal'
                    WHEN FSA='Dorval' THEN 'Montreal'
                    WHEN FSA='H4Y' THEN 'Montreal'
                    WHEN FSA='H9P' THEN 'Montreal'
                    WHEN FSA='H9S' THEN 'Montreal'
                    WHEN FSA='Gore' THEN 'Montreal'
                    WHEN FSA='J0V 1K0' THEN 'Montreal'
                    WHEN FSA='J0V1K0' THEN 'Montreal'
                    WHEN FSA='Hampstead' THEN 'Montreal'
                    WHEN FSA='H3X' THEN 'Montreal'
                    WHEN FSA='Hudson' THEN 'Montreal'
                    WHEN FSA='J0P 1H0' THEN 'Montreal'
                    WHEN FSA='J0P1H0' THEN 'Montreal'
                    WHEN FSA='Kahnawake' THEN 'Montreal'
                    WHEN FSA='J0L 1B0' THEN 'Montreal'
                    WHEN FSA='J0L1B0' THEN 'Montreal'
                    WHEN FSA='Kanesatake' THEN 'Montreal'
                    WHEN FSA='Kirkland' THEN 'Montreal'
                    WHEN FSA='H9J' THEN 'Montreal'
                    WHEN FSA='La Prairie' THEN 'Montreal'
                    WHEN FSA='J5R' THEN 'Montreal'
                    WHEN FSA='L''Assomption' THEN 'Montreal'
                    WHEN FSA='J5W' THEN 'Montreal'
                    WHEN FSA='Laval ' THEN 'Montreal'
                    WHEN FSA='Lavaltrie' THEN 'Montreal'
                    WHEN FSA='J5T' THEN 'Montreal'
                    WHEN FSA='L''Épiphanie' THEN 'Montreal'
                    WHEN FSA='J5X' THEN 'Montreal'
                    WHEN FSA='Léry' THEN 'Montreal'
                    WHEN FSA='Les Cèdres' THEN 'Montreal'
                    WHEN FSA='Les Coteaux' THEN 'Montreal'
                    WHEN FSA='L''Île-Cadieux' THEN 'Montreal'
                    WHEN FSA='Dorval' THEN 'Montreal'
                    WHEN FSA='L''Île-Dorval' THEN 'Montreal'
                    WHEN FSA='H9S' THEN 'Montreal'
                    WHEN FSA='L''Île-Perrot' THEN 'Montreal'
                    WHEN FSA='Longueuil' THEN 'Montreal'
                    WHEN FSA='J4G' THEN 'Montreal'
                    WHEN FSA='J4H' THEN 'Montreal'
                    WHEN FSA='J4J' THEN 'Montreal'
                    WHEN FSA='J4K' THEN 'Montreal'
                    WHEN FSA='J4L' THEN 'Montreal'
                    WHEN FSA='J4M' THEN 'Montreal'
                    WHEN FSA='J4N' THEN 'Montreal'
                    WHEN FSA='Lorraine' THEN 'Montreal'
                    WHEN FSA='Mascouche' THEN 'Montreal'
                    WHEN FSA='J7K' THEN 'Montreal'
                    WHEN FSA='J7L' THEN 'Montreal'
                    WHEN FSA='McMasterville' THEN 'Montreal'
                    WHEN FSA='Mercier' THEN 'Montreal'
                    WHEN FSA='H1L' THEN 'Montreal'
                    WHEN FSA='H1M' THEN 'Montreal'
                    WHEN FSA='H1N' THEN 'Montreal'
                    WHEN FSA='Mirabel' THEN 'Montreal'
                    WHEN FSA='J7J' THEN 'Montreal'
                    WHEN FSA='J7N' THEN 'Montreal'
                    WHEN FSA='Montréal' THEN 'Montreal'
                    WHEN FSA='Montréal-Est' THEN 'Montreal'
                    WHEN FSA='Montréal-Ouest' THEN 'Montreal'
                    WHEN FSA='H1B' THEN 'Montreal'
                    WHEN FSA='H1H' THEN 'Montreal'
                    WHEN FSA='H2Y' THEN 'Montreal'
                    WHEN FSA='H2Z' THEN 'Montreal'
                    WHEN FSA='H3A' THEN 'Montreal'
                    WHEN FSA='H3B' THEN 'Montreal'
                    WHEN FSA='H3G' THEN 'Montreal'
                    WHEN FSA='H3H' THEN 'Montreal'
                    WHEN FSA='H4X' THEN 'Montreal'
                    WHEN FSA='Mont-Royald' THEN 'Montreal'
                    WHEN FSA='Mont-Saint-Hilaire' THEN 'Montreal'
                    WHEN FSA='Notre-Dame-de-l''Île-Perrot' THEN 'Montreal'
                    WHEN FSA='Oka' THEN 'Montreal'
                    WHEN FSA='J0N 1E0' THEN 'Montreal'
                    WHEN FSA='J0N1E0' THEN 'Montreal'
                    WHEN FSA='Otterburn Park' THEN 'Montreal'
                    WHEN FSA='Pincourt' THEN 'Montreal'
                    WHEN FSA='J7W' THEN 'Montreal'
                    WHEN FSA='Pointe-Calumet' THEN 'Montreal'
                    WHEN FSA='J0N 1G0' THEN 'Montreal'
                    WHEN FSA='J0N1G0' THEN 'Montreal'
                    WHEN FSA='Pointe-Claire' THEN 'Montreal'
                    WHEN FSA='H9R' THEN 'Montreal'
                    WHEN FSA='Pointe-des-Cascades' THEN 'Montreal'
                    WHEN FSA='J0P 1M0' THEN 'Montreal'
                    WHEN FSA='J0P1M0' THEN 'Montreal'
                    WHEN FSA='Repentigny' THEN 'Montreal'
                    WHEN FSA='J6A' THEN 'Montreal'
                    WHEN FSA='H5Y' THEN 'Montreal'
                    WHEN FSA='H5Z' THEN 'Montreal'
                    WHEN FSA=' Richelieu' THEN 'Montreal'
                    WHEN FSA='Rosemère' THEN 'Montreal'
                    WHEN FSA='Saint-Amable' THEN 'Montreal'
                    WHEN FSA='J0L 1N0' THEN 'Montreal'
                    WHEN FSA='J0L1N0' THEN 'Montreal'
                    WHEN FSA='Saint-Basile-le-Grand' THEN 'Montreal'
                    WHEN FSA='J3N' THEN 'Montreal'
                    WHEN FSA='Saint-Bruno-de-Montarville' THEN 'Montreal'
                    WHEN FSA='J3V' THEN 'Montreal'
                    WHEN FSA='Saint-Colomban' THEN 'Montreal'
                    WHEN FSA='J5K' THEN 'Montreal'
                    WHEN FSA='Saint-Constant' THEN 'Montreal'
                    WHEN FSA='J5A' THEN 'Montreal'
                    WHEN FSA='Sainte-Anne-de-Bellevue' THEN 'Montreal'
                    WHEN FSA='H9X' THEN 'Montreal'
                    WHEN FSA='Sainte-Anne-des-Plaines' THEN 'Montreal'
                    WHEN FSA='J0N 1H0' THEN 'Montreal'
                    WHEN FSA='J0N1H0' THEN 'Montreal'
                    WHEN FSA='Sainte-Catherine ' THEN 'Montreal'
                    WHEN FSA='J5C' THEN 'Montreal'
                    WHEN FSA='Sainte-Julie ' THEN 'Montreal'
                    WHEN FSA='J3E' THEN 'Montreal'
                    WHEN FSA='Sainte-Marthe-sur-le-Lac' THEN 'Montreal'
                    WHEN FSA='J0N 1P0' THEN 'Montreal'
                    WHEN FSA='J0N1P0' THEN 'Montreal'
                    WHEN FSA='Saint-Eustache' THEN 'Montreal'
                    WHEN FSA='J7P' THEN 'Montreal'
                    WHEN FSA='J7R' THEN 'Montreal'
                    WHEN FSA='Saint-Isidore ' THEN 'Montreal'
                    WHEN FSA='G0S 2S0' THEN 'Montreal'
                    WHEN FSA='G0S2S0' THEN 'Montreal'
                    WHEN FSA='Saint-Jérôme' THEN 'Montreal'
                    WHEN FSA='J5L' THEN 'Montreal'
                    WHEN FSA='J7Y' THEN 'Montreal'
                    WHEN FSA='J7Z' THEN 'Montreal'
                    WHEN FSA='Saint-Joseph-du-Lac' THEN 'Montreal'
                    WHEN FSA='J0N 1M0' THEN 'Montreal'
                    WHEN FSA='Saint-Lambert' THEN 'Montreal'
                    WHEN FSA='J4P' THEN 'Montreal'
                    WHEN FSA='J4R' THEN 'Montreal'
                    WHEN FSA='J4S' THEN 'Montreal'
                    WHEN FSA='Saint-Lazare ' THEN 'Montreal'
                    WHEN FSA='Saint-Mathias-sur-Richelieu' THEN 'Montreal'
                    WHEN FSA='Saint-Mathieu-de-Beloeil' THEN 'Montreal'
                    WHEN FSA='Saint-Philippe' THEN 'Montreal'
                    WHEN FSA='J0L 2K0' THEN 'Montreal'
                    WHEN FSA='J0L2K0' THEN 'Montreal'
                    WHEN FSA='Saint-Placide' THEN 'Montreal'
                    WHEN FSA='J0V 2B0' THEN 'Montreal'
                    WHEN FSA='J0V2B0' THEN 'Montreal'
                    WHEN FSA='Saint-Sulpice' THEN 'Montreal'
                    WHEN FSA='Saint-Zotique' THEN 'Montreal'
                    WHEN FSA='J0P 1Z0' THEN 'Montreal'
                    WHEN FSA='J0P1Z0' THEN 'Montreal'
                    WHEN FSA='Senneville' THEN 'Montreal'
                    WHEN FSA='H9K' THEN 'Montreal'
                    WHEN FSA='Terrasse-Vaudreuil' THEN 'Montreal'
                    WHEN FSA='Terrebonne' THEN 'Montreal'
                    WHEN FSA='H6V' THEN 'Montreal'
                    WHEN FSA='H6W' THEN 'Montreal'
                    WHEN FSA='H6X' THEN 'Montreal'
                    WHEN FSA='H6Y' THEN 'Montreal'
                    WHEN FSA='Varennes' THEN 'Montreal'
                    WHEN FSA='J3X' THEN 'Montreal'
                    WHEN FSA='Vaudreuil-Dorion' THEN 'Montreal'
                    WHEN FSA='J7T' THEN 'Montreal'
                    WHEN FSA='J7V' THEN 'Montreal'
                    WHEN FSA='Vaudreuil-sur-le-Lac' THEN 'Montreal'
                    WHEN FSA='Verchères' THEN 'Montreal'
                    WHEN FSA='J0L 2R0' THEN 'Montreal'
                    WHEN FSA='J0L2R0' THEN 'Montreal'
                    WHEN FSA='Westmount' THEN 'Montreal'
                    WHEN FSA='H3Y' THEN 'Montreal'
                    WHEN FSA='H3Z' THEN 'Montreal'
                    ELSE 'QC - other'
                END
            WHEN province IN ('NL','PE','NB','SK','NT','YT','NU') THEN 'Other'
        END AS prov_city
    FROM province
)
, teranet_region AS (
    SELECT 
        *,
        CASE prov_city
            WHEN 'Calgary' THEN 'Calgary_t'
            WHEN 'Edmonton' THEN 'Edmonton_t'
            WHEN 'Halifax' THEN 'Halifax_t'
            WHEN 'Hamilton' THEN 'Hamilton_t'
            WHEN 'Montreal' THEN 'Montreal_t'
            WHEN 'Ottawa - Gatineau' THEN 'Ottawa_t'
            WHEN 'Quebec' THEN 'Quebec_t'
            WHEN 'Toronto' THEN 'Toronto_t'
            WHEN 'Vancouver' THEN 'Vancouver_t'
            WHEN 'Victoria' THEN 'Victoria_t'
            WHEN 'Winnipeg' THEN 'Winnipeg_t'
            WHEN 'AB - other' THEN 'AB'
            WHEN 'BC - other' THEN 'BC'
            WHEN 'ON - other' THEN 'ON'
            WHEN 'NS - other' THEN 'NS'
            WHEN 'QC - other' THEN 'QC'
            WHEN 'MB - other' THEN 'MB'
            ELSE 'Composite_11'
        END AS teranet_region
    FROM prov_city
)
, Appraisal_HPI AS (
    SELECT 
        a.*,
        b1.INDEX AS monthly_HPI,
        b2.INDEX AS Appraisal_HPI,
        CASE
            WHEN COALESCE(b2.INDEX, 0)=0 THEN
                CASE a.teranet_region
                    WHEN 'Victoria_t' THEN 45.97
                    WHEN 'Vancouver_t' THEN 55.36
                    WHEN 'Calgary_t' THEN 69.4
                    WHEN 'Edmonton_t' THEN 61.92
                    WHEN 'Winnipeg_t' THEN 62.65
                    WHEN 'Hamilton_t' THEN 68.02
                    WHEN 'Toronto_t' THEN 68.38
                    WHEN 'Ottawa_t' THEN 62.68
                    WHEN 'Montreal_t' THEN 59.13
                    WHEN 'Quebec_t' THEN 61.71
                    WHEN 'Halifax_t' THEN 57.04
                    WHEN 'AB' THEN 69.4
                    WHEN 'BC' THEN 54.01953857
                    WHEN 'ON' THEN 66.51151899
                    WHEN 'NS' THEN 57.04
                    WHEN 'QC' THEN 59.43752158
                    WHEN 'MB' THEN 62.65
                    WHEN 'Composite_11' THEN 65.63
                END
            ELSE b2.INDEX
        END AS Appraisal_HPI_2
    FROM teranet_region a
    LEFT OUTER JOIN housing_index b1 ON
        a.month_end_dt = b1.month_end_dt
        AND UPPER(a.teranet_region) = UPPER(b1.region)
    LEFT OUTER JOIN housing_index b2 ON
        a.prop_val_date = b2.month_end_dt
        AND UPPER(a.teranet_region) = UPPER(b2.region)
)
, LTV_teranet AS (
    SELECT 
        *,
        prop_val*(monthly_HPI/Appraisal_HPI_2) AS prop_val_new,
        end_principal_balance/(prop_val*(monthly_HPI/Appraisal_HPI_2)) AS LTV_teranet
    FROM Appraisal_HPI
)
select * from LTV_teranet
    """,
):
    pass


def duckdb_delete(
    duckdb_conn_id="duckdb-conn",
    sql=f"""
    delete from { DOWNSTREAM_ASSET } where obsn_dt = '{{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="rundate") }}}}'
    """,
):
    pass


def duckdb_load(
    duckdb_conn_id="duckdb-conn",
    sql=f"""
    INSERT INTO { DOWNSTREAM_ASSET } by name
    FROM (
        select
            a.month_end_dt as obsn_dt,
            b.basel_acct_id,
            trim(a.account_id) as account_id,
            a.LTV_teranet
        from read_parquet('{{{{ task_instance.xcom_pull(task_ids="derived__ltv_teranet.export_ltv", key="parquet") }}}}') a
        inner join { UPSTREAM_ASSET[0] } b on
            b.src_app_cd ='TNG-MOR'
            and b.src_sys_del_f != 'Y'
            and trim(a.account_id) = trim(b.src_app_id)
    )
    """,
):
    pass


