import pyarrow as pa
from airflow.sdk import get_current_context

from bns.rrap.helpers.asset_event import (
    _pull_asset_event_extras,
    _push_asset_event_extras,
)

UPSTREAM_ASSET = [ 'ingestion.MORT_MTH_SNAPSHOT', 'features.MAX_LEND_VALUE', 'features.STEP_TOTAL_BAL',  
                    'ingestion.TERANET_HOUSE_PRC_INDEX_CMA', 'ingestion.TM_DIM']

DOWNSTREAM_ASSET = 'features.STEP_INDEXED_CLTV_METRO_METHOD2'
DEPENDENCIES = {
    'duckdb_clear_step_indexed_cltv_metro_method2': ['duckdb_derive_step_indexed_cltv_metro_method2'],
}


def duckdb_clear_step_indexed_cltv_metro_method2(
    duckdb_conn_id='duckdb-conn',
    sql=rf"""
        DELETE FROM { DOWNSTREAM_ASSET } 
        WHERE OBSN_DT = '{{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="rundate") }}}}'
    """
):
    pass


def duckdb_derive_step_indexed_cltv_metro_method2(
    duckdb_conn_id='duckdb-conn',
    sql=f"""
    INSERT INTO { DOWNSTREAM_ASSET }
    BY NAME FROM (
    WITH CURR_ACCOUNTS AS (
	SELECT DISTINCT
		STEP_PLN_AGRMNT_NUM
	FROM
		{UPSTREAM_ASSET[0]}
	WHERE
		MTH_TM_ID = {{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="mth_tm_id") }}}}
	AND
		(UPPER(TRIM(COMM_TP))='RESIDENTIAL' OR TRIM(COMM_TP)='')
	AND
		CRNT_BAL_AMT>0
	AND
		TRIM(PD_OFF_F)='N'
	AND
		(STEP_PLN_AGRMNT_NUM NOT NULL AND TRIM(STEP_PLN_AGRMNT_NUM) != '')
	AND 
		MORT_AUTH_DT NOT NULL
	),

MORT_DATA AS (
	SELECT
		B.MTH_TM_ID,
		A.STEP_PLN_AGRMNT_NUM,
		A.MORT_AUTH_DT,
		A.MAX_LEND_VALUE,
		B.PROPERTY_ADDR_3
	FROM 
		{UPSTREAM_ASSET[1]} A
	INNER JOIN
		{UPSTREAM_ASSET[0]} B
	ON
		A.STEP_PLN_AGRMNT_NUM = B.STEP_PLN_AGRMNT_NUM
	AND
		A.MORT_AUTH_DT = B.MORT_AUTH_DT
    AND
		A.MORT_NUM = B.MORT_NUM
	INNER JOIN
		CURR_ACCOUNTS C
	ON
		B.STEP_PLN_AGRMNT_NUM = C.STEP_PLN_AGRMNT_NUM
    AND
		A.STEP_PLN_AGRMNT_NUM = C.STEP_PLN_AGRMNT_NUM
	WHERE
		B.STEP_PLN_AGRMNT_NUM NOT NULL AND TRIM(B.STEP_PLN_AGRMNT_NUM) != ''
	AND
		B.MORT_AUTH_DT NOT NULL
	AND 
		B.PROPERTY_ADDR_3 NOT NULL AND TRIM(B.PROPERTY_ADDR_3) != ''
	AND
		B.MTH_TM_ID = {{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="mth_tm_id") }}}}
    AND
		A.OBSN_DT = '{{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="rundate") }}}}'
	),
	
STANDARDIZED_PROPERTY_ADDR AS(	
	SELECT
		A.MTH_TM_ID,
		A.STEP_PLN_AGRMNT_NUM,
		A.MORT_AUTH_DT,
		A.MAX_LEND_VALUE,
		(CASE WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%OTTAWA%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%GATINEAU%' THEN 'OTTAWA_GATINEAU'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%SUDBURY%' THEN 'Greater Sudbury / Grand Sudbury'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%KITCHENER%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%CAMBRIDGE%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%WATERLOO%'
		THEN 'Kitchener - Cambridge - Waterloo'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%VANCOUVER%' THEN 'Vancouver'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%VICTORIA%' THEN 'Victoria'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%HALIFAX%' THEN 'Halifax'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%KINGSTON%' THEN 'Kingston'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%HAMILTON%' THEN 'Hamilton'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%OSHAWA%' THEN 'Oshawa'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%BRANTFORD%' THEN 'Brantford'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%GUELPH%' THEN 'Guelph'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%BELLEVILLE%' THEN 'Belleville'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%WINNIPEG%' THEN 'Winnipeg'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%MONCTON%' THEN 'Moncton'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%SAINT JOHN%' THEN 'Saint John'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%BARRIE%' THEN 'Barrie'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%LONDON%' THEN 'London'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%ST JOHNS%' THEN 'St. Johns'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%TROIS-RIVIERES%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%RIVIERES%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%TROIS%' THEN 'Trois-Rivieres'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%SHERBROOKE%' THEN 'Sherbrooke'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%CALGARY%' THEN 'Calgary'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%QUEBEC%' THEN 'Quebec'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%EDMONTON%' THEN 'Edmonton'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%KELOWNA%' THEN 'Kelowna'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%WINDSOR%' THEN 'Windsor'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%LETHBRIDGE%' THEN 'Lethbridge'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%MONTREAL%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%Montréal%' THEN 'Montreal'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%PETERBOROUGH%' THEN 'Peterborough'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%ABBOTSFORD%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%ABBOTSFORD-MISSION%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%MISSION%' THEN 'Abbotsford - Mission'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%THUNDER BAY%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%THUNDER-BAY%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%THUNDER%' THEN 'Thunder Bay'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%ST CATHARINES%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%NIAGARA%' OR UPPER(A.PROPERTY_ADDR_3) LIKE '%ST CATHARINES-NIAGARA%' THEN 'St. Catharines - Niagara'
		WHEN UPPER(A.PROPERTY_ADDR_3) LIKE '%TORONTO%' THEN 'Toronto'
		ELSE '11'
		END) AS PROPERTY_ADDR_3
	FROM 
		MORT_DATA A
),

STANDARDIZED_STEP_DATA AS(
SELECT 
	STEP_PLN_AGRMNT_NUM,
	MORT_AUTH_DT,
	MAX_LEND_VALUE,
	PROPERTY_ADDR_3
FROM (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY STEP_PLN_AGRMNT_NUM ORDER BY MTH_TM_ID DESC) AS ROW_NUM
    FROM STANDARDIZED_PROPERTY_ADDR AS t
) A
WHERE ROW_NUM = 1),			

STEP_TOTAL_BALANCE AS (
	SELECT
		A.STEP_PLN_AGRMNT_NUM,
		A.STEP_TOTAL_BAL AS STEP_TOTAL_BALANCE
	FROM 
		{UPSTREAM_ASSET[2]} A
	INNER JOIN
		CURR_ACCOUNTS B
	ON
		A.STEP_PLN_AGRMNT_NUM = B.STEP_PLN_AGRMNT_NUM
	WHERE
		A.OBSN_DT = '{{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="rundate") }}}}'
),

INDEX_AT_OBSN AS (
	SELECT 
		A.INDEX AS INDEX_AT_OBSN,
		B.STEP_PLN_AGRMNT_NUM,
	FROM 
		(
		SELECT DISTINCT 
			MTH_TM_ID,
			LABEL_2,
			INDEX
		FROM
			{UPSTREAM_ASSET[3]}
		) A
	INNER JOIN 
		STANDARDIZED_STEP_DATA B
	ON
		A.LABEL_2 = B.PROPERTY_ADDR_3
	WHERE 
		A.MTH_TM_ID = {{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="mth_tm_id") }}}}
),

INDEX_AT_ORIGIN AS (
	SELECT 
		A.STEP_PLN_AGRMNT_NUM,
		C.INDEX AS INDEX_AT_ORIGIN
	FROM 
		STANDARDIZED_STEP_DATA A
	INNER JOIN 
		{UPSTREAM_ASSET[4]} B
	ON
		SUBSTRING(B.TM_LVL_END_DT::VARCHAR, 1, 7) LIKE SUBSTRING(A.MORT_AUTH_DT::VARCHAR, 1, 7)
	INNER JOIN
		(
			SELECT DISTINCT 
				MTH_TM_ID,
				LABEL_2,
				INDEX
			FROM
				{UPSTREAM_ASSET[3]}
		)C
	ON
		TRIM(UPPER(A.PROPERTY_ADDR_3)) = TRIM(UPPER(C.LABEL_2))
	AND
		B.TM_ID = C.MTH_TM_ID
	WHERE
		B.TM_LVL = 'Month'
),

LEND_VALUE_AT_OBSN AS (
	SELECT
		A.STEP_PLN_AGRMNT_NUM,
		A.MORT_AUTH_DT,
		A.PROPERTY_ADDR_3,
		A.MAX_LEND_VALUE,
		A.MAX_LEND_VALUE * (B.INDEX_AT_OBSN/C.INDEX_AT_ORIGIN) AS LEND_VALUE_AT_OBSN
	FROM 
		STANDARDIZED_STEP_DATA A
	INNER JOIN 
		INDEX_AT_OBSN B
	ON
		A.STEP_PLN_AGRMNT_NUM = B.STEP_PLN_AGRMNT_NUM
	INNER JOIN
		INDEX_AT_ORIGIN C
	ON 
		A.STEP_PLN_AGRMNT_NUM = C.STEP_PLN_AGRMNT_NUM
)

    SELECT 
        '{{{{ task_instance.xcom_pull(task_ids="handle_month_context", key="rundate") }}}}' AS OBSN_DT,
        A.STEP_PLN_AGRMNT_NUM,
        CASE 
            WHEN A.LEND_VALUE_AT_OBSN IS NULL OR A.LEND_VALUE_AT_OBSN = 0 THEN NULL
            ELSE B.STEP_TOTAL_BALANCE / A.LEND_VALUE_AT_OBSN
        END AS STEP_INDEXED_CLTV_METRO_METHOD2
    FROM 
        LEND_VALUE_AT_OBSN A
    INNER JOIN
        STEP_TOTAL_BALANCE B
    ON
        A.STEP_PLN_AGRMNT_NUM = B.STEP_PLN_AGRMNT_NUM
    )
    """
):
    pass

