CREATE TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_RPTG_EXTR_CACAP(
	RPTG_TP VARCHAR(50) NOT NULL,
	RPTG_DT_TEXT VARCHAR(10) NOT NULL,
	UNQ_RECD_ID VARCHAR(50) NOT NULL,
	BASEL_PRD_TP_NM VARCHAR(50) NOT NULL,
	PD_BAND_TEXT VARCHAR(10),
	LEGAL_ENTITY VARCHAR(40),
	PD_90_DAY_F VARCHAR(5),
	UNCONDTNLY_CNCLBL VARCHAR(5),
	EXPSR_AMT_TEXT VARCHAR(18),
	EAD_PC VARCHAR(15),
	CRNCY_CD VARCHAR(3),
	EXPCTD_LOSS_RTO_TEXT VARCHAR(15),
	UNDRAWN_AMT_TEXT VARCHAR(18),
	ACCR_INTR_AMT_TEXT VARCHAR(18),
	PRTL_WRITE_OFF_AMT_TEXT VARCHAR(18),
	LGD_RTO_TEXT VARCHAR(15),
	EAD_RTO_TEXT VARCHAR(15),
	INSUR_F VARCHAR(5),
	DLGD_RTO_TEXT VARCHAR(15),
	LTV_PERCENTAGE VARCHAR(4));

CREATE TABLE EDRTLRP1D.BASEL_CCAR_PD_RPTG_EXTR_CACAP(
	RPTG_DT_TEXT VARCHAR(10) NOT NULL,
	PRD_TP_NM VARCHAR(50) NOT NULL,
	PD_BAND INTEGER,
	PD_VAL_TEXT VARCHAR(15),
	PD_MIN_RTO DECIMAL(15,8),
	PD_MAX_RTO DECIMAL(15,8));