CREATE TABLE IF NOT EXISTS ingestion.ACCT_XREF (
    ACCT_ID VARCHAR,
    ACCT_TYP VARCHAR,
    ACCT_BASE_KEY BIGINT,
    FROM_EDW_F  VARCHAR,
    POPN_DT DATE
);
ALTER TABLE ingestion.ACCT_XREF SET PARTITIONED BY (POPN_DT);
