CREATE TABLE
  IF NOT EXISTS ingestion.AIRB_RECON_APRVD_SNAPSHOT (
    MTH_END_DT DATE NOT NULL,
    GL_ACCT_NUM VARCHAR NOT NULL,
    GL_TRNST_NUM VARCHAR NOT NULL,
    SRC_SYS_CD VARCHAR NOT NULL,
    CRNCY_CD VARCHAR NOT NULL,
    BATCH_ID BIGINT NOT NULL,
    APRVL_USR_ID VARCHAR NOT NULL,
    APRVL_TMSTMP TIMESTAMP NOT NULL,
    AIRB_ADJ_COA_AMT DECIMAL(22,3) NOT NULL,
  )
;

ALTER TABLE ingestion.AIRB_RECON_APRVD_SNAPSHOT
SET
  PARTITIONED BY (MTH_END_DT)
;