CREATE TABLE IF NOT EXISTS ingestion.BASEL_PSNL_LN_SUBV_MST_SNAPSHT_NEW (
    BASEL_ACCT_ID BIGINT,
    MTH_TM_ID INTEGER,
    MTH_END_DT DATE,
    ACCT_NUM VARCHAR,
    ORIG_CAB_TRANSIT VARCHAR,
    LOAN_NUM VARCHAR,
    APPLICATION_NUM VARCHAR,
    SUBVENTION_IND VARCHAR,
    REGION VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);
ALTER TABLE ingestion.BASEL_PSNL_LN_SUBV_MST_SNAPSHT_NEW SET PARTITIONED BY (MTH_TM_ID);
