/**

IIAS Schema:

Column Name	            Schema	Type
BASEL_CUST_ID           BIGINT
CIF_KEY                 CHARACTER
CUST_CID                CHARACTER
CUST_TP_CD              CHARACTER
IP_ID                   BIGINT
CIS_PURGED_F            CHARACTER
CIS_PURGED_DT	        DATE
INSRT_PROCESS_TMSTMP	TIMESTAMP
UPDT_PROCESS_TMSTMP	    TIMESTAMP

 **/
CREATE TABLE
    IF NOT EXISTS ingestion.BASEL_CUST_DIM (
        BASEL_CUST_ID BIGINT NOT NULL,
        CIF_KEY VARCHAR,
        CUST_CID VARCHAR,
        CUST_TP_CD VARCHAR,
        IP_ID BIGINT,
        CIS_PURGED_F VARCHAR,
        CIS_PURGED_DT DATE,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;