CREATE TABLE IF NOT EXISTS ingestion.BASEL_KS_ACCT_TRANSACTOR_ROLE (
    MTH_TM_ID DECIMAL(11,0),
    BASEL_ACCT_ID DECIMAL(20,0),
    ROLE_IND VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);
ALTER TABLE ingestion.BASEL_KS_ACCT_TRANSACTOR_ROLE SET PARTITIONED BY (MTH_TM_ID);