CREATE TABLE
    IF NOT EXISTS INGESTION.BASEL_CUST_ACCT_RLTNP_SNAPSHOT (
        BASEL_CUST_ID BIGINT NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        MTH_TM_ID INTEGER NOT NULL,
        PRIM_CUST_F VARCHAR,
        REL_CD VARCHAR,
        INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;

ALTER TABLE INGESTION.BASEL_CUST_ACCT_RLTNP_SNAPSHOT
SET
    PARTITIONED BY (MTH_TM_ID)
;