CREATE TABLE
        IF NOT EXISTS ingestion.BASEL_MORT_MTH_SNAPSHOT (
                BASEL_MORT_MTH_SNAPSHOT_ID BIGINT NOT NULL,
                MTH_TM_ID INTEGER NOT NULL,
                STEP_PLN_SNAPSHOT_ID BIGINT NOT NULL,
                PRIM_BASEL_CUST_ID BIGINT NOT NULL,
                BASEL_ACCT_ID BIGINT NOT NULL,
                FLOAT_CD VARCHAR,
                MORT_NUM VARCHAR,
                PD_OFF_F VARCHAR,
                FRCLSR_F VARCHAR,
                MTH_IN_ARRS_CNT DECIMAL(5, 0),
                INSUR_CL_CD VARCHAR,
                PRPTY_CD VARCHAR,
                FUND_CD VARCHAR,
                INTR_ADJ_DT DATE,
                CRNT_BAL_AMT DECIMAL(17, 3),
                SERV_BR_TRNST_NUM VARCHAR,
                SERV_BR_OU_ID BIGINT NOT NULL,
                PROC_BR_TRNST_NUM VARCHAR,
                PROC_BR_OU_ID BIGINT NOT NULL,
                MORT_AUTH_DT DATE,
                PD_OFF_DT DATE,
                CRNT_TERM_MAT_DT DATE,
                LAST_RNEW_DT DATE,
                AUTH_AMT DECIMAL(17, 3),
                INTR_DUE_AMT DECIMAL(17, 3),
                LND_VAL INTEGER,
                TAX_CRNT_BAL_AMT DECIMAL(17, 3),
                INTR_ACCR_AMT DECIMAL(17, 3),
                TOT_ADVNC_AMT DECIMAL(17, 3),
                BRWER_CD VARCHAR,
                APRSD_LAST_BUILDING_VAL INTEGER,
                APRSD_LAND_VAL INTEGER,
                APRSD_LAST_LAND_VAL INTEGER,
                APRSD_BUILDING_VAL INTEGER,
                APRSD_ORIG_LAND_VAL INTEGER,
                APRSD_ORIG_BUILDING_VAL INTEGER,
                FINAL_ADVNC_DT DATE,
                LIFE_INSUR_CD VARCHAR,
                WK_FRST_UNPAID_DT DATE,
                BUS_SRC_CD VARCHAR,
                SCRTY_TP_2 VARCHAR,
                FRST_UNPAID_DT DATE,
                MONTREAL_TRUST_DSBLTY_STAT_CD VARCHAR,
                SALE_DT_VAL INTEGER,
                MRKTING_1_CD VARCHAR,
                MRKTING_2_CD VARCHAR,
                MRKTING_3_CD VARCHAR,
                MRKTING_4_CD VARCHAR,
                MRKTING_5_CD VARCHAR,
                CRI_CD VARCHAR,
                ARI_CD VARCHAR,
                PVSN_AMT DECIMAL(17, 3),
                SCOTIA_TOT_EQTY_PLN_F VARCHAR,
                LOAN_AUTH_DT DATE,
                HLTH_CRSIS_PRTCTN_INSUR_STAT_CD VARCHAR,
                TOT_SUSP_BAL_AMT DECIMAL(17, 3),
                ACCT_TP_CD VARCHAR,
                PRPTY_PROV_CD VARCHAR,
                RENEWED_DT DATE,
                MORT_TERM_MTH DECIMAL(4, 0),
                MAX_INTR_RT DECIMAL(10, 4),
                YR_5_MTH_6_F VARCHAR,
                PRIM_CUST_CID VARCHAR,
                STEP_PLN_AGRMNT_NUM VARCHAR,
                INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
                UPDT_PROCESS_TMSTMP TIMESTAMP,
                YTD_PRPY_AMT DECIMAL(17, 3),
                AMORT_MTH SMALLINT NOT NULL,
                PRPTY_ADDR VARCHAR,
                GL_ACCT_NUM VARCHAR,
                GL_TRNST_NUM VARCHAR,
                PRD_GRP_CD VARCHAR,
                UNIT_CNT SMALLINT,
                COMM_TP VARCHAR,
        )
;

ALTER TABLE ingestion.BASEL_MORT_MTH_SNAPSHOT
SET
        PARTITIONED BY (MTH_TM_ID)
;