/**

STEP_PLN_SNAPSHOT_ID	BIGINT
MTH_TM_ID	INTEGER
PRIM_BASEL_CUST_ID	BIGINT
STEP_PLN_AGRMNT_NUM	CHARACTER
BR_LOCTN_TRNST	CHARACTER
BR_LOCTN_OU_ID	BIGINT
ST_DT	DATE
ACTY_DT	DATE
PRPTY_DESC_1	CHARACTER
PRPTY_DESC_2	CHARACTER
PRPTY_DESC_3	CHARACTER
PRPTY_PROV_CD	CHARACTER
APRSD_VAL	DECIMAL
APRSD_DT	DATE
RGSTRD_AMT	DECIMAL
RGSTRD_DT	DATE
RGSTRD_NUM	CHARACTER
CR_LMT_AMT	DECIMAL
CR_LMT_DT	DATE
CR_APP_NUM	CHARACTER
DISCHARGE_RSN_CD	CHARACTER
ACCT_CNT	DECIMAL
CRFC_NUM	CHARACTER
INSURER_CD	CHARACTER
HR_ST_DT	DATE
REV_PRD	DECIMAL
HR_END_DT	DATE
PREM_AMT	DECIMAL
APP_FEE	DECIMAL
AUTH_DT	DATE
PRIM_CUST_CID	CHARACTER
AUTO_LMT_F	CHARACTER
ALI_DT	DATE
ALI_PRD_CD	CHARACTER
ALI_ACCT_NUM	DECIMAL
CTI_F	CHARACTER
CTI_DT	DATE
ALI_PNDG_AMT	DECIMAL
INSRT_PROCESS_TMSTMP	TIMESTAMP
UPDT_PROCESS_TMSTMP	TIMESTAMP


 **/
CREATE TABLE
    IF NOT EXISTS INGESTION.BASEL_STEP_PLN_MTH_SNAPSHOT (
        STEP_PLN_SNAPSHOT_ID BIGINT NOT NULL,
        MTH_TM_ID INTEGER NOT NULL,
        PRIM_BASEL_CUST_ID BIGINT NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        BR_LOCTN_TRNST VARCHAR,
        BR_LOCTN_OU_ID BIGINT NOT NULL,
        ST_DT DATE,
        ACTY_DT DATE,
        PRPTY_DESC_1 VARCHAR,
        PRPTY_DESC_2 VARCHAR,
        PRPTY_DESC_3 VARCHAR,
        PRPTY_PROV_CD VARCHAR,
        APRSD_VAL DECIMAL(17, 3),
        APRSD_DT DATE,
        RGSTRD_AMT DECIMAL(17, 3),
        RGSTRD_DT DATE,
        RGSTRD_NUM VARCHAR,
        CR_LMT_AMT DECIMAL(17, 3),
        CR_LMT_DT DATE,
        CR_APP_NUM VARCHAR,
        DISCHARGE_RSN_CD VARCHAR,
        ACCT_CNT DECIMAL(2, 0),
        CRFC_NUM VARCHAR,
        INSURER_CD VARCHAR,
        HR_ST_DT DATE,
        REV_PRD DECIMAL(2, 0),
        HR_END_DT DATE,
        PREM_AMT DECIMAL(17, 3),
        APP_FEE DECIMAL(17, 3),
        AUTH_DT DATE,
        PRIM_CUST_CID VARCHAR,
        AUTO_LMT_F VARCHAR,
        ALI_DT DATE,
        ALI_PRD_CD VARCHAR,
        ALI_ACCT_NUM DECIMAL(18, 0),
        CTI_F VARCHAR,
        CTI_DT DATE,
        ALI_PNDG_AMT DECIMAL(17, 3),
        INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;

ALTER TABLE INGESTION.BASEL_STEP_PLN_MTH_SNAPSHOT
SET
    PARTITIONED BY (MTH_TM_ID)
;