/**

ColumnName                      	Type
REVLVNG_CR_BASEL_MTH_SNAPSHOT_ID	BIGINT
MTH_TM_ID                       	INTEGER
BASEL_ACCT_ID                   	BIGINT
PRIM_BASEL_CUST_ID              	BIGINT
STEP_PLN_SNAPSHOT_ID            	BIGINT
ACCT_NUM                        	CHARACTER
TRNST_OU_ID                     	BIGINT
SUB_PRD_CD                      	CHARACTER
TRNST_NUM                       	CHARACTER
PRD_CD                          	CHARACTER
CORP_RTL_F                      	CHARACTER
BLOCK_RECL_CD                   	CHARACTER
ACCT_STAT_CD                    	CHARACTER
ACCT_OPND_DT                    	DATE
SRC_CD                          	CHARACTER
FINAL_CR_SCORE                  	DECIMAL
LAST_PRCH_DT                    	DATE
LAST_ACTY_DT                    	DATE
CR_LMT_AMT                      	DECIMAL
CRNT_BILL_CD                    	CHARACTER
MTH_DLQNT_CNT                   	DECIMAL
DLQNT_HIST_13_24                	DECIMAL
DLQNT_HIST_1_12                 	DECIMAL
ORIG_CHRG_OFF_AMT               	DECIMAL
CHRG_OFF_DT                     	DATE
CHRG_OFF_CD                     	CHARACTER
LAST_PYMT_DT                    	DATE
LAST_PYMT_AMT                   	DECIMAL
PRCH_CRNT_CYCL_BAL_AMT          	DECIMAL
PRCH_1_CYCL_AGO_BAL_AMT         	DECIMAL
PRCH_2_CYCL_AGO_BAL_AMT         	DECIMAL
CSH_ADVNC_CRNT_CYCL_BAL_AMT     	DECIMAL
CSH_ADVNC_1_CYCL_AGO_BAL_AMT    	DECIMAL
CSH_ADVNC_2_CYCL_AGO_BAL_AMT    	DECIMAL
TOT_NEW_BAL_AMT                 	DECIMAL
TOT_UNPAID_FNCL_CHRG_AMT        	DECIMAL
RISK_BAL_RTO                    	DECIMAL
FRST_USE_DT                     	DATE
CR_SCORE                        	DECIMAL
NON_ACCRL_DT                    	DATE
WRITE_OFF_DT                    	DATE
ACCT_CLS_RSN_CD                 	CHARACTER
BNS_DLQNT_DAY                   	DECIMAL
LAST_BLOCKED_DT                 	DATE
TOT_CYCL_TO_DT_FNCL_CHRG_AMT    	DECIMAL
PROC_TP_CD                      	CHARACTER
SCRD_TP_CD                      	CHARACTER
VISA_PLASTIC_OUT                	DECIMAL
YTD_PRCHS_CNT                   	DECIMAL
YTD_PRCHS_INTR_CHRGD_AMT        	DECIMAL
YTD_PRCHS_INTR_PD_AMT           	DECIMAL
YTD_CSH_ADVNC_INTR_CHRGD_AMT    	DECIMAL
YTD_CSH_ADVNC_INTR_PD           	DECIMAL
TOT_RCVRY_INTR_AMT              	DECIMAL
SWITCH_CD                       	CHARACTER
NEXT_RNEW_FEE_DT                	DATE
SWITCH_XREF                     	CHARACTER
SWITCH_DT                       	DATE
CHIP_F                          	CHARACTER
CMPGN_STAT_CD                   	CHARACTER
CMPGN_NOTIFIED_CD               	CHARACTER
COLCTN_CTR_CD                   	CHARACTER
SETP_TRNST_NUM                  	CHARACTER
SUB_PRD_TFR_DT                  	DATE
PRCH_RCVRY_INTR_AMT             	DECIMAL
CSH_ADVNC_RCVRY_INTR_AMT        	DECIMAL
LAST_YR_CR_INTR_PD_AMT          	DECIMAL
TOT_YTD_CR_INTR_PD_AMT          	DECIMAL
NON_RESPONDER_F                 	CHARACTER
RTN_ENVELOPE                    	CHARACTER
INACT_CD                        	CHARACTER
PAD_OTH_FNCL_INST_F             	CHARACTER
SCRTY_TP_CD                     	CHARACTER
ANUL_FEE_CD                     	CHARACTER
FNCL_YTD_PRCHS_AMT              	DECIMAL
FNCL_YTD_RTRNS_AMT              	DECIMAL
DIVDD_RBT_LAST_YR_AMT           	DECIMAL
MDL_COMPACTION                  	CHARACTER
MDL_CITIFONE                    	CHARACTER
MDL_CD_3                        	CHARACTER
MDL_CD_4                        	CHARACTER
LAST_ONLINE_UPDT_DT             	DATE
OPRTR_LAST_ONLINE_UPDT          	CHARACTER
SOLCTN_CD                       	CHARACTER
SCRTY_VAL_AMT                   	DECIMAL
LAST_ADDR_CHNG_DT               	DATE
BAL_HIST_PRCHS_AMT              	DECIMAL
BAL_HIST_CSH_ADV_AMT            	DECIMAL
BAL_HIST_PYMTS_AMT              	DECIMAL
ANUL_FEE_LNK_F                  	CHARACTER
FULL_PYMT_CD                    	CHARACTER
PREV_SUB_PRD_CD                 	CHARACTER
REQST_CR_LMT_AMT                	DECIMAL
SPSP_CCLI                       	CHARACTER
PRIM_CUST_CID                   	CHARACTER
STEP_PLN_AGRMNT_NUM             	CHARACTER
INSRT_PROCESS_TMSTMP            	TIMESTAMP
UPDT_PROCESS_TMSTMP             	TIMESTAMP
GL_ACCT_NUM                     	VARCHAR
GL_TRNST_NUM                    	VARCHAR
CRNCY_CD                        	VARCHAR

 **/
-- BASEL_REVLVNG_CR_MTH_SNAPSHOT TABLE DEFINITION
CREATE TABLE
    IF NOT EXISTS INGESTION.BASEL_REVLVNG_CR_MTH_SNAPSHOT (
        REVLVNG_CR_BASEL_MTH_SNAPSHOT_ID BIGINT NOT NULL,
        MTH_TM_ID INTEGER NOT NULL,
        BASEL_ACCT_ID BIGINT NOT NULL,
        PRIM_BASEL_CUST_ID BIGINT NOT NULL,
        STEP_PLN_SNAPSHOT_ID BIGINT NOT NULL,
        ACCT_NUM VARCHAR,
        TRNST_OU_ID BIGINT NOT NULL,
        SUB_PRD_CD VARCHAR,
        TRNST_NUM VARCHAR,
        PRD_CD VARCHAR,
        CORP_RTL_F VARCHAR,
        BLOCK_RECL_CD VARCHAR,
        ACCT_STAT_CD VARCHAR,
        ACCT_OPND_DT DATE,
        SRC_CD VARCHAR,
        FINAL_CR_SCORE DECIMAL(3, 0),
        LAST_PRCH_DT DATE,
        LAST_ACTY_DT DATE,
        CR_LMT_AMT DECIMAL(17, 3),
        CRNT_BILL_CD VARCHAR,
        MTH_DLQNT_CNT DECIMAL(3, 0),
        DLQNT_HIST_13_24 DECIMAL(12, 0),
        DLQNT_HIST_1_12 DECIMAL(12, 0),
        ORIG_CHRG_OFF_AMT DECIMAL(17, 3),
        CHRG_OFF_DT DATE,
        CHRG_OFF_CD VARCHAR,
        LAST_PYMT_DT DATE,
        LAST_PYMT_AMT DECIMAL(17, 3),
        PRCH_CRNT_CYCL_BAL_AMT DECIMAL(17, 3),
        PRCH_1_CYCL_AGO_BAL_AMT DECIMAL(17, 3),
        PRCH_2_CYCL_AGO_BAL_AMT DECIMAL(17, 3),
        CSH_ADVNC_CRNT_CYCL_BAL_AMT DECIMAL(17, 3),
        CSH_ADVNC_1_CYCL_AGO_BAL_AMT DECIMAL(17, 3),
        CSH_ADVNC_2_CYCL_AGO_BAL_AMT DECIMAL(17, 3),
        TOT_NEW_BAL_AMT DECIMAL(17, 3),
        TOT_UNPAID_FNCL_CHRG_AMT DECIMAL(17, 3),
        RISK_BAL_RTO DECIMAL(7, 6),
        FRST_USE_DT DATE,
        CR_SCORE DECIMAL(4, 0),
        NON_ACCRL_DT DATE,
        WRITE_OFF_DT DATE,
        ACCT_CLS_RSN_CD VARCHAR,
        BNS_DLQNT_DAY DECIMAL(3, 0),
        LAST_BLOCKED_DT DATE,
        TOT_CYCL_TO_DT_FNCL_CHRG_AMT DECIMAL(17, 3),
        PROC_TP_CD VARCHAR,
        SCRD_TP_CD VARCHAR,
        VISA_PLASTIC_OUT DECIMAL(2, 0),
        YTD_PRCHS_CNT DECIMAL(5, 0),
        YTD_PRCHS_INTR_CHRGD_AMT DECIMAL(17, 3),
        YTD_PRCHS_INTR_PD_AMT DECIMAL(17, 3),
        YTD_CSH_ADVNC_INTR_CHRGD_AMT DECIMAL(17, 3),
        YTD_CSH_ADVNC_INTR_PD DECIMAL(17, 3),
        TOT_RCVRY_INTR_AMT DECIMAL(17, 3),
        SWITCH_CD VARCHAR,
        NEXT_RNEW_FEE_DT DATE,
        SWITCH_XREF VARCHAR,
        SWITCH_DT DATE,
        CHIP_F VARCHAR,
        CMPGN_STAT_CD VARCHAR,
        CMPGN_NOTIFIED_CD VARCHAR,
        COLCTN_CTR_CD VARCHAR,
        SETP_TRNST_NUM VARCHAR,
        SUB_PRD_TFR_DT DATE,
        PRCH_RCVRY_INTR_AMT DECIMAL(17, 3),
        CSH_ADVNC_RCVRY_INTR_AMT DECIMAL(17, 3),
        LAST_YR_CR_INTR_PD_AMT DECIMAL(17, 3),
        TOT_YTD_CR_INTR_PD_AMT DECIMAL(17, 3),
        NON_RESPONDER_F VARCHAR,
        RTN_ENVELOPE VARCHAR,
        INACT_CD VARCHAR,
        PAD_OTH_FNCL_INST_F VARCHAR,
        SCRTY_TP_CD VARCHAR,
        ANUL_FEE_CD VARCHAR,
        FNCL_YTD_PRCHS_AMT DECIMAL(17, 3),
        FNCL_YTD_RTRNS_AMT DECIMAL(17, 3),
        DIVDD_RBT_LAST_YR_AMT DECIMAL(17, 3),
        MDL_COMPACTION VARCHAR,
        MDL_CITIFONE VARCHAR,
        MDL_CD_3 VARCHAR,
        MDL_CD_4 VARCHAR,
        LAST_ONLINE_UPDT_DT DATE,
        OPRTR_LAST_ONLINE_UPDT VARCHAR,
        SOLCTN_CD VARCHAR,
        SCRTY_VAL_AMT DECIMAL(17, 3),
        LAST_ADDR_CHNG_DT DATE,
        BAL_HIST_PRCHS_AMT DECIMAL(17, 3),
        BAL_HIST_CSH_ADV_AMT DECIMAL(17, 3),
        BAL_HIST_PYMTS_AMT DECIMAL(17, 3),
        ANUL_FEE_LNK_F VARCHAR,
        FULL_PYMT_CD VARCHAR,
        PREV_SUB_PRD_CD VARCHAR,
        REQST_CR_LMT_AMT DECIMAL(17, 3),
        SPSP_CCLI VARCHAR,
        PRIM_CUST_CID VARCHAR NOT NULL,
        STEP_PLN_AGRMNT_NUM VARCHAR,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
        GL_ACCT_NUM VARCHAR,
        GL_TRNST_NUM VARCHAR,
        CRNCY_CD VARCHAR,
    )
;

-- PARTITIONING SCHEME FOR BASEL_REVLVNG_CR_MTH_SNAPSHOT
ALTER TABLE INGESTION.BASEL_REVLVNG_CR_MTH_SNAPSHOT
SET
    PARTITIONED BY (MTH_TM_ID)
;