/**

IIAS Schema:

Column Name	            Schema	Type
BASEL_ACCT_ID	        BIGINT
CIS_PRD_CD	            CHARACTER
ACCT_NUM	            CHARACTER
INTG_LAYER_SRC_ID	    BIGINT
SRC_SYS_DEL_DT	        DATE
SRC_APP_CD	            CHARACTER
INTG_LAYER_SRC_TBL_NM	CHARACTER
SRC_APP_ID	            CHARACTER
SRC_SYS_DEL_F	        CHARACTER
INSRT_PROCESS_TMSTMP    TIMESTAMP
UPDT_PROCESS_TMSTMP     TIMESTAMP


 **/
CREATE TABLE
    IF NOT EXISTS ingestion.BASEL_ACCT_DIM (
        BASEL_ACCT_ID BIGINT NOT NULL,
        CIS_PRD_CD VARCHAR,
        ACCT_NUM VARCHAR,
        INTG_LAYER_SRC_ID BIGINT,
        SRC_SYS_DEL_DT DATE,
        SRC_APP_CD VARCHAR,
        INTG_LAYER_SRC_TBL_NM VARCHAR,
        SRC_APP_ID VARCHAR,
        SRC_SYS_DEL_F VARCHAR,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;