-- BASEL_PSNL_LOAN_MTH_SNAPHSOT TABLE DEFINITION
CREATE TABLE
        IF NOT EXISTS ingestion.BASEL_PSNL_LOAN_MTH_SNAPSHOT (
                BASEL_PSNL_LOAN_MTH_SNAPSHOT_ID BIGINT NOT NULL,
                MTH_TM_ID INTEGER NOT NULL,
                BASEL_ACCT_ID BIGINT NOT NULL,
                PRIM_BASEL_CUST_ID BIGINT NOT NULL,
                STEP_PLN_SNAPSHOT_ID BIGINT NOT NULL,
                TRNST_NUM VARCHAR,
                TRNST_OU_ID BIGINT NOT NULL,
                LOAN_NUM VARCHAR,
                RECD_STAT_CD VARCHAR,
                RECD_STAT_DT DATE,
                RSDNC_CD VARCHAR,
                LOAN_SRC_CD VARCHAR,
                PRPS_CD VARCHAR,
                SCRTY_CD VARCHAR,
                RT_CD VARCHAR,
                PROMISSORS_CNT DECIMAL(1, 0),
                GRNT_CNT DECIMAL(1, 0),
                COMM_LOAN_CD VARCHAR,
                NOTE_DT DATE,
                FRST_PAY_DT DATE,
                LAST_RGL_PAY_DT DATE,
                ORIG_LOAN_AMT DECIMAL(17, 3),
                ADD_ON_BAL_AMT DECIMAL(17, 3),
                ADD_ON_INTR_AMT DECIMAL(17, 3),
                DAY_ODUE DECIMAL(6, 0),
                ACCR_INTR DECIMAL(17, 3),
                EARLY_MAT_DT DATE,
                LAST_PYMT_DT DATE,
                TOT_CRNT_BAL_AMT DECIMAL(17, 3),
                MOTOR_VEHCL_VAL DECIMAL(17, 3),
                HH_VAL DECIMAL(17, 3),
                LOAN_VAL_OTH DECIMAL(17, 3),
                CRNT_BR_LOCTN_OU_ID BIGINT NOT NULL,
                CR_SCORE DECIMAL(3, 0),
                CRNT_BR_LOCTN_TRNST VARCHAR,
                EARNED_MTH_INTR DECIMAL(17, 3),
                LOAN_ORIG_NOTE_DT DATE,
                CHRG_OFF_DT DATE,
                CHRG_OFF_AMT DECIMAL(17, 3),
                SECRTZTN_CD VARCHAR,
                LOAN_TERM DECIMAL(6, 0),
                EARLY_MAT_TERM DECIMAL(4, 0),
                EARLY_MAT_STAT_CD VARCHAR,
                RGL_PYMT_AMT DECIMAL(17, 3),
                PYMT_FREQ_CD VARCHAR,
                INTR_RT DECIMAL(6, 2),
                CIF_COMPANY_ID DECIMAL(6, 0),
                CIF_CUST_ID VARCHAR,
                CIF_TIE_BREAKER DECIMAL(6, 0),
                STEP_PLN_AGRMNT_NUM VARCHAR,
                CUST_CID VARCHAR,
                INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
                UPDT_PROCESS_TMSTMP TIMESTAMP,
                BOOKED_AMT DECIMAL(17, 3),
                GL_ACCT_NUM VARCHAR,
                GL_TRNST_NUM VARCHAR,
                CRNCY_CD VARCHAR,
        )
;

-- PARTITIONING SCHEME FOR BASEL_PSNL_LOAN_MTH_SNAPSHOT
ALTER TABLE ingestion.BASEL_PSNL_LOAN_MTH_SNAPSHOT
SET
        PARTITIONED BY (MTH_TM_ID)
;