CREATE TABLE IF NOT EXISTS ingestion.CL_SOURCE_FILE_ACCOUNTS (
    EFFECTIVE_DATE DATE,
    VISA_ACCT_NUM VARCHAR,
    OUTSTANDING_BAL DECIMAL(17,2)
);
ALTER TABLE ingestion.CL_SOURCE_FILE_ACCOUNTS SET PARTITIONED BY (EFFECTIVE_DATE);
