CREATE TABLE IF NOT EXISTS ingestion.CUST_XREF (
    CUST_ID VARCHAR,
    CUST_BASE_KEY BIGINT,
    FROM_EDW_F VARCHAR,
    POPN_DT DATE
);
ALTER TABLE ingestion.CUST_XREF SET PARTITIONED BY (POPN_DT);
