CREATE TABLE IF NOT EXISTS ingestion.HH_DSPSBL_INCM_QTR (
    MTH_TM_ID INTEGER,
    EFF_FROM_YR_MTH VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    HH_DSPSBL_INCM_MILLNTH_AMT INTEGER,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);
