CREATE TABLE IF NOT EXISTS ingestion.IWD_PD_PLN (
    PD_PLN_KEY INTEGER,
    PD_PLN_LVL VARCHAR,
    POPN_DT DATE,
    ALL_PD_PLN INTEGER,
    SUM_SRVC_CODE VARCHAR,
    PD_PLN_CODE VARCHAR,
    PD_PLN_DESC VARCHAR,
    PD_KEY DECIMAL(11,0),
    SUM_SRVC_KEY DECIMAL(11,0)
);
