CREATE TABLE IF NOT EXISTS ingestion.IWD_CHNL (
    DLVY_KEY INTEGER,
    DLVY_LVL VARCHAR,
    POPN_DT DATE,
    ALL_CHNL_ACTY_DESC VARCHAR,
    DLVY_CHNL_DESC VARCHAR,
    TXN_GRP_DESC VARCHAR,
    ACTY_DESC VARCHAR,
    TXN_TP_DESC VARCHAR,
    DLVY_DESC VARCHAR,
    TXN_TP_KEY INTEGER,
    ACTY_KEY INTEGER,
    TXN_GRP_KEY INTEGER,
    CHNL_KEY INTEGER,
    ALL_DLVY_KEY INTEGER
);
