CREATE TABLE IF NOT EXISTS ingestion.IWD_CUST (
    CUST_BASE_KEY BIGINT,
    CUST_KEY BIGINT,
    CUST_ACCT_CNT INTEGER,
    POPN_DT DATE
);
ALTER TABLE ingestion.IWD_CUST SET PARTITIONED BY (POPN_DT);
