CREATE TABLE IF NOT EXISTS ingestion.IWF_ACTY_ROLLUP (
    TIME_KEY INTEGER,
    DLVY_KEY INTEGER,
    ACCT_ID VARCHAR,
    ACCT_BASE_KEY BIGINT,
    ACCT_KEY BIGINT,
    ACTY_CNT INTEGER,
    ACTY_TOT_AMT DOUBLE,
    MTH_END_DT DATE
);
ALTER TABLE ingestion.IWF_ACTY_ROLLUP SET PARTITIONED BY (TIME_KEY);
