CREATE TABLE IF NOT EXISTS ingestion.IWF_CUST_ACTY_RLP (
    TIME_KEY INTEGER,
    DLVY_KEY INTEGER,
    CUST_ID VARCHAR,
    CUST_BASE_KEY BIGINT,
    CUST_KEY BIGINT,
    ACCT_ID VARCHAR,
    ACCT_BASE_KEY BIGINT,
    ACCT_KEY BIGINT,
    ACTY_CNT INTEGER,
    ACTY_TOT_AMT DOUBLE,
    MTH_END_DT DATE
);
ALTER TABLE ingestion.IWF_CUST_ACTY_RLP SET PARTITIONED BY (TIME_KEY);
