CREATE TABLE IF NOT EXISTS ingestion.IWF_CUST_ACCT (
    ACCT_BASE_KEY BIGINT,
    CUST_BASE_KEY BIGINT,
    ACCT_LCST VARCHAR,
    PD_PLN_KEY INTEGER,
    ACCT_BAL DOUBLE,
    PRIM_CUST_F VARCHAR,
    SUM_SRVC_CODE VARCHAR,
    ACCT_KEY BIGINT,
    CUST_KEY BIGINT,
    TIME_KEY BIGINT
);
ALTER TABLE ingestion.IWF_CUST_ACCT SET PARTITIONED BY (TIME_KEY);
