CREATE TABLE IF NOT EXISTS ingestion.MBR_SRC_CURR (
    TRANSIT VARCHAR,
    PPLAN VARCHAR,
    ALPHCURR VARCHAR,
    DECUM DECIMAL(17,3),
    YTD DECIMAL(17,3),
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);