-- METRPL_CITY_LKP table definition
CREATE TABLE IF NOT EXISTS ingestion.METRPL_CITY_LKP (
    CITY_NM VARCHAR,
    METRPL_AREA_NM VARCHAR,
    EFF_FROM_YR_MTH VARCHAR,
    PROV VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);
