CREATE TABLE IF NOT EXISTS ingestion.ORG_UNIT_DIM (
    ORG_UNIT_ID BIGINT,
    ORG_UNIT_LVL VARCHAR,
    TRNST_NUM VARCHAR,
    ORG_UNIT_NM VARCHAR,
    CITY VARCHAR,
    CLS_DT DATE,
    OPN_DT DATE,
    PH_NUM VARCHAR,
    POSTAL_ZIP_CD VARCHAR,
    PROV_STATE VARCHAR,
    STRT_ADDR VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);
