CREATE TABLE IF NOT EXISTS ingestion.OS_TOS_ORGANIZATION (
    PARTY_ID VARCHAR NOT NULL,
    BUSINESS_EFFECTIVE_DATE DATE NOT NULL,
    ORG_TYPE_CD VARCHAR,
    PERSON_ORG_CD VARCHAR,
    SINCE_DT DATE,
    BANKRUPTCY_DT DATE,
    DOMICILE_TRANSIT_NUM VARCHAR,
    PREF_LANG_CD VARCHAR,
    LEFT_DT DATE,
    SENSITIVITY_CD VARCHAR
);

ALTER TABLE ingestion.OS_TOS_ORGANIZATION
SET PARTITIONED BY (BUSINESS_EFFECTIVE_DATE);
