CREATE TABLE IF NOT EXISTS ingestion.OS_TOS_PERSON (
    PARTY_ID VARCHAR NOT NULL,
    BUSINESS_EFFECTIVE_DATE DATE NOT NULL,
    BIRTH_DT DATE,
    PERSON_ORG_CD VARCHAR,
    OCCUP_TYPE_CD VARCHAR,
    OCCUP_STAT_CD VARCHAR,
    OCCUP_CAT_CD VARCHAR,
    SINCE_DT DATE,
    BANKRUPTCY_DT DATE,
    DOMICILE_TRANSIT_NUM VARCHAR,
    GENDER_CD VARCHAR,
    EMP_TYPE_CD VARCHAR,
    MARITAL_STAT_CD VARCHAR,
    PREF_LANG_CD VARCHAR,
    OCCUP_CD VARCHAR,
    DECEASED_DT DATE,
    LEFT_DT DATE,
    END_DT DATE,
    SENSITIVITY_CD VARCHAR
);

ALTER TABLE ingestion.OS_TOS_PERSON
SET PARTITIONED BY (BUSINESS_EFFECTIVE_DATE);
