CREATE TABLE IF NOT EXISTS ingestion.PIT_STATUS_PRE_STEP (
    MTH_TM_ID INTEGER NOT NULL,
    SRC_SYS_CD VARCHAR NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    MORT_NUM INTEGER,
    MORT_PROCESS_DATE TIMESTAMP,
    PIT_STATUS_PRE_STEP VARCHAR,
    STEP_PLN_SNAPSHOT_ID BIGINT NOT NULL,
    STEP_PLN_AGRMNT_NUM VARCHAR,
    STEP_DFLT_F VARCHAR,
    CROSS_DFLT_PIT_OVERRIDE_F VARCHAR,
    CROSS_DFLT_PIT_STATUS VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE ingestion.PIT_STATUS_PRE_STEP
SET PARTITIONED BY (MTH_TM_ID);
