CREATE TABLE IF NOT EXISTS ingestion.PROVNCL_HOUSE_INDEX_SUM(
MTH_TM_ID            INTEGER     ,
PROV_CD              VARCHAR     ,
SLS_PAIR_ANLYS_CNT   INTEGER     ,
HOUSE_INDEX_RTO      DOUBLE      ,
INSRT_PROCESS_TMSTMP TIMESTAMP   ,
UPDT_PROCESS_TMSTMP  TIMESTAMP    
);
-- Set partitions 
ALTER TABLE ingestion.PROVNCL_HOUSE_INDEX_SUM SET PARTITIONED BY (MTH_TM_ID); 
