CREATE TABLE IF NOT EXISTS ingestion.PROVNCL_HOUSE_INDEX_SUM_CMA(
MTH_TM_ID            INTEGER     ,
PROV_CD              VARCHAR     ,
SLS_PAIR_ANLYS_CNT   INTEGER     ,
HOUSE_INDEX_RTO      DECIMAL(18,4)      ,
INSRT_PROCESS_TMSTMP TIMESTAMP   ,
UPDT_PROCESS_TMSTMP  TIMESTAMP    
);

ALTER TABLE ingestion.PROVNCL_HOUSE_INDEX_SUM_CMA SET PARTITIONED BY (MTH_TM_ID); 
