-- RLP_TO_SL_ACCT_LIST TABLE DEFINITION
CREATE TABLE IF NOT EXISTS ingestion.RLP_TO_SL_ACCT_LIST (
        RLP_LOAN_NO VARCHAR,
        SL_LOAN_NO VARCHAR,
        ORIG_BASEL_ACCT_ID VARCHAR,
        PRPS_CD VARCHAR,
        MOTOR_VEHCL_VAL DOUBLE,
        CRNT_BR_LOCTN_TRNST VARCHAR,
        LOAN_VAL_OTH DOUBLE,
        SCRTY_CD VARCHAR
);
