CREATE TABLE IF NOT EXISTS ingestion.SPL_SOURCE_FILE_ACCOUNTS (
    EFFECTIVE_DATE DATE,
    ACCOUNT_NUMBER VARCHAR,
    OUTSTANDING_BALANCE DECIMAL(17,2),
    ACCRUED_INTEREST DECIMAL(17,2),
    SECURITIZATION_DATE VARCHAR
);
ALTER TABLE ingestion.SPL_SOURCE_FILE_ACCOUNTS SET PARTITIONED BY (EFFECTIVE_DATE);
