CREATE TABLE IF NOT EXISTS ingestion.TERANET_HOUSE_PRC_INDEX(
MTH_TM_ID INTEGER ,
LABEL_1   VARCHAR ,
LABEL_2   VARCHAR ,
TXN_DT    DATE ,
PUBLCT_DT DATE ,
INDEX     DECIMAL(8,4) ,
SLS_PAIR_CNT INTEGER ,
INSRT_PROCESS_TMSTMP TIMESTAMP ,
UPDT_PROCESS_TMSTMP TIMESTAMP 
);

ALTER TABLE ingestion.TERANET_HOUSE_PRC_INDEX SET PARTITIONED BY (MTH_TM_ID); 