CREATE TABLE IF NOT EXISTS ingestion.TERANET_HOUSE_PRC_INDEX_CMA(
MTH_TM_ID INTEGER ,
LABEL_1   VARCHAR ,
LABEL_2   VARCHAR ,
LABEL_2_ORIG   VARCHAR ,
INDEX     DOUBLE ,
SLS_PAIR_CNT DOUBLE ,
INSRT_PROCESS_TMSTMP TIMESTAMP  ,
UPDT_PROCESS_TMSTMP TIMESTAMP 
);

ALTER TABLE ingestion.TERANET_HOUSE_PRC_INDEX_CMA SET PARTITIONED BY (MTH_TM_ID); 