-- TERANET_ADDR_LKP_CMA table definition
CREATE TABLE IF NOT EXISTS ingestion.TERANET_ADDR_LKP_CMA (
PRPTY_LOCTN_NM       VARCHAR ,
EFF_FROM_YR_MTH      VARCHAR ,
EFF_TO_YR_MTH        VARCHAR ,
LOCTN_LABEL_1        VARCHAR ,
LOCTN_LABEL_2        VARCHAR ,
LOCTN_LABEL_2_ORIG   VARCHAR ,
CRNT_F               VARCHAR ,
INSRT_PROCESS_TMSTMP TIMESTAMP, 
UPDT_PROCESS_TMSTMP  TIMESTAMP
);
-- PARTITIONING SCHEME FOR TERANET_ADDR_LKP_CMA
ALTER TABLE  ingestion.TERANET_ADDR_LKP_CMA SET PARTITIONED BY (EFF_TO_YR_MTH);

