CREATE TABLE
    IF NOT EXISTS ingestion.TM_DIM (
        TM_ID INTEGER,
        TM_LVL VARCHAR,
        TM_SEQ_NUM INTEGER,
        TM_YR_SEQ_NUM INTEGER,
        TM_CRNT_F VARCHAR,
        CLNDR_YR VARCHAR,
        FNCL_YR VARCHAR,
        CLNDR_QTR_CD VARCHAR,
        FNCL_QTR_CD VARCHAR,
        MTH_CLNDR_CD VARCHAR,
        DAY_OF_WK_CD VARCHAR,
        DAY_OF_WK_DESC VARCHAR,
        DAY_DT DATE,
        ANUL_FNCL_KEY INTEGER,
        FNCL_QTR_KEY INTEGER,
        FNCL_MTH_KEY INTEGER,
        FNCL_DAY_KEY INTEGER,
        TM_DESC VARCHAR,
        TM_LVL_ST_DT DATE,
        TM_LVL_END_DT DATE,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;