CREATE TABLE IF NOT EXISTS ingestion.TNG_ACCT_COLLECTTRST (
    MONTH_END_DT DATE,
    MTG_NUM DECIMAL(12,0),
    TXN_DATE DATE,
    TXN_AMOUNT DECIMAL(12,2),
    TXN_COMMENT VARCHAR,
    TXN_TYPE_CATEGORY VARCHAR
);
ALTER TABLE ingestion.TNG_ACCT_COLLECTTRST SET PARTITIONED BY (MONTH_END_DT);
