CREATE TABLE IF NOT EXISTS ingestion.TNG_ACCT_WRITEOFF (
    MONTH_END_DT DATE,
    MTG_NUM VARCHAR,
    PROVIDER VARCHAR,
    INSURANCE_TYPE VARCHAR,
    WRITEOFF_DATE DATE,
    WRITEOFF_AMT DECIMAL(12,2),
    INSURER_DESC VARCHAR,
    LAST_DEFAULT_DT DATE,
    FRAUD_IND VARCHAR
);
ALTER TABLE ingestion.TNG_ACCT_WRITEOFF SET PARTITIONED BY (MONTH_END_DT);