CREATE TABLE IF NOT EXISTS ingestion.TNG_CUST_MO (
    MONTH_END_DT DATE,
    CUSTOMER_ID VARCHAR,
    CUSTOMER_KEY DECIMAL(8,0),
    LOAN_DECLINE_IND VARCHAR,
    MTG_DECLINE_IND VARCHAR,
    DEPOSIT_ACCTS_CNT DECIMAL(8,0),
    DEPOSIT_ACCTS_AMT DECIMAL(12,2),
    LOAN_ACCTS_CNT DECIMAL(8,0),
    LOAN_ACCTS_AMT DECIMAL(12,2),
    MAX_DEP_BALANCE DECIMAL(12,2),
    MAX_DEP_BALANCE_DT DATE,
    CREDIT_SCORE DECIMAL(8,0),
    CREDIT_SCORE_DT DATE,
    ACCESS_TO_FUNDS_AMT DECIMAL(12,2),
    HIGH_FREQ_CALLER_IND VARCHAR,
    HIGH_FREQ_CALLER_DT DATE,
);
ALTER TABLE ingestion.TNG_CUST_MO SET PARTITIONED BY (MONTH_END_DT);