CREATE TABLE EDRTLRIFRS9.BASEL_ANALYTCL_BL_INST_KS_IFRS
(
BASEL_ACCT_ID	DECIMAL	(20,0),
MTH_TM_ID	DECIMAL	(11,0),
SRC_SYS_CD	VARCHAR	(10),
ACCT_NUM	VARCHAR	(23),
LOAN_NUM	VARCHAR	(15),
MORT_NUM	VARCHAR	(50),
BASEL_PRD_ABR	VARCHAR	(50),
BASEL_PRD_TP_CD	VARCHAR	(10),
OS_BAL_AMT	DECIMAL	(18,3),
ADJUSTED_OS_BAL_AMT	DECIMAL	(19,8),
CR_LMT_AMT	DECIMAL	(19,8),
INDEXED_PRPTY_VAL_AMT	DECIMAL	(18,3),
SUB_PRD_CD	VARCHAR	(10),
EAD_BASEL_SEG_NUM	DECIMAL	(11,0),
EAD_BASEL_SCORECRD_NM	VARCHAR	(40),
EAD_MODEL_NM	VARCHAR	(40),
PD_BASEL_SEG_NUM	DECIMAL	(11,0),
PD_BASEL_SCORECRD_NM	VARCHAR	(40),
PD_MODEL_NM	VARCHAR	(40),
LGD_BASEL_SEG_NUM	DECIMAL	(11,0),
LGD_BASEL_SCORECRD_NM	VARCHAR	(40),
LGD_MODEL_NM	VARCHAR	(40),
PD_ACCT_SCORE	DECIMAL	(11,0),
LGD_ACCT_SCORE	DECIMAL	(11,0),
DLGD_F	VARCHAR	(1),
METRPL_AREA_NM	VARCHAR	(32),
CCAR_EXPSR_CL_NM	VARCHAR	(20),
PD_FINAL_RPTG_RTO	DECIMAL	(29,8),
LGD_FINAL_RPTG_RTO	DECIMAL	(29,8),
DLGD_RPTG_RTO	DECIMAL	(27,8),
EAD_FINAL_RPTG_RTO	DECIMAL	(29,8),
BCAR_SCHED_NUM	VARCHAR	(3),
SCRTY_TP_DESC	VARCHAR	(50),
INSRT_PROCESS_TMSTMP	TIMESTAMP,	
UPDT_PROCESS_TMSTMP	TIMESTAMP
) ORGANIZE BY ROW;

CREATE TABLE EDRTLRIFRS9.BASEL_REVLVNG_CR_RPTG_DRVD_VAR_IFRS
(
BASEL_ACCT_ID	DECIMAL	(20,0),
MTH_TM_ID	DECIMAL	(11,0),
NCR_EXPSR_CL_KEY_VAL	VARCHAR	(4),
NCR_RT_KEY_VAL	VARCHAR	(4),
DLQNT_ID	DECIMAL	(11,0),
NCR_EXPSR_SIZE_ID	DECIMAL	(11,0),
NCR_PD_BAND_ID	DECIMAL	(11,0),
NCR_GEO_ID	DECIMAL	(11,0),
NCR_PD_SEG_ID	DECIMAL	(11,0),
NCR_EAD_SEG_ID	DECIMAL	(11,0),
NCR_LGD_SEG_ID	DECIMAL	(11,0),
REVISED_EXPSR_OV_125K_F	VARCHAR	(1),
ASST_CL_NUM	INTEGER	(4),
ASST_CL_DESC	VARCHAR	(50),
BASEL_PRD_ABR	VARCHAR	(50),
PRIOR_3_MTH_ACCT_DFT_F	VARCHAR	(1),
NCR_REALZ_PD_RTO	DECIMAL	(29,8),
NCR_REALZ_EAD_RTO	DECIMAL	(29,8),
NCR_REALZ_LGD_RTO	DECIMAL	(29,8),
PRIOR_12_MTH_REALZ_DEFLTD_LOANS_OS_PD_BAL_AMT	DECIMAL	(17,3),
PRIOR_12_MTH_REALZ_DEFLTD_LOANS_OS_EAD_BAL_AMT	DECIMAL	(17,3),
PRIOR_36_MTH_REALZ_DEFLTD_LOANS_OS_LGD_BAL_AMT	DECIMAL	(17,3),
INSRT_PROCESS_TMSTMP	TIMESTAMP,
UPDT_PROCESS_TMSTMP	TIMESTAMP
) ORGANIZE BY ROW;

CREATE
VIEW EDRTLRIFRS9.ASST_DRC_COST_MTH_SNAPSHOT
AS SELECT
ASST_ID,
MTH_TM_ID,
ASST_BASE_ID,
ASST_NUM,
BASEL_ACCT_ID,
ACCT_NUM,
TRNST_NUM,
AGRMNT_TP_DESC,
SRC_SYS_CD,
PGM_TP_CD,
BAL_OWING_AMT,
ASGNMN_PRNCPL_OWING_AMT,
ASGNMN_ACCR_INTR_AMT,
ASGNMN_ADD_ON_COST_AMT,
ASGNMN_DT,
INSTRC_DESC,
STAT_DESC,
ACCT_STAT_DESC,
JUDGEMENT_CD,
LEGAL_COST_AMT,
PRPTY_MGT_COST_AMT,
INSPECTION_FEE_AMT,
ENVRNMTL_FEE_AMT,
INCM_GST_AMT,
UTL_AMT,
REPAIR_AMT,
CR_RPTG_COST_AMT,
CORP_RISK_INSUR_AMT,
TAX_AMT,
APPRAISAL_FEE_AMT,
CONDMNM_FEE_AMT,
MISC_FEE_AMT,
LOAD_FEE_AMT,
COMMSN_AMT,
TOT_COST_EXPNS_AMT,
DOLLARS_RECOVERED_RECVD_AMT,
PRCD_TO_PAY_FOR_EXPNS_AMT,
TOT_RCVRY_AMT,
HLDBCK_AMT,
APPRAISAL_AMT,
MTH_END_PRNCPL_BAL_OWING_AMT,
MTH_END_ACCR_INTR_OWING_AMT,
MTH_END_ADD_ON_COST_AMT,
HGHWY_CD,
STATE_DESC,
CLS_DT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.ASST_DRC_COST_MTH_SNAPSHOT;
		
		
CREATE
VIEW EDRTLRIFRS9.BASEL_ACCT_DIM
AS SELECT
BASEL_ACCT_ID,
CIS_PRD_CD,
ACCT_NUM,
INTG_LAYER_SRC_ID,
SRC_SYS_DEL_DT,
SRC_APP_CD,
INTG_LAYER_SRC_TBL_NM,
SRC_APP_ID,
SRC_SYS_DEL_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_ACCT_DIM
;
		

CREATE
VIEW EDRTLRIFRS9.BASEL_CUST_ACCT_RLTNP_SNAPSHOT
 AS SELECT
BASEL_CUST_ID,
BASEL_ACCT_ID,
MTH_TM_ID,
PRIM_CUST_F,
REL_CD,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
 EDRTLRP1D.BASEL_CUST_ACCT_RLTNP_SNAPSHOT
;
CREATE
VIEW EDRTLRIFRS9.BASEL_CUST_DIM
AS SELECT
BASEL_CUST_ID,
CIF_KEY,
CUST_CID,
CUST_TP_CD,
IP_ID,
CIS_PURGED_F,
CIS_PURGED_DT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_CUST_DIM
;

CREATE
VIEW EDRTLRIFRS9.BASEL_CUST_MTH_DEP_TXN_SUM
AS SELECT
MTH_TM_ID,
BASEL_CUST_ID,
DEP_CNT,
NSF_CNT,
OVDR_CNT,
PAYRL_CNT,
TOT_DEP_AMT,
TOT_NSF_AMT,
TOT_PAYRL_AMT,
TOT_WTHDRWL_AMT,
WTHDRWL_CNT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_CUST_MTH_DEP_TXN_SUM
;

CREATE
VIEW EDRTLRIFRS9.BASEL_CUST_MTH_POSTN_SUM_FACT
AS SELECT
MTH_TM_ID,
BASEL_CUST_ID,
D2D_ACCT_CNT,
D2D_BAL_AMT,
RGSTRD_INVSTMNT_BAL_ACCT_CNT,
RGSTRD_INVSTMNT_BAL_AMT,
NON_REGISTERED_INVSTMNT_ACCT_CNT,
NON_REGISTERED_INVSTMNT_BAL_AMT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP,
BASEL_RGSTRD_INVSTMNT_ACCT_CNT,
BASEL_RGSTRD_INVSTMNT_BAL_AMT,
BASEL_NON_RGSTRD_INVSTMNT_ACCT_CNT,
BASEL_NON_RGSTRD_INVSTMNT_BAL_AMT
FROM
EDRTLRP1D.BASEL_CUST_MTH_POSTN_SUM_FACT

;
CREATE
VIEW EDRTLRIFRS9.BASEL_DFT_LKP
AS SELECT
DIS_RT_CD,
EFF_FROM_YR_MTH,
EFF_TO_YR_MTH,
CRNT_F,
DIS_RT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_DFT_LKP;

CREATE
VIEW EDRTLRIFRS9.BASEL_MORT_ACCT_DRVD_VARS
AS SELECT
MTH_TM_ID,
BASEL_ACCT_ID,
BASEL_CUST_ID,
ACCT_NUM,
COMM_TP_CD,
CONSM_PRD_TREATMNT_CD,
DLQNT_DAY_CNT,
DLQNT_MTH_CNT,
LAND_RGSTRN_ACT_STAT_F,
OS_BAL_AMT,
PIT_STAT_VER_1_CD,
STEP_F,
TRNST_EXCLSN_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_MORT_ACCT_DRVD_VARS
;

CREATE
VIEW EDRTLRIFRS9.BASEL_MORT_MTH_SNAPSHOT
AS SELECT
BASEL_MORT_MTH_SNAPSHOT_ID,
MTH_TM_ID,
STEP_PLN_SNAPSHOT_ID,
PRIM_BASEL_CUST_ID,
BASEL_ACCT_ID,
FLOAT_CD,
MORT_NUM,
PD_OFF_F,
FRCLSR_F,
MTH_IN_ARRS_CNT,
INSUR_CL_CD,
PRPTY_CD,
FUND_CD,
INTR_ADJ_DT,
CRNT_BAL_AMT,
SERV_BR_TRNST_NUM,
SERV_BR_OU_ID,
PROC_BR_TRNST_NUM,
PROC_BR_OU_ID,
MORT_AUTH_DT,
PD_OFF_DT,
CRNT_TERM_MAT_DT,
LAST_RNEW_DT,
AUTH_AMT,
INTR_DUE_AMT,
LND_VAL,
TAX_CRNT_BAL_AMT,
INTR_ACCR_AMT,
TOT_ADVNC_AMT,
BRWER_CD,
APRSD_LAST_BUILDING_VAL,
APRSD_LAND_VAL,
APRSD_LAST_LAND_VAL,
APRSD_BUILDING_VAL,
APRSD_ORIG_LAND_VAL,
APRSD_ORIG_BUILDING_VAL,
FINAL_ADVNC_DT,
LIFE_INSUR_CD,
WK_FRST_UNPAID_DT,
BUS_SRC_CD,
SCRTY_TP_2,
FRST_UNPAID_DT,
MONTREAL_TRUST_DSBLTY_STAT_CD,
SALE_DT_VAL,
MRKTING_1_CD,
MRKTING_2_CD,
MRKTING_3_CD,
MRKTING_4_CD,
MRKTING_5_CD,
CRI_CD,
ARI_CD,
PVSN_AMT,
SCOTIA_TOT_EQTY_PLN_F,
LOAN_AUTH_DT,
HLTH_CRSIS_PRTCTN_INSUR_STAT_CD,
TOT_SUSP_BAL_AMT,
ACCT_TP_CD,
PRPTY_PROV_CD,
RENEWED_DT,
MORT_TERM_MTH,
MAX_INTR_RT,
YR_5_MTH_6_F,
PRIM_CUST_CID,
STEP_PLN_AGRMNT_NUM,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP,
YTD_PRPY_AMT,
AMORT_MTH,
PRPTY_ADDR,
GL_ACCT_NUM,
GL_TRNST_NUM,
PRD_GRP_CD,
UNIT_CNT,
COMM_TP
FROM
EDRTLRP1D.BASEL_MORT_MTH_SNAPSHOT

;	


CREATE
VIEW EDRTLRIFRS9.BASEL_PNL_LN_PD_SEG_ACCT_XREF
 AS SELECT
BASEL_ACCT_ID,
MTH_TM_ID,
BASEL_SEG_ID,
BASEL_MODEL_REL_ID,
BASEL_MODEL_ID,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_PNL_LN_PD_SEG_ACCT_XREF
;	
		

CREATE
VIEW EDRTLRIFRS9.BASEL_PSNL_LOAN_ACCT_DRVD_VARS
 AS SELECT
MTH_TM_ID,
BASEL_ACCT_ID,
BASEL_CUST_ID,
ACCT_NUM,
CONSM_PRD_TREATMNT_CD,
OS_BAL_AMT,
PIT_STAT_VER_1_CD,
STEP_F,
TRNST_EXCLSN_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_PSNL_LOAN_ACCT_DRVD_VARS
;	

CREATE
VIEW EDRTLRIFRS9.BASEL_PSNL_LOAN_MTH_SNAPSHOT
 AS SELECT
BASEL_PSNL_LOAN_MTH_SNAPSHOT_ID,
MTH_TM_ID,
BASEL_ACCT_ID,
PRIM_BASEL_CUST_ID,
STEP_PLN_SNAPSHOT_ID,
TRNST_NUM,
TRNST_OU_ID,
LOAN_NUM,
RECD_STAT_CD,
RECD_STAT_DT,
RSDNC_CD,
LOAN_SRC_CD,
PRPS_CD,
SCRTY_CD,
RT_CD,
PROMISSORS_CNT,
GRNT_CNT,
COMM_LOAN_CD,
NOTE_DT,
FRST_PAY_DT,
LAST_RGL_PAY_DT,
ORIG_LOAN_AMT,
ADD_ON_BAL_AMT,
ADD_ON_INTR_AMT,
DAY_ODUE,
ACCR_INTR,
EARLY_MAT_DT,
LAST_PYMT_DT,
TOT_CRNT_BAL_AMT,
MOTOR_VEHCL_VAL,
HH_VAL,
LOAN_VAL_OTH,
CRNT_BR_LOCTN_OU_ID,
CR_SCORE,
CRNT_BR_LOCTN_TRNST,
EARNED_MTH_INTR,
LOAN_ORIG_NOTE_DT,
CHRG_OFF_DT,
CHRG_OFF_AMT,
SECRTZTN_CD,
LOAN_TERM,
EARLY_MAT_TERM,
EARLY_MAT_STAT_CD,
RGL_PYMT_AMT,
PYMT_FREQ_CD,
INTR_RT,
CIF_COMPANY_ID,
CIF_CUST_ID,
CIF_TIE_BREAKER,
STEP_PLN_AGRMNT_NUM,
CUST_CID,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP,
BOOKED_AMT,
GL_ACCT_NUM,
GL_TRNST_NUM,
CRNCY_CD
FROM
EDRTLRP1D.BASEL_PSNL_LOAN_MTH_SNAPSHOT
;	


CREATE
VIEW EDRTLRIFRS9.BASEL_REVLVNG_CR_MTH_SNAPSHOT
AS SELECT
REVLVNG_CR_BASEL_MTH_SNAPSHOT_ID,
MTH_TM_ID,
BASEL_ACCT_ID,
PRIM_BASEL_CUST_ID,
STEP_PLN_SNAPSHOT_ID,
ACCT_NUM,
TRNST_OU_ID,
SUB_PRD_CD,
TRNST_NUM,
PRD_CD,
CORP_RTL_F,
BLOCK_RECL_CD,
ACCT_STAT_CD,
ACCT_OPND_DT,
SRC_CD,
FINAL_CR_SCORE,
LAST_PRCH_DT,
LAST_ACTY_DT,
CR_LMT_AMT,
CRNT_BILL_CD,
MTH_DLQNT_CNT,
DLQNT_HIST_13_24,
DLQNT_HIST_1_12,
ORIG_CHRG_OFF_AMT,
CHRG_OFF_DT,
CHRG_OFF_CD,
LAST_PYMT_DT,
LAST_PYMT_AMT,
PRCH_CRNT_CYCL_BAL_AMT,
PRCH_1_CYCL_AGO_BAL_AMT,
PRCH_2_CYCL_AGO_BAL_AMT,
CSH_ADVNC_CRNT_CYCL_BAL_AMT,
CSH_ADVNC_1_CYCL_AGO_BAL_AMT,
CSH_ADVNC_2_CYCL_AGO_BAL_AMT,
TOT_NEW_BAL_AMT,
TOT_UNPAID_FNCL_CHRG_AMT,
RISK_BAL_RTO,
FRST_USE_DT,
CR_SCORE,
NON_ACCRL_DT,
WRITE_OFF_DT,
ACCT_CLS_RSN_CD,
BNS_DLQNT_DAY,
LAST_BLOCKED_DT,
TOT_CYCL_TO_DT_FNCL_CHRG_AMT,
PROC_TP_CD,
SCRD_TP_CD,
VISA_PLASTIC_OUT,
YTD_PRCHS_CNT,
YTD_PRCHS_INTR_CHRGD_AMT,
YTD_PRCHS_INTR_PD_AMT,
YTD_CSH_ADVNC_INTR_CHRGD_AMT,
YTD_CSH_ADVNC_INTR_PD,
TOT_RCVRY_INTR_AMT,
SWITCH_CD,
NEXT_RNEW_FEE_DT,
SWITCH_XREF,
SWITCH_DT,
CHIP_F,
CMPGN_STAT_CD,
CMPGN_NOTIFIED_CD,
COLCTN_CTR_CD,
SETP_TRNST_NUM,
SUB_PRD_TFR_DT,
PRCH_RCVRY_INTR_AMT,
CSH_ADVNC_RCVRY_INTR_AMT,
LAST_YR_CR_INTR_PD_AMT,
TOT_YTD_CR_INTR_PD_AMT,
NON_RESPONDER_F,
RTN_ENVELOPE,
INACT_CD,
PAD_OTH_FNCL_INST_F,
SCRTY_TP_CD,
ANUL_FEE_CD,
FNCL_YTD_PRCHS_AMT,
FNCL_YTD_RTRNS_AMT,
DIVDD_RBT_LAST_YR_AMT,
MDL_COMPACTION,
MDL_CITIFONE,
MDL_CD_3,
MDL_CD_4,
LAST_ONLINE_UPDT_DT,
OPRTR_LAST_ONLINE_UPDT,
SOLCTN_CD,
SCRTY_VAL_AMT,
LAST_ADDR_CHNG_DT,
BAL_HIST_PRCHS_AMT,
BAL_HIST_CSH_ADV_AMT,
BAL_HIST_PYMTS_AMT,
ANUL_FEE_LNK_F,
FULL_PYMT_CD,
PREV_SUB_PRD_CD,
REQST_CR_LMT_AMT,
SPSP_CCLI,
PRIM_CUST_CID,
STEP_PLN_AGRMNT_NUM,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP,
GL_ACCT_NUM,
GL_TRNST_NUM,
CRNCY_CD
FROM
EDRTLRP1D.BASEL_REVLVNG_CR_MTH_SNAPSHOT
;


CREATE
VIEW EDRTLRIFRS9.BASEL_STEP_PLN_BASE_DRVD_VARS
AS SELECT
MTH_TM_ID,
BASEL_STEP_PLN_SNAPSHOT_ID,
PRPTY_ADDR,
DRVD_POST_ADDR_SUBSTRING,
LOCTN_LABEL_1,
LOCTN_LABEL_2,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_STEP_PLN_BASE_DRVD_VARS
;	

CREATE
VIEW EDRTLRIFRS9.BASEL_STEP_PLN_MTH_SNAPSHOT
AS SELECT
STEP_PLN_SNAPSHOT_ID,
MTH_TM_ID,
PRIM_BASEL_CUST_ID,
STEP_PLN_AGRMNT_NUM,
BR_LOCTN_TRNST,
BR_LOCTN_OU_ID,
ST_DT,
ACTY_DT,
PRPTY_DESC_1,
PRPTY_DESC_2,
PRPTY_DESC_3,
PRPTY_PROV_CD,
APRSD_VAL,
APRSD_DT,
RGSTRD_AMT,
RGSTRD_DT,
RGSTRD_NUM,
CR_LMT_AMT,
CR_LMT_DT,
CR_APP_NUM,
DISCHARGE_RSN_CD,
ACCT_CNT,
CRFC_NUM,
INSURER_CD,
HR_ST_DT,
REV_PRD,
HR_END_DT,
PREM_AMT,
APP_FEE,
AUTH_DT,
PRIM_CUST_CID,
AUTO_LMT_F,
ALI_DT,
ALI_PRD_CD,
ALI_ACCT_NUM,
CTI_F,
CTI_DT,
ALI_PNDG_AMT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BASEL_STEP_PLN_MTH_SNAPSHOT
;	

CREATE
VIEW EDRTLRIFRS9.BLOCK_RECL_CLS_RSN_LKP
AS SELECT
BLOCK_RECL_CD,
CLS_RSN_CD,
EFF_FROM_YR_MTH,
EFF_TO_YR_MTH,
CONSM_SCORECRD_EXCLSN_F,
CRNT_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BLOCK_RECL_CLS_RSN_LKP
;

CREATE
VIEW EDRTLRIFRS9.BLOCK_RECL_LKP
 AS SELECT
BLOCK_RECL_CD,
EFF_FROM_YR_MTH,
EFF_TO_YR_MTH,
BNKRPY_F,
BNKRPY_F_DESC,
BLOCK_RECL_DESC,
CONSM_SCORECRD_EXCLSN_F,
CRNT_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.BLOCK_RECL_LKP
;

CREATE
VIEW EDRTLRIFRS9.CHRG_OFF_LKP
AS SELECT
CHRG_OFF_CD,
EFF_FROM_YR_MTH,
EFF_TO_YR_MTH,
CHRG_OFF_STAT_F,
CHRG_OFF_STAT_DESC,
ACCRL_STAT_F,
ACCRL_STAT_DESC,
CRNT_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.CHRG_OFF_LKP
;	

CREATE
VIEW EDRTLRIFRS9.CR_BUREAU_DELI_MTH_SNAPSHOT
AS SELECT
MTH_TM_ID,
BASEL_CUST_ID,
CUST_CID,
CIF_KEY,
HIT_NOHIT_EDIT_REJCT_CD,
FICO_08_SCORE,
FICO_08_EXCLSN_CD,
FICO_08_FACTR_CD_1,
FICO_08_FACTR_CD_2,
FICO_08_FACTR_CD_3,
FICO_08_FACTR_CD_4,
ACTV_TRDS_CNT,
TOT_BAL_ALL_TRADE_AMT,
TOT_HCCL_ALL_TRADE_AMT,
TRADE_OPND_IN_PAST_6_MTH_CNT,
MTH_SINCE_OLDST_TRADE_OPND_CNT,
MTH_SINCE_MOST_RECNT_TRADE_OPND_CNT,
TOT_MTH_PYMT_AMT,
HIGHST_ACTV_HCCL_AMT,
TRDS_REVLVNG_CNT,
TOT_HCCL_REVLVNG_AMT,
TOT_BAL_REVLVNG_AMT,
TRADE_BNK_REVLVNG_CNT,
TOT_HCCL_BNK_REVLVNG_AMT,
TOT_BAL_BNK_REVLVNG_AMT,
SATFCTRY_TRADE_CNT,
TRADE_WORST_EVER_30_DAY_PD_CNT,
MTH_SINCE_LAST_30_DAY_DLQNT_CNT,
TRADE_WORST_EVER_60_DAY_PD_CNT,
MTH_SINCE_LAST_60_DAY_DLQNT_CNT,
TRADE_WORST_EVER_90_DAY_PD_CNT,
MTH_SINCE_LAST_90_DAY_DLQNT_CNT,
CR_BUREAU_WORST_RT_F,
MTH_SINCE_CR_BUREAU_WORST_RT_CNT,
DERGTRY_PUB_RECD_CNT,
BNKRPY_CNT,
MOST_RECNT_BANKRUPCY_DISCHARGE_DT,
MOST_RECNT_BANKRUPCY_RPTD_DT,
BNKRPY_NARRTV_CD,
COLCTN_CNT,
ORIG_COLCTN_AMT,
TOT_COLCTN_BAL_AMT,
COLCTN_INQR_CNT,
LEGAL_CNT,
TOT_ORIG_LEGAL_AMT,
TRADE_TP_BANKCARD_CNT,
TOT_HCCL_TP_BANKCARD_AMT,
TOT_BAL_TP_BANKCARD_AMT,
TOT_TRADE_CNT,
TRADE_NEVER_DLQNT_PC,
ACTV_TRADE_WITH_AMT_PD_CNT,
TOT_PD_AMT,
TOT_UTLTN_AMT,
HIGHST_ACTV_UTLTN,
TOT_AVL_CR_NOT_UTILIZED_AMT,
TOT_UTLTN_BNK_REVLVNG_CRD_AMT,
TOT_BAL_BNK_REVLVNG_LINES_AMT,
MTH_SINCE_MOST_RECNT_DLQNT_CNT,
TRADE_WORST_EVER_90_DAY_DLQNT_CNT,
NOT_SUFFICENT_FUNDS_CHQ_CNT,
TOT_COMPTV_RTO,
TOT_COMPTV_CRD_RTO,
TOT_COMPTV_LINE_RTO,
MAX_REVLVNG_CR_CRNT_UTLTN_AMT,
INQRY_CNT,
INQRY_PAST_6_MTH_CNT,
TRADE_FNCL_REVLVNG_CNT,
TOT_HCCL_FNCL_REVLVNG_AMT,
TOT_BAL_FNCL_REVLVNG_AMT,
TRADE_INSTLMNT_CNT,
TOT_HCCL_INSTLMNT_AMT,
TOT_BAL_INSTLMNT_AMT,
TRADE_BNK_INSTLMNT_CNT,
TOT_HCCL_BNK_INSTLMNT_AMT,
TOT_BAL_BNK_INSTLMNT_AMT,
TRDS_FNCL_INSTLMNT_CNT,
TOT_HCCL_FNCL_INSTLMNT_AMT,
TOT_BAL_FNCL_INSTLMNT_AMT,
TRADE_RTL_REVLVNG_CNT,
TOT_BAL_RTL_REVLVNG_AMT,
TRADE_OPND_PAST_3_MTH_CNT,
OCC_60_DAY_PD_WITHIN_PAST_12_MTH_CNT,
TRADE_OPND_PAST_12_MTH_WITH_BAL_GT_ZERO_CNT,
SATFCTRY_TRADE_GT_3_MTH_CNT,
ACTV_INSTLMNT_TRDS_BAL_GT_ZERO_CNT,
TRADE_ZERO_BAL_CNT,
TM_30_DAY_PD_LAST_12_MTH_CNT,
TM_60_DAY_PD_LAST_12_MTH_CNT,
TM_OV_90_DAY_PD_LAST_12_MTH_CNT,
TM_60_DAY_PD_EVER_CNT,
TM_90_DAY_PD_EVER_CNT,
HIGHST_BAL_OS_AMT,
ACTV_TRADE_30_DAY_RT_CNT,
ACTV_TRADE_60_DAY_RT_CNT,
ACTV_TRADE_OV_90_RT_CNT,
TRADE_90_DPD_LAST_24_MTH_CNT,
OPN_TRADE_CNT,
OLDST_OPN_TRADE_AGE_LINE_MTH_CNT,
TOT_BAL_MORT_TRADE_AMT,
TOT_BAL_ALL_TRADE_EXCLD_MORT_AMT,
MTH_SINCE_LAST_ACTY_CNT,
CUST_BRTH_DT,
POTNTL_FRAUD_VICTIM_F,
HOME_PH_NUM_FRAUD_REMRK_AREA,
TRANSUNION_RISK_SCORE,
TRANSUNION_RISK_SCORE_EXCLSN_CD,
TRANSUNION_SCORE_FACTR_CD_1,
TRANSUNION_SCORE_FACTR_CD_2,
TRANSUNION_SCORE_FACTR_CD_3,
TRANSUNION_SCORE_FACTR_CD_4,
SRC_APP_CD,
SCORE_LAST_RECVD_DT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP,
TOT_UTLTN_BNK_REVLVNG_LINE_AMT
FROM
EDRTLRP1D.CR_BUREAU_DELI_MTH_SNAPSHOT
;		

CREATE
VIEW EDRTLRIFRS9.DLQNT_DIM
AS SELECT
DLQNT_ID,
KS_MIN_DAY_DLQNT,
MIN_DAY_DLQNT,
KS_MAX_DAY_DLQNT,
MAX_DAY_DLQNT,
DLQNT_CYCL_CD,
DLQNT_CYCL_DESC,
NCR_DLQNT_CD,
NCR_DLQNT_DESC,
EFF_FROM_DT,
EFF_TO_DT,
CRNT_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.DLQNT_DIM
;


CREATE
VIEW EDRTLRIFRS9.MBR_INDRCT_COST_MTH_SNAPSHOT
AS SELECT
MBR_INDRCT_COST_SNAPSHOT_ID,
MTH_TM_ID,
TRNST_NUM,
MISCELLANEOUS_OUTSOURCE_FEE_AMT,
TOT_NON_INTR_EXPNS_AMT,
TOT_INDRCT_COST_AMT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.MBR_INDRCT_COST_MTH_SNAPSHOT
;


CREATE
VIEW EDRTLRIFRS9.PROVNCL_HOUSE_INDEX_SUM
AS SELECT
MTH_TM_ID,
PROV_CD,
SLS_PAIR_ANLYS_CNT,
HOUSE_INDEX_RTO,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.PROVNCL_HOUSE_INDEX_SUM
;

CREATE
VIEW EDRTLRIFRS9.SRC_PRD_LKP
AS SELECT
PRD_SYS_CD,
SRC_PRD_CD,
SRC_SUB_PRD_CD,
EFF_FROM_YR_MTH,
EFF_TO_YR_MTH,
BASEL_PRD_CD,
BASEL_PRD_DESC,
PRD_DESC,
LTV_TP_CD,
SML_BUS_F,
CONSM_SCORECRD_EXCLSN_F,
CONSM_PRD_TREATMNT_CD,
CRNT_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.SRC_PRD_LKP

;

CREATE
VIEW EDRTLRIFRS9.SRC_PRD_STDNT_LOAN_LKP
AS SELECT
PRD_SYS_CD,
SRC_PRD_CD,
SRC_SUB_PRD_CD,
EFF_FROM_YR_MTH,
BILL_CD_CHAR,
EFF_TO_YR_MTH,
BASEL_PRD_CD,
BASEL_PRD_DESC,
PRD_DESC,
LTV_TP_CD,
SML_BUS_F,
CONSM_SCORECRD_EXCLSN_F,
CONSM_PRD_TREATMNT_CD,
CRNT_F,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.SRC_PRD_STDNT_LOAN_LKP
;

CREATE
VIEW EDRTLRIFRS9.TERANET_HOUSE_PRC_INDEX
AS SELECT
MTH_TM_ID,
LABEL_1,
LABEL_2,
TXN_DT,
PUBLCT_DT,
INDEX,
SLS_PAIR_CNT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.TERANET_HOUSE_PRC_INDEX
;

CREATE
VIEW EDRTLRIFRS9.TM_DIM
AS SELECT
TM_ID,
TM_LVL,
TM_SEQ_NUM,
TM_YR_SEQ_NUM,
TM_CRNT_F,
CLNDR_YR,
FNCL_YR,
CLNDR_QTR_CD,
FNCL_QTR_CD,
MTH_CLNDR_CD,
DAY_OF_WK_CD,
DAY_OF_WK_DESC,
DAY_DT,
ANUL_FNCL_KEY,
FNCL_QTR_KEY,
FNCL_MTH_KEY,
FNCL_DAY_KEY,
TM_DESC,
TM_LVL_ST_DT,
TM_LVL_END_DT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.TM_DIM
;

CREATE
VIEW EDRTLRIFRS9.TRNST_EXCLSN_LKP
AS SELECT
EXCLUDED_TRNST_NUM,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.TRNST_EXCLSN_LKP
;

CREATE
    VIEW EDRTLRIFRS9.BASEL_PSNL_LN_INST_FACT_IFRS_V AS SELECT
        MTH_TM_ID,
        SRC_SYS_CD,
        BASEL_ACCT_ID,
        UNQ_ACCT_ID,
        NCR_RT_SYS_KEY_VAL,
        NCR_PD_BAND_KEY_VAL,
        NCR_EXPSR_SIZE_KEY_VAL,
        NCR_GEO_KEY_VAL,
        NCR_LTV_KEY_VAL,
        NCR_EXPSR_CL_KEY_VAL,
        NCR_RT_KEY_VAL,
        NCR_DLQNT_BCKT_KEY_VAL,
        PIT_STAT_CD,
        UTLTN_RTO,
        ACCT_ODT,
        TRNST_NUM,
        CR_LMT_AMT,
        ADVNC_AMT,
        AUTH_AMT,
        OS_BAL_AMT,
        GENL_LEDGER_BALCNG_ADJ_AMT,
        ADJUSTED_OS_BAL_AMT,
        UNADJUSTED_ADD_ON_BAL_AMT,
        AF_SECRTZTN_BAL_AMT,
        DLQNT_DAY_CNT,
        BEFORE_ZERO_NET_UNDRAWN_AMT,
        BEFORE_ZERO_NET_DRAWN_AMT,
        ORIG_PRPTY_VAL_AMT,
        LOAN_TO_VAL_RTO,
        INDEXED_PRPTY_VAL_AMT,
        INDEXED_LOAN_TO_VAL_RTO,
        PD_MODEL_NM,
        PD_MODEL_VER,
        PD_BASEL_SCORECRD_NM,
        PD_SCORECRD_VER,
        PD_BASEL_SEG_NUM,
        PD_BASEL_SEG_ID,
        PD_SEG_VER,
        PD_BASEL_MODEL_REL_ID,
        PD_MODEL_RTO,
        PD_LR_RPTG_RTO,
        PD_LR_PV_RPTG_RTO,
        PD_LR_PV_AD_RPTG_RTO,
        PD_LD_PV_AD_SV_RPTG_RTO,
        PD_ACCT_SCORE,
        PD_FINAL_RPTG_RTO,
        LGD_MODEL_NM,
        LGD_MODEL_VER,
        LGD_BASEL_SCORECRD_NM,
        LGD_SCORECRD_VER,
        LGD_BASEL_SEG_NUM,
        LGD_BASEL_SEG_ID,
        LGD_SEG_VER,
        LGD_BASEL_MODEL_REL_ID,
        LGD_MODEL_RTO,
        LGD_LR_RPTG_RTO,
        LGD_LR_PV_RPTG_RTO,
        LGD_LR_PV_AD_RPTG_RTO,
        LGD_LD_PV_AD_SV_RPTG_RTO,
        LGD_ACCT_SCORE,
        LGD_LD_PV_AD_SV_DT_RPTG_RTO,
        EAD_MODEL_NM,
        EAD_MODEL_VER,
        LGD_FINAL_RPTG_RTO,
        EAD_BASEL_SCORECRD_NM,
        EAD_SCORECRD_VER,
        EAD_BASEL_SEG_NUM,
        EAD_BASEL_SEG_ID,
        EAD_SEG_VER,
        EAD_BASEL_MODEL_REL_ID,
        EAD_MODEL_RTO,
        EAD_LR_RPTG_RTO,
        EAD_LR_PV_RPTG_RTO,
        EAD_ACCT_SCORE,
        EAD_LR_PV_AD_RPTG_RTO,
        ASST_CL_DESC,
        CONS_DFT_MTH_CNT,
        EAD_LD_PV_AD_SV_RPTG_RTO,
        EAD_LD_PV_AD_SV_DT_RPTG_RTO,
        BCAR_SCHED_NUM,
        EAD_FINAL_RPTG_RTO,
        PD_BAND,
        BASEL_PRD_ABR,
        SCRTY_TP_DESC,
        CCAR_BASEL_PRD_TP_NM,
        CCAR_EXPSR_CL_NM,
        BASEL_PRD_TP_CD,
        CONSM_PRD_TREATMNT_CD,
        PRD_ID,
        PRIM_CUST_CID,
        ACCT_NUM,
        RGNL_OFFC_CD,
        DLQNT_STG,
        MORT_NUM,
        CAB_TRNST_NUM,
        EGL_DEPRTMNT,
        BASEL_CIF_KEY,
        LOAN_NUM,
        INTR_ACCR_AMT,
        CUST_BEHV_SCORE,
        PRD_CD,
        SUB_PRD_CD,
        SRC_PRD_DESC,
        LEGAL_ENTITY,
        MAT_DT,
        LAST_PYMT_DT,
        SCRTY_TP_CD,
        STEP_F,
        LAST_ACTY_DT,
        HOUSE_TP_NM,
        LAST_RGL_PAY_DT,
        PD_OFF_F,
        PD_OFF_DT,
        RESIDUAL_MAT,
        ASST_CL_NUM,
        E_MAT_DT,
        AMORT,
        TRNST_EXCLSN_F,
        SML_BUS_F,
        NOTE_DT,
        INSRT_PROCESS_TMSTMP,
        UPDT_PROCESS_TMSTMP,
        AF_ZERO_NET_DRAWN_AMT,
        AF_ZERO_NET_UNDRAWN_AMT,
        PD_UNADJUSTED_RPTG_RTO,
        LGD_UNADJUSTED_RPTG_RTO,
        EAD_UNADJUSTED_RPTG_RTO,
        PD_LR_PV_AD_SV_DT_AA_RTO,
        LGD_LR_PV_AD_SV_DT_AA_RTO,
        EAD_LR_PV_AD_SV_DT_AA_RTO,
        INSUR_F,
        OS_PRNCPL_BAL_AMT,
        PREV_12_QTR_PRPTY_VAL_AMT,
        DLGD_F,
        CRNT_LTV_RTO,
        METRPL_AREA_NM,
        PRPTY_VAL_CORR_PCTG,
        LNG_RUN_LGD_ADD_ON_RTO,
        DLGD_RPTG_RTO
    FROM
        EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT;
		
		
	
	CREATE
    VIEW EDRTLRIFRS9.BASEL_PNL_PD_SEG_XREF_IFRS_V AS SELECT
        BASEL_ACCT_ID,
        MTH_TM_ID,
        BASEL_SEG_ID,
        BASEL_MODEL_REL_ID,
        BASEL_MODEL_ID,
        INSRT_PROCESS_TMSTMP,
        UPDT_PROCESS_TMSTMP
    FROM
        EDRTLRP1D.BASEL_PNL_LN_PD_SEG_ACCT_XREF;
		
	CREATE
    VIEW EDRTLRIFRS9.BASEL_SEG_IFRS_V AS SELECT
        BASEL_SEG_ID,
        BASEL_MODEL_ID,
        BASEL_SEG_NM,
        BASEL_SEG_DESC,
        SEG_CRTRIA_DESC,
        SEG_NUM,
        SEG_VER,
        SEG_ST_DT,
        SEG_END_DT,
        BIN_CRTRIA_SQL_CD_STRG,
        SRC_SYS_CD,
        INSRT_PROCESS_TMSTMP,
        UPDT_PROCESS_TMSTMP
    FROM
        EDRTLRIFRS9.BASEL_SEG;
		
		

		
		CREATE
    VIEW EDRTLRIFRS9.LGD_SEG_ACCT_XREF_IFRS_V AS SELECT
        BASEL_ACCT_ID,
        MTH_TM_ID,
        BASEL_SEG_ID,
        BASEL_MODEL_REL_ID,
        BASEL_MODEL_ID,
        INSRT_PROCESS_TMSTMP,
        UPDT_PROCESS_TMSTMP
    FROM
        EDRTLRIFRS9.LGD_SEG_ACCT_XREF;
		
CREATE
    VIEW EDRTLRIFRS9.PD_SEG_ACCT_XREF_IFRS_V AS SELECT
        BASEL_ACCT_ID,
        MTH_TM_ID,
        BASEL_SEG_ID,
        BASEL_MODEL_REL_ID,
        BASEL_MODEL_ID,
        INSRT_PROCESS_TMSTMP,
        UPDT_PROCESS_TMSTMP
    FROM
        EDRTLRIFRS9.PD_SEG_ACCT_XREF;


CREATE
    VIEW EDRTLRIFRS9.TNG_LGDD_SEGMENTATION_IFRS_V AS SELECT
        ACCOUNT_ID,
        MONTH_END_DT,
        "RECOVERY",
        INDIRECT_COST,
        FINAL_COST,
        LGD,
        LGD_COSTS,
        LGD_COSTS_CAP_100,
        LGD_COSTS_CAP_150,
        ACCRUED_INTEREST_AMT,
        END_PRINCIPAL_BALANCE,
        MONTHS_IN_DEFAULT,
        CLOSE_DT,
        LTV_TERANET,
        INS_ID_GROUP,
        BALANCE_INTEREST,
        EXCL,
        LGDD_SEGMENT,
        LGD_BKUP,
        LGD_COSTS_BKUP,
        LGD_COSTS_CAP_100_BKUP,
        LGD_COSTS_CAP_150_BKUP
    FROM
        FRG_USER_DATA.TNG_LGDD_SEGMENTATION;
		
CREATE
    VIEW EDRTLRIFRS9.TNG_LGD_ND_SEGMENTATION_IFRS_V AS SELECT
        ACCOUNT_ID,
        MONTH_END_DT,
        END_PRINCIPAL_BALANCE,
        DEFAULT_IND,
        CLOSE_DT,
        NEW_DEF_IND,
        NEW_DEFAULT_IND,
        WRITE_OFF_MONTH,
        WRITE_OFF_IND,
        WRITE_OFF_AMT,
        FINAL_DEFAULT_IND,
        TRADES_STSFCT_CNTSLP6M,
        TRADES_ACTIVE_UTIL_PCTMAX12M,
        DEROGATORY_PUBLIC_REC_CNT,
        COLLECTIONS_CNT,
        BANKRUPTCIES_CNT,
        CREDIT_TRBLE_BNKRPTCY_COLL_DER,
        INS_ID_GROUP,
        DAYS_ARREARS_CNT,
        NSF_YTD_CNT,
        EVER_30_CNT,
        REMAIN_AMORT2,
        PROP_VAL_NEW,
        LTV_TERANET,
        PROVIDER,
        MODEL_EXCL,
        SEGMENT
    FROM
        FRG_USER_DATA.TNG_LGD_ND_SEGMENTATION;


CREATE
    VIEW EDRTLRIFRS9.TNG_PD_SEGM_FINAL_IFRS_V AS SELECT
        ACCOUNT_ID,
        MONTH_END_DT,
        END_PRINCIPAL_BALANCE,
        DEFAULT_IND,
        CLOSE_DT,
        NEW_DEF_IND,
        NEW_DEFAULT_IND,
        WRITE_OFF_MONTH,
        WRITE_OFF_IND,
        WRITE_OFF_AMT,
        FINAL_DEFAULT_IND,
        TRADES_STSFCT_CNTSLP6M,
        TRADES_ACTIVE_UTIL_PCTMAX12M,
        DEROGATORY_PUBLIC_REC_CNT,
        COLLECTIONS_CNT,
        BANKRUPTCIES_CNT,
        CREDIT_TRBLE_BNKRPTCY_COLL_DER,
        INS_ID_GROUP,
        DAYS_ARREARS_CNT,
        NSF_YTD_CNT,
        EVER_30_CNT,
        REMAIN_AMORT2,
        PROP_VAL_NEW,
        LTV_TERANET,
        MODEL_EXCL,
        SCORECARD_POINTS,
        SCR_DAYS_ARREARS_CNT,
        SCR_EVER_30_CNT,
        SCR_LTV_TERANET,
        SCR_NSF_YTD_CNT,
        SCR_TRADES_ACTIVE_UTIL_PCTMAX12M,
        SCR_TRADES_STSFCT_CNTSLP6M,
        SCR_REMAIN_AMORT2,
        SCR_CREDIT_TRBLE_BNKRPTCY_COLL_D,
        SCR_INS_ID_GROUP,
        PD_SEGMENT,
        SEGMENT
    FROM
        FRG_USER_DATA.TNG_PD_SEGMENTATION_FINAL;

CREATE
    VIEW EDRTLRIFRS9.BASEL_PNL_LN_LGD_SEG_ACCT_XREF
 AS SELECT
        BASEL_ACCT_ID,
MTH_TM_ID,
BASEL_SEG_ID,
BASEL_MODEL_REL_ID,
BASEL_MODEL_ID,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
    FROM
        EDRTLRP1D.BASEL_PNL_LN_LGD_SEG_ACCT_XREF;
		
CREATE
VIEW EDRTLRIFRS9.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2
AS SELECT
BASEL_ACCT_ID,
MTH_TM_ID,
PIT_STATUS_V2,
PROCESS_DT,
LOAN_NUM,
CAB,
SUB_PORTFL,
COMM_F_V2,
IND_BAL_EXCL,
IND_HL_EXCL,
IND_CAB_EXCL,
IND_24MOS_EXCL,
MODEL_EXCL_F,
TREATMNT_F,
BASEL_CUST_ID,
PRD_TP,
PRD,
CONS_DFT_MTH_CNT,
SUB_PRODUCT,
PRD_ID,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP,
OS_BAL_AMT_V2
FROM
EDRTLRP1D.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2
;

CREATE
VIEW EDRTLRIFRS9.IFRS9_PROV_LKP
AS SELECT
PROVINCE_NAME,
PROV_CD,
INSRT_PROCESS_TMSTMP
FROM
EDRTLRP1D.IFRS9_PROV_LKP;

CREATE
VIEW EDRTLRIFRS9.ORG_UNIT_DIM
AS SELECT
ORG_UNIT_ID,
ORG_UNIT_LVL,
TRNST_NUM,
ORG_UNIT_NM,
CITY,
CLS_DT,
OPN_DT,
PH_NUM,
POSTAL_ZIP_CD,
PROV_STATE,
STRT_ADDR,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM
EDRTLRP1D.ORG_UNIT_DIM
;

CREATE
VIEW EDRTLRIFRS9.BASE_BNS_MOR_RPT_TBL
AS SELECT
MORTGAGE_NO,
PROCESS_DATE,
MTH_TM_ID,
HOUSE_TP_NM,
OS_BAL_AMT,
INTR_ACCR_AMT,
PD_OFF_DT,
PD_OFF_F,
PIT_STAT_CD,
BULK_IND,
INSURANCE,
FORECLOSE_IND,
TOTAL_SUSPENSE,
CURRENT_BAL,
PAID_OFF_IND,
TOTAL_BAL,
TOTAL_BAL_FOR_LTV,
SRC_SYS_CD,
NCR_RT_SYS_KEY_VAL,
UTLTN_RTO,
CR_LMT_AMT,
UNADJUSTED_ADD_ON_BAL_AMT,
EAD_ACCT_SCORE,
CUST_BEHV_SCORE,
ACCT_NUM,
LOAN_NUM,
PRD_CD,
SUB_PRD_CD,
LAST_PYMT_DT,
SCRTY_TP_CD,
LAST_ACTY_DT,
E_MAT_DT,
NOTE_DT,
LAST_RGL_PAY_DT,
SML_BUS_F,
BASEL_ACCT_ID,
PD_MODEL_VER,
PD_MODEL_NM,
PD_BASEL_SCORECRD_NM,
PD_SCORECRD_VER,
PD_SEG_VER,
PD_BASEL_SEG_ID,
PD_BASEL_MODEL_REL_ID,
PD_MODEL_RTO,
BASE_DEF_SEG,
EAD_MODEL_NM,
EAD_MODEL_VER,
EAD_BASEL_SCORECRD_NM,
EAD_SCORECRD_VER,
EAD_BASEL_SEG_NUM,
EAD_SEG_VER,
EAD_BASEL_SEG_ID,
EAD_BASEL_MODEL_REL_ID,
EAD_MODEL_RTO,
EAD_LR_RPTG_RTO,
EAD_LR_PV_RPTG_RTO,
EAD_LR_PV_AD_RPTG_RTO,
EAD_LD_PV_AD_SV_RPTG_RTO,
EAD_LD_PV_AD_SV_DT_RPTG_RTO,
EAD_FINAL_RPTG_RTO,
EAD_UNADJUSTED_RPTG_RTO,
EAD_LR_PV_AD_SV_DT_AA_RTO,
AMORT,
AT36,
AT94,
CUST_ACCT_CNT,
DLQNT_DAY,
DLQNT_MTHMAX24M,
DLQNT_DAYAVG24M,
BI33MAX3M,
BR147MAX6M,
D2DBALMAX12M,
D2DBALPMIN6M,
GO04MAX6M,
NSF_NUMMAX6M,
PAYROLL_AMTMIN3M,
PREPAY_YTDMAX24M,
INDEX_TERANETV,
INDEXED_PRPTY_VAL_AMT,
LTV,
INDEXED_LOAN_TO_VAL_RTO,
RATIO,
URATE,
NCR_EXPSR_CL_KEY_VAL,
ASST_CL_DESC,
ASST_CL_NUM,
BCAR_SCHED_NUM,
BASEL_PRD_ABR,
SCRTY_TP_DESC,
BASEL_PRD_TP_CD,
PRD_ID,
SRC_PRD_DESC,
PD_BAND_EXPOSURE_CLASS_KEY_VALUE,
CCAR_BASEL_PRODUCT_TYPE_NAME,
LGD_MODEL_VER,
LGD_SCORECRD_VER,
LGD_SEG_VER,
LGD_BASEL_MODEL_REL_ID,
LGD_BASEL_SEG_ID,
LGD_MODEL_NM,
LGD_BASEL_SCORECRD_NM,
MONTH_DEF,
CONS_DFT_MTH_CNT,
LGD_MODEL_RTO,
PROVINCE_CD,
LOAN_TO_VAL_RTO
FROM
FRG_USER_DATA.BASE_BNS_MOR_RPT_TBL
;


CREATE
VIEW EDRTLRIFRS9.BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ
AS SELECT
MORTGAGE_NO,
TIME_KEY,
INSURANCE,
BULK_IND,
TOTAL_BAL,
TOTAL_SUSPENSE,
FORECLOSE_IND,
MONTH_DEF,
ACCT_LGD24_NOCOST,
ACCT_LGD24_NOCOST_CAP,
ACCT_LGD24_COST,
ACCT_LGD24_COST_CAP15,
RATIO,
URATE,
D2DBALMAX12M,
INDEX_TERANETV,
LTV,
SCORECARD_POINTS,
B_FORECLOSE_IND,
B_UNEMP_RATE_RATIO,
B_D2DBALMAX12M,
B_MONTH_DEF,
B_INDEX_TERANETV,
B_LTV,
SCORE_FORECLOSE_IND,
SCORE_UNEMP_RATIO,
SCORE_D2DBALMAX12M,
SCORE_MONTH_DEF,
SCORE_INDEX_TERANETV,
SCORE_LTV,
BNS_LGD_D_SEGMENT,
ACCT_LGD24_NOCOST_BKUP,
ACCT_LGD24_NOCOST_CAP_BKUP,
ACCT_LGD24_COST_BKUP,
ACCT_LGD24_COST_CAP15_BKUP
FROM
FRG_USER_DATA.BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ
;

CREATE
VIEW EDRTLRIFRS9.BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ
AS SELECT
MORTGAGE_NO,
TIME_KEY,
INSURANCE,
BULK_IND,
TOTAL_BAL,
LGD24D,
LGDC24D,
LGDC_CAP_100,
LGDC_CAP_150,
STATUS,
DEFAULT_IND,
AMORT,
BI33MAX3M,
DLQNT_DAYAVG24M,
LTV,
INDEX_TERANETV,
RATIO,
URATE,
PROVINCE_CD,
SCORECARD_POINTS,
B_LTV,
B_PROP_VALUE,
B_BI33MAX3M,
B_AMORT,
B_DLQNT_DAYAVG24M,
B_RATIO,
SB_AMORT,
SB_BI33MAX3M,
SB_DLQNT_DAYAVG24M,
SB_LTV,
SB_PROP_VALUE,
SB_RATIO,
BNS_LGD_ND_SEGMENT,
LGD24D_BKUP,
LGDC24D_BKUP,
LGDC_CAP_100_BKUP,
LGDC_CAP_150_BKUP,
LGD_CAP_150
FROM
FRG_USER_DATA.BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ;

CREATE
VIEW EDRTLRIFRS9.TNG_12MTH_DEFAULT
AS SELECT
ACCOUNT_ID,
MONTH_END_DT,
END_PRINCIPAL_BALANCE,
DEFAULT_IND,
CLOSE_DT,
NEW_DEF_IND,
NEW_DEFAULT_IND,
WRITE_OFF_MONTH,
WRITE_OFF_IND,
WRITE_OFF_AMT,
FINAL_DEFAULT_IND,
MONTH_END_DATE,
DATE,
DEF_IND,
FIRST_DEFAULTDATE,
FIRST_DEFAULTBAL,
FINAL_DEFAULTDATE,
FINAL_DEFAULTBAL
FROM
FRG_USER_DATA.TNG_12MTH_DEFAULT;

CREATE
VIEW EDRTLRIFRS9.mortgage_hist
AS SELECT
MORTGAGE_NO,
COMM_TYPE,
FLOAT_LKP_ID,
GENL_LKP_ID,
CURRENT_BAL,
DELQ_DAYS,
DELQ_MONTHS,
FLOAT_IND,
FORECLOSE_IND,
INT_ACCR_AMT,
LRA_STATUS,
PAID_OFF_DATE,
PAID_OFF_IND,
PROCESS_DATE,
TOTAL_SUSPENSE,
UNPD_MTH_PAY_DATE,
UNPD_WKL_PAY_DATE,
MADE_DATE,
TIME_KEY,
INT_ADJ_DATE,
YYMTH,
INSURANCE,
CLASS,
EFF_TMSTMP,
PRPTY_DESC_1,
PRPTY_DESC_2,
PRPTY_DESC_3,
LEND_VAL2,
TRNST,
AUTH_AMT,
MAT_DT,
CAB,
TOT_ADVNC_AMT,
PRIM_CUST_ID,
CIF_KEY,
STEP_F,
INSUR_GRP,
BULK_IND,
AMORT,
PREPAY_YTD,
PROVINCE
FROM
FRG_USER_DATA.mortgage_hist;



CREATE
VIEW EDRTLRIFRS9.TNG_ACCT_MO
AS SELECT
ACCOUNT_ID,
MONTH_START_DT,
MONTH_END_DT,
MATURITY_DT,
OPEN_DT,
COMMITTED_AMT,
INTEREST_ARREARS_AMT,
PRINCIPAL_ARREARS_AMT,
ESCROW_ARREARS_AMT,
TOT_ARREARS_AMT,
NOMINAL_INTEREST_RATE,
LOAN_TO_VALUE_RATIO,
REMAINING_TERM,
NON_PERFORMING_IND,
NON_ACCRUAL_IND,
DAYS_ARREARS_CNT,
PYMTS_ARREARS_CNT,
NSF_CNT,
NSF_YTD_CNT,
NSF_LIFE_CNT,
START_PRINCIPAL_BALANCE,
END_PRINCIPAL_BALANCE,
SUNDRY_BALANCE,
ESCROW_BALANCE,
TOT_ADVANCED_AMT,
REMAIN_AMORT,
ACCOUNT_KEY,
MTG_APPLICATION_KEY,
POOL_KEY,
CUSTOMER_KEY,
AMORT_MATURITY_DT,
LST_NSF_PYMT_RTN_DT,
LST_PAYMENT_DT,
NON_PERFM_DT,
LATEST_90_DT,
TOT_SCH_PYMT,
LST_KNWN_COVER_PCT,
EVER_ARREARS_CNT,
EVER_30_CNT,
EVER_60_CNT,
EVER_90_CNT,
DEFAULT_TYPE_CODE,
MTG_ORIGINATION_KEY,
TERM_DESC,
RATE_TYPE_DESC,
ACCELERATED_PMNT_IND,
ANNUAL_FACTOR,
MTG_PROVIDER_DESC,
PROPERTY_TYPE_DESC,
TENURE_DESC,
STATUS_DESC,
INSURER_DESC,
POOL_DESC,
PURPOSE_DESC,
OCCUPANCY_TYPE_DESC,
DWELLING_TYPE,
BIRTH_DT,
OCCUPATION_INDSTRY_CODE,
GENDER,
EARLY_RNWL_IND,
ORG_ADJ_BUREAU_SCR,
SUBMIT_DT,
ORG_GDSR,
ORG_TDSR,
FRST_PYMT_RTN_DT,
FIRST_90_DT,
GURNTR_IND,
ORG_LTV_RATIO,
AMORT_PERIOD,
ORG_ADVANCED_AMT,
DIRECT_IND,
FIRST_DEFAULT_DT,
FRST_ADVANCE_DT,
LOAN_TO_VALUE_AT_FIRST_DEFAULT,
LATEST_INTEREST_ADJUST_DT,
ADVANCE_EFF_DT,
PROP_CITY,
PROP_COUNTRY_CODE,
PROP_POSTAL_CODE,
PROP_PROVINCE_CODE,
LST_PROP_APPRAISAL_VAL,
FSA,
LST_PROP_APPRAISAL_DT,
LIEN_PRIORITY_NUM,
PROP_BUILDING_TYPE,
ORG_COVER_EXEC_VAL,
PROP_USAGE_TYPE,
SECURITY_OWNER_TYPE,
SECURITY_PROVIDER,
SECURITY_REG_BEGIN_DT,
SECURITY_REG_END_DT,
SECURITY_REG_NUM,
ASSET_TYPE,
ORIG_PROP_APPRAISAL_VAL,
ORIG_PROP_APPRAISAL_DT,
PROP_PURCHASE_AMT,
PROP_PURCHASE_DT,
ORG_TOTAL_INCOME,
PI_PYMT_AMT,
NEXT_INTEREST_RESET_DT,
RATE_MODIFIER,
DOWN_PYMT_SOURCE_DESC,
CLIENT_DT,
CIF_CREATED_ON_DT,
DEFAULT_IND,
STATED_INCOME_INDICATOR,
ACCRUED_INTEREST_AMT,
CLOSE_DT,
BULK_NSURER_DESC,
SECURITIZATION_INDICATOR,
CIF_TYPE_DESC,
CUSTOMER_TYPE_2,
INTEREST_PAYMENTS,
INTEREST_COMPOUNDING_FREQ,
OPEN_CLOSED_TERM,
PAYOUT_REASON,
LAST_RENEWAL_DT,
ACCOUNT_NUM
FROM
TNGSTP1D.TNG_ACCT_MO

;


CREATE
VIEW EDRTLRIFRS9.TNG_ACCT_COLLECTTRST
AS SELECT
MONTH_END_DT,
MTG_NUM,
TXN_DATE,
TXN_AMOUNT,
TXN_COMMENT,
TXN_TYPE_CATEGORY
FROM
TNGSTP1D.TNG_ACCT_COLLECTTRST
;

CREATE
VIEW EDRTLRIFRS9.BASEL_STEP_LTV_DRVD_VARS
as SELECT
METRPL_AREA_NM,
CRNT_METRPL_TERANET_INDEX,
APPRSL_DT_PRPTY_VAL_AMT,
CRNT_PRPTY_VAL_AMT,
PREV_12_QTR_PRPTY_VAL_AMT,
STEP_PLN_SNAPSHOT_ID,
MTH_TM_ID
from  EDRTLRP1D.BASEL_STEP_LTV_DRVD_VARS;


CREATE
VIEW EDRTLRIFRS9.DLGD_SCRI_QTR_DRVD_VARS
as SELECT
METRPL_BREACH_F,
METRPL_AREA_NM,
MTH_TM_ID
from  EDRTLRP1D.DLGD_SCRI_QTR_DRVD_VARS;



CREATE
VIEW EDRTLRIFRS9.BASEL_ACCT_LTV_DRVD_VARS
as SELECT
ACCT_SENRTY_CD,
MAX_ACCT_BAL_AMT,
EXPSR_AT_DFT_RTO,
CRNT_LTV_RTO,
INDEXED_CCLTV_RTO,
BASEL_ACCT_ID,
STEP_PLN_SNAPSHOT_ID,
MTH_TM_ID
from  EDRTLRP1D.BASEL_ACCT_LTV_DRVD_VARS;


CREATE VIEW EDRTLRIFRS9.psnl_loan_rptg_prd_lkp
as
SELECT 
SRC_SYS_CD,
PRD_ID,
PRD_CD,
BASEL_PRD_CD,
BASEL_PRD_TP_CD,
ASST_CL_NUM,
ASST_CL_DESC,
PORTFL_NM,
PRD_NM,
SUB_PRD_NM,
BASEL_SUB_PRD_NM,
BCAR_SCHED_NUM,
NCR_EXPSR_CL_KEY_VAL,
CCAR_BASEL_PRD_TP_NM,
CCAR_SHT_NM,
CRNCY_OF_ACCT,
NCR_RT_KEY_VAL,
BASEL_PRD,
BASEL_PRD_ABR,
SCRTY_TP,
PD_BAND_EXPSR_CL_KEY_VAL,
PD_BAND_EXPSR_CL_DESC,
NCR_EXPSR_CL_DESC,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM EDRTLRP1D.psnl_loan_rptg_prd_lkp;



CREATE VIEW EDRTLRIFRS9.PSNL_LOAN_OBSVTN_PT_DRVD_VAR 
AS 
SELECT 
BASEL_ACCT_ID,
OBSVTN_MTH_TM_ID,
PROCESS_MTH_TM_ID,
LAST_NEW_DFT_MTH_TM_ID,
PROCESS_DT,
OBSVTN_DT,
LOAN_NUM,
CAB,
SUB_PORTFL,
PIT_STAT_VER_2_CD,
MODEL_DFT_F,
LAST_NEW_DFT_DT,
LAST_NEW_DFT_BAL_AMT,
RCVRY_WINDOW_CUTOFF_TM_ID,
RCVRY_WINDOW_CUTOFF_DT,
RCVRY_WINDOW_CUTOFF_MTH_TM_ID,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
FROM EDRTLRP1D.PSNL_LOAN_OBSVTN_PT_DRVD_VAR ;


CREATE VIEW EDRTLRIFRS9.SCORED_SEGMENTED_ACCTS_ANTQ as
SELECT MORTGAGE_NO,
PROCESS_DATE,
WINDOW_END_DT,
STATUS1,
DEFAULT_DATE,
DEFAULT_BAL,
DEFAULT_IND,
AMORT,
AT36,
AT94,
BR147MAX6M,
CUST_ACCT_CNT,
D2DBALPMIN6M,
DLQNT_DAY,
DLQNT_MTHMAX24M,
GO04MAX6M,
LTV,
NSF_NUMMAX6M,
PAYROLL_AMTMIN3M,
PREPAY_YTDMAX24M,
SCORECARD_POINTS,
SCR_AMORT,
SCR_AT36,
SCR_AT94,
SCR_BR147MAX6M,
SCR_CUST_ACCT_CNT,
SCR_D2DBALPMIN6M,
SCR_DLQNT_DAY,
SCR_DLQNT_MTHMAX24M,
SCR_GO04MAX6M,
SCR_LTV,
SCR_NSF_NUMMAX6M,
SCR_PAYROLL_AMTMIN3M,
SCR_PREPAY_YTDMAX24M,
NODE FROM 
FRG_USER_DATA.SCORED_SEGMENTED_ACCTS_ANTQ 
