Use crz_cust_scorecard;
DROP VIEW IF EXISTS  v_risk_sav_dly_txn_hist;
CREATE VIEW `v_risk_sav_dly_txn_hist` AS 
 SELECT `v_bb_transaction_hist`.`ws_bank` AS `ws_bank`,
 `v_bb_transaction_hist`.`ws_acct` AS `ws_acct`, 
 `v_bb_transaction_hist`.`ws_teller_branch` AS `ws_teller_branch`, 
 `v_bb_transaction_hist`.`ws_teller_number` AS `ws_teller_number`, 
 `v_bb_transaction_hist`.`ws_sender_id` AS `ws_sender_id`, 
 `v_bb_transaction_hist`.`ws_originator` AS `ws_originator`, 
 `v_bb_transaction_hist`.`ws_for` AS `ws_for`, 
 `v_bb_transaction_hist`.`ws_posted_date` AS `ws_posted_date`, 
 `v_bb_transaction_hist`.`ws_entered_date` AS `ws_entered_date`, 
 `v_bb_transaction_hist`.`ws_entered_time` AS `ws_entered_time`, 
 `v_bb_transaction_hist`.`ws_tran_code` AS `ws_tran_code`, 
 `v_bb_transaction_hist`.`ws_sign` AS `ws_sign`, 
 `v_bb_transaction_hist`.`ws_mnemonic_text` AS `ws_mnemonic_text`, 
 `v_bb_transaction_hist`.`ws_colt_mnemonic_code` AS `ws_colt_mnemonic_code`,
 `v_bb_transaction_hist`.`ws_amount` AS `ws_amount`, 
 `v_bb_transaction_hist`.`ws_narrative_code` AS `ws_narrative_code`, 
 `v_bb_transaction_hist`.`ws_chq_number` AS `ws_chq_number`, 
 `v_bb_transaction_hist`.`ws_alt_acct_no` AS `ws_alt_acct_no`, 
 `v_bb_transaction_hist`.`ws_cau_ind` AS `ws_cau_ind`, 
 `v_bb_transaction_hist`.`ws_pinned_ind` AS `ws_pinned_ind`, 
 `v_bb_transaction_hist`.`ws_reported_ind` AS `ws_reported_ind`, 
 `v_bb_transaction_hist`.`ws_retracted_ind` AS `ws_retracted_ind`, 
 `v_bb_transaction_hist`.`ws_appl_area_flag` AS `ws_appl_area_flag`, 
 `v_bb_transaction_hist`.`ws_utid_source` AS `ws_utid_source`, 
 `v_bb_transaction_hist`.`ws_utid_stck` AS `ws_utid_stck`, 
 `v_bb_transaction_hist`.`ws_utid_seq_no` AS `ws_utid_seq_no`, 
 `v_bb_transaction_hist`.`ws_appl_area` AS `ws_appl_area`, 
 `v_bb_transaction_hist`.`ws_appl_area1` AS `ws_appl_area1`, 
 `v_bb_transaction_hist`.`createdate` AS `createdate`, 
 `v_bb_transaction_hist`.`filename` AS `filename`, 
 `v_bb_transaction_hist`.`expirydate` AS `expirydate`, 
 `v_bb_transaction_hist`.`jobexecutionid` AS `jobexecutionid`, 
 `v_bb_transaction_hist`.`businesseffectivedate` AS `businesseffectivedate` 
 FROM 
 (SELECT
 `bb_transaction_hist_1`.`ws_data`.`ws_key`.`ws_bank`,                      
 `bb_transaction_hist_1`.`ws_data`.`ws_key`.`ws_acct`,                      
 `bb_transaction_hist_1`.`ws_data`.`ws_teller_data`.`ws_teller_branch`,     
 `bb_transaction_hist_1`.`ws_data`.`ws_teller_data`.`ws_teller_number`,     
 `bb_transaction_hist_1`.`ws_data`.`ws_sender_id`,                          
 `bb_transaction_hist_1`.`ws_data`.`ws_originator`,                         
 `bb_transaction_hist_1`.`ws_data`.`ws_for`,                                
 `bb_transaction_hist_1`.`ws_data`.`ws_posted_date`,                        
 `bb_transaction_hist_1`.`ws_data`.`ws_entered_date`,                       
 `bb_transaction_hist_1`.`ws_data`.`ws_entered_time`,                       
 `bb_transaction_hist_1`.`ws_data`.`ws_tran_code`,                          
 `bb_transaction_hist_1`.`ws_data`.`ws_sign`,                               
 `bb_transaction_hist_1`.`ws_data`.`ws_mnemonic_text`,                      
 `bb_transaction_hist_1`.`ws_data`.`ws_colt_mnemonic_code`,                 
 `bb_transaction_hist_1`.`ws_data`.`ws_amount`,                             
 `bb_transaction_hist_1`.`ws_data`.`ws_narrative_code`,                     
 `bb_transaction_hist_1`.`ws_data`.`ws_chq_number`,                         
 `bb_transaction_hist_1`.`ws_data`.`ws_alt_acct_no`,                        
 `bb_transaction_hist_1`.`ws_data`.`ws_cau_ind`,                            
 `bb_transaction_hist_1`.`ws_data`.`ws_pinned_ind`,                         
 `bb_transaction_hist_1`.`ws_data`.`ws_reported_ind`,                       
 `bb_transaction_hist_1`.`ws_data`.`ws_retracted_ind`,                      
 `bb_transaction_hist_1`.`ws_data`.`ws_appl_area_flag`,                     
 `bb_transaction_hist_1`.`ws_data`.`ws_uniq_txn_id`.`ws_utid_source`,       
 `bb_transaction_hist_1`.`ws_data`.`ws_uniq_txn_id`.`ws_utid_stck`,         
 `bb_transaction_hist_1`.`ws_data`.`ws_uniq_txn_id`.`ws_utid_seq_no`,       
 `bb_transaction_hist_1`.`ws_data`.`ws_appl_area`,                          
 `bb_transaction_hist_1`.`ws_data`.`ws_appl_area1`,                         
 `bb_transaction_hist_1`.`operationalfields`.`createdate`,                  
 `bb_transaction_hist_1`.`operationalfields`.`filename`,                    
 `bb_transaction_hist_1`.`operationalfields`.`expirydate`,                  
 `bb_transaction_hist_1`.`operationalfields`.`jobexecutionid`,              
 `bb_transaction_hist_1`.`businesseffectivedate`                            
                                                                            
 from `tsz`.`bb_transaction_hist_1`) `v_bb_transaction_hist`                
