/* RRMSS-1541

TAKE BACKUP of EDRTLRP1D.BASEL_REVLVNG_CR_MTH_SNAPSHOT before update


Below query should update only 1 record */

UPDATE EDRTLRU1D.BASEL_REVLVNG_CR_MTH_SNAPSHOT SET MTH_TM_ID =19396 WHERE mth_tm_id=-19396 AND REVLVNG_CR_BASEL_MTH_SNAPSHOT_ID=3306307536 AND BASEL_ACCT_ID =-1;

