CREATE TABLE IF NOT EXISTS emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,
    PIT_STATUS_V2 VARCHAR,
    MODEL_EXCL_F VARCHAR,
    COMM_F_V2 INTEGER,
    TREATMNT_F VARCHAR,
    PRD_ID VARCHAR,
    OS_BAL_AMT_V2 DECIMAL(17, 3),
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2
SET PARTITIONED BY (OBSN_DT, STREAM);
