CREATE TABLE IF NOT EXISTS emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS (
    OBSN_DT DATE NOT NULL,
    MTH_TM_ID BIGINT,
    BASEL_ACCT_ID BIGINT,
    BASEL_CUST_ID BIGINT,
    ACCT_NUM VARCHAR,

    BASEL_PRD_CD VARCHAR,
    BASEL_PRD_DESC VARCHAR,

    CONSM_SCORECRD_EXCLSN_F VARCHAR,
    CONSM_PRD_TREATMNT_CD VARCHAR,
    HELOC_F VARCHAR,

    PIT_STAT_VER_2_CD VARCHAR,

    REVISED_EXPSR_AMT DOUBLE,

    RS_F VARCHAR,
    SML_BUS_F VARCHAR,
    STEP_CD VARCHAR,
    TRNST_EXCLSN_F VARCHAR,
    ACCRL_STAT_F VARCHAR,
    LTV_TP_CD VARCHAR,
    BNKRPY_F VARCHAR,

    PIT_STAT_VER_2_CD90 VARCHAR,
    PIT_STAT_VER_2_CD180 VARCHAR,

    TOTAL_EXPSR_ABOVE_LMT_F VARCHAR
);

ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS
SET PARTITIONED BY (OBSN_DT);