CREATE TABLE IF NOT EXISTS emulated.BASEL_MORT_ACCT_DRVD_VARS (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    COMM_TP_CD VARCHAR,
    CONSM_PRD_TREATMNT_CD VARCHAR,
    DLQNT_DAY_CNT INTEGER,
    OS_BAL_AMT DECIMAL(17, 3),
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS
SET PARTITIONED BY (OBSN_DT, STREAM);

-- Reconcile already-deployed tables to the trimmed column set.
-- Idempotent: fresh tables no-op, pre-trim tables drop the retired columns.
ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS DROP COLUMN IF EXISTS BASEL_CUST_ID;
ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS DROP COLUMN IF EXISTS ACCT_NUM;
ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS DROP COLUMN IF EXISTS DLQNT_MTH_CNT;
ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS DROP COLUMN IF EXISTS LAND_RGSTRN_ACT_STAT_F;
ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS DROP COLUMN IF EXISTS PIT_STAT_VER_1_CD;
ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS DROP COLUMN IF EXISTS STEP_F;
ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS DROP COLUMN IF EXISTS TRNST_EXCLSN_F;
