CREATE TABLE IF NOT EXISTS emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    MTH_TM_ID BIGINT,
    BASEL_ACCT_ID BIGINT,

    PIT_STAT_VER_2_CD VARCHAR,
    CONSM_PRD_TREATMNT_CD VARCHAR,
    CONSM_SCORECRD_EXCLSN_F VARCHAR
);

ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS
SET PARTITIONED BY (OBSN_DT, STREAM);

-- Reconcile already-deployed tables to the trimmed column set (only what
-- custuniv_01 reads). Idempotent: fresh tables no-op, pre-trim tables drop
-- the retired columns.
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS BASEL_CUST_ID;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS ACCT_NUM;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS BASEL_PRD_CD;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS BASEL_PRD_DESC;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS HELOC_F;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS REVISED_EXPSR_AMT;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS RS_F;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS SML_BUS_F;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS STEP_CD;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS TRNST_EXCLSN_F;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS ACCRL_STAT_F;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS LTV_TP_CD;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS BNKRPY_F;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS PIT_STAT_VER_2_CD90;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS PIT_STAT_VER_2_CD180;
ALTER TABLE emulated.BASEL_REVLVNG_CR_BASE_DRVD_VARS DROP COLUMN IF EXISTS TOTAL_EXPSR_ABOVE_LMT_F;
