CREATE TABLE IF NOT EXISTS emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,
    PIT_STATUS_V2 VARCHAR,
    MODEL_EXCL_F VARCHAR,
    COMM_F_V2 INTEGER,
    TREATMNT_F VARCHAR,
    PRD_ID VARCHAR,
    OS_BAL_AMT_V2 DECIMAL(17, 3),
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2
SET PARTITIONED BY (OBSN_DT, STREAM);

-- Reconcile already-deployed tables to the lean feature-join schema.
-- Idempotent: fresh tables no-op, pre-trim tables drop the retired columns.
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS BASEL_CUST_ID;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS CAB;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS CONS_DFT_MTH_CNT;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS IND_24MOS_EXCL;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS IND_BAL_EXCL;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS IND_CAB_EXCL;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS IND_HL_EXCL;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS LOAN_NUM;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS PRD;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS PRD_TP;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS PROCESS_DT;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS SUB_PORTFL;
ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 DROP COLUMN IF EXISTS SUB_PRODUCT;
