CREATE TABLE IF NOT EXISTS emulated.BASEL_MORT_ACCT_DRVD_VARS (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    BASEL_CUST_ID BIGINT NOT NULL,
    ACCT_NUM VARCHAR,
    COMM_TP_CD VARCHAR,
    CONSM_PRD_TREATMNT_CD VARCHAR,
    DLQNT_DAY_CNT INTEGER,
    DLQNT_MTH_CNT INTEGER,
    LAND_RGSTRN_ACT_STAT_F VARCHAR,
    OS_BAL_AMT DECIMAL(17, 3),
    PIT_STAT_VER_1_CD VARCHAR,
    STEP_F VARCHAR,
    TRNST_EXCLSN_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.BASEL_MORT_ACCT_DRVD_VARS
SET PARTITIONED BY (OBSN_DT, STREAM);
