CREATE TABLE IF NOT EXISTS emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,
    PIT_STATUS_V2 VARCHAR,
    PROCESS_DT DATE,
    LOAN_NUM VARCHAR,
    CAB VARCHAR,
    SUB_PORTFL VARCHAR,
    COMM_F_V2 INTEGER,
    IND_BAL_EXCL INTEGER,
    IND_HL_EXCL INTEGER,
    IND_CAB_EXCL INTEGER,
    IND_24MOS_EXCL INTEGER,
    MODEL_EXCL_F VARCHAR,
    TREATMNT_F VARCHAR,
    BASEL_CUST_ID BIGINT,
    PRD_TP VARCHAR,
    PRD VARCHAR,
    CONS_DFT_MTH_CNT INTEGER,
    SUB_PRODUCT VARCHAR,
    PRD_ID VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP,
    OS_BAL_AMT_V2 DECIMAL(17, 3)
);

ALTER TABLE emulated.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2
SET PARTITIONED BY (OBSN_DT, STREAM);
