CREATE TABLE IF NOT EXISTS emulated.CBS_MDM_FLAGS (
    EFF_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,
    DATE_TYPE VARCHAR NOT NULL,

    PARTY_ID VARCHAR NOT NULL,
    PREF_LANG VARCHAR,
    GENDER_CD VARCHAR,
    MARITAL_STATUS VARCHAR,
    EMP_TYPE_CD VARCHAR,
    OCCUP_CD VARCHAR,
    OCCUP_TYPE_CD VARCHAR,
    OCCUP_STAT_CD VARCHAR,
    OCCUP_CAT_CD VARCHAR,
    TRANSIT_NUM VARCHAR,
    SENSITIVITY_CD VARCHAR,
    DECEASED_IND VARCHAR,
    CUST_STATUS VARCHAR,
    BNKRPTCY_FLAG VARCHAR,
    UNDER_18_FLAG VARCHAR,
    CUST_TYPE VARCHAR,
    TIME_ON_BOOKS DOUBLE,
    CUST_AGE INTEGER,

    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.CBS_MDM_FLAGS
SET PARTITIONED BY (EFF_DT, STREAM);
