CREATE TABLE IF NOT EXISTS emulated.CIS_DATA_NEW2 (
    FILE_YR_MTH VARCHAR NOT NULL,

    CIFKEY VARCHAR,
    PRODUCT VARCHAR,
    "ACCOUNT" VARCHAR,
    CID VARCHAR,
    PRIMARY_FLAG VARCHAR,
    RELATION_CODE VARCHAR,
    CUST_TYPE VARCHAR,
    EMPLOYEE_IND VARCHAR,
    MORT_NO VARCHAR,
    CAB VARCHAR,
    LOAN_NO VARCHAR,
    FILE_DATE DATE,

    LOAD_DATE_TM TIMESTAMP,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.CIS_DATA_NEW2
SET PARTITIONED BY (FILE_YR_MTH);
