CREATE TABLE IF NOT EXISTS emulated.PSNL_LOAN_OBSVTN_PT_DRVD_VAR (
    BASEL_ACCT_ID BIGINT NOT NULL,
    OBSVTN_MTH_TM_ID INTEGER NOT NULL,
    PROCESS_MTH_TM_ID INTEGER NOT NULL,
    LAST_NEW_DFT_MTH_TM_ID INTEGER,
    PROCESS_DT DATE,
    OBSVTN_DT DATE,
    LOAN_NUM VARCHAR,
    CAB VARCHAR,
    SUB_PORTFL VARCHAR,
    PIT_STAT_VER_2_CD VARCHAR,
    MODEL_DFT_F VARCHAR,
    LAST_NEW_DFT_DT DATE,
    LAST_NEW_DFT_BAL_AMT DECIMAL(17, 3),
    RCVRY_WINDOW_CUTOFF_TM_ID INTEGER,
    RCVRY_WINDOW_CUTOFF_DT DATE,
    RCVRY_WINDOW_CUTOFF_MTH_TM_ID INTEGER,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.PSNL_LOAN_OBSVTN_PT_DRVD_VAR
SET PARTITIONED BY (PROCESS_MTH_TM_ID);
