CREATE TABLE IF NOT EXISTS emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    OBSVTN_MTH_TM_ID INTEGER NOT NULL,
    LAST_NEW_DFT_DT DATE,
    LAST_NEW_DFT_BAL_AMT DECIMAL(17, 3),
    MODEL_DFT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR
SET PARTITIONED BY (OBSN_DT, STREAM);

-- Reconcile already-deployed tables to the lean feature-join schema.
-- Idempotent: fresh tables no-op, pre-trim tables drop the retired columns.
ALTER TABLE emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR DROP COLUMN IF EXISTS LAST_NEW_DFT_TM_ID;
ALTER TABLE emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR DROP COLUMN IF EXISTS PROCESS_MTH_TM_ID;
ALTER TABLE emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR DROP COLUMN IF EXISTS RCVRY_WINDOW_CUTOFF_DT;
ALTER TABLE emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR DROP COLUMN IF EXISTS RCVRY_WINDOW_CUTOFF_TM_ID;
