CREATE TABLE IF NOT EXISTS emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR (
    OBSVTN_MTH_TM_ID INTEGER NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    LAST_NEW_DFT_BAL_AMT DECIMAL(17, 3),
    LAST_NEW_DFT_TM_ID INTEGER NOT NULL,
    LAST_NEW_DFT_DT DATE,
    MODEL_DFT_F VARCHAR,
    RCVRY_WINDOW_CUTOFF_TM_ID INTEGER NOT NULL,
    RCVRY_WINDOW_CUTOFF_DT DATE,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP,
    PROCESS_MTH_TM_ID INTEGER
);

ALTER TABLE emulated.REVLVNG_CR_OBSVTN_PT_DRVD_VAR
SET PARTITIONED BY (PROCESS_MTH_TM_ID);
