CREATE TABLE IF NOT EXISTS emulated.STATUS_FINAL (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,

    MORTGAGE_NO BIGINT NOT NULL,
    STATUS VARCHAR,
    MODEL_EXCL VARCHAR,
    LRA_STATUS VARCHAR,
    PAID_OFF_DATE TIMESTAMP,
    CURRENT_BAL DOUBLE,
    TOTAL_SUSPENSE DOUBLE,
    PROCESS_DATE TIMESTAMP NOT NULL,

    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.STATUS_FINAL
SET PARTITIONED BY (OBSN_DT, STREAM);

-- Reconcile already-deployed tables to the lean feature-join schema.
-- Idempotent: fresh tables no-op, pre-refactor tables drop the retired columns.
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS COMM_TYPE;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS FLOAT_LKP_ID;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS GENL_LKP_ID;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS DELQ_DAYS;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS DELQ_MONTHS;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS FLOAT_IND;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS FORECLOSE_IND;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS INT_ACCR_AMT;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS PAID_OFF_IND;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS UNPD_MTH_PAY_DATE;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS UNPD_WKL_PAY_DATE;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS MADE_DATE;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS TIME_KEY;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS INT_ADJ_DATE;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS YYMTH;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS INSURANCE;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS CLASS;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS EFF_TMSTMP;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS PRPTY_DESC_1;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS PRPTY_DESC_2;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS PRPTY_DESC_3;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS LEND_VAL2;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS TRNST;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS AUTH_AMT;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS MAT_DT;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS CAB;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS TOT_ADVNC_AMT;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS PRIM_CUST_ID;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS CIF_KEY;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS STEP_F;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS INSUR_GRP;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS BULK_IND;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS AMORT;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS PREPAY_YTD;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS PROVINCE;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS DELQ_DAYS_2;
ALTER TABLE emulated.STATUS_FINAL DROP COLUMN IF EXISTS DELQ_MONTHS_2;
