-- BNS mortgage 12-month PD default observation windows (nzuser.twelve_mon_def_window).
-- One row per (MORTGAGE_NO, PROCESS_DATE) where PROCESS_DATE is the obs-window start month-end.
CREATE TABLE IF NOT EXISTS emulated.TWELVE_MON_DEF_WINDOW (
    OBSN_DT DATE NOT NULL,
    STREAM VARCHAR NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,

    MORTGAGE_NO BIGINT NOT NULL,
    PROCESS_DATE DATE NOT NULL,
    WINDOW_END_DT DATE,
    STATUS1 VARCHAR,
    DEFAULT_DATE DATE,
    DEFAULT_BAL DOUBLE,
    DEFAULT_IND INTEGER,

    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);

ALTER TABLE emulated.TWELVE_MON_DEF_WINDOW
SET PARTITIONED BY (OBSN_DT, STREAM);
