CREATE TABLE IF NOT EXISTS reference.BASEL_EXPSR_CL_DIM_NZ (
    EXPSR_CL_ID INTEGER,
    NCR_EXPSR_CL_KEY_VAL VARCHAR,
    NCR_EXPSR_CL_DESC VARCHAR,
    FRS_CD VARCHAR,
    BCAR_SCHED_NUM VARCHAR,
    CCAR_EXPSR_CL_NM VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    EFF_FROM_YR_MTH VARCHAR,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP,
);