CREATE TABLE
    if NOT EXISTS reference.BASEL_EGL_LKP_NZ (
        PRD_CD VARCHAR,
        EFF_FROM_YR_MTH VARCHAR,
        EFF_TO_YR_MTH VARCHAR,
        PRD_NM VARCHAR,
        EGL_DEPRTMNT VARCHAR,
        EGL_TRNST VARCHAR,
        CRNT_F VARCHAR,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;