CREATE TABLE IF NOT EXISTS reference.BASEL_NCR_LTV_DIM (
    NCR_LTV_ID INTEGER NOT NULL,
    NCR_LTV_KEY_VAL VARCHAR,
    NCR_LTV_DESC VARCHAR,
    FRS_CD VARCHAR,
    LTV_RTO_MIN_VAL DECIMAL(11,4),
    LTV_RTO_MAX_VAL DECIMAL(11,4),
    LTV_MIN_RTO_DESC VARCHAR,
    LTV_MAX_RTO_DESC VARCHAR,
    EFF_FROM_YR_MTH VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);
