CREATE TABLE IF NOT EXISTS reference.BASEL_NCR_GEO_DIM (
    NCR_GEO_ID INTEGER NOT NULL,
    NCR_GEO_KEY_VAL VARCHAR,
    NCR_GEO_DESC VARCHAR,
    FRS_CD VARCHAR,
    EFF_FROM_YR_MTH VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);