CREATE TABLE
    if NOT EXISTS reference.BASEL_DFT_LKP (
        DIS_RT_CD VARCHAR,
        EFF_FROM_YR_MTH VARCHAR,
        EFF_TO_YR_MTH VARCHAR,
        CRNT_F VARCHAR,
        DIS_RT DECIMAL,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;