CREATE TABLE
    if NOT EXISTS reference.BASEL_MODEL_LGD (
        BASEL_MODEL_ID INTEGER,
        MODEL_NM VARCHAR,
        MODEL_DESC VARCHAR,
        MODEL_VER VARCHAR,
        MODEL_ST_DT INTEGER,
        MODEL_END_DT INTEGER,
        SRC_SYS_CD VARCHAR,
        RPTG_F VARCHAR,
        EAD_F VARCHAR,
        PD_F VARCHAR,
        LGD_NON_DEFAULTER_F VARCHAR,
        LGD_DEFAULTER_F VARCHAR,
        LGD_RCVRY_WINDOW_MTHS INTEGER,
        LGD_PERF_WINDOW_MTHS INTEGER,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;
