CREATE TABLE IF NOT EXISTS reference.BASEL_NCR_EXPSR_SIZE_DIM (
    NCR_EXPSR_SIZE_ID INTEGER NOT NULL,
    NCR_KEY_VAL VARCHAR,
    MIN_BAL_AMT DECIMAL,
    MAX_BAL_AMT DECIMAL,
    NCR_DESC VARCHAR,
    FRS_CD VARCHAR,
    EFF_FROM_YR_MTH VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);