CREATE TABLE
    if NOT EXISTS reference.BASEL_NCR_PD_BAND_DIM_NZ (
        NCR_PD_BAND_ID INTEGER,
        NCR_PD_BAND_KEY_VAL VARCHAR,
        NCR_EXPSR_CL_KEY_VAL VARCHAR,
        PD_MAX_VAL DECIMAL,
        PD_MIN_VAL DECIMAL,
        FRS_CD VARCHAR,
        PD_MIN_VAL_DESC VARCHAR,
        EFF_FROM_YR_MTH VARCHAR,
        PD_MAX_VAL_DESC VARCHAR,
        EFF_TO_YR_MTH VARCHAR,
        PD_BAND_EXPSR_CL_DESC VARCHAR,
        NCR_PD_BAND_DESC VARCHAR,
        PD_BAND VARCHAR,
        CRNT_F VARCHAR,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;