CREATE TABLE
    if NOT EXISTS reference.BLOCK_RECL_CLS_RSN_LKP (
        BLOCK_RECL_CD VARCHAR NOT NULL,
        CLS_RSN_CD VARCHAR NOT NULL,
        EFF_FROM_YR_MTH VARCHAR NOT NULL,
        EFF_TO_YR_MTH VARCHAR,
        CONSM_SCORECRD_EXCLSN_F VARCHAR,
        CRNT_F VARCHAR NOT NULL,
        INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;