CREATE TABLE
    if NOT EXISTS reference.CHRG_OFF_LKP (
        CHRG_OFF_CD VARCHAR NOT NULL,
        EFF_FROM_YR_MTH VARCHAR NOT NULL,
        EFF_TO_YR_MTH VARCHAR,
        CHRG_OFF_STAT_F VARCHAR,
        CHRG_OFF_STAT_DESC VARCHAR,
        ACCRL_STAT_F VARCHAR,
        ACCRL_STAT_DESC VARCHAR,
        CRNT_F VARCHAR NOT NULL,
        INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;