CREATE TABLE
    if NOT EXISTS reference.DLGD_METRPL_THRSHD_VAL_DIM (
        METRPL_AREA_NM VARCHAR,
        EFF_FROM_YR_MTH VARCHAR,
        EFF_TO_YR_MTH VARCHAR,
        CRNT_F VARCHAR,
        THRSHD_VAL DECIMAL,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;