CREATE TABLE IF NOT EXISTS reference.DLQNT_DIM (
    DLQNT_ID INTEGER NOT NULL,
    KS_MIN_DAY_DLQNT INTEGER,
    MIN_DAY_DLQNT INTEGER,
    KS_MAX_DAY_DLQNT INTEGER,
    MAX_DAY_DLQNT INTEGER,
    DLQNT_CYCL_CD VARCHAR,
    DLQNT_CYCL_DESC VARCHAR,
    NCR_DLQNT_CD VARCHAR(4),
    NCR_DLQNT_DESC VARCHAR,
    EFF_FROM_DT DATE,
    EFF_TO_DT DATE,
    CRNT_F VARCHAR(1) NOT NULL,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);