CREATE TABLE IF NOT EXISTS reference.DLVY_KEY_TO_TXN_GRP_MAPPNG_LKP (
    DLVY_KEY             INTEGER,
    TXN_GRP_KEY          VARCHAR(1),
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP  TIMESTAMP
);