--GEN_LKP reference table
CREATE TABLE IF NOT EXISTS reference.GEN_LKP (
GENL_LKP_ID     VARCHAR , 
GENL_LKP_CD     VARCHAR , 
GENL_LKP_DESC   VARCHAR , 
TBL_NM          VARCHAR , 
EFF_FROM_TMSTMP   TIMESTAMP, 
EFF_TO_TMSTMP   VARCHAR , 
POPN_DATETIME   VARCHAR , 
GENL_LKP_TP_NM  VARCHAR , 
INTG_LAYER_CLASS_ID VARCHAR , 
INSRT_PROCESS_TMSTMP TIMESTAMP, 
UPDT_PROCESS_TMSTMP TIMESTAMP 

);
