--GENWORTH_BULKINS reference table
CREATE TABLE IF NOT EXISTS reference.GENWORTH_BULKINS (
INSURER         VARCHAR ,     
EFFECTIVEDTE    TIMESTAMP ,   
POOL            DOUBLE ,      
INSURE          DOUBLE ,      
LENDER_LOAN     DOUBLE ,      
LENDER_LOAN_AMT DOUBLE ,      
LEND__LOAN_IND  DOUBLE ,      
SUBSTITUDE      VARCHAR 
);
