CREATE TABLE
    if NOT EXISTS reference.IND_COST_DFT_ALLOC_LKP (
        TRNST_NUM VARCHAR,
        ACCOUNT_STATUS VARCHAR,
        DEFAULT_ALLOCATION DECIMAL,
        EFF_FROM_YR_MTH INTEGER,
        EFF_TO_YR_MTH INTEGER,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;