CREATE TABLE
    if NOT EXISTS reference.IND_COST_PRD_ALLOC_LKP (
        SRC_SYS_CD VARCHAR,
        BASEL_MODEL_ID INTEGER,
        MODEL_DESC VARCHAR,
        PRODUCT_ALLOCATION DECIMAL,
        EFF_FROM_YR_MTH INTEGER,
        EFF_TO_YR_MTH INTEGER,
        INSRT_PROCESS_TMSTMP TIMESTAMP,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;