CREATE TABLE IF NOT EXISTS reference.IWD_CHNL_RM (
        DLVY_KEY DOUBLE,
        POPN_DT DATE,
        ALL_CHNL_ACTY_DESC VARCHAR,
        DLVY_CHNL_DESC VARCHAR,
        TXN_GRP_DESC VARCHAR,
        TXN_GRP_KEY DOUBLE,
        TXN_GRP_KEY_RM VARCHAR,
        ACTY_DESC VARCHAR,
        TXN_TP_DESC VARCHAR,
        DLVY_DESC VARCHAR,
        TXN_TP_KEY DOUBLE,
        ACTY_KEY DOUBLE,
        CHNL_KEY DOUBLE,
        ALL_DLVY_KEY DOUBLE
);
