CREATE TABLE IF NOT EXISTS reference.KQ_TKQ_KS_TSYS_XREF (
    BCM_ACCT_NUM VARCHAR,
    TSYS_ACCT_ID VARCHAR,
    CLIENT_PROD_CD VARCHAR,
    TSYS_PROD_CD VARCHAR,
    EMP_CD VARCHAR,
    KS_PLASTIC_CARD_NUM VARCHAR,
    BCM_PROD_CD VARCHAR,
    BCM_SUB_PROD_CD VARCHAR,
    BCM_BLOCK_RECLASS VARCHAR,
    TSYS_CUST_ID VARCHAR,
    TSYS_CUST_TYPE_CD VARCHAR,
    TSYS_PLASTIC_CARD_NUM VARCHAR,
    TRANSFER_FROM_ACCT_NUM VARCHAR,
    BNS_CUST_ID VARCHAR,
    CONVERSION_DT VARCHAR,
    END_OF_CHAIN_INDICATOR VARCHAR,
    BUSINESSEFFECTIVEDATE DATE
);
