CREATE TABLE IF NOT EXISTS reference.ORG_UNIT_HIERARCHY_DIM_NZ(
    ORG_UNIT_HIERARCHY_ID BIGINT,
    EFF_FROM_TMSTMP TIMESTAMP,
    TRNST_NUM VARCHAR,
    RGNL_OFFC_TRNST_NUM VARCHAR,
    DSTRCT_OFFC_TRNST_NUM VARCHAR,
    RNGL_OFFC_OU_ID VARCHAR,
    DSTRCT_OFFC_OU_ID VARCHAR,
    EFF_TO_TMSTMP TIMESTAMP,
    CRNT_F VARCHAR,
    RGNL_OFFC_CD VARCHAR,
    DSTRCT_OFFC_CD VARCHAR,
    TRNST_NM VARCHAR,
    RGNL_OFFC_DESC VARCHAR,
    DSTRCT_OFFC_DESC VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);