CREATE TABLE
    if NOT EXISTS reference.PD_BAND_DIM (
        NCR_PD_BAND_ID INTEGER NOT NULL,
        NCR_PD_BAND_KEY_VAL VARCHAR,
        NCR_EXPSR_CL_KEY_VAL VARCHAR,
        PD_MIN_VAL DECIMAL(28, 8),
        PD_MAX_VAL DECIMAL(28, 8),
        PD_MIN_VAL_DESC VARCHAR,
        PD_MAX_VAL_DESC VARCHAR,
        PD_BAND_EXPSR_CL_DESC VARCHAR,
        NCR_PD_BAND_DESC VARCHAR,
        FRS_CD VARCHAR,
        PD_BAND VARCHAR,
        TRANSACTOR_F VARCHAR,
        CMHC_F VARCHAR,
        EFF_FROM_YR_MTH VARCHAR,
        EFF_TO_YR_MTH VARCHAR,
        CRNT_F VARCHAR,
        STREAM VARCHAR,
        INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;