CREATE TABLE
    IF NOT EXISTS REFERENCE.PSNL_LOAN_SCRTY_CD_LKP (
        SCRTY_CD SMALLINT NOT NULL,
        EFF_FROM_YR_MTH VARCHAR NOT NULL,
        SCRTY_DESC VARCHAR,
        TP VARCHAR,
        PRD VARCHAR,
        SUB_PRD VARCHAR,
        STEP_F VARCHAR,
        BASEL_PRD VARCHAR,
        BASEL_SUB_PRD VARCHAR,
        BASEL_PROD_ABR VARCHAR,
        PRD_ID VARCHAR,
        EFF_TO_YR_MTH VARCHAR,
        CRNT_F VARCHAR NOT NULL,
        INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
        UPDT_PROCESS_TMSTMP TIMESTAMP,
    )
;