CREATE TABLE IF NOT EXISTS reference.RPTG_CCF_LKP(
    BASEL_PRD_TP_CD VARCHAR,
    CCF DECIMAL,
    EFF_FROM_YR_MTH VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP
);