CREATE TABLE IF NOT EXISTS reference.RPTG_LGD_HC_LKP(
    COLLATERAL_TYPE VARCHAR,
    H_C DECIMAL,
    LGD_S DECIMAL,
    LGD_U DECIMAL,
    H_E DECIMAL,
    EFF_FROM_YR_MTH VARCHAR,
    EFF_TO_YR_MTH VARCHAR,
    CRNT_F VARCHAR,
    INSRT_PROCESS_TMSTMP TIMESTAMP,
    UPDT_PROCESS_TMSTMP TIMESTAMP,
);