CREATE TABLE
    IF NOT EXISTS REFERENCE.RPTG_PRD_LKP_THRSHLD (
        THRSHLD INTEGER NOT NULL,
        CRNT_F VARCHAR NOT NULL,
        EFF_FROM_YR_MTH DATE NOT NULL,
        EFF_TO_YR_MTH DATE NOT NULL,
    )
;