CREATE TABLE
    IF NOT EXISTS REFERENCE.SRC_PRD_STDNT_LOAN_LKP (
        PRD_SYS_CD VARCHAR NOT NULL,
        SRC_PRD_CD VARCHAR NOT NULL,
        SRC_SUB_PRD_CD VARCHAR NOT NULL,
        EFF_FROM_YR_MTH VARCHAR NOT NULL,
        BILL_CD_CHAR VARCHAR NOT NULL,
        EFF_TO_YR_MTH VARCHAR,
        BASEL_PRD_CD VARCHAR,
        BASEL_PRD_DESC VARCHAR,
        PRD_DESC VARCHAR,
        LTV_TP_CD VARCHAR,
        SML_BUS_F VARCHAR,
        CONSM_SCORECRD_EXCLSN_F VARCHAR,
        CONSM_PRD_TREATMNT_CD VARCHAR,
        CRNT_F VARCHAR NOT NULL,
        INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
        UPDT_PROCESS_TMSTMP TIMESTAMP
    )
;