use crz_cust_scorecard;
drop table if exists CBS_MODEL_SCORECRD_SUMMARY;
CREATE EXTERNAL TABLE CBS_MODEL_SCORECRD_SUMMARY(
    CUST_CID                VARCHAR(40)       COMMENT 'Customer ID',
    INSRT_PROCESS_TMSTMP    TIMESTAMP         COMMENT 'Insert Process Timestamp',
    OP_FIELD                VARCHAR(1000)     COMMENT 'Operational Field',
    SC_VAR_1                VARCHAR(100)      COMMENT 'Scorecard Variable 1',
    SC_VAR_VAL_1            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 1 Value',
    SC_VAR_SCORE_1          INT               COMMENT 'Scorecard Variable 1 Score',
    SC_VAR_2                VARCHAR(100)      COMMENT 'Scorecard Variable 2',
    SC_VAR_VAL_2            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 2 Value',
    SC_VAR_SCORE_2          INT               COMMENT 'Scorecard Variable 2 Score',
    SC_VAR_3                VARCHAR(100)      COMMENT 'Scorecard Variable 3',
    SC_VAR_VAL_3            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 3 Value',
    SC_VAR_SCORE_3          INT               COMMENT 'Scorecard Variable 3 Score',
    SC_VAR_4                VARCHAR(100)      COMMENT 'Scorecard Variable 4',
    SC_VAR_VAL_4            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 4 Value',
    SC_VAR_SCORE_4          INT               COMMENT 'Scorecard Variable 4 Score',
    SC_VAR_5                VARCHAR(100)      COMMENT 'Scorecard Variable 5',
    SC_VAR_VAL_5            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 5 Value',
    SC_VAR_SCORE_5          INT               COMMENT 'Scorecard Variable 5 Score',
    SC_VAR_6                VARCHAR(100)      COMMENT 'Scorecard Variable 6',
    SC_VAR_VAL_6            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 6 Value',
    SC_VAR_SCORE_6          INT               COMMENT 'Scorecard Variable 6 Score',
    SC_VAR_7                VARCHAR(100)      COMMENT 'Scorecard Variable 7',
    SC_VAR_VAL_7            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 7 Value',
    SC_VAR_SCORE_7          INT               COMMENT 'Scorecard Variable 7 Score',
    SC_VAR_8                VARCHAR(100)      COMMENT 'Scorecard Variable 8',
    SC_VAR_VAL_8            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 8 Value',
    SC_VAR_SCORE_8          INT               COMMENT 'Scorecard Variable 8 Score',
    SC_VAR_9                VARCHAR(100)      COMMENT 'Scorecard Variable 9',
    SC_VAR_VAL_9            DECIMAL(17, 3)    COMMENT 'Scorecard Variable 9 Value',
    SC_VAR_SCORE_9          INT               COMMENT 'Scorecard Variable 9 Score',
    SC_VAR_10               VARCHAR(100)      COMMENT 'Scorecard Variable 10',
    SC_VAR_VAL_10           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 10 Value',
    SC_VAR_SCORE_10         INT               COMMENT 'Scorecard Variable 10 Score',
    SC_VAR_11               VARCHAR(100)      COMMENT 'Scorecard Variable 11',
    SC_VAR_VAL_11           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 11 Value',
    SC_VAR_SCORE_11         INT               COMMENT 'Scorecard Variable 11 Score',
    SC_VAR_12               VARCHAR(100)      COMMENT 'Scorecard Variable 12',
    SC_VAR_VAL_12           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 12 Value',
    SC_VAR_SCORE_12         INT               COMMENT 'Scorecard Variable 12 Score',
    SC_VAR_13               VARCHAR(100)      COMMENT 'Scorecard Variable 13',
    SC_VAR_VAL_13           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 13 Value',
    SC_VAR_SCORE_13         INT               COMMENT 'Scorecard Variable 13 Score',
    SC_VAR_14               VARCHAR(100)      COMMENT 'Scorecard Variable 14',
    SC_VAR_VAL_14           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 14 Value',
    SC_VAR_SCORE_14         INT               COMMENT 'Scorecard Variable 14 Score',
    SC_VAR_15               VARCHAR(100)      COMMENT 'Scorecard Variable 15',
    SC_VAR_VAL_15           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 15 Value',
    SC_VAR_SCORE_15         INT               COMMENT 'Scorecard Variable 15 Score',
    SC_VAR_16               VARCHAR(100)      COMMENT 'Scorecard Variable 16',
    SC_VAR_VAL_16           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 16 Value',
    SC_VAR_SCORE_16         INT               COMMENT 'Scorecard Variable 16 Score',
    SC_VAR_17               VARCHAR(100)      COMMENT 'Scorecard Variable 17',
    SC_VAR_VAL_17           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 17 Value',
    SC_VAR_SCORE_17         INT               COMMENT 'Scorecard Variable 17 Score',
    SC_VAR_18               VARCHAR(100)      COMMENT 'Scorecard Variable 18',
    SC_VAR_VAL_18           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 18 Value',
    SC_VAR_SCORE_18         INT               COMMENT 'Scorecard Variable 18 Score',
    SC_VAR_19               VARCHAR(100)      COMMENT 'Scorecard Variable 19',
    SC_VAR_VAL_19           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 19 Value',
    SC_VAR_SCORE_19         INT               COMMENT 'Scorecard Variable 19 Score',
    SC_VAR_20               VARCHAR(100)      COMMENT 'Scorecard Variable 20',
    SC_VAR_VAL_20           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 20 Value',
    SC_VAR_SCORE_20         INT               COMMENT 'Scorecard Variable 20 Score',
    SC_VAR_21               VARCHAR(100)      COMMENT 'Scorecard Variable 21',
    SC_VAR_VAL_21           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 21 Value',
    SC_VAR_SCORE_21         INT               COMMENT 'Scorecard Variable 21 Score',
    SC_VAR_22               VARCHAR(100)      COMMENT 'Scorecard Variable 22',
    SC_VAR_VAL_22           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 22 Value',
    SC_VAR_SCORE_22         INT               COMMENT 'Scorecard Variable 22 Score',
    SC_VAR_23               VARCHAR(100)      COMMENT 'Scorecard Variable 23',
    SC_VAR_VAL_23           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 23 Value',
    SC_VAR_SCORE_23         INT               COMMENT 'Scorecard Variable 23 Score',
    SC_VAR_24               VARCHAR(100)      COMMENT 'Scorecard Variable 24',
    SC_VAR_VAL_24           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 24 Value',
    SC_VAR_SCORE_24         INT               COMMENT 'Scorecard Variable 24 Score',
    SC_VAR_25               VARCHAR(100)      COMMENT 'Scorecard Variable 25',
    SC_VAR_VAL_25           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 25 Value',
    SC_VAR_SCORE_25         INT               COMMENT 'Scorecard Variable 25 Score',
    SC_VAR_26               VARCHAR(100)      COMMENT 'Scorecard Variable 26',
    SC_VAR_VAL_26           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 26 Value',
    SC_VAR_SCORE_26         INT               COMMENT 'Scorecard Variable 26 Score',
    SC_VAR_27               VARCHAR(100)      COMMENT 'Scorecard Variable 27',
    SC_VAR_VAL_27           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 27 Value',
    SC_VAR_SCORE_27         INT               COMMENT 'Scorecard Variable 27 Score',
    SC_VAR_28               VARCHAR(100)      COMMENT 'Scorecard Variable 28',
    SC_VAR_VAL_28           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 28 Value',
    SC_VAR_SCORE_28         INT               COMMENT 'Scorecard Variable 28 Score',
    SC_VAR_29               VARCHAR(100)      COMMENT 'Scorecard Variable 29',
    SC_VAR_VAL_29           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 29 Value',
    SC_VAR_SCORE_29         INT               COMMENT 'Scorecard Variable 29 Score',
    SC_VAR_30               VARCHAR(100)      COMMENT 'Scorecard Variable 30',
    SC_VAR_VAL_30           DECIMAL(17, 3)    COMMENT 'Scorecard Variable 30 Value',
    SC_VAR_SCORE_30         INT               COMMENT 'Scorecard Variable 30 Score',
    CUST_SCORE              INT               COMMENT 'Custome Score'
)
PARTITIONED BY( EFF_DT DATE COMMENT 'Effective Date', DATE_TYPE VARCHAR(20) COMMENT 'Shows Date Type for the partition date columm - Daily,Monthly, Weekly, Adhoc etc', SEG_NUM INT COMMENT 'Segment Number')
CLUSTERED BY (CUST_CID) SORTED BY (CUST_CID ASC) INTO 60 BUCKETS
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/CBS_MODEL_SCORECRD_SUMMARY'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

