
--STEP-1--

--Source Table Information:
--DATABASE = BLUDB (PROD)
--Schema = EDRTLRD1D
--TABLE NAME = TNG_WRITEOFF_HISTORY

--Target Table Information:
--DATABASE = BLUDB (PROD)
--Schema = TNGSTP1D
--TABLE NAME = TNG_ACCT_WRITEOFF

MERGE INTO TNGSTP1D.TNG_ACCT_WRITEOFF AS T1
USING (
    SELECT "DATE", SERVICER, MORTGAGE__, WRITE_OFF_AMOUNT
    FROM EDRTLRD1D.TNG_WRITEOFF_HISTORY
) AS T2
    ON TRIM(T1.MTG_NUM)=TRIM(T2.MORTGAGE__) AND
		T1.WRITEOFF_DATE=T2.DATE
WHEN MATCHED THEN
    UPDATE SET T1.WRITEOFF_AMT = ABS(T2.WRITE_OFF_AMOUNT);
    

--STEP-2--   

--Source/Target Table Information:
--DATABASE = BLUDB (PROD)
--Schema = TNGSTP1D
--TABLE NAME = TNG_ACCT_WRITEOFF

UPDATE TNGSTP1D.TNG_ACCT_WRITEOFF SET WRITEOFF_AMT=ABS(WRITEOFF_AMT);