use crz_cust_scorecard;
drop table if exists RISK_IP_DHS_CASH_DMD_ACCT_SNAPSHOT;
CREATE EXTERNAL TABLE RISK_IP_DHS_CASH_DMD_ACCT_SNAPSHOT(
    DHS_PLAN_ACCT_NUM                VARCHAR(30),
    DHS_DEMAND_INVESTMENT_CODE       VARCHAR(20),
    DHS_PRIMARY_OWNER_CIF_ID         VARCHAR(40),
    INSRT_PROCESS_TMSTMP             TIMESTAMP,
    OP_FIELD                         VARCHAR(1000),
    DHS_CURRENCY_CODE                VARCHAR(10),
    DHS_CURR_CASH_BALANCE_SIGN       VARCHAR(10),
    DHS_CURR_CASH_BALANCE            DECIMAL(18, 2),
    DHS_CURR_CASH_BAL_EFF_DT         DATE,
    DHS_PREV_ME_CASH_BALANCE_SIGN    VARCHAR(10),
    DHS_PREV_ME_CASH_BALANCE         DECIMAL(18, 2),
    DHS_PREV_ME_CASH_BAL_EFF_DT      DATE,
    DHS_TERM                         VARCHAR(10),
    DHS_FR_INVESTMENT_TYPE           INT,
    DHS_AVAILABLE_BALANCE            DECIMAL(18, 2)
)
PARTITIONED BY( EFF_DT DATE, DATE_TYPE VARCHAR(20) COMMENT 'Shows Date Type for the partition date columm - Daily,Monthly, Weekly, Ad-hoc etc')
CLUSTERED BY (DHS_PRIMARY_OWNER_CIF_ID, DHS_PLAN_ACCT_NUM) SORTED BY (DHS_PRIMARY_OWNER_CIF_ID ASC, DHS_PLAN_ACCT_NUM ASC) INTO 60 BUCKETS
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_IP_DHS_CASH_DMD_ACCT_SNAPSHOT'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

