use crz_cust_scorecard;
drop table if exists RISK_IP_CI_CUST_PLAN_ACCT_SNAPSHOT;
CREATE EXTERNAL TABLE RISK_IP_CI_CUST_PLAN_ACCT_SNAPSHOT(
    CI_PLAN_ACCT_NUM                VARCHAR(30),
    CI_PLAN_PRODUCT_CODE            VARCHAR(20),
    CI_BASE_ACCOUNT_TYPE            VARCHAR(20),
    CI_PRIMARY_OWNER_CIF_ID         VARCHAR(40),
    INSRT_PROCESS_TMSTMP            TIMESTAMP,
    OP_FIELD                        VARCHAR(1000),
    CI_PLAN_STATUS                  VARCHAR(20),
    CI_PLAN_STATUS_EFF_DT           DATE,
    CI_PLAN_OPEN_DT                 DATE,
    CI_DORMANT_INDICATOR            VARCHAR(1),
    CI_DORMANT_DT                   DATE,
    CI_PLAN_SERVICING_TRANSIT_NO    VARCHAR(20),
    CI_OWNERSHIP_TYPE               VARCHAR(20),
    CI_PLAN_CURRENCY_CODE           VARCHAR(10),
    CI_SPOUSAL_INDICATOR            VARCHAR(1),
    CI_RESIDENCY_CODE               VARCHAR(20),
    CI_CAD_PLAN_BOOK_VALUE          DECIMAL(18, 2),
    CI_USD_PLAN_BOOK_VALUE          DECIMAL(18, 2),
    CI_CUSTOMER_TYPE                VARCHAR(20),
    CI_PRIMARY_OWNER_PERCENT        DOUBLE,
    CI_TITLE                        VARCHAR(20),
    CI_BUSINESS_OR_PERSONAL_NAME    VARCHAR(100),
    CI_RELATIONSHIP_TYPE            VARCHAR(20),
    CI_PLAN_PROD_SUB_TYPE           VARCHAR(20)
)
PARTITIONED BY( EFF_DT DATE, DATE_TYPE VARCHAR(20) COMMENT 'Shows Date Type for the partition date columm - Daily,Monthly, Weekly, Ad-hoc etc')
CLUSTERED BY (CI_PRIMARY_OWNER_CIF_ID, CI_PLAN_ACCT_NUM) SORTED BY (CI_PRIMARY_OWNER_CIF_ID ASC, CI_PLAN_ACCT_NUM ASC) INTO 60 BUCKETS
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_IP_CI_CUST_PLAN_ACCT_SNAPSHOT'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

