use crz_cust_scorecard;
drop table if exists RISK_IP_MUT_FUND_ACCT_SNAPSHOT;
CREATE EXTERNAL TABLE RISK_IP_MUT_FUND_ACCT_SNAPSHOT(
    MFS_PLAN_ACCT_NUM              VARCHAR(30),
    MFS_FUND_INVESTMENT_CODE       VARCHAR(20),
    MFS_PRIMARY_OWNER_CIF_ID       VARCHAR(40),
    INSRT_PROCESS_TMSTMP           TIMESTAMP,
    OP_FIELD                       VARCHAR(1000),
    MFS_FUND_CLOSING_BOOK_VALUE    DECIMAL(18, 2),
    MFS_FUND_CURRENCY              VARCHAR(10),
    MFS_FUND_PRODUCT_TYPE          VARCHAR(20),
    MFS_RECORD_TYPE                VARCHAR(20),
    MFS_FUND_ACCT_NUM              VARCHAR(20),
    MFS_FUND_INVEST_ISSUER_CD      VARCHAR(20),
    MFS_FUND_ACCOUNT_OPEN_DT       DATE,
    MFS_FUND_STATUS                VARCHAR(20),
    MFS_FUND_TERM                  VARCHAR(10),
    MFS_FUND_RISK                  VARCHAR(20),
    MFS_FUND_OBJECTIVE             VARCHAR(20)
)
PARTITIONED BY( EFF_DT DATE, DATE_TYPE VARCHAR(20) COMMENT 'Shows Date Type for the partition date columm - Daily,Monthly, Weekly, Ad-hoc etc')
CLUSTERED BY (MFS_PRIMARY_OWNER_CIF_ID, MFS_PLAN_ACCT_NUM) SORTED BY (MFS_PRIMARY_OWNER_CIF_ID ASC, MFS_PLAN_ACCT_NUM ASC) INTO 60 BUCKETS
STORED AS ORC
LOCATION '/data/crz/bbcx/crz_cust_scorecard.db/RISK_IP_MUT_FUND_ACCT_SNAPSHOT'
TBLPROPERTIES ('orc.compress' = 'SNAPPY')
;

