/**************************************************************************** 
 * Job:             J_RRII_H11_005_COST_POST_LOAD_CHECK			    * 
 * Description:     Post Load checks for direct & indirect cost             *
 *                     Compare count & $ column for source & target table   *
 * Source:          ASSET_SRC_CURR, ASST_DRC_COST_MTH_SNAPSHOT              *
 *                  MBR_SRC_CURR, MBR_INDRCT_COST_MTH_SNAPSHOT              *
 * Created on:    	Apr 01, 2021                 			    * 
 * Changes								    *
 ****************************************************************************/ 

DATA _NULL_;
	CALL SYMPUTX('PROCESSSTARTTIME',PUT(DATETIME(),DATETIME25.0));
RUN;

%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

%GLOBAL FLAG1;
%GLOBAL FLAG2;
%GLOBAL FLAG3;
%GLOBAL FLAG4;
%GLOBAL SRC_ROW_COUNT1;
%GLOBAL SRC_SUM1;
%GLOBAL SRC_ROW_COUNT2;
%GLOBAL SRC_SUM2;
%GLOBAL TGT_ROW_COUNT1;
%GLOBAL TGT_SUM1;
%GLOBAL TGT_ROW_COUNT2;
%GLOBAL TGT_SUM2;

%MACRO POST_LOAD_CHECK;


/* DIRECT COST - SOURCE COUNT AND SUM */
PROC SQL NOPRINT;
	SELECT 
		COUNT(*), SUM(BALANCEOWING) FORMAT=15.2
	INTO :SRC_ROW_COUNT1, :SRC_SUM1
	FROM NZRRAP.ASSET_SRC_CURR;
QUIT;

/* DIRECT COST - TARGET COUNT AND SUM */
PROC SQL NOPRINT;
	SELECT 
		COUNT(*), SUM (BAL_OWING_AMT) FORMAT=15.2
	INTO :TGT_ROW_COUNT1, :TGT_SUM1
	FROM NZRRAP.ASST_DRC_COST_MTH_SNAPSHOT
	WHERE MTH_TM_ID=&MTH_TM_ID;
QUIT;

/* INDIRECT COST - SOURCE COUNT AND SUM */
PROC SQL NOPRINT;
	SELECT 
		COUNT(*), SUM(MISCELLANEOUS_OUTSOURCE_FEE_AMT) FORMAT=15.2
	INTO :SRC_ROW_COUNT2, :SRC_SUM2
	FROM
		(SELECT CASE WHEN TRIM(PPLAN)='5124' THEN DECUM ELSE 0 END AS MISCELLANEOUS_OUTSOURCE_FEE_AMT
		FROM
			NZRRAP.MBR_SRC_CURR
			WHERE TRIM(TRANSIT)='07112'
			AND TRIM(PPLAN)='5124'
		)X
	;
QUIT;

/* INDIRECT COST- TARGET COUNT AND SUM */
PROC SQL NOPRINT;
	SELECT 
		COUNT(*), SUM(MISCELLANEOUS_OUTSOURCE_FEE_AMT) FORMAT=15.2
	INTO :TGT_ROW_COUNT2, :TGT_SUM2
	FROM NZRRAP.MBR_INDRCT_COST_MTH_SNAPSHOT
	WHERE MTH_TM_ID=&MTH_TM_ID;
QUIT;

%PUT ASSET_SRC_CURR COUNT = &SRC_ROW_COUNT1;
%PUT ASST_DRC_COST_MTH_SNAPSHOT COUNT = &TGT_ROW_COUNT1;
%PUT ASSET_SRC_CURR BALANCE = &SRC_SUM1;
%PUT ASST_DRC_COST_MTH_SNAPSHOT BALANCE = &TGT_SUM1;

%PUT MBR_SRC_CURR COUNT = &SRC_ROW_COUNT2;
%PUT MBR_INDRCT_COST_MTH_SNAPSHOT COUNT = &TGT_ROW_COUNT2;
%PUT MBR_SRC_CURR COST = &SRC_SUM2;
%PUT MBR_INDRCT_COST_MTH_SNAPSHOT COST = &TGT_SUM2;

DATA VALIDATIONS;
IF &SRC_ROW_COUNT1^=&TGT_ROW_COUNT1 THEN ROWCHECK1=1;ELSE ROWCHECK1=0;
IF &SRC_ROW_COUNT2^=&TGT_ROW_COUNT2 THEN ROWCHECK2=1;ELSE ROWCHECK2=0;
IF &SRC_SUM1^=&TGT_SUM1 THEN SUMCHECK1=1;ELSE SUMCHECK1=0;
IF &SRC_SUM2^=&TGT_SUM2 THEN SUMCHECK2=1;ELSE SUMCHECK2=0;
RUN;

PROC SQL NOPRINT;
SELECT ROWCHECK1, ROWCHECK2, SUMCHECK1, SUMCHECK2 INTO :FLAG1, :FLAG2, :FLAG3, :FLAG4 FROM VALIDATIONS;
QUIT;

%IF (&FLAG1=1 OR &FLAG3=1) %THEN %DO;
%PUT ASST_DRC_COST_MTH_SNAPSHOT VALIDATION FAILED. CHECK COUNT AND BAL_OWING_AMT.;
%PUT FLAG1=&FLAG1 AND FLAG3=&FLAG3;
%ABORT ABEND;
%END;

%IF (&FLAG2=1 OR &FLAG4=1) %THEN %DO;
%PUT MBR_INDRCT_COST_MTH_SNAPSHOT VALIDATION FAILED. CHECK COUNT AND MISCELLANEOUS_OUTSOURCE_FEE_AMT.;
%PUT FLAG2=&FLAG2 AND FLAG4=&FLAG4;
%ABORT ABEND;
%END;

%MEND;

%POST_LOAD_CHECK;

/************** JOB LOG *****************/

DATA _NULL_;
	CALL SYMPUTX('PROCESSENDTIME',PUT(DATETIME(),DATETIME25.0));
RUN;

PROC SQL NOPRINT;
	insert into NZRRAP.AUDIT_JOB_TIMER_CHECK
		select max(LOG_ID)+1 ,
			'J_RRII_H11_006_DRC_INDRC_POST_LOAD_CHECK',
			 &MTH_TM_ID.,
			"&PROCESSSTARTTIME"dt,
			"&PROCESSENDTIME"dt,
			1,
			1
		FROM NZRRAP.AUDIT_JOB_TIMER_CHECK;
QUIT;
