%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

/*DECLARATION*/
%GLOBAL QTRTIMEKEY;
%GLOBAL TOTAL_ACCOUNTS;
%GLOBAL OUTSTANDING_BALANCE;
%GLOBAL SECURI_AMT;
%GLOBAL SOURCE_ACCT_COUNT;
%GLOBAL SOURCE_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL_MATCH_RT;
%GLOBAL TGT_SECURI_ADJ_RT;
%GLOBAL TGT_THRESHOLD;
%GLOBAL RETAIL_PERCENTAGE;
%GLOBAL ACCT_DATE;
%GLOBAL BCR_DATE;
%GLOBAL SECURI_DATE;
%GLOBAL FLAG1;
%GLOBAL FLAG2;
%GLOBAL FLAG3;


/*DISPLAY IN LOG*/
%PUT MTH_TM_ID IS : &MTH_TM_ID;
%PUT &YEARMONTH;


/*Hadi - Updated Code to dynamically derive the calendar quarter*/
data cc_time_keys;
	MONTHTIMEID=&MTH_TM_ID; 
	format yearmonth YEARQTR date9.;
	yearmonth=input(cats("&yearmonth.","01"),yymmdd8.);
	YEARQTR=intnx('QTR.1',yearmonth,0,'b');
	call symputx('QTRTIMEKEY',put(yearqtr,yymmn6.));
run;
%PUT QTRTIMEKEY IS &QTRTIMEKEY;

%MACRO SECURI;
/*READING THE ACCOUNTS FILE*/

PROC IMPORT DATAFILE="&OUTPATH/securitization/cc/incoming/cc_edwext_securitization_acct_mthly_&YEARMONTH..csv"
OUT=DRAPT.CC_SOURCE_FILE_ACCOUNTS
DBMS=CSV
REPLACE;
GETNAMES=YES;
RUN;

/*FORMATTING AND REMOVING NULLS DURING LOAD*/

DATA DRAPT.CC_SOURCE_FILE_ACCOUNTS;
SET DRAPT.CC_SOURCE_FILE_ACCOUNTS;
WHERE VISA_ACCT_NUM^=.;
FORMAT VISA_ACCT_NUM 32.;
RUN;

/*SAVING THE CSV STATS INTO VARIABLES*/

PROC SQL NOPRINT;
SELECT COUNT(VISA_ACCT_NUM) FORMAT 15., SUM(OUTSTANDING_BAL) FORMAT=15.1, SUBSTR(PUT(MAX(Effective_date),8.),1,6) FORMAT=$6. 
INTO :SOURCE_ACCT_COUNT, :SOURCE_TOT_OS_BAL, :ACCT_DATE
FROM DRAPT.CC_SOURCE_FILE_ACCOUNTS;
QUIT;

/*READING THE BCR FILE FOR ACCOUNTS*/
PROC IMPORT DATAFILE="&OUTPATH/securitization/cc/incoming/cc_edwext_securitization_acct_mthly_&YEARMONTH..bcr"
OUT=DRAPT.CC_SOURCE_FILE_AMOUNT
DBMS=CSV
REPLACE;
GETNAMES=YES;
RUN;

/*STORING THE BCR DATA INTO VARIABLES*/

PROC SQL NOPRINT;
SELECT NUM_ACCT FORMAT 10., OUTSTANDING_BAL FORMAT=15.1, SUBSTR(PUT(MAX(EFFECTIVE_DATE),8.),1,6) FORMAT=$6., RETAIL_PERCENTAGE FORMAT=15.10
INTO :TOTAL_ACCOUNTS, :OUTSTANDING_BALANCE, :BCR_DATE, :RETAIL_PERCENTAGE
FROM DRAPT.CC_SOURCE_FILE_AMOUNT;
QUIT;


/*READING THE CSV FILE FOR SECURITIZATION AMOUNT*/
PROC IMPORT DATAFILE="&OUTPATH/securitization/sf/incoming/cc_edwext_securitization_gl_summary_mthly_&YEARMONTH..csv"
OUT=DRAPT.CC_SOURCE_FILE_SECURITIZATION
DBMS=CSV
REPLACE;
GETNAMES=YES;
RUN;

/*STORING THE SECURITIZATION AMOUNT INTO VARIABLES*/
PROC SQL NOPRINT;
SELECT SECURITIZEDAMOUNT FORMAT=15., SUBSTR(PUT(MAX(EFFECTIVEDATE),8.),1,6) FORMAT=$6.
INTO :SECURI_AMT, :SECURI_DATE
FROM DRAPT.CC_SOURCE_FILE_SECURITIZATION;
QUIT;


/*SOURCE VALIDATIONS*/
%PUT CSV COUNT = &SOURCE_ACCT_COUNT;
%PUT BCR COUNT = &TOTAL_ACCOUNTS;
%PUT CSV AMOUNT = &SOURCE_TOT_OS_BAL;
%PUT BCR AMOUNT = &OUTSTANDING_BALANCE;

DATA DRAPT.CC_VALIDATIONS;
YEARMONTH=&YEARMONTH;
ACCT_DATE=&ACCT_DATE;
BCR_DATE=&BCR_DATE;
SECURI_DATE=&SECURI_DATE;
SOURCE_ACCT_COUNT=&SOURCE_ACCT_COUNT;
BCR_ACCOUNTS=&TOTAL_ACCOUNTS;
SOURCE_TOT_OS_BAL=&SOURCE_TOT_OS_BAL;
BCR_OS_AMT=&OUTSTANDING_BALANCE;
IF YEARMONTH^=ACCT_DATE OR YEARMONTH^=BCR_DATE OR YEARMONTH^=SECURI_DATE THEN DATECHECK=1;ELSE DATECHECK=0;
IF SOURCE_ACCT_COUNT^=BCR_ACCOUNTS THEN ACCOUNTCHECK=1; ELSE ACCOUNTCHECK=0;
IF SOURCE_TOT_OS_BAL^=BCR_OS_AMT THEN AMOUNTCHECK=1; ELSE AMOUNTCHECK=0;
RUN;

PROC SQL NOPRINT;
SELECT DATECHECK FORMAT=1., ACCOUNTCHECK FORMAT=1., AMOUNTCHECK FORMAT=1. INTO :FLAG1, :FLAG2, :FLAG3 FROM DRAPT.CC_VALIDATIONS;
QUIT;

%IF (&FLAG1=1 OR &FLAG2=1 OR &FLAG3=1) %THEN %DO;
%PUT SOURCE FILE VALIDATIONS FAILED. ;
%PUT FLAG1=&FLAG1 AND FLAG2=&FLAG2 AND FLAG3=&FLAG3;
%ABORT ABEND; 
%END;

%MEND;
%SECURI;

/*DECLARATION*/
%GLOBAL QTRTIMEKEY;
%GLOBAL TOTAL_ACCOUNTS;
%GLOBAL OUTSTANDING_BALANCE;
%GLOBAL SECURI_AMT;
%GLOBAL SOURCE_ACCT_COUNT;
%GLOBAL SOURCE_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL_MATCH_RT;
%GLOBAL TGT_SECURI_ADJ_RT;
%GLOBAL TGT_THRESHOLD;

/*%LET SECURI_AMT=1241910000;*/

/*DISPLAY IN LOG*/
%PUT MTH_TM_ID IS : &MTH_TM_ID;
%PUT &YEARMONTH;

%PUT QTRTIMEKEY IS &QTRTIMEKEY;

/*REPROCESSING LOGIC*/
%MACRO TO_DELETE();

%LET START_MT=&MTH_TM_ID;
%LET END_MT=&MTH_TM_ID;

%DO i = &START_MT %TO &END_MT %BY 1;
	%LET MTH_LEFT = %EVAL(((&END_MT-&i.))/40);
	%LET PARTITIONS=10;
        %DO p=0 %TO %EVAL(&PARTITIONS -1);

        PROC SQL NOPRINT;
			CONNECT USING EDRRAPT AS DBCON;
			EXECUTE(DELETE FROM EDRRAPT.BASEL_CC_SEC_ACCT_MTH_SNAP WHERE 
                MOD(BASEL_ACCT_ID_CCAR_MATCHED,&PARTITIONS.) = &p. AND BASEL_ACCT_ID_CCAR_MATCHED IS NOT NULL 
				AND MTH_TM_ID=&i.
				AND SECRTZTN_TP_CD='CC') BY DBCON;
			DISCONNECT FROM DBCON;
        QUIT;
		%PUT Partition &p. for mth_tm_id &i. for CC deleted.;
		%END;

		PROC SQL NOPRINT;
			CONNECT USING EDRRAPT AS DBCON;
			EXECUTE(DELETE FROM EDRRAPT.BASEL_CC_SEC_ACCT_MTH_SNAP WHERE MTH_TM_ID=&i. AND SECRTZTN_TP_CD='CC') BY DBCON;
		DISCONNECT FROM DBCON;
        QUIT;

	%PUT Delete of mth_tm_id=&i. complete.;
%END;

%MEND TO_DELETE;

%TO_DELETE;


%delete_table(nzuser.ks_BASEL_RPTG_PRD_LKP);
%delete_table(nzuser.ks_RPTG_DRVD_VAR);
%delete_table(nzuser.ks_instr_adj);

/*
proc sql;
	create table nzuser.ks_BASEL_RPTG_PRD_LKP as 
	select * from  EDRRAPT.BASEL_RPTG_PRD_LKP;
quit; */


Data nzuser.ks_BASEL_RPTG_PRD_LKP (BULKLOAD=YES BL_METHOD=CLILOAD);
set EDRRAPT.BASEL_RPTG_PRD_LKP;
run;

/*
proc sql;
	create table nzuser.ks_RPTG_DRVD_VAR as
	select mth_tm_id, basel_acct_id, REVISED_EXPSR_OV_125K_F , NCR_PD_BAND_ID
	from EDRRAPT.BASEL_REVLVNG_CR_RPTG_DRVD_VAR where mth_tm_id=&mth_tm_id.;
quit; */

Data nzuser.ks_RPTG_DRVD_VAR (BULKLOAD=YES BL_METHOD=CLILOAD KEEP=mth_tm_id basel_acct_id REVISED_EXPSR_OV_125K_F  NCR_PD_BAND_ID);
set EDRRAPT.BASEL_REVLVNG_CR_RPTG_DRVD_VAR ;
where mth_tm_id=&mth_tm_id.;
run;

/*
proc sql;
	create table nzuser.ks_instr_adj as
	select mth_tm_id, basel_acct_id, AF_ADJ_OS_BAL_AMT
	from EDRRAPT.BASEL_REVLVNG_CR_INSTRMNT_ADJ where mth_tm_id=&mth_tm_id.;
quit; */

Data nzuser.ks_instr_adj (BULKLOAD=YES BL_METHOD=CLILOAD KEEP=mth_tm_id basel_acct_id AF_ADJ_OS_BAL_AMT);
set EDRRAPT.BASEL_REVLVNG_CR_INSTRMNT_ADJ ;
where mth_tm_id=&mth_tm_id.;
run;



proc sql;
	connect using nzuser as nzcon;
	create table DRAPT.CC_ACCOUNTS_FROM_INSTR_FACT as select MTH_TM_ID, PRD_CD, OS_BAL_AMT, BASEL_ACCT_ID, ADJUSTED_OS_BAL_AMT, OS_PRNCPL_BAL_AMT, 
							INPUT(SUBSTR(CATS('CA','0201',ACCT_NUM),17,13),15.) AS UNIQUE_ACCOUNTS FORMAT=15. 
		from connection to nzcon
		(
		select src_sys_cd, ss.MTH_TM_ID, ss.PRD_CD, ss.TOT_NEW_BAL_AMT as OS_BAL_AMT, 
				ss.BASEL_ACCT_ID, IJ.AF_ADJ_OS_BAL_AMT as ADJUSTED_OS_BAL_AMT,  ss.TOT_NEW_BAL_AMT as OS_PRNCPL_BAL_AMT, ss.ACCT_NUM

		from &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT ss
		LEFT OUTER JOIN &net_db..BASEL_REVLVNG_CR_BASE_DRVD_VARS BDV
			ON SS.BASEL_ACCT_ID=BDV.BASEL_ACCT_ID and ss.MTH_TM_ID=bdv.mth_tm_id and ss.mth_tm_id=&mth_tm_id.
		left outer join &net_wrk..ks_RPTG_DRVD_VAR RDV
			on RDV.basel_acct_id = ss.BASEL_ACCT_ID and ss.mth_tm_id=rdv.mth_tm_id and ss.mth_tm_id=&mth_tm_id.
		left outer join &net_wrk..ks_BASEL_RPTG_PRD_LKP lkp
			on ss.PRD_CD=lkp.PRD_CD and ss.SUB_PRD_CD=lkp.SUB_PRD_CD and bdv.HELOC_F=lkp.HELOC_F and bdv.HELOC_F=lkp.HELOC_F and bdv.BASEL_PRD_CD=lkp.BASEL_PRD_CD and lkp.REVISED_EXPSR_OV_125K_F=rdv.REVISED_EXPSR_OV_125K_F
		left outer join &net_wrk..ks_instr_adj IJ
			on ss.BASEL_ACCT_ID=IJ.basel_acct_id and ss.mth_tm_id=ij.mth_tm_id and ss.mth_tm_id=&mth_tm_id.
		where ss.mth_tm_id=&mth_tm_id. 
			and ss.TOT_NEW_BAL_AMT>=0 AND bdv.CONSM_PRD_TREATMNT_CD='A' AND bdv.SML_BUS_F='N' AND bdv.PIT_STAT_ver_2_CD IN ('CUR','DEF') 
			AND bdv.TRNST_EXCLSN_F='N' AND lkp.BASEL_PRD_TP_CD='CARD'
		);
quit;

/*FETCHING ACCOUNTS FROM BASEL_REVLVNG_CR_MTH_SNAPSHOT*/

PROC SQL NOPRINT;
CREATE TABLE DRAPT.CC_ACCOUNTS_FROM_ACCT_DIM AS 
SELECT MTH_TM_ID, PRD_CD, 
INPUT(SUBSTR(ACCT_NUM,11,13),15.) AS UNIQUE_ACCOUNTS FORMAT=15.,
BASEL_ACCT_ID
FROM NZRRAP.BASEL_REVLVNG_CR_MTH_SNAPSHOT
WHERE 
MTH_TM_ID=&MTH_TM_ID;
QUIT;

/*CREATING THE ACCOUNT SNAPSHOT*/

PROC SQL NOPRINT;
CREATE TABLE DRAPT.CC_SECUR_ACCT_SNAPSHOT AS 
SELECT 
	&MTH_TM_ID AS MTH_TM_ID,
	STRIP(PUT(T1.VISA_ACCT_NUM,15.)) AS ACCT_NUM_RECVD,
	T1.OUTSTANDING_BAL,
	CASE WHEN T2.UNIQUE_ACCOUNTS=. THEN '' 
		ELSE STRIP(PUT(T2.UNIQUE_ACCOUNTS,15.)) 
	END AS ACCT_NUM_RRAP_DONT,
	T2.BASEL_ACCT_ID AS BASEL_ACCT_ID_DONT,
	T3.BASEL_ACCT_ID AS BASEL_ACCT_ID_CCAR_MATCHED,
	T3.PRD_CD,
	T3.OS_BAL_AMT,
	T3.ADJUSTED_OS_BAL_AMT,
	T3.OS_PRNCPL_BAL_AMT,
	&SESSIONTIME AS INSRT_PROCESS_TMSTMP,
	&SESSIONTIME AS UPDT_PROCESS_TMSTMP,
	'CC' AS SECRTZTN_TP_CD
FROM DRAPT.CC_SOURCE_FILE_ACCOUNTS T1
LEFT OUTER JOIN DRAPT.CC_ACCOUNTS_FROM_ACCT_DIM T2 ON T1.VISA_ACCT_NUM=T2.UNIQUE_ACCOUNTS
LEFT OUTER JOIN DRAPT.CC_ACCOUNTS_FROM_INSTR_FACT T3 ON T1.VISA_ACCT_NUM=T3.UNIQUE_ACCOUNTS;
QUIT;

/*LOADING THE DB2 TABLES*/

PROC APPEND BASE=EDRRAPT.BASEL_CC_SEC_ACCT_MTH_SNAP 
	(BULKLOAD=YES BL_METHOD=CLILOAD UPDATE_LOCK_TYPE=TABLE BL_LOAD_REPLACE=NO) 
	DATA=DRAPT.CC_SECUR_ACCT_SNAPSHOT FORCE;
RUN;


/*DECLARATION*/
%GLOBAL QTRTIMEKEY;
%GLOBAL TOTAL_ACCOUNTS;
%GLOBAL OUTSTANDING_BALANCE;
%GLOBAL SECURI_AMT;
%GLOBAL SOURCE_ACCT_COUNT;
%GLOBAL SOURCE_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL_MATCH_RT;
%GLOBAL TGT_SECURI_ADJ_RT;
%GLOBAL TGT_THRESHOLD;
%GLOBAL RETAIL_PERCENTAGE;
%GLOBAL SECURI_AMT;

/*DISPLAY IN LOG*/
%PUT MTH_TM_ID IS : &MTH_TM_ID;
%PUT &YEARMONTH;

%PUT QTRTIMEKEY IS &QTRTIMEKEY;

/*REPROCESSING LOGIC*/
PROC SQL NOPRINT;
DELETE FROM EDRRAPT.BASEL_SEC_ADJ_FACTR_MTH_SNAP WHERE MTH_TM_ID=&MTH_TM_ID AND SECRTZTN_TP_CD='CC';
QUIT;

/*FETCHING DATA FROM THE DATASETS WHICH STORES THE DATA FROM FILES*/
PROC SQL NOPRINT;
SELECT RETAIL_PERCENTAGE FORMAT=15.10 INTO :RETAIL_PERCENTAGE
FROM DRAPT.CC_SOURCE_FILE_AMOUNT;
QUIT;

PROC SQL NOPRINT;
SELECT SECURITIZEDAMOUNT FORMAT=15. INTO :SECURI_AMT 
FROM DRAPT.CC_SOURCE_FILE_SECURITIZATION;
QUIT;

/*CREATING THE MATCH RATE RESULTS*/

PROC SQL NOPRINT;
CREATE TABLE DRAPT.CC_SEC_ADJ_FACTOR AS 
SELECT 'CC' AS SECRTZTN_TP_CD,
t6.MTH_TM_ID,
'CREDIT CARD' AS SECRTZTN_TP_DESC,
&SECURI_AMT*&RETAIL_PERCENTAGE AS TOT_SECRTZTN_AMT_TO_ADJUST,
SUM(T6.ADJUSTED_OS_BAL_AMT) FORMAT=20.8 AS TOT_ADJUSTED_OS_BAL_IN_CCAR,
(&SECURI_AMT*&RETAIL_PERCENTAGE)/SUM(T6.ADJUSTED_OS_BAL_AMT) AS SECRTZTN_OS_ADJ_FACTR,
&SESSIONTIME AS INSRT_PROCESS_TMSTMP,
&SESSIONTIME AS UPDT_PROCESS_TMSTMP
FROM DRAPT.CC_SOURCE_FILE_ACCOUNTS T5
INNER JOIN DRAPT.CC_ACCOUNTS_FROM_INSTR_FACT T6 ON T5.VISA_ACCT_NUM=T6.UNIQUE_ACCOUNTS
GROUP BY T6.MTH_TM_ID;
QUIT;

/*LOADING THE DB2 TABLES*/

PROC APPEND BASE=EDRRAPT.BASEL_SEC_ADJ_FACTR_MTH_SNAP (BULKLOAD=YES BL_METHOD=CLILOAD)
	DATA=DRAPT.CC_SEC_ADJ_FACTOR FORCE;
RUN;

/*DECLARATION*/
%GLOBAL QTRTIMEKEY;
%GLOBAL TOTAL_ACCOUNTS;
%GLOBAL OUTSTANDING_BALANCE;
%GLOBAL SECURI_AMT;
%GLOBAL SOURCE_ACCT_COUNT;
%GLOBAL SOURCE_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL;
%GLOBAL TGT_TOT_OS_BAL_MATCH_RT;
%GLOBAL TGT_SECURI_ADJ_RT;
%GLOBAL TGT_THRESHOLD;
%GLOBAL RETAIL_PERCENTAGE;
%GLOBAL SECURI_AMT;
%GLOBAL TM_DESC;
%GLOBAL TGT_TOT_SECRTZTN_AMT_TO_ADJUST;

/*DISPLAY IN LOG*/
%PUT MTH_TM_ID IS : &MTH_TM_ID;
%PUT &YEARMONTH;

%PUT QTRTIMEKEY IS &QTRTIMEKEY;

/*REPROCESSING LOGIC*/
PROC SQL NOPRINT;
DELETE FROM EDRRAPT.BASEL_SEC_MATCH_RT_MTH_SNAP WHERE MTH_TM_ID=&MTH_TM_ID AND SECRTZTN_TP_CD='CC';
QUIT;

/*FETCHING DATA FROM THE DATASETS WHICH STORES THE DATA FROM FILES*/
PROC SQL NOPRINT;
SELECT RETAIL_PERCENTAGE FORMAT=15.10 INTO :RETAIL_PERCENTAGE
FROM DRAPT.CC_SOURCE_FILE_AMOUNT;
QUIT;

PROC SQL NOPRINT;
SELECT SECURITIZEDAMOUNT FORMAT=15. INTO :SECURI_AMT 
FROM DRAPT.CC_SOURCE_FILE_SECURITIZATION;
QUIT;

/*CREATING THE MATCH RATE RESULTS*/

PROC SQL NOPRINT;
CREATE TABLE DRAPT.CC_ACCOUNT_MATCH_RESULTS AS 
SELECT 'CC' AS SECRTZTN_TP_CD,
t6.MTH_TM_ID,
'CREDIT CARD' AS SECRTZTN_TP_DESC,
&TOTAL_ACCOUNTS AS TOT_ACCT_CNT_RECVD,
&OUTSTANDING_BALANCE AS TOT_OS_BAL_RECVD,
COUNT(t6.UNIQUE_ACCOUNTS) AS TOT_ACCT_CNT_MATCHED,
SUM(t6.OS_BAL_AMT) FORMAT=19.3 AS TOT_OS_BAL_MATCHED,
(COUNT(t5.VISA_ACCT_NUM)/&TOTAL_ACCOUNTS)*100 AS ACCT_MATCHED_PCTG,
SUM(t6.OS_BAL_AMT)/&OUTSTANDING_BALANCE*100 AS OS_BAL_AMT_MATCHED_PCTG,
&SECURI_AMT*&RETAIL_PERCENTAGE AS TOT_SECRTZTN_AMT_TO_ADJUST,
SUM(T6.ADJUSTED_OS_BAL_AMT) FORMAT=20.8 AS TOT_ADJUSTED_OS_BAL_IN_CCAR,
(&SECURI_AMT*&RETAIL_PERCENTAGE)/SUM(T6.ADJUSTED_OS_BAL_AMT) AS SECRTZTN_OS_ADJ_FACTR,
&SESSIONTIME AS INSRT_PROCESS_TMSTMP,
&SESSIONTIME AS UPDT_PROCESS_TMSTMP
FROM DRAPT.CC_SOURCE_FILE_ACCOUNTS T5
INNER JOIN DRAPT.CC_ACCOUNTS_FROM_INSTR_FACT T6 ON T5.VISA_ACCT_NUM=T6.UNIQUE_ACCOUNTS
GROUP BY T6.MTH_TM_ID;
QUIT;

/*LOADING THE DB2 TABLES*/

PROC APPEND BASE=EDRRAPT.BASEL_SEC_MATCH_RT_MTH_SNAP (BULKLOAD=YES BL_METHOD=CLILOAD)
	DATA=DRAPT.CC_ACCOUNT_MATCH_RESULTS FORCE;
RUN;

/*SAVING THE CRITICAL VALUES INTO VARIABLES*/
PROC SQL NOPRINT;
SELECT TOT_OS_BAL_MATCHED, OS_BAL_AMT_MATCHED_PCTG, TOT_SECRTZTN_AMT_TO_ADJUST FORMAT=15., SECRTZTN_OS_ADJ_FACTR FORMAT=15.10,
CASE WHEN OS_BAL_AMT_MATCHED_PCTG>=95 THEN 'YES' ELSE 'NO, AUTHORIZATION REQUIRED' END AS THRESHOLD
INTO :TGT_TOT_OS_BAL, :TGT_TOT_OS_BAL_MATCH_RT, :TGT_TOT_SECRTZTN_AMT_TO_ADJUST, :TGT_SECURI_ADJ_RT, :TGT_THRESHOLD
FROM DRAPT.CC_ACCOUNT_MATCH_RESULTS WHERE MTH_TM_ID=&MTH_TM_ID;
QUIT;

/*EXTRACT TIME DESCRIPTION FOR THE TIME ID*/
PROC SQL NOPRINT;
SELECT TM_DESC FORMAT=$18. INTO :TM_DESC FROM NZRRAP.TM_DIM WHERE TM_ID=&MTH_TM_ID;
QUIT;


data _null_;
	infile "&rrap_dir./params/rrap/cc_securitization_email_list.txt";
	input;
	if _N_ =2 then do;
	CALL SYMPUT("to_email_list",_infile_);
	end;
	if _N_ =3 then do;
	CALL SYMPUT("cc_email_list",_infile_);
	end;
	CALL SYMPUT('MonthYear', CATX(' ',PUT(INTNX('month',"&MTH_END_DT"d,0,'E'),monname10.),PUT(YEAR(INTNX('month',"&MTH_END_DT"d,0,'E')),4.)));
run;

%put &to_email_list;
%put &cc_email_list;


/*SEND EMAIL TO IDENTIFIED RECIPIENTS*/

%MACRO SECUREMAIL;
FILENAME OUTMAIL EMAIL
SUBJECT= "[RRAP] CC Securitization Match Rates - &MonthYear. : Threshold is &TGT_TOT_OS_BAL_MATCH_RT.% - &TGT_THRESHOLD";

DATA _NULL_;
FILE OUTMAIL
TO=(&to_email_list)
CC=(&cc_email_list);
PUT "Hi,";
PUT " ";
PUT "Please see below monthly credit card securitization Match rate results.";
PUT "The month time id for this run is &TM_DESC.";
PUT " ";
PUT "1. Securitization amount received	: &SECURI_AMT";
PUT "2. Total accounts in source file		: &TOTAL_ACCOUNTS";
PUT "3. Credit card listed amount		: &OUTSTANDING_BALANCE";
PUT "4. AIRB RRAP matched amount		: &TGT_TOT_OS_BAL";
PUT "5. Outstanding balance match rate	: &TGT_TOT_OS_BAL_MATCH_RT.%";
PUT "6. Securitization adjustment rate	: &TGT_SECURI_ADJ_RT";
PUT "7. Threshold				: &TGT_THRESHOLD";
PUT " ";
PUT "Please note: This is a system generated email and responses aren't monitored.";
run;

%MEND SECUREMAIL;
%SECUREMAIL;


