 /********************************************************************************* 
 * Job:              								  							  * 
 * Description:     This job loads the Account Derived Variable                   * 
 * Source:          BASEL_REVLVNG_CR_MTH_SNAPSHOT BASEL_REVLVNG_CR_BASE_DRVD_VARS * 
 * Target:			EDRTLRP1D.BASEL_REVLVNG_CR_ACCT_DRVD_VARS_CMA				  *
 * Developed By:    Ganesh Patro                  								  * 
 * Changes:																		  *
 *********************************************************************************/ 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);


DATA _NULL_;
	CALL SYMPUTX('PROCESSSTARTTIME',PUT(DATETIME(),DATETIME25.0));
RUN;
/*
PROC SQL NOPRINT;
SELECT TM_LVL_END_DT format=YYMMDD10. INTO :MTH_END_DT FROM NZRRAP.TM_DIM WHERE TM_ID = &MTH_TM_ID.;
QUIT;
*/
/* added by VK on 21MAR2022*/
PROC SQL NOPRINT;
SELECT TM_LVL_END_DT format=date9. INTO :MTH_END_DT FROM NZRRAP.TM_DIM WHERE TM_ID = &MTH_TM_ID.;
QUIT;
/*%LET MTH_END_DT = %sysfunc(dequote("'&MTH_END_DT'")) ;*/
%put &MTH_END_DT;
%put &MTH_TM_ID;


PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (DELETE FROM &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK) BY NZCON;
QUIT;

PROC SQL ;
connect using NZRRAP as nzcon;	
         execute(
INSERT INTO &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK
SELECT 
       DR.MTH_TM_ID,
       DR.BASEL_ACCT_ID,
       DR.ACCT_NUM,
       TRIM( DR.BASEL_PRD_CD),
       TRIM(DR.CONSM_SCORECRD_EXCLSN_F),
       TRIM(DR.CONSM_PRD_TREATMNT_CD),
       DR.HELOC_F,
       TRIM(DR.PIT_STAT_VER_2_CD),
       DR.RS_F,
       DR.SML_BUS_F,
       DR.STEP_CD,
       DR.TRNST_EXCLSN_F,
       RSN.PRIM_BASEL_CUST_ID,
       RSN.STEP_PLN_SNAPSHOT_ID,
       RSN.TRNST_NUM,
       TRIM(RSN.PRD_CD),
       TRIM(RSN.BLOCK_RECL_CD),
       TRIM(RSN.ACCT_STAT_CD),
       RSN.CR_LMT_AMT,
       TRIM(RSN.CHRG_OFF_CD),
       RSN.LAST_PYMT_DT,
       RSN.TOT_NEW_BAL_AMT,
       RSN.BNS_DLQNT_DAY,
       RSN.STEP_PLN_AGRMNT_NUM  ,
       LKP.LTV_TP_CD,
       CURRENT_TIMESTAMP
FROM 
&net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT RSN,
&net_db..BASEL_REVLVNG_CR_BASE_DRVD_VARS DR,
&net_db..SRC_PRD_LKP LKP
WHERE
DR.MTH_TM_ID=RSN.MTH_TM_ID  
AND DR.BASEL_ACCT_ID=RSN.BASEL_ACCT_ID AND
RSN.PRD_CD=LKP.SRC_PRD_CD AND
RSN.SUB_PRD_CD=LKP.SRC_SUB_PRD_CD AND
LKP.PRD_SYS_CD='KS'
AND DR.SML_BUS_F='N'
AND LKP.CRNT_F='Y'
AND DR.MTH_TM_ID>=&MTH_TM_ID-960
AND DR.MTH_TM_ID<=&MTH_TM_ID
) BY NZCON;

QUIT;

PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (DELETE FROM &net_db..BASEL_REVLVNG_CR_DRVD_VAR_WRK) BY NZCON;
QUIT;

PROC SQL;
CONNECT USING NZRRAP AS NZCON;
execute(
INSERT INTO &net_db..BASEL_REVLVNG_CR_DRVD_VAR_WRK
	SELECT 
	A.BASEL_ACCT_ID,
	&MTH_TM_ID AS MTH_TM_ID,
	A.MAX_NON_DEF_TM_ID,
	A.MAX_NON_DEF_TM_ID+40,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP
	FROM 
	(SELECT
	C.BASEL_ACCT_ID AS BASEL_ACCT_ID,
	MAX(C.MTH_TM_ID) AS MAX_NON_DEF_TM_ID
	FROM
	&net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK C,
	(
	SELECT
	BASEL_ACCT_ID
	FROM
	&net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK
	WHERE
	TRIM(PIT_STAT_VER_2_CD) IN ('DEF',
	'CHG')
	AND MTH_TM_ID = &MTH_TM_ID ) P
	WHERE
	C.BASEL_ACCT_ID = P.BASEL_ACCT_ID
	AND TRIM(C.PIT_STAT_VER_2_CD)= 'CUR'
	GROUP BY
	C.BASEL_ACCT_ID) A ) BY NZCON;

QUIT;


PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (drop table &net_db..temp1_c if exists) BY NZCON;
QUIT;


PROC SQL print;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (
CREATE TABLE &net_db..temp1_c AS (
SELECT 
	A.MTH_TM_ID as MTH_TM_ID,
	A.BASEL_ACCT_ID as BASEL_ACCT_ID,
	a.PRIM_BASEL_CUST_ID as BASEL_PRIM_CUST_ID,
	A.ACCT_NUM as ACCT_NUM,
	A.LAST_PYMT_DT, /* added by VK for metic MTH_SINCE_LAST_PYMT_CNT */
	BRCD_MAXTMID.MAX_NON_DFT_TM_ID AS MAX_NON_DFT_TM_ID, /* added by vk for metric CONS_DFT_MTH_CNT */
	THPIBYDTAPRSD_DT."INDEX" AS THPIBYDTAPRSD_IDX,
	GETMTHID_DAYDT.APRSD_TM_ID AS APRSD_TM_ID,
	THPI_CURDT_APSDT."INDEX" AS THPI_CURDT_APSDT_IDX,
/*	floor(MONTHS_BETWEEN(&MTH_END_DT ,A.LAST_PYMT_DT)) as MTH_SINCE_LAST_PYMT_CNT,*/
	PHIS.HOUSE_INDEX_RTO AS HIR,
	PHIS_PROV.HOUSE_INDEX_RTO AS HIR_PROV,
	THPI_BYDT_BYCURDT."INDEX" AS THPI_BYDT_CURDT,
	UPPER(GETLABLS.LOCTN_LABEL_1) AS LOCTN_LABEL_1,
	UPPER(GETLABLS.LOCTN_LABEL_2) AS LOCTN_LABEL_2,
	THPI_CURDT_APSDT."INDEX" AS THPI_LBL_CURDT_APSDT,
	THPI_BYLBL_DFT."INDEX" AS THPI_DFT,
	GET_APRSD_VAL.APRSD_VAL AS APRSD_VAL,
	THPI_BYLBL_DFT_APSDT."INDEX" AS THPI_BYLBL_DFT_APSDT,
	CASE WHEN BRCR_DRVD_CHRG_OFF_CD.COUNT_CHRG_OFF_CD IS NULL THEN 0
		ELSE BRCR_DRVD_CHRG_OFF_CD.COUNT_CHRG_OFF_CD
	END AS DLQNT_PREV_12_MTH_CNT1,
	CASE WHEN A.TOT_NEW_BAL_AMT>A.CR_LMT_AMT 
		THEN 'Y' ELSE 'N' 
	END AS OV_LMT_F,
	A.PIT_STAT_VER_2_CD AS PIT_STAT_VER_2_CD,
	INACT12MTHF.MAX_TOT_NEW_BAL_AMT	AS i_MAX_TOT_NEW_BAL_AMT,
	INACT12MTHF.MIN_TOT_NEW_BAL_AMT	AS i_MIN_TOT_NEW_BAL_AMT,
	INACT12MTHF.CNT_TOT_NEW_BAL_AMT	AS i_CNT_TOT_NEW_BAL_AMT,
	A.BNS_DLQNT_DAY AS BNS_DLQNT_DAY,
	TRIM(CHRG_OFF_LKP.ACCRL_STAT_F) AS ACCRL_STAT_F,
	DLQNTCYCLCD.DLQNT_CYCL_CD AS DLQNT_CYCL_CD1,
	A.LTV_TP_CD AS LTV_TP_CD,
	A.TOT_NEW_BAL_AMT AS TOT_NEW_BAL_AMT,
	TRIM(A.STEP_PLN_AGRMNT_NUM) AS STEP_PLN_AGRMNT_NUM1,
	A.TRNST_NUM as TRNST_NUM,
	CASE WHEN 
			(A.CR_LMT_AMT=0 AND A.TOT_NEW_BAL_AMT>0) THEN 1
		WHEN A.TOT_NEW_BAL_AMT<0 THEN 0
		WHEN A.CR_LMT_AMT<>0 THEN ROUND((A.TOT_NEW_BAL_AMT / A.CR_LMT_AMT),4)
		ELSE 0
	END AS 	UTLTN_RTO,
	MAX_UTLTN_RTO.UTLTN_RTO	AS PAST_12_MTH_MAX_UTLTN_RTO,
	LocOsAmt.SUM_TOT_NEW_BAL_AMT AS v_RVLVNG_CR_OS_BAL_AMT_src,
	BSL_MRT_SNPST_OSAMT.SUM_OS_BAL_AMT	AS v_MORT_OS_BAL_AMT_src,
	PSNL_SNPST_OSAMT.SUM_OS_BAL_AMT AS v_SPL_OS_BAL_AMT_src,
	ISNULL(BRCD_CONSMTHCOUNT.CONS_DFT_MTH_CNT,0) AS CONS_DFT_MTH_CNT,
	A.PRD_CD AS PRD_CD,
	A.BASEL_PRD_CD AS BASEL_PRD_CD
	
FROM
	&net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK A
LEFT JOIN (                          
			SELECT asp.STEP_PLN_SNAPSHOT_ID,td.TM_ID AS  APRSD_TM_ID
			FROM &net_db..BASEL_STEP_PLN_MTH_SNAPSHOT asp
			LEFT JOIN &net_db..tm_dim td ON (CASE WHEN asp.APRSD_DT IS NULL THEN asp.CR_LMT_DT ELSE asp.APRSD_DT end) BETWEEN  TD.TM_LVL_ST_DT AND td.TM_LVL_END_DT AND TRIM(TM_LVL)='Month'
			WHERE asp.MTH_TM_ID=&MTH_TM_ID) GETMTHID_DAYDT			
			ON GETMTHID_DAYDT.STEP_PLN_SNAPSHOT_ID=a.STEP_PLN_SNAPSHOT_ID	
LEFT JOIN 
	(                          
		SELECT STEP_PLN_SNAPSHOT_ID,max(th.MTH_TM_ID) mth_id, label_1,label_2		
		FROM &net_db..BASEL_STEP_PLN_MTH_SNAPSHOT asp
		LEFT JOIN  &net_db..BASEL_STEP_PLN_BASE_DRVD_VAR_CMA dv ON asp.STEP_PLN_SNAPSHOT_ID=dv.BASEL_STEP_PLN_SNAPSHOT_ID AND asp.MTH_TM_ID= dv.MTH_TM_ID
		LEFT JOIN &net_db..tm_dim td ON (CASE WHEN asp.APRSD_DT IS NULL THEN asp.CR_LMT_DT ELSE asp.APRSD_DT end) BETWEEN  TD.TM_LVL_ST_DT AND td.TM_LVL_END_DT AND TRIM(TM_LVL)='Month'
		LEFT JOIN &net_db..TERANET_HOUSE_PRC_INDEX_CMA th
		ON UPPER(TRIM(dv.LOCTN_LABEL_1))=UPPER(TRIM(LABEL_1)) AND UPPER(TRIM(dv.LOCTN_LABEL_2))=UPPER(TRIM(LABEL_2)) AND th.MTH_TM_ID = td.TM_ID
		WHERE asp.mth_tm_id=&MTH_TM_ID
		GROUP BY STEP_PLN_SNAPSHOT_ID,asp.PRPTY_PROV_CD, label_1,label_2
	) THPI_BYDT_APRSD_DT ON A.STEP_PLN_SNAPSHOT_ID=THPI_BYDT_APRSD_DT.STEP_PLN_SNAPSHOT_ID
LEFT JOIN 	&net_db..TERANET_HOUSE_PRC_INDEX_CMA THPIBYDTAPRSD_DT 
			ON 	THPIBYDTAPRSD_DT.label_1=THPI_BYDT_APRSD_DT.label_1 
			AND THPIBYDTAPRSD_DT.label_2=THPI_BYDT_APRSD_DT.label_2 AND THPIBYDTAPRSD_DT.mth_tm_id=THPI_BYDT_APRSD_DT.mth_id
LEFT JOIN 
	(                          
		SELECT STEP_PLN_SNAPSHOT_ID,max(th.MTH_TM_ID) mth_id, label_1,label_2
		FROM &net_db..BASEL_STEP_PLN_MTH_SNAPSHOT asp
		LEFT JOIN  &net_db..BASEL_STEP_PLN_BASE_DRVD_VAR_CMA dv ON asp.STEP_PLN_SNAPSHOT_ID=dv.BASEL_STEP_PLN_SNAPSHOT_ID AND asp.MTH_TM_ID= dv.MTH_TM_ID
		LEFT JOIN &net_db..tm_dim td ON (CASE WHEN asp.APRSD_DT IS NULL THEN asp.CR_LMT_DT ELSE asp.APRSD_DT end) BETWEEN  TD.TM_LVL_ST_DT AND td.TM_LVL_END_DT AND TRIM(TM_LVL)='Month'
		LEFT JOIN &net_db..TERANET_HOUSE_PRC_INDEX_CMA th
		ON UPPER(TRIM(dv.LOCTN_LABEL_1))=UPPER(TRIM(LABEL_1)) AND UPPER(TRIM(dv.LOCTN_LABEL_2))=UPPER(TRIM(LABEL_2)) AND th.MTH_TM_ID <= td.TM_ID
		WHERE asp.mth_tm_id=&MTH_TM_ID
		GROUP BY STEP_PLN_SNAPSHOT_ID,asp.PRPTY_PROV_CD, label_1,label_2
	) THPI_BYLBL_CURDT_APRSDT ON A.STEP_PLN_SNAPSHOT_ID=THPI_BYLBL_CURDT_APRSDT.STEP_PLN_SNAPSHOT_ID

LEFT JOIN &net_db..TERANET_HOUSE_PRC_INDEX_CMA THPI_CURDT_APSDT 
	ON 	THPI_CURDT_APSDT.label_1=THPI_BYLBL_CURDT_APRSDT.label_1 
	AND THPI_CURDT_APSDT.label_2=THPI_BYLBL_CURDT_APRSDT.label_2 AND THPI_CURDT_APSDT.mth_tm_id=THPI_BYLBL_CURDT_APRSDT.mth_id
			
LEFT JOIN 	&net_db..DLQNT_DIM DLQNTCYCLCD
			ON DLQNTCYCLCD.KS_MAX_DAY_DLQNT >= A.BNS_DLQNT_DAY AND DLQNTCYCLCD.KS_MIN_DAY_DLQNT <= A.BNS_DLQNT_DAY
			AND DLQNTCYCLCD.CRNT_F='Y'
LEFT JOIN 
			(SELECT
				BASEL_ACCT_ID,
				MAX(CASE WHEN CR_LMT_AMT = 0 AND TOT_NEW_BAL_AMT>0 THEN 1 
					WHEN TOT_NEW_BAL_AMT<0 THEN 0 
					WHEN CR_LMT_AMT <> 0 THEN ROUND((TOT_NEW_BAL_AMT / CR_LMT_AMT), 4) 
					ELSE 0 END ) UTLTN_RTO
			FROM &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK
			where MTH_TM_ID>&MTH_TM_ID-480 AND MTH_TM_ID<=&MTH_TM_ID
			GROUP BY BASEL_ACCT_ID 
			ORDER BY BASEL_ACCT_ID ) MAX_UTLTN_RTO
				ON MAX_UTLTN_RTO.BASEL_ACCT_ID=A.BASEL_ACCT_ID

LEFT JOIN  &net_db..CHRG_OFF_LKP CHRG_OFF_LKP
			ON CHRG_OFF_LKP.CRNT_F = 'Y' AND  TRIM(A.CHRG_OFF_CD)=CHRG_OFF_LKP.CHRG_OFF_CD

LEFT JOIN (
			SELECT  SUM(SN.TOT_NEW_BAL_AMT) AS SUM_TOT_NEW_BAL_AMT,  SN.MTH_TM_ID AS MTH_TM_ID,  
			TRIM(SN.STEP_PLN_AGRMNT_NUM)  AS STEP_PLN_AGRMNT_NUM 
			FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT SN
				WHERE SN.STEP_PLN_SNAPSHOT_ID NOT IN(-1,-2) 
				AND TRIM(SN.PRD_CD) IN
							(SELECT SRC_PRD_CD
							 FROM &net_db..SRC_PRD_LKP
							 WHERE PRD_SYS_CD = 'KS' AND CRNT_F = 'Y' AND LTV_TP_CD = 'LOC' )
				AND SN.MTH_TM_ID=&MTH_TM_ID
				GROUP BY SN.MTH_TM_ID, SN.STEP_PLN_AGRMNT_NUM 
				ORDER BY MTH_TM_ID,STEP_PLN_AGRMNT_NUM,SUM_TOT_NEW_BAL_AMT) LocOsAmt
			ON LocOsAmt.MTH_TM_ID=A.MTH_TM_ID AND LocOsAmt.STEP_PLN_AGRMNT_NUM=A.STEP_PLN_AGRMNT_NUM
				
LEFT JOIN    &net_db..BASEL_STEP_PLN_BASE_DRVD_VAR_CMA GETLABLS 
		  	ON GETLABLS.BASEL_STEP_PLN_SNAPSHOT_ID=A.STEP_PLN_SNAPSHOT_ID AND GETLABLS.MTH_TM_ID = A.MTH_TM_ID
			and GETLABLS.MTH_TM_ID=&MTH_TM_ID
			  	
LEFT JOIN &net_db..TERANET_HOUSE_PRC_INDEX_CMA THPI_BYDT_BYCURDT
			ON 	THPI_BYDT_BYCURDT.MTH_TM_ID=A.MTH_TM_ID AND THPI_BYDT_BYCURDT.LABEL_1 = GETLABLS.LOCTN_LABEL_1 
				AND THPI_BYDT_BYCURDT.LABEL_2 = GETLABLS.LOCTN_LABEL_2
			
LEFT JOIN (SELECT 
				MAX(TOT_NEW_BAL_AMT) as MAX_TOT_NEW_BAL_AMT,
				MIN(TOT_NEW_BAL_AMT)  as MIN_TOT_NEW_BAL_AMT,
				COUNT(TOT_NEW_BAL_AMT) as  CNT_TOT_NEW_BAL_AMT,
				BASEL_ACCT_ID as BASEL_ACCT_ID 
			FROM &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK
					WHERE MTH_TM_ID>&MTH_TM_ID-480 AND
							MTH_TM_ID<=&MTH_TM_ID 
					GROUP BY BASEL_ACCT_ID ORDER BY BASEL_ACCT_ID)	INACT12MTHF	
			ON INACT12MTHF.BASEL_ACCT_ID=A.BASEL_ACCT_ID
	
LEFT JOIN  &net_db..BASEL_STEP_PLN_MTH_SNAPSHOT GET_APRSD_VAL
			ON GET_APRSD_VAL.STEP_PLN_SNAPSHOT_ID = A.STEP_PLN_SNAPSHOT_ID AND GET_APRSD_VAL.MTH_TM_ID = A.MTH_TM_ID
			and GET_APRSD_VAL.MTH_TM_ID=&MTH_TM_ID
LEFT JOIN 
			(SELECT  COUNT(CHRG_OFF_CD) AS COUNT_CHRG_OFF_CD,  BASEL_ACCT_ID AS BASEL_ACCT_ID 
				FROM &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK
			  	WHERE MTH_TM_ID >&MTH_TM_ID-480
  						AND MTH_TM_ID<=&MTH_TM_ID
 			 	 AND (TRIM(CHRG_OFF_CD) IN ('N','Q') OR  BNS_DLQNT_DAY>0) 
			  GROUP BY BASEL_ACCT_ID
			  ORDER BY BASEL_ACCT_ID) BRCR_DRVD_CHRG_OFF_CD
			 ON BRCR_DRVD_CHRG_OFF_CD.BASEL_ACCT_ID=A.BASEL_ACCT_ID 
			
LEFT JOIN 
			(SELECT  SUM(MDV.OS_BAL_AMT) AS SUM_OS_BAL_AMT,  MDV.MTH_TM_ID AS MTH_TM_ID,  TRIM(MS.STEP_PLN_AGRMNT_NUM) AS STEP_PLN_AGRMNT_NUM FROM &net_db..BASEL_MORT_ACCT_DRVD_VARS MDV, 
				 &net_db..BASEL_MORT_MTH_SNAPSHOT MS,
					 (SELECT DISTINCT STEP_PLN_SNAPSHOT_ID, STEP_PLN_AGRMNT_NUM 
						FROM &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK 
						WHERE
						 MTH_TM_ID=&MTH_TM_ID AND 
						 STEP_PLN_SNAPSHOT_ID NOT IN(-1,-2)) WRK
				 WHERE
					MDV.MTH_TM_ID=&MTH_TM_ID AND
					MS.MTH_TM_ID=&MTH_TM_ID AND
					MDV.BASEL_ACCT_ID=MS.BASEL_ACCT_ID and
					TRIM(MS.STEP_PLN_AGRMNT_NUM)= TRIM(WRK.STEP_PLN_AGRMNT_NUM)
				 GROUP BY
				 MDV.MTH_TM_ID,
				 MS.STEP_PLN_AGRMNT_NUM 
				 ORDER BY MTH_TM_ID,STEP_PLN_AGRMNT_NUM,SUM_OS_BAL_AMT)	BSL_MRT_SNPST_OSAMT		
			ON BSL_MRT_SNPST_OSAMT.MTH_TM_ID = &MTH_TM_ID 
			AND BSL_MRT_SNPST_OSAMT.STEP_PLN_AGRMNT_NUM = TRIM(A.STEP_PLN_AGRMNT_NUM)

LEFT JOIN 
			(SELECT  SUM(MDV.OS_BAL_AMT) AS SUM_OS_BAL_AMT,  MDV.MTH_TM_ID  AS MTH_TM_ID,  
				TRIM(MS.STEP_PLN_AGRMNT_NUM) AS STEP_PLN_AGRMNT_NUM FROM &net_db..BASEL_PSNL_LOAN_ACCT_DRVD_VARS MDV, 
			 	&net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT MS,
						(SELECT DISTINCT STEP_PLN_SNAPSHOT_ID, STEP_PLN_AGRMNT_NUM 
						FROM &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK 
						WHERE
						 MTH_TM_ID=&MTH_TM_ID AND 
						 STEP_PLN_SNAPSHOT_ID NOT IN(-1,-2)) WRK
				 WHERE
					 MDV.MTH_TM_ID=&MTH_TM_ID AND
					  MS.MTH_TM_ID=&MTH_TM_ID AND
					  MDV.BASEL_ACCT_ID=MS.BASEL_ACCT_ID AND
					 TRIM(MS.STEP_PLN_AGRMNT_NUM)= TRIM(WRK.STEP_PLN_AGRMNT_NUM)
				 GROUP BY
				 MDV.MTH_TM_ID,
				 MS.STEP_PLN_AGRMNT_NUM ORDER BY MTH_TM_ID,STEP_PLN_AGRMNT_NUM,SUM_OS_BAL_AMT) PSNL_SNPST_OSAMT	
			 ON  PSNL_SNPST_OSAMT.MTH_TM_ID = &MTH_TM_ID 
				AND PSNL_SNPST_OSAMT.STEP_PLN_AGRMNT_NUM = TRIM(A.STEP_PLN_AGRMNT_NUM)
				
LEFT JOIN 
			(SELECT  SUM(SN.TOT_NEW_BAL_AMT) AS SUM_TOT_NEW_BAL_AMT,  SN.MTH_TM_ID AS MTH_TM_ID,  
				TRIM(SN.STEP_PLN_AGRMNT_NUM)  AS STEP_PLN_AGRMNT_NUM FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT SN
				WHERE
					SN.STEP_PLN_SNAPSHOT_ID NOT IN(-1,-2)
					AND TRIM(SN.PRD_CD) IN
										(SELECT SRC_PRD_CD
										               FROM &net_db..SRC_PRD_LKP
										               WHERE PRD_SYS_CD = 'KS'
										               AND CRNT_F = 'Y'
										               AND LTV_TP_CD = 'LOC'
										              )
					AND SN.MTH_TM_ID=&MTH_TM_ID
					GROUP BY
					SN.MTH_TM_ID,
					SN.STEP_PLN_AGRMNT_NUM ORDER BY MTH_TM_ID,STEP_PLN_AGRMNT_NUM,SUM_TOT_NEW_BAL_AMT) RVLNG_SNPST_OSAMT
				ON  RVLNG_SNPST_OSAMT.MTH_TM_ID = &MTH_TM_ID 
				AND RVLNG_SNPST_OSAMT.STEP_PLN_AGRMNT_NUM = TRIM(A.STEP_PLN_AGRMNT_NUM) 

LEFT JOIN  &net_db..BASEL_REVLVNG_CR_DRVD_VAR_WRK BRCD_MAXTMID
			ON BRCD_MAXTMID.BASEL_ACCT_ID=A.BASEL_ACCT_ID AND BRCD_MAXTMID.MTH_TM_ID=A.MTH_TM_ID
			and BRCD_MAXTMID.MTH_TM_ID=&MTH_TM_ID

LEFT JOIN
			(SELECT  COUNT(C.MTH_TM_ID) AS CONS_DFT_MTH_CNT,  C.BASEL_ACCT_ID AS BASEL_ACCT_ID 
				FROM &net_db..BASEL_REVLVNG_CR_DRVD_VARS_WRK C, &net_db..BASEL_REVLVNG_CR_DRVD_VAR_WRK P
				WHERE
				C.BASEL_ACCT_ID=P.BASEL_ACCT_ID
				AND C.MTH_TM_ID > P.MAX_NON_DFT_TM_ID 
				AND C.MTH_TM_ID <&MTH_TM_ID
				AND TRIM(C.PIT_STAT_VER_2_CD) IN ('DEF', 'CHG')
				GROUP BY C.BASEL_ACCT_ID )	BRCD_CONSMTHCOUNT
				ON BRCD_CONSMTHCOUNT.BASEL_ACCT_ID=A.BASEL_ACCT_ID

LEFT JOIN (SELECT
				INDEX AS "INDEX",MTH_TM_ID AS MTH_TM_ID,UPPER(TRIM(LABEL_1)) AS LABEL_1,UPPER(TRIM(LABEL_2)) AS LABEL_2
			FROM &net_db..TERANET_HOUSE_PRC_INDEX_CMA WHERE
				UPPER(TRIM(LABEL_1))= 'COMPOSITE' AND UPPER(TRIM(LABEL_2))= '11' AND MTH_TM_ID <= &MTH_TM_ID
			ORDER BY UPPER(TRIM(LABEL_1)),UPPER(TRIM(LABEL_2)),MTH_TM_ID DESC LIMIT 1) THPI_BYLBL_DFT
			ON UPPER(TRIM(THPI_BYLBL_DFT.LABEL_1))= 'COMPOSITE' AND UPPER(TRIM(THPI_BYLBL_DFT.LABEL_2))= '11'	
LEFT JOIN (SELECT STEP_PLN_SNAPSHOT_ID, max(th.mth_tm_id) mth_tm_id 
			FROM 
				(SELECT asp.STEP_PLN_SNAPSHOT_ID AS STEP_PLN_SNAPSHOT_ID,td.TM_ID AS  APRSD_TM_ID
							FROM &net_db..BASEL_STEP_PLN_MTH_SNAPSHOT asp
							LEFT JOIN &net_db..tm_dim td ON (CASE WHEN asp.APRSD_DT IS NULL THEN asp.CR_LMT_DT ELSE asp.APRSD_DT end) BETWEEN  TD.TM_LVL_ST_DT AND td.TM_LVL_END_DT AND TRIM(TM_LVL)='Month'
							WHERE asp.MTH_TM_ID=&MTH_TM_ID 
							) THPI_BYLBL_DFT_APSDT1			
			
LEFT JOIN 	&net_db..TERANET_HOUSE_PRC_INDEX_CMA TH ON UPPER(TRIM(th.LABEL_1))='COMPOSITE' AND UPPER(TRIM(th.LABEL_2))='11' 
																AND th.MTH_TM_ID <= THPI_BYLBL_DFT_APSDT1.APRSD_TM_ID			
GROUP BY STEP_PLN_SNAPSHOT_ID
) ee  ON ee.STEP_PLN_SNAPSHOT_ID=a.STEP_PLN_SNAPSHOT_ID

LEFT JOIN &net_db..TERANET_HOUSE_PRC_INDEX_CMA THPI_BYLBL_DFT_APSDT ON 	
UPPER(TRIM(THPI_BYLBL_DFT_APSDT.LABEL_1))='COMPOSITE' AND UPPER(TRIM(THPI_BYLBL_DFT_APSDT.LABEL_2))='11' AND 
THPI_BYLBL_DFT_APSDT.MTH_TM_ID = ee.MTH_TM_ID



LEFT JOIN &net_db..PROVNCL_HOUSE_INDEX_SUM_CMA PHIS 
	ON 	PHIS.PROV_CD=GET_APRSD_VAL.PRPTY_PROV_CD 
	AND PHIS.mth_tm_id=GETMTHID_DAYDT.APRSD_TM_ID

LEFT JOIN &net_db..PROVNCL_HOUSE_INDEX_SUM_CMA PHIS_PROV 
	ON 	PHIS_PROV.PROV_CD=GET_APRSD_VAL.PRPTY_PROV_CD 
	AND PHIS_PROV.mth_tm_id=A.MTH_TM_ID

WHERE A.MTH_TM_ID=&MTH_TM_ID 
) with data	

) BY NZCON;
QUIT;


data LOAD
(KEEP=

MTH_TM_ID BASEL_ACCT_ID BASEL_PRIM_CUST_ID ACCT_NUM APRSD_VAL_TERANET_INDEXED_AMT CONS_DFT_MTH_CNT 
DLQNT_CYCL_CD DLQNT_PREV_12_MTH_CNT INACT_12_MTH_F LTV_TP_CD LOAN_TO_VAL_WITHOUT_INDEX_RTO 
LOAN_TO_VAL_WITH_TERANET_INDEX_R 
MTH_SINCE_LAST_PYMT_CNT OS_BAL_AMT OV_LMT_F PAST_12_MTH_MAX_UTLTN_RTO PREV_12_MTH_DLQNT_F
TERANET_HOUSE_APRSD_DT_INDEX TERANET_HOUSE_INDEX UTLTN_RTO TRNST_NUM HELOC_PRD_TP   
INSRT_PROCESS_TMSTMP UPDT_PROCESS_TMSTMP 
);
set NZRRAP.temp1_c;
RETAIN 
MTH_TM_ID BASEL_ACCT_ID BASEL_PRIM_CUST_ID ACCT_NUM APRSD_VAL_TERANET_INDEXED_AMT CONS_DFT_MTH_CNT 
DLQNT_CYCL_CD DLQNT_PREV_12_MTH_CNT INACT_12_MTH_F LTV_TP_CD LOAN_TO_VAL_WITHOUT_INDEX_RTO 
LOAN_TO_VAL_WITH_TERANET_INDEX_R MTH_SINCE_LAST_PYMT_CNT OS_BAL_AMT OV_LMT_F PAST_12_MTH_MAX_UTLTN_RTO PREV_12_MTH_DLQNT_F
TERANET_HOUSE_APRSD_DT_INDEX TERANET_HOUSE_INDEX UTLTN_RTO TRNST_NUM HELOC_PRD_TP THPI_BYLBL_DFT_APSDT  
INSRT_PROCESS_TMSTMP UPDT_PROCESS_TMSTMP;

format
MTH_TM_ID 10. BASEL_ACCT_ID 19. BASEL_PRIM_CUST_ID 19. ACCT_NUM $50. THPI_BYLBL_DFT_APSDT 8.4
APRSD_VAL_TERANET_INDEXED_AMT 17.3 v_T_IDX_BY_TM_ID 8.4 v_T_IDX_BY_APRSD_TM_ID 8.4 v_APSD_VAL_TNT_IDX_AMT 17.3
TERANET_HOUSE_APRSD_DT_INDEX 8.4 OV_LMT_F $1. TRNST_NUM $5.
TERANET_HOUSE_INDEX 8.4 DLQNT_PREV_12_MTH_CNT 5. INACT_12_MTH_F $1. DLQNT_CYCL_CD $10. PREV_12_MTH_DLQNT_F $1.
CONS_DFT_MTH_CNT 5.  LTV_TP_CD $10. OS_BAL_AMT 17.3 PAST_12_MTH_MAX_UTLTN_RTO 11.4 LOAN_TO_VAL_WITH_TERANET_INDEX_R 11.4
LOAN_TO_VAL_WITHOUT_INDEX_RTO 11.4 UTLTN_RTO 11.4 HELOC_PRD_TP $10. MTH_SINCE_LAST_PYMT_CNT 10.
v_T_IDX_APRD_ID_chkd 8.4 v_TIDX_APRSD_TMID_PROV 11.4 HIR 11.4 THPI_BYDT_CURDT 8.4 LOCTN_LABEL_1 $20. 
LOCTN_LABEL_2 $20. THPI_LBL_CURDT_APSDT 8.4 v_T_IDX_BY_TM_ID_Chk 8.4 v_T_IDX_BY_TM_ID_PROV 11.4 THPI_DFT 8.4
v_LN_TO_VAL_WTH_TNET_IDX_RTO 17.4 
INSRT_PROCESS_TMSTMP datetime25.6 UPDT_PROCESS_TMSTMP datetime25.6
  
v_TOTAL_OS_AMT_MO_SPL_KS 17.3 APRSD_VAL 17.3 v_LOAN_TO_VAL_WITHOUT_INDEX_RTO 17.4
v_MORT_OS_BAL_AMT 17.3
v_SPL_OS_BAL_AMT 17.3
v_VISA_LOC_OS_BAL_AMT 17.3
TOT_NEW_BAL_AMT 17.3
v_RVLVNG_CR_OS_BAL_AMT 17.3
v_RVLVNG_CR_OS_BAL_AMT_src v
v_SPL_OS_BAL_AMT 17.3
v_SPL_OS_BAL_AMT_src 17.3
v_MORT_OS_BAL_AMT_src 17.3
v_MORT_OS_BAL_AMT 17.3;
INSRT_PROCESS_TMSTMP="&SYSDATE9.:&SYSTIME."dt;
UPDT_PROCESS_TMSTMP ="&SYSDATE9.:&SYSTIME."dt;

/*v_T_IDX_APRD_ID_chkd*/
if ((THPIBYDTAPRSD_IDX EQ . OR THPIBYDTAPRSD_IDX EQ '') AND NOT (APRSD_TM_ID eq . OR APRSD_TM_ID eq ''))then do ; 
	v_T_IDX_APRD_ID_chkd=THPI_CURDT_APSDT_IDX; end;
else if ((THPIBYDTAPRSD_IDX EQ . OR THPIBYDTAPRSD_IDX EQ '') AND (APRSD_TM_ID eq . OR APRSD_TM_ID eq '')) THEN do;  v_T_IDX_APRD_ID_chkd= .; end;
else do; v_T_IDX_APRD_ID_chkd=THPIBYDTAPRSD_IDX; end;

/*v_TIDX_APRSD_TMID_PROV*/
IF ((v_T_IDX_APRD_ID_chkd EQ . or v_T_IDX_APRD_ID_chkd EQ '')  AND NOT (APRSD_TM_ID eq . OR APRSD_TM_ID eq '')) THEN DO; 
	v_TIDX_APRSD_TMID_PROV=HIR;END;
ELSE IF (v_T_IDX_APRD_ID_chkd EQ . or v_T_IDX_APRD_ID_chkd EQ '') AND (APRSD_TM_ID eq . OR APRSD_TM_ID eq '') THEN DO;
	v_TIDX_APRSD_TMID_PROV=.;END;
ELSE DO;v_TIDX_APRSD_TMID_PROV=v_T_IDX_APRD_ID_chkd;END;

/*v_T_IDX_BY_APRSD_TM_ID*/
IF ((v_TIDX_APRSD_TMID_PROV EQ . OR v_TIDX_APRSD_TMID_PROV EQ '')  AND NOT (APRSD_TM_ID eq . OR APRSD_TM_ID eq '')) THEN DO;
	v_T_IDX_BY_APRSD_TM_ID=THPI_BYLBL_DFT_APSDT;END;
ELSE IF ((v_TIDX_APRSD_TMID_PROV EQ . OR v_TIDX_APRSD_TMID_PROV EQ '')  AND (APRSD_TM_ID eq . OR APRSD_TM_ID eq '')) THEN DO;
		v_T_IDX_BY_APRSD_TM_ID=.;END;
ELSE DO; v_T_IDX_BY_APRSD_TM_ID=v_TIDX_APRSD_TMID_PROV;END;

TERANET_HOUSE_APRSD_DT_INDEX=ROUND(v_T_IDX_BY_APRSD_TM_ID,.0001);

/*v_T_IDX_BY_TM_ID_Chk*/
IF ((THPI_BYDT_CURDT EQ . or THPI_BYDT_CURDT eq '') AND NOT (LOCTN_LABEL_1 eq '') AND NOT (LOCTN_LABEL_2 eq '') ) THEN DO;
	v_T_IDX_BY_TM_ID_Chk=THPI_LBL_CURDT_APSDT;END;
ELSE DO; v_T_IDX_BY_TM_ID_Chk=THPI_BYDT_CURDT;END;

/*v_T_IDX_BY_TM_ID_PROV*/
IF (v_T_IDX_BY_TM_ID_Chk EQ '' or v_T_IDX_BY_TM_ID_Chk EQ .) THEN DO; v_T_IDX_BY_TM_ID_PROV=HIR_PROV; END;
ELSE DO; v_T_IDX_BY_TM_ID_PROV=v_T_IDX_BY_TM_ID_Chk; END;

/*v_T_IDX_BY_TM_ID*/
IF (v_T_IDX_BY_TM_ID_PROV EQ '' OR v_T_IDX_BY_TM_ID_PROV EQ .) THEN DO; 
	v_T_IDX_BY_TM_ID=THPI_DFT;end;
ELSE DO; v_T_IDX_BY_TM_ID=v_T_IDX_BY_TM_ID_PROV; END;

TERANET_HOUSE_INDEX=v_T_IDX_BY_TM_ID;

/*v_APSD_VAL_TNT_IDX_AMT*/
IF( (APRSD_TM_ID eq . OR APRSD_TM_ID eq '') OR (APRSD_VAL eq . OR APRSD_VAL eq '') ) THEN DO;
 	v_APSD_VAL_TNT_IDX_AMT=.;END;
ELSE IF (v_T_IDX_BY_APRSD_TM_ID EQ '' OR v_T_IDX_BY_APRSD_TM_ID = . OR v_T_IDX_BY_APRSD_TM_ID=0) THEN DO;
	v_APSD_VAL_TNT_IDX_AMT=.;END;
ELSE DO; v_APSD_VAL_TNT_IDX_AMT=ROUND(((APRSD_VAL * v_T_IDX_BY_TM_ID) / v_T_IDX_BY_APRSD_TM_ID),.001) ; END;

APRSD_VAL_TERANET_INDEXED_AMT=v_APSD_VAL_TNT_IDX_AMT;
DLQNT_PREV_12_MTH_CNT=DLQNT_PREV_12_MTH_CNT1;

/*INACT_12_MTH_F*/
IF ( TRIM(PIT_STAT_VER_2_CD)='CUR' AND (i_MAX_TOT_NEW_BAL_AMT-i_MIN_TOT_NEW_BAL_AMT=0 AND i_CNT_TOT_NEW_BAL_AMT=12))
	THEN DO; INACT_12_MTH_F='Y'; END;
ELSE DO; INACT_12_MTH_F='N';END;

/*DLQNT_CYCL_CD */
IF ACCRL_STAT_F EQ 'N' THEN DO;
	DLQNT_CYCL_CD='E';END;
ELSE IF (ACCRL_STAT_F EQ '' OR ACCRL_STAT_F NE 'N') THEN DO;
	DLQNT_CYCL_CD=DLQNT_CYCL_CD1;END;
ELSE DO; DLQNT_CYCL_CD='';END;


/*PREV_12_MTH_DLQNT_F*/
IF  DLQNT_PREV_12_MTH_CNT1 EQ 0 THEN DO; PREV_12_MTH_DLQNT_F='N';END;
ELSE DO; PREV_12_MTH_DLQNT_F='Y';END;
	
OS_BAL_AMT=TOT_NEW_BAL_AMT;

/*v_MORT_OS_BAL_AMT*/
IF(v_MORT_OS_BAL_AMT_src EQ .) THEN DO;
	v_MORT_OS_BAL_AMT=0;END;
ELSE DO; v_MORT_OS_BAL_AMT=v_MORT_OS_BAL_AMT_src;END;

/*v_SPL_OS_BAL_AMT*/
IF(v_SPL_OS_BAL_AMT_src EQ '' OR v_SPL_OS_BAL_AMT_src EQ .) THEN DO;
	v_SPL_OS_BAL_AMT=0;END;
ELSE DO; v_SPL_OS_BAL_AMT=v_SPL_OS_BAL_AMT_src;END;

/*v_RVLVNG_CR_OS_BAL_AMT*/
IF(v_RVLVNG_CR_OS_BAL_AMT_src EQ '' OR v_RVLVNG_CR_OS_BAL_AMT_src EQ .) THEN DO;
	v_RVLVNG_CR_OS_BAL_AMT=0;END;
ELSE DO; v_RVLVNG_CR_OS_BAL_AMT=v_RVLVNG_CR_OS_BAL_AMT_src;END;

/*v_VISA_LOC_OS_BAL_AMT*/

IF TRIM(LTV_TP_CD) EQ 'LOC' THEN DO; v_VISA_LOC_OS_BAL_AMT=TOT_NEW_BAL_AMT; END;
ELSE IF TRIM(LTV_TP_CD) EQ 'VISA' THEN DO; v_VISA_LOC_OS_BAL_AMT=(TOT_NEW_BAL_AMT+v_RVLVNG_CR_OS_BAL_AMT);END;
ELSE DO;v_VISA_LOC_OS_BAL_AMT=0; END;

v_TOTAL_OS_AMT_MO_SPL_KS=v_MORT_OS_BAL_AMT+v_SPL_OS_BAL_AMT+v_VISA_LOC_OS_BAL_AMT;

/*v_LN_TO_VAL_WTH_TNET_IDX_RTO*/
IF (APRSD_VAL_TERANET_INDEXED_AMT EQ '' OR APRSD_VAL_TERANET_INDEXED_AMT EQ .) THEN DO;
	v_LN_TO_VAL_WTH_TNET_IDX_RTO=.; END; /* update 0 with . value by vk 18MAR2022*/

	/* newly added to address 0 value 18MAR2022*/
IF APRSD_VAL_TERANET_INDEXED_AMT = 0 then do;
v_LN_TO_VAL_WTH_TNET_IDX_RTO=0; END;
ELSE DO; v_LN_TO_VAL_WTH_TNET_IDX_RTO=ROUND((v_TOTAL_OS_AMT_MO_SPL_KS/APRSD_VAL_TERANET_INDEXED_AMT),.0001);END;

/*v_LOAN_TO_VAL_WITHOUT_INDEX_RTO*/
IF APRSD_VAL EQ '' OR APRSD_VAL EQ . THEN DO; v_LOAN_TO_VAL_WITHOUT_INDEX_RTO=.; /* updated 0 with . value by vk 18MAR2022 */ END;
IF APRSD_VAL = 0 then do; v_LOAN_TO_VAL_WITHOUT_INDEX_RTO = 0; end;/* newly added to address 0 value by vk on 18MAR2022*/
ELSE DO;v_LOAN_TO_VAL_WITHOUT_INDEX_RTO=ROUND((v_TOTAL_OS_AMT_MO_SPL_KS/APRSD_VAL),.0001); END;

/*LOAN_TO_VAL_WITH_TERANET_INDEX_R*/
IF (v_LN_TO_VAL_WTH_TNET_IDX_RTO EQ '' OR v_LN_TO_VAL_WTH_TNET_IDX_RTO EQ .) THEN DO; 
	LOAN_TO_VAL_WITH_TERANET_INDEX_R=.; END; /* update 0 with . value by vk 18MAR2022*/
ELSE DO; LOAN_TO_VAL_WITH_TERANET_INDEX_R=v_LN_TO_VAL_WTH_TNET_IDX_RTO; END;

/*LOAN_TO_VAL_WITHOUT_INDEX_RTO*/
IF (v_LOAN_TO_VAL_WITHOUT_INDEX_RTO EQ '' OR v_LOAN_TO_VAL_WITHOUT_INDEX_RTO EQ .) THEN DO; 
	LOAN_TO_VAL_WITHOUT_INDEX_RTO=.; END; /* updated 0 with . value by vk 18MAR2022*/
ELSE DO; LOAN_TO_VAL_WITHOUT_INDEX_RTO=v_LOAN_TO_VAL_WITHOUT_INDEX_RTO; END;


IF PRD_CD='VIC' THEN DO; HELOC_PRD_TP= 'CC';END;
ELSE DO; HELOC_PRD_TP= BASEL_PRD_CD; END;

/* added by vk for metric CONS_DFT_MTH_CNT */
/*v_CONS_DFT_MTH_CNT_CHEK_NULL*/
IF STRIP(PIT_STAT_VER_2_CD) NOT IN ('DEF','CHG') OR  PIT_STAT_VER_2_CD = '' /*OR PIT_STAT_VER_2_CD '' */
THEN v_CONS_DFT_MTH_CNT_CHEK_NULL = '';
ELSE v_CONS_DFT_MTH_CNT_CHEK_NULL = PIT_STAT_VER_2_CD;


/*v_CONS_DFT_MTH_CNT_lkp*/
IF(v_CONS_DFT_MTH_CNT_CHEK_NULL = '') 
THEN v_CONS_DFT_MTH_CNT_lkp = -999;
ELSE v_CONS_DFT_MTH_CNT_lkp = CONS_DFT_MTH_CNT;


/*CONS_DFT_MTH_CNT*/
IF v_CONS_DFT_MTH_CNT_lkp = -999 THEN DO CONS_DFT_MTH_CNT = .;END;
ELSE IF v_CONS_DFT_MTH_CNT_lkp = . AND MAX_NON_DFT_TM_ID NE . THEN DO CONS_DFT_MTH_CNT = 0;END;
ELSE IF (v_CONS_DFT_MTH_CNT_lkp = . OR v_CONS_DFT_MTH_CNT_lkp = 0)  AND MAX_NON_DFT_TM_ID = . THEN DO CONS_DFT_MTH_CNT = 24; END;
ELSE DO CONS_DFT_MTH_CNT = v_CONS_DFT_MTH_CNT_lkp; END;
/*MTH_SINCE_LAST_PYMT_CNT*/ /* removed from &net_db..temp1 and added here by VK 21MAR2022 */
MTH_SINCE_LAST_PYMT_CNT = intck("month",LAST_PYMT_DT,"&MTH_END_DT."d); 
run;






/***** Added by VK to address column length value */

/* Delete if TEMP table exists and create TEMP table */
%macro check_table;
  %if %sysfunc(exist(NZRRAP.BSL_REVLV_CR_ACCT_DRVD_VARS_TMP)) %then %do;
    %put The table exists.;
	   PROC SQL NOPRINT;
	    CONNECT USING NZRRAP AS NZCON;
	     EXECUTE(drop table &net_db..BSL_REVLV_CR_ACCT_DRVD_VARS_TMP 
			) BY NZCON;
		QUIT;
  %end;
PROC SQL NOPRINT;
         	CONNECT USING NZRRAP AS NZCON;
         	EXECUTE(create table &net_db..BSL_REVLV_CR_ACCT_DRVD_VARS_TMP  as 
			(select MTH_TM_ID,
				BASEL_ACCT_ID,
				BASEL_PRIM_CUST_ID,
				ACCT_NUM,
				APRSD_VAL_TERANET_INDEXED_AMT,
				CONS_DFT_MTH_CNT,
				DLQNT_CYCL_CD,
				DLQNT_PREV_12_MTH_CNT,
				INACT_12_MTH_F,
				LOAN_TO_VAL_WITH_TERANET_INDEX_RTO as LOAN_TO_VAL_WITH_TERANET_INDEX_R,
				LOAN_TO_VAL_WITHOUT_INDEX_RTO,
				LTV_TP_CD,
				MTH_SINCE_LAST_PYMT_CNT,
				OS_BAL_AMT,
				OV_LMT_F,
				PAST_12_MTH_MAX_UTLTN_RTO,
				PREV_12_MTH_DLQNT_F,
				TERANET_HOUSE_APRSD_DT_INDEX,
				TERANET_HOUSE_INDEX,
				TRNST_NUM,
				UTLTN_RTO,
				HELOC_PRD_TP,
				INSRT_PROCESS_TMSTMP,
				UPDT_PROCESS_TMSTMP
			 FROM &net_db..BASEL_REVLVNG_CR_ACCT_DRVD_VARS_CMA) WITH NO DATA
			) BY NZCON;
		QUIT;
      %Put New Table Created;
 
%mend;

%check_table;
PROC SQL NOPRINT;
         	CONNECT USING NZRRAP AS NZCON;
         	EXECUTE(DELETE FROM &net_db..BSL_REVLV_CR_ACCT_DRVD_VARS_TMP WHERE MTH_TM_ID=&MTH_TM_ID.) BY NZCON;
 QUIT;

 proc append base=NZRRAP.BSL_REVLV_CR_ACCT_DRVD_VARS_TMP  (BULKLOAD=YES BL_METHOD=CLILOAD)
				data=LOAD force ; run;



PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (DELETE FROM &net_db..BASEL_REVLVNG_CR_ACCT_DRVD_VARS_CMA WHERE MTH_TM_ID = &MTH_TM_ID) BY NZCON;
QUIT;

PROC SQL NOPRINT;
connect using NZRRAP as nzcon;	
         execute(
	INSERT INTO &net_db..BASEL_REVLVNG_CR_ACCT_DRVD_VARS_CMA(
				MTH_TM_ID,
				BASEL_ACCT_ID,
				BASEL_PRIM_CUST_ID,
				ACCT_NUM,
				APRSD_VAL_TERANET_INDEXED_AMT,
				CONS_DFT_MTH_CNT,
				DLQNT_CYCL_CD,
				DLQNT_PREV_12_MTH_CNT,
				INACT_12_MTH_F,
				LOAN_TO_VAL_WITH_TERANET_INDEX_RTO,
				LOAN_TO_VAL_WITHOUT_INDEX_RTO,
				LTV_TP_CD,
				MTH_SINCE_LAST_PYMT_CNT,
				OS_BAL_AMT,
				OV_LMT_F,
				PAST_12_MTH_MAX_UTLTN_RTO,
				PREV_12_MTH_DLQNT_F,
				TERANET_HOUSE_APRSD_DT_INDEX,
				TERANET_HOUSE_INDEX,
				TRNST_NUM,
				UTLTN_RTO,
				HELOC_PRD_TP,
				INSRT_PROCESS_TMSTMP,
				UPDT_PROCESS_TMSTMP)
	SELECT 
			MTH_TM_ID,
				BASEL_ACCT_ID,
				BASEL_PRIM_CUST_ID,
				ACCT_NUM,
				APRSD_VAL_TERANET_INDEXED_AMT,
				CONS_DFT_MTH_CNT,
				DLQNT_CYCL_CD,
				DLQNT_PREV_12_MTH_CNT,
				INACT_12_MTH_F,
				LOAN_TO_VAL_WITH_TERANET_INDEX_R as LOAN_TO_VAL_WITH_TERANET_INDEX_RTO,
				LOAN_TO_VAL_WITHOUT_INDEX_RTO,
				LTV_TP_CD,
				MTH_SINCE_LAST_PYMT_CNT,
				OS_BAL_AMT,
				OV_LMT_F,
				PAST_12_MTH_MAX_UTLTN_RTO,
				PREV_12_MTH_DLQNT_F,
				TERANET_HOUSE_APRSD_DT_INDEX,
				TERANET_HOUSE_INDEX,
				TRNST_NUM,
				UTLTN_RTO,
				HELOC_PRD_TP,
				INSRT_PROCESS_TMSTMP,
				UPDT_PROCESS_TMSTMP
	FROM &net_db..BSL_REVLV_CR_ACCT_DRVD_VARS_TMP
	) BY NZCON;
QUIT;

PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (drop table &net_db..temp1_c if exists) BY NZCON;
QUIT;
PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (drop table &net_db..BSL_REVLV_CR_ACCT_DRVD_VARS_TMP if exists) BY NZCON;
QUIT;

/************************ END ****************************/
 