/**************************************************************************** 
 * Job:             J_RRAP_TL10_2109_BASEL_PSNL_LN_ACCT_  A57SWEI7.BH0009IE * 
 *                  SC_DRVD_VAR                                             * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/02 - Term Loans/2.1                 * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:38:16 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009IE);
%let etls_jobName = %nrquote(J_RRAP_TL10_2109_BASEL_PSNL_LN_ACCT_SC_DRVD_VAR);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_spl_autoexec                  A57SWEI7.BK000YUC * 
 * Transform:       AM_rrap_spl_autoexec                                    * 
 * Description:     Autoexec file for termloan jobs. This points to auto    * 
 *                   call macros                                            * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000YUC);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_spl_autoexec;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_spl_autoexec **/

/*---- Start of User Written Code  ----*/ 


%let product=SPL;
%let datatype=ACCT;

/* These macro variables were originally in the template, but */
/* inconsistent names for the RRAP output table forced the    */
/* move into the wrapper.                                     */
%let input_table=SCRD_VAR_STATS_SPL_ACCT; 
%let output_table=BASEL_PSNL_LN_ACCT_SC_DRVD_VAR;



/* Find the start and end dates being processed.  In the event of a rerun, the code deletes this data */
/* from the target before loading. */

%get_period_dates(product=&product, process=scrd);

%put Start and End Dates for &product Scorecards:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;

 /**** CONTROL TABLE ************************************************************************/
proc sql noprint;
	select TM_ID into :mth_tm_id
	from nzrrap.TM_DIM
	where tm_lvl='Month' and tm_lvl_end_dt = "&start_period_dt"d;

	select TM_ID into :end_mth_tm_id
	from nzrrap.TM_DIM
	where tm_lvl='Month' and tm_lvl_end_dt = "&end_period_dt"d;
quit;
%let MODULE=TL;
%let BATCH=2.1;
%etl_job_start(TARGET_TABLE=NZRRAP.BASEL_PSNL_LN_ACCT_SC_DRVD_VAR,MULTI_MONTH=Y);
/**** CONTROL TABLE ************************************************************************/

/* Get the tm_id for the start and end dates being processed */
/* Notice that for the load to the target table, we are only */
/* concerned with the exact start and end dates.  In the     */
/* initial scorecard vars extract, we changed the start date */
/* to pull data for the 24 month lookback.                   */
proc sql noprint;
select tm_key into :start_period_tm_key
from control.tm_id_lkp
where sas_date="&start_period_dt"d;
quit;

proc sql noprint;
select tm_key into :end_period_tm_key
from control.tm_id_lkp
where sas_date="&end_period_dt"d;
quit;


%put start_period_tm_key: &start_period_tm_key;
%put end_period_tm_key: &end_period_tm_key;
 

%macro delete_previously_loaded_data;
        /*---------------------------------------------
        * Checks to see if the date is in NZ table 
        *---------------------------------------------*/

       proc sql noprint;
          select count(*) 
          into :date_count trimmed
          from NZRRAP.&output_table
          where mth_tm_id between &start_period_tm_key and &end_period_tm_key;
       quit;


      /*---------------------------------------------
       * If data already exists for the month, the 
       * run delete from code.
       *---------------------------------------------*/

      %if %eval(&date_count) > 0 %then
      %do;
         proc sql;
            connect using NZRRAP as nzcon;
            execute (
               
               delete from %nrbquote(&RRAP_DB..&output_table)
               where mth_tm_id between &start_period_tm_key and &end_period_tm_key  

            ) by nzcon;
            
		execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&RRAP_DB..&output_table) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
            disconnect from nzcon;
         quit;
      %end;   

%mend delete_previously_loaded_data;
 

%delete_previously_loaded_data;


proc sql;
connect using NZRRAP as nzcon;
execute(   
   insert into %nrbquote(&RRAP_DB..&output_table) 
   select a.basel_acct_id,
          a.mth_tm_id,
          a.basel_cust_id, 
          a.amort_left, 
          a.daysovermax6m, 
          a.ind_delqmax24m, 
          a.ind_delqsum24m, 
          a.ind_joint, 
          cast(round(a.ltv_veh10,4) as decimal(11,4)),  
          a.subv_flag, 
          a.pe_num_of_months_since_last_paym, 
          cast(round(a.ltv_veh5,4) as decimal(11,4)),
          now() as insrt_process_tmstmp,
          now() as updt_process_tmstmp  
   from %nrbquote(&frg_db..&input_table) as a
   where mth_tm_id between &start_period_tm_key and &end_period_tm_key;
            
) by nzcon;
execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&RRAP_DB..&output_table) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
disconnect from nzcon;
quit;

%etl_job_end;
/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

