/**************************************************************************** 
 * Job:             J_RRAP_CCAR_ACAP_AUDIT_CHECKS         A57SWEI7.BH000LHH * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503                                                * 
 * Port:            8563                                                    * 
 *                    									    * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * CREATED on:    APR 05, 2023 9:00:00 AM EDT            	    		    * 
 * CREATED by:    DHAIVAT                                                   * 
 ****************************************************************************/ 

 %RRAP_AUTOEXEC								/*UNCOMMENT FOR PROD VERSION*/
/*%LET MTH_TM_ID=19636;*/						/*COMMENT FOR PROD*/ /*UNCOMMENT AND SUPPLY A VALUE IF TO BE RUN IN LOWER ENVIRONMENT FOR A DIFFERENT MONTH*/

%LET PREV_MTH_TM_ID=%EVAL(&MTH_TM_ID-40);				/*UNCOMMENT FOR PROD VERSION*/
/*%LET PREV_MTH_TM_ID=19516;*/					/*COMMENT FOR PROD*/ /*UNCOMMENT AND SUPPLY A VALUE IF TO BE RUN IN LOWER ENVIRONMENT FOR A DIFFERENT MONTH*/


PROC SQL;
	SELECT CLNDR_YR INTO:CURR_CAL_YR FROM NZRRAP.TM_DIM WHERE TM_LVL = 'Month' AND TM_ID = &MTH_TM_ID;
	SELECT CLNDR_YR INTO:PREV_CAL_YR FROM NZRRAP.TM_DIM WHERE TM_LVL = 'Month' AND TM_ID = &PREV_MTH_TM_ID;
	SELECT MTH_CLNDR_CD INTO:CURR_MONTH FROM NZRRAP.TM_DIM WHERE TM_LVL = 'Month' AND TM_ID = &MTH_TM_ID;
	SELECT MTH_CLNDR_CD INTO:PREV_MONTH FROM NZRRAP.TM_DIM WHERE TM_LVL = 'Month' AND TM_ID = &PREV_MTH_TM_ID;
	SELECT TM_LVL_END_DT INTO:CURR_MTH_END_DT FROM NZRRAP.TM_DIM WHERE TM_LVL = 'Month' AND TM_ID = &MTH_TM_ID;
	SELECT TM_LVL_END_DT INTO:PREV_MTH_END_DT FROM NZRRAP.TM_DIM WHERE TM_LVL = 'Month' AND TM_ID = &PREV_MTH_TM_ID;
QUIT;

DATA _NULL_;
	CALL SYMPUT('CURR',CATX("-","&CURR_MONTH","&CURR_CAL_YR"));
	CALL SYMPUT('PREV',CATX("-","&PREV_MONTH","&PREV_CAL_YR"));
	CALL SYMPUT('MonthYear',CATX(' ',"&CURR_MONTH","&CURR_CAL_YR"));
RUN;

%PUT &=MTH_TM_ID;
%PUT &=PREV_MTH_TM_ID;
%PUT &=CURR;
%PUT &=PREV;
%PUT &=CURR_MTH_END_DT;
%PUT &=PREV_MTH_END_DT;

PROC FORMAT;
	VALUE GTEQ5LTEQ
		LOW - -0.05 = 'YELLOW'
		0.05 - HIGH = 'YELLOW'
		OTHER = 'WHITE';
	VALUE GTEQ10LTEQ
		LOW - -0.1 = 'YELLOW'
		0.1 - HIGH = 'YELLOW'
		OTHER = 'WHITE';
	VALUE BKG_PD_CURVE
		0 = 'WHITE'
		OTHER = 'YELLOW';
	VALUE $BKG_PD_CURVE_TF
		'TRUE' = 'WHITE'
		'FALSE' = 'YELLOW';
	VALUE $DLGD
		'Downturn_LGD<Loss_Given_Default' = 'YELLOW'
		OTHER = 'WHITE';
	VALUE $UNINSURED_DLGD
		'Uninsured_DLGD<Uninsured_LGD' = 'YELLOW'
		OTHER = 'WHITE';
      VALUE F_INSURANCE
		LOW - -0.05 = 'YELLOW'
		0.05 - HIGH = 'YELLOW'
		OTHER = 'WHITE';
RUN;

/*IMPORT AND PROCESS CCAR DATA*/

Data CCAR;
	set NZRRAP.RRAP_CCAR_ACAP_FILES;
	WHERE MTH_TM_ID IN (&MTH_TM_ID,&PREV_MTH_TM_ID);
run;

DATA TEMP;
	SET CCAR;
	BASEL_PRODUCT_NAME2=SUBSTR(BASEL_PRODUCT_NAME,1,LENGTH(BASEL_PRODUCT_NAME)-9);
	PD_SEG = SUBSTR(BASEL_PRODUCT_NAME,LENGTH(BASEL_PRODUCT_NAME)-7,2);
	EAD_SEG = SUBSTR(BASEL_PRODUCT_NAME,LENGTH(BASEL_PRODUCT_NAME)-4,2);
	LGD_SEG = SUBSTR(BASEL_PRODUCT_NAME,LENGTH(BASEL_PRODUCT_NAME)-1,2);
RUN;

PROC SQL;
	CREATE TABLE CCAR_FINAL AS
	SELECT *,case when BASEL_PRODUCT_NAME2 like '%BNS%' then 'BNS'
        when BASEL_PRODUCT_NAME2 like '%TNG%' then 'TNG'
        when BASEL_PRODUCT_NAME2 like '%DTL%' then 'DTL'
        when BASEL_PRODUCT_NAME2 like '%ITL%' then 'ITL'
        when BASEL_PRODUCT_NAME2 like '%CC%' then 'CC'                   
        when BASEL_PRODUCT_NAME2 like '%CL%' then 'LOC'
        when BASEL_PRODUCT_NAME2 like '%HELOC%' then 'HELOC'
        when BASEL_PRODUCT_NAME2 like '%SLR%' then 'SLR'                
        when BASEL_PRODUCT_NAME2 like '%SLT%' then 'SLT'
end as PORTFOLIO,
(input(LOSS_GIVEN_DEFAULT,percent15.6)) as NUMERIC_LGD,
(input(EXPECTED_LOSS,percent15.6)) as EXPECTED_LOSS_NUM,
(input(EAD_FACTOR,percent15.6)) as EAD_FACTOR_NUM,
(input(DOWNTURN_LGD,percent15.6)) as DOWNTURN_LGD_NUM,
(input(UNINSURED_LGD,percent15.6)) as UNINSURED_LGD_NUM,
(input(UNINSURED_DLGD,percent15.6)) as UNINSURED_DLGD_NUM,
		CASE 
			WHEN (input(DOWNTURN_LGD,percent15.6)) = (input(LOSS_GIVEN_DEFAULT,percent15.6)) THEN 'Downturn_LGD=Loss_Given_Default'
			WHEN (input(DOWNTURN_LGD,percent15.6)) >= (input(LOSS_GIVEN_DEFAULT,percent15.6)) THEN 'Downturn_LGD>=Loss_Given_Default'
			WHEN (input(DOWNTURN_LGD,percent15.6)) < (input(LOSS_GIVEN_DEFAULT,percent15.6)) THEN 'Downturn_LGD<Loss_Given_Default'
			WHEN (input(DOWNTURN_LGD,percent15.6)) IS NULL THEN 'Downturn_LGD IS NULL'
		END AS DLGD_LGD_BUCKETS,
		CASE 
			WHEN (input(UNINSURED_DLGD,percent15.6)) = (input(UNINSURED_LGD,percent15.6)) THEN 'Uninsured_DLGD=Uninsured_LGD'
			WHEN (input(UNINSURED_DLGD,percent15.6)) >= (input(UNINSURED_LGD,percent15.6)) THEN 'Uninsured_DLGD>=Uninsured_LGD'
			WHEN (input(UNINSURED_DLGD,percent15.6)) < (input(UNINSURED_LGD,percent15.6)) THEN 'Uninsured_DLGD<Uninsured_LGD'
			WHEN (input(UNINSURED_DLGD,percent15.6)) IS NULL THEN 'Uninsured_DLGD IS NULL'
		END AS UNINSURED_DLGD_LGD_BUCKETS,
		CASE 
			WHEN MTH_TM_ID = &MTH_TM_ID THEN "&CURR"
			WHEN MTH_TM_ID = &PREV_MTH_TM_ID THEN "&PREV"
		END AS MONTH_CHAR
	FROM TEMP;
QUIT;

PROC SQL;
	CREATE TABLE ECL_TRANSPOSE AS
	SELECT DISTINCT 'ECL_DRAWN1' AS ECL_COL, SUM(ECL_DRAWN1) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_DRAWN2' AS ECL_COL, SUM(ECL_DRAWN2) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_DRAWN3' AS ECL_COL, SUM(ECL_Drawn3) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Undrawn1' AS ECL_COL, SUM(ECL_Undrawn1) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Undrawn2' AS ECL_COL, SUM(ECL_Undrawn2) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Undrawn3' AS ECL_COL, SUM(ECL_Undrawn3) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Drawn_PostSec1' AS ECL_COL, SUM(ECL_Drawn_PostSec1) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Drawn_PostSec2' AS ECL_COL, SUM(ECL_Drawn_PostSec2) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Drawn_PostSec3' AS ECL_COL, SUM(ECL_Drawn_PostSec3) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Drawn1' AS ECL_COL, SUM(ECL_Post_Adj_Drawn1) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Drawn2' AS ECL_COL, SUM(ECL_Post_Adj_Drawn2) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Drawn3' AS ECL_COL, SUM(ECL_Post_Adj_Drawn3) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Undrawn1' AS ECL_COL, SUM(ECL_Post_Adj_Undrawn1) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Undrawn2' AS ECL_COL, SUM(ECL_Post_Adj_Undrawn2) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Undrawn3' AS ECL_COL, SUM(ECL_Post_Adj_Undrawn3) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Drawn_PostSec1' AS ECL_COL, SUM(ECL_Post_Adj_Drawn_PostSec1) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Drawn_PostSec2' AS ECL_COL, SUM(ECL_Post_Adj_Drawn_PostSec2) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR
	UNION
	SELECT DISTINCT 'ECL_Post_Adj_Drawn_PostSec3' AS ECL_COL, SUM(ECL_Post_Adj_Drawn_PostSec3) AS TOTAL, MONTH_CHAR FROM CCAR_FINAL GROUP BY MONTH_CHAR;
QUIT;


/*IMPORT AND PROCESS PD_CURVE DATA*/

PROC SQL;
	CREATE TABLE PD_CURVE AS
	SELECT A.MTH_END_DT,
		   A.TRANSACTOR_FLAG,
		   A.PD_BAND,
		   A.PD_VAL,
		   A.PD_MIN_VAL,
		   A.PD_MAX_VAL,
	  SUBSTR(A.CCAR_BASEL_PRD_TP_NM,1,LENGTH(A.CCAR_BASEL_PRD_TP_NM)-9) AS BASEL_PRODUCT_NAME2,
	  SUBSTR(A.CCAR_BASEL_PRD_TP_NM,LENGTH(A.CCAR_BASEL_PRD_TP_NM)-7,2) AS PD_SEG,
	  CASE 
			WHEN B.TM_ID = &MTH_TM_ID THEN "&CURR"
			WHEN B.TM_ID = &PREV_MTH_TM_ID THEN "&PREV"
		END AS MONTH_CHAR
FROM NZRRAP.BASEL_CCAR_PD_CURVE A
      INNER JOIN (
            SELECT TM_ID,
                  TM_LVL_END_DT
            FROM NZRRAP.TM_DIM
            where TM_LVL = 'Month' 
			and tm_id in (&MTH_TM_ID. , &PREV_MTH_TM_ID.)
      ) B ON A.MTH_END_DT = B.TM_LVL_END_DT
WHERE A.PD_VAL NE 0;
QUIT;

PROC SORT DATA=PD_CURVE NODUPKEY;
	BY MTH_END_DT BASEL_PRODUCT_NAME2 TRANSACTOR_FLAG PD_SEG PD_BAND;
RUN;

/****************************REPORTS GENERATION START BELOW***************************************/

/*DEFINE OUTPUT EXCEL FILE LOCATION AND NAME*/
ods excel file="&rrap_dir./flat_files/rrap_iias/Audit_report_&CURR..xlsx";

/*EXPOSURE*/
ods excel options(Sheet_name='EXPOSURE' frozen_headers="ON" SHEET_INTERVAL="TABLE");


PROC REPORT DATA=CCAR_FINAL out=EXPOSURE;
	COLUMNS (BASEL_PRODUCT_NAME2 MONTH_CHAR, DRAWN_AMOUNT DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/"EXPOSURE COMPARISON" ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE DRAWN_AMOUNT/'DRAWN AMOUNT' FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'DIFF DRAWN' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=GTEQ5LTEQ.] STYLE(HEADER)=[BACKGROUND=RED];

	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C2_)/_c3_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

/*RWA*/
ods excel options(Sheet_name='RWA');

PROC SQL;
	CREATE TABLE TEMP10310_A AS
	SELECT DISTINCT SRC_SYS_CD,MTH_TM_ID,SUM(EAD_TOT_AF_CRM_AMT) AS CURR
	FROM DB2RRAP.BASEL_RISK_WGHTD_AVG_FACT A
	WHERE MTH_TM_ID = &MTH_TM_ID
	GROUP BY SRC_SYS_CD;
QUIT;


PROC SQL;
	CREATE TABLE TEMP10310_B AS
	SELECT DISTINCT SRC_SYS_CD,MTH_TM_ID,SUM(EAD_TOT_AF_CRM_AMT) AS PREV
	FROM DB2RRAP.BASEL_RISK_WGHTD_AVG_FACT A
	WHERE MTH_TM_ID = &PREV_MTH_TM_ID
	GROUP BY SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE TEMP10310 AS
	SELECT 'Weighted Avg fact - EAD_TOT_AF_CRM_AMT' as AUDIT_NAME,A.*,B.PREV,(CURR-PREV)/CURR AS DIFFERENCE FORMAT PERCENT10.2
	FROM TEMP10310_A AS A
	FULL JOIN
	TEMP10310_B AS B
	ON A.SRC_SYS_CD = B.SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE TEMP10320_A AS
	SELECT DISTINCT SRC_SYS_CD,MTH_TM_ID,SUM(EL_TOT_AF_CRM_AMT) AS CURR
	FROM DB2RRAP.BASEL_RISK_WGHTD_AVG_FACT A
	WHERE MTH_TM_ID = &MTH_TM_ID
	GROUP BY SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE TEMP10320_B AS
	SELECT DISTINCT SRC_SYS_CD,MTH_TM_ID,SUM(EL_TOT_AF_CRM_AMT) AS PREV
	FROM DB2RRAP.BASEL_RISK_WGHTD_AVG_FACT A
	WHERE MTH_TM_ID = &PREV_MTH_TM_ID
	GROUP BY SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE TEMP10320 AS
	SELECT 'Weighted Avg fact - EL_TOT_AF_CRM_AMT' as AUDIT_NAME,A.*,B.PREV,(CURR-PREV)/CURR AS DIFFERENCE FORMAT PERCENT10.2
	FROM TEMP10320_A AS A
	FULL JOIN
	TEMP10320_B AS B
	ON A.SRC_SYS_CD = B.SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE TEMP10330_A AS
	SELECT DISTINCT SRC_SYS_CD,MTH_TM_ID,SUM(RWA_TOT_AF_CRM_FLOORED_AMT) AS CURR
	FROM DB2RRAP.BASEL_RISK_WGHTD_AVG_FACT A
	WHERE MTH_TM_ID = &MTH_TM_ID
	GROUP BY SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE TEMP10330_B AS
	SELECT DISTINCT SRC_SYS_CD,MTH_TM_ID,SUM(RWA_TOT_AF_CRM_FLOORED_AMT) AS PREV
	FROM DB2RRAP.BASEL_RISK_WGHTD_AVG_FACT A
	WHERE MTH_TM_ID = &PREV_MTH_TM_ID
	GROUP BY SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE TEMP10330 AS
	SELECT 'Weighted Avg fact - RWA_TOT_AF_CRM_FLOORED_AMT' as AUDIT_NAME,A.*,B.PREV,(CURR-PREV)/CURR AS DIFFERENCE FORMAT PERCENT10.2
	FROM TEMP10330_A AS A
	FULL JOIN
	TEMP10330_B AS B
	ON A.SRC_SYS_CD = B.SRC_SYS_CD;
QUIT;

PROC SQL;
	CREATE TABLE RWA AS
	SELECT * FROM TEMP10310
	UNION
	SELECT * FROM TEMP10320
	UNION
	SELECT * FROM TEMP10330;
QUIT;

PROC REPORT DATA=RWA;
	COLUMNS (AUDIT_NAME SRC_SYS_CD CURR PREV  DIFFERENCE);
    DEFINE CURR/"&CURR" FORMAT=COMMA32.2 STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
    DEFINE PREV/"&PREV" FORMAT=COMMA32.3 STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE SRC_SYS_CD/STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE AUDIT_NAME/'AUDIT NAME' STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE DIFFERENCE/'DIFFERENCE' STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
RUN;

/*PD_CURVE*/
ODS EXCEL options(Sheet_name='PD_CURVE' frozen_headers="ON");
PROC REPORT DATA=PD_CURVE MISSING OUT=PD_CURVE_OUTPUT;
	COLUMNS BASEL_PRODUCT_NAME2 pd_seg PD_BAND MONTH_CHAR, (TRANSACTOR_FLAG PD_VAL PD_MIN_VAL PD_MAX_VAL) DIFF_TRANSACTOR_FLAG DIFF_PD_VAL DIFF_PD_MIN DIFF_PD_MAX;
	DEFINE BASEL_PRODUCT_NAME2/'PRODUCT' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE PD_SEG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE PD_BAND/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE TRANSACTOR_FLAG/STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE PD_MIN_VAL/FORMAT=COMMA30.7 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE PD_VAL/FORMAT=PERCENT7.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'PD_CURVE COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE PD_MAX_VAL/ANALYSIS SUM FORMAT=COMMA30.7 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF_TRANSACTOR_FLAG/COMPUTED STYLE(COLUMN)=[BACKGROUND=$BKG_PD_CURVE_TF.] STYLE(HEADER)=[BACKGROUND=RED];
		COMPUTE DIFF_TRANSACTOR_FLAG/character length=5;
			IF _C4_=_C8_ THEN DO;
			DIFF_TRANSACTOR_FLAG = 'TRUE';
			END;
			ELSE DO;
			DIFF_TRANSACTOR_FLAG = 'FALSE';
			END;
		ENDCOMP;
	DEFINE DIFF_PD_VAL/COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=BKG_PD_CURVE.] STYLE(HEADER)=[BACKGROUND=RED];
		COMPUTE DIFF_PD_VAL;
			DIFF_PD_VAL = SUM(_C5_,-_C9_);
		ENDCOMP;
	DEFINE DIFF_PD_MIN/COMPUTED FORMAT=COMMA30.7 STYLE(COLUMN)=[BACKGROUND=BKG_PD_CURVE.] STYLE(HEADER)=[BACKGROUND=RED];
		COMPUTE DIFF_PD_MIN;
			DIFF_PD_MIN = SUM(_C6_,-_C10_);
		ENDCOMP;
	DEFINE DIFF_PD_MAX/COMPUTED FORMAT=COMMA30.7 STYLE(COLUMN)=[BACKGROUND=BKG_PD_CURVE.] STYLE(HEADER)=[BACKGROUND=RED];
		COMPUTE DIFF_PD_MAX;
			DIFF_PD_MAX = SUM(_C7_,-_C11_);
		ENDCOMP;
RUN;

/*UNDRAWN*/
ODS EXCEL options(Sheet_name='Undrawn');

PROC REPORT DATA=CCAR_FINAL out=UNDRAWN;
	COLUMNS (BASEL_PRODUCT_NAME2 MONTH_CHAR, (UNDRAWN_AMOUNT OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'UNDRAWN AMOUNT COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM  FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE UNDRAWN_AMOUNT/FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'DIFF UNDRAWN' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)={BACKGROUND=GTEQ5LTEQ.} STYLE(HEADER)=[BACKGROUND=RED];

	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C4_)/_c2_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

/*ACCTS*/

ODS EXCEL options(Sheet_name='ACCTS');

PROC REPORT DATA=CCAR_FINAL OUT=ACCTS;
	COLUMNS (BASEL_PRODUCT_NAME2 DEFAULTED_EXPOSURE_FLAG MONTH_CHAR, (OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'ACCTS COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE DEFAULTED_EXPOSURE_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=GTEQ5LTEQ.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C4_)/_C3_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;


/*LGD_EL*/
ODS EXCEL options(Sheet_name='LGD_EL' frozen_headers="OFF" frozen_rowheaders="3" sheet_interval="none");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=LGD_EL_REPORT1;
	COLUMNS PORTFOLIO DEFAULTED_EXPOSURE_FLAG LGD_SEG MONTH_CHAR, ((MIN MEAN MAX),NUMERIC_LGD OBLIGORS) DIFF_MIN DIFF_MEAN DIFF_MAX;
	DEFINE PORTFOLIO/'PROD2' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DEFAULTED_EXPOSURE_FLAG/'DEFAULTED_EXPOSURE_FLAG' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'LGD_EL COMPARISON : LOSS_GIVEN_DEFAULT' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE LGD_SEG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE NUMERIC_LGD/'LOSS_GIVEN_DEFAULT' FORMAT=COMMA30.7 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF_MIN/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=LIGHT RED];
		COMPUTE DIFF_MIN;
			DIFF_MIN = _C8_-_C4_;
		ENDCOMP;
	DEFINE DIFF_MEAN/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=LIGHT RED];
		COMPUTE DIFF_MEAN;
			DIFF_MEAN = _C9_-_C5_;
		ENDCOMP;
	DEFINE DIFF_MAX/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=LIGHT RED];
		COMPUTE DIFF_MAX;
			DIFF_MAX = _C10_-_C6_;
		ENDCOMP;
RUN;

PROC REPORT DATA=CCAR_FINAL MISSING OUT=LGD_EL_REPORT2;
	COLUMNS PORTFOLIO DEFAULTED_EXPOSURE_FLAG LGD_SEG MONTH_CHAR, ((MIN MEAN MAX),EXPECTED_LOSS_NUM OBLIGORS) DIFF_MIN DIFF_MEAN DIFF_MAX;
	DEFINE PORTFOLIO/'PROD2' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DEFAULTED_EXPOSURE_FLAG/'DEFAULTED_EXPOSURE_FLAG' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'LGD_EL COMPARISON : EXPECTED LOSS' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE LGD_SEG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE EXPECTED_LOSS_NUM/'EXPECTED_LOSS' FORMAT=COMMA30.7 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF_MIN/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=LIGHT RED];
		COMPUTE DIFF_MIN;
			DIFF_MIN = _C8_-_C4_;
		ENDCOMP;
	DEFINE DIFF_MEAN/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=LIGHT RED];
		COMPUTE DIFF_MEAN;
			DIFF_MEAN = _C9_-_C5_;
		ENDCOMP;
	DEFINE DIFF_MAX/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=LIGHT RED];
		COMPUTE DIFF_MAX;
			DIFF_MAX = _C10_-_C6_;
		ENDCOMP;
RUN;


/*EAD*/

ODS EXCEL options(Sheet_name='EAD' frozen_headers="ON" frozen_rowheaders="3" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=EAD;
	COLUMNS PORTFOLIO EAD_SEG MONTH_CHAR, ((MIN MEAN MAX),EAD_FACTOR_NUM OBLIGORS) DIFF_MIN DIFF_MEAN DIFF_MAX;
	DEFINE PORTFOLIO/'PROD2' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'EAD COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE EAD_SEG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE EAD_FACTOR_NUM/'EAD_FACTOR' FORMAT=COMMA30.6 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF_MIN/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=RED] STYLE(COLUMN)={BACKGROUND=BKG_PD_CURVE.};
		COMPUTE DIFF_MIN;
			DIFF_MIN = _C7_-_C3_;
		ENDCOMP;
	DEFINE DIFF_MEAN/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=RED] STYLE(COLUMN)={BACKGROUND=BKG_PD_CURVE.};
		COMPUTE DIFF_MEAN;
			DIFF_MEAN = _C8_-_C4_;
		ENDCOMP;
	DEFINE DIFF_MAX/COMPUTED FORMAT=COMMA30.6 STYLE(HEADER)=[BACKGROUND=RED] STYLE(COLUMN)={BACKGROUND=BKG_PD_CURVE.};
		COMPUTE DIFF_MAX;
			DIFF_MAX = _C9_-_C5_;
		ENDCOMP;
RUN;


/*F_INSURANCE*/

ODS EXCEL options(Sheet_name='F_INSURANCE' frozen_headers="ON");

PROC REPORT DATA=CCAR_FINAL out=F_INSURANCE;
	COLUMNS (BASEL_PRODUCT_NAME2 INSURANCE_FLAG MONTH_CHAR, (OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_INSURANCE COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE INSURANCE_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)={BACKGROUND=GTEQ5LTEQ.}  STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C4_, -_C3_)/_c4_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

/*DLGD*/

ODS EXCEL options(Sheet_name='DLGD' frozen_headers="ON");

PROC REPORT DATA=CCAR_FINAL out=DLGD;
	COLUMNS (BASEL_PRODUCT_NAME2 DLGD_LGD_BUCKETS MONTH_CHAR, (OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'DLGD COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE DLGD_LGD_BUCKETS/'' ORDER GROUP STYLE(COLUMN)={BACKGROUND=$DLGD.} STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[BACKGROUND=DARK GREY COLOR=YELLOW];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C4_)/_c3_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

/*UNINSURED_LGD*/
ODS EXCEL options(Sheet_name='UNINSURED_LGD' frozen_headers="OFF" SHEET_INTERVAL="NONE");

PROC REPORT DATA=CCAR_FINAL MISSING out=UNINSURED_LGD_REPORT1;
	WHERE UNINSURED_LGD IS NULL;
	COLUMNS (BASEL_PRODUCT_NAME2 UNINSURED_LGD MONTH_CHAR, (OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'UNINSURED_LGD COMPARISON : UNINSURED_LGD IS NULL' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE UNINSURED_LGD/'UNINSURED_LGD' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[BACKGROUND=DARK GREY COLOR=YELLOW];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C4_)/_c3_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

PROC REPORT DATA=CCAR_FINAL OUT=UNINSURED_LGD_REPORT2;
	WHERE UNINSURED_LGD IS NOT NULL;
	COLUMNS BASEL_PRODUCT_NAME2 DEFAULTED_EXPOSURE_FLAG LGD_SEG MONTH_CHAR, (((MEAN),NUMERIC_LGD (MEAN),UNINSURED_LGD_NUM) ((SUM),OBLIGORS)) DIFF_LGD DIFF_UNINSURED_LGD;
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DEFAULTED_EXPOSURE_FLAG/'DEFAULTED_EXPOSURE_FLAG' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE LGD_SEG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'UNINSURED_LGD COMPARISON : UNINSURED_LGD IS NOT NULL' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE NUMERIC_LGD/'LOSS_GIVEN DEFAULT' FORMAT=COMMA30.6 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE UNINSURED_LGD_NUM/'UNINSURED_LGD' FORMAT=COMMA30.6 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF_LGD/'DIFF_LGD' FORMAT=COMMA30.6 COMPUTED STYLE(HEADER)=[BACKGROUND=RED];
		COMPUTE DIFF_LGD;
			DIFF_LGD = SUM(_C4_, -_C7_)/_c4_;
		ENDCOMP;
	DEFINE DIFF_UNINSURED_LGD/'DIFF_UNINSURED_LGD' FORMAT=COMMA30.6 COMPUTED STYLE(HEADER)=[BACKGROUND=RED];
		COMPUTE DIFF_UNINSURED_LGD;
			DIFF_UNINSURED_LGD = SUM(_C5_, -_C8_)/_c5_;
		ENDCOMP;
RUN;

/*UNINSURED_DLGD*/

ODS EXCEL options(Sheet_name='UNINSURED_DLGD' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL out=UNINSURED_DLGD;
	COLUMNS (BASEL_PRODUCT_NAME2 UNINSURED_DLGD_LGD_BUCKETS MONTH_CHAR, (OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'UNINSURED_DLGD COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE UNINSURED_DLGD_LGD_BUCKETS/'' ORDER GROUP STYLE(COLUMN)={BACKGROUND=$UNINSURED_DLGD.} STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[BACKGROUND=DARK GREY COLOR=YELLOW];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C4_)/_c3_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

/*LTV*/
ODS EXCEL options(Sheet_name='LTV' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL MISSING out=LTV;
	COLUMNS (BASEL_PRODUCT_NAME2 LTV_BUCKET MONTH_CHAR, (OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'LTV COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE LTV_BUCKET/'LTV_BUCKET' ORDER GROUP STYLE(COLUMN)={BACKGROUND=$UNINSURED_DLGD.} STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[BACKGROUND=DARK GREY COLOR=YELLOW];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=GTEQ5LTEQ.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C4_)/_c3_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

/*SEC*/
ODS EXCEL options(Sheet_name='SEC' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=SEC;
	WHERE MTH_TM_ID=&MTH_TM_ID;
	COLUMNS BASEL_PRODUCT_NAME2 SECURITIZATION_NAME MONTH_CHAR, (EXPOSURES_PRIOR_SECURITIZATION EXPOSURES_NO_SECURITIZATION EXPOSURES_WITH_SECURITIZATION SECURITIZATION_AMOUNT EXPOSURES_REDUCED OBLIGORS);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE SECURITIZATION_NAME/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'SECURITIZATION COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE EXPOSURES_PRIOR_SECURITIZATION/SUM FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE EXPOSURES_NO_SECURITIZATION/SUM FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE EXPOSURES_WITH_SECURITIZATION/SUM FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE SECURITIZATION_AMOUNT/SUM FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE EXPOSURES_REDUCED/SUM FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
RUN;

/*F_RENTAL*/
ODS EXCEL options(Sheet_name='F_RENTAL' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=F_RENTAL;
	COLUMNS RENTAL_INCOME_FLAG MONTH_CHAR, (OBLIGORS OBLIGORS=OBLIGORS_PCT) DIFF;
	DEFINE RENTAL_INCOME_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_RENTAL COMPARISON' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS_PCT/'OBLIGORS %' ANALYSIS PCTSUM FORMAT=PERCENT8.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C4_)/_c2_;
	ENDCOMP;

	RBREAK AFTER /SUMMARIZE UL OL;
RUN;

/*F_CURRENCY*/
ODS EXCEL options(Sheet_name='F_CURRENCY' frozen_headers="ON" SHEET_INTERVAL="TABLE");


PROC REPORT DATA=CCAR_FINAL MISSING OUT=F_RENTAL;
	COLUMNS CURRENCY_MISMATCH_FLAG MONTH_CHAR, (OBLIGORS OBLIGORS=OBLIGORS_PCT) DIFF;
	DEFINE CURRENCY_MISMATCH_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_CURRENCY COMPARISON' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS_PCT/'OBLIGORS %' ANALYSIS PCTSUM FORMAT=PERCENT8.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C4_)/_c2_;
	ENDCOMP;

	RBREAK AFTER /SUMMARIZE UL OL;
RUN;

/*ECL*/
ODS EXCEL options(Sheet_name='ECL' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=ECL_TRANSPOSE MISSING OUT=ECL;
	COLUMNS ECL_COL MONTH_CHAR, (TOTAL) DIFF;
	DEFINE ECL_COL/'' GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'ECL COMPARISON' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE TOTAL/FORMAT=COMMA32.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'ECL DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C3_)/_c2_;
	ENDCOMP;
RUN;


/*F_ABOVE_LIMIT*/
ODS EXCEL options(Sheet_name='F_ABOVE_LIMIT' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=F_RENTAL;
	COLUMNS TOTAL_EXPOSURE_ABOVE_LIMIT MONTH_CHAR, (OBLIGORS OBLIGORS=OBLIGORS_PCT) DIFF;
	DEFINE TOTAL_EXPOSURE_ABOVE_LIMIT/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_ABOVE_LIMIT COMPARISON' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS_PCT/'OBLIGORS %' ANALYSIS PCTSUM FORMAT=PERCENT8.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C4_)/_c2_;
	ENDCOMP;

	RBREAK AFTER /SUMMARIZE UL OL;
RUN;

/*ORIG_AMT*/
ODS EXCEL options(Sheet_name='ORIG_AMT' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=ORIG_AMT;
	COLUMNS BASEL_PRODUCT_NAME2 MONTH_CHAR, (ORIG_LOAN_AMT_AS_OF_INSUR_DATE) DIFF;
	DEFINE BASEL_PRODUCT_NAME2/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'ORIG_AMT COMPARISON' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE ORIG_LOAN_AMT_AS_OF_INSUR_DATE/'ORIG_LOAN_AMT' SUM FORMAT=COMMA32.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C3_)/_c2_;
	ENDCOMP;
RUN;


/*F_TRANS*/
ODS EXCEL options(Sheet_name='F_TRANS' frozen_headers="OFF" SHEET_INTERVAL="NONE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=F_TRANS_REPORT1;
	COLUMNS TRANSACTOR_FLAG MONTH_CHAR, (OBLIGORS OBLIGORS=OBLIGORS_PCT) DIFF;
	DEFINE TRANSACTOR_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_TRANS COMPARISON - OVERALL' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS_PCT/'OBLIGORS %' ANALYSIS PCTSUM FORMAT=PERCENT8.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C4_)/_c2_;
	ENDCOMP;

	RBREAK AFTER /SUMMARIZE UL OL;
RUN; 

PROC REPORT DATA=CCAR_FINAL OUT=F_TRANS_REPORT2;
	COLUMNS BASEL_PRODUCT_NAME2 TRANSACTOR_FLAG MONTH_CHAR, (OBLIGORS OBLIGORS=OBLIGORS_PCT) DIFF;
	DEFINE BASEL_PRODUCT_NAME2/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE TRANSACTOR_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_TRANS COMPARISON - BY BASEL_PRODUCT' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS_PCT/'OBLIGORS %' ANALYSIS PCTSUM FORMAT=PERCENT8.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C5_)/_c3_;
	ENDCOMP;

	RBREAK AFTER /SUMMARIZE UL OL;
RUN; 

/*EGL*/
ODS EXCEL options(Sheet_name='EGL' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=EGL;
	COLUMNS BASEL_PRODUCT_NAME2 EGL_DEPARTMENT_ID PRODUCT_ID MONTH_CHAR, (OBLIGORS) DIFF;
	DEFINE BASEL_PRODUCT_NAME2/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE EGL_DEPARTMENT_ID/ORDER GROUP FORMAT=$32. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE PRODUCT_ID/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'EGL COMPARISON' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C4_, -_C5_)/_c4_;
	ENDCOMP;
RUN;

/*CLP_FLAG*/
ODS EXCEL options(Sheet_name='F_CLP' frozen_headers="OFF" SHEET_INTERVAL="NONE");

PROC REPORT DATA=CCAR_FINAL MISSING OUT=F_CLP_REPORT1;
	COLUMNS CLP_FLAG MONTH_CHAR, (OBLIGORS OBLIGORS=OBLIGORS_PCT) DIFF;
	DEFINE CLP_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_CLP COMPARISON - OVERALL' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS_PCT/'OBLIGORS %' ANALYSIS PCTSUM FORMAT=PERCENT8.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C4_)/_c2_;
	ENDCOMP;

	RBREAK AFTER /SUMMARIZE UL OL;
RUN; 

PROC REPORT DATA=CCAR_FINAL MISSING OUT=F_CLP_REPORT2;
	COLUMNS BASEL_PRODUCT_NAME2 CLP_FLAG MONTH_CHAR, (OBLIGORS OBLIGORS=OBLIGORS_PCT) DIFF;
	DEFINE BASEL_PRODUCT_NAME2/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE CLP_FLAG/ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'F_CLP COMPARISON - BY BASEL_PRODUCT' GROUP ORDER ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE OBLIGORS_PCT/'OBLIGORS %' ANALYSIS PCTSUM FORMAT=PERCENT8.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'OBLIGORS DIFF' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)=[BACKGROUND=F_INSURANCE.] STYLE(HEADER)=[BACKGROUND=RED];
	COMPUTE DIFF;
		DIFF = SUM(_C3_, -_C5_)/_c3_;
	ENDCOMP;

	RBREAK AFTER /SUMMARIZE UL OL;
RUN; 


/*ACCRUED_INTEREST*/

ODS EXCEL options(Sheet_name='ACCRUED_INTEREST' frozen_headers="ON" SHEET_INTERVAL="TABLE");

PROC REPORT DATA=CCAR_FINAL out=ACCRUED_INTEREST;
	COLUMNS (BASEL_PRODUCT_NAME2 MONTH_CHAR, (ACCRUED_INTEREST OBLIGORS) DIFF);
	DEFINE BASEL_PRODUCT_NAME2/'BASEL_PRODUCT_NAME' ORDER GROUP STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE MONTH_CHAR/'ACCRUED INTEREST COMPARISON' ACROSS STYLE(HEADER)=[COLOR=WHITE BACKGROUND=BLACK];
	DEFINE OBLIGORS/SUM  FORMAT=COMMA30. STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE ACCRUED_INTEREST/FORMAT=COMMA30.2 STYLE(HEADER)=[COLOR=YELLOW BACKGROUND=DARK GREY];
	DEFINE DIFF/'DIFF ACCRUED INTEREST' COMPUTED FORMAT=PERCENT7.2 STYLE(COLUMN)={BACKGROUND=GTEQ5LTEQ.} STYLE(HEADER)=[BACKGROUND=RED];

	COMPUTE DIFF;
		DIFF = SUM(_C2_, -_C4_)/_c2_;
	ENDCOMP;

	rbreak after /dol skip summarize;
RUN;

ods excel close;

Data _null_;
infile "&rrap_dir./params/rrap_iias/ccar_audit_report_email_list.txt";
input;
if _N_ =2 then do;
CALL SYMPUT("email_list",_infile_);
end;
run;

%put &email_list;


filename mailbox email (&email_list)
     attach=("&rrap_dir./flat_files/rrap_iias/Audit_report_&CURR..xlsx" content_type="application/vnd.ms-excel")
subject = "[RRAP] CCAR Audit Report - &MonthYear." content_type="text/html";
ods listing close;
ods html body=mailbox;

data _null_;
     file print;
     put "This is an automated email. Please do not reply";
run;

ods html close;