
/*SAS JOB FOR TESTING CONNECTIVITY AND LOAD TO IIAS DATABASE*/

LIBNAME NZFRG DB2 DATABASE=BLUDBPRD SCHEMA=FRG_USER_DATA AUTHDOMAIN='IIAS_AUTH';
LIBNAME EDRFRG DB2 DATABASE=BLUDBPRD SCHEMA=EDRTLRFRGP1D AUTHDOMAIN='IIAS_AUTH';
LIBNAME NZRRAP DB2 DATABASE=BLUDBPRD SCHEMA=EDRTLRP1D AUTHDOMAIN='IIAS_AUTH';


/*Tests to connect, insert data in IIAS Tables*/





PROC SQL;
	SELECT COUNT(*) INTO :ORIGINAL_COUNT FROM NZRRAP.TM_DIM;
QUIT;

PROC APPEND BASE=NZRRAP.SAS_TEST (BULKLOAD=YES BL_METHOD=CLILOAD)
			DATA=NZRRAP.TM_DIM;
RUN;

PROC SQL;
	SELECT COUNT(*) INTO :TOT_COUNT FROM NZRRAP.SAS_TEST;
QUIT;

%PUT &=TOT_COUNT;

%IF &TOT_COUNT = &ORIGINAL_COUNT %THEN %DO;
	%PUT "TABLE LOADED (WITH BULKLOAD) AS EXPECTED";
%END;
%ELSE %DO;
	%PUT "RESULTS NOT AS EXPECTED - KINDLY VALIDATE";
%END;

PROC APPEND BASE=NZRRAP.SAS_TEST
			DATA=NZRRAP.TM_DIM;
RUN;

PROC SQL;
	SELECT COUNT (*) INTO :TOT_COUNT2 FROM NZRRAP.SAS_TEST;
QUIT;

%PUT &=TOT_COUNT2;

%IF &TOT_COUNT2 = %EVAL(&TOT_COUNT*2) %THEN %DO;
	%PUT "TABLE LOADED (WITHOUT BULKLOAD) AS EXPECTED";
%END;
%ELSE %DO;
	%PUT "RESULTS NOT AS EXPECTED - KINDLY VALIDATE";
%END;
