***************************************************************************************************************************;

%let etls_jobname = J_RRAP_GCP_Append_BASEL_ACCT_ID_MOR.sas;

***************************************************************************************************************************;
***************************************************************************************************************************;
***************************************************************************************************************************;
*
*  Target Database: IIAS FRG_USER_DATA
*  Target Table:  	AIRB_MORT_MTH_SNAPSHOT_LGD 
*					BNSMORT_ACCT_LVL_DATA_LGD
*					BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ_LGD 
*					BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ_LGD
*  
*  Purpose: 		Assign basel_acct_id to 4 MOR tables.
*
*  Frequency: 		Month End runs
*
*	Change Log:
*	2024-02-29: 	Ganesh Patro - Initial Development
*
*
*
***************************************************************************************************************************;

%RRAP_MOR_TNG_AUTOEXEC();

%RRAP_MOR_TNG_AUTOEXEC();

 %get_model_period_dates(product=mor);

/*   %let start_period_dt=31OCT2016;*/

      data _null_;
           set nzrrap.tm_dim;
           where tm_lvl_end_dt = "&start_period_dt"d and tm_lvl='Month';
           call symputx('mth_tm_id',put(tm_id,5.));
           call symputx('mth_end_dt',put(tm_lvl_end_dt,date9.));
           call symputx('mth_end_dt_nz',put(tm_lvl_end_dt,yymmdd10.));
           call symputx('yrmth',put(tm_lvl_end_dt,yymmn6.));
           call symputx('yrmth_prev',put(intnx('Month',tm_lvl_end_dt,-1,'e'),yymmn6.));
     run;

*################ TABLE1:		AIRB_MORT_MTH_SNAPSHOT_LGD		###########################*;
%macro automate_36;
%do MTH_TM_ID=6158 %to 19996 %by 40; 
%put &MTH_TM_ID start load;

proc sql;
connect using nz_frg as iiascon;
execute(delete from &FRG_DB..AIRB_MORT_MTH_SNAPSHOT_LGD where tm_id = &mth_tm_id.;) by iiascon;
execute(commit;) by iiascon;
quit;


proc sql;
connect using nz_frg as iiascon;
execute(INSERT into &FRG_DB..AIRB_MORT_MTH_SNAPSHOT_LGD 
(TM_ID,MTH_END_DT,BASEL_ACCT_ID,MORT_NUM,AMORT,OP_FIELD,LEND_VALUE,
PROPERTY_ADDR_1,PROPERTY_ADDR_2,PROPERTY_ADDR_3,PROP_PROV,PREPAY_YTD,
AUTH_AMT,CAB,DLQNT_MTH,EFF_TMSTMP,FLOAT_IND,INEREST_ACCR_AMT,
INTR_ADJ_DT,MADE_DT,MAT_DT,PD_OFF_F,PRIM_CUST_ID,STEP_F,
TOT_ADVNC_AMT,TRNST,UNPAID_MTH_PAY_DT,UNPAID_WKLY_PAY_DT,CLASS,
FUND_CD,SECURITY_TYPE,CRNT_BAL,FRCLSR_F,PD_OFF_DT,TOT_SUSP_BAL,
TNIF_RGN_CD,COMM_TP,INSUR_GRP,LRA_STAT,DLQNT_DAY,GL_ACCT_NUM,
GL_TRNST_NUM,PRD_GRP_CD,UNIT_CNT,CRNCY_CD,INSRT_PROCESS_TMSTMP
,IBMREPL_SITE,IBMREPL_KEY) 
(SELECT 
A.TM_ID,A.MTH_END_DT,B.BASEL_ACCT_ID,A.MORT_NUM,A.AMORT,A.OP_FIELD,A.LEND_VALUE,
A.PROPERTY_ADDR_1,A.PROPERTY_ADDR_2,A.PROPERTY_ADDR_3,A.PROP_PROV,A.PREPAY_YTD,
A.AUTH_AMT,A.CAB,A.DLQNT_MTH,A.EFF_TMSTMP,A.FLOAT_IND,A.INEREST_ACCR_AMT,
A.INTR_ADJ_DT,A.MADE_DT,A.MAT_DT,A.PD_OFF_F,A.PRIM_CUST_ID,A.STEP_F,
A.TOT_ADVNC_AMT,A.TRNST,A.UNPAID_MTH_PAY_DT,A.UNPAID_WKLY_PAY_DT,A.CLASS,
A.FUND_CD,A.SECURITY_TYPE,A.CRNT_BAL,A.FRCLSR_F,A.PD_OFF_DT,A.TOT_SUSP_BAL,
A.TNIF_RGN_CD,A.COMM_TP,A.INSUR_GRP,A.LRA_STAT,A.DLQNT_DAY,A.GL_ACCT_NUM,
A.GL_TRNST_NUM,A.PRD_GRP_CD,A.UNIT_CNT,A.CRNCY_CD,A.INSRT_PROCESS_TMSTMP
,A.IBMREPL_SITE,A.IBMREPL_KEY
from &FRG_DB..AIRB_MORT_MTH_SNAPSHOT  A
LEFT JOIN
(SELECT ACCT_NUM, MAX(BASEL_ACCT_ID) AS BASEL_ACCT_ID FROM &RRAP_DB..BASEL_ACCT_DIM
WHERE
TRIM(SRC_APP_CD) = 'MO'
GROUP BY ACCT_NUM) B ON A.MORT_NUM = TRIM(B.acct_NUM) 
WHERE A.TM_ID =&mth_tm_id.);) by iiascon;
execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS ON TABLE &FRG_DB..AIRB_MORT_MTH_SNAPSHOT_LGD on KEY COLUMNS and INDEXES ALL'));) by iiascon;
execute(COMMIT;) by iiascon;
quit;




*################ TABLE2:		BNSMORT_ACCT_LVL_DATA_LGD		###########################*;

proc sql;
connect using nz_frg as iiascon;
execute(delete from &FRG_DB..BNSMORT_ACCT_LVL_DATA_LGD where mth_tm_id = &mth_tm_id.;) by iiascon;
execute(commit;) by iiascon;
quit;


proc sql;
connect using nz_frg as iiascon;
execute(INSERT into &FRG_DB..BNSMORT_ACCT_LVL_DATA_LGD 
(MTH_TM_ID,MORTGAGE_NO,BASEL_ACCT_ID,PROCESS_DATE,
CRNT_BAL_AMT,INTR_ACCR_AMT,TOTAL_BAL,PD_OFF_F,PD_OFF_DT,FRCLSR_F,
TOT_SUSP_BAL_AMT,STATUS1,DEFAULT_DATE,DEFAULT_BAL,DEFAULT_IND,LTV,
AMORT,PD_SEG)
(SELECT 
A.MTH_TM_ID,A.MORTGAGE_NO,B.BASEL_ACCT_ID,A.PROCESS_DATE,
A.CRNT_BAL_AMT,A.INTR_ACCR_AMT,A.TOTAL_BAL,A.PD_OFF_F,A.PD_OFF_DT,A.FRCLSR_F,
A.TOT_SUSP_BAL_AMT,A.STATUS1,A.DEFAULT_DATE,A.DEFAULT_BAL,A.DEFAULT_IND,A.LTV,
A.AMORT,A.PD_SEG
from &FRG_DB..BNSMORT_ACCT_LVL_DATA  A
LEFT JOIN
(SELECT ACCT_NUM, MAX(BASEL_ACCT_ID) AS BASEL_ACCT_ID FROM &RRAP_DB..BASEL_ACCT_DIM
WHERE
TRIM(SRC_APP_CD) = 'MO'
GROUP BY ACCT_NUM) B ON A.MORTGAGE_NO = TRIM(B.acct_NUM) 
WHERE A.mth_tm_id =&mth_tm_id.);) by iiascon;
execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS ON TABLE &FRG_DB..BNSMORT_ACCT_LVL_DATA_LGD on KEY COLUMNS and INDEXES ALL'));) by iiascon;
execute(COMMIT;) by iiascon;
quit;


*################ TABLE3:	BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ_LGD	###########################*;

PROC SQL NOPRINT;
SELECT TM_LVL_END_DT FORMAT 8. INTO :TM_LVL_END_DT FROM NZRRAP.TM_DIM WHERE TM_ID =&mth_tm_id.;
QUIT;
DATA NZFORMATS;
CALL SYMPUT('SRC_TIME',"'"||PUT(&TM_LVL_END_DT,YYMMDD10.)||"'");
RUN;
%PUT SRC_TIME=&SRC_TIME;


proc sql;
connect using nz_frg as iiascon;
execute(delete from &FRG_DB..BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ_LGD where TIME_KEY = &SRC_TIME.;) by iiascon;
execute(commit;) by iiascon;
quit;


proc sql;
connect using nz_frg as iiascon;
execute(INSERT into &FRG_DB..BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ_LGD 
(MORTGAGE_NO,BASEL_ACCT_ID,TIME_KEY,INSURANCE,
BULK_IND,TOTAL_BAL,LGD24D,LGDC24D,LGDC_CAP_100,LGDC_CAP_150,STATUS,
DEFAULT_IND,AMORT,BI33MAX3M,DLQNT_DAYAVG24M,LTV,INDEX_TERANETV,
RATIO,URATE,PROVINCE_CD,SCORECARD_POINTS,B_LTV,B_PROP_VALUE,
B_BI33MAX3M,B_AMORT,B_DLQNT_DAYAVG24M,B_RATIO,SB_AMORT,SB_BI33MAX3M,
SB_DLQNT_DAYAVG24M,SB_LTV,SB_PROP_VALUE,SB_RATIO,BNS_LGD_ND_SEGMENT,
LGD24D_BKUP,LGDC24D_BKUP,LGDC_CAP_100_BKUP,LGDC_CAP_150_BKUP,
LGD_CAP_150,IBMREPL_SITE,IBMREPL_KEY)
(SELECT 
MORTGAGE_NO,BASEL_ACCT_ID,TIME_KEY,INSURANCE,
BULK_IND,TOTAL_BAL,LGD24D,LGDC24D,LGDC_CAP_100,LGDC_CAP_150,STATUS,
DEFAULT_IND,AMORT,BI33MAX3M,DLQNT_DAYAVG24M,LTV,INDEX_TERANETV,
RATIO,URATE,PROVINCE_CD,SCORECARD_POINTS,B_LTV,B_PROP_VALUE,
B_BI33MAX3M,B_AMORT,B_DLQNT_DAYAVG24M,B_RATIO,SB_AMORT,SB_BI33MAX3M,
SB_DLQNT_DAYAVG24M,SB_LTV,SB_PROP_VALUE,SB_RATIO,BNS_LGD_ND_SEGMENT,
LGD24D_BKUP,LGDC24D_BKUP,LGDC_CAP_100_BKUP,LGDC_CAP_150_BKUP,
LGD_CAP_150,IBMREPL_SITE,IBMREPL_KEY
from &FRG_DB..BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ  A
LEFT JOIN
(SELECT ACCT_NUM, MAX(BASEL_ACCT_ID) AS BASEL_ACCT_ID FROM &RRAP_DB..BASEL_ACCT_DIM
WHERE
TRIM(SRC_APP_CD) = 'MO'
GROUP BY ACCT_NUM) B ON A.MORTGAGE_NO = TRIM(B.acct_NUM) 
WHERE A.TIME_KEY =&SRC_TIME.);) by iiascon;
execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS ON TABLE &FRG_DB..BNS_LGD_ND_SCORED_SEG_ACCTS_ANTQ_LGD on KEY COLUMNS and INDEXES ALL'));) by iiascon;
execute(COMMIT;) by iiascon;
quit;



*################ TABLE4:	BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ_LGD		###########################*;

proc sql;
connect using nz_frg as iiascon;
execute(delete from &FRG_DB..BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ_LGD where TIME_KEY = &SRC_TIME.;) by iiascon;
execute(commit;) by iiascon;
quit;


proc sql;
connect using nz_frg as iiascon;
execute(INSERT into &FRG_DB..BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ_LGD
(MORTGAGE_NO,TIME_KEY,BASEL_ACCT_ID,INSURANCE,
BULK_IND,TOTAL_BAL,TOTAL_SUSPENSE,FORECLOSE_IND,MONTH_DEF,
ACCT_LGD24_NOCOST,ACCT_LGD24_NOCOST_CAP,ACCT_LGD24_COST,
ACCT_LGD24_COST_CAP15,RATIO,URATE,D2DBALMAX12M,INDEX_TERANETV,LTV,
SCORECARD_POINTS,B_FORECLOSE_IND,B_UNEMP_RATE_RATIO,B_D2DBALMAX12M,
B_MONTH_DEF,B_INDEX_TERANETV,B_LTV,SCORE_FORECLOSE_IND,
SCORE_UNEMP_RATIO,SCORE_D2DBALMAX12M,SCORE_MONTH_DEF,
SCORE_INDEX_TERANETV,SCORE_LTV,BNS_LGD_D_SEGMENT,ACCT_LGD24_NOCOST_BKUP,
ACCT_LGD24_NOCOST_CAP_BKUP,ACCT_LGD24_COST_BKUP,ACCT_LGD24_COST_CAP15_BKUP
,IBMREPL_SITE,IBMREPL_KEY) 
(SELECT 
MORTGAGE_NO,TIME_KEY,BASEL_ACCT_ID,INSURANCE,
BULK_IND,TOTAL_BAL,TOTAL_SUSPENSE,FORECLOSE_IND,MONTH_DEF,
ACCT_LGD24_NOCOST,ACCT_LGD24_NOCOST_CAP,ACCT_LGD24_COST,
ACCT_LGD24_COST_CAP15,RATIO,URATE,D2DBALMAX12M,INDEX_TERANETV,LTV,
SCORECARD_POINTS,B_FORECLOSE_IND,B_UNEMP_RATE_RATIO,B_D2DBALMAX12M,
B_MONTH_DEF,B_INDEX_TERANETV,B_LTV,SCORE_FORECLOSE_IND,
SCORE_UNEMP_RATIO,SCORE_D2DBALMAX12M,SCORE_MONTH_DEF,
SCORE_INDEX_TERANETV,SCORE_LTV,BNS_LGD_D_SEGMENT,ACCT_LGD24_NOCOST_BKUP,
ACCT_LGD24_NOCOST_CAP_BKUP,ACCT_LGD24_COST_BKUP,ACCT_LGD24_COST_CAP15_BKUP
,IBMREPL_SITE,IBMREPL_KEY
from &FRG_DB..BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ  A
LEFT JOIN
(SELECT ACCT_NUM, MAX(BASEL_ACCT_ID) AS BASEL_ACCT_ID FROM &RRAP_DB..BASEL_ACCT_DIM
WHERE
TRIM(SRC_APP_CD) = 'MO'
GROUP BY ACCT_NUM) B ON A.MORTGAGE_NO = TRIM(B.acct_NUM) 
WHERE A.TIME_KEY =&SRC_TIME.);) by iiascon;
execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS ON TABLE &FRG_DB..BNS_LGD_D_SCORED_SEG_ACCTS_ANTQ_LGD on KEY COLUMNS and INDEXES ALL'));) by iiascon;
execute(COMMIT;) by iiascon;
quit;



%put load end for &MTH_TM_ID;
%end;
%mend automate_36;
%automate_36;
quit;