/**************************************************************************** 
 * Job:             J_RRAP_TL10_2108_SCRD_VAR_STATS_SPL_  A57SWEI7.BH0009ID * 
 *                  CUST                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/02 - Term Loans/2.1                 * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:38:19 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009ID);
%let etls_jobName = %nrquote(J_RRAP_TL10_2108_SCRD_VAR_STATS_SPL_CUST);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_spl_autoexec                  A57SWEI7.BK000YU5 * 
 * Transform:       AM_rrap_spl_autoexec                                    * 
 * Description:     Autoexec file for termloan jobs. This points to auto    * 
 *                   call macros                                            * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000YU5);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_spl_autoexec;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_spl_autoexec **/

/*==========================================================================* 
 * Step:            User Written                          A57SWEI7.BK000YU6 * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Target Table:    User Written - work.WAHR62            A57SWEI7.BN000NGL * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000YU6);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.WAHR62;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NGL%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = i pn parts;
%let _OUTPUT_col_count = 3;
%let _OUTPUT_col0_name = i;
%let _OUTPUT_col0_table = work.WAHR62;
%let _OUTPUT_col0_length = 8;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = ;
%let _OUTPUT_col0_informat = ;
%let _OUTPUT_col0_label = %nrquote();
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = pn;
%let _OUTPUT_col1_table = work.WAHR62;
%let _OUTPUT_col1_length = 8;
%let _OUTPUT_col1_type = ;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote();
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input_count = 0;
%let _OUTPUT_col2_name = parts;
%let _OUTPUT_col2_table = work.WAHR62;
%let _OUTPUT_col2_length = 8;
%let _OUTPUT_col2_type = ;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote();
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input_count = 0;

%let _OUTPUT1 = work.WAHR62;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NGL%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = i pn parts;
%let _OUTPUT1_col_count = 3;
%let _OUTPUT1_col0_name = i;
%let _OUTPUT1_col0_table = work.WAHR62;
%let _OUTPUT1_col0_length = 8;
%let _OUTPUT1_col0_type = ;
%let _OUTPUT1_col0_format = ;
%let _OUTPUT1_col0_informat = ;
%let _OUTPUT1_col0_label = %nrquote();
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input_count = 0;
%let _OUTPUT1_col1_name = pn;
%let _OUTPUT1_col1_table = work.WAHR62;
%let _OUTPUT1_col1_length = 8;
%let _OUTPUT1_col1_type = ;
%let _OUTPUT1_col1_format = ;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote();
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input_count = 0;
%let _OUTPUT1_col2_name = parts;
%let _OUTPUT1_col2_table = work.WAHR62;
%let _OUTPUT1_col2_length = 8;
%let _OUTPUT1_col2_type = ;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote();
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input_count = 0;

/*---- Start of User Written Code  ----*/ 

data _null_;
   call sleep(30,1);
run;
%build_partitions_table(product=spl);

%put WORK LOCATION: %sysfunc(getoption(work));

%get_period_dates(product=spl, process=scrd);
%put Start and End Dates for SPL Scorecarding:;
%put start_period_dt: &start_period_dt;
%put end_period_dt: &end_period_dt;

/**** CONTROL TABLE ************************************************************************/
proc sql noprint;
	select TM_ID into :mth_tm_id
	from nzrrap.TM_DIM
	where tm_lvl='Month' and tm_lvl_end_dt = "&start_period_dt"d;

	select TM_ID into :end_mth_tm_id
	from nzrrap.TM_DIM
	where tm_lvl='Month' and tm_lvl_end_dt = "&end_period_dt"d;
quit;
%let MODULE=TL;
%let BATCH=2.1;
%etl_job_start(TARGET_TABLE=NZUSER.SCRD_VAR_STATS_SPL_CUST,MULTI_MONTH=Y);
/**** CONTROL TABLE ************************************************************************/

/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end User Written **/

/*==========================================================================* 
 * Step:            Loop                                  A57SWEI7.BK000YU7 * 
 * Transform:       Loop                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    User Written - work.WAHR62            A57SWEI7.BN000NGL * 
 * Target Table:    Loop - work.LOOPER                    A57SWEI7.BN000NGM * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000YU7);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.WAHR62, DATA)) or 
         %sysfunc(exist(work.WAHR62, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.WAHR62 out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.WAHR62); 

/* Capture summary statistics about this step for performance reporting  */ 
%put "DIS_SUMM";
%macro etls_getHandle(statusTable=, handleVariable=, row=); 
   %let etls_dsid = %sysfunc(open(&statusTable)); 
   %if (&etls_dsid = 0) %then 
      %put %sysfunc(sysmsg()); 
   %else 
   %do; 
      %let rc = %sysfunc(fetchobs(&etls_dsid, &row)); 
      %if (&rc ne 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %let etls_varnum = %sysfunc(varnum(&etls_dsid,&handleVariable)); 
         %if (&etls_varnum > 0) %then 
            %sysfunc(getvarc(&etls_dsid,&etls_varnum)); 
         %else 
            %put %sysfunc(sysmsg()); 
      %end; 
      %let rc = %sysfunc(close(&etls_dsid)); 
   %end; 
%mend etls_getHandle; 

%macro etls_freeHandle(statusTable=, statusVariable=, handleVariable=, 
   handleName=, statusSetting="Finished", 
   endTimeVariable=endTime, startTimeVariable=startTime, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, setMainJobRC=1, 
   statusUnknownReturnCode=., startTimeMacroVariable=, endTimeMacroVariable= ); 

   %if (&statusTable ne ) %then 
   %do; 
      %local etls_rcMacroVarExisted; 
      %let etls_rcMacroVarExisted = 0; 
      %if ("&returnCodeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_rcMacroVarExisted from dictionary.macros 
            where name=upcase("&returnCodeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_rcMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Return code from inner job not found.  Setting status to Unknown.;
            %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
         %end; 
         %if (&setMainJobRC eq 1) %then 
            %rcSet(&&&returnCodeMacroVariable); 
      %end; 
      %else 
      %do; 
         %let returnCodeMacroVariable=etls_rcmacvar; 
         %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
      %end; 

      %local etls_startTimeMacroVarExisted; 
      %let etls_startTimeMacroVarExisted = 0; 
      %if ("&startTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_startTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&startTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_startTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Start time from inner job not found.  No value will be set.;
            %let &startTimeMacroVariable=; 
         %end; 
      %end; 

      %local etls_endTimeMacroVarExisted; 
      %let etls_endTimeMacroVarExisted = 0; 
      %if ("&endTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_endTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&endTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_endTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) End time from inner job not found.  Setting end time to current
      time.;
            %let &endTimeMacroVariable=%sysfunc(datetime()); 
         %end; 
      %end; 

      data &statusTable; 
         modify &statusTable(where=(&handleVariable = &handleName)); 
         %if ("&startTimeMacroVariable" ne "") %then 
         %do; 
            &startTimeVariable = input(symget("&startTimeMacroVariable"),32.);; 
         %end; 
         %if ("&endTimeVariable" ne "") %then 
         %do; 
            %if ("&endTimeMacroVariable" ne "") %then 
            %do; 
               &endTimeVariable = input(symget("&endTimeMacroVariable"),32.);; 
            %end; 
            %else 
               &endTimeVariable = datetime();; 
         %end; 
         %if ("&returnCodeVariable" ne "") %then 
            &returnCodeVariable = input(symget("&returnCodeMacroVariable"),32.);; 
         %if ("&statusVariable" ne "") %then 
         %do; 
            if (symget("etls_rcMacroVarExisted") eq "0") then 
               &statusVariable = "Unknown Status"; 
            else
               &statusVariable = &statusSetting;
         %end;
         call symput('handle',&handleVariable); 
         replace; 
         stop; 
      run; 

      %rcSet(&syserr); 

      %if (&signoff eq 1) %then 
         %etls_signoff(handleName=&handle); 
   %end; 
%mend etls_freeHandle; 

%macro etls_createHandle(statusTable=,
                         statusVariable=,
                         handleVariable=,
                         handlePrefix=rmt,
                         gridOptionSet=,
                         workloadMacroVariable=,
                         row=,
                         machineVariable=,
                         statusSetting="Running", 
                         startTimeVariable=startTime,
                         signon=1,
                         useGrid=1,
                         log=,
                         output=,
                         gridRC=,
                         cmacvar=etls_signonStatus,
                         additionalSignonOptions=,
                         signonRetries= ); 

   %local remoteSessionId; 
   %let remoteSessionId = &handlePrefix.&row; 
   %let &cmacvar = 1; 
   %local etls_machineId; 
   %if (&signon eq 1) %then 

      %etls_signon(handleName=&remoteSessionId,
                   useGrid=&useGrid,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=&etls_gridOptionSet,
                   workloadMacroVariable=&workloadMacroVariable,
                   log=&log,
                   output=&output,
                   cmacvar=&cmacvar,
                   gridRC=&gridRC,
                   additionalSignonOptions=&additionalSignonOptions,
					signonRetries=&signonRetries,
                   gridJobName=DIS_&etls_jobName._&row); 

   %else %let &cmacvar=0; 

   data &statusTable; 
      retain ptr &row; 
      modify &statusTable point = ptr; 
      &handleVariable = "&remoteSessionId"; 
      %if (&signon eq 1) %then 
         &machineVariable = "&etls_machineId";; 
      %if (&&&cmacvar ne 0) %then 
      %do; 
         &statusVariable = "Failed Signon"; 
      %end; 
      %else 
         &statusVariable = &statusSetting;; 
      %if (&startTimeVariable ne ) %then 
         &startTimeVariable = datetime();; 
      replace; 
      stop; 
   run; 

   %rcSet(&syserr); 
%mend etls_createHandle; 

%macro etls_getParameterNames(parameterTable=, parameterVariableMacro=, startingColumnNumber=1);
   %let &parameterVariableMacro = ;
   %let dsid = %sysfunc(open(&parameterTable));
   %if (&dsid gt 0) %then 
   %do; 
      %do i=&startingColumnNumber %to %sysfunc(attrn(&dsid,nvars)); 
         %let &parameterVariableMacro = &&&parameterVariableMacro %sysfunc(varname(&dsid,&i)); 
      %end; 
      %let dsid = %sysfunc(close(&dsid)); 
   %end; 
   %else 
      %put %sysfunc(sysmsg()); 
   %rcSet(&syserr); 
%mend etls_getParameterNames; 

%macro etls_getParameters(parameterTable=, row=, startingColumnNumber=1 , handleName=); 
   data _null_; 
      length vname $256 vtype $1 value $32767; 
      dsid = open("&parameterTable"); 
      if (dsid > 0) then 
      do; 
         do _i = 1 to &row; 
            fetchrc = fetch(dsid); 
         end; 
         do _i=&startingColumnNumber to attrn(dsid,'nvars'); 
            vname = varname(dsid,_i); 
            vtype = vartype(dsid,_i); 
            if (fetchrc = 0) then 
            do; 
               if (vtype = 'C') then 
               do; 
                  value = getvarc(dsid,_i); 
                  value = tranwrd(value,"%","%%"); 
                  value = tranwrd(value,"(","%("); 
                  value = tranwrd(value,")","%)"); 
                  value = tranwrd(value,'"','%"'); 
                  value = tranwrd(value,"'","%'"); 
               end; 
               else 
                  value = left(put(getvarn(dsid,_i),best32.)); 
            end; /* fetchrc = 0 */ 
            
            put ;
            if indexc(trimn(value),"+-*/<>=^~;, '()&%",'"')>0 then 
            do; 
               value='%nrstr('||trim(value)||')'; 
               put "ETLS_DIAG%QUOTE(:) Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
               put "NOTE: Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
            end; 
            %if %str(&handlename) ne %str() %then 
            %do; 
               value = '%syslput '||trim(vname)||'= '||trim(value)||" / remote = &handleName;"; 
            %end; 
            %else 
            %do; 
               value = '%let '||trim(vname)||'= '||trim(value)||';'; 
            %end; 
            
            put "NOTE: Setting macro variable " vname "with statement:" value ;
            call execute(value); 
         end; /* do i= */ 
         dsid = close(dsid); 
      end; /* dsid > 0 */ 
      else 
      do; 
         put "ERROR%QUOTE(:) Parameter table, &parameterTable., could not be"
              " opened.";
         abort; 
      end; 
      stop; 
   run; 
   
   %rcSet(&syserr); 
%mend etls_getParameters; 

/* Check return codes for all processes  */ 
%macro etls_loopRCCheck(statusTable=, returnCodeVariable=,start=,end=); 
   %macro etls_loopRCError(_iteration); 
      /* Abort with a return code of  -5  */ 
      %abort return  -5; 
   %mend etls_loopRCError; 
   
   %local etls_rows etls_dsid rc etls_varnum;
   
   %let etls_rows = 0; 
   proc sql noprint; 
      select count(*) into :etls_rows from &statusTable; 
   quit; 
   
   %if &start le &etls_rows %then 
   %do; 
      %let etls_dsid = %sysfunc(open(&statusTable)); 
      %if (&etls_dsid = 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %do i=&start %to &end; 
            %let rc = %sysfunc(fetchobs(&etls_dsid, &i)); 
            %if (&rc ne 0) %then 
               %put %sysfunc(sysmsg()); 
            %else 
            %do; 
               %let etls_varnum = %sysfunc(varnum(&etls_dsid,&returnCodeVariable)); 
               %if (&etls_varnum > 0) %then 
               %do; 
                  %if ((%sysfunc(getvarn(&etls_dsid,&etls_varnum)) ge 5) and 
                       (&&etls_statusReported&i eq 0)) %then 
                  %do; 
                     %etls_loopRCError(&i); 
                     %let etls_statusReported&i = 1; 
                  %end; 
               %end; 
               %else 
                  %put %sysfunc(sysmsg()); 
            %end; 
         %end; 
         %let rc = %sysfunc(close(&etls_dsid)); 
      %end; 
   %end; 
%mend etls_loopRCCheck; 

%macro etls_loopW2FR03V; 
   %local etls_filePrefix; 
   %let etls_filePrefix = ; 
   
   %macro etls_processToLoopW2FR045(parameterTable=, row=, handleName=rmt);
      %local etls_parmvars; 
      %etls_getParameterNames(parameterTable=&parameterTable, 
         parameterVariableMacro=etls_parmvars, 
         startingColumnNumber=1); 
      %local &etls_parmvars; 
      %etls_getParameters(parameterTable=&parameterTable, row=&row, 
         startingColumnNumber=1); 
      %let etls_previousFilePrefix = &etls_filePrefix;
      %local etls_filePrefix; 
      %let etls_filePrefix = &etls_previousFilePrefix.&handleName; 
      %macro etls_jobW2FR04F; 
      
         /**************************************************************************** 
          * Job:             J_RRAP_TL10_2108A_SCRD_VAR_STATS_SPL  A57SWEI7.BH0009HE * 
          *                  _CUST                                                   * 
          * Description:                                                             * 
          *                                                                          * 
          * Metadata Server: 10.56.70.48                                             * 
          * Port:            8561                                                    * 
          * Location:        /Projects/RRAP/Jobs/02 - Term Loans/2.1/Inner Jobs      * 
          *                                                                          * 
          * Server:          SASApp                                A57SWEI7.AT000002 * 
          *                                                                          * 
          * Generated on:    Thursday, June 29, 2017 2:38:19 PM EDT                  * 
          * Generated by:    owprdsas                                                * 
          * Version:         SAS Data Integration Studio 4.8                         * 
          ****************************************************************************/ 
         
         /* Generate the process id for job  */ 
         %put Process ID: &SYSJOBID;
         
         /* General macro variables  */ 
         %let jobID = %quote(A57SWEI7.BH0009HE);
         %let etls_jobName = %nrquote(J_RRAP_TL10_2108A_SCRD_VAR_STATS_SPL_CUST);
         %let etls_userID = %nrquote(owprdsas);
         
         
         /* Create metadata macro variables */
         %let IOMServer      = %nrquote(SASApp);
         %let metaPort       = %nrquote(8561);
         %let metaServer     = %nrquote(iw503);
         
         /* Set metadata options */
         options metaport       = &metaPort 
                 metaserver     = "&metaServer"; 
         
         /* Setup for capturing job status  */ 
         %let etls_startTime = %sysfunc(datetime(),datetime.);
         %let etls_recordsBefore = 0;
         %let etls_recordsAfter = 0;
         %let etls_lib = 0;
         %let etls_table = 0;
         
         %global etls_debug; 
         %macro etls_setDebug; 
            %if %str(&etls_debug) ne 0 %then 
               OPTIONS MPRINT%str(;); 
         %mend; 
         %etls_setDebug; 
         
         /*---- Start of User Written Code  ----*/ 
         
          
         %let product=spl;
         %let datatype=cust;
         %let dsn=SCRD_VAR_STATS_INPUTS_&product._&datatype;
         %let key=basel_cust_id;
         %let time_key=mth_tm_id;
         
         /*
         %let pn=0;
         %let parts=1;
         */
         /*---- End of User Written Code  ----*/ 
         
         /**************************************************************************** 
          * Job:             J_RRAP_TL10_2108AA_SCRD_VAR_STATS_SP  A57SWEI7.BH0009HA * 
          *                  L_CUST                                                  * 
          * Description:                                                             * 
          *                                                                          * 
          * Metadata Server: 10.56.70.48                                             * 
          * Port:            8561                                                    * 
          * Location:        /Projects/RRAP/Jobs/02 - Term Loans/2.1/Inner Jobs      * 
          *                                                                          * 
          * Server:          SASApp                                A57SWEI7.AT000002 * 
          *                                                                          * 
          * Generated on:    Thursday, June 29, 2017 2:38:19 PM EDT                  * 
          * Generated by:    owprdsas                                                * 
          * Version:         SAS Data Integration Studio 4.8                         * 
          ****************************************************************************/ 
         
         /* Generate the process id for job  */ 
         %put Process ID: &SYSJOBID;
         
         /* General macro variables  */ 
         %let jobID = %quote(A57SWEI7.BH0009HA);
         %let etls_jobName = %nrquote(J_RRAP_TL10_2108AA_SCRD_VAR_STATS_SPL_CUST);
         %let etls_userID = %nrquote(owprdsas);
         
         
         /* Create metadata macro variables */
         %let IOMServer      = %nrquote(SASApp);
         %let metaPort       = %nrquote(8561);
         %let metaServer     = %nrquote(iw503);
         
         /* Set metadata options */
         options metaport       = &metaPort 
                 metaserver     = "&metaServer"; 
         
         /* Setup for capturing job status  */ 
         %let etls_startTime = %sysfunc(datetime(),datetime.);
         %let etls_recordsBefore = 0;
         %let etls_recordsAfter = 0;
         %let etls_lib = 0;
         %let etls_table = 0;
         
         %global etls_debug; 
         %macro etls_setDebug; 
            %if %str(&etls_debug) ne 0 %then 
               OPTIONS MPRINT%str(;); 
         %mend; 
         %etls_setDebug; 
         
         /*==========================================================================* 
          * Step:            AM_rrap_spl_autoexec                  A57SWEI7.BK000YT1 * 
          * Transform:       AM_rrap_spl_autoexec                                    * 
          * Description:     Autoexec file for termloan jobs. This points to auto    * 
          *                   call macros                                            * 
          *==========================================================================*/ 
         
         %let transformID = %quote(A57SWEI7.BK000YT1);
         %let trans_rc = 0;
         %let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 
         
         %let _INPUT_count = 0; 
         %let _OUTPUT_count = 0; 
         
         
         %put WORK LOCATION: %sysfunc(getoption(work));
         %rrap_spl_autoexec;
         
         
         %rcSet(&syserr); 
         %rcSet(&sysrc); 
         %rcSet(&sqlrc); 
         
         %rcSet(&syscc); 
         
         
         
         /**  Step end AM_rrap_spl_autoexec **/
         
         /*---- Start of User Written Code  ----*/ 
         
         %get_period_dates(product=&product, process=scrd);
         %put Start and End Dates for &product Scorecarding:;
         %put start_period_dt: &start_period_dt ;
         %put end_period_dt: &end_period_dt;
         %put parts: &parts;
         
         %get_interval_dates;
         
          
         %macro create_var_stat(table_name,id,time_key);
         
            data _null_;
               starttime1 = datetime();
               call symputx('starttime1', starttime1, 'g');
            run;
         
            options validvarname=any;
         
            proc sort data=&table_name;
               by &id. &time_key.;
            run;
         
            proc contents data=&table_name 
               out=col_list(where=(type=1 and format not in ('DATE' 'DATETIME')) keep=NAME TYPE FORMAT) noprint;
            run;
         
            data col_list;
               set col_list(where=(lowcase(name) not in ("&time_key." "&id.")));
               name2=compress(name,'_');
               if length(name2)<=30 then do;
                  output;
               end;
            run;
         
            proc sql noprint;
         
               select count(name) into :nvar trimmed
               from col_list;
         
            quit;
         
            %put number of variables = &nvar;
         
            %if %eval(&nvar < 1) %then
            %do;
               data &table_name._stat;
                  set &table_name.;
               run;
         
               %goto out;
            %end;
            %else %do;
               proc sql noprint;
         
                  select name into :keep_list separated by ' '
                  from col_list;
         
                  select name into :var1 - :var&nvar
                  from col_list;
         
               quit;
         
               proc transpose data=&table_name out=work.tdata(rename=(_name_=name col1=value));
                  by &id. &time_key.;
                  var &keep_list;
               run; 
         
               
               proc sort data=work.tdata;
                  by &id. name &time_key.;
               run;
         
               %let maxlag = 23;
               
               data tdata2(keep=&id. name &time_key.
                                    valavg3 valavg6 valavg24
                                    min3 min6 min24
                                    max3 max6 max12 max24
                                    valsum3 valsum6 valsum24
         	                        slp3 slp6
                                    valavg6_orig
                                    );
                  set work.tdata;
                  by &id. name &time_key.;
                  retain mcounter;
                  if first.name then mcounter = 1;
                  else mcounter + 1; 
                  vmm1 = value;
                  %do ii = 1 %to &maxlag;
                     %let jj = %eval(&ii. + 1); 
                     lagval&ii. = lag&ii.(value);
                     if mcounter >= &jj then 
                     vmm&jj. = lagval&ii.;
                     else vmm&jj. = .;   
                  %end;
         
                  valsum3 = sum(of vmm1-vmm3);
                  min3 = min(of vmm1-vmm3);
                  max3 = max(of vmm1-vmm3);
                  /* Customer fields need to convert null values to 0 so that the mean function divides by the correct value */
                  /* Original code:  valavg3 = mean(of vmm1-vmm3); */
         		   /* If there is a non-null in the 3 month period, use the coalesce function to ensure the mean function 
         		      considers all three values in the denominator of the calculation.  This function ignores null values */
                  if max3=. then
         		      valavg3=.;
         		   else 
                     valavg3 = mean(coalesce(vmm1,0), coalesce(vmm2,0), coalesce(vmm3,0));
                 
                  valsum6 = sum(of vmm1-vmm6);
         		   min6 = min(of vmm1-vmm6);
                  max6 = max(of vmm1-vmm6);
                  /* Customer fields need to convert null values to 0 so that the mean function divides by the correct value */
                  /* Original code: valavg6 = mean(of vmm1-vmm6);*/   
                  /* If there is a non-null in the 6 month period, use the coalesce function to ensure the mean function 
         		      considers all three values in the denominator of the calculation.  This function ignores null values */ 
         		   if max6=. then
         		      valavg6=.;
         	      else
                     valavg6 = mean(coalesce(vmm1,0), coalesce(vmm2,0), coalesce(vmm3,0), coalesce(vmm4,0),coalesce(vmm5,0), coalesce(vmm6,0));
         
				
                  /* 06Jul2015
                     CR41 - AT34avg6M now requries that averages ignore null values.  Therefore - calculating an average without coalesce. 
                     Coding for all time periods for consistency.  This value is used for AT34 downstream.  */
                  valavg6_orig = mean(of vmm1-vmm6);
          			
         
                  valsum12 = sum(of vmm1-vmm12);
         		   min12 = min(of vmm1-vmm12);
                  max12 = max(of vmm1-vmm12);
         		   /* Customer fields need to convert null values to 0 so that the mean function divides by the correct value */
                  /* Original code: valavg12 = mean(of vmm1-vmm12); */
         		   /* If there is a non-null in the 12 month period, use the coalesce function to ensure the mean function 
         		      considers all three values in the denominator of the calculation.  This function ignores null values */ 
                  if max12=. then
         		      valavg12=.;
                  else
                     valavg12 = mean(coalesce(vmm1,0), coalesce(vmm2,0), coalesce(vmm3,0), coalesce(vmm4,0),coalesce(vmm5,0), coalesce(vmm6,0), 
                                     coalesce(vmm7,0), coalesce(vmm8,0), coalesce(vmm9,0), coalesce(vmm10,0),coalesce(vmm11,0), coalesce(vmm12,0));
       
                  
                  
                    
                  valsum24 = sum(of vmm1-vmm24);
				  
         		   min24 = min(of vmm1-vmm24);
                  max24 = max(of vmm1-vmm24);
         		   /* Customer fields need to convert null values to 0 so that the mean function divides by the correct value */
                  /* valavg24 = mean(of vmm1-vmm24); */
         		   /* If there is a non-null in the 24 month period, use the coalesce function to ensure the mean function 
         		      considers all three values in the denominator of the calculation.  This function ignores null values */ 
                  if max24=. then
         		      valavg24=.;
                  else
                     valavg24 = mean(coalesce(vmm1,0), coalesce(vmm2,0), coalesce(vmm3,0), coalesce(vmm4,0),coalesce(vmm5,0), coalesce(vmm6,0), 
                                  coalesce(vmm7,0), coalesce(vmm8,0), coalesce(vmm9,0), coalesce(vmm10,0),coalesce(vmm11,0), coalesce(vmm12,0),
                                  coalesce(vmm13,0), coalesce(vmm14,0), coalesce(vmm15,0), coalesce(vmm16,0),coalesce(vmm17,0), coalesce(vmm18,0),
                                  coalesce(vmm19,0), coalesce(vmm20,0), coalesce(vmm21,0), coalesce(vmm22,0),coalesce(vmm23,0), coalesce(vmm24,0));
         
                        
         
                  
                  if mcounter = 1 then
                  do;
                     chg1 = .;
                     chg3 = .;
                     chg6 = .;
                     slp1 = .;
                     slp3 = .;
                     slp6 = .;
                  end;
                  else if mcounter < 3 then
                  do;
                     if vmm2 ne 0 then chg1 = (vmm1 - vmm2)/vmm2;
                     if vmm2 ne 0 then chg3 = (vmm1 - vmm2)/vmm2;
                     if vmm2 ne 0 then chg6 = (vmm1 - vmm2)/vmm2;
                     slp1 = (vmm1 - vmm2);
                     slp3 = (vmm1 - vmm2)/(mcounter-1);
                     slp6 = (vmm1 - vmm2)/(mcounter-1);
                  end;    
                  else if mcounter < 6 then
                  do;
                     if vmm2 ne 0 then chg1 = (vmm1 - vmm2)/vmm2;
                     if vmm3 ne 0 then chg3 = (vmm1 - vmm3)/vmm3;
                     %do kk = 3 %to 5;
                        if mcounter = &kk and vmm&kk. ne 0 then chg6 = (vmm1 - vmm&kk.)/vmm&kk.;
                        if mcounter = &kk then slp6 = (vmm1 - vmm&kk.)/(mcounter-1);
                     %end;
                     slp1 = (vmm1 - vmm2);
                     slp3 = (vmm1 - vmm3)/ 2;
                  end;
                  else
                  do;
                     if vmm2 ne 0 then chg1 = (vmm1 - vmm2)/vmm2;
                     if vmm3 ne 0 then chg3 = (vmm1 - vmm3)/vmm3;
                     if vmm6 ne 0 then chg6 = (vmm1 - vmm6)/vmm6;
                     slp1 = (vmm1 - vmm2);
                     slp3 = (vmm1 - vmm3)/ 2;
                     slp6 = (vmm1 - vmm6)/ 5;
                  end; 
               run;
            %end;
         
         	proc sql;
         	drop table tdata;
         	quit;
         	
         
            /* JD - May 30, 2015
            Adding where= to discard lookback data that is no longer needed 
            */
         
            proc sort data=tdata2(where=(mth_tm_id between &start_period_tm_key and &end_period_tm_key));
            by &id. &time_key.;
            run;
         
         %out:;
         
         data _null_;
               endtime1 = datetime();
               call symputx('endtime1', endtime1, 'g');
         run;
         
         %put The program ran for %sysevalf(&endtime1 - &starttime1) seconds;
         
         
         %mend;
         
         
         
         proc sql noprint ;
         	
         	create table &dsn as (
            
               select * from nzuser.&dsn  
               where mod(&key., &parts.) = &pn
         /*      and last_day(date_trunc('day',process_date)) = date(%nrbquote('&begin_dt_24_nz'))*/
         );
         
         quit;
         %create_var_stat(&dsn,&key,&time_key);
         
         
         /*---- End of User Written Code  ----*/ 
         
         %let etls_endTime = %sysfunc(datetime(),datetime.);
         
         
         
         /**  Job end J_RRAP_TL10_2108AA_SCRD_VAR_STATS_SPL_CUST **/
         
         /* Reset jobid and name */
         %let jobID = %quote(A57SWEI7.BH0009HE);
         %let etls_jobName = %nrquote(J_RRAP_TL10_2108A_SCRD_VAR_STATS_SPL_CUST);
         
         /*---- Start of User Written Code  ----*/ 
         
         
         
         %delete_table(nzuser.scrd_var_stats_&product._&datatype._&pn._tmp);
         
             
         %let var_list=AT29MAX12M AT29MAX6M AT34AVG6M AT34MAX12M AT34MAX3M AT34MAX6M AT84MAX6M 
         	           BR147MAX6M BR147MIN3M BR34MAX6M CUST13MAX6M CUST16MAX6M CUST18MIN24M CUST21MIN3M CUST22SLP3M
         	           CUST24AVG3M CUST24MAX6M CUST25MIN3M CUST32MIN6M GO04MAX3M GO11MAX12M GO22MAX3M GO11SLP6M PR01MAX6M RE33MAX24M AT34AVG6M_NULL_FLAG;
         
          /* 06Jul2015 - CR41 - AT34avg6m - the average calculation ignores null values in the denominator.  Also - if a flag in the Deli
                         file is equal to 'H' on a record where AT34 is null for the 6 months, AT34avg6m should now be null.  Field 
                         AT34AVG6M_NULL_FLAG is used here to complete that logic. */
         
         data nzuser.scrd_var_stats_&product._&datatype._&pn._tmp (keep= &key. &time_key. &var_list);
         set tdata2;
         by &key. &time_key.;
         retain &var_list;
         
         if first.&time_key. then do;
            AT29MAX12M=0;
            AT29MAX6M=0;
            AT34AVG6M=0;
            AT34MAX12M=0;
            AT34MAX3M=0;
            AT34MAX6M=0;
            AT84MAX6M=0;
            BR147MAX6M=0;
            BR147MIN3M=0;
            BR34MAX6M=0;
            CUST13MAX6M=0;
            CUST16MAX6M=0;
            CUST18MIN24M=0;
            CUST21MIN3M=0;
            CUST22SLP3M=0;
            CUST24AVG3M=0;
            CUST24MAX6M=0;
            CUST25MIN3M=0;
            CUST32MIN6M=0;
            GO04MAX3M=0;
            GO11MAX12M=0;
            GO11SLP6M=0;
            GO22MAX3M=0;
            PR01MAX6M=0;
            RE33MAX24M=0;
            AT34AVG6M_NULL_FLAG=0;
         end;
         
              
         if name = "AT29_NUM_OF_ACTV_INSTLMNT_TRDS" then do;
            AT29MAX12M=max12;
         	AT29MAX6M=max6;
         end;
         else if name="AT34_TOT_UTILZTN" then do;
            /* 06Jul2015 - CR41 changes the logic for AT34avg6m back to the original average calculation where null values are ignored. */
            AT34AVG6M=valavg6_orig;
            AT34MAX12M=max12;
            AT34MAX3M=max3;
            AT34MAX6M=max6;
         end;
         else if name="AT84_TOT_AMT_PAST_DUE" then
            AT84MAX6M=max6;
         else if name="BR147_MAX_CRNT_UTILZTN_BNK_REV" then do;
            BR147MAX6M=max6;
            BR147MIN3M=min3;
         end;
         else if name="BR34_TOT_UTIL_BNK_REVLVNG_CRDS" then
            BR34MAX6M=max6;
         else if name="CUST13" then
            CUST13MAX6M=max6;
         else if name="CUST16" then
            CUST16MAX6M=max6;
         else if name="CUST18" then
            CUST18MIN24M=min24;
         else if name="CUST21" then
            CUST21MIN3M=min3;
         else if name="CUST22" then
            CUST22SLP3M=slp3;
         else if name="CUST24" then do;
            CUST24AVG3M=valavg3;  
            CUST24MAX6M=max6;
         end;
         else if name="CUST25" then
            CUST25MIN3M=min3;
         else if name="CUST32" then
            CUST32MIN6M=min6;
         else if name="GO04" then
            GO04MAX3M=max3;
         else if name="GO11_PC_OF_TRDS_NEVER_DLQNT" then do;
            GO11MAX12M=max12;
            GO11SLP6M=slp6;
         end;
         else if name="GO22" then
            GO22MAX3M=max3;
         else if name="PR01_NUM_OF_BNKRPC" then
            PR01MAX6M=max6;
         else if name="RE33_TOT_BAL_REVLVNG" then
            RE33MAX24M=max24;
         else if name="AT34_NULL_FLAG" then
            AT34AVG6M_NULL_FLAG=valsum6;
         
         if last.&time_key. then do;
            if AT34AVG6M_NULL_FLAG > 0 then
               AT34AVG6M=.;
            output;
         end;
         run;
         
         
         /* Join Var Stats Output with Raw Inputs which weren't needed in Var Stats */
         %delete_table(nzuser.scrd_var_stats_&product._&datatype._&pn.);
         
         
         /* Select structure matches the target table */
         proc sql noprint ;
         connect using nzuser as nzcon;
         execute(
                  create table &FRG_DB..scrd_var_stats_&product._&datatype._&pn. as (
                  select  		        
                         v.BASEL_CUST_ID, 
                         v.MTH_TM_ID, 
                         v.AT29MAX12M, 
                         v.AT29MAX6M, 
                         v.AT34AVG6M, 
                         v.AT34MAX12M, 
                         v.AT34MAX3M, 
                         v.AT34MAX6M, 
                         v.AT84MAX6M, 
                         d.bad_payer_cnt as BAD_PAYER_IND, 
                         v.BR147MAX6M, 
                         v.BR147MIN3M, 
                         v.BR34MAX6M, 
                         v.CUST13MAX6M, 
                         v.CUST16MAX6M, 
                         v.CUST18MIN24M, 
                         v.CUST21MIN3M, 
                         v.CUST22SLP3M, 
                         v.CUST24AVG3M, 
                         v.CUST24MAX6M, 
                         v.CUST25MIN3M, 
                         v.CUST32MIN6M, 
                         (v.GO04MAX3M - GO22MAX3M) as GO05MAX3M, 
                         v.GO11MAX12M, 
                         v.GO11SLP6M, 
                         v.PR01MAX6M, 
                         v.RE33MAX24M 
         
         
                  from &FRG_DB..scrd_var_stats_&product._&datatype._&pn._tmp as v
         		      left join 
                       &RRAP_DB..BASEL_PSNL_LOAN_CUST_DRVD_VARS as d
                  on v.basel_cust_id=d.basel_cust_id and
                     v.MTH_TM_ID=d.mth_tm_id
         		   where mod(v.basel_cust_id, &parts.) = &pn and
         		         mod(d.basel_cust_id, &parts.) = &pn ) WITH DATA;
                  ) by nzcon;
          quit;	
         
         /* Clean up */
         %delete_table(nzuser.scrd_var_stats_&product._&datatype._&pn._tmp);
         
         
         data _null_;
               endtime1 = datetime();
               call symputx('endtime1', endtime1, 'g');
         run;
         
         %put The program ran for %sysevalf(&endtime1 - &starttime1) seconds;
         
         
         /*---- End of User Written Code  ----*/ 
         
         %let etls_endTime = %sysfunc(datetime(),datetime.);
         
         
         
         /**  Job end J_RRAP_TL10_2108A_SCRD_VAR_STATS_SPL_CUST **/
         
         /* Reset jobid and name */
         %let jobID = %quote(A57SWEI7.BH0009ID);
         %let etls_jobName = %nrquote(J_RRAP_TL10_2108_SCRD_VAR_STATS_SPL_CUST);
         
      %mend etls_jobW2FR04F; 
      
      %etls_jobW2FR04F; 
      
      %let handleName = %etls_getHandle(statusTable=&etls_statusTable,
         handleVariable=etls_handleName, row=&&&etls_controlName);
         
      %let job_rc&handleName. = &job_rc; 
      
      %etls_freeHandle(statusTable=&etls_statusTable, statusVariable=etls_status, 
         handleVariable=etls_handleName, handleName="&handleName", 
         startTimeVariable=etls_startTime, endTimeVariable=etls_endTime, signoff=0, 
         returnCodeVariable=etls_jobRC, returnCodeMacroVariable=job_rc&handleName., setMainJobRc=1); 
         
   %mend etls_processToLoopW2FR045;
   
   %local etls_controlTable etls_statusTable etls_controlName 
      etls_processesRunning etls_maxProcesses etls_parameterTable 
      etls_additionalSignonOptions etls_signonRetries;
   %let etls_controlName = L1_; 
   %let etls_statusTable = work.LOOPER; 
   %let etls_parameterTable = work.W2FR077; 
   %let &etls_controlName = 0;
   %let etls_controlTable = work.WAHR62;
   
   %put %str(NOTE: Creating status table...);
   data &etls_statusTable 
      (keep = etls_handleName etls_machineId etls_startTime etls_endTime etls_status 
              etls_jobRC
      );
      attrib etls_handleName length = $32
         label = 'Name of handle to remote session'; 
      attrib etls_machineId length = $32
         label = 'Name of machine executing the task'; 
      attrib etls_startTime length = 8
         format = nldatmap.
         label = 'Start time of task'; 
      attrib etls_endTime length = 8
         format = nldatmap.
         label = 'End time of task'; 
      attrib etls_status length = $32
         label = 'Current status of task'; 
      attrib etls_jobRC length = 8
         label = 'Return code of task'; 
      set &etls_controlTable;
   run;
   
   %rcSet(&syserr); 
   
   %put %str(NOTE: Creating parameter table...);
   proc sql; 
      create table &etls_parameterTable as 
         select parts as PARTS, 
                pn as PN 
         from &etls_controlTable; 
   quit; 
   
   %rcSet(&sqlrc); 
   
   /* Get the number of times to iterate from the number of rows in the source  */ 
   /*  table                                                                    */ 
   proc sql noprint; 
      select count(*) into :&etls_controlName._max from &etls_statusTable;
      %let &etls_controlName._max = &&&etls_controlName._max;
   quit;
   
   %rcSet(&sqlrc); 
   
   /* Initialize checks for status handling per iteration  */ 
   %do i=1 %to &&&etls_controlName._max; 
      %local etls_statusReported&i; 
      %let etls_statusReported&i = 0; 
   %end; 
   
   %let etls_maxProcesses = 1; 
   
   %if (&etls_maxProcesses > 0) %then 
   %do; 
      %do %until (&&&etls_controlName ge &&&etls_controlName._max); 
      
         %let etls_lastLoopPtr = &&&etls_controlName;
         
         %let etls_processesRunning = 0; 
         
         %do %while(&etls_processesRunning lt &&&etls_controlName._max 
            and &etls_processesRunning lt &etls_maxProcesses 
            and &&&etls_controlName lt &&&etls_controlName._max);
            
            %let &etls_controlName = %eval(&&&etls_controlName+1);
            
            %let job_rcLast=&job_rc; 
            
            %etls_createHandle(statusTable=&etls_statusTable,
                               statusVariable=etls_status,
                               handleVariable=etls_handleName,
                               handlePrefix=&etls_controlName,
                               statusSetting="Running",
                               row=&&&etls_controlName,
                               machineVariable=etls_machineId,
                               startTimeVariable=etls_startTime,
                               signon=0,
                               useGrid=0);
            
         %let etls_processesRunning = 1; 
         %etls_processToLoopW2FR045(parameterTable=&etls_parameterTable, row=&&&etls_controlName,
            handleName=%etls_getHandle(statusTable=&etls_statusTable,
            handleVariable=etls_handleName, row=&&&etls_controlName)); 
         
         /* Reset main Job_RC and Trans_RC to max return code of all iterations */ 
         %let job_rcThisIter=&job_rc; 
         %let job_rc=&job_rcLast; 
         %let trans_rc=&job_rcLast; 
         %rcSet(&job_rcThisIter); 
         
         %etls_loopRCCheck(statusTable=&etls_statusTable, returnCodeVariable=etls_jobRC, 
            start=&&&etls_controlName,end=&&&etls_controlName); 
      %end; 
      
   %end; 
   
%end;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W2FR077;
quit;

%mend etls_loopW2FR03V; 

%etls_loopW2FR03V; 

%rcSet(&syscc); 



/**  Step end Loop **/

/*==========================================================================* 
 * Step:            Loop End                              A57SWEI7.BK000YU9 * 
 * Transform:       Loop End                                                * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000YU9);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%rcSet(&syscc); 



/**  Step end Loop End **/

/*==========================================================================* 
 * Step:            User Written                          A57SWEI7.BK000YUA * 
 * Transform:       User Written                                            * 
 * Description:     Gathers the partitions into a single table in the FRG   * 
 *                   User netezza space                                     * 
 *                                                                          * 
 * Source Table:    User Written - work.WAHR62            A57SWEI7.BN000NGL * 
 * Target Table:    User Written - work.W1VPJJI           A57SWEI7.BN000NGN * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000YUA);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.WAHR62, DATA)) or 
         %sysfunc(exist(work.WAHR62, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.WAHR62 out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.WAHR62); 

%let _INPUT_count = 1;
%let _INPUT = work.WAHR62;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/User Written_A57SWEI7.BN000NGL%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT1 = work.WAHR62;
%let _INPUT1_connect = ;
%let _INPUT1_engine = ;
%let _INPUT1_memtype = DATA;
%let _INPUT1_options = %nrquote();
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NGL%(WorkTable%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote();

%let _OUTPUT_count = 1;
%let _OUTPUT = work.W1VPJJI;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NGN%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = i pn parts;
%let _OUTPUT_col_count = 3;
%let _OUTPUT_col0_name = i;
%let _OUTPUT_col0_table = work.W1VPJJI;
%let _OUTPUT_col0_length = 8;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = ;
%let _OUTPUT_col0_informat = ;
%let _OUTPUT_col0_label = %nrquote();
%let _OUTPUT_col0_input0 = i;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = i;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = pn;
%let _OUTPUT_col1_table = work.W1VPJJI;
%let _OUTPUT_col1_length = 8;
%let _OUTPUT_col1_type = ;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote();
%let _OUTPUT_col1_input0 = pn;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = pn;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = parts;
%let _OUTPUT_col2_table = work.W1VPJJI;
%let _OUTPUT_col2_length = 8;
%let _OUTPUT_col2_type = ;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote();
%let _OUTPUT_col2_input0 = parts;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = parts;
%let _OUTPUT_col2_input_count = 1;

%let _OUTPUT1 = work.W1VPJJI;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NGN%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = i pn parts;
%let _OUTPUT1_col_count = 3;
%let _OUTPUT1_col0_name = i;
%let _OUTPUT1_col0_table = work.W1VPJJI;
%let _OUTPUT1_col0_length = 8;
%let _OUTPUT1_col0_type = ;
%let _OUTPUT1_col0_format = ;
%let _OUTPUT1_col0_informat = ;
%let _OUTPUT1_col0_label = %nrquote();
%let _OUTPUT1_col0_input0 = i;
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input = i;
%let _OUTPUT1_col0_input_count = 1;
%let _OUTPUT1_col1_name = pn;
%let _OUTPUT1_col1_table = work.W1VPJJI;
%let _OUTPUT1_col1_length = 8;
%let _OUTPUT1_col1_type = ;
%let _OUTPUT1_col1_format = ;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote();
%let _OUTPUT1_col1_input0 = pn;
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input = pn;
%let _OUTPUT1_col1_input_count = 1;
%let _OUTPUT1_col2_name = parts;
%let _OUTPUT1_col2_table = work.W1VPJJI;
%let _OUTPUT1_col2_length = 8;
%let _OUTPUT1_col2_type = ;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote();
%let _OUTPUT1_col2_input0 = parts;
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input = parts;
%let _OUTPUT1_col2_input_count = 1;

/*---- Start of User Written Code  ----*/ 


options mprint mlogic;

/*Set macrovars to run job for Create Var Stats */
%let process=scrd;
%let product=spl;
%let datatype=cust;
%let dsn=&process._VAR_STATS_&product._&datatype.;
/*%let key=BASEL_CUST_ID;
%let time_key=MTH_TM_ID;
*/

data _null_;
   set &_input1;
   if _n_=1;
   call symput('parts',put(parts,3.));
run;


%load_to_netezza(table_name=&dsn., parts=&parts.);


/* Delete Partitioned Tables */
%macro delete_partitions(table_name=,parts=);
%do pn=0 %to &parts-1;
	 %delete_table(nzintmed.&table_name._&pn.); 
%end;

quit;
%mend delete_partitions;

%delete_partitions(table_name=&dsn., parts=&parts.);



/* Delete Temp Tables Used to Build Partitioned Tables */
%macro delete_partitions(table_name=,parts=);
%do pn=0 %to &parts-1;
	 %delete_table(nzintmed.&table_name._&pn._tmp); 
%end;

quit;
%mend delete_partitions;

%delete_partitions(table_name=&dsn., parts=&parts.);
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end User Written **/

/*---- Start of User Written Code  ----*/ 

%get_period_dates(product=SPL, process=scrd);
%put Start and End Dates for SPL Scorecarding:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;


proc sql noprint;
select tm_key into :start_period_tm_key
from control.tm_id_lkp
where sas_date="&start_period_dt"d;
quit;


proc sql noprint;
select tm_key into :end_period_tm_key
from control.tm_id_lkp
where sas_date="&end_period_dt"d;
quit;

%put start_period_tm_key: &start_period_tm_key;
%put end_period_tm_key: &end_period_tm_key;

 
/* Run the following join to filter out records which were needed for lookback
   calculations but not intended to be loaded.  Data that was not in both the 
   relationship table and the Deli file are most likely to removed from this 
   step.  The goal is to match record counts that are found in the 
*/

%delete_table(nzuser.SCRD_VAR_STATS_SPL_CUST_FILTERED);

/*options sastrace=',,,d' sastraceloc=saslog;*/

 
proc sql noprint ;
connect using nzuser as nzcon;
execute(

        create table &FRG_DB..SCRD_VAR_STATS_SPL_CUST_FILTERED as (
        select  r.*
          
        from ( select * from &RRAP_DB..BASEL_PSNL_LOAN_CUST_DRVD_VARS
               where mth_tm_id between &start_period_tm_key and &end_period_tm_key) as b
		  inner join
             &FRG_DB..SCRD_VAR_STATS_SPL_CUST as r
        on b.basel_cust_id=r.basel_cust_id and
           b.mth_tm_id=r.mth_tm_id
		    
		  order by b.mth_tm_id ) WITH DATA;
 
        ) by nzcon;
quit;

%etl_job_end;
/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

