 /**************************************************************************** 
 * Job:              															* 
 * Description:     This job loads the Account Derived Variable for Basel III model
 * 					changes - KS CC
 * Source:          BASEL_REVLVNG_CR_MTH_SNAPSHOT BASEL_REVLVNG_CR_BASE_DRVD_VARS * 
 * Target:			EDRTLRP1D.BASEL_CC_ACCT_SCORECRD_DRVD_VARS			          *
 * Developed By:                      							      			  * 
 * Changes:			
 **********************************************************************************/ 

DATA _NULL_;
	CALL SYMPUTX('PROCESSSTARTTIME',PUT(DATETIME(),DATETIME25.0));
RUN;

%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

PROC SQL NOPRINT;
SELECT TM_LVL_END_DT format=YYMMDD10. INTO :MTH_END_DT FROM NZRRAP.TM_DIM WHERE TM_ID = &MTH_TM_ID.;
QUIT;

%LET MTH_END_DT = %sysfunc(dequote("'&MTH_END_DT'")) ;
%put &MTH_END_DT;
%put &MTH_TM_ID;

PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (DELETE FROM &net_db..BASEL_CC_ACCT_SCORECRD_DRVD_VARS WHERE MTH_TM_ID=&MTH_TM_ID) BY NZCON;
QUIT;


PROC SQL ;
connect using NZRRAP as nzcon;	
execute(
INSERT INTO &net_db..BASEL_CC_ACCT_SCORECRD_DRVD_VARS 
SELECT DISTINCT
       SNAP.MTH_TM_ID,     
       SNAP.BASEL_ACCT_ID,   

	   /* CC PD Transactor */
	   SNAP.BAL_HIST_CSH_ADV_AMT,
	   FNC_CHRG.FNC_CHRG_AVG24M,

	   /* CC PD Revolver */
	   SNAP.TOT_UNPAID_FNCL_CHRG_AMT as TOT_UNP_FNC_CHRG_KSA ,
	   case WHEN (SNAP.CR_LMT_AMT =0 AND SNAP.TOT_NEW_BAL_AMT >0) THEN 1
     		WHEN SNAP.TOT_NEW_BAL_AMT <0 THEN 0
     		WHEN SNAP.CR_LMT_AMT <>0 THEN SNAP.TOT_NEW_BAL_AMT/SNAP.CR_LMT_AMT
     		ELSE null END AS UTIL_KSA,

	   /* CC PD Delinquent */
		CSH_ADV_MIN3M.BAL_HIST_CSH_ADV_KSAMIN3M,
		UTIL_KSAAVG3M.UTIL_KSAAVG3M,   

		/* CC PD/LGD */
		MAX(0,SNAP.BNS_DLQNT_DAY-30) BNS_DLQNT_DAY_GP_KSA,

	   /* CC LGD */
		UTIL_KSAAVG6M.UTIL_KSAAVG6M,
		TOT_UNP_FNC_CHRG_KSAAVG6M.TOT_UNP_FNC_CHRG_KSAAVG6M,
		
		/* EAD */
		CSH_AD_CRNT_C_BAL_KSAAVG6M.CSH_AD_CRNT_C_BAL_KSAAVG6M, 
		PRCH_CRNT_C_BAL_KSAMAX6M.PRCH_CRNT_C_BAL_KSAMAX6M,
				SYSDATE,
	    SYSDATE,
		CSH_AD_CRNT_C_BAL_KSASUM6M.CSH_AD_CRNT_C_BAL_KSASUM6M,
		Max_Utilization.UTIL_KSAMAX12M
FROM 
	&net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT SNAP

	LEFT JOIN &net_db..BASEL_REVLVNG_CR_BASE_DRVD_VARS DRVD 
	ON SNAP.MTH_TM_ID = DRVD.MTH_TM_ID
	AND SNAP.BASEL_ACCT_ID = DRVD.BASEL_ACCT_ID

	LEFT JOIN 
		(SELECT BASEL_ACCT_ID, AVG(TOT_CYCL_TO_DT_FNCL_CHRG_AMT) AS FNC_CHRG_AVG24M 
		FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
		WHERE MTH_TM_ID >= &MTH_TM_ID-920 AND MTH_TM_ID <= &MTH_TM_ID 
		GROUP BY BASEL_ACCT_ID) FNC_CHRG
	ON SNAP.BASEL_ACCT_ID = FNC_CHRG.BASEL_ACCT_ID

	LEFT JOIN 
		(SELECT BASEL_ACCT_ID, MIN(BAL_HIST_CSH_ADV_AMT) BAL_HIST_CSH_ADV_KSAMIN3M
		FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
		WHERE MTH_TM_ID >= &MTH_TM_ID-80 AND MTH_TM_ID <= &MTH_TM_ID 
		GROUP BY BASEL_ACCT_ID) CSH_ADV_MIN3M
	ON SNAP.BASEL_ACCT_ID = CSH_ADV_MIN3M.BASEL_ACCT_ID

	LEFT JOIN
		(SELECT BASEL_ACCT_ID, AVG(UTIL_KSA) UTIL_KSAAVG3M
			FROM
			(SELECT DISTINCT MTH_TM_ID, BASEL_ACCT_ID, 
				case WHEN (CR_LMT_AMT =0 AND TOT_NEW_BAL_AMT >0) THEN 1
     				 WHEN TOT_NEW_BAL_AMT <0 THEN 0
     				WHEN CR_LMT_AMT <>0 THEN TOT_NEW_BAL_AMT/CR_LMT_AMT
     				ELSE null END AS UTIL_KSA
			FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
			WHERE MTH_TM_ID >= &MTH_TM_ID-80 AND MTH_TM_ID <= &MTH_TM_ID )
			GROUP BY BASEL_ACCT_ID) UTIL_KSAAVG3M 
	ON SNAP.BASEL_ACCT_ID = UTIL_KSAAVG3M.BASEL_ACCT_ID

	LEFT JOIN
		(SELECT BASEL_ACCT_ID, AVG(UTIL_KSA) UTIL_KSAAVG6M
			FROM
			(SELECT DISTINCT MTH_TM_ID, BASEL_ACCT_ID, 
				case WHEN (CR_LMT_AMT =0 AND TOT_NEW_BAL_AMT >0) THEN 1
     				 WHEN TOT_NEW_BAL_AMT <0 THEN 0
     				WHEN CR_LMT_AMT <>0 THEN TOT_NEW_BAL_AMT/CR_LMT_AMT
     				ELSE null END AS UTIL_KSA
			FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
			WHERE MTH_TM_ID >= &MTH_TM_ID-200 AND MTH_TM_ID <= &MTH_TM_ID )
			GROUP BY BASEL_ACCT_ID) UTIL_KSAAVG6M 
	ON SNAP.BASEL_ACCT_ID = UTIL_KSAAVG6M.BASEL_ACCT_ID

	LEFT JOIN 
		(SELECT BASEL_ACCT_ID, AVG(TOT_UNPAID_FNCL_CHRG_AMT) AS TOT_UNP_FNC_CHRG_KSAAVG6M 
		FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
		WHERE MTH_TM_ID >= &MTH_TM_ID-200 AND MTH_TM_ID <= &MTH_TM_ID 
		GROUP BY BASEL_ACCT_ID) TOT_UNP_FNC_CHRG_KSAAVG6M
	ON SNAP.BASEL_ACCT_ID = TOT_UNP_FNC_CHRG_KSAAVG6M.BASEL_ACCT_ID

	LEFT JOIN 
		(SELECT BASEL_ACCT_ID, AVG(CSH_ADVNC_CRNT_CYCL_BAL_AMT) AS CSH_AD_CRNT_C_BAL_KSAAVG6M 
		FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
		WHERE MTH_TM_ID >= &MTH_TM_ID-200 AND MTH_TM_ID <= &MTH_TM_ID 
		GROUP BY BASEL_ACCT_ID) CSH_AD_CRNT_C_BAL_KSAAVG6M
	ON SNAP.BASEL_ACCT_ID = CSH_AD_CRNT_C_BAL_KSAAVG6M.BASEL_ACCT_ID

	LEFT JOIN 
		(SELECT BASEL_ACCT_ID, MAX(PRCH_CRNT_CYCL_BAL_AMT) AS PRCH_CRNT_C_BAL_KSAMAX6M 
		FROM &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
		WHERE MTH_TM_ID >= &MTH_TM_ID-200 AND MTH_TM_ID <= &MTH_TM_ID 
		GROUP BY BASEL_ACCT_ID) PRCH_CRNT_C_BAL_KSAMAX6M
	ON SNAP.BASEL_ACCT_ID = PRCH_CRNT_C_BAL_KSAMAX6M.BASEL_ACCT_ID



	LEFT JOIN
		(SELECT
	BASEL_ACCT_ID,
	SUM(CSH_ADVNC_CRNT_CYCL_BAL_AMT) AS CSH_AD_CRNT_C_BAL_KSASUM6M
FROM
	&net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
WHERE
	MTH_TM_ID BETWEEN (&MTH_TM_ID - 200)
	AND &MTH_TM_ID
GROUP BY
	BASEL_ACCT_ID) CSH_AD_CRNT_C_BAL_KSASUM6M
	ON SNAP.BASEL_ACCT_ID = CSH_AD_CRNT_C_BAL_KSASUM6M.BASEL_ACCT_ID

	LEFT JOIN
		(WITH Utilization_Calculation AS (
    SELECT 
        BASEL_ACCT_ID,
        MTH_TM_ID,
        case when CR_LMT_AMT=0 AND  TOT_NEW_BAL_AMT>0 THEN 1
					  when TOT_NEW_BAL_AMT<0 THEN 0
					  when CR_LMT_AMT<>0 then TOT_NEW_BAL_AMT/CR_LMT_AMT
					  else -1 END AS Utilization
    FROM 
        &net_db..BASEL_REVLVNG_CR_MTH_SNAPSHOT
    WHERE 
		MTH_TM_ID BETWEEN &MTH_TM_ID - 440 AND &MTH_TM_ID

)
SELECT 
    BASEL_ACCT_ID,
    MAX(Utilization) AS UTIL_KSAMAX12M
FROM 
    Utilization_Calculation
GROUP BY 
    BASEL_ACCT_ID) Max_Utilization
    ON SNAP.BASEL_ACCT_ID = Max_Utilization.BASEL_ACCT_ID
	WHERE SNAP.MTH_TM_ID=&mth_tm_id 
	AND SNAP.PRIM_BASEL_CUST_ID IS NOT NULL  
	AND SNAP.PRIM_BASEL_CUST_ID <> '-1' 
	AND DRVD.SML_BUS_F='N' 
	AND DRVD.CONSM_PRD_TREATMNT_CD='A'	

) BY NZCON;
QUIT;