/**************************************************************************** 
 * Job:             J_RRII_H11_001_ASST_DRC_COST_MTH_SNAPSHOT 				* 
 * Description:     Loads Direct Cost table                                 * 
 * Source:          ASSET_SRC_CURR                                          * 
 * Target:			ASST_DRC_COST_MTH_SNAPSHOT								*
 * Created on:    	Mar 20, 2020                 							* 
 * Changes:			
 ****************************************************************************/ 

DATA _NULL_;
	CALL SYMPUTX('PROCESSSTARTTIME',PUT(DATETIME(),DATETIME25.0));
RUN;

%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (DELETE FROM &net_db..ASST_DRC_COST_MTH_SNAPSHOT WHERE MTH_TM_ID = &MTH_TM_ID) BY NZCON;
QUIT;

PROC SQL;
CREATE TABLE ASSET_SRC_CURR_TMP AS
SELECT 
	A.*, 
	CASE WHEN TRIM(HOST_MNEMONIC) = 'MOR' then 'MO' else TRIM(HOST_MNEMONIC) END AS SRC_SYS_CD_JOIN,
	cats(repeat('0',23-length(TRIM(A.ACCOUNTNUMBER))-1), TRIM(A.ACCOUNTNUMBER)) AS ACCT_NUM
FROM 
	NZRRAP.ASSET_SRC_CURR A
;
QUIT;

PROC SQL;
	CREATE TABLE BASEL_ACCT_DIM_TMP AS SELECT * FROM NZRRAP.BASEL_ACCT_DIM WHERE SRC_SYS_DEL_F = 'N';
QUIT;

PROC SQL;
	CREATE TABLE TEMP AS
	SELECT A.*,
	(CASE WHEN B.BASEL_ACCT_ID IS NULL THEN -1 ELSE B.BASEL_ACCT_ID END) AS BASEL_ACCT_ID
	FROM ASSET_SRC_CURR_TMP A LEFT JOIN BASEL_ACCT_DIM_TMP B
	ON A.SRC_SYS_CD_JOIN = B.SRC_APP_CD
	AND TRIM(A.ACCT_NUM) = TRIM(B.ACCT_NUM)
	;
QUIT;

proc sql noprint;
	SELECT MAX(ASST_ID) INTO :MAX_ASST_ID FROM NZRRAP.ASST_DRC_COST_MTH_SNAPSHOT;
QUIT;

proc sort data= TEMP OUT=TEMP2;
	by BASID;
RUN;

DATA TOLOAD;
	SET TEMP2;
	BY BASID;
	IF _N_ = 1 THEN SEQ = &MAX_ASST_ID + 100;
	ELSE SEQ + 1;
RUN;

PROC SQL;
	CREATE TABLE FINAL_LOAD AS
	SELECT
	SEQ									AS ASST_ID,
	&MTH_TM_ID							AS MTH_TM_ID,
	BASID 								AS ASST_BASE_ID, 
	ASSETNUMBER 						AS ASST_NUM, 
	ACCT_NUM							AS ACCT_NUM, 
	TRANSITNUMBER						AS TRNST_NUM,
	BASEL_ACCT_ID						AS BASEL_ACCT_ID,
	trim(AGREEMENTTYPE)					AS AGRMNT_TP_DESC, 
	trim(HOST_MNEMONIC)					AS SRC_SYS_CD,
	trim(PROGRAMTYPE)					AS PGM_TP_CD, 
	BALANCEOWING						AS BAL_OWING_AMT, 
	PRINCIPALOWINGATASSIGNMENT			AS ASGNMN_PRNCPL_OWING_AMT, 
	ACCRUEDINTERESTATASSIGNMENT			AS ASGNMN_ACCR_INTR_AMT, 
	ADDONCOSTSATASSIGNMENT				AS ASGNMN_ADD_ON_COST_AMT, 
	ASSIGNMENTDATE						AS ASGNMN_DT, 
	trim(INSTRUCTION)					AS INSTRC_DESC, 
	trim(STATUS)						AS STAT_DESC, 
	trim(ACCOUNTSTATUS)					AS ACCT_STAT_DESC, 
	trim(JUDGEMENTINDICATOR) 			AS JUDGEMENT_CD, 
	LEGALCOSTS							AS LEGAL_COST_AMT, 
	PROPERTYMANAGEMENTCOSTS				AS PRPTY_MGT_COST_AMT, 
	INSPECTIONFEES 						AS INSPECTION_FEE_AMT, 
	ENVIRONMENTALFEES 					AS ENVRNMTL_FEE_AMT, 
	GSTONINCOME 						AS INCM_GST_AMT, 
	UTILITIES 							AS UTL_AMT, 
	REPAIRS								AS REPAIR_AMT, 
	CREDITREPORTINGCOSTS				AS CR_RPTG_COST_AMT, 
	CORPORATERISKINSURANCE				AS CORP_RISK_INSUR_AMT, 
	TAXES 								AS TAX_AMT,
	APPRAISALFEES 						AS APPRAISAL_FEE_AMT,
	CONDOMINIUMFEES 					AS CONDMNM_FEE_AMT,
	MISCELLANEOUSFEES 					AS MISC_FEE_AMT,
	LOADFEE 							AS LOAD_FEE_AMT,
	COMMISIONS 							AS COMMSN_AMT,
	TOTALCOSTSOREXPENSES 				AS TOT_COST_EXPNS_AMT,
	DOLLARSRECOVEREDRECEIVED 			AS DOLLARS_RECOVERED_RECVD_AMT,
	PROCEEDSTOPAYFOREXP 				AS PRCD_TO_PAY_FOR_EXPNS_AMT,
	TOTALRECOVERIES 					AS TOT_RCVRY_AMT,
	HOLDBACKS 							AS HLDBCK_AMT,
	APPRAISAL 							AS APPRAISAL_AMT,
	MONTHENDPRINCIPALBALOWING 			AS MTH_END_PRNCPL_BAL_OWING_AMT,
	MONTHENDACCRUEDINTERESTOWING 		AS MTH_END_ACCR_INTR_OWING_AMT,
	MONTHENDADDONCOST 					AS MTH_END_ADD_ON_COST_AMT,
	trim(HIGHWAY) 						AS HGHWY_CD,
	trim(STATE) 						AS STATE_DESC,
	DATEPART(closeddate) format YYMMDD10. 	AS CLS_DT,
	&SESSIONTIME						AS INSRT_PROCESS_TMSTMP,
	&SESSIONTIME						AS UPDT_PROCESS_TMSTMP
	FROM TOLOAD;
QUIT;

PROC APPEND BASE=NZRRAP.ASST_DRC_COST_MTH_SNAPSHOT DATA=FINAL_LOAD FORCE; RUN;

/************** JOB LOG *****************/
PROC SQL NOPRINT;
	SELECT COUNT(*) INTO :SRC_COUNT FROM NZRRAP.ASSET_SRC_CURR ;
QUIT;

PROC SQL NOPRINT;
	SELECT COUNT(*) INTO :TGT_COUNT FROM NZRRAP.ASST_DRC_COST_MTH_SNAPSHOT WHERE MTH_TM_ID = &MTH_TM_ID;
QUIT;

DATA _NULL_;
	CALL SYMPUTX('PROCESSENDTIME',PUT(DATETIME(),DATETIME25.0));
RUN;


PROC SQL NOPRINT;
	insert into NZRRAP.AUDIT_JOB_TIMER_CHECK (JOB_NAME, MTH_TM_ID, START_TIME, END_TIME, SOURCE_COUNT, TARGET_COUNT)
		values ('J_RRII_H11_001_ASST_DRC_COST_MTH_SNAPSHOT',&MTH_TM_ID., "&PROCESSSTARTTIME"dt, "&PROCESSENDTIME"dt, &SRC_COUNT., &TGT_COUNT.);
QUIT;



/* JOB END */
