/**************************************************************************** 
 * Job:             J_RRAP_DLGD_0090_BASEL_ACCT_LTV_DRVD  A57SWEI7.BH000I5O * 
 *                  _VARS                                                   * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503                                                * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/06 - DLGD                           * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Monday, December 4, 2017 10:39:47 AM EST                * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH000I5O);
%let etls_jobName = %nrquote(J_RRAP_DLGD_0090_BASEL_ACCT_LTV_DRVD_VARS);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            RRAP_DLGD_AUTOEXEC                    A57SWEI7.BK0011SO * 
 * Transform:       RRAP_DLGD_AUTOEXEC                                      * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK0011SO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 



%rrap_dlgd_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end RRAP_DLGD_AUTOEXEC **/

/*---- Start of User Written Code  ----*/ 

%let dlgd_date=01NOV2016;
/*---- End of User Written Code  ----*/ 

/*---- Start of User Written Code  ----*/ 




proc sql;
	create table KS as
	select a.MTH_TM_ID, a.basel_acct_id, a.STEP_PLN_SNAPSHOT_ID 
/*	,a.PRD_CD, a.SUB_PRD_CD, b.BASEL_PRD_CD, b.BASEL_PRD_DESC, b.LTV_TP_CD, d.BASEL_SEG_ID, a.TOT_NEW_BAL_AMT, a.CR_LMT_AMT*/
	,CASE WHEN b.LTV_TP_CD = 'LOC' then 2
		 WHEN b.LTV_TP_CD = 'VISA' then 4
		 ELSE .
	END as ACCT_SENRTY_CD
	,CASE WHEN b.LTV_TP_CD in ('LOC','VISA') then MAX(a.TOT_NEW_BAL_AMT, a.CR_LMT_AMT)
		 ELSE .
	END as MAX_ACCT_BAL_AMT
	,d.FINAL_RTO as EXPSR_AT_DFT_RTO
	,e.CRNT_PRPTY_VAL_AMT

	FROM 

	NZRRAP.BASEL_REVLVNG_CR_MTH_SNAPSHOT a 

	inner join NZRRAP.BASEL_REVLVNG_CR_BASE_DRVD_VARS b
	on a.mth_tm_id = b.mth_tm_id and a.basel_acct_id=b.basel_acct_id  

	left join NZRRAP.TM_DIM t
	on a.mth_tm_id = t.tm_id and t.tm_lvl='Month'

	left join NZRRAP.EAD_SEG_ACCT_XREF c
	on a.mth_tm_id = c.mth_tm_id and a.basel_acct_id=c.basel_acct_id 

	left join NZRRAP.BASEL_SEG_RPTG_PARM d
	on c.BASEL_SEG_ID=d.BASEL_SEG_ID and d.EFF_FROM_DT LE t.tm_lvl_end_dt and d.EFF_TO_DT GE t.tm_lvl_end_dt

	left join NZRRAP.BASEL_STEP_LTV_DRVD_VARS e
	on a.STEP_PLN_SNAPSHOT_ID = e.STEP_PLN_SNAPSHOT_ID and e.STEP_PLN_SNAPSHOT_ID ne -1 and a.mth_tm_id = e.mth_tm_id

	where a.mth_tm_id = &mth_tm_id. and b.Heloc_F = 'Y' 
	and a.ACCT_OPND_DT >= "&dlgd_date."d
	order by a.mth_tm_id, a.STEP_PLN_SNAPSHOT_ID, ACCT_SENRTY_CD, CRNT_PRPTY_VAL_AMT desc
;quit;


proc sql;
	create table SPL as
	select a.mth_tm_id, a.basel_acct_id, a.STEP_PLN_SNAPSHOT_ID
	,3 as ACCT_SENRTY_CD
	,b.OS_BAL_AMT_V2 as MAX_ACCT_BAL_AMT
	,1 as EXPSR_AT_DFT_RTO
	,e.CRNT_PRPTY_VAL_AMT

	FROM 

	NZRRAP.BASEL_PSNL_LOAN_MTH_SNAPSHOT a

	inner join NZRRAP.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2 b
	on a.mth_tm_id = b.mth_tm_id
	and a.BASEL_ACCT_ID = b.BASEL_ACCT_ID

	left join NZRRAP.BASEL_STEP_LTV_DRVD_VARS e
	on a.STEP_PLN_SNAPSHOT_ID = e.STEP_PLN_SNAPSHOT_ID  and a.mth_tm_id = e.mth_tm_id
			and e.STEP_PLN_SNAPSHOT_ID ne -1


	where a.mth_tm_id = &mth_tm_id.
	and UPCASE(b.PRD_ID) in  ('S05', 'S08') 
	and a.NOTE_DT >= "&dlgd_date."d

	order by a.mth_tm_id, a.STEP_PLN_SNAPSHOT_ID, ACCT_SENRTY_CD, CRNT_PRPTY_VAL_AMT desc

;quit;




/*
SELECT * FROM BASEL_MORT_MTH_SNAPSHOT WHERE mth_tm_id=@PROCESSING MONTH AND SCRTY_TP_DESC = 'Uninsured' 
and (INTR_ADJ_DT or LAST_RNEW_DT >= November 1 , 2016) . USE MORTGAGE_NO
*/

proc sql noprint;
select tm_lvl_end_dt into :month_end_dt 
from nzrrap.tm_dim t
where t.tm_lvl='Month' and t.tm_id = &mth_tm_id.;
quit;
%put &month_end_dt.;

proc sql;
	create table MOR as
	select a.MTH_TM_ID, a.basel_acct_id, a.STEP_PLN_SNAPSHOT_ID, MORT_NUM length = 80 format=$80. informat=$80. as ACCT_NUM
	,1 as ACCT_SENRTY_CD
	,b.OS_BAL_AMT as MAX_ACCT_BAL_AMT
	,1 as EXPSR_AT_DFT_RTO
	,COALESCE(e.CRNT_PRPTY_VAL_AMT,F.INDEX_TERANETV) as CRNT_PRPTY_VAL_AMT

	FROM 

	nzrrap.BASEL_MORT_MTH_SNAPSHOT a

	inner join nzrrap.BASEL_MORT_ACCT_DRVD_VARS b
	on a.mth_tm_id = b.mth_tm_id
	and a.BASEL_ACCT_ID = b.BASEL_ACCT_ID

	/*LEFT JOIN NZFRGUSR.BASE_BNS_MOR_RPT_TBL c */
	LEFT JOIN NZFRGUSR.BASE_BNS_MOR_RPT_TBL c
	on a.mort_num = strip(put(c.MORTGAGE_NO,7.)) and c.mth_tm_id =&mth_tm_id.

	left join NZRRAP.BASEL_STEP_LTV_DRVD_VARS e
	on a.STEP_PLN_SNAPSHOT_ID = e.STEP_PLN_SNAPSHOT_ID  and a.mth_tm_id = e.mth_tm_id

	left join NZFRGUSR.LTV_VAR_CLUS_LTV_FINAL f
	on input(a.MORT_NUM,7.) = f.MORTGAGE_NO and f.YYMTH = input(put("&month_end_dt."d, yymmn6.),6.)
	where a.mth_tm_id = &mth_tm_id. AND  
	
	(case when a.mth_tm_id ge 17156 then UPCASE(c.SCRTY_TP_DESC) in ('UNINSURED','INSURED') 
	  ELSE UPCASE(c.SCRTY_TP_DESC) in ('UNINSURED') 
 	end)
/*DLGD Insured - Effective Nov2017	*/
/*	upcase(c.SCRTY_TP_DESC) in ('UNINSURED','UNINSURED')*/
	and (a.LAST_RNEW_DT >= "&dlgd_date."d or a.INTR_ADJ_DT >= "&dlgd_date."d )
	and e.STEP_PLN_SNAPSHOT_ID ne -1
	order by a.mth_tm_id, a.STEP_PLN_SNAPSHOT_ID, ACCT_SENRTY_CD, CRNT_PRPTY_VAL_AMT desc

;quit;


/*SELECT * FROM TNG_ACCT_MO WHERE month_end_dt=@PROCESSING MONTH AND SCRTY_TP_DESC = 'Uninsured' 
and (OPEN_DT  or LAST_RNEW_DT >= November 1 , 2016) . USE ACCOUNT_ID 

        left join
        NZFRG.mor_reporting_product as b
        on (upcase(a.src_sys_cd) = upcase(b.source_system_code) and
            upcase(a.insur_group) = upcase(b.basel_mortgage_insurer_group_des) and
            upcase(a.bulk_ind) = upcase(b.bulk_indicator))
*/

proc sql;
create table TNG as 
select b.source_system_code, &mth_tm_id. as MTH_TM_ID, -1 as BASEL_ACCT_ID, STRIP(a.ACCOUNT_ID) length = 80 format=$80. informat=$80. as ACCT_NUM, -1 as STEP_PLN_SNAPSHOT_ID
	,1 as ACCT_SENRTY_CD
	,a.END_PRINCIPAL_BALANCE as MAX_ACCT_BAL_AMT
	,1 as EXPSR_AT_DFT_RTO
	,c.PROP_VAL_NEW as CRNT_PRPTY_VAL_AMT
	

from NZTNG.tng_acct_mo a
        left join
        NZFRGUSR.mor_reporting_product as b
        on (
            upcase(a.insurer_desc) = upcase(b.basel_mortgage_insurer_group_des) and
            (case when upcase(a.bulk_nsurer_desc)='BULKINSURED' then 'Y' else 'N' end) = upcase(b.bulk_indicator))

		left join NZFRGUSR.TNG_PD_VAR_CREATION_FINAL c
		on a.ACCOUNT_ID = c.ACCOUNT_ID and a.month_end_dt = c.month_end_dt
		where a.month_end_dt = "&month_end_dt."d
and (OPEN_DT >= "&dlgd_date."d or LAST_RENEWAL_DT>= "&dlgd_date."d)
and upcase(b.source_system_code) = 'TNG-MOR' and 

(case when a.month_end_dt ge '30NOV2017'd then UPCASE(b.SECURITY_TYPE) in ('UNINSURED','INSURED') 
	  ELSE UPCASE(b.SECURITY_TYPE) in ('UNINSURED') 
 end)
/*DLGD Insured - Effective Nov2017	*/
 	order by mth_tm_id, STEP_PLN_SNAPSHOT_ID, ACCT_SENRTY_CD, CRNT_PRPTY_VAL_AMT desc

;quit;


data STEP NOSTEP;
set KS SPL MOR TNG;
by mth_tm_id step_pln_snapshot_id acct_senrty_cd;

if step_pln_snapshot_id in (-1,-2) then do;
		CRNT_LTV_RTO = (MAX_ACCT_BAL_AMT * EXPSR_AT_DFT_RTO) / CRNT_PRPTY_VAL_AMT;
		INDEXED_CCLTV_RTO = CRNT_LTV_RTO;
		output NOSTEP;
end;
else do;

	if first.ACCT_SENRTY_CD then do;
		SUM_EAD_DOLLAR = 0; COUNT_ACCT = 0; 
	end;
		EAD_DOLLAR = EXPSR_AT_DFT_RTO * MAX_ACCT_BAL_AMT;
		SUM_EAD_DOLLAR + EAD_DOLLAR;

		COUNT_ACCT + 1;
		
		output STEP;
end;
run;


data STEP;
	set STEP;
	if CRNT_PRPTY_VAL_AMT = 0 then COUNT_ACCT=-1;
/*make sure that a zero value for CRNT_PRPTY_VAL_AMT is not used*/
run;

proc sort data=STEP(DROP =  CRNT_LTV_RTO INDEXED_CCLTV_RTO) out=STEP1;
	by step_pln_snapshot_id ACCT_SENRTY_CD descending COUNT_ACCT ;
run;

data step2;
	set step1;
	by mth_tm_id step_pln_snapshot_id acct_senrty_cd descending COUNT_ACCT ;
	RETAIN CRNT_LTV_RTO INDEXED_CCLTV_RTO;

	IF FIRST.step_pln_snapshot_id then do;
		INDEXED_CCLTV_RTO = SUM_EAD_DOLLAR / CRNT_PRPTY_VAL_AMT;
		CRNT_LTV_RTO = SUM_EAD_DOLLAR / CRNT_PRPTY_VAL_AMT;
	end;

	if first.acct_senrty_cd and not first.step_pln_snapshot_id then do;
		CRNT_LTV_RTO = SUM_EAD_DOLLAR / CRNT_PRPTY_VAL_AMT;
		INDEXED_CCLTV_RTO + CRNT_LTV_RTO;
	end;
run;


data PRELOAD;
	attrib
	   BASEL_ACCT_ID length= 8 format=20. informat=20. label='BASEL_ACCT_ID'
	   MTH_TM_ID length= 8 format=11. informat=11. label='MTH_TM_ID'
	   STEP_PLN_SNAPSHOT_ID length= 8 format=20. informat=20. label='STEP_PLN_SNAPSHOT_ID'
	   ACCT_NUM length= $80 format=$80. informat=$80. label='ACCT_NUM'
	   ACCT_SENRTY_CD length= 8 format=20. informat=20. label='ACCT_SENRTY_CD'
	   MAX_ACCT_BAL_AMT length= 8 format=19.3 informat=19.3 label='MAX_ACCT_BAL_AMT'
	   EXPSR_AT_DFT_RTO length= 8 format=30.8 informat=30.8 label='EXPSR_AT_DFT_RTO'
	   CRNT_LTV_RTO length= 8 format=23.20 informat=23.20 label='CRNT_LTV_RTO'
	   INDEXED_CCLTV_RTO length= 8 format=23.20 informat=23.20 label='INDEXED_CCLTV_RTO'
	   INSRT_PROCESS_TMSTMP length= 8 format=DATETIME25.6 informat=DATETIME25.6 label='INSRT_PROCESS_TMSTMP'
	   UPDT_PROCESS_TMSTMP length= 8 format=DATETIME25.6 informat=DATETIME25.6 label='UPDT_PROCESS_TMSTMP';

	set NOSTEP STEP2;

	INSRT_PROCESS_TMSTMP = "&SYSDATE9.:&SYSTIME"dt;
	UPDT_PROCESS_TMSTMP = "&SYSDATE9.:&SYSTIME"dt;

	KEEP BASEL_ACCT_ID MTH_TM_ID STEP_PLN_SNAPSHOT_ID ACCT_NUM ACCT_SENRTY_CD 
		MAX_ACCT_BAL_AMT EXPSR_AT_DFT_RTO CRNT_LTV_RTO INDEXED_CCLTV_RTO 
		INSRT_PROCESS_TMSTMP UPDT_PROCESS_TMSTMP;
run;



proc sql;
connect using nzrrap as nzcon;
execute(delete from EDRTLRP1D.BASEL_ACCT_LTV_DRVD_VARS where mth_tm_id = &mth_tm_id.) by nzcon;
quit;

proc append base=NZRRAP.BASEL_ACCT_LTV_DRVD_VARS (BULKLOAD=YES BL_METHOD=CLILOAD) data=PRELOAD force; run;


/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

