/**************************************************************************** 
 * Job:             J_RRAP_MOR_SRC_0130_BNS_CIS_DATA_NEW  A57SWEI7.BH0009L9 * 
 *                  _FINAL                                                  * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/04 - Mortgage/Source                * 
 *                   Automation/Jobs/BNS                                    * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:44:28 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009L9);
%let etls_jobName = %nrquote(J_RRAP_MOR_SRC_0130_BNS_CIS_DATA_NEW_FINAL);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

data _null_;
   call sleep(10,1);
run;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            AM_rrap_mor_bns_autoexec              A57SWEI7.BK000ZA5 * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZA5);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mor_bns_autoexec **/

/*==========================================================================* 
 * Step:            Read Flat File                        A57SWEI7.BK000ZA6 * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Target Table:    User Written - work.FLAT_FILE_SAS     A57SWEI7.BN000NMI * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZA6);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let ETLS_SYSLAST = &SYSLAST;
/*---- Start of Pre-Process Code  ----*/ 

%let columns=CIFKEY $ 1-17
PRODUCT $ 18-20
ACCOUNT $ 21-33
CID $ 34-49
PRIMARY_FLAG $ 90-90
RELATION_CODE $ 91-93
CUST_TYPE $ 94-95
;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

%let SYSLAST = &ETLS_SYSLAST;

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.FLAT_FILE_SAS;
/* List of target columns to keep  */ 
%let _OUTPUT_keep = CIFKEY PRODUCT ACCOUNT CID PRIMARY_FLAG RELATION_CODE CUST_TYPE 
        EMPLOYEE_IND MORT_NO CAB LOAN_NO FILE_YR_MTH LOAD_DATE_TM FILE_DATE;

%let _OUTPUT1 = work.FLAT_FILE_SAS;
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = CIFKEY PRODUCT ACCOUNT CID PRIMARY_FLAG RELATION_CODE CUST_TYPE 
        EMPLOYEE_IND MORT_NO CAB LOAN_NO FILE_YR_MTH LOAD_DATE_TM FILE_DATE;

/*---- Start of User Written Code  ----*/ 


%macro load_SPL();

%get_model_period_dates(product=mor);
%put &start_period_dt; 
/*%let start_period_dt=31OCT2015;*/

		data _null_;
			mth=month("&start_period_dt."d);
			length mthchar $2;
			if mth le 9 then mthchar=compress('0'||mth);
				else mthchar=mth;
			CALL SYMPUTX('FILE_YR_MTH',substr(compress(year("&start_period_dt."d)||mthchar),3));
		run;
		%put FILE_YR_MTH=&FILE_YR_MTH;

%do i = 1 %to 8;
	data output&i. OUTPUT_PRIMARY&i.; drop rev_account rev_cid;
	   infile "&outpath./bns/incoming/CIS&i"
          lrecl = 1640
          delimiter = '	'
          dsd
          missover
          firstobs = 1 obs=MAX
	; 
		LENGTH ACCOUNT $ 23 CID $ 15; *to match target table;
		input &columns. ;

		LENGTH EMPLOYEE_IND $1 MORT_NO $7 CAB $5 LOAN_NO $7;
			 if product='MOR' then MORT_NO=substr(account,7);
			 if product in ('SPL','OLL','SAV','DDA') then CAB = substr(account,2,5);
			 if product in ('SPL','OLL','SAV','DDA') then LOAN_NO = substr(account,7);
		
			LENGTH FILE_YR_MTH $4;
				FILE_YR_MTH="&FILE_YR_MTH.";
			FORMAT LOAD_DATE_TM datetime25.6;
				LOAD_DATE_TM="&SYSDATE9.:&SYSTIME."dt;*datetime();
			FORMAT FILE_DATE DATE9.;
				FILE_DATE=intnx('month',"&start_period_dt."d,0,'b');
		
			IF RELATION_CODE = 'SOL' and PRIMARY_FLAG = 'S'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'GTR' and PRIMARY_FLAG = 'Y'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'SOL' and PRIMARY_FLAG = 'C'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'BOR' and PRIMARY_FLAG = 'C'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'LFB' and PRIMARY_FLAG = ' '  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'TSC' and PRIMARY_FLAG = 'T'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'GTR' and PRIMARY_FLAG = 'C'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'COB' and PRIMARY_FLAG = 'C'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'TRT' and PRIMARY_FLAG = 'T'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'GTR' and PRIMARY_FLAG = 'A'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'BOR' and PRIMARY_FLAG = 'B'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'COS' and PRIMARY_FLAG = 'Y'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'COS' and PRIMARY_FLAG = 'A'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'SOL' and PRIMARY_FLAG = 'A'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'X'   and PRIMARY_FLAG = 'N'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'BOR' and PRIMARY_FLAG = 'X'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = ' '   and PRIMARY_FLAG = ' '  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'TR1' and PRIMARY_FLAG = 'T'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'SOL' and PRIMARY_FLAG = ' '  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'JNT' and PRIMARY_FLAG = 'J'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'BOR' and PRIMARY_FLAG = 'A'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'JN1' and PRIMARY_FLAG = 'J'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'COS' and PRIMARY_FLAG = 'C'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'TRU' and PRIMARY_FLAG = 'T'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'GTR' and PRIMARY_FLAG = 'G'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'SOL' and PRIMARY_FLAG = 'N'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'GTR' and PRIMARY_FLAG = 'X'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'COB' and PRIMARY_FLAG = 'A'  THEN PRIMARY_FLAG = 'N';
			IF RELATION_CODE = 'BOR' and PRIMARY_FLAG = 'N'  THEN PRIMARY_FLAG = 'Y';
			IF RELATION_CODE = 'COB' and PRIMARY_FLAG = 'Y'  THEN PRIMARY_FLAG = 'N';

			IF (MISSING(ACCOUNT) AND MISSING(CID) AND MISSING(CIFKEY)) OR PRODUCT = 'APP' THEN DELETE;

			length account account2 rev_account $23. cid cid2 rev_cid $15.;
			rev_account=substr(strip(reverse(account))||'00000000000000000000000',1,23);
			account2=strip(reverse(rev_account));
			drop account;
			rename account2=ACCOUNT;

			rev_cid=substr(strip(reverse(cid))||'000000000000000',1,15);
			cid2=strip(reverse(rev_cid));
			drop cid;
			rename cid2=CID;

			IF PRIMARY_FLAG = 'Y' THEN OUTPUT OUTPUT_PRIMARY&i.;
				ELSE OUTPUT WORK.OUTPUT&i.;
		run;

		PROC SORT DATA=OUTPUT_PRIMARY&i.(WHERE=(PRIMARY_FLAG='Y')) NODUPKEY;
			BY PRODUCT ACCOUNT PRIMARY_FLAG;
		RUN;
		
		PROC APPEND BASE=OUTPUT&i.  DATA=OUTPUT_PRIMARY&i. FORCE; RUN;
	
			%if &i EQ 1 %then %do;
				proc sql;
				create table &_output. like output1;
				quit;
			%end;
	
	proc append base=&_output.  data=output&i. force; run;
	
	proc datasets lib=work nolist;
		delete output_primary&i. output&i.;
	run;
%end;
%mend load_SPL;
%load_SPL;
		
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end Read Flat File **/

/*==========================================================================* 
 * Step:            Clean Up and Load into NZ             A57SWEI7.BK000ZA7 * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    User Written - work.FLAT_FILE_SAS     A57SWEI7.BN000NMI * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZA7);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.FLAT_FILE_SAS, DATA)) or 
         %sysfunc(exist(work.FLAT_FILE_SAS, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.FLAT_FILE_SAS out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let _INPUT_count = 1;
%let _INPUT = work.FLAT_FILE_SAS;

%let _INPUT1 = work.FLAT_FILE_SAS;

%let _OUTPUT_count = 0;
/*---- Start of User Written Code  ----*/ 




proc sql noprint;
	select distinct file_date format=yymmdd10. into :file_date 
	from &_INPUT1.;

	select distinct file_date format=date9. into :file_date_sas
	from &_INPUT1.;
quit;

%PUT FILE_DATE=&file_date file_date_sas=&file_date_sas;

proc sql noprint;
	connect using NZ as NZCON;
	execute(delete from &target_lib2..CIS_DATA_FINAL where FILE_DATE=%nrbquote('&file_date.')) by nzcon;
	execute(delete from &target_lib2..CIS_DATA_FINAL_RRAP where FILE_DATE=%nrbquote('&file_date.')) by nzcon;
quit;

proc append base=nz.cis_data_final (BULKLOAD=YES BL_METHOD=CLILOAD) data=&_INPUT1. force; run;
proc append base=nz.cis_data_final_rrap (BULKLOAD=YES BL_METHOD=CLILOAD) data=&_INPUT1. force; run;

/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end Clean Up and Load into NZ **/

/*==========================================================================* 
 * Step:            Audit Check                           A57SWEI7.BK000ZA8 * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 
/*
%let transformID = %quote(A57SWEI7.BK000ZA8);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 0;
/*---- Start of User Written Code  ----*/ 

/*
proc sql;
	create table myload as
	select file_date as process_date, count(*) as count format=comma11.
	from NZ.cis_data_final
	where file_date = "&file_date_sas"d
	group by 1
	order by 1 desc;
quit;

proc sql;
	create table myload2 as
	select file_date as process_date, count(*) as count format=comma11.
	from NZ.cis_data_final_rrap
	where file_date = "&file_date_sas"d
	group by 1
	order by 1 desc;
quit;

data myload;
	set myload;
	process_date=intnx('Month',process_date,0,'e');
run;
data myload2;
	set myload2;
	process_date=intnx('Month',process_date,0,'e');
run;


proc sql;
	create table dms_load as
	select datepart(process_date) as PROCESS_DATE format=date9., row_count format=comma11. as COUNT_DMS, balances format=comma20.2 as BALANCE_DMS
	from sql_dms.DMS_LOAD_COUNTS
	where intnx('Month',datepart(process_date),0,'e') = intnx('Month',"&file_date_sas"d,0,'e') and table_name='CIS';
quit;

data dms_load;
	set dms_load;
	process_date=intnx('Month',process_date,0,'e');
run;

/*Rig the load :)*/
/*DATA DMS_LOAD; 	SET DMS_LOAD; balance_dms=30085518534; RUN;*/



/*

proc sql noprint;
select max(audit_key) +1 as audit_key into :audit_key
from NZWRK.AUDIT_TABLE;
quit;

%let audit_status=PASS;
data compare;
	merge myload dms_load;
	by process_date;
	FORMAT COUNT_DIFF  PERCENT12.5;
	COUNT_DIFF=ABS(COUNT-COUNT_DMS)/COUNT_DMS;
	
		call symputx('COUNT_DIFF',COUNT_DIFF);
		call symputx('SRC_ROW_CNT',COUNT_DMS);
		call symputx('TARGET_ROW_CNT',COUNT);


	IF COUNT_DIFF GT 0 THEN DO;
		PUT ;
		PUT "  The count difference is greater than the threshold of &threshold.%.";
		PUT ;
		PUT "  		Rows Loaded: " COUNT ", Rows Expected: " COUNT_DMS;
		PUT ;
		PUT "  Please investigate prior to restarting this job. The process will now abort.";
		PUT ;
		CALL SYMPUTX('AUDIT_STATUS','FAIL');
	END;
	
run;

%macro audit();
proc sql;
insert into NZWRK.AUDIT_TABLE 
set
		AUDIT_KEY = &audit_key.
		,SRC_SYSTEM_NM = 'DMS'
		,SRC_OBJ_NM = 'CIS1-8'
		,CRNT_CUTOFF_TMSTMP="&file_date_sas.:00:00:00"dt
		,TARGET_OBJ_NM = 'CREDIT_RISK.CIS_DATA_FINAL'
		,EDW_LAYER = 'DM'
		,AUDIT_STAT_CD = "&audit_status."
		,ETL_PROCESS_NM = "&etls_jobName."
		,SRC_ROW_CNT = &SRC_ROW_CNT.
		,TARGET_ROW_CNT = &TARGET_ROW_CNT.
/*		,SUM1_DESC = 'PRINCIPAL_BAL'*/
/*		,SRC_SUM1 = &SRC_SUM1.*/
/*		,TARGET_SUM1 = &TARGET_SUM1.*/
/*		,SUM2_DESC*/
/*		,SRC_SUM2*/
/*		,TARGET_SUM2*/
/*		,SUM3_DESC*/
/*		,SRC_SUM3*/
/*		,TARGET_SUM3*/
/*		,SUM4_DESC*/
/*		,SRC_SUM4*/
/*		,TARGET_SUM4*/
/*		,SUM5_DESC*/
/*		,SRC_SUM5*/
/*		,TARGET_SUM5*/  /*
		,INSRT_PROCESS_TMSTMP = "&SYSDATE9.:&SYSTIME."dt
		,UPDT_PROCESS_TMSTMP = "&SYSDATE9.:&SYSTIME."dt
;quit;

%if &AUDIT_STATUS EQ FAIL %then %do;
	%PUT "The Audit Check has failed for this job. Please investigate this log and the entry created in the audit table.";
	%PUT "This job will now abort.";
	%abort;
%end;

%mend audit;
%audit;  */



/*
proc sql noprint;
select max(audit_key) +1 as audit_key into :audit_key
from NZWRK.AUDIT_TABLE;
quit;

%let audit_status=PASS;
data compare;
	merge myload2 dms_load;
	by process_date;
	FORMAT COUNT_DIFF  PERCENT12.5;
	COUNT_DIFF=ABS(COUNT-COUNT_DMS)/COUNT_DMS;

		call symputx('COUNT_DIFF',COUNT_DIFF);
		call symputx('SRC_ROW_CNT',COUNT);
		call symputx('TARGET_ROW_CNT',COUNT_DMS);

	IF COUNT_DIFF GT 0 THEN DO;
		PUT ;
		PUT "  The count difference is greater than the threshold of &threshold.%.";
		PUT ;
		PUT "  		Rows Loaded: " COUNT ", Rows Expected: " COUNT_DMS;
		PUT ;
		PUT "  Please investigate prior to restarting this job. The process will now abort.";
		PUT ;
		CALL SYMPUTX('AUDIT_STATUS','FAIL');
	END;

run;

%macro audit();
proc sql;
insert into NZWRK.AUDIT_TABLE 
set
		AUDIT_KEY = &audit_key.
		,SRC_SYSTEM_NM = 'DMS'
		,SRC_OBJ_NM = 'CIS1-8'
		,CRNT_CUTOFF_TMSTMP="&file_date_sas.:00:00:00"dt
		,TARGET_OBJ_NM = 'CREDIT_RISK.CIS_DATA_FINAL_RRAP'
		,EDW_LAYER = 'DM'
		,AUDIT_STAT_CD = "&audit_status."
		,ETL_PROCESS_NM = "&etls_jobName."
		,SRC_ROW_CNT = &SRC_ROW_CNT.
		,TARGET_ROW_CNT = &TARGET_ROW_CNT. */
/*		,SUM1_DESC = 'PRINCIPAL_BAL'*/
/*		,SRC_SUM1 = &SRC_SUM1.*/
/*		,TARGET_SUM1 = &TARGET_SUM1.*/
/*		,SUM2_DESC*/
/*		,SRC_SUM2*/
/*		,TARGET_SUM2*/
/*		,SUM3_DESC*/
/*		,SRC_SUM3*/
/*		,TARGET_SUM3*/
/*		,SUM4_DESC*/
/*		,SRC_SUM4*/
/*		,TARGET_SUM4*/
/*		,SUM5_DESC*/
/*		,SRC_SUM5*/
/*		,TARGET_SUM5*/  /*
		,INSRT_PROCESS_TMSTMP = "&SYSDATE9.:&SYSTIME."dt
		,UPDT_PROCESS_TMSTMP = "&SYSDATE9.:&SYSTIME."dt
;quit;

%if &AUDIT_STATUS EQ FAIL %then %do;
	%PUT "The Audit Check has failed for this job. Please investigate this log and the entry created in the audit table.";
	%PUT "This job will now abort.";
	%abort;
%end;

%mend audit; 
%audit;    */
/*---- End of User Written Code  ----*/  

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end Audit Check **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

