/**************************************************************************** 
 * Job:             J_RRAP_ECAP_04_RRAP_BASEL_ECONMC_CAP  A57ZQ4A4.BF0011JY * 
 *                  TL_FILES                                                * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503.bns                                            * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/06 - DLGD/CCAR_ECAP                      * 
 *                                                                          * 
 * Server:          SASApp                                A57ZQ4A4.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, July 20, 2017 4:27:22 PM EDT                  * 
 * Generated by:    s2809211                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57ZQ4A4.BF0011JY);
%let etls_jobName = %nrquote(J_RRAP_ECAP_04_RRAP_BASEL_ECONMC_CAPTL_FILES);
%let etls_userID = %nrquote(s2809211);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(cs2iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            CCAR_ECAP_AUTOEXEC                    A57ZQ4A4.BO0016DX * 
 * Transform:       CCAR_ECAP_AUTOEXEC                                      * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57ZQ4A4.BO0016DX);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%include '/sasdata/sasdi/sasdev/macro/rrap/rrap_autoexec.sas';
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end CCAR_ECAP_AUTOEXEC **/

/*---- Start of User Written Code  ----*/ 

/**************************************************************************** 
 * Job:             RRAP_STG_INS_BASEL_ECONMC_CAPTL_FILES.sas               * 
 *                                                                          * 
 * Description:     This is a file extract                                  * 
 *                                                                          * 
 * Metadata Server: cs2iw503.bns                                            * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Staging/Jobs                             * 
 *                                                                          * 
 * Server:          SASApp                                A57ZQ4A4.AT000002 * 
 *                                                                          * 
 * Source Table:    BASEL_ECONMC_CAPTL_EXTR -             A57ZQ4A4.BI00000R * 
 *                   &DBNAME.BASEL_ECONMC_CAPTL_EXTR                         * 
 *                                                                          * 
 * Generated on:    Wednesday, September 17, 2014 9:36:19 AM EDT            * 
 * Generated by:    khmood                                                  * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

/*DECLARE THE PATH TO DEFINE AUTOCALL MACRO*/
/*OPTIONS MAUTOSOURCE SASAUTOS='/sasdata/sasdev/macro/rrap';*/

/*INITIALIZATION OF VARIABLES AND EXECUTE AUTOCALL MACRO*/
/*%srrap_autoexec('BASELDB2');*/

OPTIONS COMPRESS=Y;
%GLOBAL SRCCOUNT00;
%GLOBAL CHAR_PROCESSING_DATE;
%GLOBAL MONTHENDDATE;
%GLOBAL PROCESSING_DATE;
%GLOBAL CURRENT_DATE;
%GLOBAL RECORD_COUNT;
%GLOBAL YEARMONTH;
%GLOBAL TOTAL_OUTSTANDING_BALANCE;
%LET INPUT00=EDRRAPT.BASEL_ECONMC_CAPTL_EXTR;
/*PATH WHERE THE FILES WILL GET GENERATED*/

/*Fetch the Year and Month from TM_DIM*/
%macro rrap_db2yearmonth_initialize;
proc sql noprint;
	create table _temp_yearmonth as 
	select clndr_yr, tm_yr_seq_num, '00' as charmonth, '000000' as yearmonth from EDRTLRT.TM_DIM where TM_ID = &MTH_TM_ID;
quit;

/*Convert the integer values to char values as needed*/
data _temp_yearmonth;
set _temp_yearmonth;
if tm_yr_seq_num < 10 then do;
	charmonth='0'||put(tm_yr_seq_num,1.);
end;
else do;
charmonth=tm_yr_seq_num;
end;

yearmonth=clndr_yr||charmonth;
	format yearmonth $char6.;
run;

/*Save the string YYYYMM for the latest MTH_TM_ID fetched from TM_DIM into a variable*/
proc sql noprint;
select yearmonth into :yearmonth from _temp_yearmonth;
quit;
%mend rrap_db2yearmonth_initialize;


/*This transformation generates the input and output table counts*/
%MACRO datalog;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :SRCCOUNT00 FROM &INPUT00. WHERE MTH_END_DT=(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID);
QUIT;
%MEND;


/*Macro for fetching the yearmonth in an integer format*/
%rrap_db2yearmonth_initialize;

%PUT YEARMONTH IS &YEARMONTH;

PROC SQL NOPRINT;
SELECT TM_LVL_END_DT INTO :PROCESSING_DATE FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID;
QUIT;

/*CREATE A DATASET WITH YYYYMMDD FORMAT FOR THE PROCESSING DATE*/
DATA _CHARDATE_;
TODAYDATE="&PROCESSING_DATE"d;
FORMAT TODAYDATE YYMMDD10.;
TODAYYEAR=PUT(YEAR(TODAYDATE),4.); 
FORMAT TODAYYEAR $4.;
IF MONTH(TODAYDATE)<10 THEN DO;
	TODAYMONTH='0'||PUT(MONTH(TODAYDATE),1.);
	FORMAT TODAYMONTH $2.;
END;
ELSE DO;
	TODAYMONTH=PUT(MONTH(TODAYDATE),2.);
	FORMAT TODAYMONTH $2.;
END;
IF DAY(TODAYDATE)<10 THEN DO;
	TODAYDAY='0'||PUT(DAY(TODAYDATE),1.);
	FORMAT TODAYDAY $2.;
END;
ELSE DO;
	TODAYDAY=PUT(DAY(TODAYDATE),2.);
	FORMAT TODAYDAY $2.;
END;
CHAR_PROCESSING_DATE=TODAYYEAR||TODAYMONTH||TODAYDAY;
RUN;

/*STORE THE ABOVE CREATED PROCESSING DATE INTO A MACRO VARIABLE*/

PROC SQL NOPRINT;
SELECT CHAR_PROCESSING_DATE INTO :CHAR_PROCESSING_DATE FROM _CHARDATE_;
QUIT;

/*CREATE A DATASET WITH YYYYMMDD FORMAT FOR CURRENT DATE OR SYSTEM DATE*/

DATA _CURRENTDATE_;
TODAYDATE=DATE();
FORMAT TODAYDATE YYMMDD10.;
TODAYYEAR=PUT(YEAR(TODAYDATE),4.); 
FORMAT TODAYYEAR $4.;
IF MONTH(TODAYDATE)<10 THEN DO;
	TODAYMONTH='0'||PUT(MONTH(TODAYDATE),1.);
	FORMAT TODAYMONTH $2.;
END;
ELSE DO;
	TODAYMONTH=PUT(MONTH(TODAYDATE),2.);
	FORMAT TODAYMONTH $2.;
END;
IF DAY(TODAYDATE)<10 THEN DO;
	TODAYDAY='0'||PUT(DAY(TODAYDATE),1.);
	FORMAT TODAYDAY $2.;
END;
ELSE DO;
	TODAYDAY=PUT(DAY(TODAYDATE),2.);
	FORMAT TODAYDAY $2.;
END;
CURRENTDATE=TODAYYEAR||TODAYMONTH||TODAYDAY;
RUN;

/*STORE THE ABOVE CREATED SYSTEM DATE INTO A MACRO VARIABLE*/

PROC SQL NOPRINT;
SELECT CURRENTDATE INTO :CURRENTDATE FROM _CURRENTDATE_;
QUIT;

/*ALTERNATIVE LOGIC - IGNORE THE COMMENTED LINES*/
/*CALCULATE RECORD COUNT FROM THE SOURCE TABLE*/
/*%LET DSID=%SYSFUNC(OPEN(EDRRAPT.BASEL_ECONMC_CAPTL_EXTR));*/
/*%LET RECORD_COUNT=%SYSFUNC(ATTRN(&DSID,NLOBS));*/
/*%LET RC=%SYSFUNC(CLOSE(&DSID));*/


/*CALCULATE TOTAL OUTSTANDING BALANCE AMOUNT AND RECORD COUNT FROM SOURCE */
PROC SQL NOPRINT;
SELECT ROUND(SUM(UNADJUSTED_OS_BAL_AMT),0.01) FORMAT 17.2, COUNT(*) INTO :TOTAL_OUTSTANDING_BALANCE, :RECORD_COUNT FROM EDRRAPT.BASEL_ECONMC_CAPTL_EXTR
WHERE MTH_END_DT="&PROCESSING_DATE"d;
QUIT;

/*CREATE THE FINAL DATASET BEFORE EXPORTING*/

DATA _REPORTDATA_;
CURRENTDATE=&CURRENTDATE;
CHAR_PROCESSING_DATE=&CHAR_PROCESSING_DATE;
/***Hotfix to make TOTAL_OUTSTANDING_BALANCE has 2 decimal places ***/
TOTAL_OUTSTANDING_BAL=&TOTAL_OUTSTANDING_BALANCE;
TOTAL_OUTSTANDING_BALANCE = put(TOTAL_OUTSTANDING_BAL, 17.2);
*FORMAT TOTAL_OUTSTANDING_BALANCE 17.2;
RECORD_COUNT=&RECORD_COUNT;
drop TOTAL_OUTSTANDING_BAL;
RUN;

/*DEFINING THE TARGET PATH AND THE FILE NAME*/
%put CHAR_PROCESSING_DATE=&CHAR_PROCESSING_DATE;
%global OUTPATH;
%LET OUTPATH=&OUTPATH;

%LET TARGETFILENAME="&OUTPATH/mv/outgoing/mv_edwout_ecap_dr_exposures_f_mthly_&CHAR_PROCESSING_DATE..bcr";
/*%LET TARGETFILENAME="/u/s7457680/mv_edwout_ecap_dr_exposures_f_mthly_&CHAR_PROCESSING_DATE..bcr";*/
%put &targetfilename;
/*EXPORTING THE DATA INTO A CSV FILE*/

PROC EXPORT DATA=_REPORTDATA_ OUTFILE= &TARGETFILENAME DBMS=CSV REPLACE;
PUTNAMES=NO;
RUN;

/*GENERATION OF DEL FILE*/

DATA _DEL_REPORTDATA_ (KEEP=Product_ID
POOL
PD_Segment
PD_Reporting_Without_Factors
PD_Reporting_with_LR_factor
PD_Reporting_With_Factors
LGD_Segment
LGD_Reporting_Without_Factors
LGD_Reporting_with_LR_factor
LGD_Reporting_With_Factors
EADF_Segment
EADF_Reporting_Without_Factors
EADF_Reporting_with_LR_factor
EADF_Reporting_With_Factors
Obs_Prin_Bal
Authorized_Amount
Obs_Credit_Lim
Delinq_Stage
Tnif_Region_Code
Number_Of_Records
EGL_Department
Tnif_Transit
DLGD_F
);
RENAME PRD_ID=Product_ID
	ASST_CL_NUM=POOL
	PD_BASEL_SEG_NUM=PD_Segment
	PD_WITHOUT_RPTG_RTO=PD_Reporting_Without_Factors
	PD_LR_RPTG_RTO=PD_Reporting_with_LR_factor
	PD_FINAL_RPTG_RTO=PD_Reporting_With_Factors
	LGD_BASEL_SEG_NUM=LGD_Segment
	LGD_WITHOUT_RPTG_RTO=LGD_Reporting_Without_Factors
	LGD_LR_RPTG_RTO=LGD_Reporting_with_LR_factor
	LGD_FINAL_RPTG_RTO=LGD_Reporting_With_Factors
	EAD_BASEL_SEG_NUM=EADF_Segment
	EAD_WITHOUT_RPTG_RTO=EADF_Reporting_Without_Factors
	EAD_LR_RPTG_RTO=EADF_Reporting_with_LR_factor
	EAD_FINAL_RPTG_RTO=EADF_Reporting_With_Factors
	UNADJUSTED_OS_BAL_AMT=Obs_Prin_Bal
	AUTH_AMT=Authorized_Amount
	CR_LMT_AMT=Obs_Credit_Lim
	DLQNT_STG_BAND=Delinq_Stage
	RGNL_OFFC_CD=Tnif_Region_Code
	ACCT_CNT=Number_Of_Records
	EGL_DEPRTMNT_NM=EGL_Department
	TNIF_TRNST_NUM=Tnif_Transit;
SET EDRRAPT.BASEL_ECONMC_CAPTL_EXTR;
WHERE MTH_END_DT="&PROCESSING_DATE"d;

/** Sai Addition on 16 October 2014 **/
IF LGD_BASEL_SEG_NUM=-1 THEN LGD_BASEL_SEG_NUM=.;
IF PD_BASEL_SEG_NUM=-1 THEN PD_BASEL_SEG_NUM=.;
IF EAD_BASEL_SEG_NUM=-1 THEN EAD_BASEL_SEG_NUM=.;


FORMAT PD_WITHOUT_RPTG_RTO 8.6;
FORMAT PD_LR_RPTG_RTO 8.6;
FORMAT PD_FINAL_RPTG_RTO 8.6;
FORMAT LGD_WITHOUT_RPTG_RTO 8.6;
FORMAT LGD_LR_RPTG_RTO 8.6;
FORMAT LGD_FINAL_RPTG_RTO 8.6;
FORMAT EAD_WITHOUT_RPTG_RTO 8.6;
FORMAT EAD_LR_RPTG_RTO 8.6;
FORMAT EAD_FINAL_RPTG_RTO 8.6;
/*LABEL */
/*	PRD_ID='Product_ID'*/
/*	ASST_CL_NUM='POOL'*/
/*	PD_BASEL_SEG_NUM='PD_Segment'*/
/*	PD_WITHOUT_RPTG_RTO='PD_Reporting_Without_Factors'*/
/*	PD_LR_RPTG_RTO='PD_Reporting_with_LR_factor'*/
/*	PD_FINAL_RPTG_RTO='PD_Reporting_With_Factors'*/
/*	LGD_BASEL_SEG_NUM='LGD_Segment'*/
/*	LGD_WITHOUT_RPTG_RTO='LGD_Reporting_Without_Factors'*/
/*	LGD_LR_RPTG_RTO='LGD_Reporting_with_LR_factor'*/
/*	LGD_FINAL_RPTG_RTO='LGD_Reporting_With_Factors'*/
/*	EAD_BASEL_SEG_NUM='EADF_Segment'*/
/*	EAD_WITHOUT_RPTG_RTO='EADF_Reporting_Without_Factors'*/
/*	EAD_LR_RPTG_RTO='EADF_Reporting_with_LR_factor'*/
/*	EAD_FINAL_RPTG_RTO='EADF_Reporting_With_Factors'*/
/*	UNADJUSTED_OS_BAL_AMT='Obs_Prin_Bal'*/
/*	AUTH_AMT='Authorized_Amount'*/
/*	CR_LMT_AMT='Obs_Credit_Lim'*/
/*	DLQNT_STG_BAND='Delinq_Stage'*/
/*	RGNL_OFFC_CD='Tnif_Region_Code'*/
/*	ACCT_CNT='Number_Of_Records'*/
/*	EGL_DEPRTMNT_NM='EGL_Department'*/
/*	TNIF_TRNST_NUM='Tnif_Transit';*/
RUN;

%LET DEL_TARGETFILENAME="&OUTPATH/mv/outgoing/mv_edwout_ecap_dr_exposures_f_mthly_&CHAR_PROCESSING_DATE..del";

PROC EXPORT DATA=_DEL_REPORTDATA_ OUTFILE= &DEL_TARGETFILENAME DBMS=CSV REPLACE;
/*PUTNAMES=NO;*/
RUN;
 
X chmod 777 "&OUTPATH/mv/outgoing/mv_edwout_ecap_dr_exposures_f_mthly_&CHAR_PROCESSING_DATE..del";
X chmod 777 "&OUTPATH/mv/outgoing/mv_edwout_ecap_dr_exposures_f_mthly_&CHAR_PROCESSING_DATE..bcr";

%datalog;
%PUT 
PROCESSING MONTH IS &MTH_TM_ID 
MONTH END DATE IS "&PROCESSING_DATE"d 
&INPUT00. COUNT IS &SRCCOUNT00 ;

/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

