/**************************************************************************** 
 * Job:             J_RRAP_TL10_2203_SPL_MODEL_025_REALI  A57SWEI7.BH0009II * 
 *                  ZED_LGDD                                                * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/02 - Term Loans/2.2                 * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:38:48 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009II);
%let etls_jobName = %nrquote(J_RRAP_TL10_2203_SPL_MODEL_025_REALIZED_LGDD);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_spl_autoexec                  A57SWEI7.BK000YW4 * 
 * Transform:       AM_rrap_spl_autoexec                                    * 
 * Description:     Autoexec file for termloan jobs. This points to auto    * 
 *                   call macros                                            * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000YW4);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_spl_autoexec;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_spl_autoexec **/

/*---- Start of User Written Code  ----*/ 

/*options sastrace=',,,d' sastraceloc=saslog;*/
options mprint;* mlogic symbolgen;


/*---------------------------------------------------------------------
 * NAME:       03_spl_lgd_d_realized.sas
 *
 * PURPOSE:    Calculates LGD with and without costs for the 
 *             defaulters model.
 *             
 * NOTES:      
 *             
 * MODIFIED:
 *    13APR2015 - WP - Created
 *    23APR2015 - WP - Updated code to use parameter control table to 
 *                     assign the discount rates.
 *                   - Also changed where clause conditions on delete 
 *                     from statements on the final output tables.
 *    31MAY2015 - WP - Changes to pull recovery window end date through.
 *    03JUN2015 - JL - Incorporate changes to update def_ind table with 
 *                     recovery window date.
 *
 * Copyright (c) 2015 by The Financial Risk Group, Cary, NC, USA.
 *---------------------------------------------------------------------*/


/**************** Start of Start and End Dates ****************/
/*--------------------------------------------------------
 * Assigning start and end dates to run in the code. Note:
 * this is the beginning and ending dates for history. 
 * For a one month run the dates will be the same.
 * Also setting the length of the performance window, which
 * will be a 24 month lookback for this process.
 *--------------------------------------------------------*/


%let MODULE=TL;
%let BATCH=2.2;
%let length_performance_window = 24;

/*--------------------------------------------------------
 * Assigning start and end dates to run in the code. Note:
 * this is the beginning and ending dates for history. 
 * For a one month run the dates will be the same.
 *--------------------------------------------------------*/
%get_model_period_dates(product=spl);

/*   %let start_period_dt = 30NOV2014; */
/*   %let end_period_dt = 31AUG2015;   */
%put Start and End Dates for SPL Models:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;

/**************** End of Start and End Dates ****************/ 


/*--------------------------------------------------------
 * Assigning Netezza database schemas. 
 *--------------------------------------------------------*/

%let nz_input_db=&FRG_DB;
%let nz_input_status_tbl_db=&FRG_DB;
%let nz_intmed_db=&FRG_DB;
%let nz_results_db=&RRAP_DB;
%let nz_rrap_db=&RRAP_DB;




/* SAS libnames */
%let sas_nz_source_lib=nzuser;
%let sas_nz_intmed_lib=nzuser;
%let sas_nz_results_lib=nzrrap;  
%let sas_rrap_lib=nzrrap;


  




/*--------------------------------------------------------
 * Assigning macro variables for input and output tables.
 * There is a seperate output table to store incremental 
 * monthly data that will be inserted into the final table.
 *--------------------------------------------------------*/
 
%let input_table = MODEL_REALIZED_INPUTS_SPL;
%let input_status_table = PSNL_STATUS_V;
/*Added by HD*/
%let input_pd_rlzd_table=psnl_pd_obsvtn_pt_realz_val_v;
/* Lookup tables */
%let tim_dim_table = tm_dim;

/* Intermediate tables */
%let intmed_obsvt_drvd_var = spl_lgd_d_drvd_var;

%let output_table_realized=PSNL_LN_LGD_OBSVT_PT_RELZ_VAL;
%let output_table_costs=PSNL_LN_LGD_OBSVT_PT_RELZ_COST;
%let output_table_recovery=PSNL_LN_LGD_OBSVT_PT_RELZ_RCVR;
%let output_table_obsvtn_pt = psnl_loan_obsvtn_pt_drvd_var;


/*--------------------------------------------------------
 * Creating partition number macro variable to use with
 * parallel processing in DI.
 *--------------------------------------------------------*/

%let pn=1;

/*--------------------------------------------------------
 * Wrapper macro to loop through the process for each 
 * monthly incremental load.
 *--------------------------------------------------------*/

%macro lgd_d(start_period_dt =, end_period_dt =);
   options errors=100000;

   /*--------------------------------------------------------
    * Macro to get LGD discount parameters from the SPL 
    * parameters control table.
    *--------------------------------------------------------*/

   %macro get_rrap_parameters(name=);
      %global &name._value;

      data _null_;
         set control.parameters;
         where name="&name";
         call symput("&name._value", value);
      run;
   %mend get_rrap_parameters;

   %get_rrap_parameters(name=spl_lgd_d_disc_rate)
   
   /*-------------------------------------------------------
    * Defines the number of months for which the process
    * will be run.  This will determine how many times
    * the code will be looped.
    *-------------------------------------------------------*/

   data _null_;
      call symput('number_periods', cats(intck('month', "&start_period_dt"d, "&end_period_dt"d)));
   run;
   

   /*----------------------------------------------------
    * Loop over all months for the process run
    *----------------------------------------------------*/

   %do ii = 0 %to &number_periods;


      /*----------------------------------------------------
       * Setting date macros variables for NZ date
       * literal format based off of start_period_dt and 
       * end_period_dt formats. NZ requires date literals to
       * be in following format: YYYY-MM-DD
       *----------------------------------------------------*/
      data _null_;
         call symput('period_dt', cats(put(intnx('month', "&start_period_dt"d, &ii, 'e'), date9.)));
         call symput('period_dt_nz', cats(put(intnx('month', "&start_period_dt"d, &ii, 'e'), yymmdd10.)));
      run;

		proc sql noprint;
			select tm_id into :mth_tm_id 
			from nzrrap.tm_dim
			where tm_lvl='Month' and tm_lvl_end_dt="&period_dt"d;
		quit;
		
		%etl_job_start(target_table=&sas_nz_results_lib..&output_table_realized,PROCESS_MTH_TM_ID=PROCESS_MTH_TM_ID,condition=%nrquote(upcase(lgd_type)='LGD-D'));
		
      data _null_;

         /* Dates for querying from NZ */
         call symput ('obs_date_nz', cats(put(intnx('month', "&period_dt"d, -&length_performance_window, 'e'), yymmdd10.)));  
         call symput ('start_perf_nz', cats(put(intnx('month', "&period_dt"d, -&length_performance_window + 1, 'e'), yymmdd10.)));
         call symput ('end_perf_nz', cats(put(intnx('month', "&period_dt"d, 0, 'e'), yymmdd10.)));
   
         /* Dates for processing in SAS */
         call symput ('obs_date_sas', cats(put(intnx('month', "&period_dt"d, -&length_performance_window, 'e'), date9.)));  
         call symput ('start_perf_sas', cats(put(intnx('month', "&period_dt"d, -&length_performance_window + 1, 'e'), date9.)));
         call symput ('end_perf_sas', cats(put(intnx('month', "&period_dt"d, 0, 'e'), date9.)));
      run;

      %put NOTE: USER DEFINED: SPL Realized LGD-D process for Observation Period: &obs_date_nz;
      %put NOTE: USER DEFINED: SPL Realized LGD-D Performance Window: &start_perf_nz to &end_perf_nz;
      %put;

      /*-------------------------------------------------
       * Finding the accounts that were on the books 36
       * months to the process date.  Only these accounts 
       * should be considered for the LGD-ND process.
       *-------------------------------------------------*/
 
      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_distinct_accts)
   
      proc sql;
         connect using &sas_nz_intmed_lib as nzcon;
         execute(

            create table %nrbquote(&nz_intmed_db).spl_lgd_d_distinct_accts as (
            select distinct a.loan_no,
                            a.cab
            from %nrbquote(&nz_input_db..&input_table) as a
                 inner join
                 %nrbquote(&nz_input_status_tbl_db..&input_status_table) as b
                 on a.loan_no=b.loan_no and
                    a.cab=b.cab and 
                    last_day(date_trunc('day', a.process_date))=last_day(date_trunc('day', b.process_date))
            where last_day(date_trunc('day', a.process_date))=%nrbquote('&obs_date_nz') and
                  upper(b.pit_status)='DEF' and upper(b.treatment_flag)='A' )
            	WITH DATA distribute BY HASH (loan_no);
			) by nzcon;
        * execute (generate statistics on %nrbquote(&nz_intmed_db)..spl_lgd_d_distinct_accts) by nzcon;
		 execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_intmed_db..spl_lgd_d_distinct_accts) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
         disconnect from nzcon;
      quit;


      /*-------------------------------------------------
       * Gathering the input data for the process.
       *-------------------------------------------------*/
      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_base)   

      proc sql;
         connect using &sas_nz_intmed_lib as nzcon;
         execute (
         
            create table %nrbquote(&nz_intmed_db).spl_lgd_d_base as (
            select a.basel_acct_id,
                   a.loan_no,
                   a.cab,
                   a.process_date as process_dt,
                   a.principal_bal,
                   a.addon_bal,
                   a.accr_int,
                   a.recstat_code,
                   a.chg_off_date,
                   b.pit_status,
                   b.sub_portfolio,
                   b.os_bal_amt
            from %nrbquote(&nz_input_db..&input_table) as a
                 left join 
                 %nrbquote(&nz_input_status_tbl_db..&input_status_table) as b
                 on a.loan_no=b.loan_no and 
                    a.cab=b.cab and
                    last_day(date_trunc('day', a.process_date))=last_day(date_trunc('day',  b.process_date))     

                 inner join
                 %nrbquote(&nz_intmed_db).spl_lgd_d_distinct_accts as c
                 on a.loan_no=c.loan_no and
                    a.cab=c.cab  

            where last_day(date_trunc('day', a.process_date)) >= %nrbquote('&obs_date_nz') and
                  last_day(date_trunc('day', a.process_date)) <= %nrbquote('&end_perf_nz')   

     		      ) WITH DATA distribute BY HASH (loan_no);
			) by nzcon;
       *  execute (generate statistics on %nrbquote(&nz_intmed_db)..spl_lgd_d_base) by nzcon;
		execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_intmed_db..spl_lgd_d_base) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;

         disconnect from nzcon;
      quit; 

      /*------------------------------------------------------
       * Creating arrays for capturing 24 months of data for
       * principal_bal, addon_bal, and accr_int.  Data must be 
       * sorted in SAS to ensure that data step logic will work
       * correctly.
       *------------------------------------------------------*/  
      
      %delete_table(work.spl_lgd_d_base)

      proc sort data=&sas_nz_intmed_lib..spl_lgd_d_base
                out=work.spl_lgd_d_base nodupkey;
         by loan_no
            cab
            process_dt;
      run;  

      
      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_data_prep_&pn)

      data &sas_nz_intmed_lib..spl_lgd_d_data_prep_&pn (rename=(run_dt=process_dt)
                                                    drop=process_dt
                                                         i
                                                         counter);
         set work.spl_lgd_d_base;
         by loan_no
            cab;
         length run_dt 
                observation_dt 
                performance_start_dt 
                performance_end_dt 8;
         
         array pit_status_window(25) $3;
         array process_dt_window(25);
         array prin_bal_window(25);
         array addon_bal_window(25);
         array accr_int_window(25);
         array recstat_code_window(25);
         array os_balance_window(25);
            

         retain basel_acct_id
                loan_no
                cab
                run_dt
                pit_status_window1--pit_status_window25
                process_dt_window1--process_dt_window25
                prin_bal_window1--prin_bal_window25
                addon_bal_window1--addon_bal_window25
                accr_int_window1--accr_int_window25
                recstat_code_window1--recstat_code_window25
                os_balance_window1--os_balance_window25
                counter;

       /* Process_dt is already a SAS date */
         /* process_dt=datepart(process_dt); */
         format process_dt_window1--process_dt_window25
                process_dt
                run_dt
                observation_dt
                performance_start_dt
                performance_end_dt date9.;
         if first.cab=1 or first.loan_no=1 then
         do;
            counter=0;
            do i=1 to 25;
               pit_status_window(i)='';
               process_dt_window(i)=.;
               prin_bal_window(i)=.;
               addon_bal_window(i)=.;
               accr_int_window(i)=.;
               recstat_code_window(i)=.;
               os_balance_window(i)=.;
            end;
            chg_off_date_obs_date=chg_off_date;
         end;  

         if intnx('month',process_dt,0,'e') GE "&obs_date_sas"d and intnx('month', process_dt, 0, 'e') LE "&end_perf_sas"d then
            do;
               counter+1;  

               pit_status_window(counter)=pit_status;
               process_dt_window(counter)=process_dt;
               prin_bal_window(counter)=principal_bal;
               addon_bal_window(counter)=addon_bal;
               accr_int_window(counter)=accr_int;
               recstat_code_window(counter)=recstat_code;
               os_balance_window(counter)=os_bal_amt;
               

               /*----------------------------------------------
                * If the last period of the performance window,
                * or this is the last record for the loan_no
                * and cab, then output the results.
                *----------------------------------------------*/ 

               if counter=25 or last.cab=1 or last.loan_no=1 then
               do;
                  /* Stores dates for performance window */
                  performance_start_dt = intnx('month', "&start_perf_sas"d, 0, 'e');
                  performance_end_dt = intnx('month', "&end_perf_sas"d, 0, 'e'); 

                  /* Stores observation date */
                  observation_dt = intnx('month', "&obs_date_sas"d, 0, 'e');  

                  /* Stores the date for when this was run */
                  run_dt = intnx('month', "&period_dt"d, 0, 'e'); 

                  output;
               end;
            end;
      run;  


      /*-----------------------------------------------------------
       * Subsetting the data to contain only those accounts that 
       * are current at the observation date and have default 
       * indicator set to 1.  Also identifying the cure date for 
       * the account, and the date at which the account turn 
       * recstat_code=8.
       *-----------------------------------------------------------*/
      
      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_data_subset_cure_&pn)  

      data &sas_nz_intmed_lib..spl_lgd_d_data_subset_cure_&pn;
         set &sas_nz_intmed_lib..spl_lgd_d_data_prep_&pn;
         array pit_status_window(*) pit_status_window1--pit_status_window25;
         array prin_bal_window(*) prin_bal_window1--prin_bal_window25;
         array process_dt_window(*) process_dt_window1--process_dt_window25;
         array recstat_code_window(*) recstat_code_window1--recstat_code_window25;
         array os_balance_window(*) os_balance_window1--os_balance_window25;
         format cure_date date9.;  

         /*--------------------------------------------------
          * Ensuring only those account current at the 
          * observation date and defaulted over 12 month
          * period are used in LGD calculation.
          *--------------------------------------------------*/   

         where upcase(pit_status_window1)='DEF';  

         /*-----------------------------------------
          * Identifying the point where the loan 
          * has cured.
          *-----------------------------------------*/   

         do jj=2 to 25;
            if pit_status_window(jj) in ('CUR','CLO') or prin_bal_window(jj)<=0 or os_balance_window(jj)<1 then
            do;
               cure_num=jj;
               leave;
            end;
         end;  

         /*-----------------------------------------
          * Identifying when the loan turns to
          * recstat_code=8.
          *-----------------------------------------*/   

         do ii=2 to 25;
            if recstat_code_window(ii)=8 then
            do;
               rec_stat_num=ii;
               leave;
            end;
         end;
         if cure_num ^= . then cure_date=process_dt_window(cure_num); 

         /*-----------------------------------------
          * Identifying charge off num.
          *-----------------------------------------*/   
         if chg_off_date^=. then
         do zz=1 to 25;
            if intnx('month',datepart(chg_off_date),0,'e')=intnx('month',process_dt_window(zz),0,'e') then 
            do;
               chg_off_num=zz;
               leave;
            end;
         end;
      run;  

      /*---------------------------------------------------
       * If the account is in default at the observation
       * date, we need to see if that default state began
       * at an earlier date.  If it did, we need to capture
       * the amount of accrued interest at the beginning of
       * the defaulted state so that it can be used in the 
       * derivation of the the balance used to calculate 
       * LGD.
       *---------------------------------------------------*/
      
      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_def_beg)

      proc sql;
         connect using &sas_nz_intmed_lib as nzcon;
         execute(

            create table %nrbquote(&nz_intmed_db).spl_lgd_d_def_beg as (
               select a.loan_no,
                      a.cab,
                      a.process_date,
                      a.pit_status,
                      a.os_bal_amt,
                      a.accr_int
               from %nrbquote(&nz_input_status_tbl_db..&input_status_table) as a
                    left join
                    %nrbquote(&nz_input_db..&input_table) as b
                    on a.loan_no=b.loan_no and 
                       a.cab=b.cab and
                       last_day(date_trunc('day', a.process_date))=last_day(date_trunc('day',  b.process_date))

                    inner join
                    %nrbquote(&nz_intmed_db).spl_lgd_d_distinct_accts as c
                    on a.loan_no=c.loan_no and
                       a.cab=c.cab

               where last_day(date_trunc('day', a.process_date))<=%nrbquote('&obs_date_nz')

         	    ) WITH DATA distribute BY HASH (loan_no) ;
			) by nzcon;
        * execute (generate statistics on %nrbquote(&nz_intmed_db)..spl_lgd_d_def_beg) by nzcon;
			execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_intmed_db..spl_lgd_d_def_beg) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
         disconnect from nzcon;
      quit; 

      /*----------------------------------------------
       * Sorting in SAS to ensure that order is 
       * correct
       *----------------------------------------------*/

      %delete_table(work.spl_lgd_d_def_beg)

      proc sort data=&sas_nz_intmed_lib..spl_lgd_d_def_beg 
                out=work.spl_lgd_d_def_beg;
         by loan_no
            cab
            descending process_date;
      run;

      /*-----------------------------------------------
       * Finding the start of the default state, and 
       * capturing the accrued interest.
       *-----------------------------------------------*/

      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_def_beg_int)

      data &sas_nz_intmed_lib..spl_lgd_d_def_beg_int;
         set work.spl_lgd_d_def_beg;
         by loan_no cab;
         retain flag;
         format last_new_dft_dt date9.;
         /* Code change - WP - 6/29 Begin*/
         bal_def=lag(os_bal_amt);
         int_def=lag(accr_int);
         pit=lag(pit_status);
         if first.loan_no=1 or first.cab=1 then flag=0;
         if flag=0;
         if (upcase(pit_status)='CUR' and upcase(pit)='DEF') or ((last.loan_no=1 or last.cab=1) and upcase(pit_status)='DEF') then 
         do;
            if (upcase(pit_status)='CUR' and upcase(pit)='DEF') then 
            do;
               int_chg=int_def;
               last_new_dft_bal_amt=bal_def;
            end;
            else 
            do;
               int_chg=accr_int;
               last_new_dft_bal_amt=os_bal_amt;
            end;
            flag+1;
            /*----------------------------------------------------
             * Look back in history to find when the account went 
             * into default.  This determines what number of the 
             * array the recovery process will end at.
             *----------------------------------------------------*/
            if (upcase(pit_status)='CUR' and upcase(pit)='DEF') then 
            do;
               def_num=intck('month',"&obs_date_sas"d,process_date)+1;
               last_new_dft_dt=intnx('month',process_date,1,'e');
            end;
            else
            do;
               def_num=intck('month',"&obs_date_sas"d,process_date);
               last_new_dft_dt=process_date;
            end;
            rec_end=25+def_num;
            output;
         end;
      run;

      /*----------------------------------------------------
       * Joining the int_def value to each observation
       * account.
       *----------------------------------------------------*/

      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_int_def)


      proc sql;
         connect using &sas_nz_intmed_lib as nzcon;
         execute(

            create table %nrbquote(&nz_intmed_db).spl_lgd_d_int_def as (
            select a.*,
                   b.int_chg,
                   b.rec_end,
                   b.def_num
					,
/*                   b.last_new_dft_dt ,*/
/*                   b.last_new_dft_bal_amt  , */
				   c.last_new_dft_dt,
				   c.last_new_dft_bal_amt
				                
            from %nrbquote(&nz_intmed_db).spl_lgd_d_data_subset_cure_%nrbquote(&pn) as a
                 left join 
                 %nrbquote(&nz_intmed_db).spl_lgd_d_def_beg_int as b
                 on a.loan_no=b.loan_no and
                    a.cab=b.cab

				left join 
				%nrbquote(&nz_intmed_db).&input_pd_rlzd_table. as c
                 on a.loan_no=c.loan_no and
                    a.cab=c.cab and 
					a.OBSERVATION_DT = c.OBSVTN_DATE


     	     ) WITH DATA distribute BY HASH (loan_no);
		) by nzcon;
       * execute (generate statistics on %nrbquote(&nz_intmed_db)..spl_lgd_d_int_def) by nzcon;
		 execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_intmed_db..spl_lgd_d_int_def) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
         disconnect from nzcon;
      quit; 

              

      /*---------------------------------------------
       * Calculating LGD without costs.
       *---------------------------------------------*/

      %delete_table(&sas_nz_intmed_lib..spl_lgd_d_nocost_&pn);

      data &sas_nz_intmed_lib..spl_lgd_d_nocost_&pn (drop=jj ii);
         set &sas_nz_intmed_lib..spl_lgd_d_int_def;
         array pit_status_window(*) pit_status_window1--pit_status_window25;
         array prin_bal_window(*) prin_bal_window1--prin_bal_window25;
         array addon_bal_window(*) addon_bal_window1--addon_bal_window25;
         array accr_int_window(*) accr_int_window1--accr_int_window25;
         array recstat_code_window(*) recstat_code_window1--recstat_code_window25;
         /* Change by WP Begin - 31MAY2015*/
         array process_dt_window(*) process_dt_window1--process_dt_window25;
         array rec(25);
         array drec(25);
       format rcvry_cured_dt date9.;
         /* Change by WP End - 31MAY2015*/

         /*------------------------------------
          * Calculating Balance at observation
          * date.
          *------------------------------------*/

         balance_obs=sum(prin_bal_window(1),addon_bal_window(1),int_chg);

         do jj=2 to min(rec_stat_num,25,cure_num,rec_end);
            /* Change by WP Begin - 31MAY2015*/
            rcvry_end_num=min(rec_stat_num,25,cure_num,rec_end);
            rcvry_cured_dt=intnx('month', "&obs_date_sas"d, rcvry_end_num-1, 'e');
            /* Change by WP End - 31MAY2015*/
            if jj^=cure_num then
            do;
               rec(jj)=sum(prin_bal_window(jj),addon_bal_window(jj))-sum(prin_bal_window(jj-1),addon_bal_window(jj-1));
            end;
            else
            do;
               rec(jj)=max(-balance_obs,-sum(prin_bal_window(jj-1),int_chg,addon_bal_window(jj-1)));
            end;
         end;

         tot_rec=0;

         do ii=2 to 25;
            drec(ii)=rec(ii)/(1+&spl_lgd_d_disc_rate_value.)**((ii-1)/12);
            tot_rec=sum(tot_rec,drec(ii));
         end;

         lgd_rto=(balance_obs+tot_rec)/balance_obs;
      run;

      /*----------------------------------------------
       * Loading indirect cost data into NZ to join
       * with the LGD-ND nocost data. Only keeping 
       * those records that fall into the time window
       * being considered in each loop.
       *----------------------------------------------*/
      
      %delete_table(work.spl_indirect_costs) 

      /*
      proc sql noprint;
         create table work.spl_indirect_costs as
         select a.reporting_date,
                a.indirect_unit_costs
         from conlgd.lgd_indirect_cost as a
         where intnx('month',datepart(a.reporting_date),0,'e') GE "&obs_date_sas"d and 
               intnx('month', datepart(a.reporting_date), 0, 'e') LE "&end_perf_sas"d;
      quit;
      */

      proc sql;
      create table work.spl_indirect_costs as
      select t.tm_lvl_end_dt as reporting_date, 
             a.unit_indrct_cost_amt as indirect_unit_costs
      from nzrrap.DRVD_MTH_INDRCT_COST_SUM as a,
           nzuser.tm_dim as t
      where a.mth_tm_id=t.tm_id and t.tm_lvl='Month' and
            t.tm_lvl_end_dt GE "&obs_date_sas"d and 
            t.tm_lvl_end_dt LE "&end_perf_sas"d;
      quit;
         

      /*----------------------------------------------
       * Loading direct cost data into NZ to join with
       * the LGD-ND no cost table. Only keeping 
       * those records that fall into the time window
       * being considered in each loop.
       *----------------------------------------------*/ 

      %delete_table(work.spl_direct_costs)   

      /*
      proc sql noprint;
         create table work.spl_direct_costs as
         select a.cab,
                a.loan_no,
                a.reporting_date,
                a.costs,
                a.highway
         from conlgd.lgd_direct_costs as a
         where a.cab ^= . and a.loan_no ^= . and upcase(a.highway) ^= 'RH' and
               intnx('month',datepart(a.reporting_date),0,'e') GE "&obs_date_sas"d and 
               intnx('month', datepart(a.reporting_date), 0, 'e') LE "&end_perf_sas"d;
      quit; 
      */


      proc sql noprint; 
      create table work.spl_direct_costs_tmp as
      select a.basel_acct_id,
             t.tm_lvl_end_dt as reporting_date,
             a.mth_drc_cost_amt as costs,
             a.hghwy_cd as highway
      from nzrrap.DRVD_MTH_DRC_COST as a,
           nzuser.tm_dim as t
      where a.mth_tm_id=t.tm_id and t.tm_lvl='Month' and 
            upcase(a.hghwy_cd) ^= 'RH' and
            t.tm_lvl_end_dt GE "&obs_date_sas"d and 
            t.tm_lvl_end_dt LE "&end_perf_sas"d;
      quit; 


      /* Create a lookup table for loan_no and cab */
      /* Loan no and cab are used in the realized logic */
      proc sql;
      create table work.basel_acct_x_loan_no as 
      select distinct basel_acct_id, 
             crnt_br_loctn_trnst as cab,
             loan_num as loan_no
      from nzrrap.BASEL_PSNL_LOAN_MTH_SNAPSHOT
      where RECD_STAT_CD in ('4','5','6','7','8');
      quit;

     /* Join direct costs with lookup table */
      proc sql;
      create table work.spl_direct_costs as
      select s.*, 
             b.cab,
             b.loan_no
      from work.spl_direct_costs_tmp as s 
      left join 
           work.basel_acct_x_loan_no as b
           on s.basel_acct_id=b.basel_acct_id
      where cab ^= " " and loan_no ^= " ";
      quit;



      /*----------------------------------------------
       * Transposing the direct cost data to join to
       * LGD_D no cost table. 
       *----------------------------------------------*/ 

      proc sort data=work.spl_direct_costs;
         by loan_no
            cab
            reporting_date;
      run;
      
      %delete_table(work.spl_direct_costs_transpose1)   

      data work.spl_direct_costs_transpose1 (drop=ii
                                                  num);
         set work.spl_direct_costs;
         by loan_no
            cab;
         array direct_costs(25);
         observation_dt="&obs_date_sas"d;
         retain observation_dt
                loan_no
                cab
                direct_costs1--direct_costs25;
         if first.loan_no or first.cab then 
         do ii=1 to 25;
            direct_costs(ii)=.;
         end;
       /* Array subscript out of range - ii=26 
         num=intck('month',"&obs_date_sas"d,datepart(reporting_date))+1; */
       num=intck('month',"&obs_date_sas"d,reporting_date)+1;
         if direct_costs(num)^=. then direct_costs(num)=direct_costs(num)+costs;
         else direct_costs(num)=costs;
         if last.loan_no or last.cab then output;
      run;  

      /*----------------------------------------
       * Joining to get default date number to 
       * discount direct costs.
       *----------------------------------------*/ 

      %delete_table(work.spl_direct_costs_transpose)
       
      proc sql;
         create table work.spl_direct_costs_transpose (drop=loan
                                                            cab_no
                                                            obs_dt) as
         select a.loan_no,
                a.cab,
                a.observation_dt,
                a.cure_num,
                a.sub_portfolio,
                a.lgd_rto,
                a.rec_end,
                a.def_num,
                a.cure_date,
                a.tot_rec,
                a.chg_off_date,
                a.chg_off_num,
                a.last_new_dft_dt,
                a.last_new_dft_bal_amt,
            a.rcvry_cured_dt,
                case
                   when a.cure_date=. then a.rec_end
                   else min(a.rec_end,a.cure_num)
                end as end_date,
                b.*
         from &sas_nz_intmed_lib..spl_lgd_d_nocost_&pn as a
              left join
              work.spl_direct_costs_transpose1 (rename=(loan_no=loan
                                                        cab=cab_no
                                                        observation_dt=obs_dt)) as b
              on a.loan_no=b.loan and 
                 a.cab=b.cab_no and
                 intnx('month',a.observation_dt,0,'e')=intnx('month',b.obs_dt,0,'e');
      quit; 

      /*---------------------------------------------
       * Discounting Direct Costs and creating total.
       *---------------------------------------------*/  

      %delete_table(work.spl_direct_costs_discount)   

      data work.spl_direct_costs_discount (drop=jj);
         set work.spl_direct_costs_transpose;
         array direct_costs(*) direct_costs1--direct_costs25;
         array discount_direct_costs(25);
         tot_direct_costs=0;
         if end_date=. then end_date=99;
         do jj=1 to min(25,end_date);
            discount_direct_costs(jj)=direct_costs(jj)/(1+&spl_lgd_d_disc_rate_value.)**((jj-1)/12);
            tot_direct_costs=sum(tot_direct_costs,discount_direct_costs(jj));
         end;
         if tot_direct_costs=0 then tot_direct_costs=.;
      run;  

      /*--------------------------------------------
       * Transposing Indirect Costs.
       *--------------------------------------------*/   

      %delete_table(work.spl_indirect_costs_transpose1)  

      data work.spl_indirect_costs_transpose1 (drop=reporting_date);
         set work.spl_indirect_costs end=last;
         array indirect_costs(25);
         retain indirect_costs1--indirect_costs25;
         obs_dt="&obs_date_sas"d;
       /* Array subscript out of range - ii=26 
         num=intck('month',"&obs_date_sas"d,datepart(reporting_date))+1; */
       num=intck('month',"&obs_date_sas"d,reporting_date)+1;
         indirect_costs(num)=indirect_unit_costs;
         if last then output;
      run;  

      /*--------------------------------------------
       * Joining indirect cost data to each account.
       *--------------------------------------------*/   

      %delete_table(work.spl_indirect_costs_transpose)   

      proc sql;
         create table work.spl_indirect_costs_transpose as
         select a.basel_acct_id,
                a.loan_no,
                a.cab,
                a.observation_dt,
                a.cure_num,
                a.def_num,
                a.sub_portfolio,
                a.cure_date,
                a.rec_end,
                a.lgd_rto,
                a.chg_off_date,
                a.chg_off_num,
                a.balance_obs,
                a.tot_rec,
                a.last_new_dft_dt,
                a.last_new_dft_bal_amt,
                a.rcvry_cured_dt,
                a.pit_status_window1,
					 a.pit_status_window2,
					 a.pit_status_window3,
					 a.pit_status_window4,
   				 a.pit_status_window5,
					 a.pit_status_window6,
					 a.pit_status_window7,
					 a.pit_status_window8,
					 a.pit_status_window9,
					 a.pit_status_window10,
					 a.pit_status_window11,
					 a.pit_status_window12,
					 a.pit_status_window13,
					 a.pit_status_window14,
					 a.pit_status_window15,
					 a.pit_status_window16,
					 a.pit_status_window17,
					 a.pit_status_window18,
					 a.pit_status_window19,
					 a.pit_status_window20,
					 a.pit_status_window21,
					 a.pit_status_window22,
					 a.pit_status_window23,
					 a.pit_status_window24,
					 a.pit_status_window25,
                b.*,
                /*Identifying end period for indirect calculations.*/
                case
                   when a.cure_date=. and a.chg_off_date ^=. then min(a.chg_off_num,a.rec_end,25)
                   when a.cure_date=. and a.chg_off_date =. then min(a.rec_end,25)
                   else min(a.chg_off_num,a.rec_end,a.cure_num,25)
                end as end_num
         /*Intentional cartesian join.  Indirect costs data only has 1 record.*/
         from &sas_nz_intmed_lib..spl_lgd_d_nocost_&pn as a,
              work.spl_indirect_costs_transpose1 as b;
      quit; 


      /*---------------------------------------------------
       * Discounting and totaling indirect costs.
       *---------------------------------------------------*/  

      %delete_table(work.spl_indirect_costs_discount) 

      data work.spl_indirect_costs_discount;
         set work.spl_indirect_costs_transpose;
         array indirect_costs(*) indirect_costs1--indirect_costs25;
         array pit_status_window(*) pit_status_window1--pit_status_window25;
         array discount_ind_costs(25);
         if def_num=0 then indirect_costs1=.;
         tot_indirect_costs=0;
         if def_num=0 then
         do;
         	do ii=2 to end_num-1;
            	if upcase(pit_status_window(ii))='DEF' then
            	do;
               	discount_ind_costs(ii)=indirect_costs(ii)/(1+&spl_lgd_d_disc_rate_value.)**((ii-1)/12);
               	tot_indirect_costs=sum(tot_indirect_costs,discount_ind_costs(ii));
            	end;
        	   end;
		   end;
         if def_num<0 then
         do;
				do ii=1 to end_num-1;
            	if upcase(pit_status_window(ii))='DEF' then
            	do;
               	discount_ind_costs(ii)=indirect_costs(ii)/(1+&spl_lgd_d_disc_rate_value.)**((ii-1)/12);
               	tot_indirect_costs=sum(tot_indirect_costs,discount_ind_costs(ii));
            	end;
        	   end;
		   end;
      run;  

       /*----------------------------------------------------
       * Joining direct costs data to the indirect costs 
       * table.
       *----------------------------------------------------*/ 

      %delete_table(work.spl_lgd_d_all_costs)  

      proc sql;
         create table work.spl_lgd_d_all_costs as
         select a.*,
                b.tot_direct_costs
         from work.spl_indirect_costs_discount as a
              left join
              work.spl_direct_costs_discount as b
              on a.loan_no=b.loan_no and
                 a.cab=b.cab and 
                 intnx('month',a.observation_dt,0,'e')=intnx('month',b.observation_dt,0,'e');
      quit; 

      /*----------------------------------------------------
       * Calculating LGD with costs.  The following LGD values 
       * will be calculated: 
       * 1. 
       *----------------------------------------------------*/ 

      %delete_table(&sas_nz_intmed_lib..spl_realized_lgd_d_insert_tbl_1)   

      proc sql;
         create table &sas_nz_intmed_lib..spl_realized_lgd_d_insert_tbl_1 as 
         select a.*,
                "&period_dt"d as process_dt format=date9.,
                'LGD-D' as lgd_type length=6,
                sum(balance_obs,tot_rec,tot_direct_costs)/balance_obs as lgd_npv_drc_cost_rto,
                sum(balance_obs,tot_rec,tot_indirect_costs)/balance_obs as lgd_npv_indrct_cost_rto,
                sum(balance_obs,tot_rec,tot_direct_costs,tot_indirect_costs)/balance_obs as lgd_npv_all_cost_rto,
                case 
                   when calculated lgd_npv_all_cost_rto>1 then 1
						 when calculated lgd_npv_all_cost_rto<0 then 0
                   else calculated lgd_npv_all_cost_rto
                end as lgd_npv_all_cost_flr_cap_100_rto,
                case 
                   when calculated lgd_npv_all_cost_rto>1.25 then 1.25
						 when calculated lgd_npv_all_cost_rto<0 then 0
                   else calculated lgd_npv_all_cost_rto
                end as lgd_npv_all_cost_flr_cap_150_rto,
              case 
                 when a.rcvry_cured_dt=. then 0
                 else b.tm_id 
              end as rcvry_cured_mth_tm_id,
              intnx('month', a.last_new_dft_dt, 24, 'e') as rcvry_window_cutoff_dt format=date9.,
              case 
					  when calculated rcvry_window_cutoff_dt=. then 0
                 else c.tm_id 
              end as rcvry_window_cutoff_tm_id,
              calculated rcvry_window_cutoff_tm_id as rcvry_window_cutoff_mth_tm_id,
				  case 
                 when a.last_new_dft_dt=. then 0
                 else d.tm_id 
              end as last_new_dft_mth_tm_id
         from work.spl_lgd_d_all_costs (rename=(observation_dt=obsvtn_date)) as a

              left join
              &sas_nz_source_lib..tm_dim as b
              on a.rcvry_cured_dt=b.tm_lvl_end_dt and 
                 upcase(b.tm_lvl) = 'MONTH'

              left join &sas_nz_source_lib..tm_dim as c
              on intnx('month', a.last_new_dft_dt, 24, 'e')=c.tm_lvl_end_dt and upcase(c.tm_lvl) = 'MONTH'

              left join 
              &sas_nz_source_lib..tm_dim as d
				  on a.last_new_dft_dt=d.tm_lvl_end_dt and upcase(d.tm_lvl) = 'MONTH'; 
      quit; 


      /* Join to time dim to update obsvtn_mth_tm_id and process_mth_tm_id */
     %delete_table(&sas_nz_intmed_lib..spl_realized_lgd_d_insert_tbl_2) 

      proc sql;
      create table &sas_nz_intmed_lib..spl_realized_lgd_d_insert_tbl_2 as 
      select s.*, 
             t.tm_id as obsvtn_mth_tm_id
      from &sas_nz_intmed_lib..spl_realized_lgd_d_insert_tbl_1 as s
          left join
           nzuser.tm_dim as t
      on s.obsvtn_date=t.tm_lvl_end_dt and t.tm_lvl='Month';
      quit;


     %delete_table(&sas_nz_intmed_lib..spl_realized_lgd_d_insert_tbl_3) 

     proc sql noprint;
      connect using nzuser as nzcon;
      execute (
               create table &FRG_DB..spl_realized_lgd_d_insert_tbl_3 as (
               select s.*, 
                      t.tm_id as process_mth_tm_id
               from &FRG_DB..spl_realized_lgd_d_insert_tbl_2 as s
                 left join
                    &FRG_DB..tm_dim as t
               on s.process_dt=date_trunc('day', t.tm_lvl_end_dt) and t.tm_lvl='Month') WITH DATA; 
			) 	by nzcon;
      disconnect from nzcon;
      quit;
      

     

     %delete_table(&sas_nz_intmed_lib..spl_realized_lgd_d_insert_tbl) 

     proc sql noprint;
      connect using nzuser as nzcon;
      execute (
               create table &FRG_DB..spl_realized_lgd_d_insert_tbl as (
               select s.*
               from &FRG_DB..spl_realized_lgd_d_insert_tbl_3 as s ) WITH DATA;
                 ) by nzcon;
      disconnect from nzcon;
      quit;

      PROC SQL;
         CONNECT USING NZUSER AS IIASCON;
         EXECUTE (ALTER TABLE &FRG_DB..spl_realized_lgd_d_insert_tbl
                     ADD COLUMN LGD_NO_COST_FLR_CAP_150_RTO DECIMAL (29,8)
                     ADD COLUMN LGD_RTO_BKUP DECIMAL (29,8)
                     ADD COLUMN LGD_NPV_ALL_COST_100_RTO_BKP DECIMAL (29,8)
                     ADD COLUMN LGD_NPV_ALL_COST_150_RTO_BKP DECIMAL (29,8)
                     ADD COLUMN LGD_NPV_ALL_COST_RTO_BKUP DECIMAL (29,8)
                     ADD COLUMN LGD_NPV_DRC_COST_RTO_BKUP DECIMAL (29,8)
                     ADD COLUMN LGD_NPV_INDRCT_COST_RTO_BKUP DECIMAL (29,8))BY IIASCON;
         DISCONNECT FROM IIASCON;
      QUIT;
      
      /*---------------------------------------------
       * Checks to see if the date is in NZ table for
       * the realized value output.
       *---------------------------------------------*/ 

      proc sql noprint;
         select count(*) 
         into :date_count trimmed
         from &sas_nz_results_lib..&output_table_realized
         where (month(process_date) = month("&period_dt"d) and year(process_date) = year("&period_dt"d)) and 
               upcase(lgd_type)='LGD-D';
      quit;   
   

      /*---------------------------------------------
       * If data already exists for the month, the 
       * run delete from code.
       *---------------------------------------------*/  

      %if %eval(&date_count) > 0 %then
      %do;
         proc sql;
            connect using &sas_nz_results_lib as nzcon;
            execute (
                  
               delete from %nrbquote(&nz_results_db..&output_table_realized)
               where (date_part('month',process_date) = date_part('month',cast(%nrbquote('&period_dt_nz') as date)) and 
                      date_part('year',process_date) = date_part('year',cast(%nrbquote('&period_dt_nz') as date))) and
                     upper(lgd_type)='LGD-D' 

            ) by nzcon;
          *  execute (generate statistics on %nrbquote(&nz_results_db..&output_table_realized)) by nzcon;
			execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_results_db..&output_table_realized) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
            disconnect from nzcon;
         quit;
      %end;   
      
      /* Insert data into NZ results table*/ 

      proc sql;
         connect using &sas_nz_results_lib as nzcon;
         execute(    

            insert into %nrbquote(&nz_results_db..&output_table_realized) 
            select a.basel_acct_id,
                a.obsvtn_mth_tm_id,
               a.process_mth_tm_id,
                   a.process_dt as process_date, 
                   a.obsvtn_date, 
                   a.loan_no, 
                   a.cab, 
                   a.sub_portfolio,
                   a.lgd_type, 
                   a.lgd_rto, 
                   a.lgd_npv_all_cost_flr_cap_100_rto, 
                   a.lgd_npv_all_cost_flr_cap_150_rto,
                   a.lgd_npv_all_cost_rto, 
                   a.lgd_npv_drc_cost_rto, 
                   a.lgd_npv_indrct_cost_rto, 
                   now() as insrt_process_tmstmp,
                   now() as updt_process_tmstmp,
                   a.LGD_NO_COST_FLR_CAP_150_RTO,
                   a.LGD_RTO_BKUP,
                   a.LGD_NPV_ALL_COST_100_RTO_BKP,
                   a.LGD_NPV_ALL_COST_150_RTO_BKP,
                   a.LGD_NPV_ALL_COST_RTO_BKUP,
                   a.LGD_NPV_DRC_COST_RTO_BKUP,
                   a.LGD_NPV_INDRCT_COST_RTO_BKUP

                  
            from %nrbquote(&nz_intmed_db).spl_realized_lgd_d_insert_tbl as a
            where last_day(date_trunc('day', a.process_dt))=%nrbquote('&period_dt_nz')
         ) by nzcon;
       *  execute (generate statistics on %nrbquote(&nz_results_db..&output_table_realized)  ) by nzcon;
		 	execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_results_db..&output_table_realized) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
         disconnect from nzcon;
      quit;

%etl_job_end;


      /*-------------------------------------------------
       * Checking if date being looped is in the Costs
       * output table.
       *-------------------------------------------------*/

%etl_job_start(target_table=&sas_nz_results_lib..&output_table_costs,PROCESS_MTH_TM_ID=PROCESS_MTH_TM_ID,condition=%nrquote(upcase(lgd_type)='LGD-D'));

      proc sql noprint;
         select count(*) 
         into :date_count2 trimmed
         from &sas_nz_results_lib..&output_table_costs
         where (month(process_date) = month("&period_dt"d) and year(process_date) = year("&period_dt"d)) and 
               upcase(lgd_type)='LGD-D';
      quit; 

      %if %eval(&date_count2) > 0 %then
      %do;
         proc sql;
            connect using &sas_nz_results_lib as nzcon;
            execute (
                  
               delete from %nrbquote(&nz_results_db..&output_table_costs)
               where (date_part('month',process_date) = date_part('month',cast(%nrbquote('&period_dt_nz') as date)) and 
                      date_part('year',process_date) = date_part('year',cast(%nrbquote('&period_dt_nz') as date))) and 
                     upper(lgd_type)='LGD-D'  

            ) by nzcon;
          *  execute (generate statistics on %nrbquote(&nz_results_db..&output_table_costs)) by nzcon;
				execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_results_db..&output_table_costs) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
            disconnect from nzcon;
         quit;
      %end; 

      proc sql;
         connect using &sas_nz_results_lib as nzcon;
         execute(
         
            insert into %nrbquote(&nz_results_db..&output_table_costs)
            select a.basel_acct_id,
                   a.obsvtn_mth_tm_id,
                   a.process_mth_tm_id,
                   a.process_dt as process_date,
                   a.obsvtn_date, 
                   a.loan_no, 
                   a.cab, 
                   a.sub_portfolio,
                   a.lgd_type,
                   a.tot_direct_costs as drc_cost_npv_realz_amt,
                   a.tot_indirect_costs as indrct_cost_npv_realz_amt,
                   now() as insrt_process_tmstmp,
                   now() as updt_process_tmstmp 
                                        
            from %nrbquote(&nz_intmed_db).spl_realized_lgd_d_insert_tbl as a
            where last_day(date_trunc('day', a.process_dt))=%nrbquote('&period_dt_nz')
         ) by nzcon;
       *  execute (generate statistics on %nrbquote(&nz_results_db..&output_table_costs)) by nzcon;
		 	execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_results_db..&output_table_costs) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
         disconnect from nzcon;
      quit;

%etl_job_end;

      /*------------------------------------------------
       * Checking to see if data exists in the recovery
       * output table.
       *------------------------------------------------*/
%etl_job_start(target_table=&sas_nz_results_lib..&output_table_recovery,PROCESS_MTH_TM_ID=PROCESS_MTH_TM_ID,condition=%nrquote(upcase(lgd_type)='LGD-D'));

      proc sql noprint;
         select count(*) 
         into :date_count3 trimmed
         from &sas_nz_results_lib..&output_table_recovery
         where (month(process_date) = month("&period_dt"d) and year(process_date) = year("&period_dt"d)) and 
               upcase(lgd_type)='LGD-D';
      quit; 

      %if %eval(&date_count3) > 0 %then
      %do;
         proc sql;
            connect using &sas_nz_results_lib as nzcon;
            execute (
                  
               delete from %nrbquote(&nz_results_db..&output_table_recovery)
               where (date_part('month',process_date) = date_part('month',cast(%nrbquote('&period_dt_nz') as date)) and 
                      date_part('year',process_date) = date_part('year',cast(%nrbquote('&period_dt_nz') as date))) and 
                     upper(lgd_type)='LGD-D'  

            ) by nzcon;
        *    execute (generate statistics on %nrbquote(&nz_results_db..&output_table_recovery)) by nzcon;
				execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_results_db..&output_table_recovery) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
            disconnect from nzcon;
         quit;
      %end; 

      proc sql;
         connect using &sas_nz_results_lib as nzcon;
         execute(
         
            insert into %nrbquote(&nz_results_db..&output_table_recovery)
            select a.basel_acct_id,
                   a.obsvtn_mth_tm_id,
                   a.process_mth_tm_id,
                   a.rcvry_cured_mth_tm_id,
                   a.process_dt as process_date,
                   a.obsvtn_date, 
                   a.loan_no, 
                   a.cab, 
                   a.sub_portfolio,
                   a.lgd_type,
                   a.rcvry_cured_dt,
                   a.tot_rec as rcvry_npv_realz_amt,
                   now() as insrt_process_tmstmp,
                   now() as updt_process_tmstmp
                                       
            from %nrbquote(&nz_intmed_db).spl_realized_lgd_d_insert_tbl as a
            where last_day(date_trunc('day', a.process_dt))=%nrbquote('&period_dt_nz')
         ) by nzcon;
      *   execute (generate statistics on %nrbquote(&nz_results_db..&output_table_recovery)) by nzcon;
		 	execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS 
						ON TABLE ) %nrbquote(&nz_results_db..&output_table_recovery) 
							%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
         disconnect from nzcon;
      quit;

   
%etl_job_end;

      /*------------------------------------------------
       * Adding RECOVERY WINDOW CUTOFF to the derived 
       * vars table
       *------------------------------------------------*/
  /*    %delete_table(&sas_nz_intmed_lib..&intmed_obsvt_drvd_var)
      proc sql noprint;
         connect using &sas_nz_intmed_lib as nzcon;
         execute (

            create table %nrbquote(&intmed_obsvt_drvd_var) as 
            select a.basel_acct_id,
                   a.obsvtn_mth_tm_id,
                   a.process_mth_tm_id,
                   a.last_new_dft_mth_tm_id,
                   a.process_dt,
                   a.obsvtn_date as obsvtn_dt,
                   a.loan_no as loan_num,
                   a.cab,
                   a.sub_portfolio as sub_portfl,
                   b.pit_stat_ver_2_cd,
                   b.model_dft_f,
                   a.last_new_dft_dt,
                   a.last_new_dft_bal_amt,
                   a.rcvry_window_cutoff_tm_id,
                   a.rcvry_window_cutoff_dt,
                   a.rcvry_window_cutoff_mth_tm_id,
                   now() as insrt_process_tmstmp,
                   now() as updt_process_tmstmp

            from  %nrbquote(&nz_intmed_db)..spl_realized_lgd_d_insert_tbl as a

                  left join

                  %nrbquote(&nz_intmed_db)..psnl_loan_obsvtn_pt_drvd_var as b
                  on (last_day(date_trunc('day', a.obsvtn_date)) = last_day(date_trunc('day', b.obsvtn_dt)) and
                     a.loan_no = b.loan_num and
                     a.cab = b.cab)

            where last_day(date_trunc('day', a.obsvtn_date))=%nrbquote('&obs_date_nz')
         ) by nzcon;
         disconnect from nzcon;
      quit;
*/
      /*------------------------------------------------
       * Check if dates exist and delete accordingly
       *------------------------------------------------*/
 /*     proc sql noprint;
         select count(*) 
         into :date_count4 trimmed
         from &sas_rrap_lib..&output_table_obsvtn_pt
         where (month(obsvtn_dt) = month("&obs_date_sas"d) 
                and year(obsvtn_dt) = year("&obs_date_sas"d));
      quit; 

      %if %eval(&date_count4) > 0 %then
      %do;
         proc sql;
            connect using &sas_rrap_lib as nzcon;
            execute (
                  
               delete from %nrbquote(&nz_rrap_db..&output_table_obsvtn_pt)
               where (date_part('month', obsvtn_dt) = date_part('month',cast(%nrbquote('&obs_date_nz') as date)) 
                      and date_part('year', obsvtn_dt) = date_part('year',cast(%nrbquote('&obs_date_nz') as date))
                      and basel_acct_id in (select distinct b.basel_acct_id 
                                              from %nrbquote(&nz_intmed_db..&intmed_obsvt_drvd_var) as b))

            ) by nzcon;
            disconnect from nzcon;
         quit;
      %end; 

      proc sql;
         connect using &sas_rrap_lib as nzcon;
         execute(
            insert into %nrbquote(&nz_rrap_db..&output_table_obsvtn_pt)
            select a.basel_acct_id,
                   a.obsvtn_mth_tm_id,
                   a.process_mth_tm_id,
                   a.last_new_dft_mth_tm_id,
                   a.process_dt,
                   a.obsvtn_dt,
                   a.loan_num,
                   a.cab,
                   a.sub_portfl,
                   a.pit_stat_ver_2_cd,
                   a.model_dft_f,
                   a.last_new_dft_dt,
                   a.last_new_dft_bal_amt,
                   a.rcvry_window_cutoff_tm_id,
                   a.rcvry_window_cutoff_dt,
                   a.rcvry_window_cutoff_mth_tm_id,
                   a.insrt_process_tmstmp,
                   a.updt_process_tmstmp
            from %nrbquote(&nz_intmed_db..&intmed_obsvt_drvd_var) as a
            where last_day(date_trunc('day', a.obsvtn_dt))=%nrbquote('&obs_date_nz')
         ) by nzcon;
         disconnect from nzcon;
      quit;
*/
   %end;
%mend lgd_d;

%lgd_d (start_period_dt = &start_period_dt, end_period_dt =&end_period_dt)


/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);