/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8563);
%let metaServer     = %nrquote(iw503-prod.bns);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

%rrap_dlgd_autoexec
%rrap_ncrbtt_autoexec
%rrap_spl_autoexec
%RRAP_MOR_TNG_AUTOEXEC
%rrap_mor_bns_autoexec
%rrap_autoexec
%report_validation
%rrap_exception_rpt_autoexec
%rrap_dt4_autoexec

OPTIONS NOERRABEND;

LIBNAME SAS_TEST "/sasdata/sasdi/sasprod/data/rrap_iias";

/**********************IIAS************************IIAS*********************IIAS*****/

/*CREATE TABLE IIAS - SQL PASSTHROUGH*/
PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      CREATE TABLE NZRRAP.TEST_IIAS_CONN AS
            SELECT * FROM CONNECTION TO IIASCON
            (SELECT * FROM EDRTLRP1D.TM_DIM);
      DISCONNECT FROM IIASCON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :TEST_COUNT
      FROM NZRRAP.TEST_IIAS_CONN;
QUIT;

%PUT &=TEST_COUNT;

%MACRO CREATE_TEST;
%IF &TEST_COUNT > 0 %THEN %DO;
      %PUT "TABEL CREATED WITH DATA SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%CREATE_TEST

/*UPDATE TABLE IIAS - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      EXECUTE(CREATE TABLE EDRTLRP1D.TM_DIM_MERGE AS (SELECT * FROM EDRTLRP1D.TM_DIM)WITH DATA ORGANIZE BY ROW;)BY IIASCON;
      EXECUTE(UPDATE EDRTLRP1D.TM_DIM_MERGE SET TM_LVL = 'UPDATED';)BY IIASCON;
      DISCONNECT FROM IIASCON;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :UPDATE_CHECK_ORI FROM NZRRAP.TM_DIM;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :UPDATE_CHECK_UPD FROM NZRRAP.TM_DIM_MERGE;
QUIT;

%MACRO UPDATE_CHECK;
%IF &UPDATE_CHECK_UPD = 1 %THEN %DO;
      %PUT "TABEL UPDATED SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%UPDATE_CHECK

/*MERGE CHECK IIAS - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      EXECUTE(MERGE INTO EDRTLRP1D.TEST_IIAS_CONN TIC
                  USING (SELECT TM_ID, TM_LVL FROM EDRTLRP1D.TM_DIM_MERGE) TDM
                  ON (TIC.TM_ID = TDM.TM_ID)
                  WHEN MATCHED THEN
                  UPDATE SET
                        TM_LVL = TDM.TM_LVL;)BY IIASCON;
      DISCONNECT FROM IIASCON;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :MERGE_CHECK_ORI FROM NZRRAP.TM_DIM;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :MERGE_CHECK_UPD FROM NZRRAP.TM_DIM_MERGE;
QUIT;

%MACRO MERGE_CHECK;
%IF &MERGE_CHECK_UPD = &MERGE_CHECK_ORI %THEN %DO;
      %PUT "TABEL MERGE-UPDATED SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%MERGE_CHECK

/* TRUNCATE TABLE IIAS - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      EXECUTE(TRUNCATE TABLE EDRTLRP1D.TEST_IIAS_CONN IMMEDIATE)BY IIASCON;
      DISCONNECT FROM IIASCON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :TEST_COUNT
      FROM NZRRAP.TEST_IIAS_CONN;
QUIT;

%PUT &=TEST_COUNT;

%MACRO TRUNCATE_TEST;
%IF &TEST_COUNT = 0 %THEN %DO;
      %PUT "TABEL TRUNCATED SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%TRUNCATE_TEST

/*INSERT IIAS - SQL PASSTHROUGH*/

PROC SQL;
      SELECT COUNT(*) INTO :PRIOR_INSERT_CHECK FROM NZRRAP.TEST_IIAS_CONN;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :ORIG_COUNT_INSERT_CHECK FROM NZRRAP.TM_DIM;
QUIT;

PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      EXECUTE(INSERT INTO EDRTLRP1D.TEST_IIAS_CONN (SELECT * FROM EDRTLRP1D.TM_DIM))BY IIASCON;
      DISCONNECT FROM IIASCON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :POST_INSERT_CHECK FROM NZRRAP.TEST_IIAS_CONN;
QUIT;

%MACRO INSERT_TEST;
%IF &POST_INSERT_CHECK = &ORIG_COUNT_INSERT_CHECK AND &PRIOR_INSERT_CHECK = 0 %THEN %DO;
      %PUT "TABEL INSERT SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%INSERT_TEST

/*DELETE TEST IIAS - SQL PASSTHROUGH*/

PROC SQL;
      SELECT COUNT(*) INTO :DELETE_PRIOR_COUNT FROM NZRRAP.TEST_IIAS_CONN;
QUIT;

PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      EXECUTE(DELETE FROM EDRTLRP1D.TEST_IIAS_CONN WHERE TM_LVL = 'Month')BY IIASCON;
      DISCONNECT FROM IIASCON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :DELETE_POST_COUNT FROM NZRRAP.TEST_IIAS_CONN;
QUIT;

%MACRO DELETE_TEST;
%IF &DELETE_PRIOR_COUNT > &DELETE_POST_COUNT %THEN %DO;
      %PUT "TABEL DELETE SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%DELETE_TEST

/* ALTER TABLE IIAS - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      EXECUTE(ALTER TABLE EDRTLRP1D.TEST_IIAS_CONN
                  ADD TEST CHARACTER(1);)BY IIASCON;
      DISCONNECT FROM IIASCON;
QUIT;

PROC SQL;
	SELECT COUNT(DISTINCT NAME) INTO :ORIGINAL_COUNT
	FROM DICTIONARY.COLUMNS
	WHERE MEMNAME = 'TM_DIM' AND LIBNAME = 'NZRRAP';
QUIT;

PROC SQL;
	SELECT COUNT(DISTINCT NAME) INTO :UPDATED_COUNT
	FROM DICTIONARY.COLUMNS
	WHERE MEMNAME = 'TEST_IIAS_CONN' AND LIBNAME = 'NZRRAP';
QUIT;

%MACRO ALTER_TEST;
%IF &UPDATED_COUNT > &ORIGINAL_COUNT %THEN %DO;
	%PUT "TABLE ALTERED SUCCESSFULLY";
%END;
%ELSE %DO;
	%PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%ALTER_TEST

/* DROP TABLE IIAS - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS IIASCON(DATABASE=BLUDBPRD AUTHDOMAIN='IIAS_Auth');
      EXECUTE(DROP TABLE EDRTLRP1D.TEST_IIAS_CONN)BY IIASCON;
      EXECUTE(DROP TABLE EDRTLRP1D.TM_DIM_MERGE)BY IIASCON;
      DISCONNECT FROM IIASCON;
QUIT;

%MACRO DROP_TABLE_CHECK;
      %IF %SYSFUNC(EXIST(NZRRAP.TEST_IIAS_CONN)) %THEN %DO;
            %PUT "KINDLY INVESTIGATE";
      %END;
      %ELSE %DO;
            %PUT "TABLE DROPPED SUCCESSFULLY";
      %END;
%MEND DROP_TABLE_CHECK;

%DROP_TABLE_CHECK

/*******************DB2*************************DB2*****************************DB2*********/
%put &DB2RRAP.;
%put &NZRRAP.;

DATA DB2RRAP.TM_DIM_CONN_TEST;
	SET NZRRAP.TM_DIM;
RUN;

/*CREATE TABLE DB2 - SQL PASSTHROUGH*/
PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      CREATE TABLE DB2RRAP.TEST_DB2_CONN AS
            SELECT * FROM CONNECTION TO DB2CON
            (SELECT * FROM EDRRAPT.TM_DIM_CONN_TEST);
      DISCONNECT FROM DB2CON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :TEST_COUNT
      FROM DB2RRAP.TEST_DB2_CONN;
QUIT;

%PUT &=TEST_COUNT;

%MACRO CREATE_TEST;
%IF &TEST_COUNT > 0 %THEN %DO;
      %PUT "TABEL CREATED WITH DATA SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%CREATE_TEST

/*UPDATE TABLE DB2 - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      EXECUTE(CREATE TABLE EDRRAPT.TM_DIM_MERGE AS (SELECT * FROM EDRRAPT.TM_DIM)WITH DATA ORGANIZE BY ROW;)BY DB2CON;
      EXECUTE(UPDATE EDRRAPT.TM_DIM_MERGE SET TM_LVL = 'UPDATED';)BY DB2CON;
      DISCONNECT FROM DB2CON;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :UPDATE_CHECK_ORI FROM DB2RRAP.TM_DIM_CONN_TEST;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :UPDATE_CHECK_UPD FROM DB2RRAP.TM_DIM_MERGE;
QUIT;

%MACRO UPDATE_CHECK;
%IF &UPDATE_CHECK_UPD = 1 %THEN %DO;
      %PUT "TABEL UPDATED SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%UPDATE_CHECK

/*MERGE CHECK DB2 - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      EXECUTE(MERGE INTO EDRRAPT.TEST_DB2_CONN TIC
                  USING (SELECT TM_ID, TM_LVL FROM EDRRAPT.TM_DIM_MERGE) TDM
                  ON (TIC.TM_ID = TDM.TM_ID)
                  WHEN MATCHED THEN
                  UPDATE SET
                        TM_LVL = TDM.TM_LVL;)BY DB2CON;
      DISCONNECT FROM DB2CON;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :MERGE_CHECK_ORI FROM DB2RRAP.TM_DIM_CONN_TEST;
QUIT;

PROC SQL;
      SELECT COUNT(DISTINCT TM_LVL) INTO :MERGE_CHECK_UPD FROM DB2RRAP.TM_DIM_MERGE;
QUIT;

%MACRO MERGE_CHECK;
%IF &MERGE_CHECK_UPD = &MERGE_CHECK_ORI %THEN %DO;
      %PUT "TABEL MERGE-UPDATED SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%MERGE_CHECK

/* TRUNCATE TABLE DB2 - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      EXECUTE(TRUNCATE TABLE EDRRAPT.TEST_DB2_CONN IMMEDIATE)BY DB2CON;
      DISCONNECT FROM DB2CON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :TEST_COUNT
      FROM DB2RRAP.TEST_DB2_CONN;
QUIT;

%PUT &=TEST_COUNT;

%MACRO TRUNCATE_TEST;
%IF &TEST_COUNT = 0 %THEN %DO;
      %PUT "TABEL TRUNCATED SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%TRUNCATE_TEST

/*INSERT DB2 - SQL PASSTHROUGH*/

PROC SQL;
      SELECT COUNT(*) INTO :PRIOR_INSERT_CHECK FROM DB2RRAP.TEST_DB2_CONN;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :ORIG_COUNT_INSERT_CHECK FROM DB2RRAP.TM_DIM_CONN_TEST;
QUIT;

PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      EXECUTE(INSERT INTO EDRRAPT.TEST_DB2_CONN (SELECT * FROM EDRRAPT.TM_DIM))BY DB2CON;
      DISCONNECT FROM DB2CON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :POST_INSERT_CHECK FROM DB2RRAP.TEST_DB2_CONN;
QUIT;

%MACRO INSERT_TEST;
%IF &POST_INSERT_CHECK = &ORIG_COUNT_INSERT_CHECK AND &PRIOR_INSERT_CHECK = 0 %THEN %DO;
      %PUT "TABEL INSERT SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%INSERT_TEST

/*DELETE TEST DB2 - SQL PASSTHROUGH*/

PROC SQL;
      SELECT COUNT(*) INTO :DELETE_PRIOR_COUNT FROM DB2RRAP.TEST_DB2_CONN;
QUIT;

PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      EXECUTE(DELETE FROM EDRRAPT.TEST_DB2_CONN WHERE TM_LVL = 'Month')BY DB2CON;
      DISCONNECT FROM DB2CON;
QUIT;

PROC SQL;
      SELECT COUNT(*) INTO :DELETE_POST_COUNT FROM DB2RRAP.TEST_DB2_CONN;
QUIT;

%MACRO DELETE_TEST;
%IF &DELETE_PRIOR_COUNT > &DELETE_POST_COUNT %THEN %DO;
      %PUT "TABEL DELETE SUCCESSFULLY";
%END;
%ELSE %DO;
      %PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%DELETE_TEST

/* ALTER TABLE DB2 - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      EXECUTE(ALTER TABLE EDRRAPT.TEST_DB2_CONN
                  ADD TEST CHARACTER(1);)BY DB2CON;
      DISCONNECT FROM DB2CON;
QUIT;

PROC SQL;
	SELECT COUNT(DISTINCT NAME) INTO :ORIGINAL_COUNT
	FROM DICTIONARY.COLUMNS
	WHERE MEMNAME = 'TM_DIM' AND LIBNAME = 'DB2RRAP';
QUIT;

PROC SQL;
	SELECT COUNT(DISTINCT NAME) INTO :UPDATED_COUNT
	FROM DICTIONARY.COLUMNS
	WHERE MEMNAME = 'TEST_DB2_CONN' AND LIBNAME = 'DB2RRAP';
QUIT;

%MACRO ALTER_TEST;
%IF &UPDATED_COUNT > &ORIGINAL_COUNT %THEN %DO;
	%PUT "TABLE ALTERED SUCCESSFULLY";
%END;
%ELSE %DO;
	%PUT "KINDLY INVESTIGATE";
%END;
%MEND;

%ALTER_TEST

/* DROP TABLE DB2 - SQL PASSTHROUGH*/

PROC SQL;
      CONNECT TO DB2 AS DB2CON(DATABASE=DM1P1D AUTHDOMAIN='DB2_Auth');
      EXECUTE(DROP TABLE EDRRAPT.TEST_DB2_CONN)BY DB2CON;
      EXECUTE(DROP TABLE EDRRAPT.TM_DIM_MERGE)BY DB2CON;
      EXECUTE(DROP TABLE EDRRAPT.TM_DIM_CONN_TEST)BY DB2CON;
      DISCONNECT FROM DB2CON;
QUIT;

%MACRO DROP_TABLE_CHECK;
      %IF %SYSFUNC(EXIST(DB2RRAP.TEST_DB2_CONN)) %THEN %DO;
            %PUT "KINDLY INVESTIGATE";
      %END;
      %ELSE %DO;
            %PUT "TABLE EDRRAPT.TEST_DB2_CONN DROPPED SUCCESSFULLY";
      %END;
      %IF %SYSFUNC(EXIST(DB2RRAP.TM_DIM_MERGE)) %THEN %DO;
            %PUT "KINDLY INVESTIGATE";
      %END;
      %ELSE %DO;
            %PUT "TABLE EDRRAPT.TM_DIM_MERGE DROPPED SUCCESSFULLY";
      %END;
            %IF %SYSFUNC(EXIST(DB2RRAP.TM_DIM_CONN_TEST)) %THEN %DO;
            %PUT "KINDLY INVESTIGATE";
      %END;
      %ELSE %DO;
            %PUT "TABLE EDRRAPT.TM_DIM_CONN_TEST DROPPED SUCCESSFULLY";
      %END;
%MEND DROP_TABLE_CHECK;

%DROP_TABLE_CHECK


/* testing connection to GCVE MSSQL DB using authdomain */
proc sql;
        create table test_recon as
        select * from AIRBSQL.AIRB_RECON_APRVD_STATUS ;
quit;

proc sql;
        create table test_basel as
        select * from sqlnew.NCR_DATAFEED_AUDIT ;
quit;


/*****************************SAS FOLDER ACCESS AND FILE ACCESS CHECK******************************************/

%MACRO CREATE_DELETE_FILE(FILENAME);

FILENAME MYFILE "&FILENAME.";

DATA _NULL_;
	FILE MYFILE;
RUN;

%LET FILE_EXISTS = %SYSFUNC(FILEEXIST(&FILENAME.));

%IF &FILE_EXISTS %THEN %DO;
	FILENAME DEL "&FILENAME.";

	DATA _NULL_;
		RC = FDELETE('DEL');
	RUN;
	%PUT "The CSV file &FILENAME. has been deleted.";
%END;
%ELSE %DO;
	%PUT "The CSV file &FILENAME. does not exist or could not be created.";
%END;

%MEND;

%MACRO DIRECTORY_TEST(DIRECTORY_PATH,TEST_FILE_NAME);

DATA DIR_OPEN_TEMP;
LENGTH FILE_PATH_NAME $200;
FORMAT FILE_PATH_NAME $200.;
%LET EXIST=%SYSFUNC(FILEEXIST(&DIRECTORY_PATH.));
%PUT &EXIST;
%IF &EXIST>0 %THEN %DO;
	FILE "&DIRECTORY_PATH.&TEST_FILE_NAME";
            FILE_PATH_NAME = "&DIRECTORY_PATH.&TEST_FILE_NAME";
            DIRECTORY_ACCESS = "YES";
	%PUT "Directory is ACCESSIBLE";
%CREATE_DELETE_FILE(&DIRECTORY_PATH.&TEST_FILE_NAME.)
%end;
%ELSE %DO ;
            FILE_PATH_NAME = "&DIRECTORY_PATH.&TEST_FILE_NAME";
            DIRECTORY_ACCESS = "NO";
			%PUT "Directory is NOT ACCESSIBLE";
%END;
RUN;

%MEND;

%DIRECTORY_TEST(/owpftp,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/cmf,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/rrm,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/rk,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/mv,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/rrap,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/tng,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/mbr,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/mbr/history,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/bns,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/bns/incoming,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/securitization,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/securitization/cc,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/securitization/cc/incoming,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/securitization/sf,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/securitization/sf/incoming,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/rrap/lookup,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/rk/outgoing,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/rk/outgoing/history,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/mv/outgoing,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/mv/outgoing/history,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/cmf/outgoing,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/cmf/outgoing/CCAR_ACAP,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/owpftp/cmf/outgoing/CCAR_ACAP/history,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/logs,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/logs/rrap_iias,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/macro,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/macro/rrap_iias,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/sas,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/sas/rrap_iias,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/scripts,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/scripts/rrap_iias,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/flat_files,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/flat_files/rrap,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/flat_files/rrap_iias,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/params,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/params/rrap_iias,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/params/rrap,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/data,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/data/triad,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/data/rrap,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/data/rrap/reporting,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/data/rrap_iias,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/data/rrap_iias/reporting,/TEST_CSV_FILE.csv);
%DIRECTORY_TEST(/sasdata/sasdi/sasprod/data/rrap/reporting/cr9,/TEST_CSV_FILE.csv);
