/**************************************************************************** 
 * Job:             J_RRAP_CCAR_09_RRAP_CCAR_PD_CURVE_EX  A57ZQ4A4.BF0011JT * 
 *                  TR                                                      * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503.bns                                            * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/06 - DLGD/CCAR_ECAP                      * 
 *                                                                          * 
 * Server:          SASApp                                A57ZQ4A4.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, July 20, 2017 4:27:12 PM EDT                  * 
 * Generated by:    s2809211                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57ZQ4A4.BF0011JT);
%let etls_jobName = %nrquote(J_RRAP_CCAR_09_RRAP_CCAR_PD_CURVE_EXTR);
%let etls_userID = %nrquote(s2809211);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(cs2iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            CCAR_ECAP_AUTOEXEC                    A57ZQ4A4.BO0016DS * 
 * Transform:       CCAR_ECAP_AUTOEXEC                                      * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57ZQ4A4.BO0016DS);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%include '/sasdata/sasdi/sasdev/macro/rrap/rrap_autoexec.sas';
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end CCAR_ECAP_AUTOEXEC **/

/*---- Start of User Written Code  ----*/ 

/**************************************************************************** 
 * Job:             RRAP_STG_INS_CCAR_PD_CURVE_EXTR.sas  A57ZQ4A4.BF000009 * 
 *                                                                          * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503.bns                                            * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Staging/Jobs                             * 
 *                                                                          * 
 * Server:          SASApp                                A57ZQ4A4.AT000002 * 
 *                                                                          * 
 * Source Tables:   BASEL_ANALYTCL_BL_INSTRMNT_FACT -     A57ZQ4A4.BI00000G * 
 *                  &DBNAME.BASEL_ANALYTCL_BL_INSTRMNT_F                     * 
 *                  ACT                                                     * 
 *                  TM_DIM - EDRTLRT.TM_DIM               A57ZQ4A4.BI0000UP * 
 *                  BASEL_NCR_HIERARCHY_LKP -             A57ZQ4A4.BI000016 * 
 *                   &DBNAME.BASEL_NCR_HIERARCHY_LKP                         * 
 *                  BASEL_NCR_PD_BAND_DIM -               A57ZQ4A4.BI000019 * 
 *                   &DBNAME.BASEL_NCR_PD_BAND_DIM                           * 
 *                  BASEL_TANGRN_CCAR_PD_CURVE -          A57ZQ4A4.BI00002O * 
 *                   &DBNAME.BASEL_TANGRN_CCAR_PD_CURVE                      * 
 * Target Table:    BASEL_CCAR_PD_CURVE_EXTR -            A57ZQ4A4.BI00000P * 
 *                   &DBNAME.BASEL_CCAR_PD_CURVE_EXTR                        * 
 *                                                                          * 
 * Generated on:    Sunday, September 14, 2014 2:43:14 PM EDT               * 
 * Generated by:    s1928220                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

/*DECLARE THE PATH TO DEFINE AUTOCALL MACRO*/
/*OPTIONS MAUTOSOURCE SASAUTOS='/sasdata/sasdev/macro/rrap';*/

/*INITIALIZATION OF VARIABLES AND EXECUTE AUTOCALL MACRO*/
/*%srrap_autoexec('BASELDB2');*/

%GLOBAL YEARMONTH;
%GLOBAL PRELOAD_DATA_COUNT;
%GLOBAL SRCCOUNT00;
%GLOBAL TGTCOUNT00;
%GLOBAL NON_KS_COUNT;
%GLOBAL KS_COUNT;
%LET INPUT00=EDRRAPT.BASEL_ANALYTCL_BL_INSTRMNT_FACT;
%LET INPUT01=EDRRAPT.BASEL_TANGRN_CCAR_PD_CURVE;
%LET TGT00=EDRRAPT.BASEL_CCAR_PD_CURVE_EXTR;
proc sql;
delete from EDRRAPT.BASEL_CCAR_PD_CURVE_EXTR where MTH_END_DT=(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID);
quit;
/*Fetch the Year and Month from TM_DIM to use it for query on 
EDRRAPT.BASEL_SUBSIDIARY_ACL_LKP*/
%macro rrap_db2yearmonth_initialize;
proc sql noprint;
create table _temp_yearmonth as 
select clndr_yr, tm_yr_seq_num, '00' as charmonth, '000000' as yearmonth from 
EDRTLRT.TM_DIM where TM_ID = &MTH_TM_ID;
quit;
/*Convert the integer values to char values as needed*/
data _temp_yearmonth;
set _temp_yearmonth;
if tm_yr_seq_num < 10 then do;
	charmonth='0'||put(tm_yr_seq_num,1.);
end;
else do;
charmonth=tm_yr_seq_num;
end;

yearmonth=clndr_yr||charmonth;
	format yearmonth $char6.;
run;
/*Save the string YYYYMM for the latest MTH_TM_ID fetched from TM_DIM into a 
variable*/
proc sql noprint;
select yearmonth into :yearmonth from _temp_yearmonth;
quit;
%mend rrap_db2yearmonth_initialize;

/*This transformation accepts the target table to be loaded as an input 
parameter
and checks existence of data for the processing MTH_TM_ID */
%MACRO preload_data_check;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :PRELOAD_DATA_COUNT FROM &TGT00. WHERE MTH_END_DT=
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID);
QUIT;

%IF &PRELOAD_DATA_COUNT > 0 %THEN %DO;
%PUT TARGET TABLE &TGT00. ALREADY HAS &PRELOAD_DATA_COUNT RECORDS FOR CURRENT 
PROCESSING MONTH ID &MTH_TM_ID;

%END;
%MEND preload_data_check;

/*This transformation generates the input and output table counts*/
%MACRO datalog;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :SRCCOUNT00 FROM &INPUT00. WHERE MTH_TM_ID=&MTH_TM_ID.;
/*SELECT COUNT(*) INTO :SRCCOUNT01 FROM &INPUT01. WHERE MTH_TM_ID=&MTH_TM_ID.;*/
SELECT COUNT(*) INTO :TGTCOUNT00 FROM &TGT00. WHERE MTH_END_DT=(SELECT 
TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID);
QUIT;
%MEND;

/*CLEANUP MACRO*/
/*THIS MACRO DELETES ALL TEMPORARY SAS DATASETS LISTED BY THE USER AT THE 
SPECIFIED PATH ON AIX PLATFORM*/
/*LIBREF SHOULD BE THE LIBREF DECLARED FOR A UNIX PATH IN THE PROGRAM*/
/*DATASETS SHOULD BE THE LIST OF DATASETS SEPARATED BY A SINGLE SPACE*/
%MACRO SAS_DATASET_CLEANUP (LIBREF=, DATASETS=);
/*DELETE TEMPORARY DATASETS*/
PROC DATASETS LIBRARY=&LIBREF;
DELETE &DATASETS;
RUN;
QUIT;
%MEND;

/*Macro for fetching the yearmonth in an integer format*/
%rrap_db2yearmonth_initialize;
%PUT YEARMONTH IS &YEARMONTH;

/*MACRO TO FETCH THE RECORD COUNT FROM THE TARGET TABLE FOR THE PROCESSING 
MONTH*/
%preload_data_check;

/*==========================================================================* 
 * Step:            Conditional Start                     A57ZQ4A4.BO0002TX * 
 * Transform:       Conditional Start                                       * 
 * Description:     If Preload count > 0 dont load the target               * 
 *==========================================================================*/

%macro etls_conditionW3PAJF8W;
   %local etls_condition;
   %let etls_conditionTrue = %eval(&PRELOAD_DATA_COUNT = 0);
   %if (&etls_conditionTrue=0) %then
   %do;
      %put ETLS_DIAG: Condition flow did NOT execute, condition was &PRELOAD_DATA_COUNT = 0;
      %goto exitetls_conditionW3PAJF8W;
   %end;
   %else
   %do;
      %put ETLS_DIAG: Condition flow did execute, condition was &PRELOAD_DATA_COUNT = 0;
   %end;

/*INITIAL EXTRACT, FETCH PD_MIN_VAL AND PD_MAX_VAL*/
/*FIRST PREPARE THE SUBQUERY WHICH EXTRACTS A UNIQUE COMBINATION OF 
CCAR_BASEL_PRD_TP_NM, NCR_EXPSR_CL_KEY_VAL, PD_BAND,NCR_PD_BAND_KEY_VAL*/
/*THE SUBQUERY IS TO FETCH ALL PD_BANDS FOR EVERY PRD_TP_NM AS IDENTIFIED IN 
THE BSTM STEP 3*/
PROC SQL NOPRINT;
CREATE TABLE &INPATH.._temp_pd_curve_extract AS
SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS 
MTH_END_DT,
PRIM.CCAR_BASEL_PRD_TP_NM AS CCAR_BASEL_PRD_TP_NM,
'DOM-BANK-ALONE' AS LEGAL_ENTITY,
PRIM.PD_BAND AS PD_BAND,
BAND.PD_MIN_VAL AS PD_MIN_VAL,
BAND.PD_MAX_VAL AS PD_MAX_VAL,
&SESSIONTIME AS INSRT_PROCESS_TMSTMP,
&SESSIONTIME AS UPDT_PROCESS_TMSTMP
FROM (SELECT * FROM 
(SELECT DISTINCT CCAR_BASEL_PRD_TP_NM, NCR_EXPSR_CL_KEY_VAL
FROM INPATH.BASEL_ANALYTCL_BL_INSTRMNT_FACT
WHERE 
SML_BUS_F='N'
AND CONSM_PRD_TREATMNT_CD='A'
AND SRC_SYS_CD IN ('TNG-MOR','MOR','SPL')
AND PIT_STAT_CD in ('CUR','DEF')
AND TRNST_EXCLSN_F='N'
AND MTH_TM_ID=&MTH_TM_ID) PRI,
(SELECT DISTINCT PD_BAND,NCR_PD_BAND_KEY_VAL FROM INPATH.BASEL_NCR_PD_BAND_DIM 
WHERE PD_BAND IS NOT NULL) PDBAND) PRIM 
LEFT OUTER JOIN INPATH.BASEL_NCR_HIERARCHY_LKP HIER
ON PRIM.NCR_EXPSR_CL_KEY_VAL = HIER.NCR_KEY_VAL AND HIER.NCR_PRNT_KEY_VAL IN (
'0502', '0503', '0504', '0507')
LEFT OUTER JOIN INPATH.BASEL_NCR_PD_BAND_DIM BAND
	ON HIER.NCR_PRNT_KEY_VAL = BAND.NCR_EXPSR_CL_KEY_VAL
	AND PRIM.NCR_PD_BAND_KEY_VAL = BAND.NCR_PD_BAND_KEY_VAL
AND INPUT(BAND.EFF_FROM_YR_MTH,6.) <= &yearmonth and &yearmonth <= 
INPUT(BAND.EFF_TO_YR_MTH,6.);
QUIT;
/*GENERATE MINIMUM VALUE OF PD_FINAL_RPTG_RTO*/
PROC SQL NOPRINT;
CREATE TABLE &INPATH.._temp_pd_val AS
SELECT CCAR_BASEL_PRD_TP_NM,
'DOM-BANK-ALONE' AS LEGAL_ENTITY,
PD_BAND AS PD_BAND,
MEAN(PD_FINAL_RPTG_RTO) AS PD_VAL
FROM INPATH.BASEL_ANALYTCL_BL_INSTRMNT_FACT
WHERE SML_BUS_F='N'
AND CONSM_PRD_TREATMNT_CD='A'
AND SRC_SYS_CD IN ('TNG-MOR','MOR','SPL')
AND PIT_STAT_CD in ('CUR','DEF')
AND TRNST_EXCLSN_F='N'
AND MTH_TM_ID = &MTH_TM_ID
GROUP BY CCAR_BASEL_PRD_TP_NM,
'DOM-BANK-ALONE',
PD_BAND;
QUIT;
/*SORT THE DATASET*/
PROC SORT DATA=&INPATH.._temp_pd_curve_extract 
OUT=&INPATH.._temp_pd_curve_extract;
BY CCAR_BASEL_PRD_TP_NM LEGAL_ENTITY PD_BAND;
RUN;
/*SORT THE DATASET*/
PROC SORT DATA=&INPATH.._temp_pd_val OUT=&INPATH.._temp_pd_val;
BY CCAR_BASEL_PRD_TP_NM LEGAL_ENTITY PD_BAND;
RUN;
/*MERGE THE DATASETS TO INLCUDE THE PRIMARY EXTRACT AND THE WEIGHTED AVERAGE*/
DATA &INPATH.._temp_ccar_pd_curve_extr_final;
MERGE &INPATH.._temp_pd_curve_extract &INPATH.._temp_pd_val;
BY CCAR_BASEL_PRD_TP_NM LEGAL_ENTITY PD_BAND;
RUN;
/*REPLACE NULL VALUES IN PD_VAL WITH 0*/
DATA &INPATH.._temp_ccar_pd_curve_extr_final;
SET &INPATH.._temp_ccar_pd_curve_extr_final;
WHERE MTH_END_DT > 0;
IF PD_VAL=. THEN DO;
PD_VAL=0;
END;
RUN;
/*BULK LOAD THE SAS DATASET TO NETEZZA TABLE*/
PROC APPEND BASE=EDRRAPT.BASEL_CCAR_PD_CURVE_EXTR 
DATA=&INPATH.._temp_ccar_pd_curve_extr_final FORCE;
RUN;
/*PERFORM COUNT OF RECORDS INSERTED*/
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :NON_KS_COUNT FROM 
&INPATH.._temp_ccar_pd_curve_extr_final;
QUIT;
/*KS SOURCE SYSTEM LOAD*/
/*CREATE LOOKUP TABLE FROM A MASTER TABLE*/
PROC SQL NOPRINT;
CREATE TABLE &INPATH.._temp_pd_curve_prd_lkp AS
SELECT DISTINCT NCR_EXPSR_CL_KEY_VAL, PD_BAND_EXPSR_CL_KEY_VAL FROM 
EDRRAPT.BASEL_RPTG_PRD_LKP WHERE SRC_SYS_CD='KS';
QUIT;
/*INITIAL EXTRACT, FETCH PD_MIN_VAL AND PD_MAX_VAL*/
PROC SQL NOPRINT;
CREATE TABLE &INPATH.._temp_pd_curve_extract AS
SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS 
MTH_END_DT,
PRIM.CCAR_BASEL_PRD_TP_NM AS CCAR_BASEL_PRD_TP_NM,
'DOM-BANK-ALONE' AS LEGAL_ENTITY,
PRIM.PD_BAND AS PD_BAND,
BAND.PD_MIN_VAL AS PD_MIN_VAL,
BAND.PD_MAX_VAL AS PD_MAX_VAL,
&SESSIONTIME AS INSRT_PROCESS_TMSTMP,
&SESSIONTIME AS UPDT_PROCESS_TMSTMP
FROM (SELECT * FROM 
(SELECT DISTINCT CCAR_BASEL_PRD_TP_NM, NCR_EXPSR_CL_KEY_VAL
FROM INPATH.BASEL_ANALYTCL_BL_INSTRMNT_FACT
WHERE 
SML_BUS_F='N'
AND CONSM_PRD_TREATMNT_CD='A'
AND SRC_SYS_CD IN ('KS')
AND PIT_STAT_CD in ('CUR','DEF')
AND TRNST_EXCLSN_F='N'
AND MTH_TM_ID=&MTH_TM_ID) PRI,
(SELECT DISTINCT PD_BAND,NCR_PD_BAND_KEY_VAL FROM EDRRAPT.BASEL_NCR_PD_BAND_DIM 
WHERE PD_BAND IS NOT NULL) PDBAND) PRIM
LEFT OUTER JOIN &INPATH.._temp_pd_curve_prd_lkp PRD 
	ON PRIM.NCR_EXPSR_CL_KEY_VAL = PRD.NCR_EXPSR_CL_KEY_VAL AND PRD.PD_BAND_EXPSR_CL_KEY_VAL IN ('0502', '0503', '0504', '0507')
LEFT OUTER JOIN INPATH.BASEL_NCR_PD_BAND_DIM BAND
	ON PRD.PD_BAND_EXPSR_CL_KEY_VAL = BAND.NCR_EXPSR_CL_KEY_VAL 
	AND PRIM.NCR_PD_BAND_KEY_VAL = BAND.NCR_PD_BAND_KEY_VAL 
AND INPUT(BAND.EFF_FROM_YR_MTH,6.) <= &yearmonth and &yearmonth <= 
INPUT(BAND.EFF_TO_YR_MTH,6.);
QUIT;
/*GENERATE MINIMUM VALUE OF PD_FINAL_RPTG_RTO*/
PROC SQL NOPRINT;
CREATE TABLE &INPATH.._temp_pd_val AS
SELECT CCAR_BASEL_PRD_TP_NM,
'DOM-BANK-ALONE' AS LEGAL_ENTITY,
PD_BAND AS PD_BAND,
MEAN(PD_FINAL_RPTG_RTO) AS PD_VAL
FROM INPATH.BASEL_ANALYTCL_BL_INSTRMNT_FACT
WHERE SML_BUS_F='N'
AND CONSM_PRD_TREATMNT_CD='A'
AND SRC_SYS_CD IN ('KS')
AND PIT_STAT_CD in ('CUR','DEF')
AND TRNST_EXCLSN_F='N'
AND MTH_TM_ID = &MTH_TM_ID
GROUP BY CCAR_BASEL_PRD_TP_NM,
'DOM-BANK-ALONE',
PD_BAND;
QUIT;
/*SORT THE DATASET*/
PROC SORT DATA=&INPATH.._temp_pd_curve_extract 
OUT=&INPATH.._temp_pd_curve_extract;
BY CCAR_BASEL_PRD_TP_NM LEGAL_ENTITY PD_BAND;
RUN;
/*SORT THE DATASET*/
PROC SORT DATA=&INPATH.._temp_pd_val OUT=&INPATH.._temp_pd_val;
BY CCAR_BASEL_PRD_TP_NM LEGAL_ENTITY PD_BAND;
RUN;
/*MERGE THE DATASETS TO INLCUDE THE PRIMARY EXTRACT AND THE WEIGHTED AVERAGE*/
DATA &INPATH.._temp_ccar_pd_curve_extr_final;
MERGE &INPATH.._temp_pd_curve_extract &INPATH.._temp_pd_val;
BY CCAR_BASEL_PRD_TP_NM LEGAL_ENTITY PD_BAND;
RUN;
/*REPLACE NULL VALUES IN PD_VAL WITH 0*/
DATA &INPATH.._temp_ccar_pd_curve_extr_final;
SET &INPATH.._temp_ccar_pd_curve_extr_final;
WHERE MTH_END_DT > 0;
IF PD_VAL=. THEN DO;
PD_VAL=0;
END;
RUN;
/*BULK LOAD THE SAS DATASET TO NETEZZA TABLE*/
PROC APPEND BASE=EDRRAPT.BASEL_CCAR_PD_CURVE_EXTR 
DATA=&INPATH.._temp_ccar_pd_curve_extr_final FORCE;
RUN;
/*PERFORM COUNT OF RECORDS INSERTED*/
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :KS_COUNT FROM &INPATH.._temp_ccar_pd_curve_extr_final;
QUIT;

/*TANGERINE LOAD*/
/**/
/*PROC SQL;*/
/*INSERT INTO EDRRAPT.BASEL_CCAR_PD_CURVE_EXTR*/
/*SELECT */
/*(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS */
/*MTH_END_DT,*/
/*CCAR_BASEL_PRD_TP_NM,*/
/*'DOM-BANK-ALONE' AS LEGAL_ENTITY,*/
/*PD_BAND,*/
/*PD_MIN_VAL/100 AS PD_MIN_VAL FORMAT 28.8,*/
/*PD_MAX_VAL/100 AS PD_MAX_VAL FORMAT 28.8,*/
/*PD_VAL/100 AS PD_VAL FORMAT 28.8,*/
/*&SESSIONTIME AS INSRT_PROCESS_TMSTMP,*/
/*&SESSIONTIME AS UPDT_PROCESS_TMSTMP*/
/*FROM EDRRAPT.BASEL_TANGRN_CCAR_PD_CURVE*/
/*WHERE MTH_TM_ID=&MTH_TM_ID;*/
/*QUIT;*/

%datalog;
%SAS_DATASET_CLEANUP(LIBREF=INPATH,DATASETS=_temp_pd_curve_extract _temp_pd_val _temp_ccar_pd_curve_extr_final _temp_pd_curve_prd_lkp);

%PUT 
PROCESSING MONTH IS &MTH_TM_ID 
YEARMONTH IS &YEARMONTH;
%PUT
PRELOAD DATA COUNT IN TARGET FOR &MTH_TM_ID. IS &PRELOAD_DATA_COUNT. 
&INPUT00. COUNT IS &SRCCOUNT00 
/*&INPUT01. COUNT IS &SRCCOUNT01 */
&TGT00. COUNT IS &TGTCOUNT00 
TARGET KS_COUNT IS &KS_COUNT. AND TARGET NON_KS_COUNT IS &NON_KS_COUNT.;


%exitetls_conditionW3PAJF8W:
%mend etls_conditionW3PAJF8W;

%etls_conditionW3PAJF8W;

%put etls_endTime = %sysfunc(datetime(),datetime.);


/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

