/**************************************************************************** 
 * Job:             J_RRAP_CCAR_AUDIT_CHECKS              A57SWEI7.BH000LHH * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503                                                * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/03 - Reporting                      * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Wednesday, September 27, 2017 1:55:55 PM EDT            * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH000LHH);
%let etls_jobName = %nrquote(J_RRAP_CCAR_AUDIT_CHECKS);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_mor_bns_autoexec              A57SWEI7.BK00108W * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK00108W);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mor_bns_autoexec **/

/*---- Start of User Written Code  ----*/ 

%get_model_period_dates(product=mor);
%put Start and End Dates for MOR Models:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;



data _null_;
call symputx('dt',put("&start_period_dt"d,yymmddn8.));
run;

%put &dt.;

/*DR-AIRB-EXPOSURES-20170630*/
/*DR-AIRB-EXPOSURES-BEF_NEG_NET_20170630*/

/*%let dt=20170731;*/

%macro load_dr(filename=,char=);

proc import datafile="&OUTPATH./cmf/outgoing/&filename.&char.&dt..csv"
     out=DR_AIRB_EXPOSURES
     dbms=csv
     replace; guessingrows=max;
     getnames=YES;
run;

data DR_AIRB_EXPOSURES;
retain RPTG_TP RPTG_DT_TEXT;
set DR_AIRB_EXPOSURES;
*drop OBLIGORS Exposures__Drawn__Prior_SECRTZTN Exposures__Drawn__no_SECRTZTN Exposures__Drawn__with_SECRTZTN SECRTZTN_Amount Exposures__Drawn__Reduced SECRTZTN_Flag;
drop OBLIGORS Exposures__Drawn__Prior_SECRTZTN Exposures__Drawn__no_SECRTZTN Exposures__Drawn__with_SECRTZTN SECRTZTN_Amount Exposures__Drawn__Reduced SECRTZTN_Flag 
ECL_Drawn_1	ECL_Drawn_2	ECL_Drawn_3	ECL_Undrawn_1 ECL_Undrawn_2 ECL_Undrawn_3 ECL_Drawn_PostSec_1 ECL_Drawn_PostSec_2 ECL_Drawn_PostSec_3 
ECL_Post_Adj_Drawn_1 ECL_Post_Adj_Drawn_2 ECL_Post_Adj_Drawn_3 ECL_Post_Adj_Undrawn_1 ECL_Post_Adj_Undrawn_2 ECL_Post_Adj_Undrawn_3	ECL_Post_Adj_Drawn_PostSec_1 
ECL_Post_Adj_Drawn_PostSec_2 ECL_Post_Adj_Drawn_PostSec_3;
RPTG_TP="&filename.";
RPTG_DT_TEXT="&dt.";
run;

proc sql;
create table nznames as
select varnum, name as target from sashelp.vcolumn
where libname='NZRRAP' and memname='BASEL_CCAR_EXPSR_RPTG_EXTR'
order by varnum;
create table sasnames as
select varnum, name as source from sashelp.vcolumn
where libname='WORK' and memname='DR_AIRB_EXPOSURES'
order by varnum;
quit;

data mapping;
merge  sasnames nznames;
by varnum;
if source=target then delete;
source=trim("'"||trim(source)||"'n");
target=trim(target);
run;



data _null_;
set mapping;
call symputx('source'||trim(left(_n_)),source);
call symputx('target'||trim(left(_n_)),target);
call symputx('nobs',_n_);
run;

%put &source7. &target7.;

%macro rename();
proc datasets library=work nolist;
modify DR_AIRB_EXPOSURES;
%do i = 1 %to &nobs;
rename &&source&i. = &&target&i.;
%end;
run;
%mend rename;
%rename;



/***************************************************************************************************/
proc sql;
create table nznames as
select varnum, name as source, type as type_nz, length as l_nz, format as f_nz from sashelp.vcolumn
where libname='NZRRAP' and memname='BASEL_CCAR_EXPSR_RPTG_EXTR'
order by varnum;
create table sasnames as
select varnum, name as source, type as type_sas, length as l_sas, format as f_sas from sashelp.vcolumn
where libname='WORK' and memname='DR_AIRB_EXPOSURES'
order by varnum;
quit;

data mapping;
merge  sasnames nznames;
by varnum;
if type_sas=type_nz then delete;
run;


data _null_;
set mapping;
call symputx('source'||trim(left(_n_)),source);
call symputx('nobs',_n_);
run;

%put &source1. &source2. &source6.;

%macro newtype();
data  DR_AIRB_EXPOSURES;
set DR_AIRB_EXPOSURES;
%do i = 1 %to &nobs;
&&source&i.._new = compress(put(&&source&i.,BEST12.));
drop &&source&i.;
rename &&source&i.._new = &&source&i.;
%end;
run;
%mend newtype;
%newtype;


proc sql;
connect using nzrrap as nzcon;
execute(delete from &RRAP_DB..BASEL_CCAR_EXPSR_RPTG_EXTR where RPTG_DT_TEXT=%nrbquote('&dt.') and RPTG_TP=%nrbquote('&filename.')) by nzcon;
quit;

proc append base=nzrrap.BASEL_CCAR_EXPSR_RPTG_EXTR (BULKLOAD=YES BL_METHOD=CLILOAD) data=DR_AIRB_EXPOSURES force; run;


%mend load_dr;

%load_dr(filename=DR-AIRB-EXPOSURES, char=-);
%load_dr(filename=DR-AIRB-EXPOSURES-BEF_NEG_NET, char=_);

/*---- End of User Written Code  ----*/ 

/*---- Start of User Written Code  ----*/ 

proc import datafile="&OUTPATH./cmf/outgoing/DR-AIRB-PD-CURVE-&dt..csv"
     out=PD_CURVE
     dbms=csv
     replace;
	 guessingrows=max;
     getnames=YES;
run;

data PD_CURVE;
retain RPTG_DT_TEXT;
set PD_CURVE;
RPTG_DT_TEXT="&dt.";
run;

proc sql;
create table nznames as
select varnum, name as target from sashelp.vcolumn
where libname='NZRRAP' and memname='BASEL_CCAR_PD_RPTG_EXTR'
order by varnum;
create table sasnames as
select varnum, name as source from sashelp.vcolumn
where libname='WORK' and memname='PD_CURVE'
order by varnum;
quit;

data mapping;
merge  sasnames nznames;
by varnum;
if source=target then delete;
source=trim("'"||trim(source)||"'n");
target=trim(target);
run;


/*data mapping;*/
/*set mapping;*/
/*target=tranwrd(target,'.','_');*/
/*source=compress(source);*/
/*run;*/

options mprint;
data _null_;
set mapping;
call symputx('source'||trim(left(_n_)),source);
call symputx('target'||trim(left(_n_)),target);
call symputx('nobs',_n_);
run;

/*%put &source7. &target7.;*/

%macro rename();
proc datasets library=work nolist;
modify PD_CURVE;
%do i = 1 %to &nobs;
rename &&source&i. = &&target&i.;
%end;
run;
%mend rename;
%rename;

proc sql;
connect using nzrrap as nzcon;
execute(delete from &RRAP_DB..BASEL_CCAR_PD_RPTG_EXTR where RPTG_DT_TEXT=%nrbquote('&dt.')) by nzcon;
quit;

proc append base=nzrrap.BASEL_CCAR_PD_RPTG_EXTR (BULKLOAD=YES BL_METHOD=CLILOAD) data=PD_CURVE force; run;



/*---- End of User Written Code  ----*/ 

/*---- Start of User Written Code  ----*/ 


/*%let start_period_dt=31JUL2017;*/

proc sql noprint;
select tm_id into :mth_tm_id 
from nzrrap.tm_dim
where tm_lvl='Month' and tm_lvl_end_dt="&start_period_dt."d;
quit;

%put &start_period_dt &mth_tm_id;




data AUDIT_CHECK_CNFGRTN;
	set NZRRAP.AUDIT_CHECK_CNFGRTN;
	where ACTV_F = 'Y';
	if upcase(db_tp) not in ('NETEZZA','DB2') then do;
		put "THIS PROCESS HAS ABORTED!";
		put " ";
		put "Cannot process unless DB2 or Netezza is specified in the db_tp field. Please update the AUDIT_CHECK_CNFGRTN table.";
		put " ";
		put "THIS PROCESS HAS ABORTED!";
		put " ";
		abort;
	end;
	length sql_text_input $2000. dbcon $3. TMSTMP $20.;
	if upcase(db_tp)='NETEZZA' then do;
		sql_text_input=tranwrd(sql_text,"'","''");
		dbcon='NZ';
		TMSTMP='NOW()';
	end;
	else if upcase(db_tp)='DB2' then do;
	sql_text_input=tranwrd(sql_text,"'","''");
	dbcon='DB2';
	TMSTMP='CURRENT_TIMESTAMP';
	end;
/*	where AUDIT_CNFGRTN_ID=22120;*/
run;
proc sort; by AUDIT_CNFGRTN_ID; run;


/**/
proc sql;
create table WORK.AUDIT_CHECK_OUTPUT_LOG( bufsize=106496 )
  (
   LOG_ID num format=11. informat=11. label='LOG_ID',
   LOG_TP char(80) format=$80. informat=$80. label='LOG_TP',
   LOG_TBL_NM char(80) format=$80. informat=$80. label='LOG_TBL_NM',
   LOG_AUDIT_NM char(200) format=$200. informat=$200. label='LOG_AUDIT_NM',
   LOG_SQL_TEXT char(2000) format=$2000. informat=$2000. label='LOG_SQL_TXT',
   LOG_TM_ID num format=11. informat=11. label='LOG_TM_ID',
   INSRT_PROCESS_TMSTMP num format=DATETIME25.6 informat=DATETIME25.6 label='INSRT_PROCESS_TMSTMP',
   LOG_NM char(200) format=$200. informat=$200. label='LOG_NM',
   LOG_CRNT_VAL num label='LOG_CRNT_VAL',
   LOG_BASLN_VAL num label='LOG_BASLN_VAL',
   LOG_VARNC_VAL num label='LOG_VARNC_VAL',
   LOG_CMB_RSLT char(2000) format=$2000. informat=$2000. label='LOG_CMB_RSLT'
  );
quit;

data _null_;
set AUDIT_CHECK_CNFGRTN;
call execute('

		proc sql;
		connect using ' || TRIM(dbcon) || 'rrap as dbcon;
				insert into WORK.AUDIT_CHECK_OUTPUT_LOG select * from connection to dbcon 
		(

		select 
			' || trim(AUDIT_CNFGRTN_ID) || ' as LOG_ID, 
			' || "'" || TRIM(AUDIT_SUB_CLASS_CD) || "'" || ' as LOG_TP, 
			' || "'" || TRIM(ETL_NM) || "'" || ' as LOG_TBL_NM, 
			' || "'" || TRIM(AUDIT_NM) || "'" || ' as LOG_AUDIT_NM, 
			' || "'" || TRIM(SQL_TEXT_INPUT) || "'" || ' as LOG_SQL_TEXT, 
			&mth_tm_id as LOG_TM_ID,
			' ||  TRIM(TMSTMP) || ' as INSRT_PROCESS_TMSTMP
			, aa.* 
		FROM 
			('  || TRIM(SQL_TEXT)  || ') Aa

		);
		quit;


'); 
run;


proc sql noprint;
select coalesce(max(log_seq),0) , coalesce(max(btch_id),0) into :max_log_seq, :max_btch_id
from NZRRAP.AUDIT_CHECK_OUTPUT_LOG;
quit;

%put &max_btch_id;

data WORK.AUDIT_CHECK_OUTPUT_LOG;
	set WORK.AUDIT_CHECK_OUTPUT_LOG;
	LOG_SEQ= %eval(&max_log_seq) + _n_;
	BTCH_ID=%eval(&max_btch_id) + 1; 
run;
/*NO CLEAN UP NEEDED*/
/*proc sql;*/
/*connect using nzrrap as nzcon;*/
/*execute(delete from &RRAP_DB...AUDIT_CHECK_OUTPUT_LOG where log_tm_id=&mth_tm_id.) by nzcon;*/
/*quit;*/

proc append base=NZRRAP.AUDIT_CHECK_OUTPUT_LOG (BULKLOAD=YES BL_METHOD=CLILOAD) data=WORK.AUDIT_CHECK_OUTPUT_LOG force; run;




/**/

/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

