 /**************************************************************************** 
 * Job:             J_RRII_H11_003_MBR_INDRCT_COST_MTH_SNAPSHOT 			* 
 * Description:     Loads Direct Cost table                                 * 
 * Source:          MBR_SRC_CURR                                          	* 
 * Target:			MBR_INDRCT_COST_MTH_SNAPSHOT							*
 * Created on:    	Mar 20, 2020                 							* 
 * Changes:			
 ****************************************************************************/ 

DATA _NULL_;
	CALL SYMPUTX('PROCESSSTARTTIME',PUT(DATETIME(),DATETIME25.0));
RUN;

%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

X gzip &outpath./mbr/mbr*.del;
X mv &outpath./mbr/mbr*.* &outpath./mbr/history/ ;


PROC SQL NOPRINT;
       CONNECT USING NZRRAP AS NZCON;
        EXECUTE (DELETE FROM &net_db..MBR_INDRCT_COST_MTH_SNAPSHOT WHERE MTH_TM_ID = &MTH_TM_ID) BY NZCON;
QUIT;

PROC SQL NOPRINT;
	SELECT MAX(MBR_INDRCT_COST_SNAPSHOT_ID) INTO :SEQ FROM NZRRAP.MBR_INDRCT_COST_MTH_SNAPSHOT;
QUIT;

PROC SQL;
CREATE TABLE FINAL_LOAD AS 
	SELECT 
		&SEQ+1000		AS MBR_INDRCT_COST_SNAPSHOT_ID,
		&MTH_TM_ID		AS MTH_TM_ID,
		'07112' 		AS TRNST_NUM,
		SUM(MISCELLANEOUS_OUTSOURCE_FEE_AMT) AS MISCELLANEOUS_OUTSOURCE_FEE_AMT,
		SUM(TOT_NON_INTR_EXPNS_AMT) AS TOT_NON_INTR_EXPNS_AMT,
		SUM(TOT_NON_INTR_EXPNS_AMT) - SUM(MISCELLANEOUS_OUTSOURCE_FEE_AMT) - SUM(TOT_OTHER_EXPENSE) AS TOT_INDRCT_COST_AMT,
		&SESSIONTIME	AS INSRT_PROCESS_TMSTMP,
		&SESSIONTIME	AS UPDT_PROCESS_TMSTMP
	FROM
	 	(
			SELECT 
			TRIM(TRANSIT) AS TRANSIT,  
			CASE WHEN TRIM(PPLAN)='5124' THEN DECUM ELSE 0 END AS MISCELLANEOUS_OUTSOURCE_FEE_AMT,
			CASE WHEN TRIM(PPLAN)='9621' THEN DECUM ELSE 0 END AS TOT_NON_INTR_EXPNS_AMT,
			CASE WHEN TRIM(PPLAN)='5995' THEN DECUM ELSE 0 END AS TOT_OTHER_EXPENSE
			FROM
				NZRRAP.MBR_SRC_CURR
			WHERE TRIM(TRANSIT)='07112'
		);
QUIT;

data check;
set FINAL_LOAD;
if (TOT_NON_INTR_EXPNS_AMT <= 0)
	then do;
		%put 'Data Validation Failure';
		abort;
	end;
else if (TOT_INDRCT_COST_AMT >= 5000000 or TOT_INDRCT_COST_AMT <= 0)
	then do;
		%put 'Data Validation Failure. INDIRECT_COST >= 5 Million';
		abort;
	end;
run;

PROC APPEND BASE=NZRRAP.MBR_INDRCT_COST_MTH_SNAPSHOT DATA=FINAL_LOAD FORCE; RUN;


/************** JOB LOG *****************/
PROC SQL NOPRINT;
	SELECT COUNT(*) INTO :SRC_COUNT FROM NZRRAP.MBR_SRC_CURR ;
QUIT;

PROC SQL NOPRINT;
	SELECT COUNT(*) INTO :TGT_COUNT FROM NZRRAP.MBR_INDRCT_COST_MTH_SNAPSHOT WHERE MTH_TM_ID = &MTH_TM_ID;
QUIT;

DATA _NULL_;
	CALL SYMPUTX('PROCESSENDTIME',PUT(DATETIME(),DATETIME25.0));
RUN;

PROC SQL NOPRINT;
	insert into NZRRAP.AUDIT_JOB_TIMER_CHECK (JOB_NAME, MTH_TM_ID, START_TIME, END_TIME, SOURCE_COUNT, TARGET_COUNT)
		values ('J_RRII_H11_003_MBR_INDRCT_COST_MTH_SNAPSHOT', &MTH_TM_ID., "&PROCESSSTARTTIME"dt, "&PROCESSENDTIME"dt, &SRC_COUNT., &TGT_COUNT.);
QUIT;



/* JOB END */

