/**************************************************************************** 
 * Job:             RRAP_MOR_MODEL_25_BNS_MOR_LGD_D_REAL  A57SWEI7.BH0009K7 * 
 *                  IZED_LGD                                                * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/04 - Mortgage/BNS                   * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:43:33 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009K7);
%let etls_jobName = %nrquote(RRAP_MOR_MODEL_25_BNS_MOR_LGD_D_REALIZED_LGD);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Parameter default value(s) for                 */ 
/*  RRAP_MOR_MODEL_25_BNS_MOR_LGD_D_REALIZED_LGD  */ 
%let pn = ;
%let parts = ;

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_mortgage_autoexec             A57SWEI7.BK000Z6K * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z6K);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mortgage_autoexec **/

/*==========================================================================* 
 * Step:            BNS_MOR_LGD_D_REALIZED_LGD            A57SWEI7.BK000Z6L * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Target Table:    User Written - work.W2R420I           A57SWEI7.BN000NQP * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z6L);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.W2R420I;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NQP%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
%let _OUTPUT_col_count = 0;

%let _OUTPUT1 = work.W2R420I;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NQP%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
%let _OUTPUT1_col_count = 0;

/*---- Start of User Written Code  ----*/ 

/*---------------------------------------------------------------------
 * NAME:       05_bns_mor_lgd_d_realized_lgd.sas
 *
 * PURPOSE:    Calculates the realized for LGD by segment; computes 
 *             historical averages.
 *             
 * NOTES: 
 *             
 * MODIFIED:
 *    22DEC2014 - JL - Created
 *    08JAN2015 - JL - Updated with mortgage vars
 *    18NOV2015 - CV - Per CR 36 changed the logic to how the bns_mor_historical_lgd_d
								table is calculated and changed it so that it now keeps history 
 *
 * Copyright (c) 2014 by The Financial Risk Group, Cary, NC, USA.
 *---------------------------------------------------------------------*/
*%let pn=0;
options mprint mlogic symbolgen spool;
 /* EXTRACT RUN DATE FROM CONTROL TABLE */

%get_model_period_dates(product=mor);

data _null_;
	x=put(intnx('month',"&end_period_dt."d,-38,'e'),date9.);
	call symputx('start_period_dt',x);
run;

%put Start and End Dates for Mortgage Models:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;

%let _avg_start_qtr = &start_period_dt.;
%let _avg_end_qtr   = &end_period_dt.;
/*%let _avg_start_qtr = 30JUN2012;*/
/*%let _avg_end_qtr   = 31JUL2015;*/
/*-----------------------------------------------
 * Calculates the default rates by segment
 *-----------------------------------------------*/ 

%macro create_bns_lgd_nd_lgd(_in_data =, _out_data=);

   proc summary data = &_in_data nway missing;

      var acct_lgd24_nocost acct_lgd24_nocost_cap acct_lgd24_cost acct_lgd24_cost_cap15;

      /* Aggregate by observation start date and segment */
      class time_key bns_lgd_d_segment;
      output out = work.lgd_components (drop = _TYPE_ rename = (_freq_ = current_count))
      sum = acct_lgd24_nocost acct_lgd24_nocost_cap acct_lgd24_cost acct_lgd24_cost_cap15;
   run;

   proc sql noprint;
      create table &_out_data as
      select a.bns_lgd_d_segment,
             a.time_key,
             a.current_count,
             a.acct_lgd24_nocost,
             (case
               when a.current_count NE . and a.acct_lgd24_nocost NE . then a.acct_lgd24_nocost/a.current_count
               when a.current_count NE . and a.acct_lgd24_nocost EQ . then .
               when a.current_count EQ . and a.acct_lgd24_nocost NE . then .
               else .
             end) as segment_lgd24_nocost,
             a.acct_lgd24_nocost_cap,
             (case
               when a.current_count NE . and a.acct_lgd24_nocost_cap NE . then a.acct_lgd24_nocost_cap/a.current_count
               when a.current_count NE . and a.acct_lgd24_nocost_cap EQ . then .
               when a.current_count EQ . and a.acct_lgd24_nocost_cap NE . then .
               else .
             end) as segment_lgd24_nocost_cap,
             a.acct_lgd24_cost,
             (case
               when a.current_count NE . and a.acct_lgd24_cost NE . then a.acct_lgd24_cost/a.current_count
               when a.current_count NE . and a.acct_lgd24_cost EQ . then .
               when a.current_count EQ . and a.acct_lgd24_cost NE . then .
               else .
             end) as segment_lgd24_cost,
             a.acct_lgd24_cost_cap15,
             (case
               when a.current_count NE . and a.acct_lgd24_cost_cap15 NE . then a.acct_lgd24_cost_cap15/a.current_count
               when a.current_count NE . and a.acct_lgd24_cost_cap15 EQ . then .
               when a.current_count EQ . and a.acct_lgd24_cost_cap15 NE . then .
               else .
             end) as segment_lgd24_cost_cap15
      from work.lgd_components as a
      order by bns_lgd_d_segment;
   quit;

%mend create_bns_lgd_nd_lgd;
%create_bns_lgd_nd_lgd(_in_data = NZUSER.BNS_LGD_D_SCORED_SEG_ACCTS,
                            _out_data = results.bns_mor_lgd_d_realized);

/*-----------------------------------------------
 * Takes average of quarter end DRs for a given
 * segment
 *-----------------------------------------------*/ 

%macro create_avg_pds(_in_data=, _out_data=, _avg_start_qtr=, _avg_end_qtr=);

   proc summary data = &_in_data nway missing;
      where time_key GE "&_avg_start_qtr"d and time_key LE "&_avg_end_qtr"d

/* ADDED SO THAT ONLY QTR ENDS ARE USED - CV 18NOV2015*/
		and month(time_key) in (1,4,7,10);
      class bns_lgd_d_segment time_key;
      var current_count acct_lgd24_nocost acct_lgd24_nocost_cap acct_lgd24_cost acct_lgd24_cost_cap15;
      output out = work.summarized_vals (drop = _type_ _freq_)
      sum = current_count acct_lgd24_nocost acct_lgd24_nocost_cap acct_lgd24_cost acct_lgd24_cost_cap15;
   quit;

  /*Time_key added by Cam and variable prefixs changed to qtr from avg*/
   proc sql noprint;
      create table &_out_data as
      select a.bns_lgd_d_segment,
					time_key,
             (case
               when a.current_count NE . and a.acct_lgd24_nocost NE . then a.acct_lgd24_nocost/a.current_count
               when a.current_count NE . and a.acct_lgd24_nocost EQ . then .
               when a.current_count EQ . and a.acct_lgd24_nocost NE . then .
               else .
             end) as qtr_lgd24_nocost,
             (case
               when a.current_count NE . and a.acct_lgd24_nocost_cap NE . then a.acct_lgd24_nocost_cap/a.current_count
               when a.current_count NE . and a.acct_lgd24_nocost_cap EQ . then .
               when a.current_count EQ . and a.acct_lgd24_nocost_cap NE . then .
               else .
             end) as qtr_lgd24_nocost_cap,
             (case
               when a.current_count NE . and a.acct_lgd24_cost NE . then a.acct_lgd24_cost/a.current_count
               when a.current_count NE . and a.acct_lgd24_cost EQ . then .
               when a.current_count EQ . and a.acct_lgd24_cost NE . then .
               else .
             end) as qtr_ld24_cost,
             (case
               when a.current_count NE . and a.acct_lgd24_cost_cap15 NE . then a.acct_lgd24_cost_cap15/a.current_count
               when a.current_count NE . and a.acct_lgd24_cost_cap15 EQ . then .
               when a.current_count EQ . and a.acct_lgd24_cost_cap15 NE . then .
               else .
             end) as qtr_lgd24_cost_cap15
      from work.summarized_vals as a
      order by bns_lgd_d_segment, time_key;
   quit;

%mend create_avg_pds;
%create_avg_pds(_in_data = results.bns_mor_lgd_d_realized, 
                _out_data = work.qtr_averages,
                _avg_start_qtr = &_avg_start_qtr,
                _avg_end_qtr = &_avg_end_qtr);



/* Macro checks to see if data is in raw data table, and then replaces it - CV 18NOV2015*/

%macro update_raw_data;
    proc sql noprint;
       select count(*) 
       into :date_count trimmed
       from work.qtr_averages
       where time_key in (select distinct time_key from work.qtr_averages) ;
    quit;   

	
	%put Date_count is &date_count;

	  
   /*---------------------------------------------
    * If data already exists for the data being 
    * loaded, delete it from the target table
	* and insert new code
    *---------------------------------------------*/  

   %if %eval(&date_count) > 0 %then
   %do;
 
		proc sql;
			delete from nzuser.bns_lgdd_raw_historical
			where time_key in (select distinct time_key from work.qtr_averages);
            
			insert into nzuser.bns_lgdd_raw_historical
				select *
				from work.qtr_averages;
			quit;


   %end;   
   %mend;
   %update_raw_data;

/*Sorts data to be used downstream and adds start_date - CV 18NOV2015*/

proc sql;
	create table work.lgd_d_raw_hist_sorted as
		select *,
		min(time_key) as start_date format=date9.
	from nzuser.bns_lgdd_raw_historical
	order by bns_lgd_d_segment, time_key;
quit;


/* delete old bns_mor_historical_lgd_d table*/
%delete_table(results.bns_mor_historical_lgd_d);


/*  bns_mor_historical_lgd_d table is recalculated using qtr ends and with new data that was added upstream - CV 18NOV2015*/

	data results.bns_mor_historical_lgd_d (keep= bns_lgd_d_segment start_date end_date avg_lgd24_nocost avg_lgd24_nocost_cap avg_ld24_cost avg_lgd24_cost_cap15);
		set work.lgd_d_raw_hist_sorted (rename= (time_key = end_date));
		retain new_lgd24_nocost new_lgd24_nocost_cap new_ld24_cost new_lgd24_cost_cap15;
		by bns_lgd_d_segment;
		if first.bns_lgd_d_segment then do;
			counter = 0;	
			new_lgd24_nocost = 0;
			new_lgd24_nocost_cap = 0;
			new_ld24_cost = 0;
			new_lgd24_cost_cap15 = 0;
		end;
		counter + 1;		
		new_lgd24_nocost = sum(new_lgd24_nocost,qtr_lgd24_nocost);
		new_lgd24_nocost_cap = sum(new_lgd24_nocost_cap,qtr_lgd24_nocost_cap);
		new_ld24_cost = sum(new_ld24_cost,qtr_ld24_cost);
		new_lgd24_cost_cap15 = sum(new_lgd24_cost_cap15,qtr_lgd24_cost_cap15);
		
		avg_lgd24_nocost = (new_lgd24_nocost/counter);
		avg_lgd24_nocost_cap = (new_lgd24_nocost_cap/counter);
		avg_ld24_cost = (new_ld24_cost/counter);
		avg_lgd24_cost_cap15 = (new_lgd24_cost_cap15/counter);

		format end_date date9. start_date date9.;
run;
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end BNS_MOR_LGD_D_REALIZED_LGD **/

/*==========================================================================* 
 * Step:            Load to NZ                            A57SWEI7.BK000Z6M * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    User Written - work.W2R420I           A57SWEI7.BN000NQP * 
 * Target Table:    User Written - work.WFCGA6            A57SWEI7.BN000NQQ * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z6M);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.W2R420I, DATA)) or 
         %sysfunc(exist(work.W2R420I, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.W2R420I out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.W2R420I); 

%let _INPUT_count = 1;
%let _INPUT = work.W2R420I;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/User Written_A57SWEI7.BN000NQP%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT1 = work.W2R420I;
%let _INPUT1_connect = ;
%let _INPUT1_engine = ;
%let _INPUT1_memtype = DATA;
%let _INPUT1_options = %nrquote();
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NQP%(WorkTable%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote();

%let _OUTPUT_count = 1;
%let _OUTPUT = work.WFCGA6;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NQQ%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
%let _OUTPUT_col_count = 0;

%let _OUTPUT1 = work.WFCGA6;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NQQ%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
%let _OUTPUT1_col_count = 0;

/*---- Start of User Written Code  ----*/ 

%macro Gather_tables(gather_table=);
/*data results.&gather_table.;
    set results.&gather_table._0
		  results.&gather_table._1
    	  results.&gather_table._2
		  results.&gather_table._3
		  results.&gather_table._4
		  results.&gather_table._5
		  results.&gather_table._6
		  results.&gather_table._7;	
run;
*/
%delete_table(nzuser.&gather_table.);
   
data nzuser.&gather_table. (bulkload=yes BL_METHOD=CLILOAD);
     set results.&gather_table.;
run;
%mend gather_tables;
%gather_tables(gather_table=bns_mor_historical_lgd_d);
%gather_tables(gather_table=bns_mor_lgd_d_realized);


/*CR69 REQUIREMENT APRIL 6 2016*/
%MACRO CR69_HIST_MAINTAIN;

PROC SQL NOPRINT;
SELECT MAX(TIME_KEY) INTO :TGT_TIME_KEY FROM NZUSER.BNS_MOR_LGD_D_REALIZED_ANTQ; /*where TIME_KEY = '30APR2019'D*/
SELECT MAX(TIME_KEY) INTO :SRC_TIME_KEY FROM NZUSER.BNS_MOR_LGD_D_REALIZED; /*where TIME_KEY = '31MAY2019'D*/
QUIT;

%IF ("&SRC_TIME_KEY"d > "&TGT_TIME_KEY"d) %THEN %DO;
%put SIMPLE INSERT;

PROC SQL NOPRINT;
CONNECT USING NZUSER AS NZCON1;
EXECUTE(INSERT INTO &target_lib3..BNS_MOR_LGD_D_REALIZED_ANTQ 
SELECT * FROM &target_lib3..BNS_MOR_LGD_D_REALIZED WHERE 
TIME_KEY = (SELECT MAX(TIME_KEY) FROM &target_lib3..BNS_MOR_LGD_D_REALIZED )) BY NZCON1; /*removed hard coded date */
QUIT;
%END;

%IF ("&SRC_TIME_KEY"d <= "&TGT_TIME_KEY"d) %THEN %DO;
%put DELETE WILL HAPPEN;

PROC SQL NOPRINT;
CONNECT USING NZUSER AS NZCON1;
EXECUTE(DELETE FROM &target_lib3..BNS_MOR_LGD_D_REALIZED_ANTQ 
WHERE TIME_KEY = (SELECT MAX(TIME_KEY) FROM &target_lib3..BNS_MOR_LGD_D_REALIZED )) BY NZCON1; /*removed hard coded date */
QUIT;

PROC SQL NOPRINT;
CONNECT USING NZUSER AS NZCON1;
EXECUTE(INSERT INTO &target_lib3..BNS_MOR_LGD_D_REALIZED_ANTQ 
SELECT * FROM &target_lib3..BNS_MOR_LGD_D_REALIZED WHERE 
TIME_KEY = (SELECT MAX(TIME_KEY) FROM &target_lib3..BNS_MOR_LGD_D_REALIZED )) BY NZCON1; /*removed hard coded date */
QUIT;

%END;

%MEND;

%CR69_HIST_MAINTAIN;
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end Load to NZ **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

