/**************************************************************************** 
 * Job:             RRAP_MOR_MODEL_75_BNS_RPTING_NCR_BE_  A57SWEI7.BH0009KE * 
 *                  FACT_G                                                  * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/04 - Mortgage/BNS                   * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:43:07 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009KE);
%let etls_jobName = %nrquote(RRAP_MOR_MODEL_75_BNS_RPTING_NCR_BE_FACT_G);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_mortgage_autoexec             A57SWEI7.BK000Z7B * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z7B);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mortgage_autoexec **/

/*==========================================================================* 
 * Step:            User Written                          A57SWEI7.BK000Z7C * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Target Table:    User Written - work.W6N5E4I           A57SWEI7.BN000NLO * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z7C);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.W6N5E4I;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NLO%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = _ncr_be_fact_process_dt mth_tm_id;
%let _OUTPUT_col_count = 2;
%let _OUTPUT_col0_name = _ncr_be_fact_process_dt;
%let _OUTPUT_col0_table = work.W6N5E4I;
%let _OUTPUT_col0_length = 9;
%let _OUTPUT_col0_type = $;
%let _OUTPUT_col0_format = $9.;
%let _OUTPUT_col0_informat = $9.;
%let _OUTPUT_col0_label = %nrquote();
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = mth_tm_id;
%let _OUTPUT_col1_table = work.W6N5E4I;
%let _OUTPUT_col1_length = 8;
%let _OUTPUT_col1_type = ;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote();
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input_count = 0;

%let _OUTPUT1 = work.W6N5E4I;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NLO%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = _ncr_be_fact_process_dt mth_tm_id;
%let _OUTPUT1_col_count = 2;
%let _OUTPUT1_col0_name = _ncr_be_fact_process_dt;
%let _OUTPUT1_col0_table = work.W6N5E4I;
%let _OUTPUT1_col0_length = 9;
%let _OUTPUT1_col0_type = $;
%let _OUTPUT1_col0_format = $9.;
%let _OUTPUT1_col0_informat = $9.;
%let _OUTPUT1_col0_label = %nrquote();
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input_count = 0;
%let _OUTPUT1_col1_name = mth_tm_id;
%let _OUTPUT1_col1_table = work.W6N5E4I;
%let _OUTPUT1_col1_length = 8;
%let _OUTPUT1_col1_type = ;
%let _OUTPUT1_col1_format = ;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote();
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input_count = 0;

/*---- Start of User Written Code  ----*/ 

 
 
/* Multi-month run */

/*%macro dates(start_date=,end_date=);*/
/*  data &_output (keep=_ncr_be_fact_process_dt);*/
/*	  format start_date date9. end_date date9. _ncr_be_fact_process_dt $9.;*/
/*	  start_date="&start_date"d;*/
/*	  end_date="&end_date"d;*/
/*	  do i = 1 to intck('month',start_date,end_date);*/
/*	    if i = 1 then do;*/
/*		  _ncr_be_fact_process_dt=put(intnx('month',start_date,0,'end'), date9.);*/
/*		  output;*/
/*		end;*/
/*		_ncr_be_fact_process_dt=put(intnx('month',start_date,i,'end'), date9.);*/
/*		output;*/
/*	  end;*/
/*  run;*/
/*%mend;*/
/**/
/*%dates(start_date=01JUL2015, end_date=31JUL2015);  */


/* Single Month Run */

%macro dates(start_date=,end_date=);
  data _output(keep=_ncr_be_fact_process_dt);
	  format start_date date9. end_date date9. _ncr_be_fact_process_dt $9.;
	  start_date="&start_date"d;
	  end_date="&end_date"d;
		  _ncr_be_fact_process_dt=put(intnx('month',start_date,0,'end'), date9.);
		  output;
  run;
   proc sql;
		create table &_output as
		select _ncr_be_fact_process_dt, b.tm_id as mth_tm_id
		from _output a, nzuser.tm_dim b
		where b.tm_lvl='Month' and b.tm_lvl_end_dt=input(_ncr_be_fact_process_dt,date9.);
	quit;
%mend;

%get_model_period_dates(product=mor);
%put Start and End Dates for Mortgage Models:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;

%dates(start_date=&start_period_dt., end_date=&end_period_dt.);
/*%dates(start_date=31JUL2015, end_date=31JUL2015);*/



/* New date code that keeps quarter ends for backtesting */
/* Current logic also keeps year=2015 in order to grab Feb/Mar of 2015 */
/**/
/*%macro dates(start_date=,end_date=);*/
/*  data all_dates (keep=_ncr_be_fact_process_dt _ncr_be_fact_process_date );*/
/*	  format start_date date9. end_date date9. _ncr_be_fact_process_dt $9. _ncr_be_fact_process_date date9. ;*/
/*	  start_date="&start_date"d;*/
/*	  end_date="&end_date"d;*/
/*	  do i = 1 to intck('month',start_date,end_date);*/
/*	    if i = 1 then do;*/
/*		  _ncr_be_fact_process_dt=put(intnx('month',start_date,0,'end'), date9.);*/
/*		  _ncr_be_fact_process_date=intnx('month',start_date,0,'end'); */
/*		  output;*/
/*		end;*/
/*		_ncr_be_fact_process_dt=put(intnx('month',start_date,i,'end'), date9.);*/
/*		_ncr_be_fact_process_date=intnx('month',start_date,i,'end'); */
/*		output;*/
/*	  end;*/
/*  run;*/
/*%mend;*/
/**/
/*%dates(start_date=01JAN2014, end_date=30APR2015);  */
/**/

* Keep quarters for backtesting and Feb/Mar 2015 for current Q2 run;
/*data &_output;*/
/*keep _ncr_be_fact_process_dt;*/
/*set all_dates;*/
/*month=month(_ncr_be_fact_process_date);*/
/*year=year(_ncr_be_fact_process_date);*/
/*if month in (1, 4, 7, 10) or year=2015;*/
/*run;*/





proc sql ;
/*   connect to netezza as nzcon (server=cs2iwntzp01 database=frg_user_data user = &_userid_nz password = &_pwd_nz);*/
		connect using nzuser as nzcon;
	   *execute (truncate table &FRG_DB..basel_RPT_BL_AGG_NCR_BE_FACT_bns) by nzcon;
	   execute (truncate table &FRG_DB..basel_RPT_BL_AGG_NCR_BE_FACT_bns IMMEDIATE) by nzcon;
	disconnect from nzcon;
quit;



/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end User Written **/

/*==========================================================================* 
 * Step:            Loop                                  A57SWEI7.BK000Z7D * 
 * Transform:       Loop                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    User Written - work.W6N5E4I           A57SWEI7.BN000NLO * 
 * Target Table:    Loop - work.W6NDUUE                   A57SWEI7.BN000NLP * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z7D);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.W6N5E4I, DATA)) or 
         %sysfunc(exist(work.W6N5E4I, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.W6N5E4I out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.W6N5E4I); 

/* Capture summary statistics about this step for performance reporting  */ 
%put "DIS_SUMM";
%macro etls_getHandle(statusTable=, handleVariable=, row=); 
   %let etls_dsid = %sysfunc(open(&statusTable)); 
   %if (&etls_dsid = 0) %then 
      %put %sysfunc(sysmsg()); 
   %else 
   %do; 
      %let rc = %sysfunc(fetchobs(&etls_dsid, &row)); 
      %if (&rc ne 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %let etls_varnum = %sysfunc(varnum(&etls_dsid,&handleVariable)); 
         %if (&etls_varnum > 0) %then 
            %sysfunc(getvarc(&etls_dsid,&etls_varnum)); 
         %else 
            %put %sysfunc(sysmsg()); 
      %end; 
      %let rc = %sysfunc(close(&etls_dsid)); 
   %end; 
%mend etls_getHandle; 

%macro etls_freeHandle(statusTable=, statusVariable=, handleVariable=, 
   handleName=, statusSetting="Finished", 
   endTimeVariable=endTime, startTimeVariable=startTime, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, setMainJobRC=1, 
   statusUnknownReturnCode=., startTimeMacroVariable=, endTimeMacroVariable= ); 

   %if (&statusTable ne ) %then 
   %do; 
      %local etls_rcMacroVarExisted; 
      %let etls_rcMacroVarExisted = 0; 
      %if ("&returnCodeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_rcMacroVarExisted from dictionary.macros 
            where name=upcase("&returnCodeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_rcMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Return code from inner job not found.  Setting status to Unknown.;
            %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
         %end; 
         %if (&setMainJobRC eq 1) %then 
            %rcSet(&&&returnCodeMacroVariable); 
      %end; 
      %else 
      %do; 
         %let returnCodeMacroVariable=etls_rcmacvar; 
         %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
      %end; 

      %local etls_startTimeMacroVarExisted; 
      %let etls_startTimeMacroVarExisted = 0; 
      %if ("&startTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_startTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&startTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_startTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Start time from inner job not found.  No value will be set.;
            %let &startTimeMacroVariable=; 
         %end; 
      %end; 

      %local etls_endTimeMacroVarExisted; 
      %let etls_endTimeMacroVarExisted = 0; 
      %if ("&endTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_endTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&endTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_endTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) End time from inner job not found.  Setting end time to current
      time.;
            %let &endTimeMacroVariable=%sysfunc(datetime()); 
         %end; 
      %end; 

      data &statusTable; 
         modify &statusTable(where=(&handleVariable = &handleName)); 
         %if ("&startTimeMacroVariable" ne "") %then 
         %do; 
            &startTimeVariable = input(symget("&startTimeMacroVariable"),32.);; 
         %end; 
         %if ("&endTimeVariable" ne "") %then 
         %do; 
            %if ("&endTimeMacroVariable" ne "") %then 
            %do; 
               &endTimeVariable = input(symget("&endTimeMacroVariable"),32.);; 
            %end; 
            %else 
               &endTimeVariable = datetime();; 
         %end; 
         %if ("&returnCodeVariable" ne "") %then 
            &returnCodeVariable = input(symget("&returnCodeMacroVariable"),32.);; 
         %if ("&statusVariable" ne "") %then 
         %do; 
            if (symget("etls_rcMacroVarExisted") eq "0") then 
               &statusVariable = "Unknown Status"; 
            else
               &statusVariable = &statusSetting;
         %end;
         call symput('handle',&handleVariable); 
         replace; 
         stop; 
      run; 

      %rcSet(&syserr); 

      %if (&signoff eq 1) %then 
         %etls_signoff(handleName=&handle); 
   %end; 
%mend etls_freeHandle; 

%macro etls_createHandle(statusTable=,
                         statusVariable=,
                         handleVariable=,
                         handlePrefix=rmt,
                         gridOptionSet=,
                         workloadMacroVariable=,
                         row=,
                         machineVariable=,
                         statusSetting="Running", 
                         startTimeVariable=startTime,
                         signon=1,
                         useGrid=1,
                         log=,
                         output=,
                         gridRC=,
                         cmacvar=etls_signonStatus,
                         additionalSignonOptions=,
                         signonRetries= ); 

   %local remoteSessionId; 
   %let remoteSessionId = &handlePrefix.&row; 
   %let &cmacvar = 1; 
   %local etls_machineId; 
   %if (&signon eq 1) %then 

      %etls_signon(handleName=&remoteSessionId,
                   useGrid=&useGrid,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=&etls_gridOptionSet,
                   workloadMacroVariable=&workloadMacroVariable,
                   log=&log,
                   output=&output,
                   cmacvar=&cmacvar,
                   gridRC=&gridRC,
                   additionalSignonOptions=&additionalSignonOptions,
					signonRetries=&signonRetries,
                   gridJobName=DIS_&etls_jobName._&row); 

   %else %let &cmacvar=0; 

   data &statusTable; 
      retain ptr &row; 
      modify &statusTable point = ptr; 
      &handleVariable = "&remoteSessionId"; 
      %if (&signon eq 1) %then 
         &machineVariable = "&etls_machineId";; 
      %if (&&&cmacvar ne 0) %then 
      %do; 
         &statusVariable = "Failed Signon"; 
      %end; 
      %else 
         &statusVariable = &statusSetting;; 
      %if (&startTimeVariable ne ) %then 
         &startTimeVariable = datetime();; 
      replace; 
      stop; 
   run; 

   %rcSet(&syserr); 
%mend etls_createHandle; 

%macro etls_getParameterNames(parameterTable=, parameterVariableMacro=, startingColumnNumber=1);
   %let &parameterVariableMacro = ;
   %let dsid = %sysfunc(open(&parameterTable));
   %if (&dsid gt 0) %then 
   %do; 
      %do i=&startingColumnNumber %to %sysfunc(attrn(&dsid,nvars)); 
         %let &parameterVariableMacro = &&&parameterVariableMacro %sysfunc(varname(&dsid,&i)); 
      %end; 
      %let dsid = %sysfunc(close(&dsid)); 
   %end; 
   %else 
      %put %sysfunc(sysmsg()); 
   %rcSet(&syserr); 
%mend etls_getParameterNames; 

%macro etls_getParameters(parameterTable=, row=, startingColumnNumber=1 , handleName=); 
   data _null_; 
      length vname $256 vtype $1 value $32767; 
      dsid = open("&parameterTable"); 
      if (dsid > 0) then 
      do; 
         do _i = 1 to &row; 
            fetchrc = fetch(dsid); 
         end; 
         do _i=&startingColumnNumber to attrn(dsid,'nvars'); 
            vname = varname(dsid,_i); 
            vtype = vartype(dsid,_i); 
            if (fetchrc = 0) then 
            do; 
               if (vtype = 'C') then 
               do; 
                  value = getvarc(dsid,_i); 
                  value = tranwrd(value,"%","%%"); 
                  value = tranwrd(value,"(","%("); 
                  value = tranwrd(value,")","%)"); 
                  value = tranwrd(value,'"','%"'); 
                  value = tranwrd(value,"'","%'"); 
               end; 
               else 
                  value = left(put(getvarn(dsid,_i),best32.)); 
            end; /* fetchrc = 0 */ 
            
            put ;
            if indexc(trimn(value),"+-*/<>=^~;, '()&%",'"')>0 then 
            do; 
               value='%nrstr('||trim(value)||')'; 
               put "ETLS_DIAG%QUOTE(:) Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
               put "NOTE: Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
            end; 
            %if %str(&handlename) ne %str() %then 
            %do; 
               value = '%syslput '||trim(vname)||'= '||trim(value)||" / remote = &handleName;"; 
            %end; 
            %else 
            %do; 
               value = '%let '||trim(vname)||'= '||trim(value)||';'; 
            %end; 
            
            put "NOTE: Setting macro variable " vname "with statement:" value ;
            call execute(value); 
         end; /* do i= */ 
         dsid = close(dsid); 
      end; /* dsid > 0 */ 
      else 
      do; 
         put "ERROR%QUOTE(:) Parameter table, &parameterTable., could not be"
              " opened.";
         abort; 
      end; 
      stop; 
   run; 
   
   %rcSet(&syserr); 
%mend etls_getParameters; 

%macro etls_loopW2HGPXT; 
   %local etls_filePrefix; 
   %let etls_filePrefix = ; 
   
   %macro etls_processToLoopW2HGPY3(parameterTable=, row=, handleName=rmt);
      %local etls_parmvars; 
      %etls_getParameterNames(parameterTable=&parameterTable, 
         parameterVariableMacro=etls_parmvars, 
         startingColumnNumber=1); 
      %local &etls_parmvars; 
      %etls_getParameters(parameterTable=&parameterTable, row=&row, 
         startingColumnNumber=1); 
      %let etls_previousFilePrefix = &etls_filePrefix;
      %local etls_filePrefix; 
      %let etls_filePrefix = &etls_previousFilePrefix.&handleName; 
      %macro etls_jobW2HGPYE; 
      
         /**************************************************************************** 
          * Job:             RRAP_MOR_MODEL_75_BNS_RPTING_NCR_BE_  A57SWEI7.BH0009JG * 
          *                  FACT                                                    * 
          * Description:                                                             * 
          *                                                                          * 
          * Metadata Server: 10.56.70.48                                             * 
          * Port:            8561                                                    * 
          * Location:        /Projects/RRAP/Jobs/04 - Mortgage/BNS/Inner Jobs        * 
          *                                                                          * 
          * Server:          SASApp                                A57SWEI7.AT000002 * 
          *                                                                          * 
          * Generated on:    Thursday, June 29, 2017 2:43:07 PM EDT                  * 
          * Generated by:    owprdsas                                                * 
          * Version:         SAS Data Integration Studio 4.8                         * 
          ****************************************************************************/ 
         
         /* Generate the process id for job  */ 
         %put Process ID: &SYSJOBID;
         
         /* General macro variables  */ 
         %let jobID = %quote(A57SWEI7.BH0009JG);
         %let etls_jobName = %nrquote(RRAP_MOR_MODEL_75_BNS_RPTING_NCR_BE_FACT);
         %let etls_userID = %nrquote(owprdsas);
         
         
         /* Create metadata macro variables */
         %let IOMServer      = %nrquote(SASApp);
         %let metaPort       = %nrquote(8561);
         %let metaServer     = %nrquote(iw503);
         
         /* Set metadata options */
         options metaport       = &metaPort 
                 metaserver     = "&metaServer"; 
         
         /* Setup for capturing job status  */ 
         %let etls_startTime = %sysfunc(datetime(),datetime.);
         %let etls_recordsBefore = 0;
         %let etls_recordsAfter = 0;
         %let etls_lib = 0;
         %let etls_table = 0;
         
         %global etls_debug; 
         %macro etls_setDebug; 
            %if %str(&etls_debug) ne 0 %then 
               OPTIONS MPRINT%str(;); 
         %mend; 
         %etls_setDebug; 
         
         /*==========================================================================* 
          * Step:            User Written                          A57SWEI7.BK000Z3X * 
          * Transform:       User Written                                            * 
          * Description:                                                             * 
          *                                                                          * 
          * Target Table:    User Written - work.W4Z13Y3           A57SWEI7.BN000NQ7 * 
          *                                                                          * 
          * User Written:    SourceCode                                              * 
          *==========================================================================*
          *                                                                          * 
          * Nothing will be generated for this process because the "Exclude          * 
          *  transformation from run" option is selected.                            * 
          *                                                                          * 
          *==========================================================================*/ 
         
         /*==========================================================================* 
          * Step:            User Written                          A57SWEI7.BK000Z3Y * 
          * Transform:       User Written                                            * 
          * Description:                                                             * 
          *                                                                          * 
          * Target Table:    User Written - work.WL7HPR            A57SWEI7.BN000NQ8 * 
          *                                                                          * 
          * User Written:    SourceCode                                              * 
          *==========================================================================*/ 
         
         %let transformID = %quote(A57SWEI7.BK000Z3Y);
         %let trans_rc = 0;
         %let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 
         
         %let _INPUT_count = 0;
         %let _OUTPUT_count = 1;
         %let _OUTPUT = work.WL7HPR;
         %let _OUTPUT_connect = ;
         %let _OUTPUT_engine = ;
         %let _OUTPUT_memtype = DATA;
         %let _OUTPUT_options = %nrquote();
         %let _OUTPUT_alter = %nrquote();
         %let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NQ8%(WorkTable%));
         %let _OUTPUT_type = 1;
         %let _OUTPUT_label = %nrquote();
         %let _OUTPUT_col_count = 0;
         
         %let _OUTPUT1 = work.WL7HPR;
         %let _OUTPUT1_connect = ;
         %let _OUTPUT1_engine = ;
         %let _OUTPUT1_memtype = DATA;
         %let _OUTPUT1_options = %nrquote();
         %let _OUTPUT1_alter = %nrquote();
         %let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NQ8%(WorkTable%));
         %let _OUTPUT1_type = 1;
         %let _OUTPUT1_label = %nrquote();
         %let _OUTPUT1_col_count = 0;
         
         /*---- Start of User Written Code  ----*/ 
         
         /* NAME:       07_bns_rpting_ncr_be_fact.sas
          *
          * PURPOSE:    Pulls together the data needed to feed into the reporting
          *             table BASEL_RPTG_BL_AGGRTD_NCR_BE_FACT
          *             
          * NOTES:    
          *             1. This needs to be run on a monthly basis because the 
          *                1 year and 3 year historical months will change each
          *                month. 
          *             
          * MODIFIED:
          *    20JAN2015 - JL - Created
          *    24JAN2015 - JL - Changed variable creation, input table
          *    28JAN2015 - JL - Added EAD calcs
          *    01FEB2015 - JL - Revamped logic and changed join criteria
          *
          * Copyright (c) 2014 by The Financial Risk Group, Cary, NC, USA.
          *---------------------------------------------------------------------*/
         
         %let _int_tbl_for_be = &target_lib3..history_tbl_for_bd_be_fact_bns;
         /*%let _ncr_be_fact_process_dt = 31OCT2014;*/
         
         /* These dates are used to query history from tables */
         data _null_;
            call symput('run_date', cats(put(intnx('month', "&_ncr_be_fact_process_dt"d, 0, 'e'), yymmdd10.)));
            call symput('run_date_yymth', cats(put(intnx('month', "&_ncr_be_fact_process_dt"d, 0, 'e'), yymmn.))); 
            call symput('pd_obs_dt', cats(put(intnx('month', "&_ncr_be_fact_process_dt"d, -12, 'e'), yymmdd10.)));
            call symput('lgd_obs_dt', cats(put(intnx('month', "&_ncr_be_fact_process_dt"d, -36, 'e'), yymmdd10.)));
            call symput('ead_obs_dt', cats(put(intnx('month', "&_ncr_be_fact_process_dt"d, -12, 'e'), yymmdd10.)));
         run;
         %put run_date = &run_date;
         %put run_date_yymth = &run_date_yymth;
         %put pd_obs_dt = &pd_obs_dt;
         %put lgd_obs_dt = &lgd_obs_dt;
         %put ead_obs_dt = &ead_obs_dt;
         /*---------------------------------------------------
          * 1. Gets a table of distinct values. This will
          *    define the aggregations available
          *---------------------------------------------------*/
         proc sql noprint;
            connect USING NZUSER as nzcon ;
            /* Pass through run */
            create table work.distinct_groupings1 as 
            select * from connection to nzcon (	
            select 
            	      distinct a.mth_tm_id,
                            a.ncr_expsr_cl_key_val,
                            a.ncr_rt_sys_key_val,
                            a.ncr_pd_seg_key_val,
                            a.ncr_lgd_seg_key_val,
                            a.ncr_ead_seg_key_val,
                            a.src_sys_cd
            from &_int_tbl_for_be as a
            where last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&run_date')) 
         
         /*   where intnx('month', datepart(a.process_date), 0, 'e') = "&_ncr_be_fact_process_dt"D */
         );
         disconnect from nzcon;
         quit;
         
         /*---------------------------------------------------
          * 2. Defines processing period values 
          *---------------------------------------------------*/
         proc sql noprint;
            connect USING NZUSER as nzcon ;
            /* Pass through run */
            create table work._processing_dt_vals as 
            select * from connection to nzcon (	
            
         
            /*---------------------------------------------------
             * Can't include dates because join condition is for
             * current distibution and dates will not agree to
             * process date
             *---------------------------------------------------*/
            select a.ncr_expsr_cl_key_val,
                   a.ncr_rt_sys_key_val,
                   a.ncr_pd_seg_key_val,
                   a.ncr_lgd_seg_key_val,
                   a.ncr_ead_seg_key_val,
                   a.src_sys_cd,
         
                   /* Processing period values */
                   count(*) as rptg_qtr_acct_cnt /*format = 28.8*/, 
                   avg(a.pd_final_rptg_rto) as pd_final_rptg_rto /*format = 28.8*/,
                   avg(a.dlgd_rptg_rto) as lgd_final_rptg_rto /*format = 28.8*/
                 
            from &_int_tbl_for_be as a
            where last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&run_date')) 
         /*   where intnx('month', datepart(a.process_date), 0, 'e') = "&_ncr_be_fact_process_dt"d*/
            group by a.ncr_expsr_cl_key_val, 
                     a.ncr_rt_sys_key_val,
                     a.ncr_pd_seg_key_val,
                     a.ncr_lgd_seg_key_val, 
                     a.ncr_ead_seg_key_val, 
                     a.src_sys_cd
            order by a.ncr_expsr_cl_key_val, 
                     a.ncr_rt_sys_key_val,
                     a.ncr_pd_seg_key_val,
                     a.ncr_lgd_seg_key_val, 
                     a.ncr_ead_seg_key_val, 
                     a.src_sys_cd
         			);
         			disconnect from nzcon;
         quit;
         
         /*---------------------------------------------------
          * 3. Defines observation period values for PD
          * History:
          * 21Feb2015 - JD - Updating where clause to use pd_obs_dt instead of run_date
          *                  to look back 12 months instead of using current month
          *---------------------------------------------------*/
         proc sql noprint;
            connect USING NZUSER as nzcon ;
            create table work._pd_obs_counts as 
            select * from connection to nzcon (
            select a.ncr_expsr_cl_key_val,
                   a.ncr_rt_sys_key_val,
                   a.ncr_pd_seg_key_val,
                   a.ncr_lgd_seg_key_val,
                   a.ncr_ead_seg_key_val,
                   a.src_sys_cd,
         
                   /* For 12 month realized PD */
                   a.pit_stat_cd,
                   count(*) as count,
                   sum(a.default_ind) as def_ind_cnt,
         
                   sum(
                     (case 
                        when upper(a.pit_stat_cd) = 'CUR' and a.default_ind = 1 and a.default_bal >= 0 then a.default_bal
                        when upper(a.pit_stat_cd) = 'CUR' and a.default_ind = 1 and a.default_bal < 0 then 0
                        when upper(a.pit_stat_cd) = 'CUR' and a.default_ind = 0 then 0
         				/* jd 21FEB2015 Code added to add os_bal_Amt to the DEF case */
         				/* ff 22FEB2015 Code added to add intr_accr_amt to the DEF case */		
            				when upper(a.pit_stat_cd) = 'DEF' and a.os_bal_amt is not null and a.intr_accr_amt is not null then a.os_bal_amt + a.intr_accr_amt
                        when upper(a.pit_stat_cd) = 'DEF' and a.os_bal_amt is not null and a.intr_accr_amt is null then a.os_bal_amt 
                        else null
                        end)
                     ) as pr_12_m_rlz_def_ln_os_pd_bal_am 
                 
            from &_int_tbl_for_be as a
         	  where last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&pd_obs_dt')) 
               /*   where intnx('month', datepart(a.process_date), 0, 'e') = "&_ncr_be_fact_process_dt"d*/
            group by a.ncr_expsr_cl_key_val, 
                     a.ncr_rt_sys_key_val,
                     a.ncr_pd_seg_key_val,
                     a.ncr_lgd_seg_key_val, 
                     a.ncr_ead_seg_key_val, 
                     a.src_sys_cd,
                     a.pit_stat_cd
            order by a.ncr_expsr_cl_key_val, 
                     a.ncr_rt_sys_key_val,
                     a.ncr_pd_seg_key_val,
                     a.ncr_lgd_seg_key_val, 
                     a.ncr_ead_seg_key_val, 
                     a.src_sys_cd,
                     a.pit_stat_cd
         			);
         	disconnect from nzcon;
         quit;
         
         
         
         data work._pd_obs_metrics (drop = pit_stat_cd count def_ind_cnt);
            set work._pd_obs_counts;
         
            if upcase(pit_stat_cd) = 'CUR' then 
            do;
               prior_12_mth_realz_pd_acct_cnt = count;
               pr_12_m_realz_pd_def_acct_cnt = def_ind_cnt;
               prior_12_mth_realz_pd_rto = pr_12_m_realz_pd_def_acct_cnt/prior_12_mth_realz_pd_acct_cnt;
            end;
         
            else if upcase(pit_stat_cd) = 'DEF' then 
            do;
               prior_12_mth_realz_pd_acct_cnt = 0;
               pr_12_m_realz_pd_def_acct_cnt = count;
               prior_12_mth_realz_pd_rto = 1;
            end;
         
         run;
         
         
          
         
            
         
         /*---------------------------------------------------
          * 4. Defines observation period values for LGD
          *---------------------------------------------------*/
         proc sql noprint;
            connect USING NZUSER as nzcon ;
            create table work._lgd_obs_counts_bals as 
            select * from connection to nzcon (
           
            select a.ncr_expsr_cl_key_val,
                   a.ncr_rt_sys_key_val,
                   a.ncr_pd_seg_key_val,
                   a.ncr_lgd_seg_key_val,
                   a.ncr_ead_seg_key_val,
                   a.src_sys_cd,
         
                   /* For 36 month realized LGD - per workbook, same logic*/
                   count(*) as prior_36_mth_realz_lgd_acct_cnt, /* format 17.3 */
                   count(*) as pr_36_m_realz_lgd_def_acct_cnt,  /* format 17.3 */
         
                   a.pit_stat_cd,
                   sum(
                     (case 
                        when upper(a.pit_stat_cd) = 'CUR' and a.default_ind = 1 and a.default_bal >= 0 then a.default_bal
                        when upper(a.pit_stat_cd) = 'CUR' and a.default_ind = 1 and a.default_bal < 0 then 0
                        when upper(a.pit_stat_cd) = 'CUR' and a.default_ind = 0 then 0
         				/* jd 21FEB2015 Code added to add os_bal_Amt to the DEF case */
         				/* ff 22FEB2015 Code added to add intr_accr_amt to the DEF case */		
                        when upper(a.pit_stat_cd) = 'DEF' and a.os_bal_amt is not null and a.intr_accr_amt is not null then a.os_bal_amt + a.intr_accr_amt
                        when upper(a.pit_stat_cd) = 'DEF' and a.os_bal_amt is not null and a.intr_accr_amt is null then a.os_bal_amt 
                        else null
                        end)
                     ) as pr_36_m_rlz_def_ln_os_lgd_bal_am  /* format = 17.3 */
                 
            from &_int_tbl_for_be as a
            where last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&lgd_obs_dt')) 
           /*   ff 24FEB2015 Changed below from lgd_final_rptg_rto to lgd_model_rto
                and  a.lgd_model_rto is not NULL
         		 and  a.lgd_model_rto <> 0
           */
           /*   jd 25FEB2015 Changing logic to use default_ind and pit_stat_cd      */
                and (a.default_ind=1 or upper(a.pit_stat_cd)='DEF')
                and  a.lgd_model_rto is not NULL
         		 and  a.lgd_model_rto <> 0
            group by a.ncr_expsr_cl_key_val, 
                     a.ncr_rt_sys_key_val,
                     a.ncr_pd_seg_key_val,
                     a.ncr_lgd_seg_key_val, 
                     a.ncr_ead_seg_key_val, 
                     a.src_sys_cd,
                     a.pit_Stat_cd   /*ff added due to error 21FEB15 */
         );
         disconnect from nzcon;
         quit;
         
         
         /*----------------------------------------------------
          * Needs to be separate query because average of ratio
          * is over all accounts in a segment
          *
          * History:
          * 07Mar2015 - JD - Updating calcuatiion of PRIOR_36_MTH_REALZ_LGD_RTO to use lgd_model_rto
          *                  instead of lgd_final_rptg_rto
          *----------------------------------------------------*/
         proc sql noprint;
            connect USING NZUSER as nzcon ;
            create table work._lgd_obs_realized as  
            select * from connection to nzcon (   
         
            select a.ncr_expsr_cl_key_val,
                   a.ncr_rt_sys_key_val,
                   a.ncr_pd_seg_key_val,
                   a.ncr_lgd_seg_key_val,
                   a.ncr_ead_seg_key_val,
                   a.src_sys_cd,
                   avg(a.lgd_model_rto) as prior_36_mth_realz_lgd_rto /*format 28.8*/
                 
            from &_int_tbl_for_be as a
            where last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&lgd_obs_dt')) 
         /*   where intnx('month', datepart(a.process_date), 0, 'e') = "&lgd_obs_dt"d*/
            group by a.ncr_expsr_cl_key_val, 
                     a.ncr_rt_sys_key_val,
                     a.ncr_pd_seg_key_val,
                     a.ncr_lgd_seg_key_val, 
                     a.ncr_ead_seg_key_val, 
                     a.src_sys_cd
         );
         disconnect from nzcon;
         quit;
         
         
          
         
         /*---------------------------------------------------
          * 5. Defines observation period values for EAD
          *---------------------------------------------------*/
         proc sql noprint;
            connect USING NZUSER as nzcon ;
             create table work._ead_obs_counts as 
            select * from connection to nzcon (
               select a.ncr_expsr_cl_key_val,
                   a.ncr_rt_sys_key_val,
                   a.ncr_pd_seg_key_val,
                   a.ncr_lgd_seg_key_val,
                   a.ncr_ead_seg_key_val,
                   a.src_sys_cd,
         
                   /* For 12 month realized EAD */
                   sum(
                     (case 
                        when upper(a.pit_stat_cd) = 'DEF' then 0
                        when upper(a.pit_stat_cd) = 'CUR' and default_ind = 1 then 1
                        else null
                        end)
                   ) as prior_12_mth_realz_ead_acct_cnt
                 
            from &_int_tbl_for_be as a
             where last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&ead_obs_dt')) 
             group by a.ncr_expsr_cl_key_val, 
                     a.ncr_rt_sys_key_val,
                     a.ncr_pd_seg_key_val,
                     a.ncr_lgd_seg_key_val, 
                     a.ncr_ead_seg_key_val, 
                     a.src_sys_cd
         	); disconnect from nzcon;
         quit;
         
          
         
         /*---------------------------------------------------
          * 6. Join results together - for ONE month only
          *---------------------------------------------------*/
         proc sql noprint;
            create table work.base_with_process as
            select a.mth_tm_id,
                   a.ncr_expsr_cl_key_val,
                   a.ncr_rt_sys_key_val,
                   a.ncr_pd_seg_key_val,
                   a.ncr_lgd_seg_key_val,
                   a.ncr_ead_seg_key_val,
                   a.src_sys_cd,
         
                   /* Process date values */
                   b.rptg_qtr_acct_cnt,
                   b.pd_final_rptg_rto, 
                   b.lgd_final_rptg_rto,
         
                   c.prior_12_mth_realz_ead_acct_cnt,
                   (case 
                     when b.rptg_qtr_acct_cnt > 0 then 1
                     else 0
                     end) as ead_final_rptg_rto format=28.8,
                   (case
                     when a.ncr_ead_seg_key_val = '3308' then 1
                     when c.prior_12_mth_realz_ead_acct_cnt > 0 then 1
                     else 0
                     end) as prior_12_mth_realz_ead_rto format=28.8,
                    0 as pr_12_m_realz_ead_def_acct_cnt,
                    0 as pr_12_m_rlz_def_ln_os_ead_bal_am format=17.3
         
            from work.distinct_groupings1 as a
                 left join
         
                  /* Adds Process date metrics */
                 work._processing_dt_vals as b
                 on (a.ncr_expsr_cl_key_val = b.ncr_expsr_cl_key_val and
                     a.ncr_rt_sys_key_val = b.ncr_rt_sys_key_val and
                     a.ncr_pd_seg_key_val = b.ncr_pd_seg_key_val and
                     a.ncr_lgd_seg_key_val = b.ncr_lgd_seg_key_val and
                     a.ncr_ead_seg_key_val = b.ncr_ead_seg_key_val and
                     a.src_sys_cd = b.src_sys_cd)
         
                 left join
         
                 /* Adds EAD observation metrics */
                 work._ead_obs_counts as c
                 on (a.ncr_expsr_cl_key_val = c.ncr_expsr_cl_key_val and
                     a.ncr_rt_sys_key_val = c.ncr_rt_sys_key_val and
                     a.ncr_pd_seg_key_val = c.ncr_pd_seg_key_val and
                     a.ncr_lgd_seg_key_val = c.ncr_lgd_seg_key_val and
                     a.ncr_ead_seg_key_val = c.ncr_ead_seg_key_val and
                     a.src_sys_cd = c.src_sys_cd);
         quit;
          
            
         proc sql noprint;
            create table work.base_with_pd as
            select a.*,
         
                   /* PD at obs*/
                   b.pr_12_m_realz_pd_def_acct_cnt,
                   b.prior_12_mth_realz_pd_acct_cnt,
                   b.prior_12_mth_realz_pd_rto format = 28.8,
                   b.pr_12_m_rlz_def_ln_os_pd_bal_am format = 17.3
         
            from work.base_with_process as a
                 left join
         
                 /* Adds PD observation metrics */
                 work._pd_obs_metrics as b
                 on (a.ncr_expsr_cl_key_val = b.ncr_expsr_cl_key_val and
                     a.ncr_rt_sys_key_val = b.ncr_rt_sys_key_val and
                     a.ncr_pd_seg_key_val = b.ncr_pd_seg_key_val and
                     a.ncr_lgd_seg_key_val = b.ncr_lgd_seg_key_val and
                     a.ncr_ead_seg_key_val = b.ncr_ead_seg_key_val and
                     a.src_sys_cd = b.src_sys_cd);
         quit;
         
           
         proc sql noprint;
            create table work.base_with_lgd as
            select a.*,
         
                   /* LGD at obs */
                   b.prior_36_mth_realz_lgd_acct_cnt,
                   b.pr_36_m_realz_lgd_def_acct_cnt,
                   c.prior_36_mth_realz_lgd_rto format = 28.8,
                   b.pr_36_m_rlz_def_ln_os_lgd_bal_am 
         
            from work.base_with_pd as a
                 left join
         
                 /* Adds LGD observation counts */
                 work._lgd_obs_counts_bals as b
                 on (a.ncr_expsr_cl_key_val = b.ncr_expsr_cl_key_val and
                     a.ncr_rt_sys_key_val = b.ncr_rt_sys_key_val and
                     a.ncr_pd_seg_key_val = b.ncr_pd_seg_key_val and
                     a.ncr_lgd_seg_key_val = b.ncr_lgd_seg_key_val and
                     a.ncr_ead_seg_key_val = b.ncr_ead_seg_key_val and
                     a.src_sys_cd = b.src_sys_cd)
         
                 left join
         
                 /* Adds LGD observation realized value */
                 work._lgd_obs_realized as c
                 on (a.ncr_expsr_cl_key_val = c.ncr_expsr_cl_key_val and
                     a.ncr_rt_sys_key_val = c.ncr_rt_sys_key_val and
                     a.ncr_pd_seg_key_val = c.ncr_pd_seg_key_val and
                     a.ncr_lgd_seg_key_val = c.ncr_lgd_seg_key_val and
                     a.ncr_ead_seg_key_val = c.ncr_ead_seg_key_val and
                     a.src_sys_cd = c.src_sys_cd);
         quit; 
         
         /*----------------------------------------------------
          * 6. Load to final table
          *----------------------------------------------------*/
         proc sql noprint;
            insert into nzuser.basel_rpt_bl_agg_ncr_be_fact_bns (bulkload=yes BL_METHOD=CLILOAD)
            select a.mth_tm_id,
                  a.ncr_expsr_cl_key_val,
                  a.ncr_rt_sys_key_val,
                  a.ncr_pd_seg_key_val,
                  a.src_sys_cd,
                  a.ncr_lgd_seg_key_val,
                  a.prior_12_mth_realz_pd_acct_cnt,
                  a.ncr_ead_seg_key_val,
                  a.prior_36_mth_realz_lgd_acct_cnt,
                  a.prior_12_mth_realz_ead_acct_cnt,
                  a.rptg_qtr_acct_cnt,
                  a.pd_final_rptg_rto,
                  a.lgd_final_rptg_rto,
                  a.ead_final_rptg_rto,
                  a.prior_12_mth_realz_pd_rto,
                  a.prior_36_mth_realz_lgd_rto,
                  a.prior_12_mth_realz_ead_rto,
                  a.pr_12_m_realz_pd_def_acct_cnt,
                  a.pr_36_m_realz_lgd_def_acct_cnt,
                  a.pr_12_m_realz_ead_def_acct_cnt,
                  a.pr_12_m_rlz_def_ln_os_pd_bal_am,
                  a.pr_36_m_rlz_def_ln_os_lgd_bal_am,
                  a.pr_12_m_rlz_def_ln_os_ead_bal_am,
                  datetime() as insrt_process_tmstmp format = datetime21.,
                  datetime() as updt_process_tmstmp format = datetime21.
            from work.base_with_lgd as a;
         quit;
         /*---- End of User Written Code  ----*/ 
         
         %rcSet(&syserr); 
         %rcSet(&sqlrc); 
         %rcSet(&syscc); 
         
         
         
         /**  Step end User Written **/
         
         %let etls_endTime = %sysfunc(datetime(),datetime.);
         
         
         
         /**  Job end RRAP_MOR_MODEL_75_BNS_RPTING_NCR_BE_FACT **/
         
         /* Reset jobid and name */
         %let jobID = %quote(A57SWEI7.BH0009KE);
         %let etls_jobName = %nrquote(RRAP_MOR_MODEL_75_BNS_RPTING_NCR_BE_FACT_G);
         
      %mend etls_jobW2HGPYE; 
      
      %etls_jobW2HGPYE; 
      
      %let handleName = %etls_getHandle(statusTable=&etls_statusTable,
         handleVariable=etls_handleName, row=&&&etls_controlName);
         
      %let job_rc&handleName. = &job_rc; 
      
      %etls_freeHandle(statusTable=&etls_statusTable, statusVariable=etls_status, 
         handleVariable=etls_handleName, handleName="&handleName", 
         startTimeVariable=etls_startTime, endTimeVariable=etls_endTime, signoff=0, 
         returnCodeVariable=etls_jobRC, returnCodeMacroVariable=job_rc&handleName., setMainJobRc=1); 
         
   %mend etls_processToLoopW2HGPY3;
   
   %local etls_controlTable etls_statusTable etls_controlName 
      etls_processesRunning etls_maxProcesses etls_parameterTable 
      etls_additionalSignonOptions etls_signonRetries;
   %let etls_controlName = L65_; 
   %let etls_statusTable = work.W6NDUUE; 
   %let etls_parameterTable = work.W2HGPYB; 
   %let &etls_controlName = 0;
   %let etls_controlTable = work.W6N5E4I;
   
   %put %str(NOTE: Creating status table...);
   data &etls_statusTable 
      (keep = etls_handleName etls_machineId etls_startTime etls_endTime etls_status 
              etls_jobRC
      );
      attrib etls_handleName length = $32
         label = 'Name of handle to remote session'; 
      attrib etls_machineId length = $32
         label = 'Name of machine executing the task'; 
      attrib etls_startTime length = 8
         format = nldatmap.
         label = 'Start time of task'; 
      attrib etls_endTime length = 8
         format = nldatmap.
         label = 'End time of task'; 
      attrib etls_status length = $32
         label = 'Current status of task'; 
      attrib etls_jobRC length = 8
         label = 'Return code of task'; 
      set &etls_controlTable;
   run;
   
   %rcSet(&syserr); 
   
   %put %str(NOTE: Creating parameter table...);
   proc sql; 
      create table &etls_parameterTable as 
         select _ncr_be_fact_process_dt as _ncr_be_fact_process_dt, 
                mth_tm_id as mth_tm_id 
         from &etls_controlTable; 
   quit; 
   
   %rcSet(&sqlrc); 
   
   /* Get the number of times to iterate from the number of rows in the source  */ 
   /*  table                                                                    */ 
   proc sql noprint; 
      select count(*) into :&etls_controlName._max from &etls_statusTable;
      %let &etls_controlName._max = &&&etls_controlName._max;
   quit;
   
   %rcSet(&sqlrc); 
   
   %let etls_maxProcesses = 1; 
   
   %if (&etls_maxProcesses > 0) %then 
   %do; 
      %do %until (&&&etls_controlName ge &&&etls_controlName._max); 
      
         %let etls_lastLoopPtr = &&&etls_controlName;
         
         %let etls_processesRunning = 0; 
         
         %do %while(&etls_processesRunning lt &&&etls_controlName._max 
            and &etls_processesRunning lt &etls_maxProcesses 
            and &&&etls_controlName lt &&&etls_controlName._max);
            
            %let &etls_controlName = %eval(&&&etls_controlName+1);
            
            %let job_rcLast=&job_rc; 
            
            %etls_createHandle(statusTable=&etls_statusTable,
                               statusVariable=etls_status,
                               handleVariable=etls_handleName,
                               handlePrefix=&etls_controlName,
                               statusSetting="Running",
                               row=&&&etls_controlName,
                               machineVariable=etls_machineId,
                               startTimeVariable=etls_startTime,
                               signon=0,
                               useGrid=0);
            
         %let etls_processesRunning = 1; 
         %etls_processToLoopW2HGPY3(parameterTable=&etls_parameterTable, row=&&&etls_controlName,
            handleName=%etls_getHandle(statusTable=&etls_statusTable,
            handleVariable=etls_handleName, row=&&&etls_controlName)); 
         
         /* Reset main Job_RC and Trans_RC to max return code of all iterations */ 
         %let job_rcThisIter=&job_rc; 
         %let job_rc=&job_rcLast; 
         %let trans_rc=&job_rcLast; 
         %rcSet(&job_rcThisIter); 
      %end; 
      
   %end; 
   
%end;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W2HGPYB;
quit;

%mend etls_loopW2HGPXT; 

%etls_loopW2HGPXT; 

%rcSet(&syscc); 



/**  Step end Loop **/

/*==========================================================================* 
 * Step:            Loop End                              A57SWEI7.BK000Z7F * 
 * Transform:       Loop End                                                * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z7F);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%rcSet(&syscc); 



/**  Step end Loop End **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

