/**************************************************************************** 
 * Job:             RRAP_MOR_00_SOURCE_CHECK              A57SWEI7.BH0009JQ * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503.bns                                            * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/04 - Mortgage/BNS                   * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, November 1, 2018 3:01:41 PM EDT               * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;
options symbolgen;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009JQ);
%let etls_jobName = %nrquote(RRAP_MOR_00_SOURCE_CHECK);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

%macro genSASCommand; 
   %local noobjserver; 
   %if "&sysscp"="OS" %then %let noobjserver=; 
   %else %if "&sysscp"="VMS_AXP" %then %let noobjserver=%quote(/noobjectserver); 
   %else %let noobjserver=%quote(-noobjectserver); 
   options sascmd = "!sascmd &noobjserver"; 
%mend genSASCommand; 
%genSASCommand; 

%macro etls_tsLevel(macroName=, featureName=); 
   data _null_; 
      call symput("&macroName",tslvl("&featureName")); 
   run; 
%mend etls_tsLevel; 

%macro etls_signon(handleName=etlsRemote,
                   cmacvar=etls_signonStatus,
                   gridRC=rc,
                   useGrid=1,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=,
                   workloadMacroVariable=,
                   log=,
                   output=,
                   additionalSignonOptions=,
                   signonRetries=3,
                   gridJobName=&&etls_jobName&row);

   %let etls_gridInstalled =;
   %etls_tsLevel(macroName=etls_gridInstalled, featureName=uwugrdsv); 

   %if (&useGrid = 1) %then 
   %do; 

      %if ("&etls_gridInstalled" ne "") %then 
      %do; 
         %if (&gridRC eq ) %then 
            %let gridRC = &handleName.RC ; 

         %global &gridRC;
         %let workload = ; 
         %if (&workloadMacroVariable ne %str()) %then 
         %do; 
            data _null_;
               call symput('workload','; workload = '||symget("&workloadMacroVariable"));
            run;
         %end; 
         %let gridoptset = ;
         %if (&gridOptionSet ne %str()) %then 
         %do; 
            data _null_;
               call symput('gridoptset',"; gridoptset = &gridOptionSet");
            run;
         %end; 
         %let gridJobOpts = ;
         %let gridSuppOpts = ;
         %if (&etls_gridSuppJobOptions ne %str()) %then 
         %do; 
            data _null_;
               call symput('gridJobOpts', "&etls_gridSuppJobOptions");
            run;
            data _null_;
               call symput('gridSuppOpts', '; JOBOPTS=gridJobOpts');
            run;
         %end; 
            data _null_;
               call symput('gridJbName', "; jobname = gridJobName");
            run;
         %let &gridRC = %sysfunc(grdsvc_enable("&handleName", server = SASApp &gridoptset &workload &gridSuppOpts &gridJbName));
      %end; 
      %else 
         %put %str(NOTE: Grid service functions are not installed.);
   %end; 

   %local sleeptime sleepIncreaseAmount tryCount; 
   %let sleepIncreaseAmount=5; 
   %let sleeptime=5; 
   %let tryCount=1; 
   %let &cmacvar=1; 

   /* Store original return code values to reset them if a signon succeeds  */ 
   %local etls_sysrc etls_syscc;
   %let etls_sysrc = &sysrc;
   %let etls_syscc = &syscc;

   %do %until((&&&cmacvar ne 1) or (&tryCount gt %eval(&signonRetries+1))); 
      data _null_; 
      signon &handleName cmacvar=&cmacvar 
         %if ("&log" ne "") %then 
            log=&log; 
         %if ("&output" ne "") %then 
            output=&output; 
         %if ("&additionalSignonOptions" ne "") %then 
            &additionalSignonOptions; 
      ;run; 

      %if "&&&cmacvar" eq "1" %then 
      %do; 
         %if &tryCount lt %eval(&signonRetries+1) %then 
         %do; 
            %put NOTE: Signon attempt #&tryCount failed. Retrying in &sleeptime seconds.;
            %let rc=%sysfunc(sleep(&sleeptime,1)); 
         %end; 
         %else %if &signonRetries gt 0 %then 
            %put ERROR%QUOTE(:) Final signon attempt, #&tryCount, failed.;

         %let sleeptime=%sysevalf(&sleeptime+&sleepIncreaseAmount,int); /* increase sleeptime by factor */ 
         %let tryCount=%eval(&tryCount+1); 
      %end; 
      %else
      %do;
         /* Signon succeeded make sure return codes are reset to original values  */ 
         %let sysrc = &etls_sysrc;
         %let syscc = &etls_syscc;
      %end;
   %end; 
   %rcSet(&syserr); 

   /* On successful signon, fetch and report machine name if grid was requested. */ 
   %if ("&machineIdMacroVariable" ne "") %then %let &machineIdMacroVariable = ; 
   %if ("&&&cmacvar" ne "1" and "&machineIdMacroVariable" ne "" and 
        &useGrid = 1 and "&etls_gridInstalled" ne "") %then 
   %do; 
      %put; 
      %if ("&&&gridRC" eq "0") %then 
      %do; 
         %let &machineIdmacroVariable = %sysfunc(grdsvc_getname(&handleName)); 
         %put %str(NOTE: Signed on to grid machine &&&machineIdmacroVariable..);
      %end; 
      %else 
         %put %str(NOTE: GRID SERVICES WERE NOT ENABLED.  Signed on to LOCAL machine.);
      %put; 
   %end; 

%mend etls_signon; 

%macro etls_serverConnected(serverId=,macvarname=isConnected); 
   %let &macvarname=0; 
   %local search_str none_str savenotes; 

   /* setup information for listtask output */ 
   /* listtask output on OS/390 differs */ 
   %if %bquote(&sysscp) eq OS %then 
   %do; 
      %let search_str=Remote submit for; 
      %let token=5; 
   %end; 
   %else  
   %do; 
      %let search_str=--------------; 
      %let token=1; 
   %end; 

   /* Issue listtask within PROC PRINTTO - send output to file */ 
   filename __tmptxt TEMP; 
   %let savenotes=%sysfunc(getoption(notes)); 
   options nonotes; 

   proc printto log=__tmptxt new; 
   run; 

   options notes; 
   listtask; 
   proc printto; 
   run; 

   options nonotes; 

   /* read in the output from listtask */ 
   %let dsname=_null_; 
   data _null_(keep=Session); 
      length line $256 sessionId $60; 
      infile __tmptxt length=len; 
      input @1 line $varying. len; 

      if line=:'There are no' then 
         stop; 
      /* look for the search string and scan for server name */ 
      if index(line,"&search_str") then  
      do; 
         sessionId=scan(line,&token," "); 
         sessionId=upcase(trim(left(tranwrd(sessionId,'"',' ')))); 
         if sessionId=upcase(symget("serverId")) then 
         do;  
            call symput("&macvarname","1"); 
            stop; 
         end; 
      end; 
   run; 
   filename __tmptxt clear; 
   options &savenotes; 
%mend etls_serverConnected; 

%macro etls_signoff(handleName=rmt); 
   %local savemprint; 
   %let savemprint=%sysfunc(getoption(mprint)); 
   %put %str(NOTE: Testing connection with etls_serverConnected macro %(mprint off%).);
   options nomprint; 
   %local isConnected; 
   %etls_serverConnected(serverId=&handleName); 
   options &savemprint; 
   %if &isConnected %then 
      signoff &handleName ;; 
%mend etls_signoff; 

%macro etls_getHandle(statusTable=, handleVariable=, row=); 
   %let etls_dsid = %sysfunc(open(&statusTable)); 
   %if (&etls_dsid = 0) %then 
      %put %sysfunc(sysmsg()); 
   %else 
   %do; 
      %let rc = %sysfunc(fetchobs(&etls_dsid, &row)); 
      %if (&rc ne 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %let etls_varnum = %sysfunc(varnum(&etls_dsid,&handleVariable)); 
         %if (&etls_varnum > 0) %then 
            %sysfunc(getvarc(&etls_dsid,&etls_varnum)); 
         %else 
            %put %sysfunc(sysmsg()); 
      %end; 
      %let rc = %sysfunc(close(&etls_dsid)); 
   %end; 
%mend etls_getHandle; 

%macro etls_freeHandle(statusTable=, statusVariable=, handleVariable=, 
   handleName=, statusSetting="Finished", 
   endTimeVariable=endTime, startTimeVariable=startTime, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, setMainJobRC=1, 
   statusUnknownReturnCode=., startTimeMacroVariable=, endTimeMacroVariable= ); 

   %if (&statusTable ne ) %then 
   %do; 
      %local etls_rcMacroVarExisted; 
      %let etls_rcMacroVarExisted = 0; 
      %if ("&returnCodeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_rcMacroVarExisted from dictionary.macros 
            where name=upcase("&returnCodeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_rcMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Return code from inner job not found.  Setting status to Unknown.;
            %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
         %end; 
         %if (&setMainJobRC eq 1) %then 
            %rcSet(&&&returnCodeMacroVariable); 
      %end; 
      %else 
      %do; 
         %let returnCodeMacroVariable=etls_rcmacvar; 
         %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
      %end; 

      %local etls_startTimeMacroVarExisted; 
      %let etls_startTimeMacroVarExisted = 0; 
      %if ("&startTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_startTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&startTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_startTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Start time from inner job not found.  No value will be set.;
            %let &startTimeMacroVariable=; 
         %end; 
      %end; 

      %local etls_endTimeMacroVarExisted; 
      %let etls_endTimeMacroVarExisted = 0; 
      %if ("&endTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_endTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&endTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_endTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) End time from inner job not found.  Setting end time to current
      time.;
            %let &endTimeMacroVariable=%sysfunc(datetime()); 
         %end; 
      %end; 

      data &statusTable; 
         modify &statusTable(where=(&handleVariable = &handleName)); 
         %if ("&startTimeMacroVariable" ne "") %then 
         %do; 
            &startTimeVariable = input(symget("&startTimeMacroVariable"),32.);; 
         %end; 
         %if ("&endTimeVariable" ne "") %then 
         %do; 
            %if ("&endTimeMacroVariable" ne "") %then 
            %do; 
               &endTimeVariable = input(symget("&endTimeMacroVariable"),32.);; 
            %end; 
            %else 
               &endTimeVariable = datetime();; 
         %end; 
         %if ("&returnCodeVariable" ne "") %then 
            &returnCodeVariable = input(symget("&returnCodeMacroVariable"),32.);; 
         %if ("&statusVariable" ne "") %then 
         %do; 
            if (symget("etls_rcMacroVarExisted") eq "0") then 
               &statusVariable = "Unknown Status"; 
            else
               &statusVariable = &statusSetting;
         %end;
         call symput('handle',&handleVariable); 
         replace; 
         stop; 
      run; 

      %rcSet(&syserr); 

      %if (&signoff eq 1) %then 
         %etls_signoff(handleName=&handle); 
   %end; 
%mend etls_freeHandle; 

%macro etls_createHandle(statusTable=,
                         statusVariable=,
                         handleVariable=,
                         handlePrefix=rmt,
                         gridOptionSet=,
                         workloadMacroVariable=,
                         row=,
                         machineVariable=,
                         statusSetting="Running", 
                         startTimeVariable=startTime,
                         signon=1,
                         useGrid=1,
                         log=,
                         output=,
                         gridRC=,
                         cmacvar=etls_signonStatus,
                         additionalSignonOptions=,
                         signonRetries= ); 

   %local remoteSessionId; 
   %let remoteSessionId = &handlePrefix.&row; 
   %let &cmacvar = 1; 
   %local etls_machineId; 
   %if (&signon eq 1) %then 

      %etls_signon(handleName=&remoteSessionId,
                   useGrid=&useGrid,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=&etls_gridOptionSet,
                   workloadMacroVariable=&workloadMacroVariable,
                   log=&log,
                   output=&output,
                   cmacvar=&cmacvar,
                   gridRC=&gridRC,
                   additionalSignonOptions=&additionalSignonOptions,
					signonRetries=&signonRetries,
                   gridJobName=DIS_&etls_jobName._&row); 

   %else %let &cmacvar=0; 

   data &statusTable; 
      retain ptr &row; 
      modify &statusTable point = ptr; 
      &handleVariable = "&remoteSessionId"; 
      %if (&signon eq 1) %then 
         &machineVariable = "&etls_machineId";; 
      %if (&&&cmacvar ne 0) %then 
      %do; 
         &statusVariable = "Failed Signon"; 
      %end; 
      %else 
         &statusVariable = &statusSetting;; 
      %if (&startTimeVariable ne ) %then 
         &startTimeVariable = datetime();; 
      replace; 
      stop; 
   run; 

   %rcSet(&syserr); 
%mend etls_createHandle; 

%macro etls_waitfor(statusTable=, statusVariable=, runningStatusSetting="Running", handleVariable=, 
   completeStatusSetting="Finished", endTimeVariable=endTime, 
   startTimeVariable=startTime, waitType=_ANY_, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, statusUnknownReturnCode=.); 

   proc sql noprint; 
      select count(*) into :etls_rows 
         from &statusTable where &statusVariable = &runningStatusSetting; 
      %let etls_rows = &etls_rows; 
      %if (&etls_rows gt 0) %then 
      %do; 
         select &handleVariable into :etlsHandles1 - :etlsHandles&etls_rows 
            from &statusTable where &statusVariable = &runningStatusSetting; 
      %end; 
   quit; 

   %rcSet(&sqlrc); 

   %if (&etls_rows gt 0) %then 
   %do; 
      waitfor &waitType 
         %do i=1 %to &etls_rows; 
            &&etlsHandles&i 
         %end; 
      ; 
   %end; 

   %local useDefaultRCMacVar; 
   %if ("&returnCodeMacroVariable" eq "") %then 
      %let useDefaultRCMacVar=Y; 

   %do i=1 %to &etls_rows; 

      %if ("&useDefaultRCMacVar"="Y") %then 
         %let returnCodeMacroVariable=job_rc&&etlsHandles&i; 

      waitfor &&etlsHandles&i timeout=1; 
      %if (&SYSRC eq 0) or (&SYSRC eq -2) %then /* process complete  */ 
      %do; 
         %etls_freeHandle(statusTable=&statusTable, statusVariable=&statusVariable,
            handleVariable=&handleVariable, handleName="&&etlsHandles&i", 
            statusSetting=&completeStatusSetting, endTimeVariable=&endTimeVariable, 
            startTimeVariable=&startTimeVariable, signoff=&signoff, 
            returnCodeVariable=&returnCodeVariable, returnCodeMacroVariable=&returnCodeMacroVariable, 
            statusUnknownReturnCode=&statusUnknownReturnCode, 
            startTimeMacroVariable=etls_startTime_&&etlsHandles&i., 
            endTimeMacroVariable=etls_endTime_&&etlsHandles&i. ); 
         %put NOTE: Process &&etlsHandles&i. has completed.;
      %end; 
      %else %if (&SYSRC ne -1) %then /* process status unknown  */ 
      %do; 
         %etls_freeHandle(statusTable=&statusTable, statusVariable=&statusVariable,
            handleVariable=&handleVariable, handleName="&&etlsHandles&i", 
            statusSetting="Unknown Status", endTimeVariable=&endTimeVariable, 
            startTimeVariable=&startTimeVariable, signoff=&signoff, 
            returnCodeVariable=&returnCodeVariable, returnCodeMacroVariable=&returnCodeMacroVariable, 
            statusUnknownReturnCode=&statusUnknownReturnCode, startTimeMacroVariable=etls_startTime_&&etlsHandles&i ); 
         %put NOTE: Cannot retrieve status from process &&etlsHandles&i..;
      %end; 
   %end; 
%mend etls_waitfor; 

%macro etls_getProcessesRunning(statusTable=, statusVariable=, processCountMacro=, 
   statusSetting="Running"); 

   proc sql noprint; 
      select count(*) into: &processCountMacro 
         from &statusTable where &statusVariable = &statusSetting; 
   quit; 

   %rcSet(&sqlrc); 
%mend etls_getProcessesRunning; 

/*==========================================================================* 
 * Step:            AM_rrap_mortgage_autoexec             A57SWEI7.BK0012PP * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from iw503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK0012PP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mortgage_autoexec **/

/*---- Start of User Written Code  ----*/ 

proc sql ;
  	select max(eff_from_dt) as max_date into :deli_file 
   from CB.DELI_FILE ; *WHERE eff_from_dt = '28May2019'd;        /*Sud* eff_from_dt = 28May2019 or 01Apr2019 */

	select max(time_key) as max_date into :cust_model
   from owdss.CUST_MODEL ; *where time_key = 17876;				/*Sud* where time_key = 17876; */

  	select max(popn_dt) as max_date into :iwd_cust 
   from owstar.IWD_CUST ; *where popn_dt = '15May2019'd;         /*Sud* Where POPN_DT = 15May2019 or 15Apr2019*/

	select max(POPN_DT) as max_date into :IWD_PD_PLN 
   from Owstar.IWD_PD_PLN ;*where POPN_DT = '15May2015'd;       /*Sud* Where POPN_DT = 15May2015 or 15Apr2015*/
  
   select max(time_key) as max_date into :IWF_CUST_ACTY_RLP
   from Owstar.IWF_CUST_ACTY_RLP ;* where time_key = 17876;      /*Sud* where time_key = 17876; */

	select max(time_lvl_end_dt) as max_date into :iwd_time
   from owstar.iwd_time ;*where *time_lvl_end_dt = '31May2019'd;  /*Sud* Where time_lvl_end_dt=  '31May2019'd or 31Oct2021; */

   select max(time_key) as max_date into :IWF_CUST_ACCT
   from Owstar.IWF_CUST_ACCT ;*where time_key = 17876;          /*Sud* where time_key = 17876; */

	select  max(POPN_DT) as max_date into :IWD_CHNL_RM 
   from SAS.IWD_CHNL_RM_TMP ;*where POPN_DT = '15Nov2012'd;      /*Sud* POPN_DT = 15Nov2012 */
quit;
/*---- End of User Written Code  ----*/ 

/*==========================================================================* 
 * Step:            SQL Server Sources                    A57SWEI7.BK0012PR * 
 * Transform:       Execute                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*
 *                                                                          * 
 * Nothing will be generated for this process because the "Exclude          * 
 *  transformation from run" option is selected.                            * 
 *                                                                          * 
 *==========================================================================*/ 

/*---- Start of User Written Code  ----*/ 

Title 'CIS_DATA_NEW2';
/*--Checking the min and max date of cis_date_new2.  Max date should be up to current run month.*/

proc sql;											
/*	connect using NZ as nzcon;										
	select max_date into :CIS_DATA_NEW2 from connection to nzcon ( */
	select max(file_date) as max_date into :CIS_DATA_NEW2
	from NZ.CIS_DATA_NEW2 ;* where file_date = '01May2019'd ;  /*Sud* file_date = 01May2019 */
	*disconnect from nzcon;											
quit; 

/*libname NZ netezza server=cs2iwntzp01 database=credit_risk authdomain="NZ_Auth";*/
/**/
/*proc sql;*/
/*select max(file_date) as max_date into :CIS_DATA_NEW2*/
/*from NZ.CIS_DATA_NEW2;*/
/*quit;*/


*Title 'MO_NEW';
 
/*--Checking the min and max date of mo_new.  Max date should be up to current run month.
proc sql;											
	connect using NZ as nzcon;										
	select max_date into :MO_NEW from connection to nzcon (

	select  max(process_date) as max_date
	from NZ.MO_NEW);
	disconnect from nzcon;											
quit;	
*/
Title 'UNEMP_RATE';
/*--Checking the min and max date of unemp_rate.  Max date should be up to current run month.*/


proc sql;											
/*	connect using NZ as nzcon;										
	select max_date into :UNEMP_RATE from connection to nzcon (  */

	select max(time_key) as max_date into :UNEMP_RATE 
	from NZ.UNEMP_RATE ;*where time_key = '31May2019'd ;     /*Sud* time_key = 31May2019 or 30Apr2019 */
	*disconnect from nzcon;											
quit;

/*
Title 'BASEL_MORT';
proc sql;											
	connect using NZ as nzcon;										
	select put(datepart(max_date),date9.) into :basel_mort from connection to nzcon (
									
	select max(EFF_TMSTMP) as max_date
	from NZ.BASEL_MORT);
	  										
	disconnect from nzcon;											
quit;
%put &basel_mort;
*/
title 'provncl_house_index_sum';
/*--Checking the min and max date of provncl_house_index_sum (source for HPI table).  Max date should be up to current run month-1.*/	
proc sql;
	select max(mth_tm_id) into :provncl_house_index_sum  
	from nzrrap.provncl_house_index_sum ;*where mth_tm_id = 17876;  /*Sud* Where mth_tm_id = 17876; */
quit;

Title 'TERANET_HOUSE_PRC_INDEX';

/*--Checking the min and max date of TERANET_HOUSE_PRC_INDEX (source for HPI table).  Max date should be up to current run month-1.*/
proc sql;
	select max(mth_tm_id) into :TERANET_HOUSE_PRC_INDEX 
	from NZRRAP.TERANET_HOUSE_PRC_INDEX ;* where mth_tm_id = 17876;   /*Sud* Where mth_tm_id = 17876; */
quit;

Title 'GEN_LKP';
/*--Checking the min and max date of GEN_LKP.  Max date should be up to current run month.*/
proc sql;											
	select max(EFF_FROM_TMSTMP) into :GEN_LKP
	from NZUSER.GEN_LKP ;
quit;	

Title 'GENWORTH_BULKINS';
/*--Checking the min and max date of GENWORTH_BULKINS.  Static file.*/
proc sql;											
	select  max(EFFECTIVEDTE) as max_date into :GENWORTH_BULKINS
	from NZUSER.GENWORTH_BULKINS ;*where EFFECTIVEDTE = '27Feb2012'd;  /*Sud* Where EFFECTIVEDTE = 27Feb2012 */
quit;		

/*Title 'HOUSE_INDEX_JAN_2013_CALC';*/ 
/* No need to check this as its source is TERANET_HOUSE_PRC_INDEX*/
/*--Checking the min and max date of HOUSE_INDEX_JAN_2013_CALC.  Max date should be up to current run month.*/
/*proc sql;											*/
/*	select max(date) as max_date into :HOUSE_INDEX_JAN_2013_CALC*/
/*	from NZUSER.HOUSE_INDEX_JAN_2013_CALC;*/
/*quit;	*/

/*GET THIS FROM ITS SQL SERVER SOURCE*/
/*title 'BRDM_BASELAYER_MOR';*/
/*--Checking the min and max date of BRDM_BASELAYER_MOR.  Max date should be up to current run month.*/
/*proc sql;											*/
/*	select   max(tm_id) as max_date into :BRDM_BASELAYER_MOR*/
/*	from NZUSER.BRDM_BASELAYER_MOR;*/
/*quit;*/
/*---- End of User Written Code  ----*/ 

/*---- Start of User Written Code  ----*/ 

data output;
	attrib table length=$40.;
	attrib max_date length=$40.;
	if missing(table) then delete;
run;


%macro output(dset=);
proc sql;
insert into output 
	set table="&dset",
		max_date=symget("&dset");
quit;
%mend output;
	%output(dset=DELI_FILE);
	%output(dset=CUST_MODEL);
	%output(dset=IWD_CUST);
	%output(dset=IWD_PD_PLN);
	%output(dset=IWF_CUST_ACTY_RLP);
/*	%output(dset=BASEL_MORT);*/
	%output(dset=iwd_time);
	%output(dset=IWF_CUST_ACCT);
	%output(dset=CIS_DATA_NEW2);
/*	%output(dset=MO_NEW);*/
	%output(dset=UNEMP_RATE);
	%output(dset=provncl_house_index_sum);
	%output(dset=TERANET_HOUSE_PRC_INDEX);
/*	%output(dset=GEN_LKP);*/
	%output(dset=GENWORTH_BULKINS);
/*	%output(dset=HOUSE_INDEX_JAN_2013_CALC);*/
	%output(dset=IWD_CHNL_RM);
/*	%output(dset=LGD_DIRECT_COSTS);*/
/*	%output(dset=LGD_INDIRECT_COST);*/
/*	%output(dset=BASELAYER_MOR);*/



data output_tmid;
	set output;
	where upcase(table) in (
	'CUST_MODEL'
	,'IWF_CUST_ACTY_RLP'
	,'IWF_CUST_ACCT'
	,'PROVNCL_HOUSE_INDEX_SUM' 
	,'TERANET_HOUSE_PRC_INDEX'
/*	,'BASELAYER_MOR'*/
	/*,'HOUSE_INDEX_JAN_2013_CALC'*/
	);
	date=input(strip(max_date),5.);
run;

proc sql;
	create table output_tmid2 as
	select a.table, b.tm_lvl_end_dt as monthend
	from output_tmid a, nzrrap.tm_dim b
	where a.date=b.tm_id and b.tm_lvl='Month'
	order by a.table;
quit;

data output_2;
	set output;
	where table in (
	'DELI_FILE'
	,'IWD_CUST'
	,'IWD_PD_PLN'
/*	,'BASEL_MORT'*/
	,'IWD_TIME'
	,'CIS_DATA_NEW2'
/*	,'MO_NEW'*/
	,'UNEMP_RATE'
/*	,'GEN_LKP'*/
	,'GENWORTH_BULKINS'
	,'IWD_CHNL_RM'
/*	,'LGD_DIRECT_COSTS'*/
/*	,'LGD_INDIRECT_COST'*/
	)
	;
	format monthend date9.;
	if upcase(table)='CIS_DATA_NEW2' then monthend=intnx('Month',input(max_date,date9.),0,'e');
	else if upcase(table)='UNEMP_RATE' then monthend=intnx('Month',input(max_date,date9.),0,'e');
	else if upcase(table)='DELI_FILE' then monthend=intnx('Month',input(max_date,date9.),0,'e');
	else monthend=input(max_date,date9.);
	*put monthend =;
	drop max_date;
run;
proc sort; by table; run;

/*data output_3;*/
/*	set output;*/
/*	where table='HOUSE_INDEX_JAN_2013_CALC';*/
/*	format monthend date9.;*/
/*	max_date_1=cats(max_date,'/01');*/
/*	monthend=intnx('Month',input(max_date_1,yymmdd10.),0,'e');*/
/**/
/*	keep table monthend;*/
/*run;*/


data pre_final;
	set output_2 output_tmid2 ;*output_3;
	table=upcase(table);
	by table;
run;

/*Sud* - original code. */
data _null_;
	call symputx('exp_date',intnx('Month',"&sysdate9."d,-1,'m')); *Middle of the run month;
	call symputx('exp_date_1',intnx('Month',"&sysdate9."d,-2,'m'));
run;  

/*sud* - Added below for May2019 test run 
data _null_;
	call symputx('exp_date',intnx('Month',"&sysdate9."d,-6,'m')); *Middle of the run month;
	call symputx('exp_date_1',intnx('Month',"&sysdate9."d,-7,'m'));
run; */


data final;
	set pre_final;
	attrib OK LENGTH=$8.;
	put monthend=;
	if upcase(table) in ('TERANET_HOUSE_PRC_INDEX','PROVNCL_HOUSE_INDEX_SUM') and monthend ge &exp_date_1 then do;
		OK='OK';
	end;
	else if upcase(table) in ('GENWORTH_BULKINS','IWD_CHNL_RM') and monthend ge '27FEB2012'd then do;
		OK='OK';
	end;
	else if upcase(table) = 'IWD_PD_PLN' and monthend ge '15MAY2015'd then do;
		OK='OK';
	end;
	else if monthend ge &exp_date then do;
		OK='OK';
	end;
 /*sud* - Adding beloe 3 lines code for May2019 test run as IWD_CUST table has month end date of 15th May   
	else if upcase(table) = 'IWD_CUST' and monthend ge '15MAY2015'd then do;
		OK='OK';
	end; */
	else OK='NOT OK!!';
	if OK NE 'OK' then put table monthend ok;
run;

data _null_;
	set final end=last;
	retain error 0;
	if OK ne 'OK' then do;
	error+1;
	put table monthend ok;
	end;
	if last and error gt 0 then abort;
run;
/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

