
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

%let datetime_start = %sysfunc(TIME()) ;
%put >>> START TIME: %sysfunc(datetime(),datetime14.);

%put &lib;

options threads cpucount=4;;
%PUT >> Processing_Month_Time_ID = &MTH_TM_ID.;

/*Fetch the Year and Month from TM_DIM to use it for query on 
&LIB..BASEL_SUBSIDIARY_ACL_LKP*/
option nosource;
%macro rrap_db2yearmonth_initialize(indata=, dbdata=);
proc sql noprint;
	*select max(MTH_TM_ID) into :MTH_TM_ID from &indata.;
	create table _temp_yearmonth as 
select clndr_yr, tm_yr_seq_num, '00' as charmonth, '000000' as yearmonth from 
EDRTLRT.TM_DIM where TM_ID = &MTH_TM_ID;
quit;
/*Convert the integer values to char values as needed*/
data _temp_yearmonth;
set _temp_yearmonth;
if tm_yr_seq_num < 10 then do;
	charmonth='0'||put(tm_yr_seq_num,1.);
end;
else do;
charmonth=tm_yr_seq_num;
end;
	yearmonth=clndr_yr||charmonth;
	format yearmonth $char6.;
run;
/*Save the string YYYYMM for the latest MTH_TM_ID fetched from TM_DIM into a 
variable*/
proc sql noprint;
select yearmonth into :yearmonth from _temp_yearmonth;
quit;
%mend rrap_db2yearmonth_initialize;

/**  Step end AM_rrap_db2yearmonth_initialize **/

/*This transformation accepts the target table to be loaded as an input 
parameter
and checks existence of data for the processing MTH_TM_ID */
%MACRO preload_data_check;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :PRELOAD_DATA_COUNT FROM &TGT00. WHERE 
MTH_TM_ID=&MTH_TM_ID;
QUIT;
%IF &PRELOAD_DATA_COUNT > 0 %THEN %DO;
%PUT TARGET TABLE &TGT00. ALREADY HAS &PRELOAD_DATA_COUNT RECORDS FOR CURRENT 
PROCESSING MONTH ID &MTH_TM_ID;
/*ENDSAS %STR(;);*/
%END;
%MEND preload_data_check;

/**  Step end AM_preload_data_check **/
/*==========================================================================* 
 * Step:            AM_datalog                            A57ZQ4A4.BO0001QG * 
 * Transform:       AM_datalog                                              * 
 * Description:                                                             * 
 *==========================================================================*/ 

/*This transformation generates the input and output table counts*/
%MACRO datalog;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :SRCCOUNT00 FROM &INPUT00. WHERE MTH_TM_ID=&MTH_TM_ID.;
SELECT COUNT(*) INTO :TGTCOUNT00 FROM &TGT00. WHERE MTH_TM_ID=&MTH_TM_ID.;
SELECT COUNT(*) INTO :SRCCOUNT01 FROM &INPUT01. WHERE MTH_TM_ID=&MTH_TM_ID.;
QUIT;
%MEND;

%let etls_recnt=-1;
%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 
/*CLEANUP MACRO*/
/*THIS MACRO DELETES ALL TEMPORARY SAS DATASETS LISTED BY THE USER AT THE 
SPECIFIED PATH ON AIX PLATFORM*/
/*LIBREF SHOULD BE THE LIBREF DECLARED FOR A UNIX PATH IN THE PROGRAM*/
/*DATASETS SHOULD BE THE LIST OF DATASETS SEPARATED BY A SINGLE SPACE*/
%MACRO SAS_DATASET_CLEANUP (LIBREF=, DATASETS=);
/*DELETE TEMPORARY DATASETS*/
PROC DATASETS LIBRARY=&LIBREF NOLIST;
DELETE &DATASETS;
RUN;
QUIT;
%MEND;

%let etls_recnt=-1;
/*Macro for fetching the yearmonth in an integer format*/
%rrap_db2yearmonth_initialize(indata=&input00.,dbdata=&DB.);
%PUT YEARMONTH IS &YEARMONTH;
%*PUT MONTHYEAR IS &MONTHYEAR;
%PUT MTH_TM_ID IS &MTH_TM_ID;
%PUT MTH_END_DT IS "&MTH_END_DT"d;
/*---- End of User Written Code  ----*/ 
/*---- Start of User Written Code  ----*/ 
/**Program_to_Create Basel_P1_xxx Extract Tables on 20August2014 **/
*options compress = yes cpucount=4 threads nonotes nomprint nomlogic 
nosymbolgen;

%global mth_tm_id;
%global tm_lvl_st_dt;
%global tm_lvl_end_dt;
%global dtime;

proc datasets lib=work kill nolist;
run;quit;
option nosource;


DATA &LIB..Basel_candn_rtl_ncr_bd_fact2 
&LIB..BASEL_NCR_CNDN_RTL_BD_FACT2 ;
SET
&DB..Basel_candn_rtl_ncr_bd_fact ;
WHERE 
 mth_tm_id = &MTH_TM_ID.;
 /*EXPSR_CL_ID IN (8009,8010,8011)*/
RUN;
proc sql noprint;
select tm_id as mth_tm_id, tm_lvl_st_dt, tm_lvl_end_dt , datetime() as dtime 
format datetime25.
into :mth_tm_id, :tm_lvl_st_dt, :tm_lvl_end_dt, :dtime
from  &LIB..TM_DIM
/*where tm_id=(select max(mth_tm_id) from &LIB..BASEL_NCR_BUS_AGGRTD_FACT); 
KEEP FOR PRODUCTION*/
where tm_id= &MTH_TM_ID.; * FOR TEST ONLY End of April test date 
;
quit;

proc sql;
create view &LIB..Basel_candn_rtl_ncr_bd_factV
as select *
from
&LIB..Basel_candn_rtl_ncr_bd_fact2 
;

quit;
proc sql noprint;
select compress(substr(tm_desc,1,7),"/") into :day_dtt from &LIB..TM_DIM 
where tm_id= &MTH_TM_ID.;
quit;
proc sql noprint; 
create table &LIB..Candn_rtl_bd_fact_p1 as 
select * from (
select distinct 'BASEL_CANDN_RTL_NCR_BD_FACT' as 
tbl,mth_tm_id,NCR_BD_RECD_TP_ID, 
(select b.NCR_RECD_TP_CD from &LIB..BASEL_NCR_BD_RECD_TP_DIM as b where 
a.NCR_BD_RECD_TP_ID=b.NCR_BD_RECD_TP_ID) as NCR_RECD_TP_CD,
NCR_PD_BAND_ID,(select NCR_PD_BAND_KEY_VAL from &LIB..PD_BAND_DIM 
as b where a.NCR_PD_BAND_ID=b.NCR_PD_BAND_ID 
AND put(&DAY_DTT,z6.) BETWEEN EFF_FROM_YR_MTH AND EFF_TO_YR_MTH) as NCR_PD_BAND_KEY_VAL,
NCR_EXPSR_SIZE_ID,(select NCR_KEY_VAL from &LIB..BASEL_NCR_EXPSR_SIZE_DIM as 
b where a.NCR_EXPSR_SIZE_ID=b.NCR_EXPSR_SIZE_ID) as NCR_EXPSR_SIZE_KEY_VAL,
NCR_GEO_ID,(select NCR_GEO_KEY_VAL from &LIB..BASEL_NCR_GEO_DIM as b where 
a.NCR_GEO_ID=b.NCR_GEO_ID) as NCR_GEO_KEY_VAL,
NCR_LTV_ID,(select NCR_LTV_KEY_VAL from &LIB..BASEL_NCR_LTV_DIM as b where 
a.NCR_LTV_ID=b.NCR_LTV_ID) as NCR_LTV_KEY_VAL,
EXPSR_cl_ID,(select NCR_EXPSR_CL_KEY_VAL from &LIB..BASEL_EXPSR_CL_DIM as b 
where a.EXPSR_cl_ID=b.EXPSR_cl_ID) as NCR_EXPSR_CL_KEY_VAL,
NCR_SECRTZTN_ID,(select NCR_SECRTZTN_KEY_VAL from 
&LIB..BASEL_NCR_SECRTZTN_DIM as b where a.NCR_SECRTZTN_ID=b.NCR_SECRTZTN_ID) 
as NCR_SECRTZTN_KEY_VAL,
NCR_RT_ID,(select NCR_RT_KEY_VAL from &LIB..BASEL_NCR_RT_DIM as b where 
a.NCR_RT_ID=b.NCR_RT_ID) as NCR_RT_KEY_VAL,
DLQNT_ID,(select NCR_DLQNT_CD from &LIB..DLQNT_DIM as b where 
a.DLQNT_ID=b.DLQNT_ID) as NCR_DLQNT_CD
,*
from  &LIB..Basel_candn_rtl_ncr_bd_factV as a)
where  mth_tm_id= &MTH_TM_ID.
; 

quit;
%let tdy=%sysfunc(date());


%LET good_DB_w_Tangern_join =  &LIB..CANDN_RTL_BD_FACT_P1 AS BASEL_NCR_CNDN_RTL_BD_FACT;



PROC SQL THREADS ;
create table BASEL_P1_005 as
Select distinct
"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.,
DATETIME() LENGTH=8 FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
NCR_DLQNT_CD,
BASEL_NCR_CNDN_RTL_BD_FACT.PD_BAND_NM LENGTH=40 FORMAT=$40. INFORMAT=$40. AS 
PD_BAND_NM,

(case when BASEL_NCR_CNDN_RTL_BD_FACT.PD_BAND_RTO eq . then 0 else BASEL_NCR_CNDN_RTL_BD_FACT.PD_BAND_RTO end)*100 FORMAT= 5.2 as PD_BAND_PC ,
BASEL_NCR_CNDN_RTL_BD_FACT.ACCT_CNT
 FORMAT = 24. AS ACCT_CNT
FROM 
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '005'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
quit;

data &lib..BASEL_P1_005;
set BASEL_P1_005;
run;

%MACRO APPENDNOT(N=05);
data BASEL_P1_0&N.;
set BASEL_P1_0&N.;
array nvar _NUMERIC_;
array cvar _CHARACTER_;
do over nvar;
if nvar = . then nvar = .;
end;
do over cvar;
if cvar = '' then cvar = '';
end;
run;
PROC SORT DATA = BASEL_P1_0&N. NODUPRECS FORCE;
BY
MTH_END_DT
EXTRACT_TIMESTAMP
NCR_RECD_TP_CD
NCR_PD_BAND_KEY_VAL
NCR_EXPSR_SIZE_KEY_VAL
NCR_GEO_KEY_VAL
NCR_LTV_KEY_VAL
NCR_EXPSR_CL_KEY_VAL
NCR_SECRTZTN_KEY_VAL
NCR_RT_KEY_VAL
NCR_DLQNT_CD
;
RUN;

%LET NOBS=0;

data BASEL_P1_0&N.;
set BASEL_P1_0&N. nobs=vnobs;
call symput('NOBS',vnobs);
run;


%PUT %SYSFUNC(COMPBL(>> BASEL_EXTRACT_TABLE BASEL_P1_0&N. HAS APPENDED &NOBS. 
RECORDS));
%IF &NOBS > 0 %THEN %DO;

option nosource;
proc sql;
delete from &DB..BASEL_P1_0&N. where mth_end_dt="&tm_lvl_end_dt."d;
insert into &DB..BASEL_P1_0&N. 
select *,datetime(),datetime()
from BASEL_P1_0&N.;
RUN;
quit;

%END;
%MEND APPENDNOT;
%APPENDNOT(N=05);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_010 Extract Table on 20August2014 **/
OPTIONS COMPRESS = YES;
PROC SQL THREADS;
create table BASEL_P1_010 as
Select distinct 
"&tm_lvl_end_dt."d FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3. ,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '010'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
;
quit;
%APPENDNOT(N=10);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_015 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
OPTIONS COMPRESS = YES;
PROC SQL THREADS;
create table BASEL_P1_015 as
Select distinct 
"&tm_lvl_end_dt."d FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3. ,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD = '015'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
;
quit;
%APPENDNOT(N=15);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_020 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
OPTIONS COMPRESS = YES;
PROC SQL THREADS;
create table BASEL_P1_020 as
Select distinct 
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD = '020'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
QUIT;
%APPENDNOT(N=20);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_025 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
OPTIONS COMPRESS = YES;
PROC SQL THREADS;
create table BASEL_P1_025 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD = '025'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
QUIT;
%APPENDNOT(N=25);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_030 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
OPTIONS COMPRESS = YES;
PROC SQL THREADS;
create table BASEL_P1_030 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD = '030'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
QUIT;
%APPENDNOT(N=30);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_035 Extract Table on 20August2014 **/
PROC SQL THREADS;
create table BASEL_P1_035 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD = '035'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
QUIT;
%APPENDNOT(N=35);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_040 Extract Table on 20August2014 **/
PROC SQL THREADS;
create table BASEL_P1_040 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
(BASEL_NCR_CNDN_RTL_BD_FACT.OV_LMT_ACCT_RTO *100) FORMAT=17.3 AS 
OV_LMT_ACCT_RTO
FROM
&good_DB_w_Tangern_join.
WHERE 
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD = '040'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
QUIT;
%APPENDNOT(N=40);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_045 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
/**
Candn_rtl_bd_fact_p1
tangerine_p1**/
PROC SQL THREADS;
create table BASEL_P1_045 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.AUTH_AMT/1000) AS AUTH_AMT,
round(BASEL_NCR_CNDN_RTL_BD_FACT.FRAUD_LOSS_AMT/1000) AS FRAUD_LOSS_AMT,
round(BASEL_NCR_CNDN_RTL_BD_FACT.ESTD_EAD_AMT/1000) AS ESTD_EAD_AMT,
BASEL_NCR_CNDN_RTL_BD_FACT.WRITE_OFF_ACCT_CNT 
FORMAT = 24. AS ACCT_WRTN_OFF_CNT
FROM
&good_DB_w_Tangern_join.
WHERE 
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD = '045'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
;
quit;
%APPENDNOT(N=45);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_047 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
PROC SQL THREADS;
create table BASEL_P1_047 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
/***
Total Write Off Count = 
Basel Canadian Retail NCR BD Fact.Total Write Off Count , Basel Tangerine NCR 
BD Fact.Total Write Off Count
IRB Expected Loss Amount = 
(Basel Canadian Retail NCR BD Fact.IRB Expected Loss Amount , 
Basel Tangerine NCR BD Fact.IRB Expected Loss Amount)/1000
**/
round(BASEL_NCR_CNDN_RTL_BD_FACT.WRITE_OFF_TOT_AMT/1000) AS TOT_WRITE_OFF_AMT,
round(BASEL_NCR_CNDN_RTL_BD_FACT.IRB_EXPCTD_LOSS_AMT/1000) AS IRB_EXPCTD_LOSS_AMT
FROM
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '047'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
;
quit;
%APPENDNOT(N=47);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_050 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
PROC SQL THREADS;
create table BASEL_P1_050 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.RCVRY_AMT/1000) AS RECOVERY_AMT,
round(BASEL_NCR_CNDN_RTL_BD_FACT.ECONMC_LOSS_AMT/1000) AS ECONMC_LOSS_AMT,
round(BASEL_NCR_CNDN_RTL_BD_FACT.IRB_CAPTL_AMT/1000) AS IRB_CAPTL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '050'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
;
quit;
%APPENDNOT(N=50);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_055 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
PROC SQL THREADS;
create table BASEL_P1_055 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT,
BASEL_NCR_CNDN_RTL_BD_FACT.ACCT_CNT 
format=24. AS ACCT_CNT
from 
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '055'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
quit;
%APPENDNOT(N=55);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_060 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
PROC SQL THREADS;
create table BASEL_P1_060 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
(BASEL_NCR_CNDN_RTL_BD_FACT.AVG_UTLTN_RTO *100) FORMAT= 5.2 AS AVG_UTLTN_RTO
FROM
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '060'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
quit;
%APPENDNOT(N=60);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_065 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
%*LET Processing_Month_Time_ID = 15516;
PROC SQL THREADS;
create table BASEL_P1_065 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.AUTH_AMT/1000) AS AUTH_AMT,
round(BASEL_NCR_CNDN_RTL_BD_FACT.OS_BAL_AMT/1000) AS OS_BAL_AMT
from 
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '065'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
quit;
%APPENDNOT(N=65);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_070 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
PROC SQL THREADS;
create table BASEL_P1_070 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
BASEL_NCR_CNDN_RTL_BD_FACT.ACCT_CNT
format=24. AS ACCT_CNT,
BASEL_NCR_CNDN_RTL_BD_FACT.ESTD_DEFLTD_ACCT_CNT
format=24. AS ESTD_DEFLTD_ACCT_CNT,
BASEL_NCR_CNDN_RTL_BD_FACT.REALZ_DEFLTD_ACCT_CNT
format=24. AS REALZ_DEFLTD_ACCT_CNT
from 
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '070'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
quit;
%APPENDNOT(N=70);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_080 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
PROC SQL THREADS;
create table BASEL_P1_080 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.GRS_IMPAIRED_LOAN_AND_ACPTNC_AMT/1000) AS GIL_AND_ACPTNC,
round(BASEL_NCR_CNDN_RTL_BD_FACT.GRS_IMPRD_LN_ACPT_ADDTN_AMT/1000) AS ADDTN_TO_GIL_AND_ACPTNC,
round(BASEL_NCR_CNDN_RTL_BD_FACT.GRS_IMPRD_LN_ACPT_RET_AC_ST_AMT/1000) AS GIL_AND_ACPTNC_RET_TO_ACCRL_STAT,
round(BASEL_NCR_CNDN_RTL_BD_FACT.CR_LOSS_TOT_ALWNC_AMT/1000) AS TOT_ALWNC_FOR_CR_LOSSES,
round(BASEL_NCR_CNDN_RTL_BD_FACT.CR_LOSS_TOT_PVSN_AMT/1000) AS TOT_PSVN_FOR_CR_LOSSES,
round(BASEL_NCR_CNDN_RTL_BD_FACT.CR_LOSS_GENL_PVSN_AMT/1000) AS GENL_PSVN_FOR_CR_LOSSES,
round(BASEL_NCR_CNDN_RTL_BD_FACT.CR_LOSS_SPECIFIC_PVSN_AMT/1000) AS SPECIFIC_PSVN_FOR_CR_LOSSES
FROM
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '080'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
;
quit;
%APPENDNOT(N=80);
/*REMOTE SUBMIT ENDS*/
/**Program_to_Create Basel_P1_090 Extract Table on 20August2014 **/
/*REMOTE SUBMIT THE SAS PROGRAM ONTO THE SERVER*/
PROC SQL THREADS;
create table BASEL_P1_090 as
Select
"&tm_lvl_end_dt."d LENGTH=8 FORMAT=DATE. AS MTH_END_DT,
DATETIME() FORMAT=DATETIME. AS EXTRACT_TIMESTAMP,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RECD_TP_CD LENGTH=3 FORMAT=$3. INFORMAT=$3.,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_PD_BAND_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_SIZE_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_GEO_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_LTV_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_EXPSR_CL_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_SECRTZTN_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_RT_KEY_VAL,
BASEL_NCR_CNDN_RTL_BD_FACT.NCR_DLQNT_CD,
round(BASEL_NCR_CNDN_RTL_BD_FACT.GRS_IMPRD_LN_ACPT_OTH_CHNG_AMT/1000) AS OTH_CHG_IN_GIL_AND_ACPTNC,
round(BASEL_NCR_CNDN_RTL_BD_FACT.CR_LOSS_ALWNC_OTH_CHNG_AMT/1000) AS OTH_CHG_IN_ALWNC_FOR_CR_LOSSES
from 
&good_DB_w_Tangern_join.
WHERE 
NCR_RECD_TP_CD = '090'  AND 
BASEL_NCR_CNDN_RTL_BD_FACT.MTH_TM_ID= &MTH_TM_ID.
;
quit;
%APPENDNOT(N=90);
/** Program Ends **/
/*---- End of User Written Code  ----*/ 
%PUT etls_endTime = %sysfunc(datetime(),datetime.);

%put >>> END TIME: %sysfunc(datetime(),datetime14.);
%put >>> Benchmarking PROCESSING TIME:  %sysfunc(putn(%sysevalf(%sysfunc(TIME())-&datetime_start.),mmss.)) (mm:ss) ;

