/**************************************************************************** 
 * Job:             RRAP_MOR_MODEL_60                     A57ZQ4A4.BF0011Q9 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503.bns                                            * 
 * Port:            8561                                                    * 
 * Location:        /User Folders/Hadi Dimashkieh/My Folder/Jobs/DLGD       * 
 *                   Insured Changes                                        * 
 *                                                                          * 
 * Server:          SASApp                                A57ZQ4A4.AT000002 * 
 *                                                                          * 
 * Generated on:    Wednesday, November 29, 2017 4:12:15 PM EST             * 
 * Generated by:    s2809211                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57ZQ4A4.BF0011Q9);
%let etls_jobName = %nrquote(RRAP_MOR_MODEL_60);
%let etls_userID = %nrquote(s2809211);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(cs2iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_mortgage_autoexec             A57ZQ4A4.BO0018UX * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57ZQ4A4.BO0018UX);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%include '/sasdata/sasdi/sasdev/macro/rrap/rrap_autoexec.sas';
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mortgage_autoexec **/

/*==========================================================================* 
 * Step:            Set Dates                             A57ZQ4A4.BO0018UY * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Target Table:    User Written - work.SET_DATES         A57ZQ4A4.BQ0013XA * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57ZQ4A4.BO0018UY);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.SET_DATES;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57ZQ4A4.BQ0013XA%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = _run_date _run_date_yymth mth_tm_id;
%let _OUTPUT_col_count = 3;
%let _OUTPUT_col0_name = _run_date;
%let _OUTPUT_col0_table = work.SET_DATES;
%let _OUTPUT_col0_length = 10;
%let _OUTPUT_col0_type = $;
%let _OUTPUT_col0_format = $10.;
%let _OUTPUT_col0_informat = $10.;
%let _OUTPUT_col0_label = %nrquote();
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = _run_date_yymth;
%let _OUTPUT_col1_table = work.SET_DATES;
%let _OUTPUT_col1_length = 6;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = $10.;
%let _OUTPUT_col1_informat = $10.;
%let _OUTPUT_col1_label = %nrquote();
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input_count = 0;
%let _OUTPUT_col2_name = mth_tm_id;
%let _OUTPUT_col2_table = work.SET_DATES;
%let _OUTPUT_col2_length = 8;
%let _OUTPUT_col2_type = ;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote();
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input_count = 0;

%let _OUTPUT1 = work.SET_DATES;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57ZQ4A4.BQ0013XA%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = _run_date _run_date_yymth mth_tm_id;
%let _OUTPUT1_col_count = 3;
%let _OUTPUT1_col0_name = _run_date;
%let _OUTPUT1_col0_table = work.SET_DATES;
%let _OUTPUT1_col0_length = 10;
%let _OUTPUT1_col0_type = $;
%let _OUTPUT1_col0_format = $10.;
%let _OUTPUT1_col0_informat = $10.;
%let _OUTPUT1_col0_label = %nrquote();
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input_count = 0;
%let _OUTPUT1_col1_name = _run_date_yymth;
%let _OUTPUT1_col1_table = work.SET_DATES;
%let _OUTPUT1_col1_length = 6;
%let _OUTPUT1_col1_type = $;
%let _OUTPUT1_col1_format = $10.;
%let _OUTPUT1_col1_informat = $10.;
%let _OUTPUT1_col1_label = %nrquote();
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input_count = 0;
%let _OUTPUT1_col2_name = mth_tm_id;
%let _OUTPUT1_col2_table = work.SET_DATES;
%let _OUTPUT1_col2_length = 8;
%let _OUTPUT1_col2_type = ;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote();
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input_count = 0;

/*---- Start of User Written Code  ----*/ 



%get_model_period_dates(product=mor);

%let start_period_dt=31JUL2017;
%let end_period_dt=31JUL2017;

%put Start and End Dates for Mortgage Models:;

%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;




data _output;
format _run_date $10.
       _run_date_yymth  $6.;

	run_date=intnx('month',"&end_period_dt"d,0,'e');
	_run_date_yymth = put(run_date,yymmn.);
	_run_date = put(run_date,yymmdd10.); 
	output; *Current Month - Used for Instrument Fact;
	
/*	run_date=intnx('month',"&end_period_dt"d,-1,'e');
	_run_date_yymth = put(run_date,yymmn.);
	_run_date = put(run_date,yymmdd10.); 
	output; *3 Months ago - Used for BD Fact;
	
	run_date=intnx('month',"&end_period_dt"d,-2,'e');
	_run_date_yymth = put(run_date,yymmn.);
	_run_date = put(run_date,yymmdd10.); 
	output; *3 Months ago - Used for BD Fact;
	
	run_date=intnx('month',"&end_period_dt"d,-3,'e');
	_run_date_yymth = put(run_date,yymmn.);
	_run_date = put(run_date,yymmdd10.); 
	output; *3 Months ago - Used for BD Fact;

	run_date=intnx('month',"&end_period_dt"d,-12,'e');
	_run_date_yymth = put(run_date,yymmn.);
	_run_date = put(run_date,yymmdd10.); 
	output; *12 Months ago - Used for BE Fact;
	
	run_date=intnx('month',"&end_period_dt"d,-36,'e');
	_run_date_yymth = put(run_date,yymmn.);
	_run_date = put(run_date,yymmdd10.); 
	output; *36 Months ago - Used for BE Fact;
*/
run;


proc sql;
create table &_output as
select a.*, b.tm_id as mth_tm_id
from _output a, nzrrap.tm_dim b
where b.tm_lvl='Month' and b.tm_lvl_end_dt=input(a._run_date,yymmdd10.)
order by b.tm_id;
quit;


proc sql;
connect using nzuser as nzcon;
execute (truncate table basel_analytcl_bl_inst_fct_BNS 
) by nzcon;
quit;
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end Set Dates **/

/*==========================================================================* 
 * Step:            Loop                                  A57ZQ4A4.BO0018UZ * 
 * Transform:       Loop                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    User Written - work.SET_DATES         A57ZQ4A4.BQ0013XA * 
 * Target Table:    Loop - work.W2B6FZD                   A57ZQ4A4.BQ0013XB * 
 *==========================================================================*/ 

%let transformID = %quote(A57ZQ4A4.BO0018UZ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.SET_DATES, DATA)) or 
         %sysfunc(exist(work.SET_DATES, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.SET_DATES out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.SET_DATES); 

/* Capture summary statistics about this step for performance reporting  */ 
%put "DIS_SUMM";
%macro etls_getHandle(statusTable=, handleVariable=, row=); 
   %let etls_dsid = %sysfunc(open(&statusTable)); 
   %if (&etls_dsid = 0) %then 
      %put %sysfunc(sysmsg()); 
   %else 
   %do; 
      %let rc = %sysfunc(fetchobs(&etls_dsid, &row)); 
      %if (&rc ne 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %let etls_varnum = %sysfunc(varnum(&etls_dsid,&handleVariable)); 
         %if (&etls_varnum > 0) %then 
            %sysfunc(getvarc(&etls_dsid,&etls_varnum)); 
         %else 
            %put %sysfunc(sysmsg()); 
      %end; 
      %let rc = %sysfunc(close(&etls_dsid)); 
   %end; 
%mend etls_getHandle; 

%macro etls_freeHandle(statusTable=, statusVariable=, handleVariable=, 
   handleName=, statusSetting="Finished", 
   endTimeVariable=endTime, startTimeVariable=startTime, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, setMainJobRC=1, 
   statusUnknownReturnCode=., startTimeMacroVariable=, endTimeMacroVariable= ); 

   %if (&statusTable ne ) %then 
   %do; 
      %local etls_rcMacroVarExisted; 
      %let etls_rcMacroVarExisted = 0; 
      %if ("&returnCodeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_rcMacroVarExisted from dictionary.macros 
            where name=upcase("&returnCodeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_rcMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Return code from inner job not found.  Setting status to Unknown.;
            %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
         %end; 
         %if (&setMainJobRC eq 1) %then 
            %rcSet(&&&returnCodeMacroVariable); 
      %end; 
      %else 
      %do; 
         %let returnCodeMacroVariable=etls_rcmacvar; 
         %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
      %end; 

      %local etls_startTimeMacroVarExisted; 
      %let etls_startTimeMacroVarExisted = 0; 
      %if ("&startTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_startTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&startTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_startTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Start time from inner job not found.  No value will be set.;
            %let &startTimeMacroVariable=; 
         %end; 
      %end; 

      %local etls_endTimeMacroVarExisted; 
      %let etls_endTimeMacroVarExisted = 0; 
      %if ("&endTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_endTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&endTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_endTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) End time from inner job not found.  Setting end time to current
      time.;
            %let &endTimeMacroVariable=%sysfunc(datetime()); 
         %end; 
      %end; 

      data &statusTable; 
         modify &statusTable(where=(&handleVariable = &handleName)); 
         %if ("&startTimeMacroVariable" ne "") %then 
         %do; 
            &startTimeVariable = input(symget("&startTimeMacroVariable"),32.);; 
         %end; 
         %if ("&endTimeVariable" ne "") %then 
         %do; 
            %if ("&endTimeMacroVariable" ne "") %then 
            %do; 
               &endTimeVariable = input(symget("&endTimeMacroVariable"),32.);; 
            %end; 
            %else 
               &endTimeVariable = datetime();; 
         %end; 
         %if ("&returnCodeVariable" ne "") %then 
            &returnCodeVariable = input(symget("&returnCodeMacroVariable"),32.);; 
         %if ("&statusVariable" ne "") %then 
         %do; 
            if (symget("etls_rcMacroVarExisted") eq "0") then 
               &statusVariable = "Unknown Status"; 
            else
               &statusVariable = &statusSetting;
         %end;
         call symput('handle',&handleVariable); 
         replace; 
         stop; 
      run; 

      %rcSet(&syserr); 

      %if (&signoff eq 1) %then 
         %etls_signoff(handleName=&handle); 
   %end; 
%mend etls_freeHandle; 

%macro etls_createHandle(statusTable=,
                         statusVariable=,
                         handleVariable=,
                         handlePrefix=rmt,
                         gridOptionSet=,
                         workloadMacroVariable=,
                         row=,
                         machineVariable=,
                         statusSetting="Running", 
                         startTimeVariable=startTime,
                         signon=1,
                         useGrid=1,
                         log=,
                         output=,
                         gridRC=,
                         cmacvar=etls_signonStatus,
                         additionalSignonOptions=,
                         signonRetries= ); 

   %local remoteSessionId; 
   %let remoteSessionId = &handlePrefix.&row; 
   %let &cmacvar = 1; 
   %local etls_machineId; 
   %if (&signon eq 1) %then 

      %etls_signon(handleName=&remoteSessionId,
                   useGrid=&useGrid,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=&etls_gridOptionSet,
                   workloadMacroVariable=&workloadMacroVariable,
                   log=&log,
                   output=&output,
                   cmacvar=&cmacvar,
                   gridRC=&gridRC,
                   additionalSignonOptions=&additionalSignonOptions,
					signonRetries=&signonRetries,
                   gridJobName=DIS_&etls_jobName._&row); 

   %else %let &cmacvar=0; 

   data &statusTable; 
      retain ptr &row; 
      modify &statusTable point = ptr; 
      &handleVariable = "&remoteSessionId"; 
      %if (&signon eq 1) %then 
         &machineVariable = "&etls_machineId";; 
      %if (&&&cmacvar ne 0) %then 
      %do; 
         &statusVariable = "Failed Signon"; 
      %end; 
      %else 
         &statusVariable = &statusSetting;; 
      %if (&startTimeVariable ne ) %then 
         &startTimeVariable = datetime();; 
      replace; 
      stop; 
   run; 

   %rcSet(&syserr); 
%mend etls_createHandle; 

%macro etls_getParameterNames(parameterTable=, parameterVariableMacro=, startingColumnNumber=1);
   %let &parameterVariableMacro = ;
   %let dsid = %sysfunc(open(&parameterTable));
   %if (&dsid gt 0) %then 
   %do; 
      %do i=&startingColumnNumber %to %sysfunc(attrn(&dsid,nvars)); 
         %let &parameterVariableMacro = &&&parameterVariableMacro %sysfunc(varname(&dsid,&i)); 
      %end; 
      %let dsid = %sysfunc(close(&dsid)); 
   %end; 
   %else 
      %put %sysfunc(sysmsg()); 
   %rcSet(&syserr); 
%mend etls_getParameterNames; 

%macro etls_getParameters(parameterTable=, row=, startingColumnNumber=1 , handleName=); 
   data _null_; 
      length vname $256 vtype $1 value $32767; 
      dsid = open("&parameterTable"); 
      if (dsid > 0) then 
      do; 
         do _i = 1 to &row; 
            fetchrc = fetch(dsid); 
         end; 
         do _i=&startingColumnNumber to attrn(dsid,'nvars'); 
            vname = varname(dsid,_i); 
            vtype = vartype(dsid,_i); 
            if (fetchrc = 0) then 
            do; 
               if (vtype = 'C') then 
               do; 
                  value = getvarc(dsid,_i); 
                  value = tranwrd(value,"%","%%"); 
                  value = tranwrd(value,"(","%("); 
                  value = tranwrd(value,")","%)"); 
                  value = tranwrd(value,'"','%"'); 
                  value = tranwrd(value,"'","%'"); 
               end; 
               else 
                  value = left(put(getvarn(dsid,_i),best32.)); 
            end; /* fetchrc = 0 */ 
            
            put ;
            if indexc(trimn(value),"+-*/<>=^~;, '()&%",'"')>0 then 
            do; 
               value='%nrstr('||trim(value)||')'; 
               put "ETLS_DIAG%QUOTE(:) Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
               put "NOTE: Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
            end; 
            %if %str(&handlename) ne %str() %then 
            %do; 
               value = '%syslput '||trim(vname)||'= '||trim(value)||" / remote = &handleName;"; 
            %end; 
            %else 
            %do; 
               value = '%let '||trim(vname)||'= '||trim(value)||';'; 
            %end; 
            
            put "NOTE: Setting macro variable " vname "with statement:" value ;
            call execute(value); 
         end; /* do i= */ 
         dsid = close(dsid); 
      end; /* dsid > 0 */ 
      else 
      do; 
         put "ERROR%QUOTE(:) Parameter table, &parameterTable., could not be"
              " opened.";
         abort; 
      end; 
      stop; 
   run; 
   
   %rcSet(&syserr); 
%mend etls_getParameters; 

/* Check return codes for all processes  */ 
%macro etls_loopRCCheck(statusTable=, returnCodeVariable=,start=,end=); 
   %macro etls_loopRCError(_iteration); 
      /* Abort with a return code of  2  */ 
      %abort return  2; 
   %mend etls_loopRCError; 
   
   %local etls_rows etls_dsid rc etls_varnum;
   
   %let etls_rows = 0; 
   proc sql noprint; 
      select count(*) into :etls_rows from &statusTable; 
   quit; 
   
   %if &start le &etls_rows %then 
   %do; 
      %let etls_dsid = %sysfunc(open(&statusTable)); 
      %if (&etls_dsid = 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %do i=&start %to &end; 
            %let rc = %sysfunc(fetchobs(&etls_dsid, &i)); 
            %if (&rc ne 0) %then 
               %put %sysfunc(sysmsg()); 
            %else 
            %do; 
               %let etls_varnum = %sysfunc(varnum(&etls_dsid,&returnCodeVariable)); 
               %if (&etls_varnum > 0) %then 
               %do; 
                  %if ((%sysfunc(getvarn(&etls_dsid,&etls_varnum)) ge 5) and 
                       (&&etls_statusReported&i eq 0)) %then 
                  %do; 
                     %etls_loopRCError(&i); 
                     %let etls_statusReported&i = 1; 
                  %end; 
               %end; 
               %else 
                  %put %sysfunc(sysmsg()); 
            %end; 
         %end; 
         %let rc = %sysfunc(close(&etls_dsid)); 
      %end; 
   %end; 
%mend etls_loopRCCheck; 

%macro etls_loopWVY21VJ; 
   %local etls_filePrefix; 
   %let etls_filePrefix = ; 
   
   %macro etls_processToLoopWVY21VT(parameterTable=, row=, handleName=rmt);
      %local etls_parmvars; 
      %etls_getParameterNames(parameterTable=&parameterTable, 
         parameterVariableMacro=etls_parmvars, 
         startingColumnNumber=1); 
      %local &etls_parmvars; 
      %etls_getParameters(parameterTable=&parameterTable, row=&row, 
         startingColumnNumber=1); 
      %let etls_previousFilePrefix = &etls_filePrefix;
      %local etls_filePrefix; 
      %let etls_filePrefix = &etls_previousFilePrefix.&handleName; 
      %macro etls_jobWVY21W3; 
      
         /**************************************************************************** 
          * Job:             RRAP_MOR_MODEL_60_inner               A57ZQ4A4.BF0011Q8 * 
          * Description:                                                             * 
          *                                                                          * 
          * Metadata Server: cs2iw503.bns                                            * 
          * Port:            8561                                                    * 
          * Location:        /User Folders/Hadi Dimashkieh/My Folder/Jobs/DLGD       * 
          *                   Insured Changes                                        * 
          *                                                                          * 
          * Server:          SASApp                                A57ZQ4A4.AT000002 * 
          *                                                                          * 
          * Generated on:    Wednesday, November 29, 2017 4:12:15 PM EST             * 
          * Generated by:    s2809211                                                * 
          * Version:         SAS Data Integration Studio 4.8                         * 
          ****************************************************************************/ 
         
         /* Generate the process id for job  */ 
         %put Process ID: &SYSJOBID;
         
         /* General macro variables  */ 
         %let jobID = %quote(A57ZQ4A4.BF0011Q8);
         %let etls_jobName = %nrquote(RRAP_MOR_MODEL_60_inner);
         %let etls_userID = %nrquote(s2809211);
         
         
         /* Create metadata macro variables */
         %let IOMServer      = %nrquote(SASApp);
         %let metaPort       = %nrquote(8561);
         %let metaServer     = %nrquote(cs2iw503);
         
         /* Set metadata options */
         options metaport       = &metaPort 
                 metaserver     = "&metaServer"; 
         
         /* Setup for capturing job status  */ 
         %let etls_startTime = %sysfunc(datetime(),datetime.);
         %let etls_recordsBefore = 0;
         %let etls_recordsAfter = 0;
         %let etls_lib = 0;
         %let etls_table = 0;
         
         %global etls_debug; 
         %macro etls_setDebug; 
            %if %str(&etls_debug) ne 0 %then 
               OPTIONS MPRINT%str(;); 
         %mend; 
         %etls_setDebug; 
         
         /*==========================================================================* 
          * Step:            AM_rrap_mortgage_autoexec             A57ZQ4A4.BO0018UQ * 
          * Transform:       AM_rrap_mor_bns_autoexec                                * 
          * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
          *                   transformation                                         * 
          *==========================================================================*/ 
         
         %let transformID = %quote(A57ZQ4A4.BO0018UQ);
         %let trans_rc = 0;
         %let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 
         
         %let _INPUT_count = 0; 
         %let _OUTPUT_count = 0; 
         
         
         %include '/sasdata/sasdi/sasdev/macro/rrap/rrap_autoexec.sas';
         %rrap_mor_bns_autoexec;
         
         %rcSet(&syserr); 
         %rcSet(&sysrc); 
         %rcSet(&sqlrc); 
         
         %rcSet(&syscc); 
         
         
         
         /**  Step end AM_rrap_mortgage_autoexec **/
         
         /*---- Start of User Written Code  ----*/ 
         
         /*---------------------------------------------------------------------
          * NAME:       06_bns_rpting_instrmnt_fact.sas
          *
          * PURPOSE:    Pulls together the data needed to feed into the reporting
          *             table BASEL_ANALYTCL_BL_INSTRMNT_FACT
          *             
          * NOTES:      General flow:
          *             1. Append Status (have values from basel_mort), hard-code
          *                values, add PD and EAD
          *             2. Add on BRDM data
          *             3. Add Product content
          *             4. Add LGD, impose other logic if needed, split between
          *                defaulters and non-defaulters
          *             5. Append LGD values to default/non-defaulted accounts
          *             6. Load to final table
          *             
          * MODIFIED:
          *    17JAN2015 - JL - Created
          *    27JAN2015 - JL - Removed notes; removed join to office ref table;
          *                     corrected join of product table to EGL
          *    31JAN2015 - JL - Major overhaul - move most items into NZ
          *    17Sep2015 - CV - Logic change on bns_lgd_d_segment = 14 per CR #53
          *		18Sep2015 - CV - Logic Change in the way adjusted_os_bal_amt is calculated, per CR #34
          *		07OCT2015 - CV - Changed bin logic for B_RATIO
          *							  Updated Scoring for bins B_RATIO, B_PROP_VALUE, B_LTV, B_DLQNT_DAYavg24m, B_BI33max3m, B_AMORT
          *							  Updated segmentation logic, per Item 39
          * Copyright (c) 2014 by The Financial Risk Group, Cary, NC, USA.
          *---------------------------------------------------------------------*/
         
          /*--------------------------------------------------------------------------------------
          
          	APRIL 2017 - Hadi Dimashkieh - Redesign to process only current months data.
         	 										 	Current Month - Used for Instrument Fact;
         											
          -----------------------------------------------------------------------------------------
         
         SOURCES:
         FRG_USER_DATA:
         segment_reporting_parm
         pd_band
         base_bns_mor_rpt_tbl
         BRDM_BASELAYER_MOR
         basel_ncr_ltv_dim
         
         TARGETS:
         intmed.bns_with_all_ratios_&_run_date_yymth
         FRG_USER_DATA.BNS_WITH_ALL_RTOS_&_run_Date_yymth._&filedate.
         FRG_USER_DATA.BASEL_ANALYTCL_BL_INST_FCT_BNS
         
         
         
         /*---- End of User Written Code  ----*/ 
         
         /*---- Start of User Written Code  ----*/ 
         
         /**** UNLOAD Month of Large_JOIN_DATA *******/
         proc sql noprint;
         	connect USING NZUSER as nzcon;
         	create table work.base_bns_mor_rpt_tbl as 
         		select * from connection to nzcon (	
         		select * from &target_lib3...base_bns_mor_rpt_tbl
         			where last_day(date_trunc('day',process_date)) = date(%nrbquote('&_run_date'))
         				);
         quit;
         
         /**** UNLOAD Month of BRDM_DATA *******/
         proc sql noprint;
         	select distinct cats(put(a.mth_tm_id, best32.))
         		into :tm_key separated by ','
         			from work.base_bns_mor_rpt_tbl as a;
         quit;
         
         %put tm_key = &tm_key;
         
         proc sql;
         	connect USING NZUSER as nzcon;
         	create table work.brdm_baselayer_mor as 
         		select * from connection to nzcon (	
         		select * from &target_lib3...BRDM_BASELAYER_MOR
         			where tm_id in (&tm_key);
         				);
         quit;
         
         proc sql;
         	connect USING NZUSER as nzcon;
         	create table work.BASEL_MORT_INSTRMNT_ADJ as 
         		select * from connection to nzcon (	
         		select * from &target_lib3...BASEL_MORT_INSTRMNT_ADJ
         			where mth_tm_id in (&tm_key);
         				);
         quit;
         
         proc datasets lib=work;
         modify BASEL_MORT_INSTRMNT_ADJ;
         rename GENL_LEDGER_BAL_ADJ_AMT=GENL_LEDGER_BALCNG_ADJ_AMT;
         run;
         
         
         /********Join Large Join to BRDM  ****************/
         
         proc sql;
         	create table work.base_with_brdm  as
         		select a.*,
         			b.*, bb.genl_ledger_balcng_adj_amt,
         		case 
         			when upcase(pit_stat_cd) ='DEF'
         			and upcase(paid_off_ind) ='Y'
         			and total_suspense < 0 
         			then (-1*total_suspense)
         		else a.os_bal_amt + bb.GENL_LEDGER_BALCNG_ADJ_AMT  
         		end 
         	as adjusted_os_bal_amt format = 20.8,
         		a.os_bal_amt + bb.GENL_LEDGER_BALCNG_ADJ_AMT as af_secrtztn_bal_amt format = 28.8,
         
         	coalesce(c.ncr_ltv_key_val, '0405') as ncr_ltv_key_val
         	from work.base_bns_mor_rpt_tbl as a 
         
         		left join
         			work.brdm_baselayer_mor(drop=GENL_LEDGER_BALCNG_ADJ_AMT) as b
         		on	(a.mortgage_no=input(b.mort_num,7.) and
         			a.mth_tm_id = b.tm_id)
         
         		left join work.BASEL_MORT_INSTRMNT_ADJ as bb
         			on input(b.mort_num,7.)=input(bb.mort_num,7.) and b.tm_id=bb.mth_tm_id
         
         		left join
         				nzuser.basel_ncr_ltv_dim as c
         				on  (a.loan_to_val_rto >= c.ltv_rto_min_val and 
         				a.loan_to_val_rto < c.ltv_rto_max_val)
         
         	;
         quit;
         
         
         
         /* LEGACY CODE */
         /********Join Large Join to BRDM  ****************/
         /*proc sql;*/
         /*	create table work.base_with_brdm  as*/
         /*		select a.*,*/
         /*			b.*,*/
         /*		case */
         /*			when upcase(pit_stat_cd) ='DEF'*/
         /*			and upcase(paid_off_ind) ='Y'*/
         /*			and total_suspense < 0 */
         /*			then (-1*total_suspense)*/
         /*		else a.os_bal_amt + b.genl_ledger_balcng_adj_amt */
         /*		end */
         /*	as adjusted_os_bal_amt format = 20.8,*/
         /*		a.os_bal_amt + b.genl_ledger_balcng_adj_amt as af_secrtztn_bal_amt format = 28.8,*/
         /*		*/
         /*	coalesce(c.ncr_ltv_key_val, '0405') as ncr_ltv_key_val*/
         /*	from work.base_bns_mor_rpt_tbl as a */
         /**/
         /*		left join*/
         /*			work.brdm_baselayer_mor as b*/
         /*			on (cats(put(a.mortgage_no, 21.))= b.mort_num and*/
         /*			a.mth_tm_id = b.tm_id)*/
         /**/
         /*			left join*/
         /*				nzuser.basel_ncr_ltv_dim as c*/
         /*				on  (a.loan_to_val_rto >= c.ltv_rto_min_val and */
         /*				a.loan_to_val_rto < c.ltv_rto_max_val)*/
         /**/
         /*	;*/
         /*quit;*/
         /*---- End of User Written Code  ----*/ 
         
         /*---- Start of User Written Code  ----*/ 
         
         /*---------------------------------------------------
          * 4. Score accounts for PD and LGD segments
          *---------------------------------------------------*/
         data work.with_scores;
            set work.base_with_brdm;
         
             length ccar_basel_prd_tp_nm  $50;
         
         
            /*-----------------------------------------------
             * Base scorecard points
             *-----------------------------------------------*/ 
            pd_sc_points = 559;
         
            /*-----------------------------------------------
             * Variable: amort;
             *-----------------------------------------------*/ 
            if missing(amort) then
            do;
               pd_sc_points = pd_sc_points + 22;
               scr_amort= 22;
            end;
            else if not missing(amort) and amort < 180 then
            do;
               pd_sc_points = pd_sc_points + 22;
               scr_amort = 22;
            end;
            else if not missing(amort) and 180 <= amort and amort < 270 then
            do;
               pd_sc_points = pd_sc_points + 10;
               scr_amort = 10;
            end;
            else if not missing(amort) and 270 <= amort then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_amort = 0;
            end;
         
            /*-----------------------------------------------
             * Variable: AT36;
             *-----------------------------------------------*/ 
            if missing(at36) then 
            do;
               pd_sc_points = pd_sc_points + 27;
               scr_at36= 27;
            end;
            else if not missing(at36) and at36 < 3 then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_at36 = 0;
            end;
            else if not missing(at36) and 3 <= at36 and at36 < 4 then
            do;
               pd_sc_points = pd_sc_points + 5;
               scr_at36 = 5;
            end;
            else if not missing(at36) and 4 <= at36 and at36 < 10 then
            do;
               pd_sc_points = pd_sc_points + 14;
               scr_at36 = 14;
            end;
            else if not missing(at36) and 10 <= at36 and at36 < 20 then
            do;
               pd_sc_points = pd_sc_points + 20;
               scr_at36 = 20;
            end;
            else if not missing(at36) and 20 <= at36 then 
            do;
               pd_sc_points = pd_sc_points + 27;
               scr_at36 = 27;
            end;
         
            /*-----------------------------------------------
             * Variable: AT94;
             *-----------------------------------------------*/ 
            if missing(at94) then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_at94 = 0;
            end;
            else if not missing(at94) and at94 < 5000 then 
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_at94 = 0;
            end;
            else if not missing(at94) and 5000 <= at94 and at94 < 14023 then
            do;
               pd_sc_points = pd_sc_points + 5;
               scr_at94 = 5;
            end;
            else if not missing(at94) and 14023 <= at94 and at94 < 30027 then
            do;
               pd_sc_points = pd_sc_points + 10;
               scr_at94 = 10;
            end;
            else if not missing(at94) and 30027 <= at94 and at94 < 51728 then
            do;
               pd_sc_points = pd_sc_points + 16;
               scr_at94 = 16;
            end;
            else if not missing(at94) and 51728 <= at94 then
            do;
               pd_sc_points = pd_sc_points + 23;
               scr_at94 = 23;
            end;
         
            /*-----------------------------------------------
             * Variable: BR147max6m;
             *-----------------------------------------------*/ 
            if missing(br147max6m) then 
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_br147max6m= 0;
            end;
            else if not missing(br147max6m) and br147max6m < 69 then
            do;
               pd_sc_points = pd_sc_points + 21;
               scr_br147max6m = 21;
            end;
            else if not missing(br147max6m) and 69 <= br147max6m and br147max6m < 100 then
            do;
               pd_sc_points = pd_sc_points + 15;
               scr_br147max6m = 15;
            end;
            else if not missing(br147max6m) and 100 <= br147max6m and br147max6m < 105 then
            do;
               pd_sc_points = pd_sc_points + 5;
               scr_br147max6m = 5;
            end;
            else if not missing(br147max6m) and 105 <= br147max6m then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_br147max6m = 0;
            end;
         
            /*-----------------------------------------------
             * Variable: CUST_ACCT_CNT;
             *-----------------------------------------------*/ 
            if missing(cust_acct_cnt) then 
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_cust_acct_cnt = 0;
            end;
            else if not missing(cust_acct_cnt) and cust_acct_cnt < 5 then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_cust_acct_cnt = 0;
            end;
            else if not missing(cust_acct_cnt) and 5 <= cust_acct_cnt and cust_acct_cnt < 10 then
            do;
               pd_sc_points = pd_sc_points + 7;
               scr_cust_acct_cnt = 7;
            end;
            else if not missing(cust_acct_cnt) and 10 <= cust_acct_cnt then
            do;
               pd_sc_points = pd_sc_points + 17;
               scr_cust_acct_cnt = 17;
            end;
         
            /*-----------------------------------------------
             * Variable: D2DBALPmin6m;
             *-----------------------------------------------*/ 
            if missing(d2dbalpmin6m) then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_d2dbalpmin6m = 0;
            end;
            else if not missing(d2dbalpmin6m) and d2dbalpmin6m < 0 then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_d2dbalpmin6m = 0;
            end;
            else if not missing(d2dbalpmin6m) and 0 <= d2dbalpmin6m and d2dbalpmin6m < 225.27 then
            do;
               pd_sc_points = pd_sc_points + 5;
               scr_d2dbalpmin6m = 5;
            end;
            else if not missing(d2dbalpmin6m) and 225.27 <= d2dbalpmin6m then
            do;
               pd_sc_points = pd_sc_points + 17;
               scr_d2dbalpmin6m = 17;
            end;
         
            /*-----------------------------------------------
             * Variable: DLQNT_DAY;
             *-----------------------------------------------*/ 
            if missing(dlqnt_day) then
            do;
               pd_sc_points = pd_sc_points + 71;
               scr_dlqnt_day= 71;
            end;
            else if not missing(dlqnt_day) and dlqnt_day < 1 then
            do;
               pd_sc_points = pd_sc_points + 71;
               scr_dlqnt_day = 71;
            end;
            else if not missing(dlqnt_day) and 1 <= dlqnt_day and dlqnt_day < 30 then
            do;
               pd_sc_points = pd_sc_points + 33;
               scr_dlqnt_day = 33;
            end;
            else if not missing(dlqnt_day) and 30 <= dlqnt_day and dlqnt_day < 60 then
            do;
               pd_sc_points = pd_sc_points + 15;
               scr_dlqnt_day = 15;
            end;
            else if not missing(dlqnt_day) and 60 <= dlqnt_day then 
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_dlqnt_day = 0;
            end;
         
            /*-----------------------------------------------
             * Variable: DLQNT_MTHmax24m;
             *-----------------------------------------------*/ 
            if missing(dlqnt_mthmax24m) then 
            do;
               pd_sc_points = pd_sc_points + 68;
               scr_dlqnt_mthmax24m= 68;
            end;
            else if not missing(dlqnt_mthmax24m) and dlqnt_mthmax24m < 1 then
            do;
               pd_sc_points = pd_sc_points + 68;
               scr_dlqnt_mthmax24m = 68;
            end;
            else if not missing(dlqnt_mthmax24m) and 1 <= dlqnt_mthmax24m and dlqnt_mthmax24m < 2 then 
            do;
               pd_sc_points = pd_sc_points + 38;
               scr_dlqnt_mthmax24m = 38;
            end;
            else if not missing(dlqnt_mthmax24m) and 2 <= dlqnt_mthmax24m and dlqnt_mthmax24m < 3 then
            do;
               pd_sc_points = pd_sc_points + 12;
               scr_dlqnt_mthmax24m = 12;
            end;
            else if not missing(dlqnt_mthmax24m) and 3 <= dlqnt_mthmax24m then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_dlqnt_mthmax24m = 0;
            end;
         
            /*-----------------------------------------------
             * Variable: GO04max6m;
             *-----------------------------------------------*/ 
            if missing(go04max6m) then
            do;
               pd_sc_points = pd_sc_points + 6;
               scr_go04max6m= 6;
            end;
            else if not missing(go04max6m) and go04max6m < 5 then
            do;
               pd_sc_points = pd_sc_points + 17;
               scr_go04max6m = 17;
            end;
            else if not missing(go04max6m) and 5 <= go04max6m and go04max6m < 7 then
            do;
               pd_sc_points = pd_sc_points + 12;
               scr_go04max6m = 12;
            end;
            else if not missing(go04max6m) and 7 <= go04max6m and go04max6m < 11 then
            do;
               pd_sc_points = pd_sc_points + 6;
               scr_go04max6m = 6;
            end;
            else if not missing(go04max6m) and 11 <= go04max6m then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_go04max6m = 0;
            end;
         
            /*-----------------------------------------------
             * Variable: LTV;
             *-----------------------------------------------*/ 
            if missing(ltv) then 
            do;
               pd_sc_points = pd_sc_points + 7;
               scr_ltv= 7;
            end;
            else if not missing(ltv) and ltv < 0.4 then
            do;
               pd_sc_points = pd_sc_points + 7;
               scr_ltv = 7;
            end;
            else if not missing(ltv) and 0.4 <= ltv and ltv < 0.76 then
            do;
               pd_sc_points = pd_sc_points + 4;
               scr_ltv = 4;
            end;
            else if not missing(ltv) and 0.76 <= ltv then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_ltv = 0;
            end;
         
            /*-----------------------------------------------
             * Variable: NSF_NUMmax6m;
             *-----------------------------------------------*/ 
            if missing(nsf_nummax6m) then
            do;
               pd_sc_points = pd_sc_points + 24;
               scr_nsf_nummax6m= 24;
            end;
            else if not missing(nsf_nummax6m) and nsf_nummax6m < 1 then
            do;
               pd_sc_points = pd_sc_points + 24;
               scr_nsf_nummax6m = 24;
            end;
            else if not missing(nsf_nummax6m) and 1 <= nsf_nummax6m and nsf_nummax6m < 3 then
            do;
               pd_sc_points = pd_sc_points + 7;
               scr_nsf_nummax6m = 7;
            end;
            else if not missing(nsf_nummax6m) and 3 <= nsf_nummax6m then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_nsf_nummax6m = 0;
            end;
         
            /*-----------------------------------------------
             * Variable: PAYROLL_AMTmin3m;
             *-----------------------------------------------*/ 
            if missing(payroll_amtmin3m) then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_payroll_amtmin3m= 0;
            end;
            else if not missing(payroll_amtmin3m) and payroll_amtmin3m < 1747.32 then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_payroll_amtmin3m = 0;
            end;
            else if not missing(payroll_amtmin3m) and 1747.32 <= payroll_amtmin3m and payroll_amtmin3m < 3520.08 then 
            do;
               pd_sc_points = pd_sc_points + 14;
               scr_payroll_amtmin3m = 14;
            end;
            else if not missing(payroll_amtmin3m) and 3520.08 <= payroll_amtmin3m then 
            do;
               pd_sc_points = pd_sc_points + 28;
               scr_payroll_amtmin3m = 28;
            end;
         
            /*-----------------------------------------------
             * Variable: PREPAY_YTDmax24m;
             *-----------------------------------------------*/ 
            if missing(prepay_ytdmax24m) then 
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_prepay_ytdmax24m= 0;
            end;
            else if not missing(prepay_ytdmax24m) and prepay_ytdmax24m < 282.6 then
            do;
               pd_sc_points = pd_sc_points + 0;
               scr_prepay_ytdmax24m = 0;
            end;
            else if not missing(prepay_ytdmax24m) and 282.6 <= prepay_ytdmax24m then
            do;
               pd_sc_points = pd_sc_points + 17;
               scr_prepay_ytdmax24m = 17;
            end;
         
            /*-----------------------------------------------
             * ASSIGN SEGMENT
             *-----------------------------------------------*/ 
         
            /* If pd_sc_points is not missing then assign segment 2 through 8 */
            if not missing(pd_sc_points) then
            do;
               if pd_sc_points < 646.5 then pd_segment  = 8;
               else if 646.5 <= pd_sc_points and pd_sc_points < 689.5 then pd_segment = 7;
               else if 689.5 <= pd_sc_points and pd_sc_points < 712.5 then pd_segment = 6;
               else if 712.5 <= pd_sc_points and pd_sc_points < 738.5 then pd_segment = 5;
               else if 738.5 <= pd_sc_points and pd_sc_points < 767.5 then pd_segment = 4;
               else if 767.5 <= pd_sc_points and pd_sc_points < 802.5 then pd_segment = 3;
               else if 802.5 <= pd_sc_points and pd_sc_points < 832.5 then pd_segment = 2;
               else pd_segment  = 1;
            end;
         
            if upcase(pit_stat_cd) = 'CUR' then
            do;
         
               /*-----------------------------------------------
                * Base scorecard points
                *-----------------------------------------------*/ 
               lgdnd_sc_points = 0;
         
               /*-----------------------------------------------
                * Variable: ltv
                *-----------------------------------------------*/ 
               if  not missing(ltv) and ltv < 0.45 then
               do;
                  b_ltv = 1;
               end;
               else if not missing(ltv) and 0.65 <= ltv then
               do;
                  b_ltv = 3;
               end;
               else
               do;
                  b_ltv = 2;
               end;
         
               /*-----------------------------------------------
                * Variable: index_teranetv
                *-----------------------------------------------*/ 
               if not missing(index_teranetv) and index_teranetv < 135000 then
               do;
                  b_prop_value = 1;
               end;
               else if not missing(index_teranetv) and 1067000 <= index_teranetv then
               do;
                 b_prop_value = 1;
               end;
               else 
               do;
                  b_prop_value = 2;
               end;
         
               /*-----------------------------------------------
                * Variable: bi33max3m
                *-----------------------------------------------*/ 
               if not missing(bi33max3m) and 14445 <= bi33max3m then
               do;
                  b_bi33max3m = 2;
               end;
               else 
               do;
                  b_bi33max3m = 1;
               end;
         
               /*-----------------------------------------------
                * Variable: amort
                *-----------------------------------------------*/ 
               if not missing(amort) and 220 <= amort and amort < 450 then
               do;
                 b_amort = 2;
               end;
               else if not missing(amort) and 450 <= amort then
               do;
                 b_amort = 3;
               end;
               else 
               do;
                 b_amort = 1;
               end;
         
               /*-----------------------------------------------
                * Variable: dlqnt_dayavg24m
                *-----------------------------------------------*/ 
               if not missing(dlqnt_dayavg24m) and 6.717803030303 <= dlqnt_dayavg24m and dlqnt_dayavg24m < 28.8452380952381 then
               do;
                 b_dlqnt_dayavg24m = 2;
               end;
               else if not missing(dlqnt_dayavg24m) and 28.8452380952381 <= dlqnt_dayavg24m then
               do;
                 b_dlqnt_dayavg24m = 2;
               end;
               else
               do;
                 b_dlqnt_dayavg24m = 1;
               end;
         
               /*-----------------------------------------------
                * Variable: ratio
                *-----------------------------------------------*/ 
               if upcase(Province_cd) in ('PE' 'NS' 'NF' 'NB') or missing(Province_cd) or 
                  upcase(Province_cd) in ('AB' 'BC' 'MB' 'SK' 'NW' 'YK') and ratio >=-0.1877 then
               do;
                  b_ratio = 1;
               end;
               else if upcase(Province_cd) ='QC' or
                       upcase(Province_cd) in ('AB' 'BC' 'MB' 'SK' 'NW' 'YK') and ratio <-0.1877 or missing(ratio) then
               do;
                  b_ratio = 2;
               end;
               else
               do;
                  b_ratio = 3;
               end;
         
         
               /*-----------------------------------------------
                * Apply scores
                *-----------------------------------------------*/ 
               if b_amort = 1 then sb_amort = 0;
               if b_amort = 2 then sb_amort = 45;
               if b_amort = 3 then sb_amort = 185;
         
               if b_bi33max3m = 1 then sb_bi33max3m = 0 ;
               if b_bi33max3m = 2 then sb_bi33max3m = 119;
         
               if b_dlqnt_dayavg24m = 1 then sb_dlqnt_dayavg24m = 74 ;
               if b_dlqnt_dayavg24m = 2 then sb_dlqnt_dayavg24m = 0 ;
         
               if b_ltv = 1 then sb_ltv = 0;
               if b_ltv = 2 then sb_ltv = 87;
               if b_ltv = 3 then sb_ltv = 151;
         
               if b_prop_value = 1 then sb_prop_value = 201 ;
               if b_prop_value = 2 then sb_prop_value = 0 ;
         
               if b_ratio = 1 then sb_ratio = 270;
               if b_ratio = 2 then sb_ratio = 115;
               if b_ratio = 3 then sb_ratio = 0;
         
               lgdnd_sc_points = sb_amort + sb_bi33max3m + sb_dlqnt_dayavg24m + sb_ltv + sb_prop_value + sb_ratio;
         
               /*-----------------------------------------------
                * ASSIGN SEGMENT
         		
         		 * UPDATED 07OCT2015
                *-----------------------------------------------*/ 
         
               /* Confirmed this is model exclusion criteria */
               if total_bal_for_ltv <= 5000 then bns_lgd_nd_segment = 13;
         
               /*--------------------------
                * UNINSURED
                *--------------------------*/ 
               else if upcase(insurance) = 'UNINSURED' then
               do;
                  if not missing(lgdnd_sc_points) and 166 <= lgdnd_sc_points and lgdnd_sc_points < 370 then
                  do;
                     bns_lgd_nd_segment = 2;
                  end;
                  else if not missing(lgdnd_sc_points) and 370 <= lgdnd_sc_points and lgdnd_sc_points < 640 then
                  do;
                     bns_lgd_nd_segment = 3;
                  end;
                  else if not missing(lgdnd_sc_points) and 640 <= lgdnd_sc_points then
                  do;
                     bns_lgd_nd_segment = 4;
                  end;
                  else
                  do;
                     bns_lgd_nd_segment = 1;
                  end;
               end;
         
               /*--------------------------
                * INSURED
                *--------------------------*/ 
               else if upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'N' then
               do;
                  if not missing(lgdnd_sc_points) and 166 <= lgdnd_sc_points and lgdnd_sc_points < 370 then
                  do;
                     bns_lgd_nd_segment =  6;
                  end;
                  else if not missing(lgdnd_sc_points) and 370 <= lgdnd_sc_points and lgdnd_sc_points < 640 then
                  do;
                     bns_lgd_nd_segment = 7;
                  end;
                  else if not missing(lgdnd_sc_points) and 640 <= lgdnd_sc_points then
                  do;
                     bns_lgd_nd_segment = 8;
                  end;
                  else
                  do;
                     bns_lgd_nd_segment = 5;
                  end;
               end;
         
               else if upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'Y' then
               do;
                  if not missing(lgdnd_sc_points) and 166 <= lgdnd_sc_points and lgdnd_sc_points < 370 then
                  do;
                     bns_lgd_nd_segment = 10;
                  end;
                  else if not missing(lgdnd_sc_points) and 370 <= lgdnd_sc_points and lgdnd_sc_points < 640 then
                  do;
                     bns_lgd_nd_segment = 11;
                  end;
                  else if not missing(lgdnd_sc_points) and 640 <= lgdnd_sc_points then
                  do;
                     bns_lgd_nd_segment = 12;
                  end;
                  else 
                  do;
                     bns_lgd_nd_segment = 9;
                  end;
               end;
            end;
         
            else if upcase(pit_stat_cd) = 'DEF' then
            do;
         
               /*-----------------------------------------------
                * Base scorecard points
                *-----------------------------------------------*/ 
               lgdd_sc_points = 0;
         
               /*-----------------------------------------------
                * Variable: _arbfmt_1 (i.e., foreclose_ind)
                *-----------------------------------------------*/ 
               if upcase(foreclose_ind) in ('Y') then 
               do;
                  b_foreclose_ind = 1;
               end;
               else
               do;
                  b_foreclose_ind =  2;
               end;
         
               /*-----------------------------------------------
                * Variable: ratio & urate
                *-----------------------------------------------*/ 
               if not missing(ratio) and 0.1478 <= ratio or urate>=0.1 then
               do;
                  b_unemp_rate_ratio = 2;
               end;
               else 
               do;
                  b_unemp_rate_ratio =  1;
               end;
         
               /*-----------------------------------------------
                * Variable: d2dbalmax12m
                *-----------------------------------------------*/ 
               if not missing(d2dbalmax12m) and d2dbalmax12m < 499.2 then
               do;
                  b_d2dbalmax12m = 1;
               end;
               else 
               do;
                  b_d2dbalmax12m = 2;
               end;
         
               /*-----------------------------------------------
                * Variable: month_def
                *-----------------------------------------------*/ 
         
         
               if not missing(cons_dft_mth_cnt) and 6.5 <= cons_dft_mth_cnt and cons_dft_mth_cnt < 11.5 then
               do;
                  b_month_def = 2;
               end;
               else if not missing(cons_dft_mth_cnt) and 11.5 <= cons_dft_mth_cnt and cons_dft_mth_cnt < 15.5 then
               do;
                  b_month_def = 3;
               end;
               else if not missing(cons_dft_mth_cnt) and 15.5 <= cons_dft_mth_cnt then
               do;
                  b_month_def = 4;
               end;
               else 
               do;
                  b_month_def = 1;
               end;
         
         
         
               /*-----------------------------------------------
                * Variable: index_teranetV
                *-----------------------------------------------*/ 
               if not missing(index_teranetV) and 151065.35 <= index_teranetV and index_teranetV < 1000000 then
               do;
                  b_index_teranetv = 2;
               end;
               else 
               do;
                  b_index_teranetv = 1;
               end;
         
               /*-----------------------------------------------
                * Variable: ltv
                *-----------------------------------------------*/       
               if not missing(ltv) and 0.6589 < ltv then
               do;
                  b_ltv = 2;
               end;
               else 
               do;
                  b_ltv = 1;
               end;
         
               /*-----------------------------------------------
                * Apply scores - From BRD (pg 29)
                *-----------------------------------------------*/ 
               if b_foreclose_ind = 1 then score_foreclose_ind = 166;
               if b_foreclose_ind = 2 then score_foreclose_ind = 0;
               if b_unemp_rate_ratio = 1 then score_unemp_ratio = 0;
               if b_unemp_rate_ratio = 2 then score_unemp_ratio = 64;
               if b_d2dbalmax12m = 1 then score_d2dbalmax12m = 42;
               if b_d2dbalmax12m = 2 then score_d2dbalmax12m = 0;
               if b_month_def = 1 then score_month_def = 0;
               if b_month_def = 2 then score_month_def = 216;
               if b_month_def = 3 then score_month_def = 361;
               if b_month_def = 4 then score_month_def = 540;
               if b_index_teranetv = 1 then score_index_teranetv = 137;
               if b_index_teranetv = 2 then score_index_teranetv = 0;
               if b_ltv = 1 then score_ltv = 0;
               if b_ltv = 2 then score_ltv = 50;
         
               lgdd_sc_points = score_foreclose_ind + score_unemp_ratio + score_d2dbalmax12m + score_month_def + score_index_teranetv + score_ltv;
         
               /*-----------------------------------------------
                * ASSIGN SEGMENT - From BRD (pg 30)
                *-----------------------------------------------*/ 
         
               /* Changed: 13JAN2015 - for total_bal: < --> <= */
               /*special segments 13 and 14*/
               if month_def >= 24 then bns_lgd_d_segment = 14;
               else if total_bal <= 5000 and month_def < 24 then bns_lgd_d_segment = 13;
         
               /* Uninsured accounts */
               else if (lgdd_sc_points = . or lgdd_sc_points < 247) and upcase(insurance) = 'UNINSURED' then
               do;
                  bns_lgd_d_segment = 1;
               end;
         
               else if lgdd_sc_points >= 247 and lgdd_sc_points <= 496 and upcase(insurance) = 'UNINSURED' then
               do;
                  bns_lgd_d_segment = 2;
               end;
               else if lgdd_sc_points >= 497 and lgdd_sc_points <= 647 and upcase(insurance) = 'UNINSURED' then
               do;
                  bns_lgd_d_segment = 3;
               end;
               else if lgdd_sc_points >= 648 and upcase(insurance) = 'UNINSURED' then
               do;
                  bns_lgd_d_segment = 4;
               end;
         
               /* Insured accounts, not bulk */
               else if (lgdd_sc_points = . or lgdd_sc_points < 247) and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'N' then
               do;
                  bns_lgd_d_segment = 5;
               end;
               else if lgdd_sc_points >= 247 and lgdd_sc_points <= 496 and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'N' then
               do;
                  bns_lgd_d_segment = 6;
               end;
               else if lgdd_sc_points >= 497 and lgdd_sc_points <= 647 and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'N' then
               do;
                  bns_lgd_d_segment = 7;
               end;
               else if lgdd_sc_points >= 648 and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'N' then
               do;
                  bns_lgd_d_segment = 8;
               end;
         
               /* Insured accounts, bulk */
               else if (lgdd_sc_points = . or lgdd_sc_points < 247) and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'Y' then
               do;
                  bns_lgd_d_segment = 9;
               end;
               else if lgdd_sc_points >= 247 and lgdd_sc_points <= 496 and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'Y' then
               do;
                  bns_lgd_d_segment = 10;
               end;
               else if lgdd_sc_points >= 497 and lgdd_sc_points <= 647 and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'Y'  then
               do;
                  bns_lgd_d_segment = 11;
               end;
               else if lgdd_sc_points >= 648 and upcase(insurance) = 'INSURED' and upcase(bulk_ind) = 'Y' then
               do;
                  bns_lgd_d_segment = 12;
               end;
         
            end;
         
         /*---------------------------------------------------
             * For accounts without segment from history or who 
             * don't have segment from exclusion, missing status
             *  or PD default, give segment from current data
             *---------------------------------------------------*/
         /* FF 06FEB 2015 Changed ***/
           pd_basel_seg_num = pd_segment;
           if upcase(pit_stat_cd) = 'CUR' then lgd_basel_seg_num = bns_lgd_nd_segment;
           else if upcase(pit_stat_cd) = 'DEF' then lgd_basel_seg_num = bns_lgd_d_segment;
            
            /*-----------------------------------------------
             * Excluded accounts get 98
             *-----------------------------------------------*/ 
            if (current_bal <= 0 and total_suspense = 0) and upcase(paid_off_ind) = 'Y' then 
            do;
               pd_basel_seg_num = 98;
               lgd_basel_seg_num = 98;
            end;
         
            /*-----------------------------------------------
             * Accounts with missing status get 98
             *-----------------------------------------------*/ 
            if upcase(pit_stat_cd) = '' then 
            do;
               pd_basel_seg_num = 98;
               lgd_basel_seg_num = 98;
            end;
         
            /*-----------------------------------------------
             * Accounts in default get PD segment 99
             *-----------------------------------------------*/ 
            if upcase(pit_stat_cd) = 'DEF' then 
            do;
               pd_basel_seg_num = 99;
            end;
               
           
         
           pd_acct_score = pd_sc_points;
           if upcase(pit_stat_cd) = 'CUR' then lgd_acct_score = lgdnd_sc_points;
           else if upcase(pit_stat_cd) = 'DEF' then lgd_acct_score = lgdd_sc_points; 
         
         
            ccar_basel_prd_tp_nm = cats(ccar_basel_product_type_name,'_', cats(put(pd_basel_seg_num, z2.)), '_01_', cats(put(lgd_basel_seg_num, z2.)));
         
         run;
         /*---- End of User Written Code  ----*/ 
         
         /*---- Start of User Written Code  ----*/ 
         
         /*---------------------------------------------------
          * 5. Join BRDM table to MORT table and include LTV
          *    values
          *---------------------------------------------------*/
         proc sql noprint;
            create table intmed.bns_with_all_ratios_&_run_date_yymth. (drop = pd_band_exposure_class_key_value) as
            select a.*,
         
                   /* PD ratios */
                   b.se_lr_ratio as pd_lr_rptg_rto format = 28.8,
                   b.se_lr_pv_ratio as pd_lr_pv_rptg_rto format = 28.8,
                   b.se_lr_pv_ad_ratio as pd_lr_pv_ad_rptg_rto format = 28.8,
                   b.se_lr_pv_ad_sv_ratio as pd_ld_pv_ad_sv_rptg_rto format = 28.8,
                   b.final_ratio as pd_final_rptg_rto format = 28.8, 
                   b.se_lr_pv_ad_sv_dt_aa_ratio as pd_lr_pv_ad_sv_dt_aa_rto format = 28.8,
                   b.realized_rate as pd_unadjusted_rptg_rto format = 28.8,
         
                   /* LGD ratios */
                   c.se_lr_ratio as lgd_lr_rptg_rto format = 28.8,
                   c.se_lr_pv_ratio as lgd_lr_pv_rptg_rto format = 28.8,
                   c.se_lr_pv_ad_ratio as lgd_lr_pv_ad_rptg_rto format = 28.8,
                   c.se_lr_pv_ad_sv_ratio as lgd_ld_pv_ad_sv_rptg_rto format = 28.8,
                   c.se_lr_pv_ad_sv_dt_ratio as lgd_ld_pv_ad_sv_dt_rptg_rto format = 28.8,
                   c.final_ratio as lgd_final_rptg_rto format = 28.8, 
                   c.se_lr_pv_ad_sv_dt_aa_ratio as lgd_lr_pv_ad_sv_dt_aa_rto format = 28.8,
                   c.realized_rate as lgd_unadjusted_rptg_rto format = 28.8,
         		    c.PRE_INSURANCE_LGD as lgd_insured_rptg_rto format= 28.8,   /* HADI - NEW FIELD */
                   /* PD band values */
                   d.ncr_pd_band_key_value,
                   cats(put(d.ncr_pd_band_key_value,best10.)) as ncr_pd_band_key_val length = 4,
                   cats(put(d.pd_band, best10.)) as pd_band length = 10
                    
            from work.with_scores as a
                 left join
                 nzuser.segment_reporting_parm as b
                 on (upcase(a.pd_model_nm) = upcase(b.model_name) and
                     a.pd_basel_seg_num = b.segment_no)
         
                 left join
                 nzuser.segment_reporting_parm as c
                 on (upcase(a.lgd_model_nm) = upcase(c.model_name) and
                     a.lgd_basel_seg_num = c.segment_no)
                  
                 left join
                 nzuser.pd_band as d
                 on (cats(a.pd_band_exposure_class_key_value) = cats(d.pd_band_exposure_class_key_value) and
          /*  changed 2/6 */           b.final_ratio between d.pd_minimum_value and d.pd_maximum_value);
         quit;
         
         /*---- End of User Written Code  ----*/ 
         
         /*---- Start of User Written Code  ----*/ 
         
         %macro airb_mort_accts;
         proc sql;
         	create table airb_mort_accts as
         	select mort_num
         	from nzuser.airb_mort_mth_snapshot
         	where tm_id=&tm_key 
         	%if %eval(&tm_key) GE 16996 %then %do;
         	and gl_trnst_num NOT IS MISSING
         	%end;
         	order by mort_num;
         quit;
         %mend airb_mort_accts;
         %airb_mort_accts;
         /*(bulkload=yes bl_options="ctrlchars true nullvalue ' ' " )*/
         proc sql noprint;
            insert into nzuser.BASEL_ANALYTCL_BL_INST_FCT_BNS (bulkload=yes)
            select a.mth_tm_id,
                  a.src_sys_cd,
                  a.basel_acct_id,
                  a.unq_acct_id,
                  a.ncr_rt_sys_key_val,
                  a.ncr_pd_band_key_val,
                  a.ncr_expsr_size_key_val,
                  a.ncr_geo_key_val,
                  a.ncr_ltv_key_val,
                  a.ncr_expsr_cl_key_val,
                  a.ncr_rt_key_val,
                  a.ncr_dlqnt_bckt_key_val,
                  a.pit_stat_cd,
                  a.utltn_rto,
                  a.acct_odt,
                  a.trnst_num,
                  a.cr_lmt_amt,
                  a.advnc_amt,
                  a.auth_amt,
                  a.os_bal_amt,
                  a.genl_ledger_balcng_adj_amt,
                  a.adjusted_os_bal_amt,
                  a.unadjusted_add_on_bal_amt,
                  a.af_secrtztn_bal_amt,
                  a.dlqnt_day_cnt,
                  a.before_zero_net_undrawn_amt,
                  a.before_zero_net_drawn_amt,
                  a.orig_prpty_val_amt,
                  a.loan_to_val_rto,
                  a.indexed_prpty_val_amt,
                  a.indexed_loan_to_val_rto,
                  a.pd_model_nm,
                  a.pd_model_ver,
                  a.pd_basel_scorecrd_nm,
                  a.pd_scorecrd_ver,
                  a.pd_basel_seg_num,
                  a.pd_basel_seg_id,
                  a.pd_seg_ver,
                  a.pd_basel_model_rel_id,
                  a.pd_model_rto,
                  a.pd_lr_rptg_rto,
                  a.pd_lr_pv_rptg_rto,
                  a.pd_lr_pv_ad_rptg_rto,
                  a.pd_ld_pv_ad_sv_rptg_rto,
                  a.pd_acct_score,
                  a.pd_final_rptg_rto,
                  a.lgd_model_nm,
                  a.lgd_model_ver,
                  a.lgd_basel_scorecrd_nm,
                  a.lgd_scorecrd_ver,
                  a.lgd_basel_seg_num,
                  a.lgd_basel_seg_id,
                  a.lgd_seg_ver,
                  a.lgd_basel_model_rel_id,
                  a.lgd_model_rto,
                  a.lgd_lr_rptg_rto,
                  a.lgd_lr_pv_rptg_rto,
                  a.lgd_lr_pv_ad_rptg_rto,
                  a.lgd_ld_pv_ad_sv_rptg_rto,
                  a.lgd_acct_score,
                  a.lgd_ld_pv_ad_sv_dt_rptg_rto,
                  a.ead_model_nm,
                  a.ead_model_ver,
                  a.lgd_final_rptg_rto,
                  a.ead_basel_scorecrd_nm,
                  a.ead_scorecrd_ver,
                  a.ead_basel_seg_num,
                  a.ead_basel_seg_id,
                  a.ead_seg_ver,
                  a.ead_basel_model_rel_id,
                  a.ead_model_rto,
                  a.ead_lr_rptg_rto,
                  a.ead_lr_pv_rptg_rto,
                  a.ead_acct_score,
                  a.ead_lr_pv_ad_rptg_rto,
                  a.asst_cl_desc,
                  a.cons_dft_mth_cnt,
                  a.ead_ld_pv_ad_sv_rptg_rto,
                  a.ead_ld_pv_ad_sv_dt_rptg_rto,
                  a.bcar_sched_num,
                  a.ead_final_rptg_rto,
                  a.pd_band,
                  a.basel_prd_abr,
                  a.scrty_tp_desc,
                  a.ccar_basel_prd_tp_nm,
                  a.ccar_expsr_cl_nm,
                  a.basel_prd_tp_cd,
                  a.consm_prd_treatmnt_cd,
                  a.prd_id,
                  a.prim_cust_cid,
                  a.acct_num,
                  a.rgnl_offc_cd,
                  a.dlqnt_stg,
                  a.mort_num,
                  a.cab_trnst_num,
                  a.egl_deprtmnt,
                  a.basel_cif_key,
                  a.loan_num,
                  a.intr_accr_amt,
                  a.cust_behv_score,
                  a.prd_cd,
                  a.sub_prd_cd,
                  a.src_prd_desc,
                  a.legal_entity,
                  a.mat_dt,
                  a.last_pymt_dt,
                  a.scrty_tp_cd,
                  a.step_f,
                  a.last_acty_dt,
                  a.house_tp_nm,
                  a.last_rgl_pay_dt,
                  a.pd_off_f,
                  a.pd_off_dt,
                  a.residual_mat,
                  a.asst_cl_num,
                  a.e_mat_dt,
                  a.amort,
                  a.trnst_exclsn_f,
                  a.sml_bus_f,
                  a.note_dt,
                  datetime() as insrt_process_tmstmp format = datetime21.,
                  datetime() as updt_process_tmstmp format = datetime21.,
                  a.af_zero_net_drawn_amt,
                  a.af_zero_net_undrawn_amt,
                  a.pd_unadjusted_rptg_rto,
                  a.lgd_unadjusted_rptg_rto,
         			a.lgd_insured_rptg_rto, /*HADI - NEW FIELD */
                  a.ead_unadjusted_rptg_rto,
                  a.pd_lr_pv_ad_sv_dt_aa_rto,
                  a.lgd_lr_pv_ad_sv_dt_aa_rto,
                  a.ead_lr_pv_ad_sv_dt_aa_rto
            from intmed.bns_with_all_ratios_&_run_date_yymth as a, airb_mort_accts as b
         	where input(a.mort_num,7.)=b.mort_num;
         quit;
         
         /*Hadi Dimashkieh - 13JUL2017*/
         /*inner join on mort_num and date to filter out accounts where gl_trnst is null.*/
         
         
         /*---- End of User Written Code  ----*/ 
         
         %let etls_endTime = %sysfunc(datetime(),datetime.);
         
         
         
         /**  Job end RRAP_MOR_MODEL_60_inner **/
         
         /* Reset jobid and name */
         %let jobID = %quote(A57ZQ4A4.BF0011Q9);
         %let etls_jobName = %nrquote(RRAP_MOR_MODEL_60);
         
      %mend etls_jobWVY21W3; 
      
      %etls_jobWVY21W3; 
      
      %let handleName = %etls_getHandle(statusTable=&etls_statusTable,
         handleVariable=etls_handleName, row=&&&etls_controlName);
         
      %let job_rc&handleName. = &job_rc; 
      
      %etls_freeHandle(statusTable=&etls_statusTable, statusVariable=etls_status, 
         handleVariable=etls_handleName, handleName="&handleName", 
         startTimeVariable=etls_startTime, endTimeVariable=etls_endTime, signoff=0, 
         returnCodeVariable=etls_jobRC, returnCodeMacroVariable=job_rc&handleName., setMainJobRc=1); 
         
   %mend etls_processToLoopWVY21VT;
   
   %local etls_controlTable etls_statusTable etls_controlName 
      etls_processesRunning etls_maxProcesses etls_parameterTable 
      etls_additionalSignonOptions etls_signonRetries;
   %let etls_controlName = L46_; 
   %let etls_statusTable = work.W2B6FZD; 
   %let etls_parameterTable = work.WVY21ZY; 
   %let &etls_controlName = 0;
   %let etls_controlTable = work.SET_DATES;
   
   %put %str(NOTE: Creating status table...);
   data &etls_statusTable 
      (keep = etls_handleName etls_machineId etls_startTime etls_endTime etls_status 
              etls_jobRC _run_date _run_date_yymth
      );
      attrib etls_handleName length = $32
         label = 'Name of handle to remote session'; 
      attrib etls_machineId length = $32
         label = 'Name of machine executing the task'; 
      attrib etls_startTime length = 8
         format = nldatmap.
         label = 'Start time of task'; 
      attrib etls_endTime length = 8
         format = nldatmap.
         label = 'End time of task'; 
      attrib etls_status length = $32
         label = 'Current status of task'; 
      attrib etls_jobRC length = 8
         label = 'Return code of task'; 
      attrib _run_date length = $10
         format = $10.
         informat = $10.; 
      attrib _run_date_yymth length = $6
         format = $10.
         informat = $10.; 
      set &etls_controlTable;
   run;
   
   %rcSet(&syserr); 
   
   %put %str(NOTE: Creating parameter table...);
   proc sql; 
      create table &etls_parameterTable as 
         select _run_date_yymth as _RUN_DATE_YYMTH, 
                _run_date as _RUN_DATE 
         from &etls_controlTable; 
   quit; 
   
   %rcSet(&sqlrc); 
   
   /* Get the number of times to iterate from the number of rows in the source  */ 
   /*  table                                                                    */ 
   proc sql noprint; 
      select count(*) into :&etls_controlName._max from &etls_statusTable;
      %let &etls_controlName._max = &&&etls_controlName._max;
   quit;
   
   %rcSet(&sqlrc); 
   
   /* Initialize checks for status handling per iteration  */ 
   %do i=1 %to &&&etls_controlName._max; 
      %local etls_statusReported&i; 
      %let etls_statusReported&i = 0; 
   %end; 
   
   %let etls_maxProcesses = 1; 
   
   %if (&etls_maxProcesses > 0) %then 
   %do; 
      %do %until (&&&etls_controlName ge &&&etls_controlName._max); 
      
         %let etls_lastLoopPtr = &&&etls_controlName;
         
         %let etls_processesRunning = 0; 
         
         %do %while(&etls_processesRunning lt &&&etls_controlName._max 
            and &etls_processesRunning lt &etls_maxProcesses 
            and &&&etls_controlName lt &&&etls_controlName._max);
            
            %let &etls_controlName = %eval(&&&etls_controlName+1);
            
            %let job_rcLast=&job_rc; 
            
            %etls_createHandle(statusTable=&etls_statusTable,
                               statusVariable=etls_status,
                               handleVariable=etls_handleName,
                               handlePrefix=&etls_controlName,
                               statusSetting="Running",
                               row=&&&etls_controlName,
                               machineVariable=etls_machineId,
                               startTimeVariable=etls_startTime,
                               signon=0,
                               useGrid=0);
            
         %let etls_processesRunning = 1; 
         %etls_processToLoopWVY21VT(parameterTable=&etls_parameterTable, row=&&&etls_controlName,
            handleName=%etls_getHandle(statusTable=&etls_statusTable,
            handleVariable=etls_handleName, row=&&&etls_controlName)); 
         
         /* Reset main Job_RC and Trans_RC to max return code of all iterations */ 
         %let job_rcThisIter=&job_rc; 
         %let job_rc=&job_rcLast; 
         %let trans_rc=&job_rcLast; 
         %rcSet(&job_rcThisIter); 
         
         %etls_loopRCCheck(statusTable=&etls_statusTable, returnCodeVariable=etls_jobRC, 
            start=&&&etls_controlName,end=&&&etls_controlName); 
      %end; 
      
   %end; 
   
%end;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete WVY21ZY;
quit;

%mend etls_loopWVY21VJ; 

%etls_loopWVY21VJ; 

%rcSet(&syscc); 



/**  Step end Loop **/

/*==========================================================================* 
 * Step:            Loop End                              A57ZQ4A4.BO0018V1 * 
 * Transform:       Loop End                                                * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57ZQ4A4.BO0018V1);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%rcSet(&syscc); 



/**  Step end Loop End **/

/*---- Start of User Written Code  ----*/ 

%put start_period_dt: &start_period_dt;
%put end_period_dt: &end_period_dt;
%GLOBAL CURR_QTR_MTH_TM_ID;
%GLOBAL MTH_TM_ID;

PROC SQL NOPRINT;
	SELECT TM_ID INTO :MTH_TM_ID FROM NZUSER.TM_DIM WHERE TM_LVL_END_DT="&end_period_dt"D AND TM_LVL='Month';
QUIT;

%LET Processing_Month_Time_ID = &MTH_TM_ID.;

/*FETCH MORE TIME PERIOD DETAILS*/
proc sql NOPRINT;
	CONNECT USING NZUSER AS NZCON;
	CREATE table _temp_yearmonth as 
		select * from connection to NZCON (
		select clndr_yr, tm_yr_seq_num, '00' as charmonth, '000000' as yearmonth from TM_DIM where TM_ID = &MTH_TM_ID.;
			);
	DISCONNECT FROM NZCON;
quit;

/*CONVERT THE INTEGER VALUES TO CHARACTER AS NEEDED*/
data _temp_yearmonth;
	set _temp_yearmonth;

	if tm_yr_seq_num < 10 then
		do;
			charmonth='0'||put(tm_yr_seq_num,1.);
		end;
	else
		do;
			charmonth=tm_yr_seq_num;
		end;

	yearmonth=clndr_yr||charmonth;
	format yearmonth $char6.;
run;

/*Save the string YYYYMM for the latest MTH_TM_ID fetched from TM_DIM into a variable*/
proc sql noprint;
	select yearmonth into :yearmonth from _temp_yearmonth;
quit;

%PUT >>> MTH_TM_ID IS &MTH_TM_ID.;
%PUT >>> YEARMONTH IS &YEARMONTH.;

PROC SQL NOPRINT;
	SELECT MAX(TM_ID) INTO :CURR_QTR_MTH_TM_ID FROM NZUSER.TM_DIM WHERE TM_LVL='Month' AND FNCL_QTR_KEY=
	(SELECT FNCL_QTR_KEY FROM NZUSER.TM_DIM WHERE TM_iD=&MTH_TM_ID AND TM_LVL='Month');
QUIT;

%PUT CURR_QTR_MTH_TM_ID IS &CURR_QTR_MTH_TM_ID;

PROC SQL NOPRINT;
	CONNECT USING NZUSER AS NZCON;
	EXECUTE(DELETE FROM BASEL_ANLYT_BL_INST_FCT_BNS_DLGD WHERE MTH_TM_ID=&MTH_TM_ID) BY NZCON;
	DISCONNECT FROM NZCON;
QUIT;

PROC SQL NOPRINT;
	CONNECT USING NZUSER AS NZCON;
	EXECUTE(
		INSERT INTO BASEL_ANLYT_BL_INST_FCT_BNS_DLGD
			SELECT 
				MTH_TM_ID
				,SRC_SYS_CD
				,BASEL_ACCT_ID
				,UNQ_ACCT_ID
				,NCR_RT_SYS_KEY_VAL
				,NCR_PD_BAND_KEY_VAL
				,NCR_EXPSR_SIZE_KEY_VAL
				,NCR_GEO_KEY_VAL
				,NCR_LTV_KEY_VAL
				,NCR_EXPSR_CL_KEY_VAL
				,NCR_RT_KEY_VAL
				,NCR_DLQNT_BCKT_KEY_VAL
				,PIT_STAT_CD
				,UTLTN_RTO
				,ACCT_ODT
				,TRNST_NUM
				,CR_LMT_AMT
				,ADVNC_AMT
				,AUTH_AMT
				,OS_BAL_AMT
				,GENL_LEDGER_BALCNG_ADJ_AMT
				,ADJUSTED_OS_BAL_AMT
				,UNADJUSTED_ADD_ON_BAL_AMT
				,AF_SECRTZTN_BAL_AMT
				,DLQNT_DAY_CNT
				,BEFORE_ZERO_NET_UNDRAWN_AMT
				,BEFORE_ZERO_NET_DRAWN_AMT
				,ORIG_PRPTY_VAL_AMT
				,LOAN_TO_VAL_RTO
				,INDEXED_PRPTY_VAL_AMT
				,INDEXED_LOAN_TO_VAL_RTO
				,PD_MODEL_NM
				,PD_MODEL_VER
				,PD_BASEL_SCORECRD_NM
				,PD_SCORECRD_VER
				,PD_BASEL_SEG_NUM
				,PD_BASEL_SEG_ID
				,PD_SEG_VER
				,PD_BASEL_MODEL_REL_ID
				,PD_MODEL_RTO
				,PD_LR_RPTG_RTO
				,PD_LR_PV_RPTG_RTO
				,PD_LR_PV_AD_RPTG_RTO
				,PD_LD_PV_AD_SV_RPTG_RTO
				,PD_ACCT_SCORE
				,PD_FINAL_RPTG_RTO
				,LGD_MODEL_NM
				,LGD_MODEL_VER
				,LGD_BASEL_SCORECRD_NM
				,LGD_SCORECRD_VER
				,LGD_BASEL_SEG_NUM
				,LGD_BASEL_SEG_ID
				,LGD_SEG_VER
				,LGD_BASEL_MODEL_REL_ID
				,LGD_MODEL_RTO
				,LGD_LR_RPTG_RTO
				,LGD_LR_PV_RPTG_RTO
				,LGD_LR_PV_AD_RPTG_RTO
				,LGD_LD_PV_AD_SV_RPTG_RTO
				,LGD_ACCT_SCORE
				,LGD_LD_PV_AD_SV_DT_RPTG_RTO
				,EAD_MODEL_NM
				,EAD_MODEL_VER
				,LGD_FINAL_RPTG_RTO
				,EAD_BASEL_SCORECRD_NM
				,EAD_SCORECRD_VER
				,EAD_BASEL_SEG_NUM
				,EAD_BASEL_SEG_ID
				,EAD_SEG_VER
				,EAD_BASEL_MODEL_REL_ID
				,EAD_MODEL_RTO
				,EAD_LR_RPTG_RTO
				,EAD_LR_PV_RPTG_RTO
				,EAD_ACCT_SCORE
				,EAD_LR_PV_AD_RPTG_RTO
				,ASST_CL_DESC
				,CONS_DFT_MTH_CNT
				,EAD_LD_PV_AD_SV_RPTG_RTO
				,EAD_LD_PV_AD_SV_DT_RPTG_RTO
				,BCAR_SCHED_NUM
				,EAD_FINAL_RPTG_RTO
				,PD_BAND
				,BASEL_PRD_ABR
				,SCRTY_TP_DESC
				,CCAR_BASEL_PRD_TP_NM
				,CCAR_EXPSR_CL_NM
				,BASEL_PRD_TP_CD
				,CONSM_PRD_TREATMNT_CD
				,PRD_ID
				,PRIM_CUST_CID
				,ACCT_NUM
				,RGNL_OFFC_CD
				,DLQNT_STG
				,MORT_NUM
				,CAB_TRNST_NUM
				,EGL_DEPRTMNT
				,BASEL_CIF_KEY
				,LOAN_NUM
				,INTR_ACCR_AMT
				,CUST_BEHV_SCORE
				,PRD_CD
				,SUB_PRD_CD
				,SRC_PRD_DESC
				,LEGAL_ENTITY
				,MAT_DT
				,LAST_PYMT_DT
				,SCRTY_TP_CD
				,STEP_F
				,LAST_ACTY_DT
				,HOUSE_TP_NM
				,LAST_RGL_PAY_DT
				,PD_OFF_F
				,PD_OFF_DT
				,RESIDUAL_MAT
				,ASST_CL_NUM
				,E_MAT_DT
				,AMORT
				,TRNST_EXCLSN_F
				,SML_BUS_F
				,NOTE_DT
				,INSRT_PROCESS_TMSTMP
				,UPDT_PROCESS_TMSTMP
				,AF_ZERO_NET_DRAWN_AMT
				,AF_ZERO_NET_UNDRAWN_AMT
				,PD_UNADJUSTED_RPTG_RTO
				,LGD_UNADJUSTED_RPTG_RTO
				,lgd_insured_rptg_rto /*HADI*/
				,EAD_UNADJUSTED_RPTG_RTO
				,PD_LR_PV_AD_SV_DT_AA_RTO
				,LGD_LR_PV_AD_SV_DT_AA_RTO
				,EAD_LR_PV_AD_SV_DT_AA_RTO
				,NULL AS INSUR_F
				,NULL AS OS_PRNCPL_BAL_AMT
				,HPV_12_QTR_AGO AS PREV_12_QTR_PRPTY_VAL_AMT
				,DLGD_F
				,CRNT_LTV_RTO
				,METROPOLITAN AS METRPL_AREA_NM
				,DELTA_P AS PRPTY_VAL_CORR_PCTG
				,ADDON AS LNG_RUN_LGD_ADD_ON_RTO
				,DLGD_FINAL_RPTG_RTO AS DLGD_RPTG_RTO
			FROM
				(
			SELECT SUBQ2.*, INDX.INDEX, INDX12.INDEX AS INDEX_12_QTR_AGO, (SUBQ2.INDEX_TERANETV/INDX.INDEX)*INDX12.INDEX AS HPV_12_QTR_AGO, SCRI.METRPL_BREACH_F,
				CASE 
					WHEN SUBQ2.DLGD_F='N' THEN NULL 
					WHEN SUBQ2.DLGD_F<>'N' AND SCRI.METRPL_BREACH_F='Y' THEN MAX(1-(HPV_12_QTR_AGO/NULLIF(SUBQ2.INDEX_TERANETV,0)),0.25) 
					WHEN SUBQ2.DLGD_F<>'N' AND SCRI.METRPL_BREACH_F<>'Y' THEN MAX(1-(HPV_12_QTR_AGO/NULLIF(SUBQ2.INDEX_TERANETV,0)),0) 
				END AS DELTA_P,
				CASE 
					WHEN SUBQ2.DLGD_F='Y' AND SUBQ2.CRNT_LTV_RTO IS NOT NULL AND DELTA_P IS NOT NULL 
						AND SUBQ2.INDEXED_CCLTV_RTO IS NOT NULL 
							THEN MAX((MIN(SUBQ2.CRNT_LTV_RTO, MAX(SUBQ2.INDEXED_CCLTV_RTO-0.8*(1-DELTA_P),0))-MAX(SUBQ2.INDEXED_CCLTV_RTO-0.8,0))/NULLIF(SUBQ2.CRNT_LTV_RTO,0),0) 
					WHEN SUBQ2.DLGD_F='Y' AND SUBQ2.CRNT_LTV_RTO IS NOT NULL AND DELTA_P IS NOT NULL 
						AND SUBQ2.INDEXED_CCLTV_RTO IS NULL 
							THEN (MAX(SUBQ2.CRNT_LTV_RTO-0.8*(1-DELTA_P),0)-MAX(SUBQ2.CRNT_LTV_RTO-0.8,0))/NULLIF(SUBQ2.CRNT_LTV_RTO,0)
					ELSE NULL 
				END AS ADDON,
			CASE 
				WHEN SUBQ2.DLGD_F='Y' AND SUBQ2.SCRTY_TP_DESC='Uninsured' and ADDON IS NOT NULL THEN 
						MAX(0.1, MIN(1, MAX(SUBQ2.lgd_unadjusted_rptg_rto + ADDON , SUBQ2.LGD_FINAL_RPTG_RTO))) 
				WHEN SUBQ2.DLGD_F='Y' AND SUBQ2.SCRTY_TP_DESC='Insured' and ADDON IS NOT NULL THEN 
						MAX(0.1, MIN(1, MAX(SUBQ2.lgd_insured_rptg_rto + ADDON , SUBQ2.LGD_FINAL_RPTG_RTO)))
				ELSE SUBQ2.LGD_FINAL_RPTG_RTO 
			END /*DLGD Insured changes effective November 2017 */
			AS DLGD_FINAL_RPTG_RTO

		FROM (
			SELECT SUBQ1.*, FIR.PROP_CITY, FIR.INDEX_TERANETV, LTVVAR.CRNT_LTV_RTO, LTVVAR.INDEXED_CCLTV_RTO,
				CASE 
					WHEN SUBQ1.DLGD_F='N' THEN NULL  
					WHEN SUBQ1.DLGD_F<>'N' AND (FIR.PROP_CITY IS NULL OR UPPER(FIR.PROP_CITY) LIKE '%OTHER%') THEN '11'
					WHEN SUBQ1.DLGD_F<>'N' AND TRIM(FIR.PROP_CITY)='Ottawa - Gatineau' THEN 'OTTAWA_GATINEAU' 
					ELSE FIR.PROP_CITY 
				END 
			AS METROPOLITAN
				FROM (
					SELECT A.*, B.BASEL_MORT_MTH_SNAPSHOT_ID, B.INTR_ADJ_DT, B.LAST_RNEW_DT,
						CASE 
							WHEN A.MTH_TM_ID >= 16996 /*17156*/ AND A.LGD_BASEL_SEG_NUM NOT IN (13,14) AND A.PIT_STAT_CD = 'CUR'
								AND A.SCRTY_TP_DESC in ('Uninsured','Insured') AND (B.INTR_ADJ_DT>='11-01-2016' OR B.LAST_RNEW_DT>='11-01-2016') THEN 'Y' 
							WHEN A.MTH_TM_ID < 16996 /*17156*/ and A.LGD_BASEL_SEG_NUM NOT IN (13,14) AND A.PIT_STAT_CD = 'CUR'
								AND A.SCRTY_TP_DESC='Uninsured' AND (B.INTR_ADJ_DT>='11-01-2016' OR B.LAST_RNEW_DT>='11-01-2016') THEN 'Y'
							ELSE 'N' 
						END  /*DLGD Insured changes effective November 2017 */
					AS DLGD_F 
						FROM 
							BASEL_ANALYTCL_BL_INST_FCT_BNS A,&RRAP_DB...BASEL_MORT_MTH_SNAPSHOT B 
						WHERE 
							TRIM(A.MORT_NUM)=TRIM(B.MORT_NUM) AND A.MTH_TM_ID=&MTH_TM_ID AND B.MTH_TM_ID=&MTH_TM_ID
					) SUBQ1
						LEFT OUTER JOIN LTV_VAR_CLUS_LTV_FINAL FIR ON SUBQ1.MORT_NUM=CAST(FIR.MORTGAGE_NO AS VARCHAR(30)) AND FIR.YYMTH=&YEARMONTH
						LEFT OUTER JOIN &RRAP_DB...BASEL_ACCT_LTV_DRVD_VARS LTVVAR ON TRIM(SUBQ1.MORT_NUM)=TRIM(LTVVAR.ACCT_NUM) AND LTVVAR.ACCT_SENRTY_CD=1 AND LTVVAR.MTH_TM_ID=&MTH_TM_ID
					) SUBQ2


						LEFT OUTER JOIN (SELECT DISTINCT MTH_TM_ID, LABEL_2, INDEX FROM &RRAP_DB...TERANET_HOUSE_PRC_INDEX WHERE MTH_TM_ID=(SELECT MAX(MTH_TM_ID) FROM &RRAP_DB...TERANET_HOUSE_PRC_INDEX)) INDX 
							ON UPPER(TRIM(INDX.LABEL_2)) =UPPER(TRIM(SUBQ2.METROPOLITAN))
						LEFT OUTER JOIN (SELECT DISTINCT MTH_TM_ID, LABEL_2, INDEX FROM &RRAP_DB...TERANET_HOUSE_PRC_INDEX WHERE MTH_TM_ID=(SELECT MAX(MTH_TM_ID)-1440 FROM &RRAP_DB...TERANET_HOUSE_PRC_INDEX)) INDX12 
							ON UPPER(TRIM(INDX12.LABEL_2)) =UPPER(TRIM(SUBQ2.METROPOLITAN)) 
						LEFT OUTER JOIN &RRAP_DB...DLGD_SCRI_QTR_DRVD_VARS SCRI ON UPPER(TRIM(SCRI.METRPL_AREA_NM))=UPPER(TRIM(SUBQ2.METROPOLITAN)) AND SCRI.MTH_TM_ID=&CURR_QTR_MTH_TM_ID
				) FINAL
					) BY NZCON;
	DISCONNECT FROM NZCON;
QUIT;
/*---- End of User Written Code  ----*/ 

%let etls_endTime = %sysfunc(datetime(),datetime.);

