
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);
OPTIONS COMPRESS=N;
%GLOBAL SESSIONTIME;
%GLOBAL CURRENT_DATE;
%GLOBAL OUTFILE;
%GLOBAL MTH_TM_ID;
%GLOBAL YEARMONTH;
%GLOBAL MONTHYEAR;
%GLOBAL TGTCOUNT00;
%GLOBAL MTH_END_DT;
%GLOBAL P2EXTR;
%GLOBAL FINAL_COUNT;
%GLOBAL FILE_SIZE_BYTES;
%LET SESSIONTIME=%SYSFUNC(DATETIME(),BEST18.); /*CURRENT TIMESTAMP FROM SAS */
%LET CURRENT_DATE=%SYSFUNC(TODAY(),YYMMDDn8.);
%LET INPUT00=EDRRAPT.BASEL_P1_005;
%LET INPUT01=EDRRAPT.BASEL_P1_010;
%LET INPUT02=EDRRAPT.BASEL_P1_015;
%LET INPUT03=EDRRAPT.BASEL_P1_020;
%LET INPUT04=EDRRAPT.BASEL_P1_025;
%LET INPUT05=EDRRAPT.BASEL_P1_030;
%LET INPUT06=EDRRAPT.BASEL_P1_035;
%LET INPUT07=EDRRAPT.BASEL_P1_040;
%LET INPUT08=EDRRAPT.BASEL_P1_045;
%LET INPUT09=EDRRAPT.BASEL_P1_047;
%LET INPUT10=EDRRAPT.BASEL_P1_050;
%LET INPUT11=EDRRAPT.BASEL_P1_055;
%LET INPUT12=EDRRAPT.BASEL_P1_060;
%LET INPUT13=EDRRAPT.BASEL_P1_065;
%LET INPUT14=EDRRAPT.BASEL_P1_070;
%LET INPUT15=EDRRAPT.BASEL_P1_080;
%LET INPUT16=EDRRAPT.BASEL_P1_090;
%LET P2EXTR=&OUTPATH;

%macro rrap_db2yearmonth;

	proc sql noprint;
		CREATE table _temp_yearmonth as 
			select clndr_yr, tm_yr_seq_num, '00' as charmonth, '000000' as yearmonth from EDRTLRT.TM_DIM where TM_ID = &MTH_TM_ID;
	quit;

	/*Convert the integer values to char values as needed*/
	data _temp_yearmonth;
		set _temp_yearmonth;

		if tm_yr_seq_num < 10 then
			do;
				charmonth='0'||put(tm_yr_seq_num,1.);
			end;
		else
			do;
				charmonth=tm_yr_seq_num;
			end;

		yearmonth=clndr_yr||charmonth;
		format yearmonth $char6.;
		monthyear=charmonth||clndr_yr;
		format monthyear $char6.;
	run;

	/*Save the string YYYYMM for the latest MTH_TM_ID fetched from TM_DIM into a variable*/
	proc sql noprint;
		select yearmonth into :yearmonth from _temp_yearmonth;
		select monthyear into :monthyear from _temp_yearmonth;
	quit;

%mend rrap_db2yearmonth;

%rrap_db2yearmonth;

/*THE SORTED FILE*/
%LET FILEPATH11="&P2EXTR/rk/outgoing/AE_BE_&MONTHYEAR..DAT";
%PUT YEARMONTH IS &YEARMONTH;
%PUT MONTHYEAR IS &MONTHYEAR;
%PUT MTH_TM_ID IS &MTH_TM_ID;
%PUT MTH_END_DT IS &MTH_END_DT;
%LET MTH_END_DT_FMT=%SYSFUNC(PUTN("&MTH_END_DT"d,YYMMDDd10.));
%LET MTH_END_DT_FINFMT=%UNQUOTE(%STR(%'&MTH_END_DT_FMT%'));
%PUT &MTH_END_DT_FINFMT;

/*CREATING THE HEADER RECORD*/
DATA INPATH.P2_EXTRACT_HEADER;
	COLUMN1='00005990299099932993399AE  '||PUT("&MTH_END_DT"d,YYMMDDn8.)||'BE     05.0.0'||PUT(" ",$322.)||'?';
RUN;

/*CALCULATING THE TOTAL RECORD COUNT*/
PROC SQL NOPRINT;
	SELECT SUM(COLUMN2) INTO :FINAL_COUNT FROM (
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_005 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_005 WHERE MTH_END_DT="&MTH_END_DT"d)
		UNION ALL
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_010 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_010 WHERE MTH_END_DT="&MTH_END_DT"d)
		UNION ALL
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_011 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_011 WHERE MTH_END_DT="&MTH_END_DT"d)
		UNION ALL
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_012 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_012 WHERE MTH_END_DT="&MTH_END_DT"d)
		UNION ALL
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_015 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_015 WHERE MTH_END_DT="&MTH_END_DT"d)
		UNION ALL
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_020 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_020 WHERE MTH_END_DT="&MTH_END_DT"d)
		UNION ALL
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_030 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_030 WHERE MTH_END_DT="&MTH_END_DT"d)
		UNION ALL
	SELECT COUNT(*) AS COLUMN2 FROM EDRRAPT.BASEL_P2_040 WHERE MTH_END_DT="&MTH_END_DT"d AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_040 WHERE MTH_END_DT="&MTH_END_DT"d)
		)
	;
QUIT;

/*CALCULATING THE FILE SIZE*/
%LET FILE_SIZE_BYTES=%EVAL((&FINAL_COUNT+2)*380);

/*DISPLAYING THE COUNTS IN LOG*/
%PUT FINALRECORDCOUNT IS &FINAL_COUNT;
%PUT FILESIZE IS &FILE_SIZE_BYTES;

/*CREATING THE FOOTER RECORD*/
DATA INPATH.P2_EXTRACT_FOOTER;
	COLUMN1='99905990299099932993399'||PUT(&FINAL_COUNT,z9.)||PUT(&FILE_SIZE_BYTES,z12.)||PUT("AE_BE_&MONTHYEAR..DAT",$60.)||PUT(&CURRENT_DATE,8.)||PUT(" ",$258.)||'?';
RUN;

/*CREATING THE DETAIL RECORDS*/
PROC SQL NOPRINT;
	CONNECT USING EDRRAPT AS DBCON ;
	CREATE TABLE INPATH.BE_EXTRACT_PART1 AS
		SELECT * FROM CONNECTION TO DBCON(
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			RPAD(RISK_RT_SYS_NM,60)||RPAD('',287)||'?' AS COLUMN1 FROM EDRRAPT.BASEL_P2_005 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_005 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
			UNION
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			RPAD(PD_SEG_NM,60)||RPAD('',287)||'?' AS COLUMN1 FROM EDRRAPT.BASEL_P2_010 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_010 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
			UNION
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			RPAD(LGD_SEG_NM,60)||RPAD('',287)||'?' AS COLUMN1 FROM EDRRAPT.BASEL_P2_011 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_011 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
			UNION
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			RPAD(EAD_SEG_NM,60)||RPAD('',287)||'?' AS COLUMN1 FROM EDRRAPT.BASEL_P2_012 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_012 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
			UNION
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			LPAD(TO_CHAR(NVL(ECONMC_CAPTL,0)),15,'0')||RPAD('',332)||'?' AS COLUMN1 FROM EDRRAPT.BASEL_P2_015 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_015 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
			UNION
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			LPAD(TO_CHAR(NVL(ESTD_PD,0.0)),6,'0')||LPAD(TO_CHAR(NVL(REALZ_PD,0.0)),6,'0')||LPAD(TO_CHAR(NVL(OS_BAL_AMT,0)),15,'0')||LPAD(TO_CHAR(NVL(REALZ_DFT_CNT,0)),15,'0')||RPAD('',305)||'?' AS COLUMN1 
		FROM EDRRAPT.BASEL_P2_020 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_020 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
			UNION
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			LPAD(TO_CHAR(NVL(ESTD_LGD,0.0)),6,'0')||LPAD(TO_CHAR(NVL(REALZ_LGD,0.0)),6,'0')||LPAD(TO_CHAR(NVL(OS_BAL_AMT,0)),15,'0')||LPAD(TO_CHAR(NVL(REALZ_DFT_CNT,0)),15,'0')||RPAD('',305)||'?' AS COLUMN1 
		FROM EDRRAPT.BASEL_P2_030 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_030 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
			UNION
		SELECT NCR_RECD_TP||NCR_EXPSR_CL||NCR_RISK_RT_SYS||NCR_PD_SEG||NCR_LGD_SEG||NCR_EAD_SEG||
			LPAD(TO_CHAR(NVL(ESTD_EAD,0.0)),6,'0')||LPAD(TO_CHAR(NVL(REALZ_EAD,0.0)),6,'0')||LPAD(TO_CHAR(NVL(OS_BAL_AMT,0)),15,'0')||LPAD(TO_CHAR(NVL(REALZ_DFT_CNT,0)),15,'0')||RPAD('',305)||'?' AS COLUMN1 
		FROM EDRRAPT.BASEL_P2_040 WHERE MTH_END_DT=&MTH_END_DT_FINFMT
			AND EXTRACT_TMSTMP=(SELECT MAX(EXTRACT_TMSTMP) FROM EDRRAPT.BASEL_P2_040 WHERE MTH_END_DT=&MTH_END_DT_FINFMT)
		ORDER BY 1;
			);
		DISCONNECT FROM DBCON;
QUIT;

/*CREATING THE FINAL DATASET INCLUDING HEADER DETAIL AND FOOTER RECORDS*/
DATA INPATH.BE_EXTRACT_PART1;
	SET INPATH.P2_EXTRACT_HEADER INPATH.BE_EXTRACT_PART1 INPATH.P2_EXTRACT_FOOTER;
RUN;

DATA INPATH.BE_EXTRACT_PART1;
	SET INPATH.BE_EXTRACT_PART1;
	WHERE COLUMN1<>' ';
RUN;

DATA INPATH.BE_EXTRACT_PART2;
	SET INPATH.BE_EXTRACT_PART1;
	COLUMN2=TRANSLATE(COLUMN1,'','?');
	FINAL_COLUMN=PUT(COLUMN2,$370.)||PUT(_N_,z8.);
RUN;

/*EXPORT THE FINAL DATASET ONTO THE TEXT FILE*/
DATA _NULL_;
	LENGTH CRLF $1;
	FILE &FILEPATH11. LRECL=380;
	CRLF=BYTE(13);
	SET INPATH.BE_EXTRACT_PART2;
	PUT @1 FINAL_COLUMN @;
	PUT @379 CRLF;
RUN;