/*Created on :- 09/27/2021*/
/*Created by :- Dhaivat Patel*/
/*Job name :- RRAP_MID_RUN_SAS_SERVER_CLEANUP*/
/*THE JOB DELETES THE INTERMEDIATE TABLES DURING EVERY MONTH'S RUN, REMOVING THE NEED FOR MANUL MID RUN SAS SERVER CLEANUP*/

%macro Mid_Run_Server_Cleanup(table_name);
proc sql;
	drop table &table_name;
QUIT;
%mend;
options Mprint;

%macro showdiskutil;
filename fpdf pipe 'df -k /sasdata/sasdi';
data _null_;	
   infile fpdf;
   length buffer $ 200;
   input buffer;
   put _infile_;
run;
%mend ;

%put "Disk Utilization Before Cleanup";
%showdiskutil;

%RRAP_MOR_TNG_AUTOEXEC

/*Below Macro calls deletes the individual data sets from "/sasdata/sasdi/sasprod/data/rrap_iias/mortgage/intermediate" folder on the PROD server*/

%mid_run_server_cleanup(INTMED.all_def_history_d_0)
%mid_run_server_cleanup(INTMED.all_def_history_d_1)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_0)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_1)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_2)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_3)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_4)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_5)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_6)
%mid_run_server_cleanup(INTMED.all_def_history_d_1_7)
%mid_run_server_cleanup(INTMED.all_def_history_d_2)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_0)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_1)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_2)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_3)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_4)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_5)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_6)
%mid_run_server_cleanup(INTMED.all_def_history_d_2_7)
%mid_run_server_cleanup(INTMED.all_def_history_d_3)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_0)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_1)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_2)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_3)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_4)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_5)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_6)
%mid_run_server_cleanup(INTMED.all_def_history_d_3_7)
%mid_run_server_cleanup(INTMED.all_def_history_d_4)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_0)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_1)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_2)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_3)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_4)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_5)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_6)
%mid_run_server_cleanup(INTMED.all_def_history_d_4_7)
%mid_run_server_cleanup(INTMED.all_def_history_d_5)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_0)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_1)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_2)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_3)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_4)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_5)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_6)
%mid_run_server_cleanup(INTMED.all_def_history_d_5_7)
%mid_run_server_cleanup(INTMED.all_def_history_d_6)
%mid_run_server_cleanup(INTMED.all_def_history_d_7)
%mid_run_server_cleanup(INTMED.def_history_d_0)
%mid_run_server_cleanup(INTMED.def_history_d_1)
%mid_run_server_cleanup(INTMED.def_history_d_2)
%mid_run_server_cleanup(INTMED.def_history_d_3)
%mid_run_server_cleanup(INTMED.def_history_d_4)
%mid_run_server_cleanup(INTMED.def_history_d_5)
%mid_run_server_cleanup(INTMED.def_history_d_6)
%mid_run_server_cleanup(INTMED.def_history_d_7)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2021)

/*Below Macro calls deletes the individual data sets from "/sasdata/sasdi/sasprod/data/rrap_iias/mortgage/results" folder on the PROD server*/

%mid_run_server_cleanup(RESULTS.all_lgd_d)
%mid_run_server_cleanup(RESULTS.all_lgd_d_0)
%mid_run_server_cleanup(RESULTS.all_lgd_d_1)
%mid_run_server_cleanup(RESULTS.all_lgd_d_2)
%mid_run_server_cleanup(RESULTS.all_lgd_d_3)
%mid_run_server_cleanup(RESULTS.all_lgd_d_4)
%mid_run_server_cleanup(RESULTS.all_lgd_d_5)
%mid_run_server_cleanup(RESULTS.all_lgd_d_6)
%mid_run_server_cleanup(RESULTS.all_lgd_d_7)
%mid_run_server_cleanup(RESULTS.all_lgd_nd)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_0)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_1)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_2)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_3)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_4)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_5)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_6)
%mid_run_server_cleanup(RESULTS.all_lgd_nd_7)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_0)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_1)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_2)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_3)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_4)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_5)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_6)
%mid_run_server_cleanup(RESULTS.bns_lgd_d_scored_seg_accts_7)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_0)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_1)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_2)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_3)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_4)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_5)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_6)
%mid_run_server_cleanup(RESULTS.bns_lgd_nd_scored_seg_accts_7)
%mid_run_server_cleanup(RESULTS.excluded_obs_0)
%mid_run_server_cleanup(RESULTS.excluded_obs_0)
%mid_run_server_cleanup(RESULTS.excluded_obs_1)
%mid_run_server_cleanup(RESULTS.excluded_obs_1)
%mid_run_server_cleanup(RESULTS.excluded_obs_2)
%mid_run_server_cleanup(RESULTS.excluded_obs_2)
%mid_run_server_cleanup(RESULTS.excluded_obs_3)
%mid_run_server_cleanup(RESULTS.excluded_obs_3)
%mid_run_server_cleanup(RESULTS.excluded_obs_4)
%mid_run_server_cleanup(RESULTS.excluded_obs_4)
%mid_run_server_cleanup(RESULTS.excluded_obs_5)
%mid_run_server_cleanup(RESULTS.excluded_obs_5)
%mid_run_server_cleanup(RESULTS.excluded_obs_6)
%mid_run_server_cleanup(RESULTS.excluded_obs_6)
%mid_run_server_cleanup(RESULTS.excluded_obs_7)
%mid_run_server_cleanup(RESULTS.excluded_obs_7)
%mid_run_server_cleanup(RESULTS.status_excl_0)
%mid_run_server_cleanup(RESULTS.status_excl_1)
%mid_run_server_cleanup(RESULTS.status_excl_2)
%mid_run_server_cleanup(RESULTS.status_excl_3)
%mid_run_server_cleanup(RESULTS.status_excl_4)
%mid_run_server_cleanup(RESULTS.status_excl_5)
%mid_run_server_cleanup(RESULTS.status_excl_6)
%mid_run_server_cleanup(RESULTS.status_excl_7)
%mid_run_server_cleanup(RESULTS.status_final_0)
%mid_run_server_cleanup(RESULTS.status_final_0)
%mid_run_server_cleanup(RESULTS.status_final_1)
%mid_run_server_cleanup(RESULTS.status_final_1)
%mid_run_server_cleanup(RESULTS.status_final_2)
%mid_run_server_cleanup(RESULTS.status_final_2)
%mid_run_server_cleanup(RESULTS.status_final_3)
%mid_run_server_cleanup(RESULTS.status_final_3)
%mid_run_server_cleanup(RESULTS.status_final_4)
%mid_run_server_cleanup(RESULTS.status_final_4)
%mid_run_server_cleanup(RESULTS.status_final_5)
%mid_run_server_cleanup(RESULTS.status_final_5)
%mid_run_server_cleanup(RESULTS.status_final_6)
%mid_run_server_cleanup(RESULTS.status_final_6)
%mid_run_server_cleanup(RESULTS.status_final_7)
%mid_run_server_cleanup(RESULTS.status_final_7)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_0)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_1)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_2)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_3)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_4)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_5)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_6)
%mid_run_server_cleanup(RESULTS.twelve_mon_def_window_7)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_0)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_1)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_2)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_3)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_4)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_5)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_6)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgd_nd_7)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_0)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_1)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_2)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_3)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_4)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_5)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_6)
%mid_run_server_cleanup(RESULTS.with_scorecard_vars_lgdd_7)

/*Below Macro calls deletes the individual data sets from "/sasdata/sasdi/sasprod/data/rrap_iias/mortgage/source" folder on the PROD server*/

%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_0)
%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_1)
%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_2)
%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_3)
%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_4)
%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_5)
%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_6)
%mid_run_server_cleanup(SOURCE.base_bns_lgd_d_7)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_0)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_1)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_2)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_3)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_4)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_5)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_6)
%mid_run_server_cleanup(SOURCE.base_lgd_nd_7)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_0)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_1)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_2)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_3)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_4)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_5)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_6)
%mid_run_server_cleanup(SOURCE.ltv_var_clus_ltv_final_7)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_0)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_1)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_2)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_3)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_4)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_5)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_6)
%mid_run_server_cleanup(SOURCE.scorecard_vars_final_7)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202101)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202102)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202103)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202104)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202105)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202106)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202107)
%mid_run_server_cleanup(SOURCE.lgd_d_ifrs_bkup_202108)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202009)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202010)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202011)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202012)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202101)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202102)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202103)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202104)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202105)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202106)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202107)
%mid_run_server_cleanup(SOURCE.lgd_d_prod_bkup_202108)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202009)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202010)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202011)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202012)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202101)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202102)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202103)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202104)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202105)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202106)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202107)
%mid_run_server_cleanup(SOURCE.lgd_nd_prod_bkup_202108)
%mid_run_server_cleanup(SOURCE.mbs_cost24_v3)
%mid_run_server_cleanup(SOURCE.recovery_data_all)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202009)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202010)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202011)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202012)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202101)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202102)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202103)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202104)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202105)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202106)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202107)
%mid_run_server_cleanup(SOURCE.recovery_data_all_202108)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202009)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202010)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202011)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202012)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202101)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202102)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202103)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202104)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202105)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202106)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202107)
%mid_run_server_cleanup(SOURCE.tng_lgd_d_new_logic_202108)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202009)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202010)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202011)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202012)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202101)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202102)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202103)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202104)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202105)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202106)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202107)
%mid_run_server_cleanup(SOURCE.tng_lgd_nd_new_logic_202108)

/*RRMSS-1479 As discussed with Nimrat, more datasets identified for deletion */
/*Below Macro calls deletes the individual data sets from "/sasdata/sasdi/sasprod/data/rrap_iias/mortgage/intermediate" folder on the PROD server*/

%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2006)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2007)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2008)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2009)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2010)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2011)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2012)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2013)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2014)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2015)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2016)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2017)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2018)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2019)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2020)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2021)
%mid_run_server_cleanup(INTMED.scorecard_vars_d2d_activity_2022)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_0)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_1)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_2)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_3)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_4)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_5)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_6)
%mid_run_server_cleanup(INTMED.var_clus_ltv_b_7)
%mid_run_server_cleanup(INTMED.obs_window_1)
%mid_run_server_cleanup(INTMED.obs_window_2)
%mid_run_server_cleanup(INTMED.obs_window_3)
%mid_run_server_cleanup(INTMED.obs_window_4)
%mid_run_server_cleanup(INTMED.obs_window_5)
%mid_run_server_cleanup(INTMED.obs_window_6)
%mid_run_server_cleanup(INTMED.obs_window_7)

/*RRMSS-1525/1586:	Include datasets from /sasdata/sasdi/sasprod/data/rrap_iias/mortgage/results folder*/
%mid_run_server_cleanup(RESULTS.tng_12mth_default)
%mid_run_server_cleanup(RESULTS.tng_pd_var_creation_final)
%mid_run_server_cleanup(RESULTS.tng_status)
%mid_run_server_cleanup(RESULTS.tng_pd_exclusion_final)
%mid_run_server_cleanup(RESULTS.tng_lgdnd_non_excl_obs_ifrs)
%mid_run_server_cleanup(RESULTS.tng_lgdnd_non_excluded_obs)

%put "Disk Utilization After Cleanup";
%showdiskutil;
