/**********************************************************/
/* JOB NAME: rrap_ccar_expsr_extr_ecl 
/* DATE:	Jan 22, 2020
/* Job created for BCAR ECL Changes. 
/* Source Table: EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL
/* Target Table: EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ECL
/*********************************************************/


%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

%let datetime_start = %sysfunc(TIME()) ;
%put >>> START TIME: %sysfunc(datetime(),datetime14.);

%PUT MTH_TM_ID IS &MTH_TM_ID;

/* Update values to zero for previous month */
PROC SQL NOPRINT;
CONNECT USING NZRRAP AS NZCON;
EXECUTE(UPDATE EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL
SET BEFR_ZERO_NET_ADJ_OS_BAL_AMT = 0 ,
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT = 0 ,
BEFORE_ZERO_NET_UNDRAWN_AMT = 0 ,
AF_ZERO_NET_UNDRAWN_AMT = 0 ,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT = 0 ,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT = 0 ,
PRTL_WRITE_OFF_AMT = 0 ,
ACCR_INTR_AMT = 0
where period_ind = 'PREV'
)BY NZCON  ;
quit;

/* Delete existing data in target table */
PROC SQL NOPRINT;
CONNECT USING NZRRAP AS NZCON;
EXECUTE(Truncate EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ECL immediate)BY NZCON  ;
quit;

/* Add data to target table */
PROC SQL NOPRINT;
CONNECT TO DB2 AS NZCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
	CREATE TABLE WORK.TEMP1 AS
	SELECT * FROM CONNECTION TO NZCON
	(SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRP1D.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS 
		MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		'DR_A'||LPAD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY FACT.LEGAL_ENTITY, FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
			FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.PERIOD_IND,
FACT.ECL_Drawn_1,
FACT.ECL_Drawn_2,
FACT.ECL_Drawn_3,
FACT.ECL_Undrawn_1,
FACT.ECL_Undrawn_2,
FACT.ECL_Undrawn_3,
FACT.ECL_Drawn_PostSec_1,
FACT.ECL_Drawn_PostSec_2,
FACT.ECL_Drawn_PostSec_3,
		'' AS INSRT_PROCESS_TMSTMP,
		'' AS UPDT_PROCESS_TMSTMP,
		FACT.INSUR_F,
		FACT.WGHTD_DLGD_RTO, FACT.LTV_PERCENTAGE, FACT.OBLIGORS
/*hadi*/
FROM EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL FACT WHERE FACT.LEGAL_ENTITY = 'DOM-SUB-DUNDEE' and FACT.PERIOD_IND = 'CURR'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID);
DISCONNECT FROM NZCON;
quit;

PROC SQL NOPRINT;
CONNECT TO DB2 AS NZCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
	CREATE TABLE WORK.TEMP2 AS
	SELECT * FROM CONNECTION TO NZCON
(SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRP1D.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		'DR_A'||LPAD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY FACT.LEGAL_ENTITY, FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO, FACT.LTV_PERCENTAGE, FACT.OBLIGORS,
		FACT.PERIOD_IND,
FACT.ECL_Drawn_1,
FACT.ECL_Drawn_2,
FACT.ECL_Drawn_3,
FACT.ECL_Undrawn_1,
FACT.ECL_Undrawn_2,
FACT.ECL_Undrawn_3,
FACT.ECL_Drawn_PostSec_1,
FACT.ECL_Drawn_PostSec_2,
FACT.ECL_Drawn_PostSec_3,
		'' AS INSRT_PROCESS_TMSTMP,
		'' AS UPDT_PROCESS_TMSTMP
FROM EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL FACT WHERE FACT.LEGAL_ENTITY = 'DOM-SUB-NT' and FACT.PERIOD_IND = 'CURR'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0 ) AND FACT.MTH_TM_ID=&MTH_TM_ID);
DISCONNECT FROM NZCON;
quit;

PROC SQL NOPRINT;
CONNECT TO DB2 AS NZCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
	CREATE TABLE WORK.TEMP3 AS
	SELECT * FROM CONNECTION TO NZCON
(SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRP1D.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		'DR_A'||LPAD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY FACT.LEGAL_ENTITY, FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO, FACT.LTV_PERCENTAGE, FACT.OBLIGORS,
FACT.PERIOD_IND,
FACT.ECL_Drawn_1,
FACT.ECL_Drawn_2,
FACT.ECL_Drawn_3,
FACT.ECL_Undrawn_1,
FACT.ECL_Undrawn_2,
FACT.ECL_Undrawn_3,
FACT.ECL_Drawn_PostSec_1,
FACT.ECL_Drawn_PostSec_2,
FACT.ECL_Drawn_PostSec_3,
		'' AS INSRT_PROCESS_TMSTMP,
		'' AS UPDT_PROCESS_TMSTMP
FROM EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL FACT WHERE FACT.LEGAL_ENTITY = 'DOM-SUB-MTCC' and FACT.PERIOD_IND = 'CURR'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID);
DISCONNECT FROM NZCON;
quit;

PROC SQL NOPRINT;
CONNECT TO DB2 AS NZCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
	CREATE TABLE WORK.TEMP4 AS
	SELECT * FROM CONNECTION TO NZCON
(SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRP1D.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
	'DR_A'||LPAD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY FACT.LEGAL_ENTITY, FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO, FACT.LTV_PERCENTAGE, FACT.OBLIGORS,
		FACT.PERIOD_IND,
FACT.ECL_Drawn_1,
FACT.ECL_Drawn_2,
FACT.ECL_Drawn_3,
FACT.ECL_Undrawn_1,
FACT.ECL_Undrawn_2,
FACT.ECL_Undrawn_3,
FACT.ECL_Drawn_PostSec_1,
FACT.ECL_Drawn_PostSec_2,
FACT.ECL_Drawn_PostSec_3,
		NULL AS INSRT_PROCESS_TMSTMP,
		NULL AS UPDT_PROCESS_TMSTMP
FROM EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL FACT WHERE FACT.LEGAL_ENTITY IN ('DOM-SUB-MAPLE','DOM-SUB-SMC') and FACT.PERIOD_IND = 'CURR'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID);
DISCONNECT FROM NZCON;
quit;

PROC SQL NOPRINT;
CONNECT TO DB2 AS NZCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
	CREATE TABLE WORK.TEMP5 AS
	SELECT * FROM CONNECTION TO NZCON
(SELECT DISTINCT 
SUBQ.MTH_END_DT,
SUBQ.LEGAL_ENTITY,
SUBQ.CCAR_BASEL_PRD_TP_NM,
SUBQ.PD_BAND,
'DR_A'||LPAD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY SUBQ.UNQ_RECD_ID_TEMP ASC),6,'0') AS UNQ_RECD_ID,
SUBQ.INSUR_F,
SUBQ.PD_BASEL_SEG_NUM,
SUBQ.LGD_BASEL_SEG_NUM,
SUBQ.EAD_BASEL_SEG_NUM,
SUBQ.PD_90_DAY_F,
SUBQ.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
SUBQ.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
SUBQ.EXPCTD_LOSS_RTO_TEXT,
SUBQ.BEFORE_ZERO_NET_UNDRAWN_AMT,
SUBQ.AF_ZERO_NET_UNDRAWN_AMT,
SUBQ.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
SUBQ.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
SUBQ.LGD_FINAL_RPTG_RTO_TEXT,
SUBQ.EAD_FINAL_RPTG_RTO_TEXT,
SUBQ.EAD_PC,
SUBQ.CRNCY_CD,
SUBQ.PRTL_WRITE_OFF_AMT,
SUBQ.UNCONDTNLY_CNCLBL,
SUBQ.ACCR_INTR_AMT,
SUBQ.WGHTD_DLGD_RTO, SUBQ.LTV_PERCENTAGE, SUBQ.OBLIGORS,
SUBQ.PERIOD_IND,
SUBQ.ECL_Drawn_1,
SUBQ.ECL_Drawn_2,
SUBQ.ECL_Drawn_3,
SUBQ.ECL_Undrawn_1,
SUBQ.ECL_Undrawn_2,
SUBQ.ECL_Undrawn_3,
SUBQ.ECL_Drawn_PostSec_1,
SUBQ.ECL_Drawn_PostSec_2,
SUBQ.ECL_Drawn_PostSec_3,
SUBQ.INSRT_PROCESS_TMSTMP,
SUBQ.UPDT_PROCESS_TMSTMP 
FROM
(
SELECT
		(SELECT TM_LVL_END_DT FROM EDRTLRP1D.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		'DOM-BANK-ALONE' AS LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		'TEMP'||LPAD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY FACT.LEGAL_ENTITY, FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND, FACT.PERIOD_IND ASC),6,'0') AS UNQ_RECD_ID_TEMP,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO, FACT.LTV_PERCENTAGE, FACT.OBLIGORS,
FACT.PERIOD_IND,
FACT.ECL_Drawn_1,
FACT.ECL_Drawn_2,
FACT.ECL_Drawn_3,
FACT.ECL_Undrawn_1,
FACT.ECL_Undrawn_2,
FACT.ECL_Undrawn_3,
FACT.ECL_Drawn_PostSec_1,
FACT.ECL_Drawn_PostSec_2,
FACT.ECL_Drawn_PostSec_3,
		NULL AS INSRT_PROCESS_TMSTMP,
		NULL AS UPDT_PROCESS_TMSTMP
FROM EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL FACT WHERE (FACT.LEGAL_ENTITY IN ('DOM-BANK-BNS') and FACT.PERIOD_IND = 'CURR'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID)
OR
(FACT.LEGAL_ENTITY IN ('DOM-BANK-BNS_PREV')
/*('DOM-SUB-NT_PREV','DOM-SUB-MTCC_PREV','DOM-SUB-MAPLE_PREV','DOM-SUB-SMC_PREV','DOM-BANK-BNS_PREV','DOM-SUB-TNG_PREV') */
and FACT.PERIOD_IND = 'PREV' AND FACT.MTH_TM_ID=&MTH_TM_ID-40)
OR (FACT.LEGAL_ENTITY IN ('DOM-BANK-BNS_MISS') and FACT.PERIOD_IND = 'MISS' )
) as SUBQ
);
DISCONNECT FROM NZCON;
quit;

PROC SQL NOPRINT;
CONNECT TO DB2 AS NZCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
	CREATE TABLE WORK.TEMP6 AS
	SELECT * FROM CONNECTION TO NZCON
(SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRP1D.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		'DOM-SUB-TNG' as LEGAL_ENTITY,
		TFACT.CCAR_BASEL_PRD_TP_NM,
		TFACT.PD_BAND,
	'DR_A'||LPAD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY TFACT.LEGAL_ENTITY
, TFACT.CCAR_BASEL_PRD_TP_NM, TFACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		TFACT.INSUR_F,
		PD_BASEL_SEG_NUM,
		(case when LGD_BASEL_SEG_NUM=-1 then null else LGD_BASEL_SEG_NUM end) as LGD_BASEL_SEG_NUM,
		(case when EAD_BASEL_SEG_NUM=-1 then null else EAD_BASEL_SEG_NUM end) as  EAD_BASEL_SEG_NUM,
		CASE WHEN TFACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		(CAST(ROUND(TFACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		 BEFORE_ZERO_NET_UNDRAWN_AMT,
		AF_ZERO_NET_UNDRAWN_AMT,
		TFACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT AS BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TFACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT AS AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		(CAST(ROUND(TFACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
(CAST(ROUND(TFACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		TFACT.CRNCY_CD,
		TFACT.PRTL_WRITE_OFF_AMT,
		TFACT.UNCONDTNLY_CNCLBL AS UNCONDTNLY_CNCLBL,
		TFACT.ACCR_INTR_AMT,
		TFACT.WGHTD_DLGD_RTO, TFACT.LTV_PERCENTAGE, TFACT.OBLIGORS,
TFACT.PERIOD_IND,
TFACT.ECL_Drawn_1,
TFACT.ECL_Drawn_2,
TFACT.ECL_Drawn_3,
TFACT.ECL_Undrawn_1,
TFACT.ECL_Undrawn_2,
TFACT.ECL_Undrawn_3,
TFACT.ECL_Drawn_PostSec_1,
TFACT.ECL_Drawn_PostSec_2,
TFACT.ECL_Drawn_PostSec_3,
		NULL AS INSRT_PROCESS_TMSTMP,
		NULL AS UPDT_PROCESS_TMSTMP
FROM EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ECL tFACT WHERE (tFACT.LEGAL_ENTITY IN ( 'DOM-SUB-TNG' ) and tFACT.PERIOD_IND = 'CURR'
AND (tFACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR tFACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND tFACT.MTH_TM_ID=&MTH_TM_ID)
OR
(tFACT.LEGAL_ENTITY IN ('DOM-SUB-TNG_PREV')
and tFACT.PERIOD_IND = 'PREV' AND tFACT.MTH_TM_ID=&MTH_TM_ID-40));
DISCONNECT FROM NZCON;
 QUIT;

%MACRO APPEND(INPUT);
 	PROC APPEND BASE=NZRRAP.BASEL_CCAR_EXPSR_EXTR_ECL(BULKLOAD=YES BL_METHOD=CLILOAD)
				DATA=&INPUT FORCE;
%MEND APPEND;

%APPEND(TEMP1)
%APPEND(TEMP2)
%APPEND(TEMP3)
%APPEND(TEMP4)
%APPEND(TEMP5)
%APPEND(TEMP6)


 PROC SQL NOPRINT;
CONNECT USING NZRRAP AS NZCON;
EXECUTE(update EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ECL
set 
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT=0,
BEFORE_ZERO_NET_UNDRAWN_AMT=0,
AF_ZERO_NET_UNDRAWN_AMT=0,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT=0,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT=0,
EAD_PC = NULL,
CRNCY_CD = 'CAD',
PRTL_WRITE_OFF_AMT=0,
ACCR_INTR_AMT=0,
UNCONDTNLY_CNCLBL='TRUE'
where period_ind in ('PREV', 'MISS'))
BY NZCON;
 QUIT;
