
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);


%let datetime_start = %sysfunc(TIME()) ;
%put >>> START TIME: %sysfunc(datetime(),datetime14.);
options nosource;
%let outfile= outfile;
OPTIONS SOURCE NOTES;
%PUT &mth_tm_id.;

/*
SOURCE TABLES      

EDRTLRT.TM_DIM
&DB..BASEL_NCR_BUS_AGGRTD_FACT
&DB..BASEL_NCR_RISK_RT_SYS_DIM
&DB..BASEL_TANGRN_NCR_BE_FACT
&DB..BASEL_CANDN_RTL_NCR_BE_FACT
&DB..BASEL_EXPSR_CL_DIM
&DB..BASEL_NCR_HIERARCHY_LKP
&DB..BASEL_NCR_PD_SEG_DIM
&DB..BASEL_NCR_LGD_SEG_DIM
&DB..BASEL_NCR_EAD_SEG_DIM


TARGET TABLES

&DB..BASEL_P2_005
&DB..BASEL_P2_010
&DB..BASEL_P2_011
&DB..BASEL_P2_012
&DB..BASEL_P2_015
&DB..BASEL_P2_020
&DB..BASEL_P2_030
&DB..BASEL_P2_040
*/

%global outfile;
%global mth_tm_id;
%global tm_lvl_st_dt;
%global tm_lvl_end_dt;
%global dtime;




proc sql noprint;
select tm_id as mth_tm_id, tm_lvl_st_dt, tm_lvl_end_dt , datetime() as dtime format datetime25.
into :mth_tm_id, :tm_lvl_st_dt, :tm_lvl_end_dt, :dtime
from  EDRTLRT.TM_DIM
where tm_id=&mth_tm_id.;
quit;

%PUT &mth_tm_id.;
%PUT &tm_lvl_st_dt.;
%PUT &tm_lvl_end_dt.;
%PUT &dtime.;



%global yearmonth;

/*Fetch the Year and Month from TM_DIM Output TO  MTH_TM_ID and YearMonth and creates Work._TempYearMonth Table*/
proc sql noprint ;
   connect USING EDRRAPT as dbcon;
                select compress(yrmo,"-") into :yearmonth
                  from connection to dbcon (
select substr(tm_lvl_st_dt,1,7) as yrmo from edrtlrt.tm_dim where tm_id=&MTH_TM_ID);
DISCONNECT FROM DBCON;
quit;



/**************************************************************************************
 BE_P2_005.sas
REVISED 3RD SEP RE MODIFICATIONS TO BSTM
**************************************************************************************/
options nosource;

PROC SQL;
CREATE TABLE BASEL_P2_005_TMP1 AS
SELECT 
"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.,
"&dtime."dt AS EXTRACT_TMSTMP format datetime25.,
'005' AS NCR_RECD_TP format $3.,
'0599' AS NCR_EXPSR_CL format $4.,
NCR_RISK_RT_KEY_VAL AS NCR_RISK_RT_SYS format $4.,
'0999' AS NCR_PD_SEG format $4.,
'3299' AS NCR_LGD_SEG format $4.,
'3399' AS NCR_EAD_SEG format $4.,
NCR_RISK_RT_DESC AS RISK_RT_SYS_NM  Length=60 format $60.,
"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.,
"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.
      FROM &DB..BASEL_NCR_RISK_RT_SYS_DIM
      WHERE input(NCR_RISK_RT_KEY_VAL,8.) in (201,202,203,207)
AND &YEARMONTH. between input(eff_from_yr_mth,6.) and input(eff_to_yr_mth,6.);
;Quit;


/*  APPENDING  2 TABLES ABOVE  */
PROC SQL;
CREATE TABLE BASEL_P2_005_TMP3 AS
SELECT
MTH_END_DT,
EXTRACT_TMSTMP,
NCR_RECD_TP LENGTH=3 FORMAT=$3.  LABEL='NCR_RECD_TP',
NCR_EXPSR_CL LENGTH=4,
NCR_RISK_RT_SYS  LENGTH=4  LABEL='NCR_RISK_RT_SYS',
NCR_PD_SEG  LENGTH=4,
NCR_LGD_SEG  LENGTH=4,
NCR_EAD_SEG  LENGTH=4,
RISK_RT_SYS_NM  LENGTH=60 FORMAT=$60. LABEL='RISK_RT_SYS_NM',
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
FROM BASEL_P2_005_TMP1

;
QUIT;

/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source  */


proc sql;
delete from &DB..BASEL_P2_005 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;


PROC APPEND BASE=&DB..BASEL_P2_005 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_005_TMP3; 
RUN;

%put &SYSDSN.;
%put &SQLOBS.;

DATA OUTFILE.BASEL_P2_005;
	SET BASEL_P2_005_TMP3;
RUN;


PROC DATASETS LIB=WORK KILL NOLIST ;
RUN;
QUIT;
/**************************************************************************************
  BE_P2_010.sas
REVISED ON 3RD Sep 2014
**************************************************************************************/
PROC SQL;
CREATE TABLE BASEL_P2_010_TMP1 AS
SELECT
"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.,
"&dtime."dt AS EXTRACT_TMSTMP format datetime25.,
'010' AS NCR_RECD_TP format $3.,
'0599' AS NCR_EXPSR_CL,
/*'0201' AS NCR_RISK_RT_SYS,*/
NCR_PD_SEG_KEY_VAL AS NCR_PD_SEG,
'3299' AS NCR_LGD_SEG,
'3399' AS NCR_EAD_SEG,
NCR_PD_SEG_DESC AS PD_SEG_NM,
"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.,
"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.
	FROM outfile.BASEL_NCR_PD_SEG_DIM
    WHERE NCR_PD_SEG_KEY_VAL not in ( '0999','0998')
	AND &YEARMONTH. between input(eff_from_yr_mth,6.) and input(eff_to_yr_mth,6.)

	ORDER BY NCR_RECD_TP, NCR_EXPSR_CL, NCR_PD_SEG, NCR_LGD_SEG, NCR_EAD_SEG, PD_SEG_NM
;
Quit;


PROC SQL;
CREATE TABLE BASEL_P2_010_TMP3 AS
SELECT
MTH_END_DT,
EXTRACT_TMSTMP,
NCR_RECD_TP LENGTH=3 FORMAT=$3.  LABEL='NCR_RECD_TP',
NCR_EXPSR_CL LENGTH=4,
'0201' as NCR_RISK_RT_SYS  LENGTH=4  LABEL='NCR_RISK_RT_SYS',
NCR_PD_SEG  LENGTH=4,
NCR_LGD_SEG  LENGTH=4,
NCR_EAD_SEG  LENGTH=4,
PD_SEG_NM  LENGTH=60 FORMAT=$60. LABEL='PD_SEG_NM',
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
FROM BASEL_P2_010_TMP1
UNION ALL
SELECT
MTH_END_DT,
EXTRACT_TMSTMP,
NCR_RECD_TP LENGTH=3 FORMAT=$3. LABEL='NCR_RECD_TP',
NCR_EXPSR_CL LENGTH=4,
'0207' as NCR_RISK_RT_SYS  LENGTH=4  LABEL='NCR_RISK_RT_SYS',
NCR_PD_SEG  LENGTH=4,
NCR_LGD_SEG  LENGTH=4,
NCR_EAD_SEG  LENGTH=4,
PD_SEG_NM  LENGTH=60 FORMAT=$60. LABEL='PD_SEG_NM',
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
FROM BASEL_P2_010_TMP1
;
QUIT;

/***********************************************************************************************/
/*****************************   APPENDING AND CLEARING TEMP FILES   ***************************/
/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source  */

proc sql;
delete from &DB..BASEL_P2_010 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;

PROC APPEND BASE=ldd.BASEL_P2_010 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_010_TMP3; 

RUN;

%put &SYSDSN.;
%put &SQLOBS.;


DATA OUTFILE.BASEL_P2_010;
	SET BASEL_P2_010_TMP3;
RUN;

PROC DATASETS LIB=WORK KILL NOLIST ;
RUN;
QUIT;

/**************************************************************************************
  BE_P2_011.sas
REVISED ON 3RD Sep 2014
**************************************************************************************/

PROC SQL;
CREATE TABLE BASEL_P2_011_TMP1 AS
SELECT
"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.,
"&dtime."dt AS EXTRACT_TMSTMP format datetime25.,
'011' AS NCR_RECD_TP format $3.,
'0599' AS NCR_EXPSR_CL,
/*'0201' AS NCR_RISK_RT_SYS,*/
'0999' AS NCR_PD_SEG,
NCR_LGD_SEG_KEY_VAL AS NCR_LGD_SEG,
'3399' AS NCR_EAD_SEG,
NCR_LGD_SEG_DESC AS LGD_SEG_NM,
"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.,
"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.
	FROM outfile.BASEL_NCR_LGD_SEG_DIM
	WHERE NCR_LGD_SEG_KEY_VAL not in ('3298', '3299')
	AND &YEARMONTH. between input(eff_from_yr_mth,6.) and input(eff_to_yr_mth,6.)
	ORDER BY NCR_RECD_TP, NCR_EXPSR_CL,  NCR_PD_SEG, NCR_LGD_SEG, NCR_EAD_SEG;
Quit;


PROC SQL;
CREATE TABLE BASEL_P2_011_TMP3 AS
SELECT
MTH_END_DT,
EXTRACT_TMSTMP,
NCR_RECD_TP LENGTH=3 FORMAT=$3.  LABEL='NCR_RECD_TP',
NCR_EXPSR_CL LENGTH=4,
'0201' as NCR_RISK_RT_SYS  LENGTH=4  LABEL='NCR_RISK_RT_SYS',
NCR_PD_SEG  LENGTH=4,
NCR_LGD_SEG  LENGTH=4,
NCR_EAD_SEG  LENGTH=4,
LGD_SEG_NM  LENGTH=60 FORMAT=$60. LABEL='LGD_SEG_NM',
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
FROM BASEL_P2_011_TMP1
UNION ALL
SELECT
MTH_END_DT,
EXTRACT_TMSTMP,
NCR_RECD_TP LENGTH=3 FORMAT=$3. LABEL='NCR_RECD_TP',
NCR_EXPSR_CL LENGTH=4,
'0207' as NCR_RISK_RT_SYS  LENGTH=4  LABEL='NCR_RISK_RT_SYS',
NCR_PD_SEG  LENGTH=4,
NCR_LGD_SEG  LENGTH=4,
NCR_EAD_SEG  LENGTH=4,
LGD_SEG_NM  LENGTH=60 FORMAT=$60. LABEL='LGD_SEG_NM',
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
FROM BASEL_P2_011_TMP1
;
QUIT;

/***********************************************************************************************/
/*****************************   APPENDING AND CLEARING TEMP FILES   ***************************/
/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source  */

proc sql;
delete from &DB..BASEL_P2_011 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;

PROC APPEND BASE=LDD.BASEL_P2_011 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_011_TMP3; 

RUN;

%put &SYSDSN.;
%put &SQLOBS.;


DATA OUTFILE.BASEL_P2_011;
	SET BASEL_P2_011_TMP3;
RUN;

;

PROC DATASETS LIB=WORK KILL NOLIST ;
RUN;
QUIT;
/**************************************************************************************
  BE_P2_012.sas
REVISED ON 3RD Sep 2014
**************************************************************************************/

PROC SQL;
CREATE TABLE BASEL_P2_012_TMP1 AS
SELECT DISTINCT 
"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.,
"&dtime."dt AS EXTRACT_TMSTMP format datetime25.,
'012' AS NCR_RECD_TP format $3.,
'0599' AS NCR_EXPSR_CL,
'0201' AS NCR_RISK_RT_SYS,
'0999' AS NCR_PD_SEG,
'3299' AS NCR_LGD_SEG,
NCR_EAD_SEG_KEY_VAL AS NCR_EAD_SEG,
NCR_EAD_SEG_DESC AS EAD_SEG_NM,
"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.,
"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.
	FROM outfile.BASEL_NCR_EAD_SEG_DIM
    WHERE NCR_EAD_SEG_KEY_VAL not in ('3399','3398')
	AND &YEARMONTH. between input(eff_from_yr_mth,6.) and input(eff_to_yr_mth,6.)
	ORDER BY NCR_RECD_TP, NCR_EXPSR_CL, NCR_RISK_RT_SYS, NCR_PD_SEG, NCR_LGD_SEG, NCR_EAD_SEG
;
Quit;


PROC SQL THREADS;
CREATE TABLE BASEL_P2_012_TMP3 AS
SELECT DISTINCT
MTH_END_DT,
EXTRACT_TMSTMP,
NCR_RECD_TP LENGTH=3 FORMAT=$3.  LABEL='NCR_RECD_TP',
NCR_EXPSR_CL LENGTH=4,
NCR_RISK_RT_SYS  LENGTH=4  LABEL='NCR_RISK_RT_SYS',
NCR_PD_SEG  LENGTH=4,
NCR_LGD_SEG  LENGTH=4,
NCR_EAD_SEG  LENGTH=4,
EAD_SEG_NM  LENGTH=60 FORMAT=$60. LABEL='LGD_SEG_NM',
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
FROM BASEL_P2_012_TMP1
UNION ALL
SELECT
MTH_END_DT,
EXTRACT_TMSTMP,
NCR_RECD_TP LENGTH=3 FORMAT=$3. LABEL='NCR_RECD_TP',
NCR_EXPSR_CL LENGTH=4,
'0207' as NCR_RISK_RT_SYS  LENGTH=4  LABEL='NCR_RISK_RT_SYS',
NCR_PD_SEG  LENGTH=4,
NCR_LGD_SEG  LENGTH=4,
NCR_EAD_SEG  LENGTH=4,
EAD_SEG_NM  LENGTH=60 FORMAT=$60. LABEL='LGD_SEG_NM',
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
FROM BASEL_P2_012_TMP1
;
QUIT;

proc sql;
delete from &DB..BASEL_P2_012 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;
/***********************************************************************************************/
/*****************************   APPENDING AND CLEARING TEMP FILES   ***************************/
/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source  */
PROC APPEND BASE=LDD.BASEL_P2_012 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_012_TMP3;

RUN;

%put &SYSDSN.;
%put &SQLOBS.;

DATA OUTFILE.BASEL_P2_012;
	SET BASEL_P2_012_TMP3;
RUN;

/**************************************************************************************
  BE_P2_015.sas
REVISED ON 3RD Sep 2014
**************************************************************************************/

data outfile.BASEL_CANDN_RTL_NCR_BE_FACT;
set ldd.BASEL_CANDN_RTL_NCR_BE_FACT;
where MTH_TM_ID=&MTH_TM_ID;
run;
PROC DATASETS LIB=WORK KILL NOLIST ;
RUN;
QUIT;
PROC SQL;
CREATE TABLE BASEL_P2_015_TMP1 AS
SELECT distinct
"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.,
"&dtime."dt AS EXTRACT_TMSTMP format datetime25.,
'015' AS NCR_RECD_TP format $3.,
B.NCR_EXPSR_CL_KEY_VAL AS NCR_EXPSR_CL Label='NCR_EXPSR_CL' format $4.,
'0299' AS NCR_RISK_RT_SYS format $4.,
'0999' AS NCR_PD_SEG format $4.,
'3299' AS NCR_LGD_SEG format $4.,
'3399' AS NCR_EAD_SEG format $4.,
(A.ECONMC_CAPTL_AMT
/*+C.ECONMC_CAPTL_AMT*/
)/1000 AS ECONMC_CAPTL,
"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.,
"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.
	FROM outfile.BASEL_CANDN_RTL_NCR_BE_FACT A

	LEFT JOIN outfile.BASEL_EXPSR_CL_DIM B ON A.EXPSR_CL_ID = b.EXPSR_CL_ID
	AND &YEARMONTH. between input(eff_from_yr_mth,6.) and input(eff_to_yr_mth,6.)


	WHERE B.NCR_EXPSR_CL_KEY_VAL in ('0502','0503','0505','0506','0507')
	AND A.ECONMC_CAPTL_AMT NE .

	AND A.MTH_TM_ID=&mth_tm_id.

	Order By B.NCR_EXPSR_CL_KEY_VAL
;
Quit;


/*     GROUPING THE DATA TO GET RID OF 0 VALUE RECORDS  */
PROC SQL;
CREATE TABLE BASEL_P2_015_TMP2 AS
SELECT MTH_END_DT,EXTRACT_TMSTMP,NCR_RECD_TP,NCR_EXPSR_CL,NCR_RISK_RT_SYS,NCR_PD_SEG,NCR_LGD_SEG,
NCR_EAD_SEG,round(Sum(econmc_captl)) AS ECONMC_CAPTL, INSRT_PROCESS_TMSTMP,UPDT_PROCESS_TMSTMP
From BASEL_P2_015_TMP1

Group By MTH_END_DT,EXTRACT_TMSTMP,NCR_RECD_TP,NCR_EXPSR_CL,NCR_RISK_RT_SYS,NCR_PD_SEG,NCR_LGD_SEG,
NCR_EAD_SEG,INSRT_PROCESS_TMSTMP,UPDT_PROCESS_TMSTMP

Order By MTH_END_DT,EXTRACT_TMSTMP,NCR_RECD_TP,NCR_EXPSR_CL,NCR_RISK_RT_SYS,NCR_PD_SEG,NCR_LGD_SEG,
NCR_EAD_SEG,INSRT_PROCESS_TMSTMP,UPDT_PROCESS_TMSTMP
;
Quit;

/***********************************************************************************************/
/*****************************   APPENDING AND CLEARING TEMP FILES   ***************************/
/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source  */
proc sql;
delete from &DB..BASEL_P2_015 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;

PROC APPEND BASE=&DB..BASEL_P2_015 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_015_TMP2; 

RUN;

%put &SYSDSN.;
%put &SQLOBS.;


DATA OUTFILE.BASEL_P2_015;
	SET BASEL_P2_015_TMP2;
RUN;

PROC DATASETS LIB=WORK KILL NOLIST ;
RUN;
QUIT;

/**************************************************************************************
  BE_P2_020.sas     Revised 8th Sep 2014  at 2:59pm
**************************************************************************************/

PROC SQL;
CONNECT USING EDRRAPT AS DB3CON;
CREATE TABLE SRC AS 
SELECT * FROM CONNECTION TO DB3CON
(SELECT DISTINCT
		NCR_RISK_RT_KEY_VAL
		, NCR_EXPSR_CL_KEY_VAL
		, NCR_PD_SEG_KEY_VAL
		, SUM(RPTG_QTR_ACCT_CNT) AS RPTG_QTR_ACCT_CNT
		, SUM(PD_REALZ_ACCT_CNT) AS PD_REALZ_ACCT_CNT
		, CASE WHEN SUM(RPTG_QTR_ACCT_CNT) = 0 THEN 0 ELSE SUM(PD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/SUM(RPTG_QTR_ACCT_CNT) END AS PD_ESTD_RTO
		, CASE WHEN SUM(PD_REALZ_ACCT_CNT) = 0 THEN 0 ELSE SUM(PD_REALZ_RTO*PD_REALZ_ACCT_CNT)/SUM(PD_REALZ_ACCT_CNT) END AS PD_REALZ_RTO
		, SUM(PD_REALZ_DEFLTD_OS_BAL_AMT) AS PD_REALZ_DEFLTD_OS_BAL_AMT
		, SUM(PD_REALZ_DEFLTD_ACCT_CNT) AS PD_REALZ_DEFLTD_ACCT_CNT
FROM EDRRAPT.BASEL_CANDN_RTL_NCR_BE_FACT BE
	INNER JOIN EDRRAPT.BASEL_NCR_RISK_RT_SYS_DIM RISK_RT ON
			RISK_RT.NCR_RISK_RT_SYS_ID = BE.NCR_RISK_RT_SYS_ID
	INNER JOIN EDRRAPT.BASEL_EXPSR_CL_DIM EXPSR_CL ON
			EXPSR_CL.EXPSR_CL_ID = BE.EXPSR_CL_ID
	INNER JOIN EDRRAPT.BASEL_NCR_PD_SEG_DIM PD ON
			PD.NCR_PD_SEG_ID = BE.NCR_PD_SEG_ID
	WHERE MTH_TM_ID = &mth_tm_id.
	AND ECONMC_CAPTL_AMT IS NULL
	GROUP BY NCR_RISK_RT_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_PD_SEG_KEY_VAL
	Order By NCR_RISK_RT_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_PD_SEG_KEY_VAL
);
DISCONNECT FROM DB3CON;
Quit;


PROC SQL;
CREATE TABLE SRC_ROLLUP AS 
SELECT 	NCR_RISK_RT_KEY_VAL
		, NCR_PRNT_KEY_VAL AS NCR_EXPSR_CL_KEY_VAL
		, NCR_PD_SEG_KEY_VAL
		, CASE WHEN SUM(RPTG_QTR_ACCT_CNT) = 0 THEN 0 ELSE SUM(PD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/SUM(RPTG_QTR_ACCT_CNT) END AS PD_ESTD_RTO
		, CASE WHEN SUM(PD_REALZ_ACCT_CNT) = 0 THEN 0 ELSE SUM(PD_REALZ_RTO*PD_REALZ_ACCT_CNT)/SUM(PD_REALZ_ACCT_CNT) END AS PD_REALZ_RTO
		, SUM(PD_REALZ_DEFLTD_OS_BAL_AMT) AS PD_REALZ_DEFLTD_OS_BAL_AMT
		, SUM(PD_REALZ_DEFLTD_ACCT_CNT) AS PD_REALZ_DEFLTD_ACCT_CNT
FROM SRC
		INNER JOIN &DB..BASEL_NCR_HIERARCHY_LKP EXPSR_CL
			ON EXPSR_CL.NCR_KEY_VAL = SRC.NCR_EXPSR_CL_KEY_VAL
GROUP BY NCR_RISK_RT_KEY_VAL, EXPSR_CL.NCR_PRNT_KEY_VAL, NCR_PD_SEG_KEY_VAL
;
quit;

PROC SQL;
CREATE TABLE Exposure_Class20 AS 
SELECT DISTINCT NCR_EXPSR_CL_KEY_VAL
FROM &DB..BASEL_EXPSR_CL_DIM
WHERE NCR_EXPSR_CL_KEY_VAL IN ('0500', '0501', '0502', '0503', '0504','0505', '0506', '0507')
;
/*** NCR_EXPSR_CL_KEY_VAL = '0504' has been added to fi defect #551 from Sreeraj ***/
quit;

PROC SQL;
CREATE TABLE PD_SEG20 AS 
SELECT DISTINCT NCR_PD_SEG_KEY_VAL
FROM &DB..BASEL_NCR_PD_SEG_DIM
WHERE NCR_PD_SEG_KEY_VAL not in ('0999','0998')
;
quit;

PROC SQL;
CREATE TABLE risk_rt20 AS 
SELECT DISTINCT NCR_RISK_RT_KEY_VAL
FROM &DB..BASEL_NCR_RISK_RT_SYS_DIM
WHERE   NCR_RISK_RT_KEY_VAL in ('0201','0207')
;
quit;


PROC SQL;
CREATE TABLE BASE_REC AS 
SELECT
		'020' AS NCR_RECD_TP
		,Exposure_Class.NCR_EXPSR_CL_KEY_VAL AS NCR_EXPSR_CL
		,risk_rt.NCR_RISK_RT_KEY_VAL
		,PD_SEG.NCR_PD_SEG_KEY_VAL AS NCR_PD_SEG
		,'3299' AS NCR_LGD_SEG
		,'3399' AS NCR_EAD_SEG
	FROM Exposure_Class20 as Exposure_Class
		CROSS JOIN PD_SEG20 as PD_SEG 
		CROSS JOIN risk_rt20 as risk_rt
;
quit;

PROC SQL;
CREATE TABLE BASEL_P2_020_TMP1 AS 
SELECT
	"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.
	,"&dtime."dt AS EXTRACT_TMSTMP format datetime25.
	,BASE_REC.NCR_RECD_TP Length=3  FORMAT $3.
	,BASE_REC.NCR_EXPSR_CL format $4.
	,BASE_REC.NCR_RISK_RT_KEY_VAL as NCR_RISK_RT_SYS format $4.
	,BASE_REC.NCR_PD_SEG format $4.
	,BASE_REC.NCR_LGD_SEG format $4.
	,BASE_REC.NCR_EAD_SEG format $4.
	,COALESCE(SRC_ROLLUP.PD_ESTD_RTO, 0)*100 AS ESTD_PD format 5.2
	,CASE WHEN BASE_REC.NCR_PD_SEG = '0923' THEN 100.00
			ELSE COALESCE(SRC_ROLLUP.PD_REALZ_RTO, 0) * 100
			END AS REALZ_PD format 5.2
	,ROUND(COALESCE(SRC_ROLLUP.PD_REALZ_DEFLTD_OS_BAL_AMT, 0)/1000) AS OS_BAL_AMT
	,COALESCE(SRC_ROLLUP.PD_REALZ_DEFLTD_ACCT_CNT, 0) AS REALZ_DFT_CNT
	,"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.
	,"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.
FROM BASE_REC
	LEFT JOIN SRC_ROLLUP
		ON SRC_ROLLUP.NCR_EXPSR_CL_KEY_VAL = BASE_REC.NCR_EXPSR_CL
		AND SRC_ROLLUP.NCR_PD_SEG_KEY_VAL = BASE_REC.NCR_PD_SEG
		AND SRC_ROLLUP.NCR_RISK_RT_KEY_VAL= BASE_REC.NCR_RISK_RT_KEY_VAL
		WHERE BASE_REC.NCR_PD_SEG not in ('0998', '0999')
ORDER BY BASE_REC.NCR_EXPSR_CL, BASE_REC.NCR_PD_SEG
;
quit;



PROC SQL;
CREATE TABLE BASEL_P2_020_TMP3 AS
SELECT
A.MTH_END_DT,
A.EXTRACT_TMSTMP,
A.NCR_RECD_TP,
A.NCR_EXPSR_CL,
A.NCR_RISK_RT_SYS,
A.NCR_PD_SEG,
A.NCR_LGD_SEG,
A.NCR_EAD_SEG,
round((case when A.ESTD_PD>100.00 then 100.00 else A.ESTD_PD end ),0.01) as ESTD_PD,
round((case when A.REALZ_PD>100.00 then 100.00 else A.REALZ_PD end ),0.01)  as REALZ_PD,
A.OS_BAL_AMT,
A.REALZ_DFT_CNT,
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
	FROM BASEL_P2_020_TMP1 A

;
Quit;

/***********************************************************************************************/
/*****************************   APPENDING AND CLEARING TEMP FILES   ***************************/
/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source   FORCE*/

proc sql;
delete from &DB..BASEL_P2_020 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;
PROC APPEND BASE=&DB..BASEL_P2_020 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_020_TMP3 ; 
WHERE SUBSTR(NCR_PD_SEG,3,2) NE '98' AND
SUBSTR(NCR_LGD_SEG,3,2) NE '98' AND
SUBSTR(NCR_EAD_SEG,3,2) NE '98';
WHERE ALSO NCR_PD_SEG NOT IN ( '0999' , '0998');
RUN;

%put &SYSDSN.;
%put &SQLOBS.;

DATA OUTFILE.BASEL_P2_020;
	SET BASEL_P2_020_TMP3;
RUN;

PROC DATASETS LIB=WORK KILL NOLIST ;
RUN;
QUIT;

/**************************************************************************************
  BE_P2_030.sas     Revised 8th Sep 2014
***************************************************************************************/
PROC SQL;
CONNECT USING EDRRAPT AS DB3CON ;
CREATE TABLE SRC AS 
SELECT * FROM CONNECTION TO DB3CON
(SELECT
		NCR_RISK_RT_KEY_VAL
		, NCR_EXPSR_CL_KEY_VAL
		, NCR_LGD_SEG_KEY_VAL
		, SUM(RPTG_QTR_ACCT_CNT) AS RPTG_QTR_ACCT_CNT
		, SUM(LGD_REALZ_ACCT_CNT) AS LGD_REALZ_ACCT_CNT
		, CASE WHEN SUM(RPTG_QTR_ACCT_CNT) = 0 THEN 0 ELSE SUM(LGD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/SUM(RPTG_QTR_ACCT_CNT) END AS LGD_ESTD_RTO
		, CASE WHEN SUM(LGD_REALZ_ACCT_CNT) = 0 THEN 0 ELSE SUM(LGD_REALZ_RTO*LGD_REALZ_ACCT_CNT)/SUM(LGD_REALZ_ACCT_CNT) END AS LGD_REALZ_RTO
		, SUM(LGD_REALZ_DEFLTD_OS_BAL_AMT) AS LGD_REALZ_DEFLTD_OS_BAL_AMT
		, SUM(LGD_REALZ_DEFLTD_ACCT_CNT) AS LGD_REALZ_DEFLTD_ACCT_CNT
	FROM EDRRAPT.BASEL_CANDN_RTL_NCR_BE_FACT BE
		INNER JOIN EDRRAPT.BASEL_NCR_RISK_RT_SYS_DIM RISK_RT ON
			RISK_RT.NCR_RISK_RT_SYS_ID = BE.NCR_RISK_RT_SYS_ID
		INNER JOIN EDRRAPT.BASEL_EXPSR_CL_DIM EXPSR_CL ON
			EXPSR_CL.EXPSR_CL_ID = BE.EXPSR_CL_ID
		INNER  JOIN EDRRAPT.BASEL_NCR_LGD_SEG_DIM LGD ON
			LGD.NCR_LGD_SEG_ID = BE.NCR_LGD_SEG_ID
	WHERE MTH_TM_ID = &mth_tm_id.
			AND ECONMC_CAPTL_AMT IS NULL
	GROUP BY NCR_RISK_RT_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_LGD_SEG_KEY_VAL
	Order By NCR_RISK_RT_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_LGD_SEG_KEY_VAL
);
DISCONNECT FROM DB3CON;
Quit;

PROC SQL;
CREATE TABLE SRC_ROLLUP AS 
SELECT	NCR_RISK_RT_KEY_VAL
		, NCR_PRNT_KEY_VAL AS NCR_EXPSR_CL_KEY_VAL
		, NCR_LGD_SEG_KEY_VAL
		, CASE WHEN SUM(RPTG_QTR_ACCT_CNT) = 0 THEN 0 ELSE SUM(LGD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/SUM(RPTG_QTR_ACCT_CNT) END AS LGD_ESTD_RTO
		, CASE WHEN SUM(LGD_REALZ_ACCT_CNT) = 0 THEN 0 ELSE SUM(LGD_REALZ_RTO*LGD_REALZ_ACCT_CNT)/SUM(LGD_REALZ_ACCT_CNT) END AS LGD_REALZ_RTO
		, SUM(LGD_REALZ_DEFLTD_OS_BAL_AMT) AS LGD_REALZ_DEFLTD_OS_BAL_AMT
		, SUM(LGD_REALZ_DEFLTD_ACCT_CNT) AS LGD_REALZ_DEFLTD_ACCT_CNT
FROM SRC
		INNER JOIN OUTFILE.BASEL_NCR_HIERARCHY_LKP EXPSR_CL
			ON EXPSR_CL.NCR_KEY_VAL = SRC.NCR_EXPSR_CL_KEY_VAL
	GROUP BY NCR_RISK_RT_KEY_VAL, EXPSR_CL.NCR_PRNT_KEY_VAL, NCR_LGD_SEG_KEY_VAL
;
quit;

PROC SQL;
CREATE TABLE Exposure_Class AS 
SELECT DISTINCT NCR_EXPSR_CL_KEY_VAL
FROM OUTFILE.BASEL_EXPSR_CL_DIM
WHERE NCR_EXPSR_CL_KEY_VAL IN ('0500', '0501', '0502', '0503', '0504', '0505', '0506', '0507')
;
quit;

PROC SQL;
CREATE TABLE LGD_SEG AS 
SELECT DISTINCT NCR_LGD_SEG_KEY_VAL
FROM &DB..BASEL_NCR_LGD_SEG_DIM
WHERE NCR_LGD_SEG_KEY_VAL NE '3299'
;
quit;


PROC SQL;
CREATE TABLE risk_rt AS 
SELECT DISTINCT NCR_RISK_RT_KEY_VAL
FROM &DB..BASEL_NCR_RISK_RT_SYS_DIM
WHERE   NCR_RISK_RT_KEY_VAL in ('0201','0207')
;
quit;
PROC SQL;
CREATE TABLE BASE_REC AS 
SELECT
		'030' AS NCR_RECD_TP
		,Exposure_Class.NCR_EXPSR_CL_KEY_VAL AS NCR_EXPSR_CL
		,risk_rt.NCR_RISK_RT_KEY_VAL
		,'0999' AS NCR_PD_SEG
		,LGD_SEG.NCR_LGD_SEG_KEY_VAL 
		,'3399' AS NCR_EAD_SEG
	FROM Exposure_Class
		CROSS JOIN LGD_SEG
		CROSS JOIN risk_rt
;
quit;


PROC SQL;
CREATE TABLE BASEL_P2_030_TMP1 AS
SELECT
	"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.
	,"&dtime."dt AS EXTRACT_TMSTMP format datetime25.
	,BASE_REC.NCR_RECD_TP Length=3  FORMAT $3.
	,BASE_REC.NCR_EXPSR_CL format $4.
	,BASE_REC.NCR_RISK_RT_KEY_VAL as NCR_RISK_RT_SYS format $4.
	,BASE_REC.NCR_PD_SEG format $4.
	,BASE_REC.NCR_LGD_SEG_KEY_VAL as NCR_LGD_SEG format $4.
	,BASE_REC.NCR_EAD_SEG format $4.
	,COALESCE(SRC_ROLLUP.LGD_ESTD_RTO, 0)*100 AS ESTD_LGD format 5.2
	,COALESCE(SRC_ROLLUP.LGD_REALZ_RTO, 0)*100 AS REALZ_LGD format 5.2
	,ROUND(COALESCE(SRC_ROLLUP.LGD_REALZ_DEFLTD_OS_BAL_AMT, 0)/1000) AS OS_BAL_AMT
	,COALESCE(SRC_ROLLUP.LGD_REALZ_DEFLTD_ACCT_CNT, 0) AS REALZ_DFT_CNT
	,"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.
	,"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.
FROM BASE_REC 
	LEFT JOIN SRC_ROLLUP ON
		SRC_ROLLUP.NCR_EXPSR_CL_KEY_VAL = BASE_REC.NCR_EXPSR_CL
		AND SRC_ROLLUP.NCR_LGD_SEG_KEY_VAL = BASE_REC.NCR_LGD_SEG_KEY_VAL
		AND SRC_ROLLUP.NCR_RISK_RT_KEY_VAL= BASE_REC.NCR_RISK_RT_KEY_VAL
		WHERE BASE_REC.NCR_LGD_SEG_KEY_VAL not in ('3298', '3299')
ORDER BY BASE_REC.NCR_EXPSR_CL, BASE_REC.NCR_LGD_SEG_KEY_VAL
;
quit;


PROC SQL;
CREATE TABLE BASEL_P2_030_TMP3 AS
SELECT
A.MTH_END_DT,
A.EXTRACT_TMSTMP,
A.NCR_RECD_TP,
A.NCR_EXPSR_CL,
A.NCR_RISK_RT_SYS,
A.NCR_PD_SEG,
A.NCR_LGD_SEG,
A.NCR_EAD_SEG,
(case when A.ESTD_LGD>100.00 then 100.00 else A.ESTD_LGD end ) as ESTD_LGD,
(case when A.REALZ_LGD>100.00 then 100.00 else A.REALZ_LGD end ) as REALZ_LGD,
A.OS_BAL_AMT,
A.REALZ_DFT_CNT,
INSRT_PROCESS_TMSTMP format datetime25.,
UPDT_PROCESS_TMSTMP format datetime25.
	FROM BASEL_P2_030_TMP1 A
;
Quit;

/***********************************************************************************************/
/*****************************   APPENDING AND CLEARING TEMP FILES   ***************************/
/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source  */

proc sql;
delete from &DB..BASEL_P2_030 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;
PROC APPEND BASE=&DB..BASEL_P2_030 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_030_TMP3 ; 
WHERE SUBSTR(NCR_PD_SEG,3,2) NE '98' AND
SUBSTR(NCR_LGD_SEG,3,2) NE '98' AND
SUBSTR(NCR_EAD_SEG,3,2) NE '98';
WHERE ALSO NCR_LGD_SEG NOT IN ( '3299' , '3298');
RUN;

%put &SYSDSN.;
%put &SQLOBS.;

DATA OUTFILE.BASEL_P2_030;
	SET BASEL_P2_030_TMP3;
RUN;

PROC DATASETS LIB=WORK KILL NOLIST ;
RUN;
QUIT;
/**************************************************************************************
  BE_P2_040.sas     Revised 8th Sep 2014
***************************************************************************************/
PROC SQL;
CONNECT USING EDRRAPT AS DB3CON ;
CREATE TABLE SRC40 AS 
SELECT * FROM CONNECTION TO DB3CON
(SELECT
		NCR_RISK_RT_KEY_VAL
		, NCR_EXPSR_CL_KEY_VAL
		, NCR_EAD_SEG_KEY_VAL
		, SUM(RPTG_QTR_ACCT_CNT) AS RPTG_QTR_ACCT_CNT
		, SUM(EAD_REALZ_ACCT_CNT) AS EAD_REALZ_ACCT_CNT
		, CASE WHEN SUM(RPTG_QTR_ACCT_CNT) = 0 THEN 0 ELSE SUM(EAD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/SUM(RPTG_QTR_ACCT_CNT) END AS EAD_ESTD_RTO
		, CASE WHEN SUM(EAD_REALZ_ACCT_CNT) = 0 THEN 0 ELSE SUM(EAD_REALZ_RTO*EAD_REALZ_ACCT_CNT)/SUM(EAD_REALZ_ACCT_CNT) END AS EAD_REALZ_RTO
		, SUM(EAD_REALZ_DEFLTD_OS_BAL_AMT) AS EAD_REALZ_DEFLTD_OS_BAL_AMT
		, SUM(EAD_REALZ_DEFLTD_ACCT_CNT) AS EAD_REALZ_DEFLTD_ACCT_CNT
	FROM EDRRAPT.BASEL_CANDN_RTL_NCR_BE_FACT BE
		INNER JOIN EDRRAPT.BASEL_NCR_RISK_RT_SYS_DIM RISK_RT ON
			RISK_RT.NCR_RISK_RT_SYS_ID = BE.NCR_RISK_RT_SYS_ID
		INNER JOIN EDRRAPT.BASEL_EXPSR_CL_DIM EXPSR_CL ON
			EXPSR_CL.EXPSR_CL_ID = BE.EXPSR_CL_ID
		INNER JOIN EDRRAPT.BASEL_NCR_EAD_SEG_DIM EAD ON
			EAD.NCR_EAD_SEG_ID = BE.NCR_EAD_SEG_ID
	WHERE MTH_TM_ID = &mth_tm_id.
			AND ECONMC_CAPTL_AMT IS NULL
	GROUP BY NCR_RISK_RT_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_EAD_SEG_KEY_VAL
	ORDER BY NCR_RISK_RT_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_EAD_SEG_KEY_VAL
);
DISCONNECT FROM DB3CON;
Quit;




PROC SQL;
CREATE TABLE SRC_ROLLUP40 AS 
SELECT
		NCR_RISK_RT_KEY_VAL
		, NCR_PRNT_KEY_VAL AS NCR_EXPSR_CL_KEY_VAL
		, NCR_EAD_SEG_KEY_VAL
		, CASE WHEN SUM(RPTG_QTR_ACCT_CNT) = 0 THEN 0 ELSE SUM(EAD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/SUM(RPTG_QTR_ACCT_CNT) END AS EAD_ESTD_RTO
		, CASE WHEN SUM(EAD_REALZ_ACCT_CNT) = 0 THEN 0 ELSE SUM(EAD_REALZ_RTO*EAD_REALZ_ACCT_CNT)/SUM(EAD_REALZ_ACCT_CNT) END AS EAD_REALZ_RTO
		, SUM(EAD_REALZ_DEFLTD_OS_BAL_AMT) AS EAD_REALZ_DEFLTD_OS_BAL_AMT
		, SUM(EAD_REALZ_DEFLTD_ACCT_CNT) AS EAD_REALZ_DEFLTD_ACCT_CNT
FROM SRC40
		INNER JOIN OUTFILE.BASEL_NCR_HIERARCHY_LKP EXPSR_CL ON
			EXPSR_CL.NCR_KEY_VAL = SRC40.NCR_EXPSR_CL_KEY_VAL
	GROUP BY NCR_RISK_RT_KEY_VAL, EXPSR_CL.NCR_PRNT_KEY_VAL, NCR_EAD_SEG_KEY_VAL
;
quit;




PROC SQL;
CREATE TABLE Exposure_Class40 AS 
SELECT DISTINCT NCR_EXPSR_CL_KEY_VAL
FROM OUTFILE.BASEL_EXPSR_CL_DIM
WHERE NCR_EXPSR_CL_KEY_VAL IN ('0500', '0501', '0502', '0503', '0504', '0505', '0506', '0507')
;
quit;



PROC SQL;
CREATE TABLE EAD_SEG40 AS
SELECT DISTINCT NCR_EAD_SEG_KEY_VAL
FROM OUTFILE.BASEL_NCR_EAD_SEG_DIM
WHERE NCR_EAD_SEG_KEY_VAL NE '3399'
;
quit;



PROC SQL;
CREATE TABLE risk_rt40 AS 
SELECT DISTINCT NCR_RISK_RT_KEY_VAL
FROM &DB..BASEL_NCR_RISK_RT_SYS_DIM
WHERE   NCR_RISK_RT_KEY_VAL in ('0201','0207')
;
quit;

PROC SQL;
CREATE TABLE BASE_REC40 AS
SELECT 
		'040' AS NCR_RECD_TP
		,Exposure_Class40.NCR_EXPSR_CL_KEY_VAL AS NCR_EXPSR_CL
			,risk_rt40.NCR_RISK_RT_KEY_VAL
		,'0999' AS NCR_PD_SEG
		,'3299' AS NCR_LGD_SEG
		,EAD_SEG40.NCR_EAD_SEG_KEY_VAL AS NCR_EAD_SEG
	FROM Exposure_Class40
		CROSS JOIN EAD_SEG40 
		CROSS JOIN risk_rt40 
;
quit;


PROC SQL;
CREATE TABLE BASEL_P2_040_TMP1 AS
SELECT
	"&tm_lvl_end_dt."d as MTH_END_DT FORMAT DATE9.
	,"&dtime."dt AS EXTRACT_TMSTMP format datetime25.
	,BASE_REC40.NCR_RECD_TP Length=3  FORMAT $3.
	,BASE_REC40.NCR_EXPSR_CL format $4.
	,BASE_REC40.NCR_RISK_RT_KEY_VAL as NCR_RISK_RT_SYS format $4.
	,BASE_REC40.NCR_PD_SEG format $4.
	,BASE_REC40.NCR_LGD_SEG format $4.
	,BASE_REC40.NCR_EAD_SEG format $4.
	,COALESCE(SRC_ROLLUP40.EAD_ESTD_RTO, 0)*100 AS ESTD_EAD format 5.2
	,CASE
		WHEN BASE_REC40.NCR_EAD_SEG = '3308' THEN 100.00
		ELSE COALESCE(SRC_ROLLUP40.EAD_REALZ_RTO, 0)*100
		END AS REALZ_EAD format 5.2
	,ROUND(COALESCE(SRC_ROLLUP40.EAD_REALZ_DEFLTD_OS_BAL_AMT, 0)/1000) AS OS_BAL_AMT
	,COALESCE(SRC_ROLLUP40.EAD_REALZ_DEFLTD_ACCT_CNT, 0) AS REALZ_DFT_CNT
	,"&dtime."dt AS INSRT_PROCESS_TMSTMP format datetime25.
	,"&dtime."dt AS UPDT_PROCESS_TMSTMP format datetime25.

FROM BASE_REC40 
	LEFT JOIN SRC_ROLLUP40 ON
		SRC_ROLLUP40.NCR_EXPSR_CL_KEY_VAL = BASE_REC40.NCR_EXPSR_CL
		AND SRC_ROLLUP40.NCR_EAD_SEG_KEY_VAL = BASE_REC40.NCR_EAD_SEG
		AND SRC_ROLLUP40.NCR_RISK_RT_KEY_VAL= BASE_REC40.NCR_RISK_RT_KEY_VAL
		WHERE BASE_REC40.NCR_EAD_SEG not in ('3298', '3299')
ORDER BY BASE_REC40.NCR_EXPSR_CL, BASE_REC40.NCR_EAD_SEG
;
quit;




PROC SQL;
CREATE TABLE BASEL_P2_040_TMP3 AS
SELECT
A.MTH_END_DT,
A.EXTRACT_TMSTMP,
A.NCR_RECD_TP,
A.NCR_EXPSR_CL,
A.NCR_RISK_RT_SYS,
A.NCR_PD_SEG,
A.NCR_LGD_SEG,
A.NCR_EAD_SEG,
round((case when A.ESTD_EAD>100.00 then 100.00 else A.ESTD_EAD end ),0.01) as ESTD_EAD,
round((case when A.REALZ_EAD>100.00 then 100.00 else A.REALZ_EAD end ),0.01) as REALZ_EAD,
A.OS_BAL_AMT,
A.REALZ_DFT_CNT,
A.INSRT_PROCESS_TMSTMP format datetime25.,
A.UPDT_PROCESS_TMSTMP format datetime25.
	FROM BASEL_P2_040_TMP1 A

;
Quit;

/***********************************************************************************************/
/*****************************   APPENDING AND CLEARING TEMP FILES   ***************************/
/*   "Append the DATA to the BASE "       BASE=Detination,    DATA=Source  */

proc sql;
delete from &DB..BASEL_P2_040 where MTH_END_DT="&tm_lvl_end_dt."d ;
quit;

PROC APPEND BASE=&DB..BASEL_P2_040 (BULKLOAD=YES BL_METHOD=CLILOAD) DATA=BASEL_P2_040_TMP3 ; 
WHERE SUBSTR(NCR_PD_SEG,3,2) NE '98' AND
SUBSTR(NCR_LGD_SEG,3,2) NE '98' AND
SUBSTR(NCR_EAD_SEG,3,2) NE '98';
WHERE ALSO NCR_EAD_SEG NOT IN ( '3399' , '3398');
RUN;

%put &SYSDSN.;
%put &SQLOBS.;

DATA OUTFILE.BASEL_P2_040;
	SET BASEL_P2_040_TMP3;
RUN;


%put >>> END TIME: %sysfunc(datetime(),datetime14.);
%put >>> Benchmarking PROCESSING TIME:  %sysfunc(putn(%sysevalf(%sysfunc(TIME())-&datetime_start.),mmss.)) (mm:ss) ;

