/**************************************************************************** 
 * Job:             RRAP_MOR_MODEL_57_DEFAULT_MONTHS_G    A57SWEI7.BH0009KA * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/04 - Mortgage/BNS                   * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:43:02 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009KA);
%let etls_jobName = %nrquote(RRAP_MOR_MODEL_57_DEFAULT_MONTHS_G);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_mortgage_autoexec             A57SWEI7.BK000Z6S * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z6S);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mortgage_autoexec **/

/*==========================================================================* 
 * Step:            User Written                          A57SWEI7.BK000Z6T * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Target Table:    User Written - work.W1U78SU           A57SWEI7.BN000NLH * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z6T);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.W1U78SU;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NLH%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = _run_date _run_date_yymth _run_date24;
%let _OUTPUT_col_count = 3;
%let _OUTPUT_col0_name = _run_date;
%let _OUTPUT_col0_table = work.W1U78SU;
%let _OUTPUT_col0_length = 10;
%let _OUTPUT_col0_type = $;
%let _OUTPUT_col0_format = $10.;
%let _OUTPUT_col0_informat = $10.;
%let _OUTPUT_col0_label = %nrquote();
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = _run_date_yymth;
%let _OUTPUT_col1_table = work.W1U78SU;
%let _OUTPUT_col1_length = 6;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = $10.;
%let _OUTPUT_col1_informat = $10.;
%let _OUTPUT_col1_label = %nrquote();
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input_count = 0;
%let _OUTPUT_col2_name = _run_date24;
%let _OUTPUT_col2_table = work.W1U78SU;
%let _OUTPUT_col2_length = 10;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = $10.;
%let _OUTPUT_col2_informat = $10.;
%let _OUTPUT_col2_label = %nrquote();
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input_count = 0;

%let _OUTPUT1 = work.W1U78SU;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NLH%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = _run_date _run_date_yymth _run_date24;
%let _OUTPUT1_col_count = 3;
%let _OUTPUT1_col0_name = _run_date;
%let _OUTPUT1_col0_table = work.W1U78SU;
%let _OUTPUT1_col0_length = 10;
%let _OUTPUT1_col0_type = $;
%let _OUTPUT1_col0_format = $10.;
%let _OUTPUT1_col0_informat = $10.;
%let _OUTPUT1_col0_label = %nrquote();
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input_count = 0;
%let _OUTPUT1_col1_name = _run_date_yymth;
%let _OUTPUT1_col1_table = work.W1U78SU;
%let _OUTPUT1_col1_length = 6;
%let _OUTPUT1_col1_type = $;
%let _OUTPUT1_col1_format = $10.;
%let _OUTPUT1_col1_informat = $10.;
%let _OUTPUT1_col1_label = %nrquote();
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input_count = 0;
%let _OUTPUT1_col2_name = _run_date24;
%let _OUTPUT1_col2_table = work.W1U78SU;
%let _OUTPUT1_col2_length = 10;
%let _OUTPUT1_col2_type = $;
%let _OUTPUT1_col2_format = $10.;
%let _OUTPUT1_col2_informat = $10.;
%let _OUTPUT1_col2_label = %nrquote();
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input_count = 0;

/*---- Start of User Written Code  ----*/ 

/* Run date */
/*  %let _run_date = 2014-10-31; */
/*  %let _run_date_yymth = 201410;*/

%get_model_period_dates(product=mor);
%put Start and End Dates for Mortgage Models:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;

%let start_date= &start_period_dt.;
%let end_date= &end_period_dt.;
/*%let start_date= 31JUL2015;*/
/*%let end_date= 31JUL2015;*/

data &_output;
   format _run_date _run_Date24 $10.
          _run_date_yymth  $6.; 
	mths=intck('month',"&start_date"d,"&end_date"d)+1;
   do i=1 to mths; 
       if i=1 then run_date="&start_date"d;
   else run_date=intnx('month',"&start_date"d,i-1,'e');
        run_date24=intnx('month',"&start_date"d,i-25,'e');
        _run_date_yymth = put(run_date,yymmn.);
        _run_date = put(run_date,yymmdd10.);
        _run_date24 = put(run_date24,yymmdd10.);
        output;
   end;
run;
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end User Written **/

/*==========================================================================* 
 * Step:            Loop                                  A57SWEI7.BK000Z6U * 
 * Transform:       Loop                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    User Written - work.W1U78SU           A57SWEI7.BN000NLH * 
 * Target Table:    Loop - work.W1YG89U                   A57SWEI7.BN000NLI * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z6U);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.W1U78SU, DATA)) or 
         %sysfunc(exist(work.W1U78SU, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.W1U78SU out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.W1U78SU); 

/* Capture summary statistics about this step for performance reporting  */ 
%put "DIS_SUMM";
%macro etls_getHandle(statusTable=, handleVariable=, row=); 
   %let etls_dsid = %sysfunc(open(&statusTable)); 
   %if (&etls_dsid = 0) %then 
      %put %sysfunc(sysmsg()); 
   %else 
   %do; 
      %let rc = %sysfunc(fetchobs(&etls_dsid, &row)); 
      %if (&rc ne 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %let etls_varnum = %sysfunc(varnum(&etls_dsid,&handleVariable)); 
         %if (&etls_varnum > 0) %then 
            %sysfunc(getvarc(&etls_dsid,&etls_varnum)); 
         %else 
            %put %sysfunc(sysmsg()); 
      %end; 
      %let rc = %sysfunc(close(&etls_dsid)); 
   %end; 
%mend etls_getHandle; 

%macro etls_freeHandle(statusTable=, statusVariable=, handleVariable=, 
   handleName=, statusSetting="Finished", 
   endTimeVariable=endTime, startTimeVariable=startTime, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, setMainJobRC=1, 
   statusUnknownReturnCode=., startTimeMacroVariable=, endTimeMacroVariable= ); 

   %if (&statusTable ne ) %then 
   %do; 
      %local etls_rcMacroVarExisted; 
      %let etls_rcMacroVarExisted = 0; 
      %if ("&returnCodeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_rcMacroVarExisted from dictionary.macros 
            where name=upcase("&returnCodeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_rcMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Return code from inner job not found.  Setting status to Unknown.;
            %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
         %end; 
         %if (&setMainJobRC eq 1) %then 
            %rcSet(&&&returnCodeMacroVariable); 
      %end; 
      %else 
      %do; 
         %let returnCodeMacroVariable=etls_rcmacvar; 
         %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
      %end; 

      %local etls_startTimeMacroVarExisted; 
      %let etls_startTimeMacroVarExisted = 0; 
      %if ("&startTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_startTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&startTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_startTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Start time from inner job not found.  No value will be set.;
            %let &startTimeMacroVariable=; 
         %end; 
      %end; 

      %local etls_endTimeMacroVarExisted; 
      %let etls_endTimeMacroVarExisted = 0; 
      %if ("&endTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_endTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&endTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_endTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) End time from inner job not found.  Setting end time to current
      time.;
            %let &endTimeMacroVariable=%sysfunc(datetime()); 
         %end; 
      %end; 

      data &statusTable; 
         modify &statusTable(where=(&handleVariable = &handleName)); 
         %if ("&startTimeMacroVariable" ne "") %then 
         %do; 
            &startTimeVariable = input(symget("&startTimeMacroVariable"),32.);; 
         %end; 
         %if ("&endTimeVariable" ne "") %then 
         %do; 
            %if ("&endTimeMacroVariable" ne "") %then 
            %do; 
               &endTimeVariable = input(symget("&endTimeMacroVariable"),32.);; 
            %end; 
            %else 
               &endTimeVariable = datetime();; 
         %end; 
         %if ("&returnCodeVariable" ne "") %then 
            &returnCodeVariable = input(symget("&returnCodeMacroVariable"),32.);; 
         %if ("&statusVariable" ne "") %then 
         %do; 
            if (symget("etls_rcMacroVarExisted") eq "0") then 
               &statusVariable = "Unknown Status"; 
            else
               &statusVariable = &statusSetting;
         %end;
         call symput('handle',&handleVariable); 
         replace; 
         stop; 
      run; 

      %rcSet(&syserr); 

      %if (&signoff eq 1) %then 
         %etls_signoff(handleName=&handle); 
   %end; 
%mend etls_freeHandle; 

%macro etls_createHandle(statusTable=,
                         statusVariable=,
                         handleVariable=,
                         handlePrefix=rmt,
                         gridOptionSet=,
                         workloadMacroVariable=,
                         row=,
                         machineVariable=,
                         statusSetting="Running", 
                         startTimeVariable=startTime,
                         signon=1,
                         useGrid=1,
                         log=,
                         output=,
                         gridRC=,
                         cmacvar=etls_signonStatus,
                         additionalSignonOptions=,
                         signonRetries= ); 

   %local remoteSessionId; 
   %let remoteSessionId = &handlePrefix.&row; 
   %let &cmacvar = 1; 
   %local etls_machineId; 
   %if (&signon eq 1) %then 

      %etls_signon(handleName=&remoteSessionId,
                   useGrid=&useGrid,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=&etls_gridOptionSet,
                   workloadMacroVariable=&workloadMacroVariable,
                   log=&log,
                   output=&output,
                   cmacvar=&cmacvar,
                   gridRC=&gridRC,
                   additionalSignonOptions=&additionalSignonOptions,
					signonRetries=&signonRetries,
                   gridJobName=DIS_&etls_jobName._&row); 

   %else %let &cmacvar=0; 

   data &statusTable; 
      retain ptr &row; 
      modify &statusTable point = ptr; 
      &handleVariable = "&remoteSessionId"; 
      %if (&signon eq 1) %then 
         &machineVariable = "&etls_machineId";; 
      %if (&&&cmacvar ne 0) %then 
      %do; 
         &statusVariable = "Failed Signon"; 
      %end; 
      %else 
         &statusVariable = &statusSetting;; 
      %if (&startTimeVariable ne ) %then 
         &startTimeVariable = datetime();; 
      replace; 
      stop; 
   run; 

   %rcSet(&syserr); 
%mend etls_createHandle; 

%macro etls_getParameterNames(parameterTable=, parameterVariableMacro=, startingColumnNumber=1);
   %let &parameterVariableMacro = ;
   %let dsid = %sysfunc(open(&parameterTable));
   %if (&dsid gt 0) %then 
   %do; 
      %do i=&startingColumnNumber %to %sysfunc(attrn(&dsid,nvars)); 
         %let &parameterVariableMacro = &&&parameterVariableMacro %sysfunc(varname(&dsid,&i)); 
      %end; 
      %let dsid = %sysfunc(close(&dsid)); 
   %end; 
   %else 
      %put %sysfunc(sysmsg()); 
   %rcSet(&syserr); 
%mend etls_getParameterNames; 

%macro etls_getParameters(parameterTable=, row=, startingColumnNumber=1 , handleName=); 
   data _null_; 
      length vname $256 vtype $1 value $32767; 
      dsid = open("&parameterTable"); 
      if (dsid > 0) then 
      do; 
         do _i = 1 to &row; 
            fetchrc = fetch(dsid); 
         end; 
         do _i=&startingColumnNumber to attrn(dsid,'nvars'); 
            vname = varname(dsid,_i); 
            vtype = vartype(dsid,_i); 
            if (fetchrc = 0) then 
            do; 
               if (vtype = 'C') then 
               do; 
                  value = getvarc(dsid,_i); 
                  value = tranwrd(value,"%","%%"); 
                  value = tranwrd(value,"(","%("); 
                  value = tranwrd(value,")","%)"); 
                  value = tranwrd(value,'"','%"'); 
                  value = tranwrd(value,"'","%'"); 
               end; 
               else 
                  value = left(put(getvarn(dsid,_i),best32.)); 
            end; /* fetchrc = 0 */ 
            
            put ;
            if indexc(trimn(value),"+-*/<>=^~;, '()&%",'"')>0 then 
            do; 
               value='%nrstr('||trim(value)||')'; 
               put "ETLS_DIAG%QUOTE(:) Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
               put "NOTE: Special characters encountered; References may require: %nrbquote(%)UNQUOTE(&" vname+(-1)').';
            end; 
            %if %str(&handlename) ne %str() %then 
            %do; 
               value = '%syslput '||trim(vname)||'= '||trim(value)||" / remote = &handleName;"; 
            %end; 
            %else 
            %do; 
               value = '%let '||trim(vname)||'= '||trim(value)||';'; 
            %end; 
            
            put "NOTE: Setting macro variable " vname "with statement:" value ;
            call execute(value); 
         end; /* do i= */ 
         dsid = close(dsid); 
      end; /* dsid > 0 */ 
      else 
      do; 
         put "ERROR%QUOTE(:) Parameter table, &parameterTable., could not be"
              " opened.";
         abort; 
      end; 
      stop; 
   run; 
   
   %rcSet(&syserr); 
%mend etls_getParameters; 

%macro etls_loopW2HFLPP; 
   %local etls_filePrefix; 
   %let etls_filePrefix = ; 
   
   %macro etls_processToLoopW2HFLPZ(parameterTable=, row=, handleName=rmt);
      %local etls_parmvars; 
      %etls_getParameterNames(parameterTable=&parameterTable, 
         parameterVariableMacro=etls_parmvars, 
         startingColumnNumber=1); 
      %local &etls_parmvars; 
      %etls_getParameters(parameterTable=&parameterTable, row=&row, 
         startingColumnNumber=1); 
      %let etls_previousFilePrefix = &etls_filePrefix;
      %local etls_filePrefix; 
      %let etls_filePrefix = &etls_previousFilePrefix.&handleName; 
      %macro etls_jobW2HFLQ9; 
      
         /**************************************************************************** 
          * Job:             RRAP_MOR_MODEL_57_DEFAULT_MONTHS      A57SWEI7.BH0009JD * 
          * Description:                                                             * 
          *                                                                          * 
          * Metadata Server: 10.56.70.48                                             * 
          * Port:            8561                                                    * 
          * Location:        /Projects/RRAP/Jobs/04 - Mortgage/BNS/Inner Jobs        * 
          *                                                                          * 
          * Server:          SASApp                                A57SWEI7.AT000002 * 
          *                                                                          * 
          * Generated on:    Thursday, June 29, 2017 2:43:02 PM EDT                  * 
          * Generated by:    owprdsas                                                * 
          * Version:         SAS Data Integration Studio 4.8                         * 
          ****************************************************************************/ 
         
         /* Generate the process id for job  */ 
         %put Process ID: &SYSJOBID;
         
         /* General macro variables  */ 
         %let jobID = %quote(A57SWEI7.BH0009JD);
         %let etls_jobName = %nrquote(RRAP_MOR_MODEL_57_DEFAULT_MONTHS);
         %let etls_userID = %nrquote(owprdsas);
         
         
         /* Create metadata macro variables */
         %let IOMServer      = %nrquote(SASApp);
         %let metaPort       = %nrquote(8561);
         %let metaServer     = %nrquote(iw503);
         
         /* Set metadata options */
         options metaport       = &metaPort 
                 metaserver     = "&metaServer"; 
         
         /* Setup for capturing job status  */ 
         %let etls_startTime = %sysfunc(datetime(),datetime.);
         %let etls_recordsBefore = 0;
         %let etls_recordsAfter = 0;
         %let etls_lib = 0;
         %let etls_table = 0;
         
         %global etls_debug; 
         %macro etls_setDebug; 
            %if %str(&etls_debug) ne 0 %then 
               OPTIONS MPRINT%str(;); 
         %mend; 
         %etls_setDebug; 
         
         /*==========================================================================* 
          * Step:            User Written                          A57SWEI7.BK000Z3S * 
          * Transform:       User Written                                            * 
          * Description:                                                             * 
          *                                                                          * 
          * Target Table:    User Written - work.W1QUR21           A57SWEI7.BN000NQ3 * 
          *                                                                          * 
          * User Written:    SourceCode                                              * 
          *==========================================================================*/ 
         
         %let transformID = %quote(A57SWEI7.BK000Z3S);
         %let trans_rc = 0;
         %let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 
         
         %let _INPUT_count = 0;
         %let _OUTPUT_count = 1;
         %let _OUTPUT = work.W1QUR21;
         %let _OUTPUT_connect = ;
         %let _OUTPUT_engine = ;
         %let _OUTPUT_memtype = DATA;
         %let _OUTPUT_options = %nrquote();
         %let _OUTPUT_alter = %nrquote();
         %let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NQ3%(WorkTable%));
         %let _OUTPUT_type = 1;
         %let _OUTPUT_label = %nrquote();
         %let _OUTPUT_col_count = 0;
         
         %let _OUTPUT1 = work.W1QUR21;
         %let _OUTPUT1_connect = ;
         %let _OUTPUT1_engine = ;
         %let _OUTPUT1_memtype = DATA;
         %let _OUTPUT1_options = %nrquote();
         %let _OUTPUT1_alter = %nrquote();
         %let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NQ3%(WorkTable%));
         %let _OUTPUT1_type = 1;
         %let _OUTPUT1_label = %nrquote();
         %let _OUTPUT1_col_count = 0;
         
         /*---- Start of User Written Code  ----*/ 
         
         /*%let _run_date = 2011-10-31;*/
         /*%let _run_date24 = 2009-09-30;*/
         /*%let _run_date_yymm =201110;*/
         
         
          %delete_table(nzuser.bns_accts_in_def_&_run_date_yymm);
          %delete_table(nzuser.bns_for_month_def_&_run_date_yymm);
         
         proc sql noprint;
            connect USING NZUSER as nzcon ;
          /*     execute (drop table &target_lib3...bns_accts_in_def_&_run_date_yymm) by nzcon;  */
          /*     execute (drop table &target_lib3...bns_for_month_def_&_run_date_yymm) by nzcon; */
            execute (
               create table &target_lib3..bns_accts_in_def_&_run_date_yymm as (
               select a.mortgage_no, a.pit_stat_cd, a.process_date
               from &target_lib3..base_bns_mor_rpt_tbl as a
               where upper(a.pit_stat_cd) = 'DEF' and last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&_run_date'))
				) WITH DATA 
               /*distribute on (mortgage_no)) by nzcon; */
				 distribute BY (mortgage_no)) by nzcon; 
         
            execute (
               create table &target_lib3..bns_for_month_def_&_run_date_yymm as (
               select a.mortgage_no,
                      a.pit_stat_cd,
                      a.process_date,
                      (case 
                        when upper(a.pit_stat_cd) = 'DEF' and last_day(date_trunc('day', a.process_date)) = date(%nrbquote('&_run_date')) then 0
                        when upper(a.pit_stat_cd) = 'DEF' and last_day(date_trunc('day', a.process_date)) < date(%nrbquote('&_run_date')) then 1
                        else 0
                        end) as def_counter
               from &target_lib3..base_bns_mor_rpt_tbl as a
                    inner join 
                    &target_lib3..bns_accts_in_def_&_run_date_yymm as b
                    on cast(a.mortgage_no as integer) = cast(b.mortgage_no as integer)
               where last_day(date_trunc('day', a.process_date)) <= date(%nrbquote('&_run_date')) and
                     last_day(date_trunc('day', a.process_date)) >= date(%nrbquote('&_run_date24'))
               order by a.mortgage_no, a.process_date desc 
			   ) WITH DATA
         /*   distribute on (mortgage_no)) by nzcon;  */
            distribute BY (mortgage_no)  ) by nzcon;

            disconnect from nzcon;
         quit;
         /*---- End of User Written Code  ----*/ 
         
         %rcSet(&syserr); 
         %rcSet(&sqlrc); 
         %rcSet(&syscc); 
         
         
         
         /**  Step end User Written **/
         
         %let etls_endTime = %sysfunc(datetime(),datetime.);
         
         
         
         /**  Job end RRAP_MOR_MODEL_57_DEFAULT_MONTHS **/
         
         /* Reset jobid and name */
         %let jobID = %quote(A57SWEI7.BH0009KA);
         %let etls_jobName = %nrquote(RRAP_MOR_MODEL_57_DEFAULT_MONTHS_G);
         
      %mend etls_jobW2HFLQ9; 
      
      %etls_jobW2HFLQ9; 
      
      %let handleName = %etls_getHandle(statusTable=&etls_statusTable,
         handleVariable=etls_handleName, row=&&&etls_controlName);
         
      %let job_rc&handleName. = &job_rc; 
      
      %etls_freeHandle(statusTable=&etls_statusTable, statusVariable=etls_status, 
         handleVariable=etls_handleName, handleName="&handleName", 
         startTimeVariable=etls_startTime, endTimeVariable=etls_endTime, signoff=0, 
         returnCodeVariable=etls_jobRC, returnCodeMacroVariable=job_rc&handleName., setMainJobRc=1); 
         
   %mend etls_processToLoopW2HFLPZ;
   
   %local etls_controlTable etls_statusTable etls_controlName 
      etls_processesRunning etls_maxProcesses etls_parameterTable 
      etls_additionalSignonOptions etls_signonRetries;
   %let etls_controlName = L29_; 
   %let etls_statusTable = work.W1YG89U; 
   %let etls_parameterTable = work.W2HFLQJ; 
   %let &etls_controlName = 0;
   %let etls_controlTable = work.W1U78SU;
   
   %put %str(NOTE: Creating status table...);
   data &etls_statusTable 
      (keep = etls_handleName etls_machineId etls_startTime etls_endTime etls_status 
              etls_jobRC _run_date _run_date_yymth _run_date24
      );
      attrib etls_handleName length = $32
         label = 'Name of handle to remote session'; 
      attrib etls_machineId length = $32
         label = 'Name of machine executing the task'; 
      attrib etls_startTime length = 8
         format = nldatmap.
         label = 'Start time of task'; 
      attrib etls_endTime length = 8
         format = nldatmap.
         label = 'End time of task'; 
      attrib etls_status length = $32
         label = 'Current status of task'; 
      attrib etls_jobRC length = 8
         label = 'Return code of task'; 
      attrib _run_date length = $10
         format = $10.
         informat = $10.; 
      attrib _run_date_yymth length = $6
         format = $10.
         informat = $10.; 
      attrib _run_date24 length = $10
         format = $10.
         informat = $10.; 
      set &etls_controlTable;
   run;
   
   %rcSet(&syserr); 
   
   %put %str(NOTE: Creating parameter table...);
   proc sql; 
      create table &etls_parameterTable as 
         select _run_date as _run_date, 
                _run_date24 as _run_date24, 
                _run_date_yymth as _run_date_yymm 
         from &etls_controlTable; 
   quit; 
   
   %rcSet(&sqlrc); 
   
   /* Get the number of times to iterate from the number of rows in the source  */ 
   /*  table                                                                    */ 
   proc sql noprint; 
      select count(*) into :&etls_controlName._max from &etls_statusTable;
      %let &etls_controlName._max = &&&etls_controlName._max;
   quit;
   
   %rcSet(&sqlrc); 
   
   %let etls_maxProcesses = 1; 
   
   %if (&etls_maxProcesses > 0) %then 
   %do; 
      %do %until (&&&etls_controlName ge &&&etls_controlName._max); 
      
         %let etls_lastLoopPtr = &&&etls_controlName;
         
         %let etls_processesRunning = 0; 
         
         %do %while(&etls_processesRunning lt &&&etls_controlName._max 
            and &etls_processesRunning lt &etls_maxProcesses 
            and &&&etls_controlName lt &&&etls_controlName._max);
            
            %let &etls_controlName = %eval(&&&etls_controlName+1);
            
            %let job_rcLast=&job_rc; 
            
            %etls_createHandle(statusTable=&etls_statusTable,
                               statusVariable=etls_status,
                               handleVariable=etls_handleName,
                               handlePrefix=&etls_controlName,
                               statusSetting="Running",
                               row=&&&etls_controlName,
                               machineVariable=etls_machineId,
                               startTimeVariable=etls_startTime,
                               signon=0,
                               useGrid=0);
            
         %let etls_processesRunning = 1; 
         %etls_processToLoopW2HFLPZ(parameterTable=&etls_parameterTable, row=&&&etls_controlName,
            handleName=%etls_getHandle(statusTable=&etls_statusTable,
            handleVariable=etls_handleName, row=&&&etls_controlName)); 
         
         /* Reset main Job_RC and Trans_RC to max return code of all iterations */ 
         %let job_rcThisIter=&job_rc; 
         %let job_rc=&job_rcLast; 
         %let trans_rc=&job_rcLast; 
         %rcSet(&job_rcThisIter); 
      %end; 
      
   %end; 
   
%end;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W2HFLQJ;
quit;

%mend etls_loopW2HFLPP; 

%etls_loopW2HFLPP; 

%rcSet(&syscc); 



/**  Step end Loop **/

/*==========================================================================* 
 * Step:            Loop End                              A57SWEI7.BK000Z6W * 
 * Transform:       Loop End                                                * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z6W);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%rcSet(&syscc); 



/**  Step end Loop End **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

