%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

%MACRO ARCHIVE;

%PUT MTH_TM_ID IS &MTH_TM_ID;
PROC SQL NOPRINT;
SELECT TRIM(MTH_CLNDR_CD) INTO :CAL_MONTH FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID;
QUIT;

%PUT CALENDAR MONTH IS &CAL_MONTH;

%IF (&CAL_MONTH^=January AND &CAL_MONTH^=April AND &CAL_MONTH^=July AND &CAL_MONTH^=October) %THEN %DO;
%PUT I AM MONTH END AND MONTHLY REPORTS ARE ARCHIVED IN MONTHLY SCHEDULE;
/*ARCHIVE OLDER REPORTS*/
X mkdir &OUTPATH/rk/outgoing/history/&YEARMONTH;
X mv &OUTPATH/rk/outgoing/AE_BD*.* &OUTPATH/rk/outgoing/history/&YEARMONTH;
X mv &OUTPATH/rk/outgoing/AE_BE*.* &OUTPATH/rk/outgoing/history/&YEARMONTH;
%END;
%IF (&CAL_MONTH=January OR &CAL_MONTH=April OR &CAL_MONTH=July OR &CAL_MONTH=October) %THEN %DO;
%PUT I AM QUARTER END AND QUARTERLY REPORTS WILL BE ARCHIVED IN QUARTERLY SCHEDULE ONCE COMPLETE;
/*ARCHIVE OLDER REPORTS*/
/*X mkdir &OUTPATH/rk/outgoing/history/&YEARMONTH;*/
/*X mv &OUTPATH/rk/outgoing/AE_BD*.* &OUTPATH/rk/outgoing/history/&YEARMONTH;*/
/*X mv &OUTPATH/rk/outgoing/AE_BE*.* &OUTPATH/rk/outgoing/history/&YEARMONTH;*/
%END;
%MEND;

%ARCHIVE;
