/**************************************************************************** 
 * Job:             RRAP_TNG_10_DATA_TRANSFER             A57SWEI7.BH0009M7 * 
 * Description:     This job will create a new SAS dataset                  * 
 *                  BASEL_ANALY_BL_INSTR_FCT_&YR_MTH. everytime it is       * 
 *                  run.It is coded so that it will automatically select    * 
 *                   the previous month's data using the system date.       * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/04 - Mortgage/TNG                   * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Source Tables:   BASEL_ANALYTCL_BL_INSTRMNT_FACT -     A57SWEI7.BE00044F * 
 *                  DB2RRAP.BASEL_ANALYTCL_BL_INSTRMNT_                     * 
 *                  FACT                                                    * 
 *                  BASEL_ANALY_BL_INSTR_FCT_&MTH_YR -    A57SWEI7.BE00044K * 
 *                   RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR                   * 
 * Target Table:    BASEL_ANALY_BL_INSTR_FCT_&MTH_YR -    A57SWEI7.BE00044K * 
 *                   RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR                   * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:45:24 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009M7);
%let etls_jobName = %nrquote(RRAP_TNG_10_DATA_TRANSFER);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

%macro genSASCommand; 
   %local noobjserver; 
   %if "&sysscp"="OS" %then %let noobjserver=; 
   %else %if "&sysscp"="VMS_AXP" %then %let noobjserver=%quote(/noobjectserver); 
   %else %let noobjserver=%quote(-noobjectserver); 
   options sascmd = "!sascmd &noobjserver"; 
%mend genSASCommand; 
%genSASCommand; 

%macro etls_tsLevel(macroName=, featureName=); 
   data _null_; 
      call symput("&macroName",tslvl("&featureName")); 
   run; 
%mend etls_tsLevel; 

%macro etls_signon(handleName=etlsRemote,
                   cmacvar=etls_signonStatus,
                   gridRC=rc,
                   useGrid=1,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=,
                   workloadMacroVariable=,
                   log=,
                   output=,
                   additionalSignonOptions=,
                   signonRetries=3,
                   gridJobName=&&etls_jobName&row);

   %let etls_gridInstalled =;
   %etls_tsLevel(macroName=etls_gridInstalled, featureName=uwugrdsv); 

   %if (&useGrid = 1) %then 
   %do; 

      %if ("&etls_gridInstalled" ne "") %then 
      %do; 
         %if (&gridRC eq ) %then 
            %let gridRC = &handleName.RC ; 

         %global &gridRC;
         %let workload = ; 
         %if (&workloadMacroVariable ne %str()) %then 
         %do; 
            data _null_;
               call symput('workload','; workload = '||symget("&workloadMacroVariable"));
            run;
         %end; 
         %let gridoptset = ;
         %if (&gridOptionSet ne %str()) %then 
         %do; 
            data _null_;
               call symput('gridoptset',"; gridoptset = &gridOptionSet");
            run;
         %end; 
         %let gridJobOpts = ;
         %let gridSuppOpts = ;
         %if (&etls_gridSuppJobOptions ne %str()) %then 
         %do; 
            data _null_;
               call symput('gridJobOpts', "&etls_gridSuppJobOptions");
            run;
            data _null_;
               call symput('gridSuppOpts', '; JOBOPTS=gridJobOpts');
            run;
         %end; 
            data _null_;
               call symput('gridJbName', "; jobname = gridJobName");
            run;
         %let &gridRC = %sysfunc(grdsvc_enable("&handleName", server = SASApp &gridoptset &workload &gridSuppOpts &gridJbName));
      %end; 
      %else 
         %put %str(NOTE: Grid service functions are not installed.);
   %end; 

   %local sleeptime sleepIncreaseAmount tryCount; 
   %let sleepIncreaseAmount=5; 
   %let sleeptime=5; 
   %let tryCount=1; 
   %let &cmacvar=1; 

   /* Store original return code values to reset them if a signon succeeds  */ 
   %local etls_sysrc etls_syscc;
   %let etls_sysrc = &sysrc;
   %let etls_syscc = &syscc;

   %do %until((&&&cmacvar ne 1) or (&tryCount gt %eval(&signonRetries+1))); 
      data _null_; 
      signon &handleName cmacvar=&cmacvar 
         %if ("&log" ne "") %then 
            log=&log; 
         %if ("&output" ne "") %then 
            output=&output; 
         %if ("&additionalSignonOptions" ne "") %then 
            &additionalSignonOptions; 
      ;run; 

      %if "&&&cmacvar" eq "1" %then 
      %do; 
         %if &tryCount lt %eval(&signonRetries+1) %then 
         %do; 
            %put NOTE: Signon attempt #&tryCount failed. Retrying in &sleeptime seconds.;
            %let rc=%sysfunc(sleep(&sleeptime,1)); 
         %end; 
         %else %if &signonRetries gt 0 %then 
            %put ERROR%QUOTE(:) Final signon attempt, #&tryCount, failed.;

         %let sleeptime=%sysevalf(&sleeptime+&sleepIncreaseAmount,int); /* increase sleeptime by factor */ 
         %let tryCount=%eval(&tryCount+1); 
      %end; 
      %else
      %do;
         /* Signon succeeded make sure return codes are reset to original values  */ 
         %let sysrc = &etls_sysrc;
         %let syscc = &etls_syscc;
      %end;
   %end; 
   %rcSet(&syserr); 

   /* On successful signon, fetch and report machine name if grid was requested. */ 
   %if ("&machineIdMacroVariable" ne "") %then %let &machineIdMacroVariable = ; 
   %if ("&&&cmacvar" ne "1" and "&machineIdMacroVariable" ne "" and 
        &useGrid = 1 and "&etls_gridInstalled" ne "") %then 
   %do; 
      %put; 
      %if ("&&&gridRC" eq "0") %then 
      %do; 
         %let &machineIdmacroVariable = %sysfunc(grdsvc_getname(&handleName)); 
         %put %str(NOTE: Signed on to grid machine &&&machineIdmacroVariable..);
      %end; 
      %else 
         %put %str(NOTE: GRID SERVICES WERE NOT ENABLED.  Signed on to LOCAL machine.);
      %put; 
   %end; 

%mend etls_signon; 

%macro etls_serverConnected(serverId=,macvarname=isConnected); 
   %let &macvarname=0; 
   %local search_str none_str savenotes; 

   /* setup information for listtask output */ 
   /* listtask output on OS/390 differs */ 
   %if %bquote(&sysscp) eq OS %then 
   %do; 
      %let search_str=Remote submit for; 
      %let token=5; 
   %end; 
   %else  
   %do; 
      %let search_str=--------------; 
      %let token=1; 
   %end; 

   /* Issue listtask within PROC PRINTTO - send output to file */ 
   filename __tmptxt TEMP; 
   %let savenotes=%sysfunc(getoption(notes)); 
   options nonotes; 

   proc printto log=__tmptxt new; 
   run; 

   options notes; 
   listtask; 
   proc printto; 
   run; 

   options nonotes; 

   /* read in the output from listtask */ 
   %let dsname=_null_; 
   data _null_(keep=Session); 
      length line $256 sessionId $60; 
      infile __tmptxt length=len; 
      input @1 line $varying. len; 

      if line=:'There are no' then 
         stop; 
      /* look for the search string and scan for server name */ 
      if index(line,"&search_str") then  
      do; 
         sessionId=scan(line,&token," "); 
         sessionId=upcase(trim(left(tranwrd(sessionId,'"',' ')))); 
         if sessionId=upcase(symget("serverId")) then 
         do;  
            call symput("&macvarname","1"); 
            stop; 
         end; 
      end; 
   run; 
   filename __tmptxt clear; 
   options &savenotes; 
%mend etls_serverConnected; 

%macro etls_signoff(handleName=rmt); 
   %local savemprint; 
   %let savemprint=%sysfunc(getoption(mprint)); 
   %put %str(NOTE: Testing connection with etls_serverConnected macro %(mprint off%).);
   options nomprint; 
   %local isConnected; 
   %etls_serverConnected(serverId=&handleName); 
   options &savemprint; 
   %if &isConnected %then 
      signoff &handleName ;; 
%mend etls_signoff; 

%macro etls_getHandle(statusTable=, handleVariable=, row=); 
   %let etls_dsid = %sysfunc(open(&statusTable)); 
   %if (&etls_dsid = 0) %then 
      %put %sysfunc(sysmsg()); 
   %else 
   %do; 
      %let rc = %sysfunc(fetchobs(&etls_dsid, &row)); 
      %if (&rc ne 0) %then 
         %put %sysfunc(sysmsg()); 
      %else 
      %do; 
         %let etls_varnum = %sysfunc(varnum(&etls_dsid,&handleVariable)); 
         %if (&etls_varnum > 0) %then 
            %sysfunc(getvarc(&etls_dsid,&etls_varnum)); 
         %else 
            %put %sysfunc(sysmsg()); 
      %end; 
      %let rc = %sysfunc(close(&etls_dsid)); 
   %end; 
%mend etls_getHandle; 

%macro etls_freeHandle(statusTable=, statusVariable=, handleVariable=, 
   handleName=, statusSetting="Finished", 
   endTimeVariable=endTime, startTimeVariable=startTime, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, setMainJobRC=1, 
   statusUnknownReturnCode=., startTimeMacroVariable=, endTimeMacroVariable= ); 

   %if (&statusTable ne ) %then 
   %do; 
      %local etls_rcMacroVarExisted; 
      %let etls_rcMacroVarExisted = 0; 
      %if ("&returnCodeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_rcMacroVarExisted from dictionary.macros 
            where name=upcase("&returnCodeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_rcMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Return code from inner job not found.  Setting status to Unknown.;
            %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
         %end; 
         %if (&setMainJobRC eq 1) %then 
            %rcSet(&&&returnCodeMacroVariable); 
      %end; 
      %else 
      %do; 
         %let returnCodeMacroVariable=etls_rcmacvar; 
         %let &returnCodeMacroVariable=&statusUnknownReturnCode; 
      %end; 

      %local etls_startTimeMacroVarExisted; 
      %let etls_startTimeMacroVarExisted = 0; 
      %if ("&startTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_startTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&startTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_startTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) Start time from inner job not found.  No value will be set.;
            %let &startTimeMacroVariable=; 
         %end; 
      %end; 

      %local etls_endTimeMacroVarExisted; 
      %let etls_endTimeMacroVarExisted = 0; 
      %if ("&endTimeMacroVariable" ne "") %then 
      %do; 
         proc sql noprint; 
            select '1' into: etls_endTimeMacroVarExisted from dictionary.macros 
            where name=upcase("&endTimeMacroVariable"); 
         quit; 

         %rcSet(&sqlrc); 
         %if (&etls_endTimeMacroVarExisted = 0) %then 
         %do; 
            %put WARNING%QUOTE(:) End time from inner job not found.  Setting end time to current
      time.;
            %let &endTimeMacroVariable=%sysfunc(datetime()); 
         %end; 
      %end; 

      data &statusTable; 
         modify &statusTable(where=(&handleVariable = &handleName)); 
         %if ("&startTimeMacroVariable" ne "") %then 
         %do; 
            &startTimeVariable = input(symget("&startTimeMacroVariable"),32.);; 
         %end; 
         %if ("&endTimeVariable" ne "") %then 
         %do; 
            %if ("&endTimeMacroVariable" ne "") %then 
            %do; 
               &endTimeVariable = input(symget("&endTimeMacroVariable"),32.);; 
            %end; 
            %else 
               &endTimeVariable = datetime();; 
         %end; 
         %if ("&returnCodeVariable" ne "") %then 
            &returnCodeVariable = input(symget("&returnCodeMacroVariable"),32.);; 
         %if ("&statusVariable" ne "") %then 
         %do; 
            if (symget("etls_rcMacroVarExisted") eq "0") then 
               &statusVariable = "Unknown Status"; 
            else
               &statusVariable = &statusSetting;
         %end;
         call symput('handle',&handleVariable); 
         replace; 
         stop; 
      run; 

      %rcSet(&syserr); 

      %if (&signoff eq 1) %then 
         %etls_signoff(handleName=&handle); 
   %end; 
%mend etls_freeHandle; 

%macro etls_createHandle(statusTable=,
                         statusVariable=,
                         handleVariable=,
                         handlePrefix=rmt,
                         gridOptionSet=,
                         workloadMacroVariable=,
                         row=,
                         machineVariable=,
                         statusSetting="Running", 
                         startTimeVariable=startTime,
                         signon=1,
                         useGrid=1,
                         log=,
                         output=,
                         gridRC=,
                         cmacvar=etls_signonStatus,
                         additionalSignonOptions=,
                         signonRetries= ); 

   %local remoteSessionId; 
   %let remoteSessionId = &handlePrefix.&row; 
   %let &cmacvar = 1; 
   %local etls_machineId; 
   %if (&signon eq 1) %then 

      %etls_signon(handleName=&remoteSessionId,
                   useGrid=&useGrid,
                   machineIdMacroVariable=etls_machineId,
                   gridOptionSet=&etls_gridOptionSet,
                   workloadMacroVariable=&workloadMacroVariable,
                   log=&log,
                   output=&output,
                   cmacvar=&cmacvar,
                   gridRC=&gridRC,
                   additionalSignonOptions=&additionalSignonOptions,
					signonRetries=&signonRetries,
                   gridJobName=DIS_&etls_jobName._&row); 

   %else %let &cmacvar=0; 

   data &statusTable; 
      retain ptr &row; 
      modify &statusTable point = ptr; 
      &handleVariable = "&remoteSessionId"; 
      %if (&signon eq 1) %then 
         &machineVariable = "&etls_machineId";; 
      %if (&&&cmacvar ne 0) %then 
      %do; 
         &statusVariable = "Failed Signon"; 
      %end; 
      %else 
         &statusVariable = &statusSetting;; 
      %if (&startTimeVariable ne ) %then 
         &startTimeVariable = datetime();; 
      replace; 
      stop; 
   run; 

   %rcSet(&syserr); 
%mend etls_createHandle; 

%macro etls_waitfor(statusTable=, statusVariable=, runningStatusSetting="Running", handleVariable=, 
   completeStatusSetting="Finished", endTimeVariable=endTime, 
   startTimeVariable=startTime, waitType=_ANY_, signoff=1, 
   returnCodeVariable=, returnCodeMacroVariable=, statusUnknownReturnCode=.); 

   proc sql noprint; 
      select count(*) into :etls_rows 
         from &statusTable where &statusVariable = &runningStatusSetting; 
      %let etls_rows = &etls_rows; 
      %if (&etls_rows gt 0) %then 
      %do; 
         select &handleVariable into :etlsHandles1 - :etlsHandles&etls_rows 
            from &statusTable where &statusVariable = &runningStatusSetting; 
      %end; 
   quit; 

   %rcSet(&sqlrc); 

   %if (&etls_rows gt 0) %then 
   %do; 
      waitfor &waitType 
         %do i=1 %to &etls_rows; 
            &&etlsHandles&i 
         %end; 
      ; 
   %end; 

   %local useDefaultRCMacVar; 
   %if ("&returnCodeMacroVariable" eq "") %then 
      %let useDefaultRCMacVar=Y; 

   %do i=1 %to &etls_rows; 

      %if ("&useDefaultRCMacVar"="Y") %then 
         %let returnCodeMacroVariable=job_rc&&etlsHandles&i; 

      waitfor &&etlsHandles&i timeout=1; 
      %if (&SYSRC eq 0) or (&SYSRC eq -2) %then /* process complete  */ 
      %do; 
         %etls_freeHandle(statusTable=&statusTable, statusVariable=&statusVariable,
            handleVariable=&handleVariable, handleName="&&etlsHandles&i", 
            statusSetting=&completeStatusSetting, endTimeVariable=&endTimeVariable, 
            startTimeVariable=&startTimeVariable, signoff=&signoff, 
            returnCodeVariable=&returnCodeVariable, returnCodeMacroVariable=&returnCodeMacroVariable, 
            statusUnknownReturnCode=&statusUnknownReturnCode, 
            startTimeMacroVariable=etls_startTime_&&etlsHandles&i., 
            endTimeMacroVariable=etls_endTime_&&etlsHandles&i. ); 
         %put NOTE: Process &&etlsHandles&i. has completed.;
      %end; 
      %else %if (&SYSRC ne -1) %then /* process status unknown  */ 
      %do; 
         %etls_freeHandle(statusTable=&statusTable, statusVariable=&statusVariable,
            handleVariable=&handleVariable, handleName="&&etlsHandles&i", 
            statusSetting="Unknown Status", endTimeVariable=&endTimeVariable, 
            startTimeVariable=&startTimeVariable, signoff=&signoff, 
            returnCodeVariable=&returnCodeVariable, returnCodeMacroVariable=&returnCodeMacroVariable, 
            statusUnknownReturnCode=&statusUnknownReturnCode, startTimeMacroVariable=etls_startTime_&&etlsHandles&i ); 
         %put NOTE: Cannot retrieve status from process &&etlsHandles&i..;
      %end; 
   %end; 
%mend etls_waitfor; 

%macro etls_getProcessesRunning(statusTable=, statusVariable=, processCountMacro=, 
   statusSetting="Running"); 

   proc sql noprint; 
      select count(*) into: &processCountMacro 
         from &statusTable where &statusVariable = &statusSetting; 
   quit; 

   %rcSet(&sqlrc); 
%mend etls_getProcessesRunning; 

/*==========================================================================* 
 * Step:            AM_rrap_mor_tng_autoexec              A57SWEI7.BK000ZD8 * 
 * Transform:       AM_rrap_mor_tng_autoexec                                * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZD8);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_tng_autoexec;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mor_tng_autoexec **/

/*==========================================================================* 
 * Step:            Execute                               A57SWEI7.BK000ZD9 * 
 * Transform:       Execute                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZD9);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 0;
/*---- Start of User Written Code  ----*/ 

%get_model_period_dates(product=mor);
%put Start and End Dates for Mortgage Models:;
%put start_period_dt: &start_period_dt ;
%put end_period_dt: &end_period_dt;

proc sql;
	select TM_ID , put(tm_lvl_end_Dt,monyy7.) as mth_yr into :mth_tm_id, :MTH_YR 
	from 
	db2_tmdm.TM_DIM
	where tm_lvl='Month' and tm_lvl_end_dt between "&end_period_dt"d and "&end_period_dt"d
	order by 1;
quit;
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end Execute **/

/*==========================================================================* 
 * Step:            Select Columns and Filter Criteria    A57SWEI7.BK000ZDA * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    BASEL_ANALYTCL_BL_INSTRMNT_FACT -     A57SWEI7.BE00044F * 
 *                  DB2RRAP.BASEL_ANALYTCL_BL_INSTRMNT_                     * 
 *                  FACT                                                    * 
 * Target Table:    Join - work.W1B3J8OF                  A57SWEI7.BN000NMU * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZDA);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recnt = 0;
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(DB2RRAP.BASEL_ANALYTCL_BL_INSTRMNT_FACT, DATA)) or 
         %sysfunc(exist(DB2RRAP.BASEL_ANALYTCL_BL_INSTRMNT_FACT, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      proc sql noprint;
         select count(*) into :etls_recnt from DB2RRAP.BASEL_ANALYTCL_BL_INSTRMNT_FACT;
      quit;
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(DB2RRAP.BASEL_ANALYTCL_BL_INSTRMNT_FACT); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W1B3J8OF;
quit;

proc sql;
   create table work.W1B3J8OF as
   select
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.MTH_TM_ID length = 8   
         format = 11.
         informat = 11.
         label = 'MTH_TM_ID',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.UNQ_ACCT_ID length = 30   
         format = $30.
         informat = $30.
         label = 'UNQ_ACCT_ID',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PIT_STAT_CD length = 10   
         format = $10.
         informat = $10.
         label = 'PIT_STAT_CD',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.OS_BAL_AMT length = 8   
         format = 19.3
         informat = 19.3
         label = 'OS_BAL_AMT',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_BASEL_SEG_NUM length = 8   
         format = 11.
         informat = 11.
         label = 'PD_BASEL_SEG_NUM',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_MODEL_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_MODEL_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_LR_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_LR_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_LR_PV_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_LR_PV_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_LR_PV_AD_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_LR_PV_AD_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_LD_PV_AD_SV_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_LD_PV_AD_SV_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_FINAL_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_FINAL_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_BASEL_SEG_NUM length = 8   
         format = 11.
         informat = 11.
         label = 'LGD_BASEL_SEG_NUM',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_MODEL_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_MODEL_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_LR_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_LR_PV_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_PV_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_LR_PV_AD_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_PV_AD_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_LD_PV_AD_SV_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_LD_PV_AD_SV_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_LD_PV_AD_SV_DT_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_LD_PV_AD_SV_DT_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_FINAL_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_FINAL_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.CCAR_EXPSR_CL_NM length = 20   
         format = $20.
         informat = $20.
         label = 'CCAR_EXPSR_CL_NM',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.MORT_NUM length = 50   
         format = $50.
         informat = $50.
         label = 'MORT_NUM',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.BASEL_CIF_KEY length = 17   
         format = $17.
         informat = $17.
         label = 'BASEL_CIF_KEY',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_UNADJUSTED_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_UNADJUSTED_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_UNADJUSTED_RPTG_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_UNADJUSTED_RPTG_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.PD_LR_PV_AD_SV_DT_AA_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'PD_LR_PV_AD_SV_DT_AA_RTO',
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.LGD_LR_PV_AD_SV_DT_AA_RTO length = 8   
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_PV_AD_SV_DT_AA_RTO'
   from
      DB2RRAP.BASEL_ANALYTCL_BL_INSTRMNT_FACT as BASEL_ANALYTCL_BL_INSTRMNT_FACT
   where
      BASEL_ANALYTCL_BL_INSTRMNT_FACT.MTH_TM_ID = &mth_tm_id
      and BASEL_ANALYTCL_BL_INSTRMNT_FACT.SRC_SYS_CD = 'TNG-MOR'
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end Select Columns and Filter Criteria **/

/*==========================================================================* 
 * Step:            Table Loader                          A57SWEI7.BK000ZDB * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W1B3J8OF                  A57SWEI7.BN000NMU * 
 * Target Table:    BASEL_ANALY_BL_INSTR_FCT_&MTH_YR -    A57SWEI7.BE00044K * 
 *                   RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR                   * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZDB);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for RRAP  */ 

%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(work.W1B3J8OF); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: Replace - EntireTable
   Constraint and index action selections: 'ASIS','ASIS','ASIS','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR, DATA)) or 
         %sysfunc(exist(RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR, VIEW))); 
   
   %if &etls_tableExist %then 
   %do;/* table exists  */ 
      %let etls_hasPreExistingConstraint=0; 
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_commands etls_commands_F;
      quit;
      
      %let etls_otherTablesReferToThisTable=0;
      
      %macro etls_CIContents(table=,workTableOut=,inDSOptions=);
         %put NOTE: Building table listing Constraints and Indexes for: &table;
         proc datasets lib=work nolist; delete &workTableOut; quit;
         proc contents data=&table&inDSOptions out2=&workTableOut noprint; run;
         
         data &workTableOut;
            length name $60 type $20 icown idxUnique idxNoMiss $3 recreate $600;
            set &workTableOut;
            type=upcase(type);
            if type eq 'REFERENTIAL' then
            do;
               put "WARNING%QUOTE(:) Target table is referenced by constraints in"
                    " another table: " ref;
               call symput('etls_otherTablesReferToThisTable','1');
               delete;
            end;
            if type='INDEX' and ICOwn eq 'YES' then delete;
         run;
         %rcSet(&syserr); 
         
      %mend etls_CIContents;
      
      %etls_CIContents(table=RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR, workTableOut=etls_commands, inDSOptions=);
      
      %if &etls_otherTablesReferToThisTable %then 
         %put WARNING%QUOTE(:) Replacing entire table will fail. Consider an alternate load technique or revising constraints.; 
      %else 
      %do; /* okay - remove foreign keys  */ 
      
         data etls_commands_F; 
            set etls_commands; 
            if upcase(type)="FOREIGN KEY" then 
            do; 
               command='ic delete '||trim(name)||';';
               output etls_commands_F; 
            end; 
         run; 
         
         %put %str(NOTE: Removing foreign keys before dropping table...);
         data _null_;
            set etls_commands_F end=eof;
            if _n_=1 then 
               call execute('proc datasets nolist lib=RRAP;modify BASEL_ANLY_BL_INSTR_FCT_&MTH_YR;');
            call execute(command);
            if eof then call execute('; quit;');
         run;
         %rcSet(&syserr); 
         
   %end; /* okay - remove foreign keys  */ 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete etls_commands etls_commands_F;
   quit;
   
   /*---- Drop a table  ----*/ 
   %put %str(NOTE: Dropping table ...);
   proc datasets lib = RRAP nolist nowarn memtype = (data view);
      delete BASEL_ANLY_BL_INSTR_FCT_&MTH_YR;
   quit;
   
   %rcSet(&syserr); 
   
   %let etls_tableExist = 0;
   
%end; /* table exists  */ 

/*---- Create a new table  ----*/ 
%if (&etls_tableExist eq 0) %then 
%do;  /* if table does not exist  */ 

   %put %str(NOTE: Creating table ...);
   
   data RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR;
      attrib MTH_TM_ID length = 8
         format = 11.
         informat = 11.
         label = 'MTH_TM_ID'; 
      attrib UNQ_ACCT_ID length = $30
         format = $30.
         informat = $30.
         label = 'UNQ_ACCT_ID'; 
      attrib PIT_STAT_CD length = $10
         format = $10.
         informat = $10.
         label = 'PIT_STAT_CD'; 
      attrib OS_BAL_AMT length = 8
         format = 19.3
         informat = 19.3
         label = 'OS_BAL_AMT'; 
      attrib PD_BASEL_SEG_NUM length = 8
         format = 11.
         informat = 11.
         label = 'PD_BASEL_SEG_NUM'; 
      attrib PD_MODEL_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_MODEL_RTO'; 
      attrib PD_LR_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_LR_RPTG_RTO'; 
      attrib PD_LR_PV_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_LR_PV_RPTG_RTO'; 
      attrib PD_LR_PV_AD_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_LR_PV_AD_RPTG_RTO'; 
      attrib PD_LD_PV_AD_SV_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_LD_PV_AD_SV_RPTG_RTO'; 
      attrib PD_FINAL_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_FINAL_RPTG_RTO'; 
      attrib LGD_BASEL_SEG_NUM length = 8
         format = 11.
         informat = 11.
         label = 'LGD_BASEL_SEG_NUM'; 
      attrib LGD_MODEL_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_MODEL_RTO'; 
      attrib LGD_LR_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_RPTG_RTO'; 
      attrib LGD_LR_PV_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_PV_RPTG_RTO'; 
      attrib LGD_LR_PV_AD_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_PV_AD_RPTG_RTO'; 
      attrib LGD_LD_PV_AD_SV_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_LD_PV_AD_SV_RPTG_RTO'; 
      attrib LGD_LD_PV_AD_SV_DT_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_LD_PV_AD_SV_DT_RPTG_RTO'; 
      attrib LGD_FINAL_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_FINAL_RPTG_RTO'; 
      attrib CCAR_EXPSR_CL_NM length = $20
         format = $20.
         informat = $20.
         label = 'CCAR_EXPSR_CL_NM'; 
      attrib MORT_NUM length = $50
         format = $50.
         informat = $50.
         label = 'MORT_NUM'; 
      attrib BASEL_CIF_KEY length = $17
         format = $17.
         informat = $17.
         label = 'BASEL_CIF_KEY'; 
      attrib PD_UNADJUSTED_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_UNADJUSTED_RPTG_RTO'; 
      attrib LGD_UNADJUSTED_RPTG_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_UNADJUSTED_RPTG_RTO'; 
      attrib PD_LR_PV_AD_SV_DT_AA_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'PD_LR_PV_AD_SV_DT_AA_RTO'; 
      attrib LGD_LR_PV_AD_SV_DT_AA_RTO length = 8
         format = 30.8
         informat = 30.8
         label = 'LGD_LR_PV_AD_SV_DT_AA_RTO'; 
      call missing(of _all_);
      stop;
   run;
   
   %rcSet(&syserr); 
   
%end;  /* if table does not exist  */ 

/*---- Append  ----*/ 
%put %str(NOTE: Appending data ...);

proc append base = RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR 
   data = &etls_lastTable (&etls_tableOptions)  force ; 
 run; 

%rcSet(&syserr); 

%mend etls_loader;
%etls_loader;

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR, DATA)) or 
         %sysfunc(exist(RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%rcSet(&syscc); 



/**  Step end Table Loader **/

/*==========================================================================* 
 * Step:            Copy File and Change Extension        A57SWEI7.BK000ZDC * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    BASEL_ANALY_BL_INSTR_FCT_&MTH_YR -    A57SWEI7.BE00044K * 
 *                   RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR                   * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000ZDC);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR, DATA)) or 
         %sysfunc(exist(RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR); 

%let _INPUT_count = 1;
%let _INPUT = RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR;

%let _INPUT1 = RRAP.BASEL_ANLY_BL_INSTR_FCT_&MTH_YR;

%let _OUTPUT_count = 0;
/*---- Start of User Written Code  ----*/ 


%let file_path=&rrap_dir./data/rrap_iias;
%let tng_path=&outpath./tng;
%let dset=%lowcase(BASEL_ANLY_BL_INSTR_FCT_&MTH_YR);

%let dset=&dset; %let file_path=&file_path;
/*x cp &file_path./&dset..sas7bdat &tng_path./&dset..sas7bdat;*/
DATA _NULL_;
	CALL SYSTEM("openssl dgst -sha256 &file_path./&dset..sas7bdat | sed -e 's/^.*= //g' >> &file_path./&dset._chk.ctl");
run;
x cp &file_path./&dset..sas7bdat &tng_path./&dset..sas7bdat.JOAAITNG;
x cp &file_path./&dset._chk.ctl &tng_path./&dset._chk.ctl;

/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end Copy File and Change Extension **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

