/**************************************************************************** 
 * Job:             RRAP_MOR_SCRCD_60_LOAD_SCORECARD_VARS A57SWEI7.BH0009L3 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 10.56.70.48                                             * 
 * Port:            8561                                                    * 
 * Location:        /Projects/RRAP/Jobs/04 - Mortgage/BNS                   * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Generated on:    Thursday, June 29, 2017 2:42:27 PM EDT                  * 
 * Generated by:    owprdsas                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009L3);
%let etls_jobName = %nrquote(RRAP_MOR_SCRCD_60_LOAD_SCORECARD_VARS);
%let etls_userID = %nrquote(owprdsas);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_rrap_mortgage_autoexec             A57SWEI7.BK000Z9L * 
 * Transform:       AM_rrap_mor_bns_autoexec                                * 
 * Description:     BNS Mortgage jobs imported from IW503 leverage this     * 
 *                   transformation                                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z9L);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%put WORK LOCATION: %sysfunc(getoption(work));
%rrap_mor_bns_autoexec;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_rrap_mortgage_autoexec **/

/*==========================================================================* 
 * Step:            User Written                          A57SWEI7.BK000Z9M * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Target Table:    User Written - work.W5JU94            A57SWEI7.BN000NRB * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK000Z9M);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.W5JU94;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A57SWEI7.BN000NRB%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
%let _OUTPUT_col_count = 0;

%let _OUTPUT1 = work.W5JU94;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A57SWEI7.BN000NRB%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
%let _OUTPUT1_col_count = 0;

/*---- Start of User Written Code  ----*/ 


/*---------------------------------------------------------------------
 * NAME:       
 *
 * PURPOSE: 
 *             
 * NOTES: 
 *             
 * MODIFIED: 5Oct2015 - CV - Added the Province_CD variable to SCORECARD_VARS_FINAL
									  Updated code to use delete table macro
 *    
 *
 * Copyright (c) 2014 by The Financial Risk Group, Cary, NC, USA.
 *---------------------------------------------------------------------*/

%delete_table(nzuser.SCORECARD_VARS_FINAL);

proc sql;
connect USING NZUSER as nzcon ;
 
execute ( create table &target_lib3..SCORECARD_VARS_FINAL as (
select  s.MORTGAGE_NO
      , s.PROCESS_DATE
      , s.AMORT
	   , s.AT36_MTH_SINCE_MOST_RECNT_DLQN as at36
	   , s.AT94_AVAILABLE_CR_NOT_UTILIZED as at94
	   , s.CUST_ACCT_CNT
	   , s.DLQNT_DAY
      , v.DLQNT_MTHMAX24M
      , DLQNT_DAYavg24m
	   , v.BI33MAX3M
	   , v.BR147MAX6M
	   , v.D2DBALMAX12M
	   , v.D2DBALPMIN6M
	   , v.GO04MAX6M
	   , v.NSF_NUMMAX6M
	   , v.PAYROLL_AMTMIN3M
	   , v.PREPAY_YTDMAX24M
      , l.INDEX_TERANETV
	   , l.LTV    
	   , ur.RATIO
	   , ur.URATE
		, p.PROVINCE_CD
from &target_lib3..SCORECARD_VARS_COMBINED  as s 
 left join &target_lib3..SCORECARD_VAR as v  
/*left join &target_lib3..SCORECARD_VAR_NZ as v  */ /* For Parallel Run used Netezza table */
   on s.MORTGAGE_NO=v.MORTGAGE_NO and
      s.PROCESS_DATE=v.PROCESS_DATE
left join &target_lib3..LTV_VAR_CLUS_LTV_FINAL as l
   on s.MORTGAGE_NO=l.MORTGAGE_NO and 
      to_number(to_char(s.PROCESS_DATE,'YYYYMM'),'999999')=l.YYMTH
left join &target_lib3..PROVINCE_REF p 
   on p.PROVINCE_ID=nullif(s.PROVINCE, ' ')
   left join &target_lib2..UNEMP_RATE ur
   on last_day(date_trunc('day', s.process_date))=last_day(date_trunc('day', ur.time_key)) and
   p.province_cd=ur.province
) WITH DATA
DISTRIBUTE BY (mortgage_no)) by nzcon;
/*
DISTRIBUTE ON (mortgage_no)) by nzcon; */


/*execute( grant select, insert, update, delete on &target_lib3...SCORECARD_VARS_MOR_09 TO frg_user) by nzcon; */

*execute (generate statistics on &target_lib3..SCORECARD_VARS_FINAL) by nzcon;
		execute(CALL SYSPROC.ADMIN_CMD (%nrbquote('RUNSTATS
					ON TABLE ) %nrbquote(&target_lib3..SCORECARD_VARS_FINAL)
						%nrbquote(ON KEY COLUMNS and INDEXES ALL'))) by nzcon;
disconnect from nzcon;

quit;



/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%rcSet(&syscc); 



/**  Step end User Written **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

