
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

%let datetime_start = %sysfunc(TIME()) ;
%put >>> START TIME: %sysfunc(datetime(),datetime14.);

%LET INPUT00=EDRRAPT.BASEL_ACAP_EXPSR_FACT;
/*%LET INPUT01=EDRRAPT.BASEL_TANGRN_CCAR_EXPSR_FACT;*/
%LET TGT00=EDRRAPT.BASEL_ACAP_EXPSR_EXTR;

PROC SQL NOPRINT ;
CONNECT USING EDRRAPT AS DB3CON;
/*DOM-SUB-DUNDEE LOAD*/
EXECUTE(
delete from  EDRRAPT.BASEL_ACAP_EXPSR_EXTR where MTH_END_DT=(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID)
)
BY DB3CON;
DISCONNECT FROM DB3CON;					   
quit;

%PUT MTH_TM_ID IS &MTH_TM_ID;

PROC SQL NOPRINT;
CONNECT USING EDRRAPT AS DB3CON;
/*DOM-SUB-DUNDEE LOAD*/
EXECUTE(
INSERT INTO EDRRAPT.BASEL_ACAP_EXPSR_EXTR 
(MTH_END_DT,
LEGAL_ENTITY,
CCAR_BASEL_PRD_TP_NM,
PD_BAND,
TRNST_NUM,
PRD_ID,
UNQ_RECD_ID,
PD_BASEL_SEG_NUM,
LGD_BASEL_SEG_NUM,
EAD_BASEL_SEG_NUM,
PD_90_DAY_F,
BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
EXPCTD_LOSS_RTO_TEXT,
BEFORE_ZERO_NET_UNDRAWN_AMT,
AF_ZERO_NET_UNDRAWN_AMT,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
LGD_FINAL_RPTG_RTO_TEXT,
EAD_FINAL_RPTG_RTO_TEXT,
EAD_PC,
CRNCY_CD,
PRTL_WRITE_OFF_AMT,
UNCONDTNLY_CNCLBL,
ACCR_INTR_AMT,
INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP,
INSUR_F,
WGHTD_DLGD_RTO)

SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS 
		MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		FACT.TRNST_NUM,
		FACT.PRD_ID,
		'DR_A'||LPAD(ROW_NUMBER() OVER (ORDER BY FACT.LEGAL_ENTITY, FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		TO_CHAR(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TO_CHAR(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		TO_CHAR(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		CURRENT_TIMESTAMP AS INSRT_PROCESS_TMSTMP,
		CURRENT_TIMESTAMP AS UPDT_PROCESS_TMSTMP,
		FACT.INSUR_F,
		FACT.WGHTD_DLGD_RTO

FROM EDRRAPT.BASEL_ACAP_EXPSR_FACT FACT WHERE FACT.LEGAL_ENTITY = 'DOM-SUB-DUNDEE'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID.
) BY DB3CON;
DISCONNECT FROM DB3CON;					   
quit;

PROC SQL NOPRINT;
CONNECT USING EDRRAPT AS DB3CON;
/*DOM-SUB-NT LOAD*/
EXECUTE(
INSERT INTO EDRRAPT.BASEL_ACAP_EXPSR_EXTR 
(MTH_END_DT,
LEGAL_ENTITY,
CCAR_BASEL_PRD_TP_NM,
PD_BAND,
TRNST_NUM,
PRD_ID,
UNQ_RECD_ID,
INSUR_F,
PD_BASEL_SEG_NUM,
LGD_BASEL_SEG_NUM,
EAD_BASEL_SEG_NUM,
PD_90_DAY_F,
BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
EXPCTD_LOSS_RTO_TEXT,
BEFORE_ZERO_NET_UNDRAWN_AMT,
AF_ZERO_NET_UNDRAWN_AMT,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
LGD_FINAL_RPTG_RTO_TEXT,
EAD_FINAL_RPTG_RTO_TEXT,
EAD_PC,
CRNCY_CD,
PRTL_WRITE_OFF_AMT,
UNCONDTNLY_CNCLBL,
ACCR_INTR_AMT,
WGHTD_DLGD_RTO,

INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
)
SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		FACT.TRNST_NUM,
		FACT.PRD_ID,
		'DR_A'||LPAD(ROW_NUMBER() OVER (ORDER BY FACT.LEGAL_ENTITY, 
		FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		TO_CHAR(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TO_CHAR(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		TO_CHAR(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO,

		CURRENT_TIMESTAMP AS INSRT_PROCESS_TMSTMP,
		CURRENT_TIMESTAMP AS UPDT_PROCESS_TMSTMP
FROM EDRRAPT.BASEL_ACAP_EXPSR_FACT FACT WHERE FACT.LEGAL_ENTITY = 'DOM-SUB-NT'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0 ) AND FACT.MTH_TM_ID=&MTH_TM_ID. 
) BY DB3CON;
DISCONNECT FROM DB3CON;
quit;

PROC SQL NOPRINT;
CONNECT USING EDRRAPT AS DB3CON ;
/*DOM-SUB-MTCC LOAD*/
EXECUTE(
INSERT INTO EDRRAPT.BASEL_ACAP_EXPSR_EXTR 
(MTH_END_DT,
LEGAL_ENTITY,
CCAR_BASEL_PRD_TP_NM,
PD_BAND,
TRNST_NUM,
PRD_ID,
UNQ_RECD_ID,
INSUR_F,
PD_BASEL_SEG_NUM,
LGD_BASEL_SEG_NUM,
EAD_BASEL_SEG_NUM,
PD_90_DAY_F,
BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
EXPCTD_LOSS_RTO_TEXT,
BEFORE_ZERO_NET_UNDRAWN_AMT,
AF_ZERO_NET_UNDRAWN_AMT,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
LGD_FINAL_RPTG_RTO_TEXT,
EAD_FINAL_RPTG_RTO_TEXT,
EAD_PC,
CRNCY_CD,
PRTL_WRITE_OFF_AMT,
UNCONDTNLY_CNCLBL,
ACCR_INTR_AMT,
WGHTD_DLGD_RTO,

INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
)
SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		FACT.TRNST_NUM,
		FACT.PRD_ID,
		'DR_A'||LPAD(ROW_NUMBER() OVER (ORDER BY FACT.LEGAL_ENTITY, 
		FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		TO_CHAR(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TO_CHAR(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		TO_CHAR(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO,

		CURRENT_TIMESTAMP AS INSRT_PROCESS_TMSTMP,
		CURRENT_TIMESTAMP AS UPDT_PROCESS_TMSTMP
FROM EDRRAPT.BASEL_ACAP_EXPSR_FACT FACT WHERE FACT.LEGAL_ENTITY = 'DOM-SUB-MTCC'
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID
) BY DB3CON;
DISCONNECT FROM DB3CON;
quit;

PROC SQL NOPRINT;
CONNECT USING EDRRAPT AS DB3CON;
/*DOM-SUB-MAPLE AND DOM-SUB-SMC LOAD*/
EXECUTE(
INSERT INTO EDRRAPT.BASEL_ACAP_EXPSR_EXTR 
(MTH_END_DT,
LEGAL_ENTITY,
CCAR_BASEL_PRD_TP_NM,
PD_BAND,
TRNST_NUM,
PRD_ID,
UNQ_RECD_ID,
INSUR_F,
PD_BASEL_SEG_NUM,
LGD_BASEL_SEG_NUM,
EAD_BASEL_SEG_NUM,
PD_90_DAY_F,
BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
EXPCTD_LOSS_RTO_TEXT,
BEFORE_ZERO_NET_UNDRAWN_AMT,
AF_ZERO_NET_UNDRAWN_AMT,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
LGD_FINAL_RPTG_RTO_TEXT,
EAD_FINAL_RPTG_RTO_TEXT,
EAD_PC,
CRNCY_CD,
PRTL_WRITE_OFF_AMT,
UNCONDTNLY_CNCLBL,
ACCR_INTR_AMT,
WGHTD_DLGD_RTO,

INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
)
SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		FACT.LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		FACT.TRNST_NUM,
		FACT.PRD_ID,
		'DR_A'||LPAD(ROW_NUMBER() OVER (ORDER BY FACT.LEGAL_ENTITY, 
		FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		TO_CHAR(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TO_CHAR(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		TO_CHAR(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO,
		CURRENT_TIMESTAMP AS INSRT_PROCESS_TMSTMP,
		CURRENT_TIMESTAMP AS UPDT_PROCESS_TMSTMP
FROM EDRRAPT.BASEL_ACAP_EXPSR_FACT FACT WHERE FACT.LEGAL_ENTITY IN ('DOM-SUB-MAPLE','DOM-SUB-SMC')
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID
) BY DB3CON;
DISCONNECT FROM DB3CON;					   
quit;

PROC SQL NOPRINT;
CONNECT USING EDRRAPT AS DB3CON;
/*DOM-BANK-BNS AND TANGERINE LOAD TOGETHER*/
EXECUTE(
INSERT INTO EDRRAPT.BASEL_ACAP_EXPSR_EXTR 
(MTH_END_DT,
LEGAL_ENTITY,
CCAR_BASEL_PRD_TP_NM,
PD_BAND,
TRNST_NUM,
PRD_ID,
UNQ_RECD_ID,
INSUR_F,
PD_BASEL_SEG_NUM,
LGD_BASEL_SEG_NUM,
EAD_BASEL_SEG_NUM,
PD_90_DAY_F,
BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
EXPCTD_LOSS_RTO_TEXT,
BEFORE_ZERO_NET_UNDRAWN_AMT,
AF_ZERO_NET_UNDRAWN_AMT,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
LGD_FINAL_RPTG_RTO_TEXT,
EAD_FINAL_RPTG_RTO_TEXT,
EAD_PC,
CRNCY_CD,
PRTL_WRITE_OFF_AMT,
UNCONDTNLY_CNCLBL,
ACCR_INTR_AMT,
WGHTD_DLGD_RTO,

INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
)
SELECT DISTINCT 
SUBQ.MTH_END_DT,
SUBQ.LEGAL_ENTITY,
SUBQ.CCAR_BASEL_PRD_TP_NM,
SUBQ.PD_BAND,
SUBQ.TRNST_NUM,
SUBQ.PRD_ID,
'DR_A'||LPAD(ROW_NUMBER() OVER (ORDER BY SUBQ.UNQ_RECD_ID_TEMP ASC),6,'0') AS UNQ_RECD_ID,
SUBQ.INSUR_F,
SUBQ.PD_BASEL_SEG_NUM,
SUBQ.LGD_BASEL_SEG_NUM,
SUBQ.EAD_BASEL_SEG_NUM,
SUBQ.PD_90_DAY_F,
SUBQ.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
SUBQ.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
SUBQ.EXPCTD_LOSS_RTO_TEXT,
SUBQ.BEFORE_ZERO_NET_UNDRAWN_AMT,
SUBQ.AF_ZERO_NET_UNDRAWN_AMT,
SUBQ.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
SUBQ.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
SUBQ.LGD_FINAL_RPTG_RTO_TEXT,
SUBQ.EAD_FINAL_RPTG_RTO_TEXT,
SUBQ.EAD_PC,
SUBQ.CRNCY_CD,
SUBQ.PRTL_WRITE_OFF_AMT,
SUBQ.UNCONDTNLY_CNCLBL,
SUBQ.ACCR_INTR_AMT,
SUBQ.WGHTD_DLGD_RTO,

SUBQ.INSRT_PROCESS_TMSTMP,
SUBQ.UPDT_PROCESS_TMSTMP 
FROM
(
SELECT
		(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		'DOM-BANK-ALONE' AS LEGAL_ENTITY,
		FACT.CCAR_BASEL_PRD_TP_NM,
		FACT.PD_BAND,
		FACT.TRNST_NUM,
		FACT.PRD_ID,
		'TEMP'||LPAD(ROW_NUMBER() OVER (ORDER BY FACT.LEGAL_ENTITY, 
		FACT.CCAR_BASEL_PRD_TP_NM, FACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID_TEMP,
		FACT.INSUR_F,
		FACT.PD_BASEL_SEG_NUM,
		CASE WHEN FACT.LGD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.LGD_BASEL_SEG_NUM END AS LGD_BASEL_SEG_NUM,
		CASE WHEN FACT.EAD_BASEL_SEG_NUM=-1 THEN NULL ELSE FACT.EAD_BASEL_SEG_NUM END AS EAD_BASEL_SEG_NUM,
		CASE WHEN FACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		FACT.AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		TO_CHAR(CAST(ROUND(FACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		FACT.BEFORE_ZERO_NET_UNDRAWN_AMT,
		FACT.AF_ZERO_NET_UNDRAWN_AMT,
		FACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		FACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TO_CHAR(CAST(ROUND(FACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		TO_CHAR(CAST(ROUND(FACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		FACT.CRNCY_CD,
		FACT.PRTL_WRITE_OFF_AMT,
		FACT.UNCONDTNLY_CNCLBL,
		FACT.ACCR_INTR_AMT,
		FACT.WGHTD_DLGD_RTO,

		CURRENT_TIMESTAMP AS INSRT_PROCESS_TMSTMP,
		CURRENT_TIMESTAMP AS UPDT_PROCESS_TMSTMP
FROM EDRRAPT.BASEL_ACAP_EXPSR_FACT FACT WHERE FACT.LEGAL_ENTITY IN ('DOM-BANK-BNS')
AND (FACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR FACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND FACT.MTH_TM_ID=&MTH_TM_ID
) as SUBQ
) BY DB3CON;
DISCONNECT FROM DB3CON;					   
quit;

PROC SQL NOPRINT;
CONNECT USING EDRRAPT AS DB3CON;
/*TANGERINE LOAD ONLY*/
EXECUTE(
INSERT INTO EDRRAPT.BASEL_ACAP_EXPSR_EXTR 
(MTH_END_DT,
LEGAL_ENTITY,
CCAR_BASEL_PRD_TP_NM,
PD_BAND,
TRNST_NUM,
PRD_ID,
UNQ_RECD_ID,
INSUR_F,
PD_BASEL_SEG_NUM,
LGD_BASEL_SEG_NUM,
EAD_BASEL_SEG_NUM,
PD_90_DAY_F,
BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
EXPCTD_LOSS_RTO_TEXT,
BEFORE_ZERO_NET_UNDRAWN_AMT,
AF_ZERO_NET_UNDRAWN_AMT,
BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
LGD_FINAL_RPTG_RTO_TEXT,
EAD_FINAL_RPTG_RTO_TEXT,
EAD_PC,
CRNCY_CD,
PRTL_WRITE_OFF_AMT,
UNCONDTNLY_CNCLBL,
ACCR_INTR_AMT,
WGHTD_DLGD_RTO,

INSRT_PROCESS_TMSTMP,
UPDT_PROCESS_TMSTMP
)
SELECT DISTINCT
(SELECT TM_LVL_END_DT FROM EDRTLRT.TM_DIM WHERE TM_ID=&MTH_TM_ID) AS MTH_END_DT,
		TFACT.LEGAL_ENTITY,
		TFACT.CCAR_BASEL_PRD_TP_NM,
		TFACT.PD_BAND,
		TFACT.TRNST_NUM,
		TFACT.PRD_ID,
		'DR_A'||LPAD(ROW_NUMBER() OVER (ORDER BY TFACT.LEGAL_ENTITY, 
		TFACT.CCAR_BASEL_PRD_TP_NM, TFACT.PD_BAND ASC),6,'0') AS UNQ_RECD_ID,
		TFACT.INSUR_F,
		PD_BASEL_SEG_NUM,
		(case when LGD_BASEL_SEG_NUM=-1 then null else LGD_BASEL_SEG_NUM end) as LGD_BASEL_SEG_NUM,
		(case when EAD_BASEL_SEG_NUM=-1 then null else EAD_BASEL_SEG_NUM end) as  EAD_BASEL_SEG_NUM,
		CASE WHEN TFACT.PD_90_DAY_F = 'T' THEN 'TRUE' ELSE 'FALSE' END AS PD_90_DAY_F,
		BEFR_ZERO_NET_ADJ_OS_BAL_AMT,
		AF_ZERO_NET_ADJUSTED_OS_BAL_AMT,
		TO_CHAR(CAST(ROUND(TFACT.EXPCTD_LOSS_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EXPCTD_LOSS_RTO_TEXT,
		 BEFORE_ZERO_NET_UNDRAWN_AMT,
		AF_ZERO_NET_UNDRAWN_AMT,
		TFACT.BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT AS BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TFACT.AF_ZERO_NET_ALWBL_CR_LOSS_AMT AS AF_ZERO_NET_ALWBL_CR_LOSS_AMT,
		TO_CHAR(CAST(ROUND(TFACT.LGD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS LGD_FINAL_RPTG_RTO_TEXT,
		TO_CHAR(CAST(ROUND(TFACT.EAD_FINAL_RPTG_RTO*100,6) AS DECIMAL(15,6)))||'%' AS EAD_FINAL_RPTG_RTO_TEXT,
		'' AS EAD_PC,
		TFACT.CRNCY_CD,
		TFACT.PRTL_WRITE_OFF_AMT,
		TFACT.UNCONDTNLY_CNCLBL AS UNCONDTNLY_CNCLBL,
		TFACT.ACCR_INTR_AMT,
		TFACT.WGHTD_DLGD_RTO,

		CURRENT_TIMESTAMP AS INSRT_PROCESS_TMSTMP,
		CURRENT_TIMESTAMP AS UPDT_PROCESS_TMSTMP
FROM EDRRAPT.BASEL_ACAP_EXPSR_FACT tFACT WHERE tFACT.LEGAL_ENTITY IN ( 'DOM-SUB-TNG' )
AND (tFACT.BEFR_ZERO_NET_ADJ_OS_BAL_AMT <> 0 OR tFACT.BEFORE_ZERO_NET_UNDRAWN_AMT <> 0) AND tFACT.MTH_TM_ID=&MTH_TM_ID)
 BY DB3CON;
						
QUIT;


