
%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);


%GLOBAL YEARMONTH;
%GLOBAL PRELOAD_DATA_COUNT;
%GLOBAL SRCCOUNT00;
%GLOBAL SRCCOUNT01;
%GLOBAL TGTCOUNT00;
%LET INPUT00=EDRRAPT.BASEL_ANALYTCL_BL_INSTRMNT_FACT;
%LET TGT00=EDRRAPT.BASEL_RPTG_SCHED_2_6_FACT;

proc sql;
delete from &db..BASEL_RPTG_SCHED_2_6_FACT where MTH_TM_ID=&MTH_TM_ID;
quit;
/*Fetch the Year and Month from TM_DIM to use it for query on 
EDRRAPT.BASEL_SUBSIDIARY_ACL_LKP*/
%macro rrap_db2yearmonth_initialize;
proc sql noprint;
create table _temp_yearmonth as 
select clndr_yr, tm_yr_seq_num, '00' as charmonth, '000000' as yearmonth from 
EDRTLRT.TM_DIM where TM_ID = &MTH_TM_ID;
quit;
/*Convert the integer values to char values as needed*/
data _temp_yearmonth;
set _temp_yearmonth;
if tm_yr_seq_num < 10 then do;
	charmonth='0'||put(tm_yr_seq_num,1.);
end;
else do;
charmonth=tm_yr_seq_num;
end;
yearmonth=clndr_yr||charmonth;
	format yearmonth $char6.;
run;
/*Save the string YYYYMM for the latest MTH_TM_ID fetched from TM_DIM into a 
variable*/
proc sql noprint;
select yearmonth into :yearmonth from _temp_yearmonth;
quit;
%mend rrap_db2yearmonth_initialize;

/*This transformation accepts the target table to be loaded as an input 
parameter
and checks existence of data for the processing MTH_TM_ID */
%MACRO preload_data_check;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :PRELOAD_DATA_COUNT FROM &TGT00. WHERE 
MTH_TM_ID=&MTH_TM_ID;
QUIT;
%IF &PRELOAD_DATA_COUNT > 0 %THEN %DO;
%PUT TARGET TABLE &TGT00. ALREADY HAS &PRELOAD_DATA_COUNT RECORDS FOR CURRENT 
PROCESSING MONTH ID &MTH_TM_ID;
%END;
%MEND preload_data_check;

/*This transformation generates the input and output table counts*/
%MACRO datalog;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :SRCCOUNT00 FROM &INPUT00. WHERE MTH_TM_ID=&MTH_TM_ID.;
SELECT COUNT(*) INTO :TGTCOUNT00 FROM &TGT00. WHERE MTH_TM_ID=&MTH_TM_ID.;
QUIT;
%MEND;

/*CLEANUP MACRO*/
/*THIS MACRO DELETES ALL TEMPORARY SAS DATASETS LISTED BY THE USER AT THE 
SPECIFIED PATH ON AIX PLATFORM*/
/*LIBREF SHOULD BE THE LIBREF DECLARED FOR A UNIX PATH IN THE PROGRAM*/
/*DATASETS SHOULD BE THE LIST OF DATASETS SEPARATED BY A SINGLE SPACE*/
%MACRO SAS_DATASET_CLEANUP (LIBREF=, DATASETS=);
/*DELETE TEMPORARY DATASETS*/
PROC DATASETS LIBRARY=&LIBREF;
DELETE &DATASETS;
RUN;
QUIT;
%MEND;

/*Macro for fetching the yearmonth in an integer format*/
%rrap_db2yearmonth_initialize;
%PUT YEARMONTH IS &YEARMONTH;

/*MACRO TO FETCH THE RECORD COUNT FROM THE TARGET TABLE FOR THE PROCESSING 
MONTH*/
%preload_data_check;

/*==========================================================================* 
 * Step:            Conditional Start                     A57ZQ4A4.BO0002TX * 
 * Transform:       Conditional Start                                       * 
 * Description:     If Preload count > 0 dont load the target               * 
 *==========================================================================*/
%macro etls_conditionW372I5YQ;
   %local etls_condition;
   %let etls_conditionTrue = %eval(&PRELOAD_DATA_COUNT = 0);
   %if (&etls_conditionTrue=0) %then
   %do;
      %put ETLS_DIAG: Condition flow did NOT execute, condition was &PRELOAD_DATA_COUNT = 0;
      %goto exitetls_conditionW372I5YQ;
   %end;
   %else
   %do;
      %put ETLS_DIAG: Condition flow did execute, condition was &PRELOAD_DATA_COUNT = 0;
   %end;

/*CREATE THE PRIMARY DATASET WITH ALL CALCULATIONS EXCEPT THE 11 MONTH COUNT*/
PROC SQL;
CREATE TABLE &INPATH.._TEMP_RRAP_2_6_EXTRACT AS 
SELECT ASST_CL_NUM, BCAR_SCHED_NUM, 
SUM(
CASE WHEN PIT_STAT_CD IN ('CUR','DEF') THEN 1 ELSE 0 
END
) AS ACCT_CNT, 
SUM(
CASE WHEN SRC_SYS_CD='SPL' THEN (ADJUSTED_OS_BAL_AMT/*+UNADJUSTED_ADD_ON_BAL_AMT*/)
	 WHEN SRC_SYS_CD IN ('MOR','KS','TNG-MOR') THEN (ADJUSTED_OS_BAL_AMT) 
END 
) AS ADJ_BEFORE_ZERO_NET_OS_BAL_AMT FORMAT 20.8,
SUM(
CASE WHEN SRC_SYS_CD='SPL' THEN 
CASE WHEN ADJUSTED_OS_BAL_AMT/*+UNADJUSTED_ADD_ON_BAL_AMT*/ < 0 THEN 0 ELSE 
ADJUSTED_OS_BAL_AMT /*+UNADJUSTED_ADD_ON_BAL_AMT*/ END
	 WHEN SRC_SYS_CD IN ('MOR','KS','TNG-MOR') THEN 
	 	CASE WHEN ADJUSTED_OS_BAL_AMT < 0 THEN 0 ELSE ADJUSTED_OS_BAL_AMT END 
END
) AS ADJUSTED_AF_ZERO_NET_OS_BAL_AMT FORMAT 20.8,
SUM(
CASE WHEN PIT_STAT_CD = 'DEF' THEN 1 ELSE 0 
END
) AS DEFLTD_ACCT_CNT,
SUM(
CASE WHEN PIT_STAT_CD = 'DEF' THEN
CASE WHEN SRC_SYS_CD='SPL' THEN (ADJUSTED_OS_BAL_AMT /*+UNADJUSTED_ADD_ON_BAL_AMT*/)
	 		WHEN SRC_SYS_CD IN ('MOR','KS','TNG-MOR') THEN (ADJUSTED_OS_BAL_AMT) 
	END 
ELSE 0 END
) AS ADJ_BEFR_ZER_NET_DF_AC_OS_BL_AMT FORMAT 20.8,
SUM(
CASE WHEN PIT_STAT_CD = 'DEF' THEN
	CASE 	WHEN SRC_SYS_CD='SPL' THEN 
CASE WHEN ADJUSTED_OS_BAL_AMT /*+UNADJUSTED_ADD_ON_BAL_AMT*/ < 0 THEN 0 ELSE 
ADJUSTED_OS_BAL_AMT /*+UNADJUSTED_ADD_ON_BAL_AMT*/ END
	 		WHEN SRC_SYS_CD IN ('MOR','KS','TNG-MOR') THEN 
	 			CASE WHEN ADJUSTED_OS_BAL_AMT < 0 THEN 0 ELSE ADJUSTED_OS_BAL_AMT END 
	END
ELSE 0 END
) AS ADJ_AF_ZERO_NET_DF_AC_OS_BAL_AMT FORMAT 20.8
FROM INPATH.BASEL_ANALYTCL_BL_INSTRMNT_FACT 
WHERE SML_BUS_F = 'N' AND CONSM_PRD_TREATMNT_CD ='A' 
AND PIT_STAT_CD IN ('CUR' ,'DEF')
AND TRNST_EXCLSN_F = 'N'
AND MTH_TM_ID=&MTH_TM_ID
GROUP BY ASST_CL_NUM,BCAR_SCHED_NUM;
QUIT;

/*FETCH THE 11 MONTH COUNT USING A PASS THROUGH*/
/*THE PROCESSING MONTH SUBTRACTED BY 11 MONTHS GIVES THE MTH_TM_ID OF THE 
PERIOD 11 MOMTH OLDER THAT PROCESSING MONTH*/
PROC SQL;
CONNECT USING EDRRAPT AS DBCON ;
CREATE TABLE &INPATH.._TEMP_RRAP_2_6_11MTH_COUNT AS
SELECT * FROM CONNECTION TO DBCON (
SELECT ASST_CL_NUM, BCAR_SCHED_NUM,
COUNT(DISTINCT BASEL_ACCT_ID) AS PREV_12_MTH_TOT_DEFLTD_ACCT_CNT
FROM EDRRAPT.BASEL_ANALYTCL_BL_INSTRMNT_FACT 
WHERE SML_BUS_F = 'N' AND CONSM_PRD_TREATMNT_CD ='A' 
AND PIT_STAT_CD IN ('DEF')
AND TRNST_EXCLSN_F = 'N'
AND MTH_TM_ID BETWEEN (
SELECT TM_ID AS MTH_TM_ID_11MTHS FROM EDRTLRT.TM_DIM WHERE TM_LVL_ST_DT = (
SELECT TM_LVL_ST_DT - 11 MONTHS AS MTH_END_DT_11MTHS FROM EDRTLRT.TM_DIM WHERE 
TM_ID=&MTH_TM_ID
) AND TM_LVL='Month') AND &MTH_TM_ID
GROUP BY ASST_CL_NUM,BCAR_SCHED_NUM;
);
DISCONNECT FROM DBCON;
QUIT;
/*SORT THE DATASET*/
PROC SORT DATA=&INPATH.._TEMP_RRAP_2_6_EXTRACT 
OUT=&INPATH.._TEMP_RRAP_2_6_EXTRACT;
BY ASST_CL_NUM BCAR_SCHED_NUM;
RUN;
/*SORT THE DATASET*/
PROC SORT DATA=&INPATH.._TEMP_RRAP_2_6_11MTH_COUNT 
OUT=&INPATH.._TEMP_RRAP_2_6_11MTH_COUNT;
BY ASST_CL_NUM BCAR_SCHED_NUM;
RUN;
/*MERGE THE DATASETS TO INLCUDE THE PRIMARY EXTRACT AND THE 11MTH COUNT */
DATA &INPATH.._TEMP_RRAP_2_6_EXTRACT_F;
MERGE &INPATH.._TEMP_RRAP_2_6_EXTRACT &INPATH.._TEMP_RRAP_2_6_11MTH_COUNT;
BY ASST_CL_NUM BCAR_SCHED_NUM;
RUN;
/*ADD TIMESTAMPS*/
DATA &INPATH.._TEMP_RRAP_2_6_EXTRACT_F;
format mth_tm_id 11.
ASST_CL_NUM 6.
BCAR_SCHED_NUM $3. 
ACCT_CNT 11.
ADJ_BEFORE_ZERO_NET_OS_BAL_AMT	22.8
ADJUSTED_AF_ZERO_NET_OS_BAL_AMT 22.8
DEFLTD_ACCT_CNT 11.
ADJ_BEFR_ZER_NET_DF_AC_OS_BL_AMT 22.8
ADJ_AF_ZERO_NET_DF_AC_OS_BAL_AMT 22.8
PREV_12_MTH_TOT_DEFLTD_ACCT_CNT 6.
INSRT_PROCESS_TMSTMP UPDT_PROCESS_TMSTMP datetime25.6;
SET &INPATH.._TEMP_RRAP_2_6_EXTRACT_F;
MTH_TM_ID=&MTH_TM_ID;
INSRT_PROCESS_TMSTMP = &SESSIONTIME;
UPDT_PROCESS_TMSTMP = &SESSIONTIME;
RUN;

data &INPATH.._TEMP_RRAP_2_6_EXTRACT_F2;
set &INPATH.._TEMP_RRAP_2_6_EXTRACT_F;
where asst_cl_num ne .;
run;
			

/*APPEND THE SAS DATASET TO DB2 TABLE*/
PROC APPEND BASE=EDRRAPT.BASEL_RPTG_SCHED_2_6_FACT (BULKLOAD=YES BL_METHOD=CLILOAD)
DATA=INPATH._TEMP_RRAP_2_6_EXTRACT_F2 FORCE;
RUN;


%datalog;

%SAS_DATASET_CLEANUP(LIBREF=INPATH,DATASETS=_TEMP_RRAP_2_6_EXTRACT _TEMP_RRAP_2_6_11MTH_COUNT _TEMP_RRAP_2_6_EXTRACT_F);

%PUT 
PROCESSING MONTH IS &MTH_TM_ID 
YEARMONTH IS &YEARMONTH 
PRELOAD DATA COUNT IN TARGET FOR &MTH_TM_ID IS &PRELOAD_DATA_COUNT 
&INPUT00. COUNT IS &SRCCOUNT00 
&TGT00. COUNT IS &TGTCOUNT00;

%exitetls_conditionW372I5YQ:
%mend etls_conditionW372I5YQ;

%etls_conditionW372I5YQ;

%PUT etls_endTime = %sysfunc(datetime(),datetime.);
