

%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);

OPTIONS COMPRESS=Y;
%GLOBAL YEARMONTH;
%GLOBAL PRELOAD_DATA_COUNT;
%GLOBAL SRCCOUNT00;
%GLOBAL SRCCOUNT01;
%GLOBAL TGTCOUNT00;
%GLOBAL V_NCR_RISK_RT_SYS_ID;
%GLOBAL V_EXPSR_CL_ID;
%GLOBAL V_NCR_PD_SEG_ID;
%GLOBAL V_NCR_LGD_SEG_ID;
%GLOBAL V_NCR_EAD_SEG_ID;
%LET INPUT00=EDRRAPT.BASEL_CANDN_RTL_NCR_BE_FACT;
%LET TGT00=EDRRAPT.BASEL_NCR_BACK_TESTNG_FACT;

proc sql;
delete from edrrapt.BASEL_NCR_BACK_TESTNG_FACT
where MTH_TM_ID=&MTH_TM_ID;
quit;

/*Fetch the Year and Month from TM_DIM to use it for query on 
EDRRAPT.BASEL_SUBSIDIARY_ACL_LKP*/
%macro rrap_db2yearmonth_initialize;
proc sql noprint;
create table _temp_yearmonth as 
select clndr_yr, tm_yr_seq_num, '00' as charmonth, '000000' as yearmonth from 
EDRTLRT.TM_DIM where TM_ID = &MTH_TM_ID;
quit;
/*Convert the integer values to char values as needed*/
data _temp_yearmonth;
set _temp_yearmonth;
if tm_yr_seq_num < 10 then do;
	charmonth='0'||put(tm_yr_seq_num,1.);
end;
else do;
charmonth=tm_yr_seq_num;
end;
	yearmonth=clndr_yr||charmonth;
	format yearmonth $char6.;
run;
/*Save the string YYYYMM for the latest MTH_TM_ID fetched from TM_DIM into a variable*/
proc sql noprint;
select yearmonth into :yearmonth from _temp_yearmonth;
quit;
%mend rrap_db2yearmonth_initialize;

/*This transformation accepts the target table to be loaded as an input 
parameter
and checks existence of data for the processing MTH_TM_ID */
%MACRO preload_data_check;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :PRELOAD_DATA_COUNT FROM &TGT00. WHERE 
MTH_TM_ID=&MTH_TM_ID;
QUIT;
%IF &PRELOAD_DATA_COUNT > 0 %THEN %DO;
%PUT TARGET TABLE &TGT00. ALREADY HAS &PRELOAD_DATA_COUNT RECORDS FOR CURRENT 
PROCESSING MONTH ID &MTH_TM_ID;
%END;
%MEND preload_data_check;

/*This transformation generates the input and output table counts*/
%MACRO datalog;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :SRCCOUNT00 FROM &INPUT00. WHERE MTH_TM_ID=&MTH_TM_ID.;
SELECT COUNT(*) INTO :TGTCOUNT00 FROM &TGT00. WHERE MTH_TM_ID=&MTH_TM_ID.;
QUIT;
%MEND;

/*CLEANUP MACRO*/
/*THIS MACRO DELETES ALL TEMPORARY SAS DATASETS LISTED BY THE USER AT THE 
SPECIFIED PATH ON AIX PLATFORM*/
/*LIBREF SHOULD BE THE LIBREF DECLARED FOR A UNIX PATH IN THE PROGRAM*/
/*DATASETS SHOULD BE THE LIST OF DATASETS SEPARATED BY A SINGLE SPACE*/
%MACRO SAS_DATASET_CLEANUP (LIBREF=, DATASETS=);
/*DELETE TEMPORARY DATASETS*/
PROC DATASETS LIBRARY=&LIBREF;
DELETE &DATASETS;
RUN;
QUIT;
%MEND;

/*Macro for fetching the yearmonth in an integer format*/
%rrap_db2yearmonth_initialize;
%PUT YEARMONTH IS &YEARMONTH;

/*MACRO TO FETCH THE RECORD COUNT FROM THE TARGET TABLE FOR THE PROCESSING MONTH*/
%preload_data_check;

/*==========================================================================* 
 * Step:            Conditional Start                     A57ZQ4A4.BO0002TX * 
 * Transform:       Conditional Start                                       * 
 * Description:     If Preload count > 0 dont load the target               * 
 *==========================================================================*/


%macro etls_conditionW36PM3VD;
   %local etls_condition;
   %let etls_conditionTrue = %eval(&PRELOAD_DATA_COUNT = 0);
   %if (&etls_conditionTrue=0) %then
   %do;
      %put ETLS_DIAG: Condition flow did NOT execute, condition was &PRELOAD_DATA_COUNT = 0;
      %goto exitetls_conditionW36PM3VD;
   %end;
   %else
   %do;
      %put ETLS_DIAG: Condition flow did execute, condition was &PRELOAD_DATA_COUNT = 0;
   %end;

%MACRO basel_ncr_back_testing_fact;
/*FETCH AND STORE THE SEGEMENT IDs AS A PART OF LOOKUP NECESSITY. THESE 
VARIABLES WILL BE EVENTUALLY USED IN THE INSERT STATEMENT BELOW*/
PROC SQL NOPRINT;
/*RISK*/
SELECT NCR_RISK_RT_SYS_ID INTO :V_NCR_RISK_RT_SYS_ID FROM 
DDB2CON.BASEL_NCR_RISK_RT_SYS_DIM WHERE NCR_RISK_RT_KEY_VAL='0299' 
/*AND CRNT_F='Y' */
AND INPUT(EFF_FROM_YR_MTH,6.) <= &yearmonth and &yearmonth <= 
INPUT(EFF_TO_YR_MTH,6.);
/*EXPOSURE*/
SELECT EXPSR_CL_ID INTO :V_EXPSR_CL_ID FROM DDB2CON.BASEL_EXPSR_CL_DIM WHERE 
NCR_EXPSR_CL_KEY_VAL='0599' 
/*AND CRNT_F='Y' */
AND INPUT(EFF_FROM_YR_MTH,6.) <= &yearmonth and &yearmonth <= 
INPUT(EFF_TO_YR_MTH,6.);
/*PD LGD AND EAD SEGMENTS*/
SELECT NCR_PD_SEG_ID INTO :V_NCR_PD_SEG_ID FROM DDB2CON.BASEL_NCR_PD_SEG_DIM 
WHERE NCR_PD_SEG_KEY_VAL='0999' 
/*AND CRNT_F='Y'*/
AND INPUT(EFF_FROM_YR_MTH,6.) <= &yearmonth and &yearmonth <= 
INPUT(EFF_TO_YR_MTH,6.);
SELECT NCR_LGD_SEG_ID INTO :V_NCR_LGD_SEG_ID FROM DDB2CON.BASEL_NCR_LGD_SEG_DIM 
WHERE NCR_LGD_SEG_KEY_VAL='3299' 
/*AND CRNT_F='Y'*/
AND INPUT(EFF_FROM_YR_MTH,6.) <= &yearmonth and &yearmonth <= 
INPUT(EFF_TO_YR_MTH,6.);
SELECT NCR_EAD_SEG_ID INTO :V_NCR_EAD_SEG_ID FROM DDB2CON.BASEL_NCR_EAD_SEG_DIM 
WHERE NCR_EAD_SEG_KEY_VAL='3399' 
/*AND CRNT_F='Y'*/
AND INPUT(EFF_FROM_YR_MTH,6.) <= &yearmonth and &yearmonth <= 
INPUT(EFF_TO_YR_MTH,6.);
QUIT;
/*HANDLE NULL VALUES FOR THE ABOVE MACRO VARIABLES. */
/*THESE MACRO VARIABLES WILL BE PART OF PRIMARY KEY IN THE TARGET TABLE AND 
HENCE NULL SHOULD BE REPLACED WITH -1*/
%IF &V_NCR_RISK_RT_SYS_ID= %THEN %LET V_NCR_RISK_RT_SYS_ID=-1;
%IF &V_EXPSR_CL_ID= %THEN %LET V_EXPSR_CL_ID=-1;
%IF &V_NCR_PD_SEG_ID= %THEN %LET V_NCR_PD_SEG_ID=-1;
%IF &V_NCR_LGD_SEG_ID= %THEN %LET V_NCR_LGD_SEG_ID=-1;
%IF &V_NCR_EAD_SEG_ID= %THEN %LET V_NCR_EAD_SEG_ID=-1;
/*DISPLAY IN LOG THE VALUES ASSIGNED TO VARIABLES*/
%PUT V_NCR_RISK_RT_SYS_ID IS  &V_NCR_RISK_RT_SYS_ID;
%PUT V_EXPSR_CL_ID IS  &V_EXPSR_CL_ID;
%PUT V_NCR_PD_SEG_ID IS  &V_NCR_PD_SEG_ID;
%PUT V_NCR_LGD_SEG_ID IS  &V_NCR_LGD_SEG_ID;
%PUT V_NCR_EAD_SEG_ID IS  &V_NCR_EAD_SEG_ID;
/*STEP 1 OF BSTM*/
/*GROUP BY CUBE ALL LISTED ATTRIBUTES WITH RESPECTIVE AGGREGATION RULES*/


PROC SQL NOPRINT;
CONNECT USING EDRRAPT AS DB3CON ;
CREATE TABLE &INPATH.._temp_backtest_first AS 
SELECT * FROM CONNECTION TO DB3CON (
SELECT 
NCR_RISK_RT_SYS_ID,
EXPSR_CL_ID,
NCR_PD_SEG_ID,
NCR_LGD_SEG_ID,
NCR_EAD_SEG_ID,
SUM(RPTG_QTR_ACCT_CNT) AS ACCT_CNT,
NVL(SUM(PD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/NULLIF(SUM(RPTG_QTR_ACCT_CNT),0),0) AS 
PD_ESTD_AVG_RTO, /*HANDLING DIVIDE BY ZERO*/
NVL(SUM(LGD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/NULLIF(SUM(RPTG_QTR_ACCT_CNT),0),0) AS 
LGD_ESTD_AVG_RTO,/*HANDLING DIVIDE BY ZERO*/
NVL(SUM(EAD_ESTD_RTO*RPTG_QTR_ACCT_CNT)/NULLIF(SUM(RPTG_QTR_ACCT_CNT),0),0) AS 
EAD_ESTD_AVG_RTO,/*HANDLING DIVIDE BY ZERO*/
SUM(PD_REALZ_ACCT_CNT) AS NON_DEFLTD_PREV_12_MTH_ACCT_CNT,
SUM(LGD_REALZ_ACCT_CNT) AS LGD_CALC_PREV_36_MTH_ACCT_CNT,
SUM(EAD_REALZ_ACCT_CNT) AS EVER_DEFLTD_PREV_12_MTH_ACCT_CNT,
NVL(SUM(PD_REALZ_RTO*PD_REALZ_ACCT_CNT)/NULLIF(SUM(PD_REALZ_ACCT_CNT),0),0) AS 
PD_REALZ_RTO,/*HANDLING DIVIDE BY ZERO*/
NVL(SUM(LGD_REALZ_RTO*LGD_REALZ_ACCT_CNT)/NULLIF(SUM(LGD_REALZ_ACCT_CNT),0),0) 
AS LGD_REALZ_RTO,/*HANDLING DIVIDE BY ZERO*/
NVL(SUM(EAD_REALZ_RTO*EAD_REALZ_ACCT_CNT)/NULLIF(SUM(EAD_REALZ_ACCT_CNT),0),0) 
AS EAD_REALZ_RTO,/*HANDLING DIVIDE BY ZERO*/
SUM(PD_REALZ_DEFLTD_ACCT_CNT) AS PD_DEFLTD_PREV_12_MTH_ACCT_CNT,
SUM(LGD_REALZ_DEFLTD_ACCT_CNT) AS LGD_DEFLTD_PREV_36_MTH_ACCT_CNT,
SUM(EAD_REALZ_DEFLTD_ACCT_CNT) AS EAD_EVER_DF_PREV_12_MTH_ACCT_CNT,
SUM(PD_REALZ_DEFLTD_OS_BAL_AMT) AS PD_REALZ_OS_BAL_AMT,
SUM(LGD_REALZ_DEFLTD_OS_BAL_AMT) AS LGD_REALZ_OS_BAL_AMT,
SUM(EAD_REALZ_DEFLTD_OS_BAL_AMT) AS EAD_REALZ_OS_BAL_AMT
FROM EDRRAPT.BASEL_CANDN_RTL_NCR_BE_FACT
WHERE MTH_TM_ID = &MTH_TM_ID. AND ECONMC_CAPTL_AMT IS NULL /* &MTH_TM_ID USED FOR 
TESTING */
GROUP BY CUBE ( /*GROUP BY CUBE USED HERE */
NCR_RISK_RT_SYS_ID,
EXPSR_CL_ID,
NCR_PD_SEG_ID,
NCR_LGD_SEG_ID,
NCR_EAD_SEG_ID);
);
DISCONNECT FROM DB3CON;
QUIT;

***
GROUP BY
NCR_RISK_RT_SYS_ID,
EXPSR_CL_ID,
NCR_PD_SEG_ID,
NCR_LGD_SEG_ID,
NCR_EAD_SEG_ID
);
QUIT;

/*STEP 2 OF BSTM*/
/*UPDATE MASTER TABLE CREATED IN STEP 1 WITH VALID VALUES EXTRACTED AT THE 
BEGINNING OF THE MACRO THUS REPLACING NULL VALUES*/
DATA &INPATH.._temp_backtest_first;
SET &INPATH.._temp_backtest_first;
IF NCR_RISK_RT_SYS_ID=. THEN DO; NCR_RISK_RT_SYS_ID=&V_NCR_RISK_RT_SYS_ID; END;
IF EXPSR_CL_ID=. THEN DO; EXPSR_CL_ID=&V_EXPSR_CL_ID; END;
IF NCR_PD_SEG_ID=. THEN DO; NCR_PD_SEG_ID=&V_NCR_PD_SEG_ID; END;
IF NCR_LGD_SEG_ID=. THEN DO; NCR_LGD_SEG_ID=&V_NCR_LGD_SEG_ID; END;
IF NCR_EAD_SEG_ID=. THEN DO; NCR_EAD_SEG_ID=&V_NCR_EAD_SEG_ID; END;
RUN;
/*STEP 3 OF BSTM*/
/*CREATE A TABLE WITH DISTINCT EXPOSURE CLASS ID AND LGD SEGMENT ID WITH LEAST 
LGD AVERAGE RATIO FROM MASTER TABLE CREATED IN STEP 1*/
PROC SQL NOPRINT;
CREATE TABLE &INPATH.._temp_backtest_second AS 
SELECT EXPSR_CL_ID, NCR_LGD_SEG_ID, MIN(LGD_ESTD_AVG_RTO) AS 
UPD_LGD_ESTD_AVG_RTO FROM &INPATH.._temp_backtest_first
WHERE EXPSR_CL_ID<>&V_EXPSR_CL_ID AND NCR_LGD_SEG_ID<>&V_NCR_LGD_SEG_ID AND 
ACCT_CNT>0
GROUP BY EXPSR_CL_ID, NCR_LGD_SEG_ID;
QUIT;
/*UPDATE THE MASTER TABLE WITH DATA IN TABLE CREATED ABOVE USING MATCHED 
MERGING BUT ONLY FOR THOSE RECORDS WHERE ACCT_CNT = 0*/
PROC SQL NOPRINT;
UPDATE &INPATH.._temp_backtest_first AS A SET LGD_ESTD_AVG_RTO=(SELECT 
UPD_LGD_ESTD_AVG_RTO FROM &INPATH.._temp_backtest_second AS B
WHERE A.EXPSR_CL_ID=B.EXPSR_CL_ID AND A.NCR_LGD_SEG_ID=B.NCR_LGD_SEG_ID AND 
A.ACCT_CNT=0)
WHERE A.EXPSR_CL_ID IN (SELECT EXPSR_CL_ID FROM 
&INPATH.._temp_backtest_second) AND 
A.NCR_LGD_SEG_ID IN (SELECT NCR_LGD_SEG_ID FROM 
&INPATH.._temp_backtest_second)
AND A.ACCT_CNT=0;
QUIT;
/*STEP 4 OF BSTM*/
/*CREATE A TABLE WITH DISTINCT EXPOSURE CLASS ID AND EAD SEGMENT ID WITH LEAST 
EAD AVERAGE RATIO FROM MASTER TABLE CREATED IN STEP 1*/
PROC SQL NOPRINT;
CREATE TABLE &INPATH.._temp_backtest_third AS 
SELECT EXPSR_CL_ID, NCR_EAD_SEG_ID, MIN(EAD_ESTD_AVG_RTO) AS 
UPD_EAD_ESTD_AVG_RTO FROM &INPATH.._temp_backtest_first
WHERE EXPSR_CL_ID<>&V_EXPSR_CL_ID AND NCR_EAD_SEG_ID<>&V_NCR_EAD_SEG_ID AND 
ACCT_CNT>0
GROUP BY EXPSR_CL_ID, NCR_EAD_SEG_ID;
QUIT;
/*UPDATE THE MASTER TABLE WITH DATA IN TABLE CREATED ABOVE USING MATCHED 
MERGING BUT ONLY FOR THOSE RECORDS WHERE ACCT_CNT = 0*/
PROC SQL NOPRINT;
UPDATE &INPATH.._temp_backtest_first AS A SET EAD_ESTD_AVG_RTO=(SELECT 
UPD_EAD_ESTD_AVG_RTO FROM &INPATH.._temp_backtest_third AS B
WHERE A.EXPSR_CL_ID=B.EXPSR_CL_ID AND A.NCR_EAD_SEG_ID=B.NCR_EAD_SEG_ID AND 
A.ACCT_CNT=0)
WHERE A.EXPSR_CL_ID IN (SELECT EXPSR_CL_ID FROM &INPATH.._temp_backtest_third) 
AND 
A.NCR_EAD_SEG_ID IN (SELECT NCR_EAD_SEG_ID FROM &INPATH.._temp_backtest_third)
AND A.ACCT_CNT=0;
QUIT;
/*ADD MONTH_TM_ID TO THE FINAL RESULT. THIS PREVENTS USE OF MACRO VARIABLES IN 
INSERT STATEMENT BELOW THUS PREVENTING DB2 LOAD ERRORS*/
DATA &INPATH.._temp_backtest_first;
SET &INPATH.._temp_backtest_first;
MTH_TM_ID=&MTH_TM_ID;
FORMAT MTH_TM_ID 8.;
RUN;
/*INSERT FINAL RESULT INTO THE DB2 TARGET TABLE*/
PROC SQL NOPRINT;
INSERT INTO edrrapt.BASEL_NCR_BACK_TESTNG_FACT 
SELECT MTH_TM_ID, 
NCR_RISK_RT_SYS_ID,
EXPSR_CL_ID,
NCR_PD_SEG_ID,
NCR_LGD_SEG_ID,
NCR_EAD_SEG_ID,
ACCT_CNT,
PD_ESTD_AVG_RTO,
LGD_ESTD_AVG_RTO,
EAD_ESTD_AVG_RTO,
NON_DEFLTD_PREV_12_MTH_ACCT_CNT,
LGD_CALC_PREV_36_MTH_ACCT_CNT,
EVER_DEFLTD_PREV_12_MTH_ACCT_CNT,
PD_REALZ_RTO,
LGD_REALZ_RTO,
EAD_REALZ_RTO,
PD_DEFLTD_PREV_12_MTH_ACCT_CNT,
LGD_DEFLTD_PREV_36_MTH_ACCT_CNT,
EAD_EVER_DF_PREV_12_MTH_ACCT_CNT,
PD_REALZ_OS_BAL_AMT,
LGD_REALZ_OS_BAL_AMT,
EAD_REALZ_OS_BAL_AMT,
&SESSIONTIME AS INSRT_PROCESS_TMSTMP,
&SESSIONTIME AS UPDT_PROCESS_TMSTMP
FROM &INPATH.._temp_backtest_first;
QUIT;
/*END OF MACRO*/
%MEND;
/*EXECUTE THE MACRO*/
%basel_ncr_back_testing_fact;


%datalog;
%PUT 
PROCESSING MONTH IS &MTH_TM_ID 
YEARMONTH IS &YEARMONTH 
PRELOAD DATA COUNT IN TARGET FOR &MTH_TM_ID IS &PRELOAD_DATA_COUNT 
&INPUT00. COUNT IS &SRCCOUNT00 
&TGT00. COUNT IS &TGTCOUNT00 ;

%SAS_DATASET_CLEANUP(LIBREF=INPATH,DATASETS=_temp_backtest_first _temp_backtest_second _temp_backtest_third);

%exitetls_conditionW36PM3VD:
%mend etls_conditionW36PM3VD;

%etls_conditionW36PM3VD;

%PUT etls_endTime = %sysfunc(datetime(),datetime.);
