%rrap_autoexec(RRAPENV=REVOLVING_CREDIT);
%put &=MTH_TM_ID;
%put &=YEARMONTH;
%LET CONNECTION_STRING=%STR(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
%PUT &=CONNECTION_STRING;
/*----STEP 1 TAKING BACKUP OF BASEL_PSNL_LOAN_MTH_SNAPSHOT table only for current month
				which has raw data from EDL------ */
%macro temp;
	%if %sysfunc(exist(NZRRAP.BASEL_PSNL_LN_MTH_SNP_&YEARMONTH.)) %then %do;
		%PUT "Backup table exists";
		%put "the table name is BASEL_PSNL_LN_MTH_SNP_&YEARMONTH.";
		proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* FROM CONNECTION TO IIASCON 
(		DELETE FROM &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT WHERE mth_tm_id in (&MTH_TM_ID,-&MTH_TM_ID)
);
quit;
proc sql;

proc sql;
	CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* FROM CONNECTION TO IIASCON 
(		insert into &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT 
		 SELECT * FROM &net_db..BASEL_PSNL_LN_MTH_SNP_&YEARMONTH. where MTH_TM_ID=&MTH_TM_ID
);
quit;
		
	%end;
	%else %do;
		%put "Backup table does not exist";
		%put "Creating the table";
		proc sql;
 			create table NZRRAP.BASEL_PSNL_LN_MTH_SNP_&YEARMONTH. as
			SELECT * FROM NZRRAP.BASEL_PSNL_LOAN_MTH_SNAPSHOT WHERE 1=2; 
		quit;
		proc sql;
		 insert into NZRRAP.BASEL_PSNL_LN_MTH_SNP_&YEARMONTH. (BULKLOAD = YES BL_METHOD=CLILOAD)
		 SELECT * FROM NZRRAP.BASEL_PSNL_LOAN_MTH_SNAPSHOT where MTH_TM_ID=&MTH_TM_ID ; 
		quit;
	%end;
%mend temp;
%temp
/* STEP 2 Updating BASEL_PSNL_LOAN_MTH_SNAPSHOT with -MTH_TM_ID for set of SLP records which 
	which are still coming from EDL(Source Team), This step will avoid having duplicate set of SL records*/
%LET CONNECTION_STRING=%STR(DATABASE=BLUDBPRD authdomain="IIAS_Auth");
%PUT &=CONNECTION_STRING;

/* PRE VALIDATION FOR STEP2: BEFORE UPDATE */ 
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* INTO: TOTAL_PRESLCOUNT
FROM CONNECTION TO IIASCON 
(SELECT count(*) FROM (
SELECT DISTINCT SL_LOAN_NO AS ACCT_NUM FROM &net_db..RLP_TO_SL_ACCT_LIST) a INNER JOIN &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT C
ON TRIM(L '0' FROM (C.TRNST_NUM||C.LOAN_NUM)) = TRIM(L '0' FROM A.ACCT_NUM)
WHERE c.MTH_TM_ID=&MTH_TM_ID);
quit;
%PUT " PRE STEP: &TOTAL_PRESLCOUNT NUMBER OF RECORDS THAT WOULD BE UPDATED to -&MTH_TM_ID AS PART OF STEP:2";

/* UPDATE FOR STEP 2 */
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING); 
EXECUTE
(
UPDATE &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT E
SET E.MTH_TM_ID=%EVAL(0-&MTH_TM_ID),
	e.UPDT_PROCESS_TMSTMP=NOW
from(
SELECT 
DISTINCT SL_LOAN_NO AS ACCT_NUM
FROM &net_db..RLP_TO_SL_ACCT_LIST) D WHERE TRIM(L '0' FROM D.ACCT_NUM)=TRIM(L '0' FROM (E.TRNST_NUM||E.LOAN_NUM))
AND E.MTH_TM_ID=&MTH_TM_ID)BY IIASCON;
DISCONNECT FROM IIASCON;
quit; 
/* POST UPDATE VALIDATION FOR STEP 2 */
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* INTO: TOTAL_POSTSLPCOUNT
FROM CONNECTION TO IIASCON 
(SELECT count(*) FROM &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT C
WHERE c.MTH_TM_ID=-&MTH_TM_ID);
quit;
%PUT "POST STEP: &TOTAL_POSTSLPCOUNT NUMBER OF RECORDS UPDATED to -&MTH_TM_ID AS PART OF STEP:2";
/* STEP 3: TO UPDATE RLP ACCOUNTS IN SNAPSHOT WITH ORIGINAL_BASEL_ACCT_ID */

/* PRE VALIDATION FOR STEP3: BEFORE UPDATE */ 
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* INTO: TOTAL_PRERLCOUNT
FROM CONNECTION TO IIASCON 
(SELECT count(*) FROM (
SELECT DISTINCT RLP_LOAN_NO AS ACCT_NUM FROM &net_db..RLP_TO_SL_ACCT_LIST) a INNER JOIN &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT C
ON TRIM(L '0' FROM (C.TRNST_NUM||C.LOAN_NUM)) = TRIM(L '0' FROM A.ACCT_NUM)
WHERE c.MTH_TM_ID=&MTH_TM_ID);
quit;
%PUT " PRE STEP: &TOTAL_PRERLCOUNT NUMBER OF RECORDS THAT WOULD BE UPDATED STEP:3";

/* UPDATE FOR STEP 3 */
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING); 
EXECUTE
(
UPDATE &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT E
SET E.BASEL_ACCT_ID=D.ORIG_BASEL_ACCT_ID,
e.UPDT_PROCESS_TMSTMP=NOW
from
(
SELECT 
DISTINCT A.RLP_LOAN_NO AS ACCT_NUM
,A.ORIG_BASEL_ACCT_ID AS ORIG_BASEL_ACCT_ID
FROM &net_db..RLP_TO_SL_ACCT_LIST a
) D WHERE TRIM(L '0' FROM (E.TRNST_NUM||E.LOAN_NUM))=TRIM(L '0' FROM D.ACCT_NUM)
AND E.MTH_TM_ID=&MTH_TM_ID)BY IIASCON;
DISCONNECT FROM IIASCON;
%PUT "RECORDS UPDATED IN SNAPSHOT FOR RLP ACCOUNTS WITH ORIG_BASEL_ACCT_ID FROM STATIC TABLE &net_db..RLP_TO_SL_ACCT_LIST ";
quit;

/* POST VALIDATION FOR STEP3: AFTER UPDATE */ 
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* INTO: TOTAL_POSTRLPCOUNT
FROM CONNECTION TO IIASCON 
(SELECT count(*) FROM (
SELECT DISTINCT RLP_LOAN_NO AS ACCT_NUM,ORIG_BASEL_ACCT_ID AS ORIG_BASEL_ACCT_ID
FROM &net_db..RLP_TO_SL_ACCT_LIST) a INNER JOIN &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT C
ON TRIM(L '0' FROM (C.TRNST_NUM||C.LOAN_NUM)) = TRIM(L '0' FROM A.ACCT_NUM) AND A.ORIG_BASEL_ACCT_ID=C.BASEL_ACCT_ID  
WHERE c.MTH_TM_ID=&MTH_TM_ID);
quit;
%PUT " POST STEP: &TOTAL_POSTRLPCOUNT NUMBER OF RECORDS THAT WAS UPDATED IN STEP:3";

/* STEP 4: TO UPDATE ALL RLP ACCOUNTS WITH VALUES FROM SL ACCOUNT USING THE STATIC TABLE (RLP_TO_SL_ACCT_LIST) */

/* PRE VALIDATION FOR STEP4: BEFORE UPDATE */ 
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* INTO: TOTAL_PRERLUPDATE
FROM CONNECTION TO IIASCON 
(SELECT count(*) FROM (
SELECT DISTINCT RLP_LOAN_NO AS ACCT_NUM,ORIG_BASEL_ACCT_ID AS ORIG_BASEL_ACCT_ID
FROM &net_db..RLP_TO_SL_ACCT_LIST) a INNER JOIN &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT C
ON TRIM(L '0' FROM (C.TRNST_NUM||C.LOAN_NUM)) = TRIM(L '0' FROM A.ACCT_NUM) AND C.BASEL_ACCT_ID=A.ORIG_BASEL_ACCT_ID
WHERE c.MTH_TM_ID=&MTH_TM_ID);
quit;
%PUT " PRE STEP: &TOTAL_PRERLUPDATE NUMBER OF RECORDS THAT WOULD BE UPDATED STEP:4";

/* UPDATE FOR STEP 4 */
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING); 
EXECUTE
(
UPDATE &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT E
SET e.TRNST_NUM=d.old_trnst_num
,e.LOAN_NUM=d.old_loan_num
,e.MOTOR_VEHCL_VAL=d.MOTOR_VEHCL_VAL
 	,e.LOAN_VAL_OTH=d.LOAN_VAL_OTH
 	,e.PRPS_CD=d.PRPS_CD
 	,e.CRNT_BR_LOCTN_TRNST=d.CRNT_BR_LOCTN_TRNST
	,e.SCRTY_CD=d.SCRTY_CD
,e.UPDT_PROCESS_TMSTMP=NOW
FROM
( SELECT 
A.RLP_LOAN_NO AS ACCT_NUM
,SUBSTRING( trim(a.SL_LOAN_NO), 1, 5 ) AS old_trnst_num
,SUBSTRING( trim(a.SL_LOAN_NO), 6, 7 ) AS old_loan_num
,A.MOTOR_VEHCL_VAL AS MOTOR_VEHCL_VAL
,A.LOAN_VAL_OTH AS LOAN_VAL_OTH
,A.PRPS_CD AS PRPS_CD
,A.CRNT_BR_LOCTN_TRNST AS CRNT_BR_LOCTN_TRNST
,a.SCRTY_CD as SCRTY_CD
,A.ORIG_BASEL_ACCT_ID AS ORIG_BASEL_ACCT_ID
FROM &net_db..RLP_TO_SL_ACCT_LIST a
) D 
WHERE TRIM(L '0' FROM (E.TRNST_NUM||E.LOAN_NUM))=TRIM(L '0' FROM D.ACCT_NUM)
AND E.BASEL_ACCT_ID=D.ORIG_BASEL_ACCT_ID
AND E.MTH_TM_ID=&MTH_TM_ID)BY IIASCON;
DISCONNECT FROM IIASCON;
%PUT "RECORDS UPDATED IN SNAPSHOT FOR RLP ACCOUNTS WITH TRNST_NUM,LOAN_NUM,MOTOR_VEHCL_VAL,LOAN_VAL_OTH,PRPS_CD
CRNT_BR_LOCTN_TRNST,SCRTY_CD FROM STATIC TABLE &net_db..RLP_TO_SL_ACCT_LIST ";
quit;

/* POST VALIDATION FOR STEP4: AFTER UPDATE */ 
proc sql;
/*CONNECT TO IIAS AS IIASCON(DATABASE=BLUDBPRD authdomain="IIAS_Auth"); */
CONNECT TO DB2 AS IIASCON(&CONNECTION_STRING);
SELECT 
* INTO: TOTAL_POSTRLPCOUNT
FROM CONNECTION TO IIASCON 
(SELECT count(*) FROM (
SELECT DISTINCT SL_LOAN_NO AS ACCT_NUM,ORIG_BASEL_ACCT_ID AS ORIG_BASEL_ACCT_ID
FROM &net_db..RLP_TO_SL_ACCT_LIST) a INNER JOIN &net_db..BASEL_PSNL_LOAN_MTH_SNAPSHOT C
ON TRIM(L '0' FROM (C.TRNST_NUM||C.LOAN_NUM)) = TRIM(L '0' FROM A.ACCT_NUM) AND C.BASEL_ACCT_ID=A.ORIG_BASEL_ACCT_ID
WHERE c.MTH_TM_ID=&MTH_TM_ID);
quit;
%PUT " POST STEP: &TOTAL_POSTRLPCOUNT NUMBER OF RECORDS THAT WAS UPDATED IN STEP:4";

%MACRO SECUREMAIL1;
FILENAME OUTMAIL EMAIL
SUBJECT= "RLP to SLP Summary Email : &YEARMONTH."
FROM= "RMSS";
DATA _NULL_;
FILE OUTMAIL
TO=("ganeshbhagwan.patro@scotiabank.com" "michelle.kao@scotiabank.com" "nikhilarun.gaikwad@scotiabank.com" "nimrat.grewal@scotiabank.com")
BCC=("dhaivat.patel@scotiabank.com");
PUT "Hi,";
PUT " ";
PUT "Please see below summary results for RL to SL conversion of accounts";
PUT "The month time id for this run is &MTH_TM_ID.";
PUT " ";
PUT "1. Backup Table: BASEL_PSNL_LN_MTH_SNP_&YEARMONTH.";
PUT "2. PRE STEP: &TOTAL_PRESLCOUNT NUMBER OF RECORDS THAT WOULD BE UPDATED to -&MTH_TM_ID";
PUT "3. POST STEP: &TOTAL_POSTSLPCOUNT NUMBER OF RECORDS UPDATED to -&MTH_TM_ID";
PUT "4. PRE STEP: &TOTAL_PRERLCOUNT RLP ACCOUNTS TO BE UPDATED WITH ORIGINAL BASEL_ACCT_ID";
PUT "5. POST STEP: &TOTAL_POSTRLPCOUNT RLP ACCOUNTS GOT UPDATED WITH ORIGINAL BASEL_ACCT_ID";
PUT "6. PRE STEP: &TOTAL_PRERLUPDATE RLP ACCOUNTS WILL BE CONVERTED WITH SL TRANSIT, LOAN and other columns 
from Static Table (&net_db..RLP_TO_SL_ACCT_LIST) ";
PUT "7. POST STEP: &TOTAL_POSTRLPCOUNT NUMBER OF RLP RECORDS THAT WAS UPDATED TO SL ACCOUNTS";
PUT "Please note: This is a system generated email and responses aren't monitored.";
run;
%MEND SECUREMAIL1;
%SECUREMAIL1;