/***************************************************************************
Deployment Date: AUG 16, 2024
CHANGE TICKET: CHG0900152
JIRA: RRMSS-2993/RRMSS-3055
CHANGE: CREATE NEW TABLE/VIEW IN IIAS PROD.


/****************************************************************************/

/****************** New PIT STATUS Table ***********************/
/* PLEASE ADD HIDDEN COLUMNS */
/* THIS TABLE DOES NOT HAVE TO BE REPLICATED */

CREATE TABLE EDRTLRP1D.STEP_DEF_ACCT_POST_CCAR_RMA(
	PROCESS_DATE DATE,
	MTH_TM_ID DECIMAL(11,0),
	BASEL_ACCT_ID DECIMAL(20,0),
	MORT_NUM DECIMAL(20,0),
	PROD_TYPE VARCHAR(6),
	STEP_PIT_STATUS VARCHAR(3),
	PD_BAND VARCHAR(10),
	EAD_FINAL_RPTG_RTO DECIMAL(11,0),
	NCR_PD_BAND_KEY_VAL VARCHAR(4),
	SRC_SYS_CD VARCHAR(3))
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MTH_TM_ID);
COMMIT;