/***************************************************************************
Deployment Date: MARCH 11  2023, 7:00 AM to 11:00 PM
CHANGE TICKET: CHG0648110
CHANGE: Basel III CHANGES
Note: No dependency
/****************************************************************************/

/************* DT4_RW_INSURER Instructions ***********************/
--1. Back Up EDRTLRP1D.DT4_RW_INSURER  
create table EDRTLRP1D.DT4_RW_INSURER_bkup as (select * from EDRTLRP1D.DT4_RW_INSURER) with data; commit;

--2. Create new table
drop table EDRTLRP1D.DT4_RW_INSURER if exists; commit;
CREATE TABLE EDRTLRP1D.DT4_RW_INSURER (
		NAME VARCHAR(4 OCTETS), 
		RW_INSURER DOUBLE, 
		IG_CODE VARCHAR(4 OCTETS), 
		PD DOUBLE, 
		LGD DOUBLE, 
		RW_INSURER_A1 DOUBLE, 
		CORRELATION_PMI DOUBLE, 
		MATURITY_ADJUSTMENT_PMI	 DOUBLE, 	
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (NAME, EFF_FROM_YR_MTH); COMMIT;
	
--3. Insert data from backup table into new STRUCTURE
insert into EDRTLRP1D.DT4_RW_INSURER
SELECT 
NAME,
RW_INSURER, 
NULL as IG_CODE, 
NULL as PD, 
NULL as LGD, 
NULL as RW_INSURER_A1, 
NULL as CORRELATION_PMI, 
NULL as MATURITY_ADJUSTMENT_PMI, 
EFF_FROM_YR_MTH, 
EFF_TO_YR_MTH, 
CRNT_F, 
INSRT_PROCESS_TMSTMP, 
UPDT_PROCESS_TMSTMP 
FROM 
EDRTLRP1D.DT4_RW_INSURER_bkup;

/*******************************************************************************************/ 
/****************** INSTRUMENT FACT CHANGES ************************************************/

-- STEP 1. TAKE BACKUPS OF FOLLOWING TABLES IN IIAS DR

1. EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT -> EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT_BKP_MAR11
2. FRG_USER_DATA.BASEL_ANALYTCL_BL_INST_FCT_BNS 	/* No need to backup with data - only table structure required for backup*/
3. FRG_USER_DATA.BASEL_ANLYT_BL_INST_FCT_BNS_DLGD
4. FRG_USER_DATA.BASEL_ANALYTCL_BL_INST_FCT_TNG     /* No need to backup with data - only table structure required for backup */
5. FRG_USER_DATA.BASEL_ANLYT_BL_INST_FCT_TNG_DLGD
6. FRG_USER_DATA.BASEL_ANALYTCL_BL_INSTRMNT_FACT 	/* No need to backup with data - only table structure required for backup */
7. EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS -> EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS_BKP_MAR11
8. EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP 			/* No need to backup with data - only table structure required for backup*/
9. EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP 			/* No need to backup with data - only table structure required for backup */

-- STEP 2: RUN SQLs TO ADD COLUMNS TO INSTRUMENT FACT TABLES 
-- Make sure backups have been taken in Step 1 

/* NOT REQUIRED */
-- FOR 2 TABLES, ALTER STATEMENT DOES NOT WORK DUE TO COLUMN ORGANIZED -
	-- A. HAVE TO DROP AND RE-CREATE THE TABLES AS ROW-ORGANIZED
	-- B. COPY DATA FROM BACKUPS TO NEW TABLES 
	-- C. RUN ALTER STATEMENTS

/*
DROP TABLE EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT;
DROP TABLE EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS;

CREATE TABLE EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT(
	MTH_TM_ID INTEGER NOT NULL,
	SRC_SYS_CD CHARACTER(10) NOT NULL,
	BASEL_ACCT_ID BIGINT NOT NULL,
	UNQ_ACCT_ID CHARACTER(30),
	NCR_RT_SYS_KEY_VAL CHARACTER(4),
	NCR_PD_BAND_KEY_VAL CHARACTER(4),
	NCR_EXPSR_SIZE_KEY_VAL CHARACTER(4),
	NCR_GEO_KEY_VAL CHARACTER(4),
	NCR_LTV_KEY_VAL CHARACTER(4),
	NCR_EXPSR_CL_KEY_VAL CHARACTER(4),
	NCR_RT_KEY_VAL CHARACTER(4),
	NCR_DLQNT_BCKT_KEY_VAL CHARACTER(4),
	PIT_STAT_CD CHARACTER(10),
	UTLTN_RTO DECIMAL(20,8),
	ACCT_ODT DATE,
	TRNST_NUM CHARACTER(5),
	CR_LMT_AMT DECIMAL(20,8),
	ADVNC_AMT DECIMAL(20,8),
	AUTH_AMT DECIMAL(28,8),
	OS_BAL_AMT DECIMAL(17,3),
	GENL_LEDGER_BALCNG_ADJ_AMT DECIMAL(17,3),
	ADJUSTED_OS_BAL_AMT DECIMAL(20,8),
	UNADJUSTED_ADD_ON_BAL_AMT DECIMAL(17,3),
	AF_SECRTZTN_BAL_AMT DECIMAL(28,8),
	DLQNT_DAY_CNT SMALLINT,
	BEFORE_ZERO_NET_UNDRAWN_AMT DECIMAL(17,3),
	BEFORE_ZERO_NET_DRAWN_AMT DECIMAL(17,3),
	ORIG_PRPTY_VAL_AMT DECIMAL(17,3),
	LOAN_TO_VAL_RTO DECIMAL(20,8),
	INDEXED_PRPTY_VAL_AMT DECIMAL(20,8),
	INDEXED_LOAN_TO_VAL_RTO DECIMAL(20,8),
	PD_MODEL_NM CHARACTER(40),
	PD_MODEL_VER CHARACTER(10),
	PD_BASEL_SCORECRD_NM CHARACTER(40),
	PD_SCORECRD_VER CHARACTER(10),
	PD_BASEL_SEG_NUM INTEGER,
	PD_BASEL_SEG_ID INTEGER,
	PD_SEG_VER CHARACTER(10),
	PD_BASEL_MODEL_REL_ID INTEGER,
	PD_MODEL_RTO DECIMAL(28,8),
	PD_LR_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	PD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	PD_ACCT_SCORE SMALLINT,
	PD_FINAL_RPTG_RTO DECIMAL(28,8),
	LGD_MODEL_NM CHARACTER(40),
	LGD_MODEL_VER CHARACTER(10),
	LGD_BASEL_SCORECRD_NM CHARACTER(40),
	LGD_SCORECRD_VER CHARACTER(10),
	LGD_BASEL_SEG_NUM INTEGER,
	LGD_BASEL_SEG_ID INTEGER,
	LGD_SEG_VER CHARACTER(10),
	LGD_BASEL_MODEL_REL_ID INTEGER,
	LGD_MODEL_RTO DECIMAL(28,8),
	LGD_LR_RPTG_RTO DECIMAL(28,8),
	LGD_LR_PV_RPTG_RTO DECIMAL(28,8),
	LGD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	LGD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	LGD_ACCT_SCORE SMALLINT,
	LGD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(28,8),
	EAD_MODEL_NM CHARACTER(40),
	EAD_MODEL_VER CHARACTER(10),
	LGD_FINAL_RPTG_RTO DECIMAL(28,8),
	EAD_BASEL_SCORECRD_NM CHARACTER(40),
	EAD_SCORECRD_VER CHARACTER(10),
	EAD_BASEL_SEG_NUM INTEGER,
	EAD_BASEL_SEG_ID INTEGER,
	EAD_SEG_VER CHARACTER(10),
	EAD_BASEL_MODEL_REL_ID INTEGER,
	EAD_MODEL_RTO DECIMAL(28,8),
	EAD_LR_RPTG_RTO DECIMAL(28,8),
	EAD_LR_PV_RPTG_RTO DECIMAL(28,8),
	EAD_ACCT_SCORE SMALLINT,
	EAD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	ASST_CL_DESC VARCHAR(255),
	CONS_DFT_MTH_CNT SMALLINT,
	EAD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	EAD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(28,8),
	BCAR_SCHED_NUM CHARACTER(3),
	EAD_FINAL_RPTG_RTO DECIMAL(28,8),
	PD_BAND CHARACTER(10),
	BASEL_PRD_ABR VARCHAR(50),
	SCRTY_TP_DESC VARCHAR(50),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	CCAR_EXPSR_CL_NM CHARACTER(20),
	BASEL_PRD_TP_CD CHARACTER(10),
	CONSM_PRD_TREATMNT_CD CHARACTER(10),
	PRD_ID CHARACTER(10),
	PRIM_CUST_CID CHARACTER(20),
	ACCT_NUM CHARACTER(23),
	RGNL_OFFC_CD CHARACTER(5),
	DLQNT_STG CHARACTER(10),
	MORT_NUM CHARACTER(50),
	CAB_TRNST_NUM CHARACTER(5),
	EGL_DEPRTMNT VARCHAR(255),
	BASEL_CIF_KEY CHARACTER(68),
	LOAN_NUM CHARACTER(15),
	INTR_ACCR_AMT DECIMAL(17,3),
	CUST_BEHV_SCORE INTEGER,
	PRD_CD CHARACTER(10),
	SUB_PRD_CD CHARACTER(10),
	SRC_PRD_DESC VARCHAR(255),
	LEGAL_ENTITY CHARACTER(40),
	MAT_DT DATE,
	LAST_PYMT_DT DATE,
	SCRTY_TP_CD CHARACTER(10),
	STEP_F CHARACTER(1),
	LAST_ACTY_DT DATE,
	HOUSE_TP_NM CHARACTER(20),
	LAST_RGL_PAY_DT DATE,
	PD_OFF_F CHARACTER(1),
	PD_OFF_DT DATE,
	RESIDUAL_MAT INTEGER,
	ASST_CL_NUM SMALLINT,
	E_MAT_DT DATE,
	AMORT DECIMAL(17,3),
	TRNST_EXCLSN_F CHARACTER(1),
	SML_BUS_F CHARACTER(1),
	NOTE_DT DATE,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	AF_ZERO_NET_DRAWN_AMT DECIMAL(17,3),
	AF_ZERO_NET_UNDRAWN_AMT DECIMAL(17,3),
	PD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	LGD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	EAD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	LGD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	EAD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	INSUR_F CHARACTER(10),
	OS_PRNCPL_BAL_AMT DECIMAL(17,3),
	PREV_12_QTR_PRPTY_VAL_AMT DECIMAL(20,8),
	DLGD_F CHARACTER(1) NOT NULL,
	CRNT_LTV_RTO DECIMAL(30,20),
	METRPL_AREA_NM VARCHAR(32),
	PRPTY_VAL_CORR_PCTG DECIMAL(11,4),
	LNG_RUN_LGD_ADD_ON_RTO DECIMAL(28,8),
	DLGD_RPTG_RTO DECIMAL(28,8),
	LTV_PERCENTAGE VARCHAR(4)
) DISTRIBUTE BY HASH("BASEL_ACCT_ID") ORGANIZE BY ROW; 


CREATE TABLE EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS (
	MTH_TM_ID INTEGER NOT NULL,
	SRC_SYS_CD CHARACTER(10) NOT NULL,
	BASEL_ACCT_ID BIGINT NOT NULL,
	UNQ_ACCT_ID CHARACTER(30),
	NCR_RT_SYS_KEY_VAL CHARACTER(4),
	NCR_PD_BAND_KEY_VAL CHARACTER(4),
	NCR_EXPSR_SIZE_KEY_VAL CHARACTER(4),
	NCR_GEO_KEY_VAL CHARACTER(4),
	NCR_LTV_KEY_VAL CHARACTER(4),
	NCR_EXPSR_CL_KEY_VAL CHARACTER(4),
	NCR_RT_KEY_VAL CHARACTER(4),
	NCR_DLQNT_BCKT_KEY_VAL CHARACTER(4),
	PIT_STAT_CD CHARACTER(10),
	UTLTN_RTO DECIMAL(20,8),
	ACCT_ODT DATE,
	TRNST_NUM CHARACTER(5),
	CR_LMT_AMT DECIMAL(20,8),
	ADVNC_AMT DECIMAL(20,8),
	AUTH_AMT DECIMAL(28,8),
	OS_BAL_AMT DECIMAL(17,3),
	GENL_LEDGER_BALCNG_ADJ_AMT DECIMAL(17,3),
	ADJUSTED_OS_BAL_AMT DECIMAL(20,8),
	UNADJUSTED_ADD_ON_BAL_AMT DECIMAL(17,3),
	AF_SECRTZTN_BAL_AMT DECIMAL(28,8),
	DLQNT_DAY_CNT SMALLINT,
	BEFORE_ZERO_NET_UNDRAWN_AMT DECIMAL(17,3),
	BEFORE_ZERO_NET_DRAWN_AMT DECIMAL(17,3),
	ORIG_PRPTY_VAL_AMT DECIMAL(17,3),
	LOAN_TO_VAL_RTO DECIMAL(20,8),
	INDEXED_PRPTY_VAL_AMT DECIMAL(20,8),
	INDEXED_LOAN_TO_VAL_RTO DECIMAL(20,8),
	PD_MODEL_NM CHARACTER(40),
	PD_MODEL_VER CHARACTER(10),
	PD_BASEL_SCORECRD_NM CHARACTER(40),
	PD_SCORECRD_VER CHARACTER(10),
	PD_BASEL_SEG_NUM INTEGER,
	PD_BASEL_SEG_ID INTEGER,
	PD_SEG_VER CHARACTER(10),
	PD_BASEL_MODEL_REL_ID INTEGER,
	PD_MODEL_RTO DECIMAL(28,8),
	PD_LR_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	PD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	PD_ACCT_SCORE SMALLINT,
	PD_FINAL_RPTG_RTO DECIMAL(28,8),
	LGD_MODEL_NM CHARACTER(40),
	LGD_MODEL_VER CHARACTER(10),
	LGD_BASEL_SCORECRD_NM CHARACTER(40),
	LGD_SCORECRD_VER CHARACTER(10),
	LGD_BASEL_SEG_NUM INTEGER,
	LGD_BASEL_SEG_ID INTEGER,
	LGD_SEG_VER CHARACTER(10),
	LGD_BASEL_MODEL_REL_ID INTEGER,
	LGD_MODEL_RTO DECIMAL(28,8),
	LGD_LR_RPTG_RTO DECIMAL(28,8),
	LGD_LR_PV_RPTG_RTO DECIMAL(28,8),
	LGD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	LGD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	LGD_ACCT_SCORE SMALLINT,
	LGD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(28,8),
	EAD_MODEL_NM CHARACTER(40),
	EAD_MODEL_VER CHARACTER(10),
	LGD_FINAL_RPTG_RTO DECIMAL(28,8),
	EAD_BASEL_SCORECRD_NM CHARACTER(40),
	EAD_SCORECRD_VER CHARACTER(10),
	EAD_BASEL_SEG_NUM INTEGER,
	EAD_BASEL_SEG_ID INTEGER,
	EAD_SEG_VER CHARACTER(10),
	EAD_BASEL_MODEL_REL_ID INTEGER,
	EAD_MODEL_RTO DECIMAL(28,8),
	EAD_LR_RPTG_RTO DECIMAL(28,8),
	EAD_LR_PV_RPTG_RTO DECIMAL(28,8),
	EAD_ACCT_SCORE SMALLINT,
	EAD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	ASST_CL_DESC VARCHAR(255),
	CONS_DFT_MTH_CNT SMALLINT,
	EAD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	EAD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(28,8),
	BCAR_SCHED_NUM CHARACTER(3),
	EAD_FINAL_RPTG_RTO DECIMAL(28,8),
	PD_BAND CHARACTER(10),
	BASEL_PRD_ABR VARCHAR(50),
	SCRTY_TP_DESC VARCHAR(50),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	CCAR_EXPSR_CL_NM CHARACTER(20),
	BASEL_PRD_TP_CD CHARACTER(10),
	CONSM_PRD_TREATMNT_CD CHARACTER(10),
	PRD_ID CHARACTER(10),
	PRIM_CUST_CID CHARACTER(20),
	ACCT_NUM CHARACTER(23),
	RGNL_OFFC_CD CHARACTER(5),
	DLQNT_STG CHARACTER(10),
	MORT_NUM CHARACTER(50),
	CAB_TRNST_NUM CHARACTER(5),
	EGL_DEPRTMNT VARCHAR(255),
	BASEL_CIF_KEY CHARACTER(68),
	LOAN_NUM CHARACTER(15),
	INTR_ACCR_AMT DECIMAL(17,3),
	CUST_BEHV_SCORE INTEGER,
	PRD_CD CHARACTER(10),
	SUB_PRD_CD CHARACTER(10),
	SRC_PRD_DESC VARCHAR(255),
	LEGAL_ENTITY CHARACTER(40),
	MAT_DT DATE,
	LAST_PYMT_DT DATE,
	SCRTY_TP_CD CHARACTER(10),
	STEP_F CHARACTER(1),
	LAST_ACTY_DT DATE,
	HOUSE_TP_NM CHARACTER(20),
	LAST_RGL_PAY_DT DATE,
	PD_OFF_F CHARACTER(1),
	PD_OFF_DT DATE,
	RESIDUAL_MAT INTEGER,
	ASST_CL_NUM SMALLINT,
	E_MAT_DT DATE,
	AMORT DECIMAL(17,3),
	TRNST_EXCLSN_F CHARACTER(1),
	SML_BUS_F CHARACTER(1),
	NOTE_DT DATE,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	AF_ZERO_NET_DRAWN_AMT DECIMAL(17,3),
	AF_ZERO_NET_UNDRAWN_AMT DECIMAL(17,3),
	PD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	LGD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	EAD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	LGD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	EAD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	INSUR_F CHARACTER(10),
	OS_PRNCPL_BAL_AMT DECIMAL(17,3),
	PREV_12_QTR_PRPTY_VAL_AMT DECIMAL(20,8),
	DLGD_F CHARACTER(1) NOT NULL,
	CRNT_LTV_RTO DECIMAL(30,20),
	METRPL_AREA_NM VARCHAR(32),
	PRPTY_VAL_CORR_PCTG DECIMAL(11,4),
	LNG_RUN_LGD_ADD_ON_RTO DECIMAL(28,8),
	DLGD_RPTG_RTO DECIMAL(28,8),
	LTV_PERCENTAGE VARCHAR(4)
) DISTRIBUTE BY HASH("BASEL_ACCT_ID") ORGANIZE BY ROW; 

-- COPY DATA FROM BACKUPS 
INSERT INTO EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT SELECT * FROM EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT_BKP_MAR11;
INSERT INTO EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS SELECT * FROM EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS_BKP_MAR11;
*/

/* ADD NEW COLUMNS */

ALTER TABLE EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

ALTER TABLE FRG_USER_DATA.BASEL_ANALYTCL_BL_INST_FCT_BNS
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN CLP_FLAG CHAR(1);

ALTER TABLE FRG_USER_DATA.BASEL_ANLYT_BL_INST_FCT_BNS_DLGD
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

	
ALTER TABLE FRG_USER_DATA.BASEL_ANALYTCL_BL_INST_FCT_TNG
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN CLP_FLAG CHAR(1);

ALTER TABLE FRG_USER_DATA.BASEL_ANLYT_BL_INST_FCT_TNG_DLGD
ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);
	
ALTER TABLE FRG_USER_DATA.BASEL_ANALYTCL_BL_INSTRMNT_FACT
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

ALTER TABLE EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

/* MAKE SURE TO REORG TABLES AFTER RUNNING ALTER STATEMENTS */

/********************************************************************************/
--1. Back Up 
create table EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT_BKP_MAR10 as 
	(select * from EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT) with data; commit;

--2. Drop table 
	DROP TABLE EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT;

--3. Create new table
CREATE TABLE EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT (
	MTH_TM_ID INTEGER NOT NULL,
	SRC_SYS_CD CHARACTER(10) NOT NULL,
	BASEL_ACCT_ID BIGINT NOT NULL,
	UNQ_ACCT_ID CHARACTER(30),
	NCR_RT_SYS_KEY_VAL CHARACTER(4),
	NCR_PD_BAND_KEY_VAL CHARACTER(4),
	NCR_EXPSR_SIZE_KEY_VAL CHARACTER(4),
	NCR_GEO_KEY_VAL CHARACTER(4),
	NCR_LTV_KEY_VAL CHARACTER(4),
	NCR_EXPSR_CL_KEY_VAL CHARACTER(4),
	NCR_RT_KEY_VAL CHARACTER(4),
	NCR_DLQNT_BCKT_KEY_VAL CHARACTER(4),
	PIT_STAT_CD CHARACTER(10),
	UTLTN_RTO DECIMAL(20,8),
	ACCT_ODT DATE,
	TRNST_NUM CHARACTER(5),
	CR_LMT_AMT DECIMAL(20,8),
	ADVNC_AMT DECIMAL(20,8),
	AUTH_AMT DECIMAL(28,8),
	OS_BAL_AMT DECIMAL(17,3),
	GENL_LEDGER_BALCNG_ADJ_AMT DECIMAL(17,3),
	ADJUSTED_OS_BAL_AMT DECIMAL(20,8),
	UNADJUSTED_ADD_ON_BAL_AMT DECIMAL(17,3),
	AF_SECRTZTN_BAL_AMT DECIMAL(28,8),
	DLQNT_DAY_CNT SMALLINT,
	BEFORE_ZERO_NET_UNDRAWN_AMT DECIMAL(17,3),
	BEFORE_ZERO_NET_DRAWN_AMT DECIMAL(17,3),
	ORIG_PRPTY_VAL_AMT DECIMAL(17,3),
	LOAN_TO_VAL_RTO DECIMAL(20,8),
	INDEXED_PRPTY_VAL_AMT DECIMAL(20,8),
	INDEXED_LOAN_TO_VAL_RTO DECIMAL(20,8),
	PD_MODEL_NM CHARACTER(40),
	PD_MODEL_VER CHARACTER(10),
	PD_BASEL_SCORECRD_NM CHARACTER(40),
	PD_SCORECRD_VER CHARACTER(10),
	PD_BASEL_SEG_NUM INTEGER,
	PD_BASEL_SEG_ID INTEGER,
	PD_SEG_VER CHARACTER(10),
	PD_BASEL_MODEL_REL_ID INTEGER,
	PD_MODEL_RTO DECIMAL(28,8),
	PD_LR_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	PD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	PD_ACCT_SCORE SMALLINT,
	PD_FINAL_RPTG_RTO DECIMAL(28,8),
	LGD_MODEL_NM CHARACTER(40),
	LGD_MODEL_VER CHARACTER(10),
	LGD_BASEL_SCORECRD_NM CHARACTER(40),
	LGD_SCORECRD_VER CHARACTER(10),
	LGD_BASEL_SEG_NUM INTEGER,
	LGD_BASEL_SEG_ID INTEGER,
	LGD_SEG_VER CHARACTER(10),
	LGD_BASEL_MODEL_REL_ID INTEGER,
	LGD_MODEL_RTO DECIMAL(28,8),
	LGD_LR_RPTG_RTO DECIMAL(28,8),
	LGD_LR_PV_RPTG_RTO DECIMAL(28,8),
	LGD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	LGD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	LGD_ACCT_SCORE SMALLINT,
	LGD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(28,8),
	EAD_MODEL_NM CHARACTER(40),
	EAD_MODEL_VER CHARACTER(10),
	LGD_FINAL_RPTG_RTO DECIMAL(28,8),
	EAD_BASEL_SCORECRD_NM CHARACTER(40),
	EAD_SCORECRD_VER CHARACTER(10),
	EAD_BASEL_SEG_NUM INTEGER,
	EAD_BASEL_SEG_ID INTEGER,
	EAD_SEG_VER CHARACTER(10),
	EAD_BASEL_MODEL_REL_ID INTEGER,
	EAD_MODEL_RTO DECIMAL(28,8),
	EAD_LR_RPTG_RTO DECIMAL(28,8),
	EAD_LR_PV_RPTG_RTO DECIMAL(28,8),
	EAD_ACCT_SCORE SMALLINT,
	EAD_LR_PV_AD_RPTG_RTO DECIMAL(28,8),
	ASST_CL_DESC VARCHAR(255),
	CONS_DFT_MTH_CNT SMALLINT,
	EAD_LD_PV_AD_SV_RPTG_RTO DECIMAL(28,8),
	EAD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(28,8),
	BCAR_SCHED_NUM CHARACTER(3),
	EAD_FINAL_RPTG_RTO DECIMAL(28,8),
	PD_BAND CHARACTER(10),
	BASEL_PRD_ABR VARCHAR(50),
	SCRTY_TP_DESC VARCHAR(50),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	CCAR_EXPSR_CL_NM CHARACTER(20),
	BASEL_PRD_TP_CD CHARACTER(20),
	CONSM_PRD_TREATMNT_CD CHARACTER(10),
	PRD_ID CHARACTER(10),
	PRIM_CUST_CID CHARACTER(20),
	ACCT_NUM CHARACTER(23),
	RGNL_OFFC_CD CHARACTER(5),
	DLQNT_STG CHARACTER(10),
	MORT_NUM CHARACTER(50),
	CAB_TRNST_NUM CHARACTER(5),
	EGL_DEPRTMNT VARCHAR(255),
	BASEL_CIF_KEY CHARACTER(69),
	LOAN_NUM CHARACTER(15),
	INTR_ACCR_AMT DECIMAL(17,3),
	CUST_BEHV_SCORE INTEGER,
	PRD_CD CHARACTER(10),
	SUB_PRD_CD CHARACTER(10),
	SRC_PRD_DESC VARCHAR(255),
	LEGAL_ENTITY CHARACTER(40),
	MAT_DT DATE,
	LAST_PYMT_DT DATE,
	SCRTY_TP_CD CHARACTER(10),
	STEP_F CHARACTER(1),
	LAST_ACTY_DT DATE,
	HOUSE_TP_NM CHARACTER(20),
	LAST_RGL_PAY_DT DATE,
	PD_OFF_F CHARACTER(1),
	PD_OFF_DT DATE,
	RESIDUAL_MAT INTEGER,
	ASST_CL_NUM SMALLINT,
	E_MAT_DT DATE,
	AMORT DECIMAL(17,3),
	TRNST_EXCLSN_F CHARACTER(1),
	SML_BUS_F CHARACTER(1),
	NOTE_DT DATE,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	AF_ZERO_NET_DRAWN_AMT DECIMAL(17,3),
	AF_ZERO_NET_UNDRAWN_AMT DECIMAL(17,3),
	PD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	LGD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	EAD_UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	PD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	LGD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	EAD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	INSUR_F CHARACTER(10),
	OS_PRNCPL_BAL_AMT DECIMAL(20,8),
	PREV_12_QTR_PRPTY_VAL_AMT DECIMAL(20,8),
	DLGD_F CHARACTER(1) NOT NULL,
	CRNT_LTV_RTO DECIMAL(30,20),
	METRPL_AREA_NM VARCHAR(32),
	PRPTY_VAL_CORR_PCTG DECIMAL(11,4),
	LNG_RUN_LGD_ADD_ON_RTO DECIMAL(28,8),
	DLGD_RPTG_RTO DECIMAL(28,8),
	LTV_PERCENTAGE VARCHAR(4),
	RNTL_PRPTY_F CHARACTER(1),
	CURRENCY_MISMATCH_F CHARACTER(1),
	TOT_EXPSR_ABOVE_1500K_LMT_F CHARACTER(1),
	ORIG_AMT_LOAN DOUBLE,
	LTV_BUCKET VARCHAR(30),
	TRANSACTOR_F CHARACTER(1),
	PD_90_DAY_F VARCHAR(5),
	UNINSURED_LGD_SEG_NUM DOUBLE,
	UNINSURED_LGD_RTO DECIMAL(28,8),
	UNINSURED_DLGD_RTO DECIMAL(28,8),
	TRANSACTOR_FLAG_QRR VARCHAR(1),
	CCF DECIMAL(11,4),
	DRAWN DECIMAL(22,8),
	EAD_FLR DOUBLE,
	EAD_FLRD_RPTG_RTO DOUBLE,
	UNDRAWN DECIMAL(19,3),
	UNDRAWN_EXPSR_PCT DOUBLE,
	CMHC_F VARCHAR(1),
	DLGD_FLR DOUBLE,
	FULLY_SECURED_F VARCHAR(1),
	LGD_FLR DOUBLE,
	PRE_INSURANCE_LGD DOUBLE,
	PD_FLR DOUBLE,
	PD_FLRD_RPTG_RTO DOUBLE,
	LGD_FLRD_RPTG_RTO DOUBLE,
	PMI_LGD_INSURED_RPTG_RTO DOUBLE,
	PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29,8),
	UNINSURED_FLRD_LGD_RTO DOUBLE,
	PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4),
	DLGD_RPTG_RTO_OLD DECIMAL(29,8),
	CCAR_F INTEGER,
	CLP_FLAG CHAR(1),
	BCAR_SCHED_NM VARCHAR(150),
	BCAR_SCHED_NUM_50 VARCHAR(10),
	COLLATERAL_TYPE VARCHAR(50 OCTETS) ,
	H_C DECIMAL(11 , 6),
	LGD_S DECIMAL(11 , 6),
	LGD_U DECIMAL(11 , 6),
	H_E DECIMAL(11 , 6),
	COLLATERAL_VALUE DECIMAL(18 , 3),
	EXPOSURE DOUBLE,
	EXPOSURE_SECURED_MAXIMUM DOUBLE,
	EXPOSURE_SECURED DOUBLE,
	EXPOSURE_UNSECURED DOUBLE,
	WEIGHT_SECURED DOUBLE,
	WEIGHT_UNSECURED DOUBLE)
ORGANIZE BY COLUMN DISTRIBUTE BY HASH (BASEL_ACCT_ID); COMMIT;

-- 3. Copy from backup to New table
INSERT INTO EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT (MTH_TM_ID, SRC_SYS_CD, BASEL_ACCT_ID, UNQ_ACCT_ID, NCR_RT_SYS_KEY_VAL, NCR_PD_BAND_KEY_VAL, NCR_EXPSR_SIZE_KEY_VAL, NCR_GEO_KEY_VAL, NCR_LTV_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_RT_KEY_VAL, NCR_DLQNT_BCKT_KEY_VAL, PIT_STAT_CD, UTLTN_RTO, ACCT_ODT, TRNST_NUM, CR_LMT_AMT, ADVNC_AMT, AUTH_AMT, OS_BAL_AMT, GENL_LEDGER_BALCNG_ADJ_AMT, ADJUSTED_OS_BAL_AMT, UNADJUSTED_ADD_ON_BAL_AMT, AF_SECRTZTN_BAL_AMT, DLQNT_DAY_CNT, BEFORE_ZERO_NET_UNDRAWN_AMT, BEFORE_ZERO_NET_DRAWN_AMT, ORIG_PRPTY_VAL_AMT, LOAN_TO_VAL_RTO, INDEXED_PRPTY_VAL_AMT, INDEXED_LOAN_TO_VAL_RTO, PD_MODEL_NM, PD_MODEL_VER, PD_BASEL_SCORECRD_NM, PD_SCORECRD_VER, PD_BASEL_SEG_NUM, PD_BASEL_SEG_ID, PD_SEG_VER, PD_BASEL_MODEL_REL_ID, PD_MODEL_RTO, PD_LR_RPTG_RTO, PD_LR_PV_RPTG_RTO, PD_LR_PV_AD_RPTG_RTO, PD_LD_PV_AD_SV_RPTG_RTO, PD_ACCT_SCORE, PD_FINAL_RPTG_RTO, LGD_MODEL_NM, LGD_MODEL_VER, LGD_BASEL_SCORECRD_NM, LGD_SCORECRD_VER, LGD_BASEL_SEG_NUM, LGD_BASEL_SEG_ID, LGD_SEG_VER, LGD_BASEL_MODEL_REL_ID, LGD_MODEL_RTO, LGD_LR_RPTG_RTO, LGD_LR_PV_RPTG_RTO, LGD_LR_PV_AD_RPTG_RTO, LGD_LD_PV_AD_SV_RPTG_RTO, LGD_ACCT_SCORE, LGD_LD_PV_AD_SV_DT_RPTG_RTO, EAD_MODEL_NM, EAD_MODEL_VER, LGD_FINAL_RPTG_RTO, EAD_BASEL_SCORECRD_NM, EAD_SCORECRD_VER, EAD_BASEL_SEG_NUM, EAD_BASEL_SEG_ID, EAD_SEG_VER, EAD_BASEL_MODEL_REL_ID, EAD_MODEL_RTO, EAD_LR_RPTG_RTO, EAD_LR_PV_RPTG_RTO, EAD_ACCT_SCORE, EAD_LR_PV_AD_RPTG_RTO, ASST_CL_DESC, CONS_DFT_MTH_CNT, EAD_LD_PV_AD_SV_RPTG_RTO, EAD_LD_PV_AD_SV_DT_RPTG_RTO, BCAR_SCHED_NUM, EAD_FINAL_RPTG_RTO, PD_BAND, BASEL_PRD_ABR, SCRTY_TP_DESC, CCAR_BASEL_PRD_TP_NM, CCAR_EXPSR_CL_NM, BASEL_PRD_TP_CD, CONSM_PRD_TREATMNT_CD, PRD_ID, PRIM_CUST_CID, ACCT_NUM, RGNL_OFFC_CD, DLQNT_STG, MORT_NUM, CAB_TRNST_NUM, EGL_DEPRTMNT, BASEL_CIF_KEY, LOAN_NUM, INTR_ACCR_AMT, CUST_BEHV_SCORE, PRD_CD, SUB_PRD_CD, SRC_PRD_DESC, LEGAL_ENTITY, MAT_DT, LAST_PYMT_DT, SCRTY_TP_CD, STEP_F, LAST_ACTY_DT, HOUSE_TP_NM, LAST_RGL_PAY_DT, PD_OFF_F, PD_OFF_DT, RESIDUAL_MAT, ASST_CL_NUM, E_MAT_DT, AMORT, TRNST_EXCLSN_F, SML_BUS_F, NOTE_DT, INSRT_PROCESS_TMSTMP, UPDT_PROCESS_TMSTMP, AF_ZERO_NET_DRAWN_AMT, AF_ZERO_NET_UNDRAWN_AMT, PD_UNADJUSTED_RPTG_RTO, LGD_UNADJUSTED_RPTG_RTO, EAD_UNADJUSTED_RPTG_RTO, PD_LR_PV_AD_SV_DT_AA_RTO, LGD_LR_PV_AD_SV_DT_AA_RTO, EAD_LR_PV_AD_SV_DT_AA_RTO, INSUR_F, OS_PRNCPL_BAL_AMT, PREV_12_QTR_PRPTY_VAL_AMT, DLGD_F, CRNT_LTV_RTO, METRPL_AREA_NM, PRPTY_VAL_CORR_PCTG, LNG_RUN_LGD_ADD_ON_RTO, DLGD_RPTG_RTO, LTV_PERCENTAGE) 
SELECT MTH_TM_ID, SRC_SYS_CD, BASEL_ACCT_ID, UNQ_ACCT_ID, NCR_RT_SYS_KEY_VAL, NCR_PD_BAND_KEY_VAL, NCR_EXPSR_SIZE_KEY_VAL, NCR_GEO_KEY_VAL, NCR_LTV_KEY_VAL, NCR_EXPSR_CL_KEY_VAL, NCR_RT_KEY_VAL, NCR_DLQNT_BCKT_KEY_VAL, PIT_STAT_CD, UTLTN_RTO, ACCT_ODT, TRNST_NUM, CR_LMT_AMT, ADVNC_AMT, AUTH_AMT, OS_BAL_AMT, GENL_LEDGER_BALCNG_ADJ_AMT, ADJUSTED_OS_BAL_AMT, UNADJUSTED_ADD_ON_BAL_AMT, AF_SECRTZTN_BAL_AMT, DLQNT_DAY_CNT, BEFORE_ZERO_NET_UNDRAWN_AMT, BEFORE_ZERO_NET_DRAWN_AMT, ORIG_PRPTY_VAL_AMT, LOAN_TO_VAL_RTO, INDEXED_PRPTY_VAL_AMT, INDEXED_LOAN_TO_VAL_RTO, PD_MODEL_NM, PD_MODEL_VER, PD_BASEL_SCORECRD_NM, PD_SCORECRD_VER, PD_BASEL_SEG_NUM, PD_BASEL_SEG_ID, PD_SEG_VER, PD_BASEL_MODEL_REL_ID, PD_MODEL_RTO, PD_LR_RPTG_RTO, PD_LR_PV_RPTG_RTO, PD_LR_PV_AD_RPTG_RTO, PD_LD_PV_AD_SV_RPTG_RTO, PD_ACCT_SCORE, PD_FINAL_RPTG_RTO, LGD_MODEL_NM, LGD_MODEL_VER, LGD_BASEL_SCORECRD_NM, LGD_SCORECRD_VER, LGD_BASEL_SEG_NUM, LGD_BASEL_SEG_ID, LGD_SEG_VER, LGD_BASEL_MODEL_REL_ID, LGD_MODEL_RTO, LGD_LR_RPTG_RTO, LGD_LR_PV_RPTG_RTO, LGD_LR_PV_AD_RPTG_RTO, LGD_LD_PV_AD_SV_RPTG_RTO, LGD_ACCT_SCORE, LGD_LD_PV_AD_SV_DT_RPTG_RTO, EAD_MODEL_NM, EAD_MODEL_VER, LGD_FINAL_RPTG_RTO, EAD_BASEL_SCORECRD_NM, EAD_SCORECRD_VER, EAD_BASEL_SEG_NUM, EAD_BASEL_SEG_ID, EAD_SEG_VER, EAD_BASEL_MODEL_REL_ID, EAD_MODEL_RTO, EAD_LR_RPTG_RTO, EAD_LR_PV_RPTG_RTO, EAD_ACCT_SCORE, EAD_LR_PV_AD_RPTG_RTO, ASST_CL_DESC, CONS_DFT_MTH_CNT, EAD_LD_PV_AD_SV_RPTG_RTO, EAD_LD_PV_AD_SV_DT_RPTG_RTO, BCAR_SCHED_NUM, EAD_FINAL_RPTG_RTO, PD_BAND, BASEL_PRD_ABR, SCRTY_TP_DESC, CCAR_BASEL_PRD_TP_NM, CCAR_EXPSR_CL_NM, BASEL_PRD_TP_CD, CONSM_PRD_TREATMNT_CD, PRD_ID, PRIM_CUST_CID, ACCT_NUM, RGNL_OFFC_CD, DLQNT_STG, MORT_NUM, CAB_TRNST_NUM, EGL_DEPRTMNT, BASEL_CIF_KEY, LOAN_NUM, INTR_ACCR_AMT, CUST_BEHV_SCORE, PRD_CD, SUB_PRD_CD, SRC_PRD_DESC, LEGAL_ENTITY, MAT_DT, LAST_PYMT_DT, SCRTY_TP_CD, STEP_F, LAST_ACTY_DT, HOUSE_TP_NM, LAST_RGL_PAY_DT, PD_OFF_F, PD_OFF_DT, RESIDUAL_MAT, ASST_CL_NUM, E_MAT_DT, AMORT, TRNST_EXCLSN_F, SML_BUS_F, NOTE_DT, INSRT_PROCESS_TMSTMP, UPDT_PROCESS_TMSTMP, AF_ZERO_NET_DRAWN_AMT, AF_ZERO_NET_UNDRAWN_AMT, PD_UNADJUSTED_RPTG_RTO, LGD_UNADJUSTED_RPTG_RTO, EAD_UNADJUSTED_RPTG_RTO, PD_LR_PV_AD_SV_DT_AA_RTO, LGD_LR_PV_AD_SV_DT_AA_RTO, EAD_LR_PV_AD_SV_DT_AA_RTO, INSUR_F, OS_PRNCPL_BAL_AMT, PREV_12_QTR_PRPTY_VAL_AMT, DLGD_F, CRNT_LTV_RTO, METRPL_AREA_NM, PRPTY_VAL_CORR_PCTG, LNG_RUN_LGD_ADD_ON_RTO, DLGD_RPTG_RTO, LTV_PERCENTAGE 
FROM EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT_BKP_MAR10;

/**************************************************************/
drop table EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP;
drop table EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP;

CREATE TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP(
	LEGAL_ENTITY VARCHAR(40),
	PD_BAND VARCHAR(10),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	MTH_TM_ID DOUBLE,
	LGD_BASEL_SEG_NUM DOUBLE,
	EAD_BASEL_SEG_NUM DOUBLE,
	PD_BASEL_SEG_NUM DOUBLE,
	PD_BASEL_SEG_ID DOUBLE,
	LGD_BASEL_SEG_ID DOUBLE,
	EAD_BASEL_SEG_ID DOUBLE,
	PD_90_DAY_F VARCHAR(1),
	BEFR_ZERO_NET_ADJ_OS_BAL_AMT DOUBLE,
	AF_ZERO_NET_ADJUSTED_OS_BAL_AMT DOUBLE,
	EXPCTD_LOSS_RTO DOUBLE,
	BEFORE_ZERO_NET_UNDRAWN_AMT DOUBLE,
	AF_ZERO_NET_UNDRAWN_AMT DOUBLE,
	BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	AF_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	LGD_FLRD_RPTG_RTO DOUBLE,
	EAD_FLRD_RPTG_RTO DOUBLE,
	CRNCY_CD VARCHAR(10),
	PRTL_WRITE_OFF_AMT DOUBLE,
	UNCONDTNLY_CNCLBL VARCHAR(10),
	ACCR_INTR_AMT DOUBLE,
	INSRT_PROCESS_TMSTMP DOUBLE,
	UPDT_PROCESS_TMSTMP DOUBLE,
	INSUR_F VARCHAR(10),
	WGHTD_DLGD_RTO DOUBLE,
	LTV_PERCENTAGE VARCHAR(30),
	OBLIGORS DOUBLE,
	PERIOD_IND VARCHAR(4),
	ECL_DRAWN_1 DOUBLE,
	ECL_DRAWN_2 DOUBLE,
	ECL_DRAWN_3 DOUBLE,
	ECL_UNDRAWN_1 DOUBLE,
	ECL_UNDRAWN_2 DOUBLE,
	ECL_UNDRAWN_3 DOUBLE,
	ECL_DRAWN_POSTSEC_1 DOUBLE,
	ECL_DRAWN_POSTSEC_2 DOUBLE,
	ECL_DRAWN_POSTSEC_3 DOUBLE,
	TRNST_NUM VARCHAR(5),
	EGL_DEPRTMNT VARCHAR(255),
	PRD_ID VARCHAR(10),
	RNTL_PRPTY_F CHAR(1),
	CURRENCY_MISMATCH_F CHAR(1),
	TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1),
	ORIG_AMT_LOAN DOUBLE,
	TRANSACTOR_FLAG_QRR CHAR(1),
	DEFAULT_F CHAR(1),
	UNINSURED_FLRD_LGD_RTO DOUBLE,
	UNINSURED_DLGD_RTO DOUBLE,
	BASEL_ACCT_ID DOUBLE,
	PMI CHAR(1));
	
CREATE TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP(
	MTH_END_DT DATE,
	LEGAL_ENTITY VARCHAR(40),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	PD_BAND VARCHAR(10),
	UNQ_RECD_ID VARCHAR(20),
	PD_BASEL_SEG_NUM DOUBLE,
	LGD_BASEL_SEG_NUM DOUBLE,
	EAD_BASEL_SEG_NUM DOUBLE,
	PD_90_DAY_F VARCHAR(5),
	BEFR_ZERO_NET_ADJ_OS_BAL_AMT DOUBLE,
	AF_ZERO_NET_ADJUSTED_OS_BAL_AMT DOUBLE,
	EXPCTD_LOSS_RTO_TEXT VARCHAR(18),
	BEFORE_ZERO_NET_UNDRAWN_AMT DOUBLE,
	AF_ZERO_NET_UNDRAWN_AMT DOUBLE,
	BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	AF_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	LGD_FINAL_RPTG_RTO_TEXT VARCHAR(18),
	EAD_FINAL_RPTG_RTO_TEXT VARCHAR(18),
	EAD_PC VARCHAR(15),
	CRNCY_CD VARCHAR(10),
	PRTL_WRITE_OFF_AMT DOUBLE,
	UNCONDTNLY_CNCLBL VARCHAR(10),
	ACCR_INTR_AMT DOUBLE,
	PERIOD_IND VARCHAR(4),
	ECL_DRAWN_1 DOUBLE,
	ECL_DRAWN_2 DOUBLE,
	ECL_DRAWN_3 DOUBLE,
	ECL_UNDRAWN_1 DOUBLE,
	ECL_UNDRAWN_2 DOUBLE,
	ECL_UNDRAWN_3 DOUBLE,
	ECL_DRAWN_POSTSEC_1 DOUBLE,
	ECL_DRAWN_POSTSEC_2 DOUBLE,
	ECL_DRAWN_POSTSEC_3 DOUBLE,
	INSRT_PROCESS_TMSTMP DECIMAL(31,8),
	UPDT_PROCESS_TMSTMP DECIMAL(31,8),
	INSUR_F VARCHAR(10),
	WGHTD_DLGD_RTO DECIMAL(23,8),
	LTV_PERCENTAGE VARCHAR(30),
	OBLIGORS DECIMAL(21,0),
	TRNST_NUM VARCHAR(5),
	PRD_ID VARCHAR(10),
	EGL_DEPRTMNT VARCHAR(5),
	RNTL_PRPTY_F CHARACTER(1),
	CURRENCY_MISMATCH_F CHARACTER(1),
	TOT_EXPSR_ABOVE_1500K_LMT_F CHARACTER(1),
	ORIG_AMT_LOAN DOUBLE,
	TRANSACTOR_FLAG_QRR CHARACTER(1),
	DEFAULT_F VARCHAR(5),
	UNINSURED_FLRD_LGD_RTO VARCHAR(22),
	UNINSURED_DLGD_RTO DECIMAL(22,8),
	BASEL_ACCT_ID BIGINT,
	PMI CHARACTER(1));	

/************************************* END OF SCRIPT *******************************************************/