/***************************************************************************
Deployment Date: MARCH 10  2023, 7:00 AM to 11:00 PM
CHANGE TICKET: CHG0648057
CHANGE: REPORTING PARAMETER
NOTE: 
/****************************************************************************/

/* ENSURE TABLES ARE CREATED WITHOUT PRIMARY KEYS */
	-- EDRTLRP1D.BASEL_SEG_RPTG_PARM 
	-- EDRTLRBTWRKP1D.BASEL_SEG_RPTG_PARM

-- DEACTIVATING DELETED SEGMENTS 

UPDATE EDRTLRP1D.basel_Seg_rptg_parm 
SET EFF_TO_DT = '2023-01-31', 
	CRNT_F = 'N'
WHERE 
	BASEL_SEG_ID NOT IN (SELECT BASEL_SEG_ID FROM EDRTLRP1D.BASEL_SEG) AND EFF_TO_DT = '9999-12-31';


-- COPY THE PARAMETER TO BACKTESTING

DELETE FROM EDRTLRBTWRKP1D.BASEL_SEG_RPTG_PARM;

INSERT INTO EDRTLRBTWRKP1D.BASEL_SEG_RPTG_PARM
	SELECT * FROM EDRTLRP1D.BASEL_SEG_RPTG_PARM WHERE CRNT_F='Y';
	
UPDATE EDRTLRBTWRKP1D.BASEL_SEG_RPTG_PARM
SET EFF_FROM_DT = '2000-01-01';
