-- CHANGE TICKET: CHG0649665 
--  DATE: MAR 13, 2023 

/***************************************************************
SPL TABLE CHANGES
****************************************************************/

-- STEP 1: ENSURE BACKUP FROM MAR 11 DEPLOYMENT EXISTS FOR TABLE EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT (COLUMN ORGANIZED) WITHOUT THE NEW COLUMNS LISTED IN STEP 4

-- STEP 2: DROP TABLE 
DROP TABLE EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT;

-- STEP 3: RE-CREATE TABLE FROM BACKUP WITH DATA (ENSURE THIS IS COLUMN ORGANIZED)

-- STEP 4: ADD NEW COLUMNS 
ALTER TABLE EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT
	ADD COLUMN LTV_PERCENTAGE VARCHAR(4)
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

/*****************************************************************
CCAR TABLE CHANGES
/*****************************************************************/

-- STEP 1: ENSURE BACKUPS ARE PRESENT AS PART OF MAR 11 DEPLOYMENT 
EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP;
EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP;

-- STEP 2: DROP AND CREATE TABLES
drop table EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP;
drop table EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP;

CREATE TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP(
	LEGAL_ENTITY VARCHAR(40),
	PD_BAND VARCHAR(10),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	MTH_TM_ID DOUBLE,
	LGD_BASEL_SEG_NUM DOUBLE,
	EAD_BASEL_SEG_NUM DOUBLE,
	PD_BASEL_SEG_NUM DOUBLE,
	PD_BASEL_SEG_ID DOUBLE,
	LGD_BASEL_SEG_ID DOUBLE,
	EAD_BASEL_SEG_ID DOUBLE,
	PD_90_DAY_F VARCHAR(1),
	BEFR_ZERO_NET_ADJ_OS_BAL_AMT DOUBLE,
	AF_ZERO_NET_ADJUSTED_OS_BAL_AMT DOUBLE,
	EXPCTD_LOSS_RTO DOUBLE,
	BEFORE_ZERO_NET_UNDRAWN_AMT DOUBLE,
	AF_ZERO_NET_UNDRAWN_AMT DOUBLE,
	BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	AF_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	LGD_FLRD_RPTG_RTO DOUBLE,
	EAD_FLRD_RPTG_RTO DOUBLE,
	CRNCY_CD VARCHAR(10),
	PRTL_WRITE_OFF_AMT DOUBLE,
	UNCONDTNLY_CNCLBL VARCHAR(10),
	ACCR_INTR_AMT DOUBLE,
	INSRT_PROCESS_TMSTMP DOUBLE,
	UPDT_PROCESS_TMSTMP DOUBLE,
	INSUR_F VARCHAR(10),
	WGHTD_DLGD_RTO DOUBLE,
	LTV_PERCENTAGE VARCHAR(30),
	OBLIGORS DOUBLE,
	PERIOD_IND VARCHAR(4),
	ECL_DRAWN_1 DOUBLE,
	ECL_DRAWN_2 DOUBLE,
	ECL_DRAWN_3 DOUBLE,
	ECL_UNDRAWN_1 DOUBLE,
	ECL_UNDRAWN_2 DOUBLE,
	ECL_UNDRAWN_3 DOUBLE,
	ECL_DRAWN_POSTSEC_1 DOUBLE,
	ECL_DRAWN_POSTSEC_2 DOUBLE,
	ECL_DRAWN_POSTSEC_3 DOUBLE,
	TRNST_NUM VARCHAR(5),
	EGL_DEPRTMNT VARCHAR(255),
	PRD_ID VARCHAR(10),
	RNTL_PRPTY_F CHAR(1),
	CURRENCY_MISMATCH_F CHAR(1),
	TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1),
	ORIG_AMT_LOAN DOUBLE,
	TRANSACTOR_FLAG_QRR CHAR(1),
	DEFAULT_F CHAR(1),
	UNINSURED_FLRD_LGD_RTO DOUBLE,
	UNINSURED_DLGD_RTO DOUBLE,
	BASEL_ACCT_ID DOUBLE,
	PMI CHAR(1));
	
CREATE TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP(
	MTH_END_DT DATE,
	LEGAL_ENTITY VARCHAR(40),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	PD_BAND VARCHAR(10),
	UNQ_RECD_ID VARCHAR(20),
	PD_BASEL_SEG_NUM DOUBLE,
	LGD_BASEL_SEG_NUM DOUBLE,
	EAD_BASEL_SEG_NUM DOUBLE,
	PD_90_DAY_F VARCHAR(5),
	BEFR_ZERO_NET_ADJ_OS_BAL_AMT DOUBLE,
	AF_ZERO_NET_ADJUSTED_OS_BAL_AMT DOUBLE,
	EXPCTD_LOSS_RTO_TEXT VARCHAR(18),
	BEFORE_ZERO_NET_UNDRAWN_AMT DOUBLE,
	AF_ZERO_NET_UNDRAWN_AMT DOUBLE,
	BEFR_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	AF_ZERO_NET_ALWBL_CR_LOSS_AMT DOUBLE,
	LGD_FINAL_RPTG_RTO_TEXT VARCHAR(18),
	EAD_FINAL_RPTG_RTO_TEXT VARCHAR(18),
	EAD_PC VARCHAR(15),
	CRNCY_CD VARCHAR(10),
	PRTL_WRITE_OFF_AMT DOUBLE,
	UNCONDTNLY_CNCLBL VARCHAR(10),
	ACCR_INTR_AMT DOUBLE,
	PERIOD_IND VARCHAR(4),
	ECL_DRAWN_1 DOUBLE,
	ECL_DRAWN_2 DOUBLE,
	ECL_DRAWN_3 DOUBLE,
	ECL_UNDRAWN_1 DOUBLE,
	ECL_UNDRAWN_2 DOUBLE,
	ECL_UNDRAWN_3 DOUBLE,
	ECL_DRAWN_POSTSEC_1 DOUBLE,
	ECL_DRAWN_POSTSEC_2 DOUBLE,
	ECL_DRAWN_POSTSEC_3 DOUBLE,
	INSRT_PROCESS_TMSTMP DECIMAL(31,8),
	UPDT_PROCESS_TMSTMP DECIMAL(31,8),
	INSUR_F VARCHAR(10),
	WGHTD_DLGD_RTO DECIMAL(23,8),
	LTV_PERCENTAGE VARCHAR(30),
	OBLIGORS DECIMAL(21,0),
	TRNST_NUM VARCHAR(5),
	PRD_ID VARCHAR(10),
	EGL_DEPRTMNT VARCHAR(5),
	RNTL_PRPTY_F CHARACTER(1),
	CURRENCY_MISMATCH_F CHARACTER(1),
	TOT_EXPSR_ABOVE_1500K_LMT_F CHARACTER(1),
	ORIG_AMT_LOAN DOUBLE,
	TRANSACTOR_FLAG_QRR CHARACTER(1),
	DEFAULT_F VARCHAR(5),
	UNINSURED_FLRD_LGD_RTO VARCHAR(22),
	UNINSURED_DLGD_RTO DECIMAL(22,8),
	BASEL_ACCT_ID BIGINT,
	PMI CHARACTER(1));	
