import os
import pyarrow as pa
from airflow.sdk import get_current_context, task


@task
def create_sq034_rundir():
    """Create sq034 run directory."""
    context = get_current_context()
    rundir = context["ti"].xcom_pull(task_ids="handle_month_context", key="RUNDIR")
    sq034_rundir = f"{rundir}/sq034"
    os.makedirs(sq034_rundir, exist_ok=True)


@task.beeline(
    task_id="make_airb_tangrn_mort_acct",
    beeline_conn_id="edlr-conn",
    sql="""
        select
            date_format(current_timestamp, 'yyyy-MM-dd HH:mm:ss.SSSSSS') as INSRT_PROCESS_TMSTMP,
            cast(ACCT_ID as VARCHAR(80)) as ACCT_ID,
            cast(MTH_ST_DT as DATE) as MTH_ST_DT,
            '{{ task_instance.xcom_pull(task_ids="handle_month_context", key="MTH_END_DT") }}' as MTH_END_DT,
            cast(MATURITY_DT as DATE) as MAT_DT,
            cast(OPEN_DT as DATE) as OPN_DT,
            cast(COMMITTED_AMT as DECIMAL(22,2)) as COMMTTD_AMT,
            cast(INTR_ARRS_AMT as  DECIMAL(22,2)) as INTR_ARRS_AMT,
            cast(PRNCPL_ARRS_AMT as DECIMAL(22,2)) as PRNCPL_ARRS_AMT,
            cast(ESCROW_ARRS_AMT as DECIMAL(22,2)) as ESCROW_ARRS_AMT,
            cast(TOT_ARRS_AMT as DECIMAL(22,2)) as TOT_ARRS_AMT,
            cast(NOMINAL_INTR_RATE as DECIMAL(11,4)) as NOMNL_INTR_RT,
            cast(CRNT_LTV_RTO as DECIMAL(11,4)) as CRNT_LOAN_TO_VAL_RTO,
            cast(RMNG_TERM as INTEGER) as RMNG_TERM,
            cast(NON_PERFORMING_IND as VARCHAR(1)) as NON_PRFRMNG_IND,
            cast(NAL_IND as CHAR(1)) as NON_ACCRL_IND,
            cast(DAY_ARRS_CNT as INTEGER) as DAYS_ARRS_CNT,
            cast(PYMTS_ARRS_CNT as INTEGER) as PYMTS_ARRS_CNT,
            cast(NSF_CNT as INTEGER) as NSF_CNT,
            cast(NSF_YTD_CNT as INTEGER) as NSF_YTD_CNT,
            cast(NSF_LIFE_CNT as INTEGER) as NSF_LIFE_CNT,
            cast(ST_PRNCPL_BAL_AMT as DECIMAL(22,2)) as ST_PRNCPL_BAL_AMT,
            cast(OS_BAL_COA_AMT as DECIMAL(22,2)) as END_PRNCPL_BAL_AMT,
            cast(SUNDRY_BAL_AMT as DECIMAL(22,2)) as SUNDRY_BAL_AMT,
            cast(ESCROW_BAL_AMT as DECIMAL(22,2)) as ESCROW_BAL_AMT,
            cast(TOT_ADVNC_AMT as DECIMAL(22,2)) as TOT_ADVNC_AMT,
            cast(RMNG_AMORT as INTEGER) as RMNG_AMORT,
            cast(ACCT_KEY as BIGINT) as ACCT_KEY,
            cast(MORT_APPLICATION_KEY as BIGINT) as MORT_APP_KEY,
            cast(POOL_KEY as BIGINT) as POOL_KEY,
            cast(CUST_KEY as BIGINT) as CUST_KEY,
            cast(AMORT_DT as DATE) as AMORT_DT,
            cast(LAST_NSF_PYMT_RETURN_DT as DATE) as LAST_NSF_PYMT_RTN_DT,
            cast(LAST_PYMT_DT as DATE) as LAST_PYMT_DT,
            cast(NON_PERFORMING_DT as DATE) as NON_PRFRMNG_DT,
            cast(LATEST_90_DT_PST_DUE_DT as DATE) as LATEST_90_DT_PD_DT,
            cast(TOT_SCHED_PYMT_AMT as DECIMAL(22,2)) as TOT_SCHED_PYMT_AMT,
            cast(LAST_KNOWN_COVER_PCTG as DECIMAL(11,4)) as LAST_KNOWN_COVER_PCTG,
            cast(EVER_ARRS_CNT as INTEGER) as EVER_ARRS_CNT,
            cast(EVER_30_CNT_PST_DUE_CNT as INTEGER) as EVER_30_CNT_PD_CNT,
            cast(EVER_60_CNT_PST_DUE_CNT as INTEGER) as EVER_60_CNT_PD_CNT,
            cast(EVER_90_CNT_PST_DUE_CNT as INTEGER) as EVER_90_CNT_PD_CNT,
            cast(DEFLT_TYPE_CD as CHAR(20)) as DFT_TP_CD,
            cast(MORT_ORGNTN_KEY as BIGINT) as MORT_ORGNTN_KEY,
            cast(ORIG_TERM as INTEGER) as ORIG_TERM,
            cast(RATE_TYPE_DESC as VARCHAR(80)) as RT_TP_DESC,
            cast(ACCELERATED_PYMT_IND as VARCHAR(1)) as ACCELERATED_PYMT_IND,
            cast(ANNUAL_FACTR as DECIMAL(11,4)) as ANUL_FACTR,
            cast(MORT_PROVIDER_DESC as VARCHAR(255)) as MORT_PROVIDER_DESC,
            cast(PRPTY_TYPE_DESC as VARCHAR(255)) as PRPTY_TP_DESC,
            cast(TENURE_DESC as VARCHAR(255)) as TENURE_DESC,
            cast(STAT_DESC as VARCHAR(255)) as STAT_DESC,
            cast(INSURER_DESC as VARCHAR(255)) as INSURER_DESC,
            cast(POOL_DESC as VARCHAR(255)) as POOL_DESC,
            cast(PURPOSE_DESC as VARCHAR(255)) as PRPS_DESC,
            cast(OCCUPANCY_TYPE_DESC as VARCHAR(255)) as OCPNY_TP_DESC,
            cast(DWELLING_TYPE_CD as VARCHAR(20)) as DWELLING_TP_CD,
            cast(OCCUPATION_INDSTR_CD as VARCHAR(100)) as OCP_INDSTR_CD,
            cast(EARLY_RENEW_IND as VARCHAR(1)) as EARLY_RNEW_IND,
            cast(ORIG_ADJ_BUREAU_SCORE as INTEGER) as ORIG_ADJUSTED_BUREAU_SCORE,
            cast(SUBMIT_DT as DATE) as SUBMIT_DT,
            cast(ORIG_GDSR as DECIMAL(22,2)) as ORIG_GDSR,
            cast(ORIG_TDSR as DECIMAL(22,2)) as ORIG_TDSR,
            cast(FIRST_PYMT_RETURN_DT as DATE) as FRST_PYMT_RTN_DT,
            cast(FIRST_90_DAY_PST_DUE_DT as DATE) as FRST_90_DAYS_PD_DT,
            cast(GUAR_IND as VARCHAR(1)) as GRNT_IND,
            cast(ORIG_LTV_RTO as DECIMAL(11,4)) as ORIG_LOAN_TO_VAL_RTO,
            cast(AMORT_PERIOD as INTEGER) as AMORT_PRD,
            cast(ORIG_ADVNC_AMT as DECIMAL(22,2)) as ORIG_ADVNC_AMT,
            cast(DIRECT_IND as VARCHAR(1)) as DRC_IND,
            cast(FIRST_DEFLT_DT as DATE) as FRST_DFT_DT,
            cast(FIRST_ADVNC_DT as DATE) as FRST_ADVNC_DT,
            cast(LTV_RTO_AT_FIRST_DEFLT as DECIMAL(11,4)) as LTV_RTO_AT_FRST_DFT,
            cast(LATEST_INTR_ADJ_DT as DATE) as LATEST_INTR_ADJ_DT,
            cast(ADVNC_EFF_DT as DATE) as ADVNC_EFF_DT,
            cast(PRPTY_CITY as VARCHAR(255)) as PRPTY_CITY,
            cast(PRPTY_CNTRY_CD as VARCHAR(2)) as PRPTY_CNTRY_CD,
            cast(PRPTY_POSTAL_CD as VARCHAR(20)) as PRPTY_POST_CD,
            cast(PRPTY_PROV_CD as VARCHAR(2)) as PRPTY_PROV_CD,
            cast(LAST_PRPTY_APPRAISAL_VAL as DECIMAL(22,2)) as LAST_PRPTY_APPRSL_VAL,
            cast(FSA as VARCHAR(3)) as FSA,
            cast(LAST_PRPTY_APPRAISAL_DT as DATE) as LAST_PRPTY_APPRSL_DT,
            cast(LIEN_PRIORITY_NUM as INTEGER) as LIEN_PRIORITY_NUM,
            cast(PRPTY_BUILDNG_TYPE as VARCHAR(20)) as PRPTY_BUILDING_TP,
            cast(ORIG_COVER_EXEC_VAL as DECIMAL(22,2)) as ORIG_COVER_EXECUTION_VAL,
            cast(PRPTY_USAGE_TYPE as VARCHAR(20)) as PRPTY_USAGE_TP,
            cast(SCRTY_OWN_TYPE as VARCHAR(255)) as SCRTY_OWN_TP,
            cast(SCRTY_PROVIDER as VARCHAR(255)) as SCRTY_PROVIDER,
            cast(SCRTY_RGSTRN_BEGIN_DT as DATE) as SCRTY_RGSTRN_BEGIN_DT,
            cast(SCRTY_RGSTRN_END_DT as DATE) as SCRTY_RGSTRN_END_DT,
            cast(SCRTY_RGSTRN_NUM as VARCHAR(255)) as SCRTY_RGSTRN_NUM,
            cast(ASSET_TYPE_DESC as VARCHAR(255)) as ASST_TP_DESC,
            cast(ORIG_PRPTY_APPRAISAL_VAL as DECIMAL(22,2)) as ORIG_PRPTY_APPRSL_VAL,
            cast(ORIG_PRPTY_APPRAISAL_DT as DATE) as ORIG_PRPTY_APPRSL_DT,
            cast(PRPTY_PRCH_AMT as DECIMAL(22,2)) as PRPTY_PRCH_AMT,
            cast(PRPTY_PRCH_DT as DATE) as PRPTY_PRCH_DT,
            cast(ORIG_TOT_INCM as INTEGER) as ORIG_TOT_INCM,
            cast(PRNCPL_INTR_PYMT_AMT as DECIMAL(22,2)) as PRNCPL_INTR_PYMT_AMT,
            cast(NEXT_INTR_RESET_DT as DATE) as NEXT_INTR_RESET_DT,
            cast(RATE_MODIFIER as DECIMAL(11,4)) as RT_MODFR,
            cast(DOWN_PYMT_SRC_DESC as VARCHAR(255)) as DN_PYMT_SRC_DESC,
            cast(CLIENT_DT as DATE) as CLIENT_DT,
            cast(CIF_CREATED_ON_DT as DATE) as CIF_CREATD_ON_DT,
            cast(DEFLT_IND as VARCHAR(1)) as DFT_IND,
            cast(STATED_INCM_IND as VARCHAR(1)) as STATED_INCM_IND,
            cast(ACCR_INTR_AMT as DECIMAL(22,2)) as ACCR_INTR_AMT,
            cast(CLS_DT as DATE) as CLS_DT,
            cast(BULK_INSURER_DESC as VARCHAR(255)) as BULK_INSURER_DESC,
            cast(SECURITIZATION_IND as VARCHAR(1)) as SECRTZTN_IND,
            cast(CIF_TYPE_DESC as VARCHAR(255)) as CIF_TP_DESC,
            cast(CUST_TYPE_2 as VARCHAR(20)) as CUST_TP_2,
            cast(INTR_PYMTS_AMT as DECIMAL(22,2)) as INTR_PYMTS_AMT,
            cast(INTR_COMPOUNDING_FREQ as INTEGER) as INTR_CMPNDNG_FREQ,
            cast(OPEN_CLS_TERM as VARCHAR(6)) as OPN_CLSD_TERM,
            cast(PAYOUT_REASON as VARCHAR(6)) as PYT_RSN,
            cast(LAST_RENEW_DT as DATE) as LAST_RNEW_DT,
            cast(ACCT_NUM as VARCHAR(50)) as ACCT_NUM,
            cast(GL_ACCT_NUM as VARCHAR(7)) as GL_ACCT_NUM,
            cast(GL_ACCTNG_TRANSIT as VARCHAR(5)) as GL_TRNST_NUM,
            cast(CURRENCY_CD as VARCHAR(3)) as CRNCY_CD
        from
            {{ var.value.RCRR_SCHEMA }}.TNG_MORT_ACCT_MTH_SNAPSHOT as MAIN
        where
            MAIN.MTH_END_DT = '{{ task_instance.xcom_pull(task_ids="handle_month_context", key="MTH_END_DT") }}'
        ;
    """,
    rundir="{{ task_instance.xcom_pull(task_ids='handle_month_context', key='RUNDIR') }}/sq034",
    to_parquet=True,
    tmpfileloc="/bns/rrap/data/tmp",
    target="make_airb_tangrn_mort_acct.parquet",
    schema=pa.schema([
        ("INSRT_PROCESS_TMSTMP", pa.string()),
        ("ACCT_ID", pa.string()),
        ("MTH_ST_DT", pa.date64()),
        ("MTH_END_DT", pa.string()),
        ("MAT_DT", pa.date64()),
        ("OPN_DT", pa.date64()),
        ("COMMTTD_AMT", pa.float64()),
        ("INTR_ARRS_AMT", pa.float64()),
        ("PRNCPL_ARRS_AMT", pa.float64()),
        ("ESCROW_ARRS_AMT", pa.float64()),
        ("TOT_ARRS_AMT", pa.float64()),
        ("NOMNL_INTR_RT", pa.float64()),
        ("CRNT_LOAN_TO_VAL_RTO", pa.float64()),
        ("RMNG_TERM", pa.int64()),
        ("NON_PRFRMNG_IND", pa.string()),
        ("NON_ACCRL_IND", pa.string()),
        ("DAYS_ARRS_CNT", pa.int64()),
        ("PYMTS_ARRS_CNT", pa.int64()),
        ("NSF_CNT", pa.int64()),
        ("NSF_YTD_CNT", pa.int64()),
        ("NSF_LIFE_CNT", pa.int64()),
        ("ST_PRNCPL_BAL_AMT", pa.float64()),
        ("END_PRNCPL_BAL_AMT", pa.float64()),
        ("SUNDRY_BAL_AMT", pa.float64()),
        ("ESCROW_BAL_AMT", pa.float64()),
        ("TOT_ADVNC_AMT", pa.float64()),
        ("RMNG_AMORT", pa.int64()),
        ("ACCT_KEY", pa.int64()),
        ("MORT_APP_KEY", pa.int64()),
        ("POOL_KEY", pa.int64()),
        ("CUST_KEY", pa.int64()),
        ("AMORT_DT", pa.date64()),
        ("LAST_NSF_PYMT_RTN_DT", pa.date64()),
        ("LAST_PYMT_DT", pa.date64()),
        ("NON_PRFRMNG_DT", pa.date64()),
        ("LATEST_90_DT_PD_DT", pa.date64()),
        ("TOT_SCHED_PYMT_AMT", pa.float64()),
        ("LAST_KNOWN_COVER_PCTG", pa.float64()),
        ("EVER_ARRS_CNT", pa.int64()),
        ("EVER_30_CNT_PD_CNT", pa.int64()),
        ("EVER_60_CNT_PD_CNT", pa.int64()),
        ("EVER_90_CNT_PD_CNT", pa.int64()),
        ("DFT_TP_CD", pa.string()),
        ("MORT_ORGNTN_KEY", pa.int64()),
        ("ORIG_TERM", pa.int64()),
        ("RT_TP_DESC", pa.string()),
        ("ACCELERATED_PYMT_IND", pa.string()),
        ("ANUL_FACTR", pa.float64()),
        ("MORT_PROVIDER_DESC", pa.string()),
        ("PRPTY_TP_DESC", pa.string()),
        ("TENURE_DESC", pa.string()),
        ("STAT_DESC", pa.string()),
        ("INSURER_DESC", pa.string()),
        ("POOL_DESC", pa.string()),
        ("PRPS_DESC", pa.string()),
        ("OCPNY_TP_DESC", pa.string()),
        ("DWELLING_TP_CD", pa.string()),
        ("OCP_INDSTR_CD", pa.string()),
        ("EARLY_RNEW_IND", pa.string()),
        ("ORIG_ADJUSTED_BUREAU_SCORE", pa.int64()),
        ("SUBMIT_DT", pa.date64()),
        ("ORIG_GDSR", pa.float64()),
        ("ORIG_TDSR", pa.float64()),
        ("FRST_PYMT_RTN_DT", pa.date64()),
        ("FRST_90_DAYS_PD_DT", pa.date64()),
        ("GRNT_IND", pa.string()),
        ("ORIG_LOAN_TO_VAL_RTO", pa.float64()),
        ("AMORT_PRD", pa.int64()),
        ("ORIG_ADVNC_AMT", pa.float64()),
        ("DRC_IND", pa.string()),
        ("FRST_DFT_DT", pa.date64()),
        ("FRST_ADVNC_DT", pa.date64()),
        ("LTV_RTO_AT_FRST_DFT", pa.float64()),
        ("LATEST_INTR_ADJ_DT", pa.date64()),
        ("ADVNC_EFF_DT", pa.date64()),
        ("PRPTY_CITY", pa.string()),
        ("PRPTY_CNTRY_CD", pa.string()),
        ("PRPTY_POST_CD", pa.string()),
        ("PRPTY_PROV_CD", pa.string()),
        ("LAST_PRPTY_APPRSL_VAL", pa.float64()),
        ("FSA", pa.string()),
        ("LAST_PRPTY_APPRSL_DT", pa.date64()),
        ("LIEN_PRIORITY_NUM", pa.int64()),
        ("PRPTY_BUILDING_TP", pa.string()),
        ("ORIG_COVER_EXECUTION_VAL", pa.float64()),
        ("PRPTY_USAGE_TP", pa.string()),
        ("SCRTY_OWN_TP", pa.string()),
        ("SCRTY_PROVIDER", pa.string()),
        ("SCRTY_RGSTRN_BEGIN_DT", pa.date64()),
        ("SCRTY_RGSTRN_END_DT", pa.date64()),
        ("SCRTY_RGSTRN_NUM", pa.string()),
        ("ASST_TP_DESC", pa.string()),
        ("ORIG_PRPTY_APPRSL_VAL", pa.float64()),
        ("ORIG_PRPTY_APPRSL_DT", pa.date64()),
        ("PRPTY_PRCH_AMT", pa.float64()),
        ("PRPTY_PRCH_DT", pa.date64()),
        ("ORIG_TOT_INCM", pa.int64()),
        ("PRNCPL_INTR_PYMT_AMT", pa.float64()),
        ("NEXT_INTR_RESET_DT", pa.date64()),
        ("RT_MODFR", pa.float64()),
        ("DN_PYMT_SRC_DESC", pa.string()),
        ("CLIENT_DT", pa.date64()),
        ("CIF_CREATD_ON_DT", pa.date64()),
        ("DFT_IND", pa.string()),
        ("STATED_INCM_IND", pa.string()),
        ("ACCR_INTR_AMT", pa.float64()),
        ("CLS_DT", pa.date64()),
        ("BULK_INSURER_DESC", pa.string()),
        ("SECRTZTN_IND", pa.string()),
        ("CIF_TP_DESC", pa.string()),
        ("CUST_TP_2", pa.string()),
        ("INTR_PYMTS_AMT", pa.float64()),
        ("INTR_CMPNDNG_FREQ", pa.int64()),
        ("OPN_CLSD_TERM", pa.string()),
        ("PYT_RSN", pa.string()),
        ("LAST_RNEW_DT", pa.date64()),
        ("ACCT_NUM", pa.string()),
        ("GL_ACCT_NUM", pa.string()),
        ("GL_TRNST_NUM", pa.string()),
        ("CRNCY_CD", pa.string()),
    ]),
)
def make_airb_tangrn_mort_acct():
    """
    Extract Tangerine mortgage account month-end snapshot.
    
    Extracts comprehensive mortgage account data including balances, delinquency,
    rates, property details, security information, income, payments, and various
    indicators from TNG_MORT_ACCT_MTH_SNAPSHOT for the current month-end date.
    103 columns covering complete account lifecycle and characteristics.
    """
    pass


"""Source layer for sq034."""
rundir_task = create_sq034_rundir()
extract_task = make_airb_tangrn_mort_acct()

rundir_task >> extract_task
