-- New tables.


	
DROP TABLE EDRTLRP1D.DT4_SEGMENT_XREF if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_SEGMENT_XREF (
		MTH_TM_ID INTEGER, 
		BASEL_ACCT_ID BIGINT, 
		MORT_NUM VARCHAR(20 OCTETS), 
		PD_BASEL_SEG_NUM INTEGER, 
		PD_BASEL_SEG_ID INTEGER, 
		PD_BASEL_MODEL_ID INTEGER, 
		DT4_PD_MODEL_INCL_F INTEGER, 
		LGD_D_BASEL_SEG_NUM INTEGER, 
		LGD_D_BASEL_SEG_ID INTEGER, 
		LGD_D_BASEL_MODEL_ID INTEGER, 
		DT4_LGD_D_MODEL_INCL_F INTEGER, 
		LGD_ND_BASEL_SEG_NUM INTEGER, 
		LGD_ND_BASEL_SEG_ID INTEGER, 
		LGD_ND_BASEL_MODEL_ID INTEGER, 
		DT4_LGD_ND_MODEL_INCL_F INTEGER, 
		EAD_BASEL_SEG_NUM INTEGER, 
		EAD_BASEL_SEG_ID INTEGER, 
		EAD_BASEL_MODEL_ID INTEGER, 
		DT4_EAD_MODEL_INCL_F INTEGER, 
		EFF_FROM_YR_MTH CHAR(6 OCTETS), 
		EFF_TO_YR_MTH CHAR(6 OCTETS), 
		CRNT_F CHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, BASEL_ACCT_ID, EFF_FROM_YR_MTH); COMMIT;
	
DROP TABLE EDRTLRP1D.RPTG_RISK_RT_SYS_DIM IF EXISTS; COMMIT; 

CREATE TABLE EDRTLRD3D.RPTG_RISK_RT_SYS_DIM (
		NCR_RISK_RT_SYS_ID INTEGER NOT NULL, 
		NCR_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		NCR_RISK_RT_DESC VARCHAR(255 OCTETS), 
		EFF_TO_YR_MTH CHAR(6 OCTETS), 
		EFF_FROM_YR_MTH CHAR(6 OCTETS), 
		CRNT_F CHAR(1 OCTETS) NOT NULL, 
		INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (NCR_RISK_RT_SYS_ID); COMMIT; 
	
DROP TABLE EDRTLRP1D.DT4_BASEL_SEG_INCL if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_BASEL_SEG_INCL (
		MODEL_TYPE VARCHAR(10 OCTETS), 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		MODEL_NM VARCHAR(20 OCTETS), 
		SEG_NUM INTEGER, 
		BASEL_SEG_ID INTEGER NOT NULL, 
		BASEL_MODEL_ID INTEGER NOT NULL, 
		BASEL_SEG_DESC VARCHAR(50 OCTETS), 
		SEG_CRTRIA_DESC VARCHAR(255 OCTETS), 
		INCL_F INTEGER, 
		EFF_FROM_YR_MTH CHAR(6 OCTETS), 
		EFF_TO_YR_MTH CHAR(6 OCTETS), 
		CRNT_F CHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_SEG_ID, EFF_FROM_YR_MTH); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_SEG_DIM if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_SEG_DIM (
		MODEL_TYPE VARCHAR(6 OCTETS) NOT NULL, 
		RRAP_SEG_NUM INTEGER NOT NULL, 
		DT4_SEG_KEY_VAL CHAR(4 OCTETS) NOT NULL, 
		DT4_SEG_DESC VARCHAR(255 OCTETS) NOT NULL, 
		EFF_FROM_YR_MTH CHAR(6 OCTETS) NOT NULL, 
		EFF_TO_YR_MTH CHAR(6 OCTETS) NOT NULL, 
		CRNT_F CHAR(1 OCTETS) NOT NULL, 
		INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL, 
		UPDT_PROCESS_TMSTMP TIMESTAMP, 
		CONSTRAINT SQL211209173311550 PRIMARY KEY
		(DT4_SEG_KEY_VAL) NOT ENFORCED
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (DT4_SEG_KEY_VAL); COMMIT;

DROP TABLE EDRTLRP1D.DT4_RT05_DECLARATION if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT05_DECLARATION (
		MTH_TM_ID INTEGER, 
		RRS VARCHAR(4 OCTETS), 
		RRS_NAME VARCHAR(200 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, RRS); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT10_DECLARATION if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT10_DECLARATION (
		MTH_TM_ID INTEGER, 
		RRS VARCHAR(4 OCTETS), 
		PD_SEG VARCHAR(4 OCTETS), 
		PD_SEGMENT_NAME VARCHAR(255 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, RRS, PD_SEG); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT11_DECLARATION if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT11_DECLARATION (
		MTH_TM_ID INTEGER, 
		RRS VARCHAR(4 OCTETS), 
		LGD_SEG VARCHAR(4 OCTETS), 
		LGD_NAME VARCHAR(200 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, RRS, LGD_SEG); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT12_DECLARATION if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT12_DECLARATION (
		MTH_TM_ID INTEGER, 
		RRS VARCHAR(4 OCTETS), 
		EADF_SEG VARCHAR(4 OCTETS), 
		EADF_NAME VARCHAR(200 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, RRS, EADF_SEG); COMMIT;
	

DROP TABLE EDRTLRP1D.DT4_PD12_RLZ_DRVD_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_PD12_RLZ_DRVD_VARS (
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NO VARCHAR(20 OCTETS), 
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		OBS_PIT_STAT_CD CHAR(10 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		DRAWN DECIMAL(17 , 3), 
		UNDRAWN DECIMAL(17 , 3), 
		MODEL_DFT_F INTEGER, 
		LAST_NEW_DEFAULT_DATE INTEGER, 
		LAST_NEW_DEFAULT_OS_BAL_AMT DECIMAL(17 , 3), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MORT_NO, PROCESS_MTH_TM_ID); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_PD12_FINAL_RPTG_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_PD12_FINAL_RPTG_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		OBSERVED_PD_12M DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, DT4_EXPSR_CL_KEY_VAL); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT20_RLZ_DRVD_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT20_RLZ_DRVD_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NO VARCHAR(20 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		PD_BASEL_SEG_NUM INTEGER, 
		PD_BASEL_SEG_ID INTEGER, 
		PD_BASEL_MODEL_ID INTEGER, 
		MODEL_DFT_F INTEGER, 
		EST_PD_FINAL_RPTG_RTO DOUBLE, 
		ADJ_FOR_CRM DOUBLE, 
		EAD_AFTER_CRM_DRAWN DOUBLE, 
		EAD_AFTER_CRM_UNDRAWN DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, BASEL_ACCT_ID); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT20_FINAL_RPTG_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT20_FINAL_RPTG_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		DT4_RISK_RT_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_RISK_RT_DESC VARCHAR(255 OCTETS), 
		MODEL_NM VARCHAR(20 OCTETS), 
		DT4_PD_SEG_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_PD_SEG_DESC VARCHAR(255 OCTETS), 
		PD_BASEL_SEG_NUM INTEGER, 
		PD_BASEL_SEG_ID INTEGER, 
		PD_BASEL_MODEL_ID INTEGER, 
		DEFAULTERS INTEGER, 
		ACCOUNTS INTEGER, 
		PREDICTED_PD DOUBLE, 
		REALIZED_PD DOUBLE, 
		ZVALUE DOUBLE, 
		LOWER_CI DOUBLE, 
		UPPER_CI DOUBLE, 
		BREACH INTEGER, 
		EAD_DEF DOUBLE, 
		EAD_NONDEF DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, PD_BASEL_SEG_ID, PD_BASEL_MODEL_ID); COMMIT;


DROP TABLE EDRTLRP1D.DT4_RT30_RLZ_DRVD_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT30_RLZ_DRVD_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NUM VARCHAR(20 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		MODEL_TYPE CHAR(6 OCTETS), 
		LGD_BASEL_SEG_NUM INTEGER, 
		LGD_BASEL_SEG_ID INTEGER, 
		LGD_BASEL_MODEL_ID INTEGER, 
		LGD_NPV_ALL_COST_FLR_CAP_150_RTO DOUBLE, 
		EST_LGD_FINAL_RPTG_RTO DOUBLE, 
		MODEL_DFT_F INTEGER, 
		ADJ_FOR_CRM DOUBLE, 
		EAD_AFTER_CRM_DRAWN DOUBLE, 
		EAD_AFTER_CRM_UNDRAWN DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, BASEL_ACCT_ID); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT30_FINAL_RPTG_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT30_FINAL_RPTG_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		DT4_RISK_RT_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_RISK_RT_DESC VARCHAR(255 OCTETS), 
		MODEL_NM VARCHAR(20 OCTETS), 
		DT4_LGD_SEG_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_LGD_SEG_DESC VARCHAR(255 OCTETS), 
		LGD_BASEL_SEG_NUM INTEGER, 
		LGD_BASEL_SEG_ID INTEGER, 
		LGD_BASEL_MODEL_ID INTEGER, 
		DEFAULTERS INTEGER, 
		ACCOUNTS INTEGER, 
		PREDICTED_LGD DOUBLE, 
		REALIZED_LGD DOUBLE, 
		TVALUE DOUBLE, 
		CALC_STD DOUBLE, 
		LOWER_CI DOUBLE, 
		UPPER_CI DOUBLE, 
		BREACH INTEGER, 
		EAD_DEF DOUBLE, 
		EAD_NONDEF DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, LGD_BASEL_SEG_ID, LGD_BASEL_MODEL_ID); COMMIT;

DROP TABLE EDRTLRP1D.DT4_RT40_RLZ_DRVD_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT40_RLZ_DRVD_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NO VARCHAR(20 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		EAD_BASEL_SEG_NUM INTEGER, 
		EAD_BASEL_SEG_ID INTEGER, 
		EAD_BASEL_MODEL_ID INTEGER, 
		MODEL_DFT_F INTEGER, 
		EST_EAD_FINAL_RPTG_RTO DOUBLE, 
		EAD_FLR_CAP_200_RTO DOUBLE, 
		ADJ_FOR_CRM DOUBLE, 
		EAD_AFTER_CRM_DRAWN DOUBLE, 
		EAD_AFTER_CRM_UNDRAWN DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, BASEL_ACCT_ID); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_RT40_FINAL_RPTG_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RT40_FINAL_RPTG_VARS (
		PROCESS_MTH_TM_ID INTEGER, 
		OBS_MTH_TM_ID INTEGER, 
		DT4_RISK_RT_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_RISK_RT_DESC VARCHAR(255 OCTETS), 
		MODEL_NM VARCHAR(20 OCTETS), 
		DT4_EAD_SEG_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_EAD_SEG_DESC VARCHAR(255 OCTETS), 
		EAD_BASEL_SEG_NUM INTEGER, 
		EAD_BASEL_SEG_ID INTEGER, 
		EAD_BASEL_MODEL_ID INTEGER, 
		DEFAULTERS INTEGER, 
		ACCOUNTS INTEGER, 
		PREDICTED_EAD DOUBLE, 
		REALIZED_EAD DOUBLE, 
		TVALUE DOUBLE, 
		CALC_STD DOUBLE, 
		LOWER_CI DOUBLE, 
		UPPER_CI DOUBLE, 
		BREACH INTEGER, 
		EAD_DEF DOUBLE, 
		EAD_NONDEF DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (PROCESS_MTH_TM_ID, EAD_BASEL_SEG_ID, EAD_BASEL_MODEL_ID); COMMIT;


DROP TABLE EDRTLRP1D.DT4_BRDR_SEG_LVL if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_BRDR_SEG_LVL (
		MTH_TM_ID INTEGER, 
		RRS VARCHAR(4 OCTETS), 
		SEGMENT_ID VARCHAR(4 OCTETS), 
		BREACHING_PARAMETER VARCHAR(6 OCTETS), 
		NUM_BREACHES INTEGER, 
		RRS_DESC VARCHAR(255 OCTETS), 
		SEGMENT_DESC VARCHAR(255 OCTETS), 
		ESTIMATED_PARAMETER DOUBLE, 
		REALIZED_PARAMETER DOUBLE, 
		EXPOSURE_CLASSES VARCHAR(30 OCTETS), 
		EAD_SEG_V_RRS DOUBLE, 
		EAD_RRS_V_SAC DOUBLE, 
		EAD_SAC_V_AC DOUBLE, 
		ACCOUNT_COUNT DOUBLE, 
		EAD_DOM_SEG_X_EXPSR DOUBLE, 
		EAD_SEG DOUBLE, 
		EAD_RRS DOUBLE, 
		SUB_ASSET_CLASS VARCHAR(20 OCTETS), 
		DOM_SUB_ASSET_CLASS VARCHAR(3 OCTETS), 
		EAD_DOM_SUB_ASSET_CLASS DOUBLE, 
		EAD_RETAIL DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, RRS, SEGMENT_ID); COMMIT;
	
DROP TABLE EDRTLRP1D.DT4_BRDR_REC_UNREC_BRCH if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_BRDR_REC_UNREC_BRCH (
		MTH_TM_ID INTEGER, 
		RRS VARCHAR(4 OCTETS), 
		SEGMENT_ID VARCHAR(4 OCTETS), 
		BREACHING_PARAMETER VARCHAR(6 OCTETS), 
		NUM_BREACHES INTEGER, 
		RRS_DESC VARCHAR(255 OCTETS), 
		SEGMENT_DESC VARCHAR(255 OCTETS), 
		ESTIMATED_PARAMETER DOUBLE, 
		REALIZED_PARAMETER DOUBLE, 
		EXPOSURE_CLASSES VARCHAR(30 OCTETS), 
		EAD_SEG_V_RRS DOUBLE, 
		EAD_RRS_V_SAC DOUBLE, 
		EAD_SAC_V_AC DOUBLE, 
		ACCOUNT_COUNT DOUBLE, 
		EAD_DOM_SEG_X_EXPSR DOUBLE, 
		EAD_SEG DOUBLE, 
		EAD_RRS DOUBLE, 
		SUB_ASSET_CLASS VARCHAR(20 OCTETS), 
		DOM_SUB_ASSET_CLASS VARCHAR(3 OCTETS), 
		EAD_DOM_SUB_ASSET_CLASS DOUBLE, 
		EAD_RETAIL DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, RRS, SEGMENT_ID); COMMIT;
	
