-- Existing tables to be replaced.

DROP TABLE EDRTLRP1D.DT4_RPTG_DRVD_VARS if exists; COMMIT;

CREATE TABLE EDRTLRP1D.DT4_RPTG_DRVD_VARS (
		MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		BASEL_ACCT_ID BIGINT, 
		MORT_NUM VARCHAR(50 OCTETS), 
		PIT_STAT_CD VARCHAR(5 OCTETS), 
		PD_BAND CHAR(10 OCTETS), 
		DT4_RISK_RT_KEY_VAL CHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL CHAR(4 OCTETS), 
		BCAR_SCHED_NUM CHAR(3 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MTH_TM_ID); COMMIT;

DROP TABLE EDRTLRP1D.RPTG_PRD_LKP_KS IF EXISTS; COMMIT; 

CREATE TABLE EDRTLRP1D.RPTG_PRD_LKP_KS (
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		PRD_CD VARCHAR(10 OCTETS), 
		SUB_PRD_CD VARCHAR(10 OCTETS), 
		REVISED_EXPSR_OV_125K_F VARCHAR(1 OCTETS), 
		HELOC_F VARCHAR(1 OCTETS), 
		BASEL_PRD_CD VARCHAR(10 OCTETS), 
		BASEL_PRD_TP_CD VARCHAR(10 OCTETS), 
		ASST_CL_NUM SMALLINT, 
		ASST_CL_DESC VARCHAR(255 OCTETS), 
		PRD_ID VARCHAR(10 OCTETS), 
		PORTFL_NM VARCHAR(50 OCTETS), 
		PRD_NM VARCHAR(50 OCTETS), 
		SUB_PRD_NM VARCHAR(255 OCTETS), 
		BASEL_SUB_PRD_NM VARCHAR(255 OCTETS), 
		BCAR_SCHED_NUM VARCHAR(3 OCTETS), 
		NCR_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		CCAR_BASEL_PRD_TP_NM VARCHAR(50 OCTETS), 
		CCAR_SHT_NM VARCHAR(4 OCTETS), 
		ACCT_CRNCY_CD VARCHAR(10 OCTETS), 
		RT_KEY_VAL VARCHAR(4 OCTETS), 
		BASEL_PRD_NM VARCHAR(50 OCTETS), 
		BASEL_PRD_ABR VARCHAR(255 OCTETS), 
		SCRTY_TP_CD VARCHAR(50 OCTETS), 
		PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		PD_BAND_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		NCR_EXPSR_CL_DESC VARCHAR(255 OCTETS), 
		DT4_RISK_RT_KEY_VAL VARCHAR(4 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (SRC_SYS_CD, PRD_CD, SUB_PRD_CD, REVISED_EXPSR_OV_125K_F, HELOC_F, BASEL_PRD_CD, EFF_FROM_YR_MTH); COMMIT; 





DROP TABLE EDRTLRP1D.DT4_RT18_EST_ER_VARS IF EXISTS; COMMIT; 

CREATE TABLE EDRTLRP1D.DT4_RT18_EST_ER_VARS (
		BASEL_ACCT_ID BIGINT, 
		MTH_TM_ID INTEGER, 
		SRC_SYS_CD VARCHAR(10 OCTETS), 
		CCAR_BASEL_PRD_TP_NM VARCHAR(50 OCTETS), 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		PD_BAND VARCHAR(10 OCTETS), 
		PD_VALUE DECIMAL(30 , 8), 
		EAD_INCL INTEGER, 
		EXPOSURE_DRAWN DOUBLE, 
		NETEAD_UNDRAWN DOUBLE, 
		EL_DRAWNPCT_FOR_DEFAULTED DOUBLE, 
		EAD_FINAL_RPTG_RTO DOUBLE, 
		DLGD_RPTG_RTO_VAL DOUBLE, 
		CORRELATION DOUBLE, 
		RETAIL_RW DOUBLE, 
		GUARANTEE_PARTICIPATION DOUBLE, 
		ADJ_FOR_CRM DOUBLE, 
		NETEAD_BEFORECRM_DRAWN DOUBLE,
		NETEAD_DRAWN DOUBLE, 
		RWA_UNDRAWN DOUBLE, 
		RWA_DRAWN DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (BASEL_ACCT_ID, MTH_TM_ID); COMMIT; 
	

DROP TABLE EDRTLRP1D.DT4_RT18_EST_VARS IF EXISTS; COMMIT; 

CREATE TABLE EDRTLRP1D.DT4_RT18_EST_VARS (
		MTH_TM_ID INTEGER, 
		DT4_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS), 
		EXPOSURE_CLASS VARCHAR(255 OCTETS), 
		OBLIGORS DOUBLE, 
		WEIGHTED_PD_BEFORECRM DOUBLE, 
		WEIGHTED_LGD_BEFORECRM DOUBLE, 
		WEIGHTED_EAD_AFTERCRM DOUBLE, 
		EAD_AFTERCRM_NODEF DOUBLE, 
		EAD_AFTERCRM_DEF DOUBLE, 
		RWA_NODEF DOUBLE, 
		RWA_DEF DOUBLE, 
		RWA DOUBLE, 
		RWA_WSCALAR DOUBLE, 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, DT4_EXPSR_CL_KEY_VAL); COMMIT; 