/**************************************************************************** 
 * Job:             J_ITLC_BB_CDN_BLACK_BOOK_MTH_SNAPSHOT A57SWEI7.BH0009MK * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: cs2iw503                                                * 
 * Port:            8561                                                    * 
 * Location:        /Projects/ITLC                                          * 
 *                                                                          * 
 * Server:          SASApp                                A57SWEI7.AT000002 * 
 *                                                                          * 
 * Source Tables:   ITLC_CBB_Used_yyyymm -                A57SWEI7.C200000L * 
 *                  /owpftp/cbb/incoming/cbb_edwext_cbu                     * 
 *                  r_f_mthly_&YEARMONTH..txt                               * 
 *                  CANADIAN_BLACK_BOOK_SRC_CURR -        A57SWEI7.BE00044N * 
 *                  DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CU                     * 
 *                  RR                                                      * 
 * Target Tables:   CDN_BLACK_BOOK_MTH_SNAPSHOT -         A57SWEI7.BE00044M * 
 *                   DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT                    * 
 *                  CANADIAN_BLACK_BOOK_SRC_CURR -        A57SWEI7.BE00044N * 
 *                  DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CU                     * 
 *                  RR                                                      * 
 *                  CDN_BLACK_BOOK_MTH_SNAPSHOT -         A57SWEI7.BE00044M * 
 *                   DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT                    * 
 *                                                                          * 
 * Generated on:    Thursday, August 23, 2018 2:27:55 PM EDT                * 
 * Generated by:    s7026573                                                * 
 * Version:         SAS Data Integration Studio 4.8                         * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A57SWEI7.BH0009MK);
%let etls_jobName = %nrquote(J_ITLC_BB_CDN_BLACK_BOOK_MTH_SNAPSHOT);
%let etls_userID = %nrquote(s7026573);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc syscc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(iw503);

/* Set metadata options */
options metaport       = &metaPort 
        metaserver     = "&metaServer"; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            AM_itlc_autoexec                      A57SWEI7.BK0012SW * 
 * Transform:       AM_itlc_autoexec                                        * 
 * Description:     Autoexec file for ITLC project.                         * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK0012SW);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


%INCLUDE '/sasdata/sasdi/sasprod/macro/itlc/itlc_autoexec.sas';
%ITLC_AUTOEXEC;

%put WORK LOCATION: %sysfunc(getoption(work));

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end AM_itlc_autoexec **/

/*==========================================================================* 
 * Step:            File Reader                           A57SWEI7.BK0012SX * 
 * Transform:       File Reader                                             * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    ITLC_CBB_Used_yyyymm -                A57SWEI7.C200000L * 
 *                  /owpftp/cbb/incoming/cbb_edwext_cbu                     * 
 *                  r_f_mthly_&YEARMONTH..txt                               * 
 * Target Table:    File Reader - work.W620ETTP           A57SWEI7.BN000R0C * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK0012SX);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

proc datasets lib = work nolist nowarn memtype = (data view);
   delete etls_W620ETTP;
quit;

data work.etls_W620ETTP / view = work.etls_W620ETTP ; 
   infile "/owpftp/cbb/incoming/cbb_edwext_cbur_f_mthly_&YEARMONTH..txt"
          lrecl = 242
          truncover
          firstobs = 1; 
   ; 
   attrib VIN length = $8; 
   attrib VINYEAR length = $1; 
   attrib VALID_ASSEMBLY_PLANTS length = $20; 
   attrib GROUPNUMBER length = $4; 
   attrib MODELNUMBER length = $10; 
   attrib MANUFACTURER length = $15; 
   attrib MAKE length = $15; 
   attrib MODEL length = $20; 
   attrib SERIES length = $20; 
   attrib BODYSTYLE length = $20; 
   attrib WEXTRACLEAN length = $6; 
   attrib WCLEAN length = $6; 
   attrib WAVERAGE length = $6; 
   attrib WROUGH length = $6; 
   attrib REXTRACLEAN length = $6; 
   attrib RCLEAN length = $6; 
   attrib RAVERAGE length = $6; 
   attrib RROUGH length = $6; 
   attrib MSRP length = $6; 
   attrib LOANVALUE length = $6; 
   attrib MONTH12_RESIDUAL length = $6; 
   attrib MONTH24_RESIDUAL length = $6; 
   attrib MONTH30_RESIDUAL length = $6; 
   attrib MONTH36_RESIDUAL length = $6; 
   attrib MONTH42_RESIDUAL length = $6; 
   attrib MONTH48_RESIDUAL length = $6; 
   attrib MONTH60_RESIDUAL length = $3; 
   attrib MANUFACTURERCODE length = $3; 
   attrib UVC length = $3; 
   attrib MILEAGECATELOG length = $1; 
   
   input @ 1 VIN  $8.
          @ 9 VINYEAR  $1.
          @ 10 VALID_ASSEMBLY_PLANTS  $20.
          @ 30 GROUPNUMBER  $4.
          @ 34 MODELNUMBER  $10.
          @ 44 MANUFACTURER  $15.
          @ 59 MAKE  $15.
          @ 74 MODEL  $20.
          @ 94 SERIES  $20.
          @ 114 BODYSTYLE  $20.
          @ 134 WEXTRACLEAN  $6.
          @ 140 WCLEAN  $6.
          @ 146 WAVERAGE  $6.
          @ 152 WROUGH  $6.
          @ 158 REXTRACLEAN  $6.
          @ 164 RCLEAN  $6.
          @ 170 RAVERAGE  $6.
          @ 176 RROUGH  $6.
          @ 182 MSRP  $6.
          @ 188 LOANVALUE  $6.
          @ 194 MONTH12_RESIDUAL  $6.
          @ 200 MONTH24_RESIDUAL  $6.
          @ 206 MONTH30_RESIDUAL  $6.
          @ 212 MONTH36_RESIDUAL  $6.
          @ 218 MONTH42_RESIDUAL  $6.
          @ 224 MONTH48_RESIDUAL  $6.
          @ 230 MONTH60_RESIDUAL  $6.
          @ 236 MANUFACTURERCODE  $3.
          @ 239 UVC  $3.
          @ 242 MILEAGECATELOG  $1.; 
   
run; 

%rcSet(&syserr); 

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W620ETTP;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W620ETTP as
      select
         VIN,
         VINYEAR,
         VALID_ASSEMBLY_PLANTS,
         GROUPNUMBER,
         MODELNUMBER,
         MANUFACTURER,
         MAKE,
         MODEL,
         SERIES,
         BODYSTYLE,
         WEXTRACLEAN,
         WCLEAN,
         WAVERAGE,
         WROUGH,
         REXTRACLEAN,
         RCLEAN,
         RAVERAGE,
         RROUGH,
         MSRP,
         LOANVALUE,
         MONTH12_RESIDUAL,
         MONTH24_RESIDUAL,
         MONTH30_RESIDUAL,
         MONTH36_RESIDUAL,
         MONTH42_RESIDUAL,
         MONTH48_RESIDUAL,
         MONTH60_RESIDUAL,
         MANUFACTURERCODE,
         UVC,
         MILEAGECATELOG   
            format = $1.
   from work.etls_W620ETTP
   ;
quit;

%let SYSLAST = work.W620ETTP;

%rcSet(&syscc); 



/**  Step end File Reader **/

/*==========================================================================* 
 * Step:            Extract                               A57SWEI7.BK0012SY * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    File Reader - work.W620ETTP           A57SWEI7.BN000R0C * 
 * Target Table:    Extract - work.W62078HK               A57SWEI7.BN000R0D * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK0012SY);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recnt = -1;
%let SYSLAST = %nrquote(work.W620ETTP); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W62078HK;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W62078HK as
      select
         VIN,
         VINYEAR,
         VALID_ASSEMBLY_PLANTS,
         GROUPNUMBER,
         MODELNUMBER,
         MANUFACTURER,
         MAKE,
         MODEL,
         SERIES,
         BODYSTYLE,
         WEXTRACLEAN,
         WCLEAN,
         WAVERAGE,
         WROUGH,
         REXTRACLEAN,
         RCLEAN,
         RAVERAGE,
         RROUGH,
         MSRP,
         LOANVALUE,
         MONTH12_RESIDUAL,
         MONTH24_RESIDUAL,
         MONTH30_RESIDUAL,
         MONTH36_RESIDUAL,
         MONTH42_RESIDUAL,
         MONTH48_RESIDUAL,
         MONTH60_RESIDUAL,
         MANUFACTURERCODE,
         UVC,
         MILEAGECATELOG
   from &SYSLAST
   order by
      VIN,
      VINYEAR
   ;
quit;

%let SYSLAST = work.W62078HK;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

%rcSet(&syscc); 



/**  Step end Extract **/

/*---- Start of User Written Code  ----*/ 

   /*---- Delete the target table  ----*/ 
   proc sql;
      connect to DB2
      ( 
           authdomain=db2_auth DATASRC=&DB2TARGET
      ); 
      execute 
      ( 
         delete from EDRTLRT.CDN_BLACK_BOOK_MTH_SNAPSHOT where MTH_TM_ID = &MTH_TM_ID
      ) by DB2;
		QUIT;
/*---- End of User Written Code  ----*/ 

/*==========================================================================* 
 * Step:            Table Loader                          A57SWEI7.BK0012T0 * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W62078HK               A57SWEI7.BN000R0D * 
 * Target Table:    CANADIAN_BLACK_BOOK_SRC_CURR -        A57SWEI7.BE00044N * 
 *                  DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CU                     * 
 *                  RR                                                      * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK0012T0);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for DB2ITLC_LANDING  */ 
LIBNAME DB2ITLCL DB2  authdomain="db2_auth"  Datasrc=OWSTGNDB  SCHEMA=STJUT ;
%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(work.W62078HK); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: Replace - Delete
   Constraint and index action selections: 'ASIS','ASIS','ASIS','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /*---- Map the columns  ----*/ 
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete W2XY377;
   quit;
   
   %put %str(NOTE: Mapping columns ...);
   proc sql;
      create view work.W2XY377 as
         select
            VIN length = 20   
               format = $20.
               informat = $20.,
            VINYEAR length = 4   
               format = $4.
               informat = $4.,
            VALID_ASSEMBLY_PLANTS as VALIDASSEMBLYPLANTS   
               format = $20.,
            GROUPNUMBER length = 20   
               format = $20.
               informat = $20.,
            MODELNUMBER length = 20   
               format = $20.
               informat = $20.,
            MANUFACTURER length = 20   
               format = $20.
               informat = $20.,
            MAKE length = 20   
               format = $20.
               informat = $20.,
            MODEL   
               format = $20.,
            SERIES   
               format = $20.,
            BODYSTYLE   
               format = $20.,
            WEXTRACLEAN length = 10   
               format = $10.
               informat = $10.,
            WCLEAN length = 10   
               format = $10.
               informat = $10.,
            WAVERAGE length = 10   
               format = $10.
               informat = $10.,
            WROUGH length = 10   
               format = $10.
               informat = $10.,
            REXTRACLEAN length = 10   
               format = $10.
               informat = $10.,
            RCLEAN length = 10   
               format = $10.
               informat = $10.,
            RAVERAGE length = 10   
               format = $10.
               informat = $10.,
            RROUGH length = 10   
               format = $10.
               informat = $10.,
            MSRP length = 10   
               format = $10.
               informat = $10.,
            LOANVALUE length = 10   
               format = $10.
               informat = $10.,
            MONTH12_RESIDUAL length = 10   
               format = $10.
               informat = $10.,
            MONTH24_RESIDUAL length = 10   
               format = $10.
               informat = $10.,
            MONTH30_RESIDUAL length = 10   
               format = $10.
               informat = $10.,
            MONTH36_RESIDUAL length = 10   
               format = $10.
               informat = $10.,
            MONTH42_RESIDUAL length = 10   
               format = $10.
               informat = $10.,
            MONTH48_RESIDUAL length = 10   
               format = $10.
               informat = $10.,
            MONTH60_RESIDUAL length = 10   
               format = $10.
               informat = $10.,
            MANUFACTURERCODE length = 8   
               format = $8.
               informat = $8.,
            UVC length = 8   
               format = $8.
               informat = $8.,
            MILEAGECATELOG as MILEAGECATEG,
            (DATETIME()) as INSRT_PROCESS_TMSTMP length = 8
               format = DATETIME25.6
               informat = DATETIME25.6
      from &etls_lastTable
      ;
   quit;
   
   %let SYSLAST = work.W2XY377;
   
   %let etls_lastTable = &SYSLAST; 
   %let etls_tableOptions = ; 
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR, DATA)) or 
         %sysfunc(exist(DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR, VIEW))); 
   
   /*---- Create a new table  ----*/ 
   %if (&etls_tableExist eq 0) %then 
   %do;  /* if table does not exist  */ 
   
      %put %str(NOTE: Creating table ...);
      
      data DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR
              (dbnull = (
                         VIN = YES
                         VINYEAR = YES
                         VALIDASSEMBLYPLANTS = YES
                         GROUPNUMBER = YES
                         MODELNUMBER = YES
                         MANUFACTURER = YES
                         MAKE = YES
                         MODEL = YES
                         SERIES = YES
                         BODYSTYLE = YES
                         WEXTRACLEAN = YES
                         WCLEAN = YES
                         WAVERAGE = YES
                         WROUGH = YES
                         REXTRACLEAN = YES
                         RCLEAN = YES
                         RAVERAGE = YES
                         RROUGH = YES
                         MSRP = YES
                         LOANVALUE = YES
                         MONTH12_RESIDUAL = YES
                         MONTH24_RESIDUAL = YES
                         MONTH30_RESIDUAL = YES
                         MONTH36_RESIDUAL = YES
                         MONTH42_RESIDUAL = YES
                         MONTH48_RESIDUAL = YES
                         MONTH60_RESIDUAL = YES
                         MANUFACTURERCODE = YES
                         UVC = YES
                         MILEAGECATEG = YES
                         INSRT_PROCESS_TMSTMP = NO));
         attrib VIN length = $20
            format = $20.
            informat = $20.
            label = 'VIN'; 
         attrib VINYEAR length = $4
            format = $4.
            informat = $4.
            label = 'VINYEAR'; 
         attrib VALIDASSEMBLYPLANTS length = $20
            format = $20.
            informat = $20.
            label = 'VALIDASSEMBLYPLANTS'; 
         attrib GROUPNUMBER length = $20
            format = $20.
            informat = $20.
            label = 'GROUPNUMBER'; 
         attrib MODELNUMBER length = $20
            format = $20.
            informat = $20.
            label = 'MODELNUMBER'; 
         attrib MANUFACTURER length = $20
            format = $20.
            informat = $20.
            label = 'MANUFACTURER'; 
         attrib MAKE length = $20
            format = $20.
            informat = $20.
            label = 'MAKE'; 
         attrib MODEL length = $20
            format = $20.
            informat = $20.
            label = 'MODEL'; 
         attrib SERIES length = $20
            format = $20.
            informat = $20.
            label = 'SERIES'; 
         attrib BODYSTYLE length = $20
            format = $20.
            informat = $20.
            label = 'BODYSTYLE'; 
         attrib WEXTRACLEAN length = $10
            format = $10.
            informat = $10.
            label = 'WEXTRACLEAN'; 
         attrib WCLEAN length = $10
            format = $10.
            informat = $10.
            label = 'WCLEAN'; 
         attrib WAVERAGE length = $10
            format = $10.
            informat = $10.
            label = 'WAVERAGE'; 
         attrib WROUGH length = $10
            format = $10.
            informat = $10.
            label = 'WROUGH'; 
         attrib REXTRACLEAN length = $10
            format = $10.
            informat = $10.
            label = 'REXTRACLEAN'; 
         attrib RCLEAN length = $10
            format = $10.
            informat = $10.
            label = 'RCLEAN'; 
         attrib RAVERAGE length = $10
            format = $10.
            informat = $10.
            label = 'RAVERAGE'; 
         attrib RROUGH length = $10
            format = $10.
            informat = $10.
            label = 'RROUGH'; 
         attrib MSRP length = $10
            format = $10.
            informat = $10.
            label = 'MSRP'; 
         attrib LOANVALUE length = $10
            format = $10.
            informat = $10.
            label = 'LOANVALUE'; 
         attrib MONTH12_RESIDUAL length = $10
            format = $10.
            informat = $10.
            label = 'MONTH12_RESIDUAL'; 
         attrib MONTH24_RESIDUAL length = $10
            format = $10.
            informat = $10.
            label = 'MONTH24_RESIDUAL'; 
         attrib MONTH30_RESIDUAL length = $10
            format = $10.
            informat = $10.
            label = 'MONTH30_RESIDUAL'; 
         attrib MONTH36_RESIDUAL length = $10
            format = $10.
            informat = $10.
            label = 'MONTH36_RESIDUAL'; 
         attrib MONTH42_RESIDUAL length = $10
            format = $10.
            informat = $10.
            label = 'MONTH42_RESIDUAL'; 
         attrib MONTH48_RESIDUAL length = $10
            format = $10.
            informat = $10.
            label = 'MONTH48_RESIDUAL'; 
         attrib MONTH60_RESIDUAL length = $10
            format = $10.
            informat = $10.
            label = 'MONTH60_RESIDUAL'; 
         attrib MANUFACTURERCODE length = $8
            format = $8.
            informat = $8.
            label = 'MANUFACTURERCODE'; 
         attrib UVC length = $8
            format = $8.
            informat = $8.
            label = 'UVC'; 
         attrib MILEAGECATEG length = $1
            format = $1.
            informat = $1.
            label = 'MILEAGECATEG'; 
         attrib INSRT_PROCESS_TMSTMP length = 8
            format = DATETIME25.6
            informat = DATETIME25.6
            label = 'INSRT_PROCESS_TMSTMP'; 
         call missing(of _all_);
         stop;
      run;
      
      %rcSet(&syserr); 
      
   %end;  /* if table does not exist  */ 
   
   %else 
   %do;  /* table exists */ 
      /*---- Deleting all rows  ----*/ 
      %put %str(NOTE: Deleting all rows ...);
      proc sql;
         connect to DB2
         ( 
             authdomain="db2_auth" DATASRC=OWSTGNDB
         ); 
         reset noprint; 
         
         execute 
         ( 
            delete from STJUT.CANADIAN_BLACK_BOOK_SRC_CURR
             where 1=1 
         ) by DB2; 
         
         %rcSet(&sqlrc); 
         
         disconnect from DB2; 
      quit; 
      
      %rcSet(&sqlrc); 
      
   %end; /* table exists */ 
   
   /*---- Append  ----*/ 
   %put %str(NOTE: Appending data ...);
   
   proc append base = DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR 
      data = &etls_lastTable (&etls_tableOptions)  force ; 
    run; 
   
   %rcSet(&syserr); 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete W2XY377;
   quit;
   
%mend etls_loader;
%etls_loader;

%let etls_recnt = 0;
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR, DATA)) or 
         %sysfunc(exist(DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      proc sql noprint;
         select count(*) into :etls_recnt from DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR;
      quit;
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%rcSet(&syscc); 



/**  Step end Table Loader **/

/*==========================================================================* 
 * Step:            Table Loader                          A57SWEI7.BK0012T1 * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    CANADIAN_BLACK_BOOK_SRC_CURR -        A57SWEI7.BE00044N * 
 *                  DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CU                     * 
 *                  RR                                                      * 
 * Target Table:    CDN_BLACK_BOOK_MTH_SNAPSHOT -         A57SWEI7.BE00044M * 
 *                   DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT                    * 
 *==========================================================================*/ 

%let transformID = %quote(A57SWEI7.BK0012T1);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for DB2ITLC_DM_EDRTLRT  */ 
LIBNAME DB2ITLC DB2  authdomain=db2_auth  Datasrc=DM1P1D  SCHEMA=EDRTLRT ;
%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(DB2ITLCL.CANADIAN_BLACK_BOOK_SRC_CURR); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: AppendToExisting - AppendProc
   Constraint and index action selections: 'ASIS','ASIS','ASIS','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /*---- Map the columns  ----*/ 
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete W2XY3SR;
   quit;
   
   %put %str(NOTE: Mapping columns ...);
   proc sql;
      create view work.W2XY3SR as
         select
            (&MTH_TM_ID) as MTH_TM_ID length = 8
               format = 11.
               informat = 11.,
            VIN,
            VINYEAR,
            VALIDASSEMBLYPLANTS,
            GROUPNUMBER,
            MODELNUMBER,
            MANUFACTURER as MFRS,
            MAKE,
            MODEL,
            SERIES,
            BODYSTYLE,
            (INPUT(WEXTRACLEAN,BEST32.)) as WEXTRACLEAN length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(WCLEAN,BEST32.)) as WCLEAN length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(WAVERAGE,BEST32.)) as WAVERAGE length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(WROUGH,BEST32.)) as WROUGH length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(REXTRACLEAN,BEST32.)) as REXTRACLEAN length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(RCLEAN,BEST32.)) as RCLEAN length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(RAVERAGE,BEST32.)) as RAVERAGE length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(RROUGH,BEST32.)) as RROUGH length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MSRP,BEST32.)) as MSRP length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(LOANVALUE,BEST32.)) as LOANVALUE length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MONTH12_RESIDUAL,BEST32.)) as MONTH12_RESIDUAL length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MONTH24_RESIDUAL,BEST32.)) as MONTH24_RESIDUAL length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MONTH30_RESIDUAL,BEST32.)) as MONTH30_RESIDUAL length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MONTH36_RESIDUAL,BEST32.)) as MONTH36_RESIDUAL length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MONTH42_RESIDUAL,BEST32.)) as MONTH42_RESIDUAL length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MONTH48_RESIDUAL,BEST32.)) as MONTH48_RESIDUAL length = 8
               format = 19.3
               informat = 19.3,
            (INPUT(MONTH60_RESIDUAL,BEST32.)) as MONTH60_RESIDUAL length = 8
               format = 19.3
               informat = 19.3,
            MANUFACTURERCODE,
            UVC,
            MILEAGECATEG,
            (DATETIME()) as INSRT_PROCESS_TMSTMP length = 8
               format = DATETIME25.6
               informat = DATETIME25.6,
            (DATETIME()) as UPDT_PROCESS_TMSTMP length = 8
               format = DATETIME25.6
               informat = DATETIME25.6
      from &etls_lastTable
      ;
   quit;
   
   %let SYSLAST = work.W2XY3SR;
   
   %let etls_lastTable = &SYSLAST; 
   %let etls_tableOptions = ; 
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT, DATA)) or 
         %sysfunc(exist(DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT, VIEW))); 
   
   /*---- Create a new table  ----*/ 
   %if (&etls_tableExist eq 0) %then 
   %do;  /* if table does not exist  */ 
   
      %put %str(NOTE: Creating table ...);
      
      data DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT
              (dbnull = (
                         MTH_TM_ID = NO
                         VIN = NO
                         VINYEAR = NO
                         VALIDASSEMBLYPLANTS = YES
                         GROUPNUMBER = NO
                         MODELNUMBER = NO
                         MFRS = YES
                         MAKE = YES
                         MODEL = YES
                         SERIES = YES
                         BODYSTYLE = YES
                         WEXTRACLEAN = YES
                         WCLEAN = YES
                         WAVERAGE = YES
                         WROUGH = YES
                         REXTRACLEAN = YES
                         RCLEAN = YES
                         RAVERAGE = YES
                         RROUGH = YES
                         MSRP = YES
                         LOANVALUE = YES
                         MONTH12_RESIDUAL = YES
                         MONTH24_RESIDUAL = YES
                         MONTH30_RESIDUAL = YES
                         MONTH36_RESIDUAL = YES
                         MONTH42_RESIDUAL = YES
                         MONTH48_RESIDUAL = YES
                         MONTH60_RESIDUAL = YES
                         MANUFACTURERCODE = YES
                         UVC = YES
                         MILEAGECATEG = YES
                         INSRT_PROCESS_TMSTMP = NO
                         UPDT_PROCESS_TMSTMP = YES));
         attrib MTH_TM_ID length = 8
            format = 11.
            informat = 11.
            label = 'MTH_TM_ID'; 
         attrib VIN length = $20
            format = $20.
            informat = $20.
            label = 'VIN'; 
         attrib VINYEAR length = $4
            format = $4.
            informat = $4.
            label = 'VINYEAR'; 
         attrib VALIDASSEMBLYPLANTS length = $20
            format = $20.
            informat = $20.
            label = 'VALIDASSEMBLYPLANTS'; 
         attrib GROUPNUMBER length = $20
            format = $20.
            informat = $20.
            label = 'GROUPNUMBER'; 
         attrib MODELNUMBER length = $20
            format = $20.
            informat = $20.
            label = 'MODELNUMBER'; 
         attrib MFRS length = $20
            format = $20.
            informat = $20.
            label = 'MFRS'; 
         attrib MAKE length = $20
            format = $20.
            informat = $20.
            label = 'MAKE'; 
         attrib MODEL length = $20
            format = $20.
            informat = $20.
            label = 'MODEL'; 
         attrib SERIES length = $20
            format = $20.
            informat = $20.
            label = 'SERIES'; 
         attrib BODYSTYLE length = $20
            format = $20.
            informat = $20.
            label = 'BODYSTYLE'; 
         attrib WEXTRACLEAN length = 8
            format = 19.3
            informat = 19.3
            label = 'WEXTRACLEAN'; 
         attrib WCLEAN length = 8
            format = 19.3
            informat = 19.3
            label = 'WCLEAN'; 
         attrib WAVERAGE length = 8
            format = 19.3
            informat = 19.3
            label = 'WAVERAGE'; 
         attrib WROUGH length = 8
            format = 19.3
            informat = 19.3
            label = 'WROUGH'; 
         attrib REXTRACLEAN length = 8
            format = 19.3
            informat = 19.3
            label = 'REXTRACLEAN'; 
         attrib RCLEAN length = 8
            format = 19.3
            informat = 19.3
            label = 'RCLEAN'; 
         attrib RAVERAGE length = 8
            format = 19.3
            informat = 19.3
            label = 'RAVERAGE'; 
         attrib RROUGH length = 8
            format = 19.3
            informat = 19.3
            label = 'RROUGH'; 
         attrib MSRP length = 8
            format = 19.3
            informat = 19.3
            label = 'MSRP'; 
         attrib LOANVALUE length = 8
            format = 19.3
            informat = 19.3
            label = 'LOANVALUE'; 
         attrib MONTH12_RESIDUAL length = 8
            format = 19.3
            informat = 19.3
            label = 'MONTH12_RESIDUAL'; 
         attrib MONTH24_RESIDUAL length = 8
            format = 19.3
            informat = 19.3
            label = 'MONTH24_RESIDUAL'; 
         attrib MONTH30_RESIDUAL length = 8
            format = 19.3
            informat = 19.3
            label = 'MONTH30_RESIDUAL'; 
         attrib MONTH36_RESIDUAL length = 8
            format = 19.3
            informat = 19.3
            label = 'MONTH36_RESIDUAL'; 
         attrib MONTH42_RESIDUAL length = 8
            format = 19.3
            informat = 19.3
            label = 'MONTH42_RESIDUAL'; 
         attrib MONTH48_RESIDUAL length = 8
            format = 19.3
            informat = 19.3
            label = 'MONTH48_RESIDUAL'; 
         attrib MONTH60_RESIDUAL length = 8
            format = 19.3
            informat = 19.3
            label = 'MONTH60_RESIDUAL'; 
         attrib MANUFACTURERCODE length = $8
            format = $8.
            informat = $8.
            label = 'MANUFACTURERCODE'; 
         attrib UVC length = $8
            format = $8.
            informat = $8.
            label = 'UVC'; 
         attrib MILEAGECATEG length = $1
            format = $1.
            informat = $1.
            label = 'MILEAGECATEG'; 
         attrib INSRT_PROCESS_TMSTMP length = 8
            format = DATETIME25.6
            informat = DATETIME25.6
            label = 'INSRT_PROCESS_TMSTMP'; 
         attrib UPDT_PROCESS_TMSTMP length = 8
            format = DATETIME25.6
            informat = DATETIME25.6
            label = 'UPDT_PROCESS_TMSTMP'; 
         call missing(of _all_);
         stop;
      run;
      
      %rcSet(&syserr); 
      
   %end;  /* if table does not exist  */ 
   
   /*---- Append  ----*/ 
   %put %str(NOTE: Appending data ...);
   
   proc append base = DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT 
      data = &etls_lastTable (&etls_tableOptions)  force ; 
    run; 
   
   %rcSet(&syserr); 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete W2XY3SR;
   quit;
   
%mend etls_loader;
%etls_loader;

%let etls_recnt = 0;
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT, DATA)) or 
         %sysfunc(exist(DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      proc sql noprint;
         select count(*) into :etls_recnt from DB2ITLC.CDN_BLACK_BOOK_MTH_SNAPSHOT;
      quit;
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%rcSet(&syscc); 



/**  Step end Table Loader **/

/*---- Start of Post-Process Code  ----*/ 

%include "&itlc_dir./sas/collection_models/email_communication.sas";
%email_declare;

%macro email1;
/*EMAIL */

FILENAME OUTMAIL EMAIL
SUBJECT= "BLACK BOOK DATA LOADED - %sysfunc(datetime(),datetime26.3)";

DATA _NULL_;
FILE OUTMAIL
TO= (&ITLC_CC_LIST);
PUT "BLACK BOOK DATA LOADED";
RUN;
%mend email1;

%email1;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

%let etls_endTime = %sysfunc(datetime(),datetime.);

