%coll_autoexec;
%include "&coll_dir./sas/collection_models/email_communication.sas";

/*Collections models score age report*/
/*create datasets one for each portfolio for the past 70 days*/

PROC SQL NOPRINT;
CONNECT USING DB2PROD AS DBCON;
CREATE TABLE SASCOLL.ULOCC_SCORE_AGE_V2 AS 
SELECT * FROM CONNECTION TO DBCON(
SELECT DISTINCT TM_ID, TM_LVL_END_DT AS DT_SCORED_FOR, DAY_OF_WK_DESC, 
CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=6 THEN TM_LVL_END_DT+3 DAYS 
	 WHEN DAYOFWEEK(TM_LVL_END_DT) IN (1,7) THEN NULL 
	 ELSE TM_LVL_END_DT+1 DAY END AS EXPECTED_SCORING_DT,
DAYNAME(CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=6 THEN TM_LVL_END_DT+3 DAYS 
	 		 WHEN DAYOFWEEK(TM_LVL_END_DT) IN (1,7) THEN NULL 
			 ELSE TM_LVL_END_DT+1 DAY END) AS EXPECTED_SCORING_DAY,
YEAR(CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=6 THEN TM_LVL_END_DT+3 DAYS ELSE TM_LVL_END_DT+1 DAY END)||'W'||WEEK(CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=6 
THEN TM_LVL_END_DT+3 DAYS ELSE TM_LVL_END_DT+1 DAY END) AS YEARWEEK, 
EFF_TM_iD, SCORING_DT AS SCORED_DT, PRIM.INSRT_PROCESS_TMSTMP,  
SCORING_DT-TM_LVL_END_DT AS SCORE_AGE_IN_DAYS
FROM EDRTLRT.TM_DIM 
LEFT OUTER JOIN EDRTLRT.ULOC_COLCTN_MODEL_OUTPUT PRIM ON EFF_TM_iD=TM_ID
WHERE DAYS(TM_LVL_END_DT) >= DAYS(CURRENT_DATE)-70 
AND TM_LVL='Day' AND TM_LVL_END_DT<(CURRENT_DATE)
ORDER BY TM_iD DESC);
DISCONNECT FROM DBCON;
QUIT;

PROC SQL NOPRINT;
CONNECT USING DB2PROD AS DBCON;
CREATE TABLE SASCOLL.ITLC_SCORE_AGE_V2 AS 
SELECT * FROM CONNECTION TO DBCON(
SELECT DISTINCT TM_ID, TM_LVL_END_DT AS DT_SCORED_FOR, DAY_OF_WK_DESC, 
CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=7 THEN TM_LVL_END_DT+2 DAYS 
	 WHEN DAYOFWEEK(TM_LVL_END_DT)=1 THEN NULL
	 ELSE TM_LVL_END_DT+1 DAY END AS EXPECTED_SCORING_DT,
DAYNAME(CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=7 THEN TM_LVL_END_DT+2 DAYS 
	 		 WHEN DAYOFWEEK(TM_LVL_END_DT)=1 THEN NULL 
			 ELSE TM_LVL_END_DT+1 DAY END) AS EXPECTED_SCORING_DAY,
YEAR(CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=7 THEN TM_LVL_END_DT+2 DAYS ELSE TM_LVL_END_DT+1 DAY END)||'W'||WEEK(CASE WHEN DAYOFWEEK(TM_LVL_END_DT)=7 
THEN TM_LVL_END_DT+2 DAYS ELSE TM_LVL_END_DT+1 DAY END) AS YEARWEEK, 
EFF_TM_iD, DATE(SCORING_DT) AS SCORED_DT,
DATE(SCORING_DT)-TM_LVL_END_DT AS SCORE_AGE_IN_DAYS
FROM EDRTLRT.TM_DIM 
LEFT OUTER JOIN EDRTLR.COLCTN_PROBE_DLY_ACCT_OUTPUT ON EFF_TM_iD=TM_ID
WHERE DAYS(TM_LVL_END_DT) >= DAYS(CURRENT_DATE)-70 
AND TM_LVL='Day' AND TM_LVL_END_DT<(CURRENT_DATE)
ORDER BY TM_iD DESC);
DISCONNECT FROM DBCON;
QUIT;


/*REMOVE HOLIDAYS*/
/*PROC SQL NOPRINT;*/
/*CREATE TABLE SASCOLL.ULOCC_SCORE_AGE_V2 AS */
/*SELECT * FROM SASCOLL.ULOCC_SCORE_AGE_V2 WHERE EXPECTED_SCORING_DT NOT IN */
/*		(SELECT HOLIDATE FROM DB2PROD.ONTARIO_HOLIDAY_CALENDAR) */
/*		(SELECT HOLIDATE FROM SASCOLL._10_YEAR_HOLIDAYS)*/
/*;*/
/*CREATE TABLE SASCOLL.ITLC_SCORE_AGE_V2 AS */
/*SELECT * FROM SASCOLL.ITLC_SCORE_AGE_V2 WHERE EXPECTED_SCORING_DT NOT IN */
/*		(SELECT HOLIDATE FROM DB2PROD.ONTARIO_HOLIDAY_CALENDAR) */
/*		(SELECT HOLIDATE FROM SASCOLL._10_YEAR_HOLIDAYS)*/
/*;*/
/*QUIT;*/

/*CALCULATING SCORE AGE IN DAYS FOR NON SCORED DAYS*/

%MACRO ITLC_MISSING;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :MISSINGDAYS FROM SASCOLL.ITLC_SCORE_AGE_V2 WHERE SCORED_DT IS MISSING;
SELECT TM_ID INTO :MISS1-:MISS70 FROM SASCOLL.ITLC_SCORE_AGE_V2 WHERE SCORED_DT IS MISSING ORDER BY TM_ID;
QUIT;

data ITLC_TEMP;
SET SASCOLL.ITLC_SCORE_AGE_V2;
run;

%DO I=1 %TO &MISSINGDAYS;
	PROC SQL NOPRINT;
	SELECT MAX(TM_id) INTO :INTERIMTIME FROM SASCOLL.ITLC_SCORE_AGE_V2 WHERE TM_ID<&&MISS&I; 
	%PUT MISS&I &&MISS&I;
	%PUT INTERIM TIME IS &INTERIMTIME;

	UPDATE ITLC_TEMP
		SET SCORE_AGE_IN_DAYS=(SELECT CASE WHEN EXPECTED_SCORING_DAY='Saturday' THEN SCORE_AGE_IN_DAYS+2 ELSE SCORE_AGE_IN_DAYS+1 END FROM SASCOLL.ITLC_SCORE_AGE_V2 WHERE TM_iD=&INTERIMTIME)
	WHERE TM_ID=&&MISS&I;
	QUIT;

	DATA SASCOLL.ITLC_SCORE_AGE_V2;
	SET ITLC_TEMP;
	RUN;


%END;
%MEND;
%ITLC_MISSING;

/*CALCULATING AVERAGES*/

PROC SQL NOPRINT;
CREATE TABLE ITLC_SCORE_AGE_AVERAGES AS
SELECT YEARWEEK, 
COUNT(CASE WHEN EXPECTED_SCORING_DT NE . AND SCORED_DT =. THEN 1
		   WHEN SCORED_DT NE . AND WEEKDAY(SCORED_DT) IN (3,4,5,6,7) AND SCORE_AGE_IN_DAYS>1 THEN 1 
		   WHEN SCORED_DT NE . AND WEEKDAY(SCORED_DT)=2 AND SCORE_AGE_IN_DAYS>2 THEN 1
	  ELSE . END) AS DELAY_COUNT,
MIN(SCORE_AGE_IN_DAYS) AS MIN_SCORE_AGE,
MAX(SCORE_AGE_IN_DAYS) AS MAX_SCORE_AGE, 
MEAN(CASE WHEN WEEKDAY(SCORED_DT)=2 AND SCORE_AGE_IN_DAYS=2 THEN 1
	  ELSE SCORE_AGE_IN_DAYS END) AS AVG_SCORE_AGE
FROM SASCOLL.ITLC_SCORE_AGE_V2
/*WHERE WEEK(EXPECTED_SCORING_DT,'W')>=WEEK("&SYSDATE"D,'W')-10*/
GROUP BY 1 ORDER BY 1;
QUIT;

/*CALCULATING SCORE AGE IN FOR NON SCORED DAYS*/

%MACRO ULOCC_MISSING;
PROC SQL NOPRINT;
SELECT COUNT(*) INTO :MISSINGDAYS FROM SASCOLL.ULOCC_SCORE_AGE_V2 WHERE SCORED_DT IS MISSING;
SELECT TM_ID INTO :MISS1-:MISS70 FROM SASCOLL.ULOCC_SCORE_AGE_V2 WHERE SCORED_DT IS MISSING ORDER BY TM_ID;
QUIT;

data ULOCC_TEMP;
SET SASCOLL.ULOCC_SCORE_AGE_V2;
run;

%DO I=1 %TO &MISSINGDAYS;
	PROC SQL NOPRINT;
	SELECT MAX(TM_id) INTO :INTERIMTIME FROM SASCOLL.ULOCC_SCORE_AGE_V2 WHERE TM_ID<&&MISS&I; 
	%PUT MISS&I &&MISS&I;
	%PUT INTERIM TIME IS &INTERIMTIME;

	UPDATE ULOCC_TEMP
		SET SCORE_AGE_IN_DAYS=(SELECT CASE WHEN EXPECTED_SCORING_DAY='Friday' THEN SCORE_AGE_IN_DAYS+3 ELSE SCORE_AGE_IN_DAYS+1 END FROM SASCOLL.ULOCC_SCORE_AGE_V2 WHERE TM_iD=&INTERIMTIME)
	WHERE TM_ID=&&MISS&I;
	QUIT;

	DATA SASCOLL.ULOCC_SCORE_AGE_V2;
	SET ULOCC_TEMP;
	RUN;


%END;
%MEND;
%ULOCC_MISSING;

/*CALCULATING AVERAGES*/

PROC SQL NOPRINT;
CREATE TABLE ULOCC_SCORE_AGE_AVERAGES AS
SELECT YEARWEEK, 
COUNT(CASE WHEN EXPECTED_SCORING_DT NE . AND SCORED_DT =. THEN 1
		   WHEN SCORED_DT NE . AND WEEKDAY(SCORED_DT) IN (3,4,5,6) AND SCORE_AGE_IN_DAYS>1 THEN 1 
		   WHEN SCORED_DT NE . AND WEEKDAY(SCORED_DT)=2 AND SCORE_AGE_IN_DAYS>3 THEN 1
	  ELSE . END) AS DELAY_COUNT,
MIN(SCORE_AGE_IN_DAYS) AS MIN_SCORE_AGE,
MAX(SCORE_AGE_IN_DAYS) AS MAX_SCORE_AGE, 
MEAN(CASE WHEN WEEKDAY(SCORED_DT)=2 AND SCORE_AGE_IN_DAYS=3 THEN 1
	  ELSE SCORE_AGE_IN_DAYS END) AS AVG_SCORE_AGE
FROM SASCOLL.ULOCC_SCORE_AGE_V2
/*WHERE WEEK(EXPECTED_SCORING_DT,'W')>=WEEK("&SYSDATE"D,'W')-10*/
GROUP BY 1 ORDER BY 1;
QUIT;

/*DASHBOARD*/
proc template;
 define style color;
 parent = Styles.pearl;
 style body from body /
 backgroundcolor=WHITE;
end;run;

ODS LISTING CLOSE;
options NOLABEL orientation=LANDSCAPE /*papersize=(11in 8.5in)*/
nonumber topmargin=0.2in bottommargin=.25in
leftmargin=.05in rightmargin=.05in;
ods escapechar='^';
ODS PDF FILE="&coll_dir./flat_files/collection_models/collection_models_score_age_report.pdf" notoc;
TITLE1 "COLLECTION MODELS SCORE AGE REPORT";
TITLE2 "DAILY REPORT GENERATED FOR - &SYSDATE";
FOOTNOTE1 HEIGHT=10PT COLOR=BIB 'NOTE1: THERE IS NO WEEKEND OR HOLIDAY PROCESSING. SO ITLC AND ULOCC WILL SHOW SCORE AGE AS 2 AND 3 RESPECTIVELY FOR MONDAYS';
FOOTNOTE2 HEIGHT=10PT COLOR=BIB 'NOTE2: THE DELAY COUNT IN RED IDENTIFIES THE NUMBER OF TIMES A DELAY IN PROCESSING HAS OCCURED EXCLUDING WEEKENDS OR HOLIDAYS';

ODS LAYOUT START WIDTH=11IN HEIGHT=8.5IN STYLE={BACKGROUND=WHITE};
ODS REGION Y=0IN HEIGHT=3IN WIDTH=5.3IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.ITLC_SCORE_AGE_V2 (WHERE=(SCORING_DATE NE .) OBS=8 RENAME=(EXPECTED_SCORING_DT=SCORING_DATE))
STYLE(HEADER)={BACKGROUND=#08E8DE};
TITLE6 "ITLC SCORE AGE FOR LAST 10 DAYS";
COLUMN YEARWEEK SCORING_DATE SCORED_DT SCORE_AGE_IN_DAYS;
DEFINE SCORED_DT / DISPLAY NOPRINT;
DEFINE YEARWEEK / DISPLAY GROUP ORDER=DATA;
DEFINE SCORE_AGE_IN_DAYS / DISPLAY;
DEFINE SCORING_DATE / FORMAT=DATE10. ORDER=INTERNAL;
COMPUTE SCORE_AGE_IN_DAYS;
IF (SCORED_DT=. AND SCORE_AGE_IN_DAYS>1) THEN CALL DEFINE(_COL_,"STYLE","STYLE={FOREGROUND=RED}");
ENDCOMP;
RUN;

ODS REGION Y=0IN X=5.31IN HEIGHT=3IN WIDTH=5.3IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.ULOCC_SCORE_AGE_V2 (WHERE=(SCORING_DATE NE .) OBS=8 RENAME=(EXPECTED_SCORING_DT=SCORING_DATE))
STYLE(HEADER)={BACKGROUND=#08E8DE};
TITLE6 "ULOCC SCORE AGE FOR LAST 10 DAYS";
COLUMN YEARWEEK SCORING_DATE SCORED_DT SCORE_AGE_IN_DAYS ;
DEFINE SCORED_DT / DISPLAY NOPRINT;
DEFINE YEARWEEK / GROUP ORDER=DATA;
DEFINE SCORE_AGE_IN_DAYS / DISPLAY;
DEFINE SCORING_DATE / FORMAT=DATE10. ORDER=INTERNAL;
COMPUTE SCORE_AGE_IN_DAYS;
IF (SCORED_DT=. AND SCORE_AGE_IN_DAYS>1) THEN CALL DEFINE(_COL_,"STYLE","STYLE={FOREGROUND=RED}");
ENDCOMP;
RUN;

/*SCORE DELAY HISTORY*/
ODS REGION Y=3.2IN HEIGHT=3.5IN WIDTH=5.3IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=ITLC_SCORE_AGE_AVERAGES
STYLE(HEADER)={BACKGROUND=#08E8DE};
TITLE6 "ITLC DELAY 10 WEEK HISTORY";
COLUMN YEARWEEK DELAY_COUNT MIN_SCORE_AGE MAX_SCORE_AGE AVG_SCORE_AGE;
DEFINE DELAY_COUNT / DISPLAY;
DEFINE YEARWEEK / ORDER DESCENDING;
DEFINE AVG_SCORE_AGE / FORMAT=5.2;
COMPUTE DELAY_COUNT;
IF DELAY_COUNT>0 THEN CALL DEFINE(_COL_,"STYLE","STYLE={FOREGROUND=RED}");
ENDCOMP;
RUN;

ODS REGION Y=3.2IN X=5.45IN HEIGHT=3.5IN WIDTH=5.3IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=ULOCC_SCORE_AGE_AVERAGES
STYLE(HEADER)={BACKGROUND=#08E8DE};
TITLE6 "ULOCC DELAY 10 WEEK HISTORY";
COLUMN YEARWEEK DELAY_COUNT MIN_SCORE_AGE MAX_SCORE_AGE AVG_SCORE_AGE;
DEFINE DELAY_COUNT / DISPLAY;
DEFINE YEARWEEK / ORDER DESCENDING;
DEFINE AVG_SCORE_AGE / FORMAT=5.2;
COMPUTE DELAY_COUNT;
IF DELAY_COUNT>0 THEN CALL DEFINE(_COL_,"STYLE","STYLE={FOREGROUND=RED}");
ENDCOMP;
RUN;

ODS LAYOUT END;
ods _all_ close;

/*EMAIL DASHBOARD*/
%email_declare;
%macro email;
filename mymail email 
to=(&INTERNAL_LIST)
CC=(&INTERNAL_CC_LIST)
Subject="collection models score age report";

DATA _NULL_;
FILE mymail;
PUT "Hi" //;
PUT "Please find attached a copy of the collection models score age report as of &sysdate.";
PUT " ";
PUT '!EM_ATTACH! ("&coll_dir./flat_files/collection_models/collection_models_score_age_report.pdf")';
PUT " ";
PUT "regards,";
RUN;

%mend email;

%email;

