%coll_autoexec;
%include "&coll_dir./sas/collection_models/email_communication.sas";

%GLOBAL DLY_TM_iD;
%GLOBAL DLY_TM_DATE;

DATA ITLC_FINAL_RESULT;
LENGTH MODEL_SCORECRD_ID $20.;
LENGTH VAR_DESC $80.;
LENGTH TOTAL_WEIGHT 8.;
FORMAT TOTAL_WEIGHT 11.6;
LENGTH ACCTCOUNT 8.;
LENGTH CHARACTER_COUNT 8.;
LENGTH PERCENT_POP 8.;
FORMAT PERCENT_POP PERCENT10.2;
STOP;
RUN;

/*FETCH THE LATEST TIMESTAMP FOR DATA*/
PROC SQL NOPRINT;
SELECT MAX(EFF_TM_ID) INTO :DLY_TM_iD FROM DB2PROD.COLCTN_INDRCT_TERM_LOAN_OUTPUT;
SELECT TM_LVL_END_DT INTO :DLY_TM_DATE FROM DB2PROD.TM_DIM WHERE TM_ID=&DLY_TM_ID;
SELECT MAX(EFF_TM_ID) INTO :PREV_DLY_TM_iD FROM DB2PROD.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD<&DLY_TM_iD;
SELECT TM_LVL_END_DT INTO :PREV_DLY_TM_DATE FROM DB2PROD.TM_DIM WHERE TM_ID=&PREV_DLY_TM_iD;
QUIT;

%PUT LATEST TIME ID IS &DLY_TM_iD;
%PUT PREVIOUS TIME ID IS &PREV_DLY_TM_iD;
%PUT LATEST DATE IS &DLY_TM_DATE;
%PUT PREVIOUS DATE IS &PREV_DLY_TM_DATE;

/*GENERATE DATA FOR LATEST TIME PERIOD*/
%MACRO MODEL_VALIDATION;
/*FOR RECOVERIES*/

PROC SQL NOPRINT;
CONNECT USING DB2PROD AS DBCON;
CREATE TABLE RECOVERIES AS 
SELECT * FROM CONNECTION TO DBCON(
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR1_DESC AS CHAR_DESC, 1 AS CHARID, 
CASE WHEN CHAR1_VAL < 298.5 THEN 63 ELSE 0 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR1_DESC, (CASE WHEN CHAR1_VAL < 298.5 THEN 63 ELSE 0 END)
UNION ALL
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR4_DESC AS CHAR_DESC, 4 AS CHARID, 
CASE WHEN CHAR4_VAL = 1 THEN 0 ELSE 42 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR4_DESC, (CASE WHEN CHAR4_VAL = 1 THEN 0 ELSE 42 END)
UNION ALL
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR5_DESC AS CHAR_DESC, 5 AS CHARID, 
CASE WHEN CHAR5_VAL IS NOT NULL AND CHAR5_VAL<0.12856246567996 THEN 372
	 WHEN CHAR5_VAL IS NOT NULL AND 0.12856246567996 <= CHAR5_VAL AND CHAR5_VAL< 0.27043460513807 THEN 191
	 WHEN CHAR5_VAL IS NOT NULL AND 0.36760879409041 <= CHAR5_VAL AND CHAR5_VAL< 0.45559324295992 THEN 68
	 WHEN CHAR5_VAL IS NOT NULL AND 0.45559324295992 <= CHAR5_VAL THEN 0
 ELSE 136 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR5_DESC, (CASE WHEN CHAR5_VAL IS NOT NULL AND CHAR5_VAL<0.12856246567996 THEN 372
	 WHEN CHAR5_VAL IS NOT NULL AND 0.12856246567996 <= CHAR5_VAL AND CHAR5_VAL< 0.27043460513807 THEN 191
	 WHEN CHAR5_VAL IS NOT NULL AND 0.36760879409041 <= CHAR5_VAL AND CHAR5_VAL< 0.45559324295992 THEN 68
	 WHEN CHAR5_VAL IS NOT NULL AND 0.45559324295992 <= CHAR5_VAL THEN 0
 ELSE 136 END)
UNION ALL
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR2_DESC AS CHAR_DESC, 2 AS CHARID, 
CASE WHEN CHAR2_VAL >0 THEN 110 ELSE 0 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR2_DESC, (CASE WHEN CHAR2_VAL >0 THEN 110 ELSE 0 END)
UNION ALL
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR3_DESC AS CHAR_DESC, 3 AS CHARID, 
CASE WHEN CHAR3_VAL <0 THEN 0 ELSE 123 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR3_DESC, (CASE WHEN CHAR3_VAL <0 THEN 0 ELSE 123 END)
UNION ALL
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR7_DESC AS CHAR_DESC, 7 AS CHARID, 
CASE WHEN CHAR7_VAL IS NULL THEN 52 
	 WHEN CHAR7_VAL <100 THEN 0 ELSE 52 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR7_DESC, (CASE WHEN CHAR7_VAL IS NULL THEN 52 
	 WHEN CHAR7_VAL <100 THEN 0 ELSE 52 END)
UNION ALL
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR6_DESC AS CHAR_DESC, 6 AS CHARID, 
CASE WHEN CHAR6_VAL >=3.5 THEN 0 ELSE 45 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR6_DESC, (CASE WHEN CHAR6_VAL >=3.5 THEN 0 ELSE 45 END)
UNION ALL
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR8_DESC AS CHAR_DESC, 8 AS CHARID, 
CASE WHEN CHAR8_VAL IS NOT NULL AND 4166 <= CHAR8_VAL AND CHAR8_VAL < 8013 THEN 103 
	 WHEN CHAR8_VAL IS NOT NULL AND 8013 <= CHAR8_VAL THEN 193
	ELSE 0 END AS CHAR_SCORE, 
count(*) AS account_COUNT 
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_ID.
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR8_DESC, (CASE WHEN CHAR8_VAL IS NOT NULL AND 4166 <= CHAR8_VAL AND CHAR8_VAL < 8013 THEN 103 
	 WHEN CHAR8_VAL IS NOT NULL AND 8013 <= CHAR8_VAL THEN 193
	ELSE 0 END)
);
DISCONNECT FROM DBCON;
QUIT;


PROC SQL NOPRINT;
INSERT INTO ITLC_FINAL_RESULT 
SELECT SUBQ1.RCVRY_MODEL_SCORECRD_ID AS MODEL_SCORECRD_ID, SUBQ1.CHAR_DESC AS VAR_DESC, SUBQ1.CHAR_WGHT AS TOTAL_WEIGHT, ACCOUNT_COUNT, 
CHARACTER_COUNT, ACCOUNT_COUNT/CHARACTER_COUNT AS PERCENT_POP FROM
(SELECT RCVRY_MODEL_SCORECRD_ID, PRIM.CHAR_DESC, PRIM.CHAR_SCORE AS CHAR_WGHT, ACCOUNT_COUNT
FROM RECOVERIES PRIM) SUBQ1
INNER JOIN (
SELECT RCVRY_MODEL_SCORECRD_ID, CHAR_DESC, SUM(ACCOUNT_COUNT) AS CHARACTER_COUNT FROM RECOVERIES
GROUP BY RCVRY_MODEL_SCORECRD_ID, CHAR_DESC) SUBQ2
ON SUBQ1.CHAR_DESC=SUBQ2.CHAR_DESC AND SUBQ1.RCVRY_MODEL_SCORECRD_ID=SUBQ2.RCVRY_MODEL_SCORECRD_ID;
QUIT;

/*FOR SEGMENTS 1 AND 2*/
/*VAR1 TO VAR8 ATTRIBUTES IN THE DB2 TABLE CONTAINS RECOVERIES AND THEY ARE HANDLED DIFFERENTLY AS ABOVE*/

%DO I=9 %TO 28;
PROC SQL NOPRINT;
CONNECT USING DB2PROD AS DBCON;
CREATE TABLE RESULT&I. AS 
SELECT * FROM CONNECTION TO DBCON(
SELECT SUBQ1.MODEL_SCORECRD_ID, SUBQ1.CHAR&I._DESC AS VAR_DESC, SUBQ1.CHAR&I._WGHT AS TOTAL_WEIGHT, ACCTCOUNT, CHARACTER_COUNT, CAST(ACCTCOUNT AS FLOAT)/CAST(CHARACTER_COUNT AS FLOAT) AS PERCENT_POP FROM
(SELECT MODEL_SCORECRD_ID, PRIM.CHAR&I._DESC, PRIM.CHAR&I._WGHT, COUNT(PRIM.LOAN_NUM) AS ACCTCOUNT
FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT PRIM
WHERE CHAR&I._DESC IS NOT NULL AND PRIM.EFF_TM_iD=&DLY_TM_iD.
GROUP BY PRIM.MODEL_SCORECRD_ID, PRIM.CHAR&I._DESC, PRIM.CHAR&I._WGHT
ORDER BY PRIM.MODEL_SCORECRD_ID, PRIM.CHAR&I._DESC, PRIM.CHAR&I._WGHT
) SUBQ1
INNER JOIN (
SELECT MODEL_SCORECRD_ID, CHAR&I._DESC, COUNT(*) AS CHARACTER_COUNT FROM EDRTLRT.COLCTN_INDRCT_TERM_LOAN_OUTPUT WHERE EFF_TM_iD=&DLY_TM_iD.
GROUP BY MODEL_SCORECRD_ID, CHAR&I._DESC ORDER BY MODEL_SCORECRD_ID, CHAR&I._DESC) SUBQ2
ON SUBQ1.CHAR&I._DESC=SUBQ2.CHAR&I._DESC AND SUBQ1.MODEL_SCORECRD_ID=SUBQ2.MODEL_SCORECRD_ID);
DISCONNECT FROM DBCON;
QUIT;

PROC APPEND BASE=ITLC_FINAL_RESULT DATA=RESULT&I. FORCE; RUN;

%END;
%MEND;

%MODEL_VALIDATION;

/*READ THE REFERENCE DATA WITH WHICH THE LATEST DATA IS COMPARED*/

options MSGLEVEL=I;
proc import out= Model_monitoring_ITLC_segment1 replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - ITLC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "ITLC - cycle 1";
    getnames = yes;
run;
proc import out= Model_monitoring_ITLC_segment2 replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - ITLC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "ITLC cycle 2-3";
    getnames = yes;
run;
proc import out= Model_monitoring_ITLC_recovery replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - ITLC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "Recovery";
    getnames = yes;
run;
proc import out= PSI_threshold replace
    datafile = "&coll_dir./flat_files/collection_models/PSI_threshold.csv"
    dbms = csv;
    getnames = yes;
run;

/*COMPARE THE REFERENCE WITH GENERATED DATA*/
/*BRING IN THE THRESHOLDS INTO VARIABLES*/
PROC SQL NOPRINT;
SELECT PSI INTO :LOWLEVEL FROM PSI_THRESHOLD WHERE PORTFOLIO='ITLC' AND STATUS=0;
SELECT PSI INTO :HIGHLEVEL FROM PSI_THRESHOLD WHERE PORTFOLIO='ITLC' AND STATUS=2;
QUIT;

/*SEGMENT 1*/

PROC SQL NOPRINT;
CREATE TABLE SASCOLL.ITLC_MODEL_SEGMENT1_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(STRIP(VARIABLE)) AS VARIABLE, UPCASE(STRIP(VAR_DESC)) AS VAR_DESC, A.WEIGHT, 
'Base (May-16)'n, PERCENT_POP, (PERCENT_POP-'Base (May-16)'n)*LOG(PERCENT_POP/'Base (May-16)'n) AS PRE_PSI
FROM Model_monitoring_ITLC_segment1 A
LEFT OUTER JOIN ITLC_FINAL_RESULT ON UPCASE(STRIP(VAR_DESC))='C_'||UPCASE(STRIP(VARIABLE))
AND INT(TOTAL_WEIGHT*10**6)=INT(A.WEIGHT*10**6) AND MODEL_SCORECRD_ID='ITLC_B01'
) GROUP BY VARIABLE;

/*SEGMENT 2*/

CREATE TABLE SASCOLL.ITLC_MODEL_SEGMENT2_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(STRIP(VARIABLE)) AS VARIABLE, UPCASE(STRIP(VAR_DESC)) AS VAR_DESC, B.WEIGHT,
'Base (May-16)'n, PERCENT_POP, (PERCENT_POP-'Base (May-16)'n)*LOG(PERCENT_POP/'Base (May-16)'n) AS PRE_PSI
FROM Model_monitoring_ITLC_segment2 B 
LEFT OUTER JOIN ITLC_FINAL_RESULT ON UPCASE(STRIP(VAR_DESC))='C_'||UPCASE(STRIP(VARIABLE))
AND INT(TOTAL_WEIGHT*10**6)=INT(B.WEIGHT*10**6) AND MODEL_SCORECRD_ID='ITLC_B02'
) GROUP BY VARIABLE;


/*RECOVERY SEGMENT*/

CREATE TABLE SASCOLL.ITLC_MODEL_RECOVERY_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(STRIP(VARIABLE)) AS VARIABLE, UPCASE(STRIP(VAR_DESC)) AS VAR_DESC, 'POINTS ASSIGNED'n,
'Base (May-16)'n, PERCENT_POP, (PERCENT_POP-'Base (May-16)'n)*LOG(PERCENT_POP/'Base (May-16)'n) AS PRE_PSI
FROM Model_monitoring_ITLC_recovery 
LEFT OUTER JOIN ITLC_FINAL_RESULT ON UPCASE(STRIP(VAR_DESC))='R_'||UPCASE(STRIP(VARIABLE))
AND TOTAL_WEIGHT='POINTS ASSIGNED'n 
AND VAR_DESC LIKE 'R_%'
) GROUP BY VARIABLE;

QUIT;


/*LOAD DATA TO DB2*/
/*CLEAN UP*/
PROC SQL NOPRINT;
DELETE FROM DB2PROD.COLLECTION_MODEL_ITLC_PSI WHERE TIME_ID=&DLY_TM_ID;
QUIT;

PROC SQL NOPRINT;
INSERT INTO DB2PROD.COLLECTION_MODEL_ITLC_PSI SELECT &DLY_TM_ID AS TIME_ID, 'ITLC_B01' AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.ITLC_MODEL_SEGMENT1_PSI;
INSERT INTO DB2PROD.COLLECTION_MODEL_ITLC_PSI SELECT &DLY_TM_ID AS TIME_ID, 'ITLC_B02' AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.ITLC_MODEL_SEGMENT2_PSI;
INSERT INTO DB2PROD.COLLECTION_MODEL_ITLC_PSI SELECT &DLY_TM_ID AS TIME_ID, 'ITLC_R01' AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.ITLC_MODEL_RECOVERY_PSI;
QUIT;


/*BRING DATA FROM DB2 TO REPORT*/
PROC SQL NOPRINT;
CREATE TABLE SASCOLL.RPT_COLLECTION_MODEL_ITLC_PSI AS 
SELECT PREV.MODEL_SCORECARD_ID, PREV.CHARACTERISTIC, PREV.POPULATION_STABILITY_INDEX AS PREV_PSI LABEL='PREV_PSI', 
CASE WHEN PREV.STATUS='STABLE' THEN 0  
	 WHEN PREV.STATUS='SHIFT' THEN 1
	 WHEN PREV.STATUS='UNSTABLE' THEN 2 END AS PREV_STATUS,
CURR.POPULATION_STABILITY_INDEX AS PSI LABEL='PSI',
CASE WHEN CURR.STATUS='STABLE' THEN 0  
	 WHEN CURR.STATUS='SHIFT' THEN 1
	 WHEN CURR.STATUS='UNSTABLE' THEN 2 END AS STATUS
FROM DB2PROD.COLLECTION_MODEL_ITLC_PSI PREV
FULL JOIN DB2PROD.COLLECTION_MODEL_ITLC_PSI CURR ON PREV.CHARACTERISTIC=CURR.CHARACTERISTIC
AND PREV.MODEL_SCORECARD_ID=CURR.MODEL_SCORECARD_ID
WHERE PREV.TIME_ID=&PREV_DLY_TM_iD AND CURR.TIME_ID=&DLY_TM_iD;
QUIT;

/*DASHBOARD*/
proc template;
 define style color;
 parent = Styles.pearl;
 style body from body /
 backgroundcolor=WHITE;
end;run;

PROC FORMAT;
VALUE COLOR
0='GREEN'
1='YELLOW'
2='RED';
RUN;

ODS LISTING CLOSE;
options orientation=landscape /*papersize=(11in 8.5in)*/
nonumber topmargin=0.2in bottommargin=.25in
leftmargin=.05in rightmargin=.05in;
ods escapechar='^';
ODS PDF FILE="&coll_dir./flat_files/collection_models/itlc_collections_psi_report.pdf" notoc;
TITLE1 "ITLC COLLECTION MODELS PSI REPORT";
TITLE2 "DAILY REPORT GENERATED FOR &DLY_TM_DATE.";
FOOTNOTE;

ODS LAYOUT START WIDTH=10.5IN HEIGHT=8IN STYLE={BACKGROUND=WHITE};
ODS REGION Y=0IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_ITLC_PSI (WHERE=(MODEL_SCORECARD_ID='ITLC_B01'));
TITLE6 "SEGMENT 1";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=0IN X=5.26IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_ITLC_PSI (WHERE=(MODEL_SCORECARD_ID='ITLC_B02'));
TITLE6 "SEGMENT 2";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=3.54IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_ITLC_PSI (WHERE=(MODEL_SCORECARD_ID='ITLC_R01'));
TITLE6 "RECOVERY";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=4.54IN X=5.26IN HEIGHT=3IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=PSI_THRESHOLD (WHERE=(PORTFOLIO='ITLC'));
TITLE6 "LEGEND";
COLUMN PSI_CONDITION DESCRIPTION STATUS;
DEFINE STATUS / GROUP ORDER STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
FOOTNOTE "NOTE: PREV PSI AND PREV STATUS REFERS TO VALUES OF PREVIOUS DAY";
RUN;


ODS LAYOUT END;
ods _all_ close;

/*STAGE 7*/
/*EMAIL DASHBOARD ON YELLOW/RED*/
%email_declare;
%macro email;
filename mymail email 
to=(&INTERNAL_LIST)
CC=(&INTERNAL_CC_LIST)
Subject="ITLC collection models PSI report";

DATA _NULL_;
FILE mymail;
PUT "Hi" //;
PUT "Please find attached a copy of the ITLC PSI report as of &sysdate.";
PUT " ";
PUT "Today's report having attributes flagged Yellow or Red need your attention.";
PUT '!EM_ATTACH! ("&coll_dir./flat_files/collection_models/itlc_collections_psi_report.pdf")';
PUT " ";
PUT "regards,";
RUN;

%mend email;

%macro DISTRIBUTION;
PROC SQL NOPRINT;
SELECT MAX(STATUS) INTO :ERROR_CODE FROM SASCOLL.RPT_COLLECTION_MODEL_ULOCC_PSI;
QUIT;

  %if &ERROR_CODE > 0 %then %do;
  		%email;
     %end;
  %else %do;
  %end;
%mend DISTRIBUTION;

%DISTRIBUTION;
