%coll_autoexec;
%include "&coll_dir./sas/collection_models/email_communication.sas";

%GLOBAL MTH_TM_iD;
%GLOBAL MTH_TM_DATE;
%GLOBAL PREV_MTH_TM_iD;
%GLOBAL PREV_MTH_TM_DATE;

DATA FINAL_RESULT;
LENGTH MODEL_SCORECRD_ID 8.;
LENGTH VAR_DESC $80.;
LENGTH BIN $50.;
LENGTH TOTAL_WEIGHT 8.;
FORMAT TOTAL_WEIGHT 11.6;
LENGTH PERCENT_POP 8.;
FORMAT PERCENT_POP PERCENT10.2;
STOP;
RUN;

/*FETCH THE LATEST TIMESTAMP FOR DATA*/
PROC SQL NOPRINT;
SELECT MAX(EFF_TM_iD) INTO :MTH_TM_iD FROM DB2PROD.COLCTN_SCORING_DTL_MODEL_OUTPUT;
SELECT TM_LVL_END_DT INTO :MTH_TM_DATE FROM DB2PROD.TM_DIM WHERE TM_ID=&MTH_TM_ID;
SELECT MAX(EFF_TM_ID) INTO :PREV_MTH_TM_iD FROM DB2PROD.COLCTN_SCORING_DTL_MODEL_OUTPUT WHERE EFF_TM_iD<&MTH_TM_iD;
SELECT TM_LVL_END_DT INTO :PREV_MTH_TM_DATE FROM DB2PROD.TM_DIM WHERE TM_ID=&PREV_MTH_TM_iD;
QUIT;

%PUT LATEST DATE IS &MTH_TM_DATE;
%PUT PREVIOUS DATE IS &PREV_MTH_TM_DATE;

/*GENERATE DATA FOR LATEST TIME PERIOD*/
%MACRO MODEL_VALIDATION;
%DO I=1 %TO 25;
PROC SQL NOPRINT;
CONNECT USING DB2PROD AS DBCON;
CREATE TABLE RESULT&I. AS 
SELECT * FROM CONNECTION TO DBCON(
SELECT SUBQ1.MODEL_SCORECRD_ID, SUBQ1.CHAR&I._DESC AS VAR_DESC, '' AS BIN, SUBQ1.CHAR&I._WGHT AS TOTAL_WEIGHT, CAST(ACCTCOUNT AS FLOAT)/CAST(CHARACTER_COUNT AS FLOAT) AS PERCENT_POP FROM
(SELECT MODEL_SCORECRD_ID, PRIM.CHAR&I._DESC, PRIM.CHAR&I._WGHT, COUNT(PRIM.CORPTN_AND_ACCT_NUM) AS ACCTCOUNT
FROM EDRTLRT.COLCTN_SCORING_DTL_MODEL_OUTPUT PRIM
WHERE CHAR&I._DESC IS NOT NULL AND PRIM.EFF_TM_iD=&MTH_TM_iD.
GROUP BY PRIM.MODEL_SCORECRD_ID, PRIM.CHAR&I._DESC, PRIM.CHAR&I._WGHT
ORDER BY PRIM.MODEL_SCORECRD_ID, PRIM.CHAR&I._DESC, PRIM.CHAR&I._WGHT
) SUBQ1
INNER JOIN (
SELECT MODEL_SCORECRD_ID, CHAR&I._DESC, COUNT(*) AS CHARACTER_COUNT FROM EDRTLRT.COLCTN_SCORING_DTL_MODEL_OUTPUT WHERE EFF_TM_iD=&MTH_TM_iD.
GROUP BY MODEL_SCORECRD_ID, CHAR&I._DESC ORDER BY MODEL_SCORECRD_ID, CHAR&I._DESC) SUBQ2
ON SUBQ1.CHAR&I._DESC=SUBQ2.CHAR&I._DESC AND SUBQ1.MODEL_SCORECRD_ID=SUBQ2.MODEL_SCORECRD_ID);
DISCONNECT FROM DBCON;
QUIT;

PROC APPEND BASE=FINAL_RESULT DATA=RESULT&I. FORCE; RUN;
%END;
/*CUSTOM PROCESS FOR MTH_SINCE_MOST_RECNT_DLQNT IN DESC DUE TO DUPLICATE WEIGHTS I.E. 44*/
PROC SQL NOPRINT;
DELETE FROM FINAL_RESULT WHERE MODEL_SCORECRD_ID=63003 AND VAR_DESC='MTH_SINCE_MOST_RECNT_DLQNT';
QUIT;

PROC SQL NOPRINT;
CONNECT USING DB2PROD AS DBCON;
CREATE TABLE CUSTOM_CHARACTERISTIC AS 
SELECT * FROM CONNECTION TO DBCON(
SELECT SUBQ1.MODEL_SCORECRD_ID, SUBQ1.CHAR4_DESC AS VAR_DESC, SUBQ1.BIN, SUBQ1.TOTAL_WEIGHT, CAST(ACCTCOUNT AS FLOAT)/CAST(CHARACTER_COUNT AS FLOAT) AS PERCENT_POP FROM
(SELECT PRIM.MODEL_SCORECRD_ID, PRIM.CHAR4_DESC,
CASE WHEN PRIM.CHAR4_VAL IS NULL OR PRIM.CHAR4_VAL<2 then 'x < 2  OR Missing(x)' 
	 WHEN 2<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<3 THEN '2 <= x < 3'
	 WHEN 3<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<5 THEN '3 <= x < 5'
	 WHEN 5<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<999 THEN '5 <= x < 999'
	 WHEN 999<=PRIM.CHAR4_VAL THEN '999 <= x' END AS BIN,
CASE WHEN PRIM.CHAR4_VAL IS NULL OR PRIM.CHAR4_VAL<2 then 44 
	 WHEN 2<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<3 THEN 36
	 WHEN 3<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<5 THEN 48
	 WHEN 5<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<999 THEN 55
	 WHEN 999<=PRIM.CHAR4_VAL THEN 44 END AS TOTAL_WEIGHT, COUNT(PRIM.CORPTN_AND_ACCT_NUM) AS ACCTCOUNT
FROM EDRTLRT.COLCTN_SCORING_DTL_MODEL_OUTPUT PRIM
WHERE PRIM.MODEL_SCORECRD_ID=63003 AND PRIM.EFF_TM_iD=17471
GROUP BY PRIM.MODEL_SCORECRD_ID, PRIM.CHAR4_DESC, 
CASE WHEN PRIM.CHAR4_VAL IS NULL OR PRIM.CHAR4_VAL<2 then 'x < 2  OR Missing(x)' 
	 WHEN 2<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<3 THEN '2 <= x < 3'
	 WHEN 3<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<5 THEN '3 <= x < 5'
	 WHEN 5<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<999 THEN '5 <= x < 999'
	 WHEN 999<=PRIM.CHAR4_VAL THEN '999 <= x' END,
CASE WHEN PRIM.CHAR4_VAL IS NULL OR PRIM.CHAR4_VAL<2 then 44 
	 WHEN 2<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<3 THEN 36
	 WHEN 3<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<5 THEN 48
	 WHEN 5<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<999 THEN 55
	 WHEN 999<=PRIM.CHAR4_VAL THEN 44 END
ORDER BY PRIM.MODEL_SCORECRD_ID, PRIM.CHAR4_DESC, CASE WHEN PRIM.CHAR4_VAL IS NULL OR PRIM.CHAR4_VAL<2 then 44 
	 WHEN 2<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<3 THEN 36
	 WHEN 3<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<5 THEN 48
	 WHEN 5<=PRIM.CHAR4_VAL AND PRIM.CHAR4_VAL<999 THEN 55
	 WHEN 999<=PRIM.CHAR4_VAL THEN 44 END) SUBQ1
INNER JOIN (
SELECT MODEL_SCORECRD_ID, CHAR4_DESC, COUNT(*) AS CHARACTER_COUNT FROM EDRTLRT.COLCTN_SCORING_DTL_MODEL_OUTPUT WHERE EFF_TM_iD=17471
GROUP BY MODEL_SCORECRD_ID, CHAR4_DESC ORDER BY MODEL_SCORECRD_ID, CHAR4_DESC) SUBQ2
ON SUBQ1.CHAR4_DESC=SUBQ2.CHAR4_DESC AND SUBQ1.MODEL_SCORECRD_ID=SUBQ2.MODEL_SCORECRD_ID
);
DISCONNECT FROM DBCON;
QUIT;

PROC APPEND BASE=FINAL_RESULT DATA=CUSTOM_CHARACTERISTIC FORCE; RUN;

%MEND;

%MODEL_VALIDATION;

/*READ THE REFERENCE DATA WITH WHICH THE LATEST DATA IS COMPARED*/

options MSGLEVEL=I;
proc import out= Model_monitoring_CCC_segment1 replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - CCC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "Cycle 1 (22-29 delq)";
    getnames = yes;
run;
proc import out= Model_monitoring_CCC_segment2 replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - CCC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "Cycle 2 (30-59 delq)";
    getnames = yes;
run;
proc import out= Model_monitoring_CCC_segment3 replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - CCC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "Cycle 3 (60-89 delq)";
    getnames = yes;
run;
proc import out= PSI_threshold replace
    datafile = "&coll_dir./flat_files/collection_models/PSI_threshold.csv"
    dbms = csv;
    getnames = yes;
run;

/*COMPARE THE REFERENCE WITH GENERATED DATA*/
/*BRING IN THE THRESHOLDS INTO VARIABLES*/
PROC SQL NOPRINT;
SELECT PSI INTO :LOWLEVEL FROM PSI_THRESHOLD WHERE PORTFOLIO='CCC' AND STATUS=0;
SELECT PSI INTO :HIGHLEVEL FROM PSI_THRESHOLD WHERE PORTFOLIO='CCC' AND STATUS=2;
QUIT;

/*SEGMENT 1*/

PROC SQL NOPRINT;
CREATE TABLE SASCOLL.CCC_MODEL_SEGMENT1_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(VARIABLE) AS VARIABLE, VAR_DESC, 'POINTS ASSIGNED'n, TOTAL_WEIGHT, 'Base (Jan-16)'n, PERCENT_POP, (PERCENT_POP-'Base (Jan-16)'n)*LOG(PERCENT_POP/'Base (Jan-16)'n) AS PRE_PSI
FROM Model_monitoring_CCC_segment1
LEFT OUTER JOIN FINAL_RESULT ON STRIP(VAR_DESC)=STRIP(VARIABLE)
AND TOTAL_WEIGHT='POINTS ASSIGNED'n AND MODEL_SCORECRD_ID=63001
) GROUP BY VARIABLE;

/*SEGMENT 2*/

CREATE TABLE SASCOLL.CCC_MODEL_SEGMENT2_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(VARIABLE) AS VARIABLE, VAR_DESC, 'POINTS ASSIGNED'n, TOTAL_WEIGHT, 'Base (Jan-16)'n, PERCENT_POP, (PERCENT_POP-'Base (Jan-16)'n)*LOG(PERCENT_POP/'Base (Jan-16)'n) AS PRE_PSI
FROM Model_monitoring_CCC_segment2
LEFT OUTER JOIN FINAL_RESULT ON STRIP(VAR_DESC)=STRIP(VARIABLE)
AND TOTAL_WEIGHT='POINTS ASSIGNED'n AND MODEL_SCORECRD_ID=63002
) GROUP BY VARIABLE;

/*SEGMENT 3*/

CREATE TABLE SASCOLL.CCC_MODEL_SEGMENT3_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(VARIABLE) AS VARIABLE, VAR_DESC, 'POINTS ASSIGNED'n, TOTAL_WEIGHT, 'Base (Jan-16)'n, PERCENT_POP, (PERCENT_POP-'Base (Jan-16)'n)*LOG(PERCENT_POP/'Base (Jan-16)'n) AS PRE_PSI
FROM Model_monitoring_CCC_segment3 SEG
LEFT OUTER JOIN FINAL_RESULT RES ON STRIP(VAR_DESC)=STRIP(VARIABLE)
AND TOTAL_WEIGHT='POINTS ASSIGNED'n AND 
CASE WHEN STRIP(VAR_DESC)='MTH_SINCE_MOST_RECNT_DLQNT' THEN MODEL_SCORECRD_ID=63003 AND SEG.BIN=RES.BIN
ELSE MODEL_SCORECRD_ID=63003 END
) GROUP BY VARIABLE;
QUIT;

/*LOAD DATA TO DB2*/
/*CLEAN UP*/
PROC SQL NOPRINT;
DELETE FROM DB2PROD.COLLECTION_MODEL_CCC_PSI WHERE TIME_ID=&MTH_TM_ID;
QUIT;

PROC SQL NOPRINT;
INSERT INTO DB2PROD.COLLECTION_MODEL_CCC_PSI SELECT &MTH_TM_iD AS TIME_ID, 63001 AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.CCC_MODEL_SEGMENT1_PSI;
INSERT INTO DB2PROD.COLLECTION_MODEL_CCC_PSI SELECT &MTH_TM_iD AS TIME_ID, 63002 AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.CCC_MODEL_SEGMENT2_PSI;
INSERT INTO DB2PROD.COLLECTION_MODEL_CCC_PSI SELECT &MTH_TM_iD AS TIME_ID, 63003 AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.CCC_MODEL_SEGMENT3_PSI;
QUIT;


/*BRING DATA FROM DB2 TO REPORT*/
PROC SQL NOPRINT;
CREATE TABLE SASCOLL.RPT_COLLECTION_MODEL_CCC_PSI AS 
SELECT PREV.MODEL_SCORECARD_ID, PREV.CHARACTERISTIC, PREV.POPULATION_STABILITY_INDEX AS PREV_PSI LABEL='PREV_PSI', 
CASE WHEN PREV.STATUS='STABLE' THEN 0  
	 WHEN PREV.STATUS='SHIFT' THEN 1
	 WHEN PREV.STATUS='UNSTABLE' THEN 2 END AS PREV_STATUS,
CURR.POPULATION_STABILITY_INDEX AS PSI LABEL='PSI',
CASE WHEN CURR.STATUS='STABLE' THEN 0  
	 WHEN CURR.STATUS='SHIFT' THEN 1
	 WHEN CURR.STATUS='UNSTABLE' THEN 2 END AS STATUS
FROM DB2PROD.COLLECTION_MODEL_CCC_PSI PREV
FULL JOIN DB2PROD.COLLECTION_MODEL_CCC_PSI CURR ON PREV.CHARACTERISTIC=CURR.CHARACTERISTIC
AND PREV.MODEL_SCORECARD_ID=CURR.MODEL_SCORECARD_ID
WHERE PREV.TIME_ID=&PREV_MTH_TM_iD AND CURR.TIME_ID=&MTH_TM_iD;
QUIT;

/*DASHBOARD*/
proc template;
 define style color;
 parent = Styles.pearl;
 style body from body /
 backgroundcolor=WHITE;
end;run;

PROC FORMAT;
VALUE COLOR
0='GREEN'
1='YELLOW'
2='RED';
RUN;

ODS LISTING CLOSE;
options orientation=landscape /*papersize=(11in 8.5in)*/
nonumber topmargin=0.2in bottommargin=.25in
leftmargin=.05in rightmargin=.05in;
ods escapechar='^';
ODS PDF FILE="&coll_dir./flat_files/collection_models/ccc_collections_psi_report.pdf" notoc;
TITLE1 "CREDIT CARD COLLECTION MODELS PSI REPORT";
TITLE2 "MONTHLY REPORT GENERATED FOR &MTH_TM_DATE.";
FOOTNOTE;

ODS LAYOUT START WIDTH=10.5IN HEIGHT=8IN STYLE={BACKGROUND=WHITE};
ODS REGION Y=0IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_CCC_PSI (WHERE=(MODEL_SCORECARD_ID=63001));
TITLE6 "SEGMENT 1";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=0IN X=5.26IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_CCC_PSI (WHERE=(MODEL_SCORECARD_ID=63002));
TITLE6 "SEGMENT 2";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=3.54IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_CCC_PSI (WHERE=(MODEL_SCORECARD_ID=63003));
TITLE6 "SEGMENT 3";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=4.54IN X=5.26IN HEIGHT=3IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=PSI_THRESHOLD (WHERE=(PORTFOLIO='CCC'));
TITLE6 "LEGEND";
COLUMN PSI_CONDITION DESCRIPTION STATUS;
DEFINE STATUS / GROUP ORDER STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
FOOTNOTE "NOTE: PREV PSI AND PREV STATUS REFERS TO VALUES OF PREVIOUS MONTH";
RUN;


ODS LAYOUT END;
ods _all_ close;

/*STAGE 7*/
/*EMAIL DASHBOARD ON YELLOW/RED*/
%email_declare;
%macro email;
filename mymail email 
to=(&INTERNAL_LIST)
CC=(&INTERNAL_CC_LIST)
Subject="CCC collection models PSI report";

DATA _NULL_;
FILE mymail;
PUT "Hi" //;
PUT "Please find attached a copy of the CCC PSI report as of &sysdate.";
PUT " ";
PUT "Today's report having attributes flagged Yellow or Red need your attention.";
PUT '!EM_ATTACH! ("&coll_dir./flat_files/collection_models/ccc_collections_psi_report.pdf")';
PUT " ";
PUT "regards,";
RUN;

%mend email;

%macro DISTRIBUTION;
PROC SQL NOPRINT;
SELECT MAX(STATUS) INTO :ERROR_CODE FROM SASCOLL.RPT_COLLECTION_MODEL_ULOCC_PSI;
QUIT;

  %if &ERROR_CODE > 0 %then %do;
  		%email;
     %end;
  %else %do;
  %end;
%mend DISTRIBUTION;

%DISTRIBUTION;
