%coll_autoexec;
%include "&coll_dir./sas/collection_models/email_communication.sas";

%GLOBAL DLY_TM_iD;
%GLOBAL DLY_TM_DATE;

DATA ULOCC_FINAL_RESULT;
LENGTH MODEL_SCORECRD_ID $20.;
LENGTH VAR_DESC $80.;
LENGTH VAR_SCORE 8.;
FORMAT VAR_SCORE 8.;
LENGTH ACCOUNT_COUNT 8.;
LENGTH CHARACTER_COUNT 8.;
LENGTH PERCENT_POP 8.;
FORMAT PERCENT_POP PERCENT10.2;
STOP;
RUN;

/*FETCH THE LATEST TIMESTAMP FOR DATA*/
PROC SQL NOPRINT;
SELECT MAX(EFF_TM_ID) INTO :DLY_TM_iD FROM DB2PROD.ULOC_COLCTN_MODEL_OUTPUT;
SELECT TM_LVL_END_DT INTO :DLY_TM_DATE FROM DB2PROD.TM_DIM WHERE TM_ID=&DLY_TM_ID;
SELECT MAX(EFF_TM_ID) INTO :PREV_DLY_TM_iD FROM DB2PROD.ULOC_COLCTN_MODEL_OUTPUT WHERE EFF_TM_iD<&DLY_TM_iD;
SELECT TM_LVL_END_DT INTO :PREV_DLY_TM_DATE FROM DB2PROD.TM_DIM WHERE TM_ID=&PREV_DLY_TM_iD;
QUIT;

%PUT LATEST TIME ID IS &DLY_TM_iD;
%PUT PREVIOUS TIME ID IS &PREV_DLY_TM_iD;
%PUT LATEST DATE IS &DLY_TM_DATE;
%PUT PREVIOUS DATE IS &PREV_DLY_TM_DATE;

/*GENERATE DATA FOR LATEST TIME PERIOD*/
PROC SQL NOPRINT;
CONNECT USING DB2PROD AS DBCON;
INSERT INTO ULOCC_FINAL_RESULT 
SELECT * FROM CONNECTION TO DBCON(
SELECT SUBQ1.MODEL_SCORECRD_ID, SUBQ1.VAR_DESC, SUBQ1.VAR_SCORE, ACCOUNT_COUNT, CHARACTER_COUNT, 
(CAST(ACCOUNT_COUNT AS FLOAT)/CAST(CHARACTER_COUNT AS FLOAT)) AS PERCENT_POP FROM

(SELECT t1.MODEL_SCORECRD_ID, t2.VAR_DESC, t2.VAR_SCORE, COUNT(*) AS ACCOUNT_COUNT
      FROM EDRTLRT.ULOC_COLCTN_MODEL_OUTPUT t1, EDRTLRT.ULOC_COLCTN_MODEL_OUTPUT_VAR t2
      WHERE (t1.EFF_TM_ID = t2.EFF_TM_ID AND t1.ACCT_ID = t2.ACCT_ID) AND  t1.EFF_TM_ID = &DLY_TM_iD
GROUP BY t1.MODEL_SCORECRD_ID, t2.VAR_DESC, t2.VAR_SCORE) SUBQ1

INNER JOIN (
SELECT t1.MODEL_SCORECRD_ID, t2.VAR_DESC, COUNT(*) AS CHARACTER_COUNT
      FROM EDRTLRT.ULOC_COLCTN_MODEL_OUTPUT t1, EDRTLRT.ULOC_COLCTN_MODEL_OUTPUT_VAR t2
      WHERE (t1.EFF_TM_ID = t2.EFF_TM_ID AND t1.ACCT_ID = t2.ACCT_ID) AND  t1.EFF_TM_ID = &DLY_TM_iD
GROUP BY t1.MODEL_SCORECRD_ID, t2.VAR_DESC) SUBQ2

ON SUBQ1.VAR_DESC=SUBQ2.VAR_DESC AND SUBQ1.MODEL_SCORECRD_ID=SUBQ2.MODEL_SCORECRD_ID);
DISCONNECT FROM DBCON;
QUIT;

/*READ THE REFERENCE DATA WITH WHICH THE LATEST DATA IS COMPARED*/

options MSGLEVEL=I;
proc import out= Model_monitoring_ULOCC_segment1 replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - ULOC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "ULOC - cycle 1";
    getnames = yes;
run;
proc import out= Model_monitoring_ULOCC_segment2 replace
    datafile = "&coll_dir./flat_files/collection_models/Model monitoring - ULOC Characteristics PSI.xlsx"
    dbms = xlsx;
    sheet = "ULOC cycle 2-3";
    getnames = yes;
run;
proc import out= PSI_threshold replace
    datafile = "&coll_dir./flat_files/collection_models/PSI_threshold.csv"
    dbms = csv;
    getnames = yes;
run;

/*COMPARE THE REFERENCE WITH GENERATED DATA*/
/*BRING IN THE THRESHOLDS INTO VARIABLES*/
PROC SQL NOPRINT;
SELECT PSI INTO :LOWLEVEL FROM PSI_THRESHOLD WHERE PORTFOLIO='ULOCC' AND STATUS=0;
SELECT PSI INTO :HIGHLEVEL FROM PSI_THRESHOLD WHERE PORTFOLIO='ULOCC' AND STATUS=2;
QUIT;

/*SEGMENT 1*/

PROC SQL NOPRINT;
CREATE TABLE SASCOLL.ULOCC_MODEL_SEGMENT1_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(VARIABLE) AS VARIABLE, VAR_DESC, 'POINTS ASSIGNED'n, 'Base (Jan-2013)'n, PERCENT_POP, (PERCENT_POP-'Base (Jan-2013)'n)*LOG(PERCENT_POP/'Base (Jan-2013)'n) AS PRE_PSI
FROM Model_monitoring_ULOCC_segment1
LEFT OUTER JOIN ULOCC_FINAL_RESULT ON STRIP(VAR_DESC)=STRIP(VARIABLE)
AND VAR_SCORE='POINTS ASSIGNED'n AND MODEL_SCORECRD_ID='ULOC_B01'
) GROUP BY VARIABLE;

/*SEGMENT 2*/

CREATE TABLE SASCOLL.ULOCC_MODEL_SEGMENT2_PSI AS 
SELECT VARIABLE, SUM(PRE_PSI) AS PSI,
CASE WHEN SUM(PRE_PSI)<&LOWLEVEL THEN 0
	 WHEN SUM(PRE_PSI)>=&LOWLEVEL AND SUM(PRE_PSI)<&HIGHLEVEL THEN 1
	 WHEN SUM(PRE_PSI)>=&HIGHLEVEL THEN 2
	 END AS STATUS
FROM 
(
SELECT UPCASE(VARIABLE) AS VARIABLE, VAR_DESC, 'POINTS ASSIGNED'n, 'Base (Jan-16)'n, PERCENT_POP, (PERCENT_POP-'Base (Jan-16)'n)*LOG(PERCENT_POP/'Base (Jan-16)'n) AS PRE_PSI
FROM Model_monitoring_ULOCC_segment2
LEFT OUTER JOIN ULOCC_FINAL_RESULT ON STRIP(VAR_DESC)=STRIP(VARIABLE)
AND VAR_SCORE='POINTS ASSIGNED'n AND MODEL_SCORECRD_ID='ULOC_B02'
) GROUP BY VARIABLE;
QUIT;


/*LOAD DATA TO DB2*/
/*CLEAN UP*/
PROC SQL NOPRINT;
DELETE FROM DB2PROD.COLLECTION_MODEL_ULOCC_PSI WHERE TIME_ID=&DLY_TM_ID;
QUIT;

PROC SQL NOPRINT;
INSERT INTO DB2PROD.COLLECTION_MODEL_ULOCC_PSI SELECT &DLY_TM_ID AS TIME_ID, 'ULOC_B01' AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.ULOCC_MODEL_SEGMENT1_PSI;
INSERT INTO DB2PROD.COLLECTION_MODEL_ULOCC_PSI SELECT &DLY_TM_ID AS TIME_ID, 'ULOC_B02' AS MODEL_SCORECARD_ID,
VARIABLE AS CHARACTERISTIC, PSI AS POPULATION_STABILITY_INDEX,
CASE WHEN STATUS=0 THEN 'STABLE' WHEN STATUS=1 THEN 'SHIFT' WHEN STATUS=2 THEN 'UNSTABLE' END AS STATUS, DATETIME() AS INSRT_PROCESS_TMSTMP
FROM SASCOLL.ULOCC_MODEL_SEGMENT2_PSI;
QUIT;

/*BRING DATA FROM DB2 TO REPORT*/
PROC SQL NOPRINT;
CREATE TABLE SASCOLL.RPT_COLLECTION_MODEL_ULOCC_PSI AS 
SELECT PREV.MODEL_SCORECARD_ID, PREV.CHARACTERISTIC, PREV.POPULATION_STABILITY_INDEX AS PREV_PSI LABEL='PREV_PSI', 
CASE WHEN PREV.STATUS='STABLE' THEN 0  
	 WHEN PREV.STATUS='SHIFT' THEN 1
	 WHEN PREV.STATUS='UNSTABLE' THEN 2 END AS PREV_STATUS,
CURR.POPULATION_STABILITY_INDEX AS PSI LABEL='PSI',
CASE WHEN CURR.STATUS='STABLE' THEN 0  
	 WHEN CURR.STATUS='SHIFT' THEN 1
	 WHEN CURR.STATUS='UNSTABLE' THEN 2 END AS STATUS
FROM DB2PROD.COLLECTION_MODEL_ULOCC_PSI PREV
FULL JOIN DB2PROD.COLLECTION_MODEL_ULOCC_PSI CURR ON PREV.CHARACTERISTIC=CURR.CHARACTERISTIC
AND PREV.MODEL_SCORECARD_ID=CURR.MODEL_SCORECARD_ID
WHERE PREV.TIME_ID=&PREV_DLY_TM_iD AND CURR.TIME_ID=&DLY_TM_iD;
QUIT;

/*DASHBOARD*/
proc template;
 define style color;
 parent = Styles.pearl;
 style body from body /
 backgroundcolor=WHITE;
end;run;

PROC FORMAT;
VALUE COLOR
0='GREEN'
1='YELLOW'
2='RED';
RUN;

ODS LISTING CLOSE;
options orientation=landscape /*papersize=(11in 8.5in)*/
nonumber topmargin=0.2in bottommargin=.25in
leftmargin=.05in rightmargin=.05in;
ods escapechar='^';
ODS PDF FILE="&coll_dir./flat_files/collection_models/ulocc_collections_psi_report.pdf" notoc;
TITLE1 "ULOCC COLLECTION MODELS PSI REPORT";
TITLE2 "DAILY REPORT GENERATED FOR &DLY_TM_DATE.";
FOOTNOTE;

ODS LAYOUT START WIDTH=10.5IN HEIGHT=8IN STYLE={BACKGROUND=WHITE};
ODS REGION Y=0IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_ULOCC_PSI (WHERE=(MODEL_SCORECARD_ID='ULOC_B01'));
TITLE6 "SEGMENT 1";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=0IN X=5.26IN HEIGHT=4IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=SASCOLL.RPT_COLLECTION_MODEL_ULOCC_PSI (WHERE=(MODEL_SCORECARD_ID='ULOC_B02'));
TITLE6 "SEGMENT 2";
COLUMN CHARACTERISTIC PREV_PSI PREV_STATUS PSI STATUS;
DEFINE CHARACTERISTIC / GROUP ORDER;
DEFINE PREV_STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
DEFINE STATUS / STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
RUN;

ODS REGION Y=4.54IN X=5.26IN HEIGHT=3IN WIDTH=5.24IN STYLE={BACKGROUND=WHITE};
PROC REPORT DATA=PSI_THRESHOLD (WHERE=(PORTFOLIO='CCC'));
TITLE6 "LEGEND";
COLUMN PSI_CONDITION DESCRIPTION STATUS;
DEFINE STATUS / GROUP ORDER STYLE(COLUMN)={BACKGROUND=COLOR. FOREGROUND=COLOR.};
FOOTNOTE "NOTE: PREV PSI AND PREV STATUS REFERS TO VALUES OF PREVIOUS DAY";
RUN;


ODS LAYOUT END;
ods _all_ close;

/*STAGE 7*/
/*EMAIL DASHBOARD ON YELLOW/RED*/
%email_declare;
%macro email;
filename mymail email 
to=(&INTERNAL_LIST)
CC=(&INTERNAL_CC_LIST)
Subject="ULOC collection models PSI report";

DATA _NULL_;
FILE mymail;
PUT "Hi" //;
PUT "Please find attached a copy of the ULOC PSI report as of &sysdate.";
PUT " ";
PUT "Today's report having attributes flagged Yellow or Red need your attention.";
PUT '!EM_ATTACH! ("&coll_dir./flat_files/collection_models/ulocc_collections_psi_report.pdf")';
PUT " ";
PUT "regards,";
RUN;

%mend email;

%macro DISTRIBUTION;
PROC SQL NOPRINT;
SELECT MAX(STATUS) INTO :ERROR_CODE FROM SASCOLL.RPT_COLLECTION_MODEL_ULOCC_PSI;
QUIT;

  %if &ERROR_CODE > 0 %then %do;
  		%email;
     %end;
  %else %do;
  %end;
%mend DISTRIBUTION;

%DISTRIBUTION;

