UPDATE (SELECT * FROM EDRTLRP1D.BASEL_ACCT_DIM WHERE BASEL_ACCT_ID IN (SELECT BASEL_ACCT_ID FROM ( 
SELECT BASEL_ACCT_ID,RANK()OVER (PARTITION BY acct_num ORDER BY INSRT_PROCESS_TMSTMP) AS acctrank, acct_num, SRC_APP_CD,src_sys_del_dt,src_sys_del_f,insrt_process_tmstmp FROM EDRTLRP1D.BASEL_ACCT_DIM WHERE ACCT_NUM IN 
(SELECT acct_num FROM EDRTLRP1D.BASEL_ACCT_DIM bad WHERE SRC_APP_CD = 'TNG-MOR' 
AND (SRC_SYS_DEL_DT IS NULL OR SRC_SYS_DEL_DT='9999-12-31') 
GROUP BY acct_num HAVING COUNT(*)>1)
and (SRC_SYS_DEL_DT IS NULL OR SRC_SYS_DEL_DT='9999-12-31'))a
WHERE a.acctrank=1 
ORDER BY acct_num,acctrank)) AS E 
SET E.SRC_SYS_DEL_DT='2022-01-31',
	E.SRC_SYS_DEL_F='Y';