/************ BASEL III CHANGES ****************************************/
/* DDL CHANGES FOR BASEL  III DB2  */
/* Created by: N Grewal */
/* Last Modified: Jan 05, 2023 */
/* RUN THIS BEFORE DATA PATCH */
/*********************************************************************/

ALTER TABLE EDRRAPT.BASEL_ANALYTCL_BL_INSTRMNT_FACT
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM INTEGER
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER;

-- Copy or load from file BASEL_AIRB_PRD_LKP