/* DDL CHANGES FOR BASEL  III */
/* Created by: N Grewal */
/* Last Modified: Oct 20, 2022 */

/* TABLE SCRIPT */
/* CHANGE SCHEMA FOR PRODUCTION */
/* RUN THIS BEFORE DATA PATCH */ 

/****************** PIT STAT CD CHANGE ***********************/
ALTER TABLE EDRTLRP1D.BASEL_REVLVNG_CR_BASE_DRVD_VARS 
ADD COLUMN PIT_STAT_VER_2_CD90  char(3)
ADD COLUMN PIT_STAT_VER_2_CD180 char(3);


/**************** NEW BASEL APF TABLE **********************/
DROP TABLE EDRTLRP1D.BASEL_ACCT_PRFM_FACT IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.BASEL_ACCT_PRFM_FACT (
MTH_TM_ID DECIMAL(11,0),
MTH_END_DT DATE,
SRC_SYS_CD VARCHAR(30),
BASEL_ACCT_ID DECIMAL(20,0), 
ACCT_NUM VARCHAR(80),
PROC_TRANSIT VARCHAR(5),
SERV_TRANSIT VARCHAR(5),
PRD_CD VARCHAR(6),
CURRENCY_CD VARCHAR(3),
HELOC_IND VARCHAR(1),
LTV_BCKT_CD VARCHAR(30),
LTV_RTO DECIMAL(15,8),
LOAN_AMT_AT_INSURED_DATE DECIMAL(22,2),
RNTL_INCM_DPNDCY_F VARCHAR(1),
TRNSCTR_IND VARCHAR(1),
CURRENCY_MISMATCH_F VARCHAR(1),
TOT_EXPSR_ABOVE_1500K_LMT_F VARCHAR(1),
RNTL_INCM_AMT DECIMAL(22,2),
GRS_INCM_AMT DECIMAL(22,2),
PRCH_PRC_AMT DECIMAL(22,2),
APRSD_VAL_AMT DECIMAL(22,2),
PRPTY_VAL_AMT DECIMAL(22,2),
UNDRAWN_AMT DECIMAL(22,2),
CRNT_AUTH_LMT_AMT DECIMAL(22,2),
OCCUPANCY_TYPE_CD VARCHAR(1),
OS_BAL_AMT DECIMAL(22,2),
CRNT_LTV_RTO DECIMAL(15,8),
CLP_FLAG CHARACTER(1),
CRNT_PRPTY_VAL_AMT DECIMAL(22,2),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP)
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (ACCT_NUM,MTH_END_DT); COMMIT;

CREATE TABLE EDRTLRP1D.BASEL_KS_ACCT_TRANSACTOR_ROLE (
MTH_TM_ID DECIMAL(11,0),
BASEL_ACCT_ID DECIMAL(20,0),
ROLE_IND CHAR(1),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (BASEL_ACCT_ID,MTH_TM_ID); COMMIT;

/************* CREATE NEW DERIVED VARIABLE TABLES *******************/
DROP TABLE EDRTLRP1D.BASEL_CC_CUST_SCORECRD_DRVD_VARS IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.BASEL_CC_CUST_SCORECRD_DRVD_VARS (
MTH_TM_ID INTEGER,   
BASEL_CUST_ID BIGINT,
UTIL_KSC DECIMAL (11,4),          
AT36_MIN3M DECIMAL(3,0),
AT94_MIN24M DECIMAL(7,0),
BR147_MAX3M DECIMAL(5,0),
GO04_MAX6M DECIMAL(4,0),
DEP_CNT_MIN6M INTEGER,
AT29_MAX3M DECIMAL(3,0),
AT94_SUM3M DECIMAL(10,0),
BY34_MAX3M DECIMAL(7,0),
D2D_BAL_AMT_MIN3M DECIMAL(17,3) ,
INVSTM_ACCT_AMT DECIMAL(17,3),
BNS_DLQNT_DAY_MAX6M DECIMAL(3,0),
AT23_MIN6M DECIMAL(3,0),
AT83_MAX3M DECIMAL(3,0),
GO06_MAX3M DECIMAL(2,0),
BC33_AVG6M DECIMAL(10,3),
D2D_BAL_AMT_INV DECIMAL(17,3),
TOT_UNP_FNC_CHRG_12M DECIMAL(12,8),
AT84_SUM12M DECIMAL(14,0),
AT29_AVG6M DECIMAL(8,3),
AT41 DECIMAL(3,0),
BAL_HIST_CSH_ADV_KSCAVG12M DECIMAL(17,3),
BC33_MAX6M DECIMAL(7,0),
BNS_DLQNT_DAY_GP_KSCMAX24M DECIMAL(3,0)	,
GO11_AVG24M DECIMAL(5,2),
OVDR_CNT_SVG INTEGER,
GO04_MAX24M DECIMAL(4,0),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (MTH_TM_ID); COMMIT;

DROP TABLE EDRTLRP1D.BASEL_CC_ACCT_SCORECRD_DRVD_VARS IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.BASEL_CC_ACCT_SCORECRD_DRVD_VARS (
MTH_TM_ID INTEGER,   
BASEL_ACCT_ID BIGINT,
BAL_HIST_CSH_ADV_AMT DECIMAL(17,3),
FNC_CHRG_AVG24M DECIMAL(17,3),
TOT_UNP_FNC_CHRG_KSA DECIMAL(17,3),
UTIL_KSA DECIMAL (11,4),
BAL_HIST_CSH_ADV_MIN3M DECIMAL(17,3),
UTIL_KSAAVG3M DECIMAL (11,4),
BNS_DLQNT_DAY_GP_KSA DECIMAL(3,0),
UTIL_KSAAVG6M DECIMAL (11,4),
TOT_UNP_FNC_CHRG_KSAAVG6M DECIMAL(17,3),
CSH_AD_CRNT_C_BAL_KSAAVG6M DECIMAL(17,3), 
PRCH_CRNT_C_BAL_KSAMAX6M DECIMAL(17,3),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (MTH_TM_ID); COMMIT;

/************* SCORING + SEGMENTATION CHANGES ************************/
DROP TABLE EDRTLRP1D.BASEL_RCA_SCORE_SNAPSHOT_CC_PD IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.BASEL_RCA_SCORE_SNAPSHOT_CC_PD (
MTH_TM_ID INTEGER,   
BASEL_ACCT_ID BIGINT,
BASEL_MODEL_ID INTEGER,
BASEL_MODEL_SCORECARD_HDR_ID INTEGER,
CALC_SCORE INTEGER,
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (MTH_TM_ID); COMMIT;


/*********** PMI + 90D + BASEL APF CHANGES INSTRUMENT FACT + FLOOR INSTRUMENT FACT **********/
/************************ SPL ********************************/
ALTER TABLE EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

ALTER TABLE FRG_USER_DATA.BASEL_ANALYTCL_BL_INST_FCT_BNS
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN CLP_FLAG CHAR(1);

	
ALTER TABLE FRG_USER_DATA.BASEL_ANLYT_BL_INST_FCT_BNS_DLGD
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

	
ALTER TABLE FRG_USER_DATA.BASEL_ANALYTCL_BL_INST_FCT_TNG
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN CLP_FLAG CHAR(1);

ALTER TABLE FRG_USER_DATA.BASEL_ANLYT_BL_INST_FCT_TNG_DLGD
ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);
	
ALTER TABLE FRG_USER_DATA.BASEL_ANALYTCL_BL_INSTRMNT_FACT
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

ALTER TABLE EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_KS
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

ALTER TABLE EDRTLRP1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT /* RCERATE TABLE DUE TO SEQUECING ISSUE */
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN LTV_BUCKET VARCHAR(30)
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN PD_90_DAY_F VARCHAR(5)
	ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
	ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
	ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
	ADD COLUMN TRANSACTOR_FLAG_QRR VARCHAR(1)
	ADD COLUMN CCF DECIMAL(11 , 4)
	ADD COLUMN DRAWN DECIMAL(22 , 8)
	ADD COLUMN EAD_FLR DOUBLE
	ADD COLUMN EAD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN UNDRAWN DECIMAL(19 , 3)
	ADD COLUMN UNDRAWN_EXPSR_PCT DOUBLE
	ADD COLUMN CMHC_F VARCHAR(1 OCTETS)
	ADD COLUMN DLGD_FLR DOUBLE
	ADD COLUMN FULLY_SECURED_F VARCHAR(1 OCTETS)
	ADD COLUMN LGD_FLR DOUBLE
	ADD COLUMN PRE_INSURANCE_LGD DOUBLE
	ADD COLUMN PD_FLR DOUBLE
	ADD COLUMN PD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN LGD_FLRD_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_INSURED_RPTG_RTO DOUBLE
	ADD COLUMN PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29 , 8)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4 OCTETS)
	ADD COLUMN DLGD_RPTG_RTO_OLD DECIMAL(29 , 8)
	ADD COLUMN CCAR_F INTEGER
	ADD COLUMN CLP_FLAG CHAR(1)
	ADD COLUMN BCAR_SCHED_NM VARCHAR(150)
	ADD COLUMN BCAR_SCHED_NUM_50 VARCHAR(10)
	ADD COLUMN COLLATERAL_TYPE VARCHAR(50 OCTETS) 
	ADD COLUMN H_C DECIMAL(11 , 6)
	ADD COLUMN LGD_S DECIMAL(11 , 6)
	ADD COLUMN LGD_U DECIMAL(11 , 6)
	ADD COLUMN H_E DECIMAL(11 , 6)
	ADD COLUMN COLLATERAL_VALUE DECIMAL(18 , 3)
	ADD COLUMN EXPOSURE DOUBLE
	ADD COLUMN EXPOSURE_SECURED_MAXIMUM DOUBLE
	ADD COLUMN EXPOSURE_SECURED DOUBLE
	ADD COLUMN EXPOSURE_UNSECURED DOUBLE
	ADD COLUMN WEIGHT_SECURED DOUBLE
	ADD COLUMN WEIGHT_UNSECURED DOUBLE
	ALTER COLUMN BASEL_PRD_TP_CD SET DATA TYPE VARCHAR(20);

ALTER TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN DEFAULT_F CHAR(1)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN UNINSURED_DLGD_RTO DOUBLE
	ADD COLUMN BASEL_ACCT_ID DOUBLE
	ADD COLUMN PMI CHAR(1);

ALTER TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP
	ADD COLUMN RNTL_PRPTY_F CHAR(1)
	ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
	ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
	ADD COLUMN ORIG_AMT_LOAN DOUBLE
	ADD COLUMN TRANSACTOR_F CHAR(1)
	ADD COLUMN DEFAULT_F CHAR(1)
	ADD COLUMN UNINSURED_FLRD_LGD_RTO DOUBLE
	ADD COLUMN UNINSURED_DLGD_RTO DOUBLE
	ADD COLUMN BASEL_ACCT_ID DOUBLE
	ADD COLUMN PMI CHAR(1);

/****************** FLOORING CHANGES *****************************/
DROP TABLE EDRTLRP1D.RPTG_CCF_LKP IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.RPTG_CCF_LKP (
BASEL_PRD_TP_CD VARCHAR(20), 
CCF DECIMAL(10,4), 
EFF_FROM_YR_MTH VARCHAR(6), 
EFF_TO_YR_MTH VARCHAR(6), 
CRNT_F VARCHAR(1),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
; COMMIT;

DROP TABLE EDRTLRP1D.PD_BAND_DIM IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.PD_BAND_DIM (
NCR_EXPSR_CL_KEY_VAL VARCHAR(4), 
PD_MIN_VAL DOUBLE, 
PD_MAX_VAL DOUBLE, 
PD_MIN_VAL_DESC VARCHAR(7), 
PD_MAX_VAL_DESC VARCHAR(7), 
NCR_PD_BAND_KEY_VAL VARCHAR(4), 
PD_BAND_EXPSR_CL_DESC VARCHAR(36), 
NCR_PD_BAND_DESC VARCHAR(16), 
FRS_CD VARCHAR(2), 
PD_BAND VARCHAR(2), 
TRANSACTOR_F VARCHAR(1), 
CMHC_F VARCHAR(1), 
EFF_FROM_YR_MTH VARCHAR(6), 
EFF_TO_YR_MTH VARCHAR(6), 
CRNT_F VARCHAR(1), 
INSRT_PROCESS_TMSTMP TIMESTAMP, 
UPDT_PROCESS_TMSTMP TIMESTAMP)
ORGANIZE BY COLUMN
; COMMIT;

DROP TABLE EDRTLRP1D.BASEL_CCAR_PD_CURVE IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.BASEL_CCAR_PD_CURVE (
MTH_END_DT DATE, 
CCAR_BASEL_PRD_TP_NM VARCHAR(50), 
LEGAL_ENTITY VARCHAR(14), 
CMHC_F VARCHAR(1), 
TRANSACTOR_FLAG VARCHAR(1), 
PD_BAND VARCHAR(3), 
PD_MIN_VAL DOUBLE, 
PD_MAX_VAL DOUBLE, 
PD_VAL DOUBLE, 
INSRT_PROCESS_TMSTMP TIMESTAMP, 
UPDT_PROCESS_TMSTMP TIMESTAMP)
ORGANIZE BY COLUMN DISTRIBUTE BY HASH (MTH_END_DT);
; COMMIT;

DROP TABLE EDRTLRFRGP1D.TMP_INSTRMNT_FACT IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRFRGP1D.TMP_INSTRMNT_FACT (
	MTH_TM_ID DECIMAL(11,0),
	SRC_SYS_CD VARCHAR(10),
	BASEL_ACCT_ID DECIMAL(20,0),
	UNQ_ACCT_ID VARCHAR(30),
	NCR_RT_SYS_KEY_VAL VARCHAR(4),
	NCR_PD_BAND_KEY_VAL VARCHAR(4),
	NCR_EXPSR_SIZE_KEY_VAL VARCHAR(4),
	NCR_GEO_KEY_VAL VARCHAR(4),
	NCR_LTV_KEY_VAL VARCHAR(4),
	NCR_EXPSR_CL_KEY_VAL VARCHAR(4),
	NCR_RT_KEY_VAL VARCHAR(4),
	NCR_DLQNT_BCKT_KEY_VAL VARCHAR(4),
	PIT_STAT_CD VARCHAR(10),
	UTLTN_RTO DECIMAL(21,8),
	ACCT_ODT DATE,
	TRNST_NUM VARCHAR(5),
	CR_LMT_AMT DECIMAL(21,8),
	ADVNC_AMT DECIMAL(21,8),
	AUTH_AMT DECIMAL(29,8),
	OS_BAL_AMT DECIMAL(18,3),
	GENL_LEDGER_BALCNG_ADJ_AMT DECIMAL(18,3),
	ADJUSTED_OS_BAL_AMT DECIMAL(21,8),
	UNADJUSTED_ADD_ON_BAL_AMT DECIMAL(18,3),
	AF_SECRTZTN_BAL_AMT DECIMAL(29,8),
	DLQNT_DAY_CNT INTEGER,
	BEFORE_ZERO_NET_UNDRAWN_AMT DECIMAL(18,3),
	BEFORE_ZERO_NET_DRAWN_AMT DECIMAL(18,3),
	ORIG_PRPTY_VAL_AMT DECIMAL(18,3),
	LOAN_TO_VAL_RTO DECIMAL(21,8),
	INDEXED_PRPTY_VAL_AMT DECIMAL(21,8),
	INDEXED_LOAN_TO_VAL_RTO DECIMAL(21,8),
	PD_MODEL_NM VARCHAR(40),
	PD_MODEL_VER VARCHAR(10),
	PD_BASEL_SCORECRD_NM VARCHAR(40),
	PD_SCORECRD_VER VARCHAR(10),
	PD_BASEL_SEG_NUM DECIMAL(11,0),
	PD_BASEL_SEG_ID DECIMAL(11,0),
	PD_SEG_VER VARCHAR(10),
	PD_BASEL_MODEL_REL_ID DECIMAL(11,0),
	PD_MODEL_RTO DECIMAL(29,8),
	PD_LR_RPTG_RTO DECIMAL(29,8),
	PD_LR_PV_RPTG_RTO DECIMAL(29,8),
	PD_LR_PV_AD_RPTG_RTO DECIMAL(29,8),
	PD_LD_PV_AD_SV_RPTG_RTO DECIMAL(29,8),
	PD_ACCT_SCORE INTEGER,
	PD_FINAL_RPTG_RTO DECIMAL(29,8),
	LGD_MODEL_NM VARCHAR(40),
	LGD_MODEL_VER VARCHAR(10),
	LGD_BASEL_SCORECRD_NM VARCHAR(40),
	LGD_SCORECRD_VER VARCHAR(10),
	LGD_BASEL_SEG_NUM DECIMAL(11,0),
	LGD_BASEL_SEG_ID DECIMAL(11,0),
	LGD_SEG_VER VARCHAR(10),
	LGD_BASEL_MODEL_REL_ID DECIMAL(11,0),
	LGD_MODEL_RTO DECIMAL(29,8),
	LGD_LR_RPTG_RTO DECIMAL(29,8),
	LGD_LR_PV_RPTG_RTO DECIMAL(29,8),
	LGD_LR_PV_AD_RPTG_RTO DECIMAL(29,8),
	LGD_LD_PV_AD_SV_RPTG_RTO DECIMAL(29,8),
	LGD_ACCT_SCORE INTEGER,
	LGD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(29,8),
	EAD_MODEL_NM VARCHAR(40),
	EAD_MODEL_VER VARCHAR(10),
	LGD_FINAL_RPTG_RTO DECIMAL(29,8),
	EAD_BASEL_SCORECRD_NM VARCHAR(40),
	EAD_SCORECRD_VER VARCHAR(10),
	EAD_BASEL_SEG_NUM DECIMAL(11,0),
	EAD_BASEL_SEG_ID DECIMAL(11,0),
	EAD_SEG_VER VARCHAR(10),
	EAD_BASEL_MODEL_REL_ID DECIMAL(11,0),
	EAD_MODEL_RTO DECIMAL(29,8),
	EAD_LR_RPTG_RTO DECIMAL(29,8),
	EAD_LR_PV_RPTG_RTO DECIMAL(29,8),
	EAD_ACCT_SCORE INTEGER,
	EAD_LR_PV_AD_RPTG_RTO DECIMAL(29,8),
	ASST_CL_DESC VARCHAR(255),
	CONS_DFT_MTH_CNT INTEGER,
	EAD_LD_PV_AD_SV_RPTG_RTO DECIMAL(29,8),
	EAD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL(29,8),
	BCAR_SCHED_NUM VARCHAR(3),
	EAD_FINAL_RPTG_RTO DECIMAL(29,8),
	PD_BAND VARCHAR(10),
	BASEL_PRD_ABR VARCHAR(50),
	SCRTY_TP_DESC VARCHAR(50),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	CCAR_EXPSR_CL_NM VARCHAR(20),
	BASEL_PRD_TP_CD VARCHAR(10),
	CONSM_PRD_TREATMNT_CD VARCHAR(10),
	PRD_ID VARCHAR(10),
	PRIM_CUST_CID VARCHAR(20),
	ACCT_NUM VARCHAR(23),
	RGNL_OFFC_CD VARCHAR(5),
	DLQNT_STG VARCHAR(10),
	MORT_NUM VARCHAR(50),
	CAB_TRNST_NUM VARCHAR(5),
	EGL_DEPRTMNT VARCHAR(255),
	BASEL_CIF_KEY VARCHAR(69),
	LOAN_NUM VARCHAR(15),
	INTR_ACCR_AMT DECIMAL(18,3),
	CUST_BEHV_SCORE DECIMAL(11,0),
	PRD_CD VARCHAR(10),
	SUB_PRD_CD VARCHAR(10),
	SRC_PRD_DESC VARCHAR(255),
	LEGAL_ENTITY VARCHAR(40),
	MAT_DT DATE,
	LAST_PYMT_DT DATE,
	SCRTY_TP_CD VARCHAR(10),
	STEP_F VARCHAR(1),
	LAST_ACTY_DT DATE,
	HOUSE_TP_NM VARCHAR(20),
	LAST_RGL_PAY_DT DATE,
	PD_OFF_F VARCHAR(1),
	PD_OFF_DT DATE,
	RESIDUAL_MAT DECIMAL(11,0),
	ASST_CL_NUM INTEGER,
	E_MAT_DT DATE,
	AMORT DECIMAL(18,3),
	TRNST_EXCLSN_F VARCHAR(1),
	SML_BUS_F VARCHAR(1),
	NOTE_DT DATE,
	INSRT_PROCESS_TMSTMP TIMESTAMP,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	AF_ZERO_NET_DRAWN_AMT DECIMAL(18,3),
	AF_ZERO_NET_UNDRAWN_AMT DECIMAL(18,3),
	PD_UNADJUSTED_RPTG_RTO DECIMAL(29,8),
	LGD_UNADJUSTED_RPTG_RTO DECIMAL(29,8),
	EAD_UNADJUSTED_RPTG_RTO DECIMAL(29,8),
	PD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(29,8),
	LGD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(29,8),
	EAD_LR_PV_AD_SV_DT_AA_RTO DECIMAL(29,8),
	INSUR_F VARCHAR(10),
	OS_PRNCPL_BAL_AMT DECIMAL(21,8),
	PREV_12_QTR_PRPTY_VAL_AMT DECIMAL(21,8),
	DLGD_F VARCHAR(1),
	CRNT_LTV_RTO DECIMAL(31,20),
	METRPL_AREA_NM VARCHAR(32),
	PRPTY_VAL_CORR_PCTG DECIMAL(12,4),
	LNG_RUN_LGD_ADD_ON_RTO DECIMAL(29,8),
	DLGD_RPTG_RTO DECIMAL(29,8),
	LTV_PERCENTAGE VARCHAR(4),
	RNTL_PRPTY_F CHARACTER(1),
	CURRENCY_MISMATCH_F CHARACTER(1),
	TOT_EXPSR_ABOVE_1500K_LMT_F CHARACTER(1),
	ORIG_AMT_LOAN DOUBLE,
	LTV_BUCKET VARCHAR(30),
	TRANSACTOR_F CHARACTER(1),
	PD_90_DAY_F VARCHAR(5),
	UNINSURED_LGD_SEG_NUM DOUBLE,
	UNINSURED_LGD_RTO DECIMAL(28,8),
	UNINSURED_DLGD_RTO DECIMAL(28,8),
	TRANSACTOR_FLAG_QRR VARCHAR(1),
	CCF DECIMAL(11,4),
	DRAWN DECIMAL(22,8),
	EAD_FLR DOUBLE,
	EAD_FLRD_RPTG_RTO DOUBLE,
	UNDRAWN DECIMAL(19,3),
	UNDRAWN_EXPSR_PCT DOUBLE,
	CMHC_F VARCHAR(1),
	DLGD_FLR DOUBLE,
	FULLY_SECURED_F VARCHAR(1),
	LGD_FLR DOUBLE,
	PRE_INSURANCE_LGD DOUBLE,
	PD_FLR DOUBLE,
	PD_FLRD_RPTG_RTO DOUBLE,
	LGD_FLRD_RPTG_RTO DOUBLE,
	PMI_LGD_INSURED_RPTG_RTO DOUBLE,
	PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL(29,8),
	UNINSURED_FLRD_LGD_RTO DOUBLE,
	PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4),
	DLGD_RPTG_RTO_OLD DECIMAL(29,8),
	CCAR_F INTEGER,
	CLP_FLAG CHAR(1),
	BCAR_SCHED_NM VARCHAR(150),
	BCAR_SCHED_NUM_50 VARCHAR(10),
	COLLATERAL_TYPE VARCHAR(50 OCTETS) ,
	H_C DECIMAL(11 , 6),
	LGD_S DECIMAL(11 , 6),
	LGD_U DECIMAL(11 , 6),
	H_E DECIMAL(11 , 6),
	COLLATERAL_VALUE DECIMAL(18 , 3),
	EXPOSURE DOUBLE,
	EXPOSURE_SECURED_MAXIMUM DOUBLE,
	EXPOSURE_SECURED DOUBLE,
	EXPOSURE_UNSECURED DOUBLE,
	WEIGHT_SECURED DOUBLE,
	WEIGHT_UNSECURED DOUBLE)
ORGANIZE BY COLUMN DISTRIBUTE BY HASH (MTH_TM_ID, BASEL_ACCT_ID);
; COMMIT;


CREATE TABLE EDRTLRP1D.BASEL_NCR_HIERARCHY_LKP (
NCR_KEY_VAL VARCHAR(4), 
NCR_PRNT_KEY_VAL VARCHAR(4), 
NCR_KEY_DESC VARCHAR(255), 
NCR_PRNT_KEY_DESC VARCHAR(255), 
INSRT_PROCESS_TMSTMP TIMESTAMP, 
UPDT_PROCESS_TMSTMP TIMESTAMP)
ORGANIZE BY COLUMN ;
; COMMIT;

CREATE TABLE EDRTLRP1D.RPTG_PRD_LKP_THRSHLD
(
THRSHLD INTEGER NOT NULL,
CRNT_F CHAR(1) NOT NULL,
EFF_FROM_YR_MTH DATE NOT NULL,
EFF_TO_YR_MTH DATE NOT NULL
);


/**************** NEW history table for 2 6 report **********************/
CREATE TABLE EDRTLRP1D.BASEL_RPTG_SCHED_2_6_BCAR50_FACT (
	MTH_TM_ID INTEGER NOT NULL,
	BCAR_SCHED_SORT SMALLINT,
	ASST_CL_NUM SMALLINT,
	BCAR_SCHED_NUM_50 VARCHAR(10) NOT NULL,
	BCAR_SCHED_NM VARCHAR(150),
	ACCT_CNT INTEGER,
	ADJ_BEFORE_ZERO_NET_OS_BAL_AMT DECIMAL(21,8),
	ADJUSTED_AF_ZERO_NET_OS_BAL_AMT DECIMAL(21,8),
	DEFLTD_ACCT_CNT INTEGER,
	ADJ_BEFR_ZER_NET_DF_AC_OS_BL_AMT DECIMAL(21,8),
	ADJ_AF_ZERO_NET_DF_AC_OS_BAL_AMT DECIMAL(21,8),
	PREV_12_MTH_TOT_DEFLTD_ACCT_CNT INTEGER,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL WITH DEFAULT,
	UPDT_PROCESS_TMSTMP TIMESTAMP NOT NULL WITH DEFAULT)
	DISTRIBUTE BY HASH (BCAR_SCHED_NUM_50, MTH_TM_ID);
COMMIT;


/**************** NEW lookup table for 2 6 report **********************/
CREATE TABLE EDRTLRP1D.RMA_BASEL3_PRDCT_SCHD_BCAR50_LKP (
	SRC_SYS_CD VARCHAR(10) NOT NULL,
	BCAR_SCHED_NUM VARCHAR(3),
	ASST_CL_NUM SMALLINT NOT NULL,
	BASEL_PRD_TP_CD VARCHAR(15),
	PRD_CD VARCHAR(10),
	SUB_PRD_CD VARCHAR(10),
	RNTL_PRPTY_F CHAR(1),
	CLP_FLAG CHAR(1),
	TRANSACTOR_FLAG_QRR CHAR(1),
	TOT_EXPSR_ABOVE_LMT_F CHAR(1),
	BCAR_SCHED_NUM_50 VARCHAR(10) NOT NULL,
	BCAR_SCHED_NM VARCHAR(150) NOT NULL,
	BCAR_SCHED_SORT SMALLINT,
	CRNT_F CHAR(1) NOT NULL,
	EFF_FROM_YR_MTH VARCHAR(6),
	EFF_TO_YR_MTH VARCHAR(6),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL WITH DEFAULT,
	UPDT_PROCESS_TMSTMP TIMESTAMP NOT NULL WITH DEFAULT);
COMMIT;







/***********  TABLE THAT STORES RRAP FILE ******************/

DROP TABLE EDRTLRP1D.RRAP_CCAR_ACAP_FILES IF exists; COMMIT;

CREATE TABLE EDRTLRP1D.RRAP_CCAR_ACAP_FILES (
		MTH_TM_ID INTEGER,
		UNIQUE_IDENTIFIER VARCHAR(11 OCTETS), 
		BASEL_PRODUCT_NAME VARCHAR(50 OCTETS), 
		PROBABILITYDEFAULT_BAND DOUBLE, 
		LEGAL_ENTITY VARCHAR(40 OCTETS), 
		DEFAULTED_EXPOSURE_FLAG VARCHAR(5 OCTETS), 
		DAY90_PASTDUE_FLAG VARCHAR(5 OCTETS), 
		UNCONDITIONALLY_CANCELABLE_FLAG VARCHAR(10 OCTETS), 
		DRAWN_AMOUNT DECIMAL(24 , 2), 
		EXPOSURES_AT_DEFAULT VARCHAR(1 OCTETS), 
		CURRENCY VARCHAR(10 OCTETS), 
		EXPECTED_LOSS VARCHAR(18 OCTETS), 
		UNDRAWN_AMOUNT DECIMAL(21 , 2), 
		ACCRUED_INTEREST DECIMAL(21 , 2), 
		PARTIAL_WRITE_OFF DECIMAL(21 , 2), 
		LOSS_GIVEN_DEFAULT VARCHAR(18 OCTETS), 
		EAD_FACTOR VARCHAR(18 OCTETS), 
		INSURANCE_FLAG VARCHAR(3 OCTETS), 
		DOWNTURN_LGD VARCHAR(18 OCTETS),  
		UNINSURED_LGD VARCHAR(22 OCTETS), 
		UNINSURED_DLGD VARCHAR(18 OCTETS),  
		LTV_BUCKET VARCHAR(30 OCTETS), 
		OBLIGORS DECIMAL(22 , 0), 
		RENTAL_INCOME_FLAG VARCHAR(1 OCTETS), 
		CURRENCY_MISMATCH_FLAG VARCHAR(1 OCTETS), 
		TOTAL_EXPOSURE_ABOVE_LIMIT VARCHAR(1 OCTETS), 
		ORIG_LOAN_AMT_AS_OF_INSUR_DATE DECIMAL(18 , 3), 
		TRANSACTOR_FLAG VARCHAR(1 OCTETS), 
		EXPOSURES_PRIOR_SECURITIZATION DECIMAL(21 , 2), 
		EXPOSURES_NO_SECURITIZATION DECIMAL(21 , 2), 
		EXPOSURES_WITH_SECURITIZATION DECIMAL(21 , 2), 
		SECURITIZATION_AMOUNT DECIMAL(21 , 2), 
		EXPOSURES_REDUCED DECIMAL(21 , 2), 
		SECURITIZATION_NAME VARCHAR(13 OCTETS), 
		ECL_DRAWN1 DECIMAL(29 , 2), 
		ECL_DRAWN2 DECIMAL(29 , 2), 
		ECL_DRAWN3 DECIMAL(29 , 2), 
		ECL_UNDRAWN1 DECIMAL(29 , 2), 
		ECL_UNDRAWN2 DECIMAL(29 , 2), 
		ECL_UNDRAWN3 DECIMAL(29 , 2), 
		ECL_DRAWN_POSTSEC1 DECIMAL(29 , 2), 
		ECL_DRAWN_POSTSEC2 DECIMAL(29 , 2), 
		ECL_DRAWN_POSTSEC3 DECIMAL(29 , 2), 
		ECL_POST_ADJ_DRAWN1 DECIMAL(29 , 2), 
		ECL_POST_ADJ_DRAWN2 DECIMAL(29 , 2), 
		ECL_POST_ADJ_DRAWN3 DECIMAL(29 , 2), 
		ECL_POST_ADJ_UNDRAWN1 DECIMAL(29 , 2), 
		ECL_POST_ADJ_UNDRAWN2 DECIMAL(29 , 2), 
		ECL_POST_ADJ_UNDRAWN3 DECIMAL(29 , 2), 
		ECL_POST_ADJ_DRAWN_POSTSEC1 DECIMAL(29 , 2), 
		ECL_POST_ADJ_DRAWN_POSTSEC2 DECIMAL(29 , 2), 
		ECL_POST_ADJ_DRAWN_POSTSEC3 DECIMAL(29 , 2), 
		TRANSIT_NUMBER VARCHAR(5 OCTETS), 
		PRODUCT_ID VARCHAR(10 OCTETS), 
		EGL_DEPARTMENT_ID VARCHAR(255 OCTETS),
		INSRT_PROCESS_TMSTMP TIMESTAMP,
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (MTH_TM_ID, UNIQUE_IDENTIFIER); COMMIT;

/************* DT4_RW_INSURER Instructions ***********************/

--1. Back Up EDRTLRP1D.DT4_RW_INSURER  **** Name backup table according to back up naming conventions
create table EDRTLRP1D.DT4_RW_INSURER_bkup as (select * from EDRTLRP1D.DT4_RW_INSURER) with data; commit;

--2. Create EDRTLRP1D.DT4_RW_INSURER with new structure
drop table EDRTLRP1D.DT4_RW_INSURER if exists; commit;
CREATE TABLE EDRTLRP1D.DT4_RW_INSURER (
		NAME VARCHAR(4 OCTETS), 
		RW_INSURER DOUBLE, 
		IG_CODE VARCHAR(4 OCTETS), 
		PD DOUBLE, 
		LGD DOUBLE, 
		RW_INSURER_A1 DOUBLE, 
		CORRELATION_PMI DOUBLE, 
		MATURITY_ADJUSTMENT_PMI	 DOUBLE, 	
		EFF_FROM_YR_MTH VARCHAR(6 OCTETS), 
		EFF_TO_YR_MTH VARCHAR(6 OCTETS), 
		CRNT_F VARCHAR(1 OCTETS), 
		INSRT_PROCESS_TMSTMP TIMESTAMP, 
		UPDT_PROCESS_TMSTMP TIMESTAMP
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE 
	DISTRIBUTE BY HASH (NAME, EFF_FROM_YR_MTH); COMMIT;
	
--3. Insert data from backup table into new STRUCTURE

insert into EDRTLRP1D.DT4_RW_INSURER
SELECT 
NAME,
RW_INSURER, 
NULL as IG_CODE, 
NULL as PD, 
NULL as LGD, 
NULL as RW_INSURER_A1, 
NULL as CORRELATION_PMI, 
NULL as MATURITY_ADJUSTMENT_PMI, 
EFF_FROM_YR_MTH, 
EFF_TO_YR_MTH, 
CRNT_F, 
INSRT_PROCESS_TMSTMP, 
UPDT_PROCESS_TMSTMP 
FROM 
EDRTLRP1D.DT4_RW_INSURER_bkup;