/************ TERANET CHANGES ****************************************/
/* DDL CHANGES FOR BASEL  III TERANET */
/* Created by: N Grewal */
/* Last Modified: Jan 05, 2023 */
/* RUN THIS BEFORE DATA PATCH */
/*********************************************************************/

CREATE TABLE EDRTLRP1D.STANDARDIZED_CMA (
   STANDARDIZED_CMA varchar(50), 
   SOURCE_CMA varchar(50), 
   INSRT_PROCESS_TMSTMP TIMESTAMP, 
   UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.TERANET_HOUSE_PRC_INDEX_CMA_12M (
    PROCESS_MTH_TM_ID INTEGER, 
	MTH_TM_ID INTEGER, 
	LABEL_1 VARCHAR(32), 
	LABEL_2 VARCHAR(32), 
	LABEL_2_ORIG VARCHAR(32), 
	"INDEX" DOUBLE, 
	SLS_PAIR_CNT DOUBLE, 
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.TERANET_HOUSE_PRC_INDEX_CMA (
	MTH_TM_ID INTEGER, 
	LABEL_1 VARCHAR(32), 
	LABEL_2 VARCHAR(32), 
	LABEL_2_ORIG VARCHAR(32), 
	"INDEX" DOUBLE, 
	SLS_PAIR_CNT DOUBLE, 
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.METRPL_CITY_LKP_CMA (
	CITY_NM VARCHAR(64), 
	METRPL_AREA_NM VARCHAR(32), 
	METRPL_AREA_NM_ORIG VARCHAR(32), 
	PROV CHAR(2), 
	EFF_FROM_YR_MTH CHAR(6), 
	EFF_TO_YR_MTH CHAR(6), 
	CRNT_F CHAR(1), 
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.TERANET_ADDR_LKP_CMA (
	PRPTY_LOCTN_NM VARCHAR(50), 
	EFF_FROM_YR_MTH CHAR(6), 
	EFF_TO_YR_MTH CHAR(6), 
	LOCTN_LABEL_1 VARCHAR(40), 
	LOCTN_LABEL_2 VARCHAR(40), 
	LOCTN_LABEL_2_ORIG VARCHAR(40), 
	CRNT_F CHAR(1), 
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.PROVNCL_HOUSE_INDEX_SUM_CMA (
	MTH_TM_ID INTEGER, 
	PROV_CD CHAR(2), 
	SLS_PAIR_ANLYS_CNT INTEGER, 
	HOUSE_INDEX_RTO DECIMAL(11,4), 	
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.BASEL_STEP_LTV_DRVD_VARS_CMA (
	STEP_PLN_SNAPSHOT_ID BIGINT, 
	MTH_TM_ID INTEGER, 
	BASEL_CUST_ID BIGINT, 
	METRPL_AREA_NM VARCHAR(32), 
	CRNT_METRPL_TERANET_INDEX DECIMAL(8,4), 
	PREV_12_QTR_METRPL_TERANET_HOUSE_INDEX DECIMAL(8,4), 
	APPRSL_DT_PRPTY_VAL_AMT DECIMAL(17,3), 
	CRNT_PRPTY_VAL_AMT DECIMAL(17,3), 
	PREV_12_QTR_PRPTY_VAL_AMT DECIMAL(17,3),  	
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.BASEL_ACCT_LTV_DRVD_VARS_CMA (
	BASEL_ACCT_ID BIGINT, 
	MTH_TM_ID INTEGER, 
	STEP_PLN_SNAPSHOT_ID BIGINT, 
	ACCT_NUM VARCHAR(80), 
	ACCT_SENRTY_CD BIGINT, 
	MAX_ACCT_BAL_AMT DECIMAL(17,3), 
	EXPSR_AT_DFT_RTO DECIMAL(28,8), 
	CRNT_LTV_RTO DECIMAL(30,20), 
	INDEXED_CCLTV_RTO DECIMAL(30,20), 
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.BASEL_ACCT_LTV_DRVD_VARS_CMA (
	BASEL_ACCT_ID BIGINT, 
	MTH_TM_ID INTEGER, 
	STEP_PLN_SNAPSHOT_ID BIGINT, 
	ACCT_NUM VARCHAR(80), 
	ACCT_SENRTY_CD BIGINT, 
	MAX_ACCT_BAL_AMT DECIMAL(17,3), 
	EXPSR_AT_DFT_RTO DECIMAL(28,8), 
	CRNT_LTV_RTO DECIMAL(30,20), 
	INDEXED_CCLTV_RTO DECIMAL(30,20), 
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.BASEL_STEP_PLN_BASE_DRVD_VAR_CMA (
	MTH_TM_ID DECIMAL(11,0), 
	BASEL_STEP_PLN_SNAPSHOT_ID DECIMAL(20,0), 
	PRPTY_ADDR VARCHAR(200), 
	DRVD_POST_ADDR_SUBSTRING VARCHAR(50), 
	LOCTN_LABEL_1 VARCHAR(2), 
	LOCTN_LABEL_2 VARCHAR(40), 
	INSRT_PROCESS_TMSTMP TIMESTAMP, 
	UPDT_PROCESS_TMSTMP TIMESTAMP
) ORGANIZE BY COLUMN;

CREATE TABLE EDRTLRP1D.BASEL_REVLVNG_CR_ACCT_DRVD_VARS_CMA (
	MTH_TM_ID INTEGER NOT NULL,
	BASEL_ACCT_ID BIGINT NOT NULL,
	BASEL_PRIM_CUST_ID BIGINT NOT NULL,
	ACCT_NUM CHARACTER(50),
	APRSD_VAL_TERANET_INDEXED_AMT DECIMAL(17,3),
	CONS_DFT_MTH_CNT SMALLINT,
	DLQNT_CYCL_CD CHARACTER(10),
	DLQNT_PREV_12_MTH_CNT SMALLINT,
	INACT_12_MTH_F CHARACTER(1),
	LOAN_TO_VAL_WITH_TERANET_INDEX_RTO DECIMAL(11,4),
	LOAN_TO_VAL_WITHOUT_INDEX_RTO DECIMAL(11,4),
	LTV_TP_CD CHARACTER(10),
	MTH_SINCE_LAST_PYMT_CNT INTEGER,
	OS_BAL_AMT DECIMAL(17,3),
	OV_LMT_F CHARACTER(1),
	PAST_12_MTH_MAX_UTLTN_RTO DECIMAL(11,4),
	PREV_12_MTH_DLQNT_F CHARACTER(1),
	TERANET_HOUSE_APRSD_DT_INDEX DECIMAL(8,4),
	TERANET_HOUSE_INDEX DECIMAL(8,4),
	TRNST_NUM CHARACTER(5),
	UTLTN_RTO DECIMAL(11,4),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	HELOC_PRD_TP CHARACTER(10)) ORGANIZE BY COLUMN;

CREATE TABLE FRG_USER_DATA.LTV_VAR_CLUS_LTV_FINAL(
	MORTGAGE_NO DECIMAL(11,0),
	YYMTH DECIMAL(13,0),
	INDEX_TERANETV DOUBLE,
	LTV DOUBLE,
	LEND_VAL2 DECIMAL(20,2),
	CURRENT_BAL DECIMAL(22,3),
	INT_ACCR_AMT DECIMAL(23,5),
	TOTAL_SUSPENSE DECIMAL(20,3),
	PROP_CITY VARCHAR(30)) ORGANIZE BY COLUMN;
	
CREATE TABLE FRG_USER_DATA.TNG_PD_VAR_CREATION_FINAL_CMA (
	ACCOUNT_ID VARCHAR(80),
	MONTH_END_DT DATE,
	END_PRINCIPAL_BALANCE DECIMAL(14,2),
	DEFAULT_IND VARCHAR(1),
	CLOSE_DT DATE,
	NEW_DEF_IND VARCHAR(8),
	NEW_DEFAULT_IND VARCHAR(1),
	WRITE_OFF_MONTH DOUBLE,
	WRITE_OFF_IND VARCHAR(1),
	WRITE_OFF_AMT DOUBLE,
	FINAL_DEFAULT_IND VARCHAR(1),
	TRADES_STSFCT_CNTSLP6M DOUBLE,
	TRADES_ACTIVE_UTIL_PCTMAX12M DOUBLE,
	DEROGATORY_PUBLIC_REC_CNT INTEGER,
	COLLECTIONS_CNT INTEGER,
	BANKRUPTCIES_CNT INTEGER,
	CREDIT_TRBLE_BNKRPTCY_COLL_DER DOUBLE,
	INS_ID_GROUP DOUBLE,
	DAYS_ARREARS_CNT DECIMAL(13,0),
	NSF_YTD_CNT DECIMAL(13,0),
	EVER_30_CNT DECIMAL(13,0),
	REMAIN_AMORT2 DOUBLE,
	PROP_VAL_NEW DOUBLE,
	LTV_TERANET DOUBLE,
	PROP_CITY VARCHAR(80),
	PROP_PROVINCE_CODE VARCHAR(20)) ORGANIZE BY COLUMN;
	
	
/************** DATA COPY FROM IIAS UAT TO IIAS PROD ********************/
1. Copy data from EDRTLRP1D.STANDARDIZED_CMA to EDRTLRP1D.STANDARDIZED_CMA
2. Copy data from EDRTLRP1D.TERANET_HOUSE_PRC_INDEX_CMA_12M to EDRTLRP1D.TERANET_HOUSE_PRC_INDEX_CMA_12M
3. Copy data from EDRTLRP1D.TERANET_HOUSE_PRC_INDEX_CMA to EDRTLRP1D.TERANET_HOUSE_PRC_INDEX_CMA
4. Copy data from EDRTLRP1D.METRPL_CITY_LKP_CMA to EDRTLRP1D.METRPL_CITY_LKP_CMA
5. Copy data from EDRTLRP1D.TERANET_ADDR_LKP_CMA to EDRTLRP1D.TERANET_ADDR_LKP_CMA
6. Copy data from EDRTLRP1D.PROVNCL_HOUSE_INDEX_SUM_CMA to EDRTLRP1D.PROVNCL_HOUSE_INDEX_SUM_CMA

