/* DATA PATCH FOR BASEL III */
/* Created by: N Grewal */
/* Last Modified: Oct 20, 2022 */

/************ 1. PIT_STAT_CD *************************/
/* Data Patch received from RMA */
/* For Q4, run the delta for Aug & Sep 2022 */
/* For PROD deployment, Copy data from DEV to PROD */

UPDATE EDRTLRPD1D.BASEL_REVLVNG_CR_BASE_DRVD_VARS
SET PIT_STAT_VER_2_CD90 = PIT_STAT_VER_2_CD;

UPDATE EDRTLRPD1D.BASEL_REVLVNG_CR_BASE_DRVD_VARS B
SET B.PIT_STAT_VER_2_CD = A.PIT_180
FROM
	(SELECT 
			BASEL_ACCT_ID,
			PIT_180,
			MTH_TM_ID
	FROM edrtlrd1d.CC_PIT180_RRAP_202112 WHERE MTH_TM_ID=19076 ) A 
WHERE A.MTH_TM_ID = B.MTH_TM_ID
	AND A.BASEL_ACCT_ID = B.BASEL_ACCT_ID
	AND A.MTH_TM_ID = 19076 ;



/********** 2. BASEL_REVLVNG_CR_ACCT_DRVD_VAR ************ */
Run this job for 3 years 
For Q4, just run the delta for Aug & Sep 2022
For PROD deployment, Copy historical data from DEV to PROD (pit_stat_cd flows to this table)
BASEL_REVLVNG_CR_ACCT_DRVD_VARS

/********** 3. XREF TABLES - PD, LGD, EAD *****************/
/* Data Patch received from RMA */

DELETE FROM edrtlrpd1d.PD_SEG_ACCT_XREF WHERE mth_tm_id=18916 AND BASEL_MODEL_ID=8011;
INSERT INTO edrtlrpd1d.PD_SEG_ACCT_XREF
SELECT a.BASEL_ACCT_ID,a.MTH_TM_ID, b.BASEL_SEG_ID, c.BASEL_MODEL_REL_ID, 8011, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM credit_risk_user.CC_PD_SEG_2021_14710 a
INNER JOIN edrtlrd1d.BASEL_SEG_N b 
ON a.PD_SEG_BASEL3 = b.SEG_NUM
INNER JOIN edrtlrd1d.BASEL_MODEL_REL_N c 
ON b.BASEL_SEG_ID = c.BASEL_SEG_ID
WHERE a.MTH_TM_ID = 18916
AND b.BASEL_MODEL_ID = 8011;


delete FROM EDRTLRPD1D.LGD_SEG_ACCT_XREF WHERE MTH_TM_ID = 18436 AND BASEL_MODEL_ID=8010;
INSERT INTO edrtlrpd1d.LGD_SEG_ACCT_XREF
SELECT a.BASEL_ACCT_ID,a.MTH_TM_ID, a.BASEL_SEG_ID, c.BASEL_MODEL_REL_ID, a.BASEL_MODEL_ID, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM credit_risk_user.BASEL3_CC_LGDD_JUL2020_XREF_V2 a
INNER JOIN edrtlrpd1d.BASEL_MODEL_REL c 
ON a.BASEL_SEG_ID = c.BASEL_SEG_ID
WHERE a.MTH_TM_ID = 18436
AND a.BASEL_MODEL_ID = 8010;

delete FROM EDRTLRPD1D.LGD_SEG_ACCT_XREF WHERE MTH_TM_ID = 17956 AND BASEL_MODEL_ID=8009;
INSERT INTO edrtlrpd1d.LGD_SEG_ACCT_XREF
SELECT a.BASEL_ACCT_ID,a.MTH_TM_ID, a.BASEL_SEG_ID, c.BASEL_MODEL_REL_ID, a.BASEL_MODEL_ID, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM credit_risk_user.BASEL3_CC_LGDND_JUL2019_XREF  a
INNER JOIN edrtlrpd1d.BASEL_MODEL_REL c 
ON a.BASEL_SEG_ID = c.BASEL_SEG_ID
WHERE a.MTH_TM_ID = 17956
AND a.BASEL_MODEL_ID = 8009;

/* Missing EAD - not required for Q3 */


/*********** 4. REVLVNG_CR_OBSVTN_PT_DRVD_VAR ***********************/
Copy historical data from DEV to PROD (pit_stat_cd flows to this table)
REVLVNG_CR_OBSVTN_PT_DRVD_VAR
