/* DDL CHANGES FOR BASEL  III */
/* Created by: N Grewal */
/* Last Modified: Dec 06, 2022 */
/* add columns to APF table */

/* TABLE SCRIPT */
/* CHANGE SCHEMA FOR PRODUCTION */
/* RUN THIS BEFORE DATA PATCH */

/****************** 1. PIT STAT CD CHANGE ***********************/
ALTER TABLE EDRTLRPD1D.BASEL_REVLVNG_CR_BASE_DRVD_VARS 
ADD COLUMN PIT_STAT_VER_2_CD90  char(3)
ADD COLUMN PIT_STAT_VER_2_CD180 char(3);


/**************** 2. NEW BASEL APF TABLE **********************/
DROP TABLE EDRTLRP1D.BASEL_ACCT_PRFM_FACT IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRP1D.BASEL_ACCT_PRFM_FACT (
MTH_TM_ID DECIMAL(11,0),
MTH_END_DT DATE,
SRC_SYS_CD VARCHAR(30),
BASEL_ACCT_ID DECIMAL(20,0), 
ACCT_NUM VARCHAR(80),
PROC_TRANSIT VARCHAR(5),
SERV_TRANSIT VARCHAR(5),
PRD_CD VARCHAR(6),
CURRENCY_CD VARCHAR(3),
HELOC_IND VARCHAR(1),
LTV_BCKT_CD VARCHAR(30),
LTV_RTO DECIMAL(15,8),
LOAN_AMT_AT_INSURED_DATE DECIMAL(22,2),
RNTL_INCM_DPNDCY_F VARCHAR(1),
TRNSCTR_IND VARCHAR(1),
CURRENCY_MISMATCH_F VARCHAR(1),
TOT_EXPSR_ABOVE_1500K_LMT_F VARCHAR(1),
RNTL_INCM_AMT DECIMAL(22,2),
GRS_INCM_AMT DECIMAL(22,2),
PRCH_PRC_AMT DECIMAL(22,2),
APRSD_VAL_AMT DECIMAL(22,2),
PRPTY_VAL_AMT DECIMAL(22,2),
UNDRAWN_AMT DECIMAL(22,2),
CRNT_AUTH_LMT_AMT DECIMAL(22,2),
OCCUPANCY_TYPE_CD VARCHAR(1),
OS_BAL_AMT DECIMAL(22,2),
NEW_ACCT_NUM VARCHAR(80),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP)
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (ACCT_NUM,MTH_END_DT); COMMIT;

CREATE TABLE EDRTLRP1D.BASEL_KS_ACCT_TRANSACTOR_ROLE (
MTH_TM_ID DECIMAL(11,0),
BASEL_ACCT_ID DECIMAL(20,0),
ROLE_IND CHAR(1),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (BASEL_ACCT_ID,MTH_TM_ID); COMMIT;

/************* 3. CREATE NEW DERIVED VARIABLE TABLES *******************/
DROP TABLE EDRTLRPD1D.BASEL_CC_CUST_SCORECRD_DRVD_VARS IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRPD1D.BASEL_CC_CUST_SCORECRD_DRVD_VARS (
MTH_TM_ID INTEGER,   
BASEL_CUST_ID BIGINT,
UTIL_KSC DECIMAL (11,4),          
AT36_MIN3M DECIMAL(3,0),
AT94_MIN24M DECIMAL(7,0),
BR147_MAX3M DECIMAL(5,0),
GO04_MAX6M DECIMAL(4,0),
DEP_CNT_MIN6M INTEGER,
AT29_MAX3M DECIMAL(3,0),
AT94_SUM3M DECIMAL(10,0),
BY34_MAX3M DECIMAL(7,0),
D2D_BAL_AMT_MIN3M DECIMAL(17,3) ,
INVSTM_ACCT_AMT DECIMAL(17,3),
BNS_DLQNT_DAY_MAX6M DECIMAL(3,0),
AT23_MIN6M DECIMAL(3,0),
AT83_MAX3M DECIMAL(3,0),
GO06_MAX3M DECIMAL(2,0),
BC33_AVG6M DECIMAL(10,3),
D2D_BAL_AMT_INV DECIMAL(17,3),
TOT_UNP_FNC_CHRG_12M DECIMAL(12,8),
AT84_SUM12M DECIMAL(14,0),
AT29_AVG6M DECIMAL(8,3),
AT41 DECIMAL(3,0),
BAL_HIST_CSH_ADV_KSCAVG12M DECIMAL(17,3),
BC33_MAX6M DECIMAL(7,0),
BNS_DLQNT_DAY_GP_KSCMAX24M DECIMAL(3,0)	,
GO11_AVG24M DECIMAL(5,2),
OVDR_CNT_SVG INTEGER,
GO04_MAX24M DECIMAL(4,0),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (MTH_TM_ID); COMMIT;

DROP TABLE EDRTLRPD1D.BASEL_CC_ACCT_SCORECRD_DRVD_VARS IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRPD1D.BASEL_CC_ACCT_SCORECRD_DRVD_VARS (
MTH_TM_ID INTEGER,   
BASEL_ACCT_ID BIGINT,
BAL_HIST_CSH_ADV_AMT DECIMAL(17,3),
FNC_CHRG_AVG24M DECIMAL(17,3),
TOT_UNP_FNC_CHRG_KSA DECIMAL(17,3),
UTIL_KSA DECIMAL (11,4),
BAL_HIST_CSH_ADV_MIN3M DECIMAL(17,3),
UTIL_KSAAVG3M DECIMAL (11,4),
BNS_DLQNT_DAY_GP_KSA DECIMAL(3,0),
UTIL_KSAAVG6M DECIMAL (11,4),
TOT_UNP_FNC_CHRG_KSAAVG6M DECIMAL(17,3),
CSH_AD_CRNT_C_BAL_KSAAVG6M DECIMAL(17,3), 
PRCH_CRNT_C_BAL_KSAMAX6M DECIMAL(17,3),
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (MTH_TM_ID); COMMIT;

/************* 4. SCORING + SEGMENTATION CHANGES ************************/
DROP TABLE EDRTLRPD1D.BASEL_RCA_SCORE_SNAPSHOT_CC_PD IF EXISTS; COMMIT; 
CREATE TABLE EDRTLRPD1D.BASEL_RCA_SCORE_SNAPSHOT_CC_PD (
MTH_TM_ID INTEGER,   
BASEL_ACCT_ID BIGINT,
BASEL_MODEL_ID INTEGER,
BASEL_MODEL_SCORECARD_HDR_ID INTEGER,
CALC_SCORE INTEGER,
INSRT_PROCESS_TMSTMP TIMESTAMP,
UPDT_PROCESS_TMSTMP TIMESTAMP )
ORGANIZE BY COLUMN
DISTRIBUTE BY HASH (MTH_TM_ID); COMMIT;

/*********** PMI + 90D + BASEL APF CHANGES INSTRUMENT FACT *******************/
/************************ SPL ********************************/
ALTER TABLE EDRTLRPD1D.BASEL_PSNL_LN_ANL_BL_INST_FACT
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN PD_90_DAY_F VARCHAR(5)
ADD COLUMN UNINSURED_LGD_SEG_NUM INTEGER
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8);

ALTER TABLE FRG_USER_DATA_DEV1.BASEL_ANALYTCL_BL_INST_FCT_BNS
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8);

ALTER TABLE FRG_USER_DATA_DEV1.BASEL_ANLYT_BL_INST_FCT_BNS_DLGD
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN PD_90_DAY_F VARCHAR(5)
ADD COLUMN UNINSURED_LGD_SEG_NUM INTEGER
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8);

ALTER TABLE FRG_USER_DATA_DEV1.BASEL_ANALYTCL_BL_INST_FCT_TNG
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8);

ALTER TABLE FRG_USER_DATA_DEV1.BASEL_ANLYT_BL_INST_FCT_TNG_DLGD
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN PD_90_DAY_F VARCHAR(5)
ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8);

ALTER TABLE FRG_USER_DATA_DEV1.BASEL_ANALYTCL_BL_INSTRMNT_FACT
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN PD_90_DAY_F VARCHAR(5)
ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8);

ALTER TABLE EDRTLRPD1D.BASEL_ANALYTCL_BL_INSTRMNT_KS
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN PD_90_DAY_F VARCHAR(5)
ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8);

ALTER TABLE EDRTLRPD1D.BASEL_ANALYTCL_BL_INSTRMNT_FACT
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN PD_90_DAY_F VARCHAR(5)
ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8);

ALTER TABLE EDRRAPT.BASEL_ANALYTCL_BL_INSTRMNT_FACT
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN LTV_BUCKET VARCHAR(30)
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN PD_90_DAY_F VARCHAR(5)
ADD COLUMN UNINSURED_LGD_SEG_NUM DOUBLE
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8);

ALTER TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_FACT_ACAP
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN DEFAULT_F CHAR(1)
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
ADD COLUMN BASEL_ACCT_ID BIGINT
ADD COLUMN PMI CHAR(1);

ALTER TABLE EDRTLRP1D.BASEL_CCAR_EXPSR_EXTR_ACAP
ADD COLUMN RNTL_PRPTY_F CHAR(1)
ADD COLUMN CURRENCY_MISMATCH_F CHAR(1)
ADD COLUMN TOT_EXPSR_ABOVE_1500K_LMT_F CHAR(1)
ADD COLUMN ORIG_AMT_LOAN DOUBLE
ADD COLUMN TRANSACTOR_F CHAR(1)
ADD COLUMN DEFAULT_F CHAR(1)
ADD COLUMN UNINSURED_LGD_RTO DECIMAL(28,8)
ADD COLUMN UNINSURED_DLGD_RTO DECIMAL(28,8)
ADD COLUMN BASEL_ACCT_ID BIGINT
ADD COLUMN PMI CHAR(1);
