--update the schema in the BIN_CRTRIA_SQL_CD_STRG column after data copy
UPDATE EDRTLRPLL.basel_seg 
SET BIN_CRTRIA_SQL_CD_STRG = REPLACE(BIN_CRTRIA_SQL_CD_STRG, 'EDRTLRP1D.', 'EDRTLRPLL.')
WHERE BIN_CRTRIA_SQL_CD_STRG LIKE '%EDRTLRP1D.%';

--update the schema in the BIN_CRTRIA_SQL_CD_STRG column after data copy
UPDATE EDRTLRPLL.BASEL_MODEL_SCORECRD_DTL 
SET BIN_CRTRIA_SQL_CD_STRG = REPLACE(BIN_CRTRIA_SQL_CD_STRG, 'EDRTLRP1D.', 'EDRTLRPLL.')
WHERE BIN_CRTRIA_SQL_CD_STRG LIKE '%EDRTLRP1D.%';