	/**************************************************
	JIRA: RRMSS-3337
	DATE: JAN 06, 2025
	CHANGE: CREATE PARALLEL RUN FOR KS
	**************************************************/

	/* NOTE: PLEASE INCLUDE THIS SCHEMA AND ALL TABLE/VIEWS AS PART OF DR */

	/* PLEASE USE SAME COLUMNS AS EDRTLRP1D FOR DISTRIBUTE BY */

CREATE TABLE EDRTLRPLL."PD_SEG_ACCT_XREF"  (
	BASEL_ACCT_ID BIGINT NOT NULL,
	MTH_TM_ID INTEGER NOT NULL,
	BASEL_SEG_ID INTEGER NOT NULL,
	BASEL_MODEL_REL_ID INTEGER NOT NULL,
	BASEL_MODEL_ID INTEGER NOT NULL,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1),
	IBMREPL_KEY BIGINT NOT NULL,
    PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
) 

CREATE TABLE EDRTLRPLL."LGD_SEG_ACCT_XREF" (
	BASEL_ACCT_ID BIGINT NOT NULL,
	MTH_TM_ID INTEGER NOT NULL,
	BASEL_SEG_ID INTEGER NOT NULL,
	BASEL_MODEL_REL_ID INTEGER NOT NULL,
	BASEL_MODEL_ID INTEGER NOT NULL,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1),
	IBMREPL_KEY BIGINT NOT NULL,
    PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
) 

CREATE TABLE EDRTLRPLL."EAD_SEG_ACCT_XREF"  (
	BASEL_ACCT_ID BIGINT NOT NULL,
	MTH_TM_ID INTEGER NOT NULL,
	BASEL_SEG_ID INTEGER NOT NULL,
	BASEL_MODEL_REL_ID INTEGER NOT NULL,
	BASEL_MODEL_ID INTEGER NOT NULL,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1),
	IBMREPL_KEY BIGINT NOT NULL,
    PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
) 

CREATE TABLE EDRTLRPLL."BASEL_RCA_SCORE_SNAPSHOT" (
	MTH_TM_ID INTEGER NOT NULL,
	BASEL_ACCT_ID BIGINT NOT NULL,
	BASEL_MODEL_ID INTEGER NOT NULL,
	BASEL_MODEL_SCORECRD_HDR_ID INTEGER NOT NULL,
	CALC_SCORE INTEGER,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1),
	IBMREPL_KEY BIGINT NOT NULL,
    PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_RCA_SCORE_DTL_SNAPSHOT" (
    BASEL_MODEL_SCORECRD_DTL_ID INTEGER NOT NULL,
    MTH_TM_ID INTEGER NOT NULL,
    BASEL_ACCT_ID BIGINT NOT NULL,
    BASEL_MODEL_ID INTEGER NOT NULL,
    BASEL_MODEL_SCORECRD_HDR_ID INTEGER NOT NULL,
    BIN INTEGER,
    PT_CNT INTEGER,
    INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
    UPDT_PROCESS_TMSTMP TIMESTAMP,
    IBMREPL_SITE CHARACTER(1) NOT NULL,
    IBMREPL_KEY BIGINT NOT NULL,
    PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
)

CREATE TABLE EDRTLRPLL."BASEL_MODEL"(
	BASEL_MODEL_ID INTEGER NOT NULL,
	MODEL_NM CHARACTER(20) NOT NULL,
	MODEL_DESC VARCHAR(255),
	MODEL_VER CHARACTER(10),
	MODEL_ST_DT DATE,
	MODEL_END_DT DATE,
	SRC_SYS_CD CHARACTER(10),
	RPTG_F CHARACTER(1),
	EAD_F CHARACTER(1),
	PD_F CHARACTER(1),
	LGD_NON_DEFAULTER_F CHARACTER(1),
	LGD_DEFAULTER_F CHARACTER(1),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_MODEL_REL"(
	BASEL_MODEL_REL_ID INTEGER NOT NULL,
	BASEL_SEG_ID INTEGER,
	BASEL_MODEL_SCORECRD_HDR_ID INTEGER,
	RPTG_USAGE_F CHARACTER(1),
	SCORECRD_VER CHARACTER(10),
	SEG_VER CHARACTER(10),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_MODEL_SCORECRD_DTL"(
	BASEL_MODEL_SCORECRD_DTL_ID INTEGER NOT NULL,
	BASEL_MODEL_SCORECRD_HDR_ID INTEGER NOT NULL,
	BIN INTEGER,
	CRTRIA_DESC VARCHAR(255),
	PT_CNT INTEGER,
	VAR_NM VARCHAR(100),
	VAR_DESC VARCHAR(255),
	BIN_CRTRIA_SQL_CD_STRG VARCHAR(2000),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_MODEL_SCORECRD_HDR"(
	BASEL_MODEL_SCORECRD_HDR_ID INTEGER NOT NULL,
	BASEL_MODEL_ID INTEGER NOT NULL,
	BASEL_SCORECRD_DESC VARCHAR(255),
	BASEL_SCORECRD_NM CHARACTER(40),
	SCORECRD_VER CHARACTER(10),
	SRC_SYS_CD CHARACTER(10),
	SCORECRD_ST_DT DATE,
	SCORECRD_END_DT DATE,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_SEG"(
	BASEL_SEG_ID INTEGER NOT NULL,
	BASEL_MODEL_ID INTEGER NOT NULL,
	BASEL_SEG_NM CHARACTER(30),
	BASEL_SEG_DESC VARCHAR(50),
	SEG_CRTRIA_DESC VARCHAR(255),
	SEG_NUM INTEGER,
	SEG_VER CHARACTER(10),
	SEG_ST_DT DATE,
	SEG_END_DT DATE,
	BIN_CRTRIA_SQL_CD_STRG VARCHAR(2000),
	SRC_SYS_CD CHARACTER(10),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_SEG_RPTG_PARM"(
	BASEL_SEG_ID INTEGER NOT NULL,
	EFF_FROM_DT DATE NOT NULL,
	BASEL_MODEL_ID INTEGER NOT NULL,
	EFF_TO_DT DATE,
	LR_RTO DECIMAL(28,8),
	LR_PV_RTO DECIMAL(28,8),
	LR_PV_AD_RTO DECIMAL(28,8),
	LR_PV_AD_SV_RTO DECIMAL(28,8),
	LR_PV_AD_SV_DT_RTO DECIMAL(28,8),
	FINAL_RTO DECIMAL(28,8),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	CRNT_F CHARACTER(1),
	LR_PV_AD_SV_DT_AA_RTO DECIMAL(28,8),
	UNADJUSTED_RPTG_RTO DECIMAL(28,8),
	SE_RTO DECIMAL(28,8),
	SE_LR_AS DECIMAL(28,8),
	SE_LR_AS_PV_AD_SV_DTC_DTS DECIMAL(28,8),
	PRE_INSURANCE_LGD DOUBLE,
	CF_ADJUSTED_RATE DECIMAL(28,8),
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."PD_BAND_DIM"(
	NCR_PD_BAND_ID INTEGER NOT NULL, 
	NCR_PD_BAND_KEY_VAL VARCHAR(4), 
	NCR_EXPSR_CL_KEY_VAL VARCHAR(4), 
	PD_MIN_VAL DECIMAL(28,8), 
	PD_MAX_VAL DECIMAL(28,8), 
	PD_MIN_VAL_DESC VARCHAR(255), 
	PD_MAX_VAL_DESC VARCHAR(255), 
	PD_BAND_EXPSR_CL_DESC VARCHAR(255), 
	NCR_PD_BAND_DESC VARCHAR(255), 
	FRS_CD VARCHAR(2), 
	PD_BAND VARCHAR(2), 
	TRANSACTOR_F VARCHAR(1), 
	CMHC_F VARCHAR(1), 
	EFF_FROM_YR_MTH VARCHAR(6), 
	EFF_TO_YR_MTH VARCHAR(6), 
	CRNT_F VARCHAR(1),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_RCA_SCORE_SNAPSHOT_CC_PD"(
	MTH_TM_ID INTEGER,
	BASEL_ACCT_ID BIGINT,
	BASEL_MODEL_ID INTEGER,
	BASEL_MODEL_SCORECARD_HDR_ID INTEGER,
	CALC_SCORE INTEGER,
	INSRT_PROCESS_TMSTMP TIMESTAMP,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."REVLVNG_CR_OBSVTN_PT_DRVD_VAR"(
	OBSVTN_MTH_TM_ID INTEGER NOT NULL,
	BASEL_ACCT_ID BIGINT NOT NULL,
	LAST_NEW_DFT_BAL_AMT DECIMAL(17,3),
	LAST_NEW_DFT_TM_ID INTEGER NOT NULL,
	LAST_NEW_DFT_DT DATE,
	MODEL_DFT_F CHARACTER(1),
	RCVRY_WINDOW_CUTOFF_TM_ID INTEGER NOT NULL,
	RCVRY_WINDOW_CUTOFF_DT DATE,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	PROCESS_MTH_TM_ID INTEGER,
	IBMREPL_SITE CHARACTER(1) NOT NULL,
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."REVLVNG_CR_MTH_ACCT_RCVRY"(
	MTH_TM_ID INTEGER NOT NULL,
	BASEL_ACCT_ID BIGINT NOT NULL,
	CRNT_OS_BAL_AMT DECIMAL(17,3),
	MTH_RCVRY_AMT DECIMAL(17,3),
	PREV_MTH_OS_BAL_AMT DECIMAL(17,3),
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	PIT_STAT_VER_2_CD CHARACTER(10),
	IBMREPL_SITE CHARACTER(1),
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

CREATE TABLE EDRTLRPLL."BASEL_ANALYTCL_BL_INSTRMNT_FACT" (
	MTH_TM_ID INTEGER NOT NULL,
	SRC_SYS_CD CHARACTER(10),
	BASEL_ACCT_ID BIGINT NOT NULL,
	UNQ_ACCT_ID CHARACTER(30),
	NCR_RT_SYS_KEY_VAL CHARACTER(4),
	NCR_PD_BAND_KEY_VAL CHARACTER(4),
	NCR_EXPSR_SIZE_KEY_VAL CHARACTER(4),
	NCR_GEO_KEY_VAL CHARACTER(4),
	NCR_LTV_KEY_VAL CHARACTER(4),
	NCR_EXPSR_CL_KEY_VAL CHARACTER(4),
	NCR_RT_KEY_VAL CHARACTER(4),
	NCR_DLQNT_BCKT_KEY_VAL CHARACTER(4),
	PIT_STAT_CD CHARACTER(10),
	UTLTN_RTO DECIMAL,
	ACCT_ODT DATE,
	TRNST_NUM CHARACTER(5),
	CR_LMT_AMT DECIMAL,
	ADVNC_AMT DECIMAL,
	AUTH_AMT DECIMAL,
	OS_BAL_AMT DECIMAL,
	GENL_LEDGER_BALCNG_ADJ_AMT DECIMAL,
	ADJUSTED_OS_BAL_AMT DECIMAL,
	UNADJUSTED_ADD_ON_BAL_AMT DECIMAL,
	AF_SECRTZTN_BAL_AMT DECIMAL,
	DLQNT_DAY_CNT SMALLINT,
	BEFORE_ZERO_NET_UNDRAWN_AMT DECIMAL,
	BEFORE_ZERO_NET_DRAWN_AMT DECIMAL,
	ORIG_PRPTY_VAL_AMT DECIMAL,
	LOAN_TO_VAL_RTO DECIMAL,
	INDEXED_PRPTY_VAL_AMT DECIMAL,
	INDEXED_LOAN_TO_VAL_RTO DECIMAL,
	PD_MODEL_NM CHARACTER(40),
	PD_MODEL_VER CHARACTER(10),
	PD_BASEL_SCORECRD_NM CHARACTER(40),
	PD_SCORECRD_VER CHARACTER(10),
	PD_BASEL_SEG_NUM INTEGER,
	PD_BASEL_SEG_ID INTEGER,
	PD_SEG_VER CHARACTER(10),
	PD_BASEL_MODEL_REL_ID INTEGER,
	PD_MODEL_RTO DECIMAL,
	PD_LR_RPTG_RTO DECIMAL,
	PD_LR_PV_RPTG_RTO DECIMAL,
	PD_LR_PV_AD_RPTG_RTO DECIMAL,
	PD_LD_PV_AD_SV_RPTG_RTO DECIMAL,
	PD_ACCT_SCORE SMALLINT,
	PD_FINAL_RPTG_RTO DECIMAL,
	LGD_MODEL_NM CHARACTER(40),
	LGD_MODEL_VER CHARACTER(10),
	LGD_BASEL_SCORECRD_NM CHARACTER(40),
	LGD_SCORECRD_VER CHARACTER(10),
	LGD_BASEL_SEG_NUM INTEGER,
	LGD_BASEL_SEG_ID INTEGER,
	LGD_SEG_VER CHARACTER(10),
	LGD_BASEL_MODEL_REL_ID INTEGER,
	LGD_MODEL_RTO DECIMAL,
	LGD_LR_RPTG_RTO DECIMAL,
	LGD_LR_PV_RPTG_RTO DECIMAL,
	LGD_LR_PV_AD_RPTG_RTO DECIMAL,
	LGD_LD_PV_AD_SV_RPTG_RTO DECIMAL,
	LGD_ACCT_SCORE SMALLINT,
	LGD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL,
	EAD_MODEL_NM CHARACTER(40),
	EAD_MODEL_VER CHARACTER(10),
	LGD_FINAL_RPTG_RTO DECIMAL,
	EAD_BASEL_SCORECRD_NM CHARACTER(40),
	EAD_SCORECRD_VER CHARACTER(10),
	EAD_BASEL_SEG_NUM INTEGER,
	EAD_BASEL_SEG_ID INTEGER,
	EAD_SEG_VER CHARACTER(10),
	EAD_BASEL_MODEL_REL_ID INTEGER,
	EAD_MODEL_RTO DECIMAL,
	EAD_LR_RPTG_RTO DECIMAL,
	EAD_LR_PV_RPTG_RTO DECIMAL,
	EAD_ACCT_SCORE SMALLINT,
	EAD_LR_PV_AD_RPTG_RTO DECIMAL,
	ASST_CL_DESC VARCHAR(255),
	CONS_DFT_MTH_CNT SMALLINT,
	EAD_LD_PV_AD_SV_RPTG_RTO DECIMAL,
	EAD_LD_PV_AD_SV_DT_RPTG_RTO DECIMAL,
	BCAR_SCHED_NUM CHARACTER(3),
	EAD_FINAL_RPTG_RTO DECIMAL,
	PD_BAND CHARACTER(10),
	BASEL_PRD_ABR VARCHAR(50),
	SCRTY_TP_DESC VARCHAR(50),
	CCAR_BASEL_PRD_TP_NM VARCHAR(50),
	CCAR_EXPSR_CL_NM CHARACTER(20),
	BASEL_PRD_TP_CD CHARACTER(20),
	CONSM_PRD_TREATMNT_CD CHARACTER(10),
	PRD_ID CHARACTER(10),
	PRIM_CUST_CID CHARACTER(20),
	ACCT_NUM CHARACTER(23),
	RGNL_OFFC_CD CHARACTER(5),
	DLQNT_STG CHARACTER(10),
	MORT_NUM CHARACTER(50),
	CAB_TRNST_NUM CHARACTER(5),
	EGL_DEPRTMNT VARCHAR(255),
	BASEL_CIF_KEY CHARACTER(69),
	LOAN_NUM CHARACTER(15),
	INTR_ACCR_AMT DECIMAL,
	CUST_BEHV_SCORE INTEGER,
	PRD_CD CHARACTER(10),
	SUB_PRD_CD CHARACTER(10),
	SRC_PRD_DESC VARCHAR(255),
	LEGAL_ENTITY CHARACTER(40),
	MAT_DT DATE,
	LAST_PYMT_DT DATE,
	SCRTY_TP_CD CHARACTER(10),
	STEP_F CHARACTER(1),
	LAST_ACTY_DT DATE,
	HOUSE_TP_NM CHARACTER(20),
	LAST_RGL_PAY_DT DATE,
	PD_OFF_F CHARACTER(1),
	PD_OFF_DT DATE,
	RESIDUAL_MAT INTEGER,
	ASST_CL_NUM SMALLINT,
	E_MAT_DT DATE,
	AMORT DECIMAL,
	TRNST_EXCLSN_F CHARACTER(1),
	SML_BUS_F CHARACTER(1),
	NOTE_DT DATE,
	INSRT_PROCESS_TMSTMP TIMESTAMP NOT NULL,
	UPDT_PROCESS_TMSTMP TIMESTAMP,
	AF_ZERO_NET_DRAWN_AMT DECIMAL,
	AF_ZERO_NET_UNDRAWN_AMT DECIMAL,
	PD_UNADJUSTED_RPTG_RTO DECIMAL,
	LGD_UNADJUSTED_RPTG_RTO DECIMAL,
	EAD_UNADJUSTED_RPTG_RTO DECIMAL,
	PD_LR_PV_AD_SV_DT_AA_RTO DECIMAL,
	LGD_LR_PV_AD_SV_DT_AA_RTO DECIMAL,
	EAD_LR_PV_AD_SV_DT_AA_RTO DECIMAL,
	INSUR_F CHARACTER(10),
	OS_PRNCPL_BAL_AMT DECIMAL,
	PREV_12_QTR_PRPTY_VAL_AMT DECIMAL,
	DLGD_F CHARACTER(1),
	CRNT_LTV_RTO DECIMAL,
	METRPL_AREA_NM VARCHAR(32),
	PRPTY_VAL_CORR_PCTG DECIMAL,
	LNG_RUN_LGD_ADD_ON_RTO DECIMAL,
	DLGD_RPTG_RTO DECIMAL,
	LTV_PERCENTAGE VARCHAR(4),
	RNTL_PRPTY_F CHARACTER(1),
	CURRENCY_MISMATCH_F CHARACTER(1),
	TOT_EXPSR_ABOVE_1500K_LMT_F CHARACTER(1),
	ORIG_AMT_LOAN DOUBLE,
	LTV_BUCKET VARCHAR(30),
	TRANSACTOR_F CHARACTER(1),
	PD_90_DAY_F VARCHAR(5),
	UNINSURED_LGD_SEG_NUM DOUBLE,
	UNINSURED_LGD_RTO DECIMAL,
	UNINSURED_DLGD_RTO DECIMAL,
	TRANSACTOR_FLAG_QRR VARCHAR(1),
	CCF DECIMAL,
	DRAWN DECIMAL,
	EAD_FLR DOUBLE,
	EAD_FLRD_RPTG_RTO DOUBLE,
	UNDRAWN DECIMAL,
	UNDRAWN_EXPSR_PCT DOUBLE,
	CMHC_F VARCHAR(1),
	DLGD_FLR DOUBLE,
	FULLY_SECURED_F VARCHAR(1),
	LGD_FLR DOUBLE,
	PRE_INSURANCE_LGD DOUBLE,
	PD_FLR DOUBLE,
	PD_FLRD_RPTG_RTO DOUBLE,
	LGD_FLRD_RPTG_RTO DOUBLE,
	PMI_LGD_INSURED_RPTG_RTO DOUBLE,
	PMI_LGD_UNADJUSTED_RPTG_RTO DECIMAL,
	UNINSURED_FLRD_LGD_RTO DOUBLE,
	PD_BAND_EXPSR_CL_KEY_VAL VARCHAR(4),
	DLGD_RPTG_RTO_OLD DECIMAL,
	CCAR_F INTEGER,
	CLP_FLAG CHARACTER(1),
	BCAR_SCHED_NM VARCHAR(150),
	BCAR_SCHED_NUM_50 VARCHAR(10),
	COLLATERAL_TYPE VARCHAR(50),
	H_C DECIMAL,
	LGD_S DECIMAL,
	LGD_U DECIMAL,
	H_E DECIMAL,
	COLLATERAL_VALUE DECIMAL,
	EXPOSURE DOUBLE,
	EXPOSURE_SECURED_MAXIMUM DOUBLE,
	EXPOSURE_SECURED DOUBLE,
	EXPOSURE_UNSECURED DOUBLE,
	WEIGHT_SECURED DOUBLE,
	WEIGHT_UNSECURED DOUBLE,
	IBMREPL_SITE CHARACTER(1),
	IBMREPL_KEY BIGINT NOT NULL,
	PRIMARY KEY (IBMREPL_KEY,IBMREPL_SITE)
);

--VIEWS--
--VIEWS FOR IFRS9
CREATE VIEW	  EDRTLRPLL.BASEL_MORT_MTH_SNAPSHOT	AS SELECT * FROM EDRTLRP1D.BASEL_MORT_MTH_SNAPSHOT;
CREATE VIEW	  EDRTLRPLL.BASEL_PNL_LN_LGD_SEG_ACCT_XREF	AS SELECT * FROM EDRTLRP1D.BASEL_PNL_LN_LGD_SEG_ACCT_XREF;
CREATE VIEW   EDRTLRPLL.BASEL_PNL_PD_SEG_XREF_IFRS_V    AS SELECT * FROM EDRTLRP1D.BASEL_PNL_LN_PD_SEG_ACCT_XREF ;
CREATE VIEW	  EDRTLRPLL.BASEL_PSNL_LN_INST_FACT_IFRS_V 	AS SELECT * FROM EDRTLRP1D.BASEL_PSNL_LN_ANL_BL_INST_FACT; 
CREATE VIEW	  EDRTLRPLL.BASEL_PSNL_LOAN_ACCT_DRVD_VARS	AS SELECT * FROM EDRTLRP1D.BASEL_PSNL_LOAN_ACCT_DRVD_VARS;
CREATE VIEW	  EDRTLRPLL.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2	AS SELECT * FROM EDRTLRP1D.BASEL_PSNL_LOAN_ACCT_DRVD_VARS_2;
CREATE VIEW	  EDRTLRPLL.BASEL_PSNL_LOAN_MTH_SNAPSHOT	AS SELECT * FROM EDRTLRP1D.BASEL_PSNL_LOAN_MTH_SNAPSHOT;
CREATE VIEW	  EDRTLRPLL.IFRS9_PROV_LKP	AS SELECT * FROM EDRTLRP1D.IFRS9_PROV_LKP;
CREATE VIEW	  EDRTLRPLL.ORG_UNIT_DIM	AS SELECT * FROM EDRTLRP1D.ORG_UNIT_DIM;
CREATE VIEW	  EDRTLRPLL.PSNL_LOAN_OBSVTN_PT_DRVD_VAR	AS SELECT * FROM EDRTLRP1D.PSNL_LOAN_OBSVTN_PT_DRVD_VAR;
CREATE VIEW	  EDRTLRPLL.psnl_loan_rptg_prd_lkp	AS SELECT * FROM EDRTLRP1D.psnl_loan_rptg_prd_lkp;


--input tables for parallel run
CREATE VIEW EDRTLRPLL.BASEL_ACCT_DIM AS SELECT * FROM EDRTLRP1D.BASEL_ACCT_DIM ;
CREATE VIEW EDRTLRPLL.BASEL_CUST_DIM AS SELECT * FROM EDRTLRP1D.BASEL_CUST_DIM ;
CREATE VIEW EDRTLRPLL.BASEL_CUST_ACCT_RLTNP_SNAPSHOT AS SELECT * FROM EDRTLRP1D.BASEL_CUST_ACCT_RLTNP_SNAPSHOT ;
CREATE VIEW EDRTLRPLL.BASEL_REVLVNG_CR_MTH_SNAPSHOT AS SELECT * FROM EDRTLRP1D.BASEL_REVLVNG_CR_MTH_SNAPSHOT ;
CREATE VIEW EDRTLRPLL.BASEL_STEP_PLN_MTH_SNAPSHOT AS SELECT * FROM EDRTLRP1D.BASEL_STEP_PLN_MTH_SNAPSHOT ;
CREATE VIEW EDRTLRPLL.ASST_DRC_COST_MTH_SNAPSHOT AS SELECT * FROM EDRTLRP1D.ASST_DRC_COST_MTH_SNAPSHOT ;
CREATE VIEW EDRTLRPLL.MBR_INDRCT_COST_MTH_SNAPSHOT AS SELECT * FROM EDRTLRP1D.MBR_INDRCT_COST_MTH_SNAPSHOT ;
CREATE VIEW EDRTLRPLL.BASEL_ACCT_PRFM_FACT AS SELECT * FROM EDRTLRP1D.BASEL_ACCT_PRFM_FACT;
CREATE VIEW EDRTLRPLL.AUDIT_JOB_TIMER_CHECK AS SELECT * FROM EDRTLRP1D.AUDIT_JOB_TIMER_CHECK;
CREATE VIEW EDRTLRPLL.BASEL_CUST_MTH_DEP_TXN_SUM AS SELECT * FROM EDRTLRP1D.BASEL_CUST_MTH_DEP_TXN_SUM;
CREATE VIEW EDRTLRPLL.BASEL_CUST_MTH_POSTN_SUM_FACT AS SELECT * FROM EDRTLRP1D.BASEL_CUST_MTH_POSTN_SUM_FACT;
CREATE VIEW EDRTLRPLL.CR_BUREAU_DELI_MTH_SNAPSHOT AS SELECT * FROM EDRTLRP1D.CR_BUREAU_DELI_MTH_SNAPSHOT;
CREATE VIEW EDRTLRPLL.BASEL_CC_ACCT_SCORECRD_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_CC_ACCT_SCORECRD_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_CC_CUST_SCORECRD_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_CC_CUST_SCORECRD_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_REVLVNG_CR_ACCT_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_REVLVNG_CR_ACCT_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_REVLVNG_CR_BASE_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_REVLVNG_CR_BASE_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_CUST_SCORECRD_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_CUST_SCORECRD_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_CC_LOC_CUST_SCORECRD_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_CC_LOC_CUST_SCORECRD_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_CC_LOC_REVLVNG_CR_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_CC_LOC_REVLVNG_CR_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_STEP_SCORECRD_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_STEP_SCORECRD_DRVD_VARS;
CREATE VIEW EDRTLRPLL.BASEL_STEP_PLN_BASE_DRVD_VARS AS SELECT * FROM EDRTLRP1D.BASEL_STEP_PLN_BASE_DRVD_VARS;
CREATE VIEW EDRTLRPLL.DRVD_MTH_ASST_DRC_COST AS SELECT * FROM EDRTLRP1D.DRVD_MTH_ASST_DRC_COST;
CREATE VIEW EDRTLRPLL.DRVD_MTH_DRC_COST AS SELECT * FROM EDRTLRP1D.DRVD_MTH_DRC_COST;
CREATE VIEW EDRTLRPLL.TM_DIM AS SELECT * FROM EDRTLRP1D.TM_DIM; 
CREATE VIEW EDRTLRPLL.BASEL_MORT_ACCT_DRVD_VARS AS SELECT* FROM EDRTLRP1D.BASEL_MORT_ACCT_DRVD_VARS;

--views from PLL schema for IFRS
CREATE VIEW EDRTLRPLL.BASEL_SEG_IFRS_V AS SELECT * FROM EDRTLRPLL.BASEL_SEG;
CREATE VIEW EDRTLRPLL.LGD_SEG_ACCT_XREF_IFRS_V AS SELECT * FROM EDRTLRPLL.LGD_SEG_ACCT_XREF;
CREATE VIEW EDRTLRPLL.PD_SEG_ACCT_XREF_IFRS_V AS SELECT * FROM EDRTLRPLL.PD_SEG_ACCT_XREF;