/* SQL SCRIPT CHANGES FOR BASEL III *
/* Created by: N Grewal */
/* Last Modified: Oct 20, 2022 */

/* ******************************************************************* */
/* DIMENSION TABLES INCLUDING SCORING & SEGMENTATION */
DELETE FROM EDRTLRPD1D.BASEL_MODEL_SCORECRD_DTL WHERE BASEL_MODEL_SCORECRD_HDR_ID in (8025,8026,8027); /*cc pd* - new */

UPDATE EDRTLRPD1D.BASEL_MODEL_SCORECRD_DTL SET BIN_CRTRIA_SQL_CD_STRG = null, updt_process_tmstmp = sysdate WHERE BASEL_MODEL_SCORECRD_HDR_ID=8004; /*cc pd*/
UPDATE EDRTLRPD1D.BASEL_MODEL_SCORECRD_DTL SET BIN_CRTRIA_SQL_CD_STRG = null, updt_process_tmstmp = sysdate WHERE BASEL_MODEL_SCORECRD_HDR_ID=8002; /*cc lgdd*/
UPDATE EDRTLRPD1D.BASEL_MODEL_SCORECRD_DTL SET BIN_CRTRIA_SQL_CD_STRG = null, updt_process_tmstmp = sysdate WHERE BASEL_MODEL_SCORECRD_HDR_ID=8003; /*cc lgdnd*/

Copy following tables from DEV to PROD-
1. BASEL_MODEL
2. BASEL_MODEL_REL
3. BASEL_MODEL_SCORECRD_HDR
4. BASEL_MODEL_SCORECRD_DTL /* REPLACE EDRTRPD1D WITH EDRTLRP1D */
5. BASEL_SEG    			/* REPLACE EDRTRPD1D WITH EDRTLRP1D */

UPDATE EDRTLRPD1D.BASEL_MODEL_SCORECRD_DTL SET BIN_CRTRIA_SQL_CD_STRG = REPLACE(BIN_CRTRIA_SQL_CD_STRG, 'EDRTLRD1D', 'EDRTLRPD1D');
UPDATE EDRTLRPD1D.BASEL_MODEL_SCORECRD_DTL SET BIN_CRTRIA_SQL_CD_STRG = REPLACE(BIN_CRTRIA_SQL_CD_STRG, 'EDRTLRP1D', 'EDRTLRPD1D'); /* FOR DEV ONLY */

UPDATE EDRTLRPD1D.BASEL_SEG SET BIN_CRTRIA_SQL_CD_STRG = REPLACE(BIN_CRTRIA_SQL_CD_STRG, 'EDRTLRD1D', 'EDRTLRPD1D');
UPDATE EDRTLRPD1D.BASEL_SEG SET BIN_CRTRIA_SQL_CD_STRG = REPLACE(BIN_CRTRIA_SQL_CD_STRG, 'EDRTLRP1D', 'EDRTLRPD1D'); /* FOR DEV ONLY */


/* BASEL_SEG_RPTG_PARM - RUN AFTER THE NEW FILE IS LOADED */
/* Manually deactivate deleted segments */
UPDATE edrtlrpd1d.basel_Seg_rptg_parm SET EFF_TO_DT = '2022-06-30' WHERE BASEL_SEG_ID IN (16049,16053,16054) AND EFF_TO_DT = '9999-12-31';