[global]
; Global settings for dag generators
functions_dir = /bns/rrap/apps/rebuild-airflow/functions

[feature_map]
; Structure map specific to feature_dag_generator
reference = static
ingestion = raw,cleaned
features = derived,realized

[feature_dependencies]
; Cross-dag dependencies specific to feature_dag_generator
features = ingestion,reference

[stream_map]
; Structure map specific to stream_dag_generator
model = scored,segmented
instrument = variable,fact
reporting = ccar,dq,dt4,ncr,exception,securitization
reference = dynamic
emulated = filteredtable
cbs = custuniv

[stream_dependencies]
; Cross-dag dependencies specific to stream_dag_generator
model = features
instrument = model
reporting = instrument
emulated = features
cbs = emulated