/*******************************************************************************************/
Deployment Date: MARCH 22, 2024, 7:00 AM to 4:00 PM
CHANGE TICKET: CHG0828669
CHANGE: Basel III Reform
Database: DM1P1D
Note: No dependency
/*******************************************************************************************/

--1. Back Up EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT

create table EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT_bkp_20240322 as (select * from EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT) with data; commit;


--2. Alter table for 5 columns, execute REORG on table as required

ALTER TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT ALTER COLUMN EXPSR_CL_KEY_VAL SET DATA TYPE VARCHAR(15);
ALTER TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT ALTER COLUMN BCAR_SCHED_NUM SET DATA TYPE VARCHAR(255);
ALTER TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT ALTER COLUMN ADJUSTED_OS_BAL_AMT SET DATA TYPE DECIMAL(17,0);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT');
ALTER TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT ALTER COLUMN ESTD_EAD_AMT SET DATA TYPE DECIMAL(17,0);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT');
ALTER TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT ALTER COLUMN IRB_EXPCTD_LOSS_AMT SET DATA TYPE DECIMAL(17,0);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EDRRAPT.BASEL_NCR_BCAR_ATTESTTN_FACT');


/************************************* END OF SCRIPT ***************************************/